### ISSUE TITLE
(JS-0336) Avoid using promises in places not designed to handle them

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1001]
## Description
Using promises is forbiddedn in places where the TypeScript compiler allows them but they are not handled properly. These situations can often arise due to a missing await keyword or just a misunderstanding of the way async functions are handled/awaited. Example - The not-preferred way :

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ToolJet/ToolJet/issue/JS-0336/occurrences/](https://deepsource.io/gh/ToolJet/ToolJet/issue/JS-0336/occurrences/)

**Comment by heytulsiprasad** [comment]
I think I got the solution for this too, would be an easy fix. Mind if I raise a PR?
