### ISSUE TITLE
(JS-0050) Avoid use of `==` and `!=`

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1002]
## Description
It is considered good practice to use the type-safe equality operators `===` and `!==` instead of their regular counterparts `==` and `!=`. If one of those occurs in an innocent-looking statement such as `a == b` the actual problem is very difficult to spot.

## Occurrences
There are 35 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ToolJet/ToolJet/issue/JS-0050/occurrences/](https://deepsource.io/gh/ToolJet/ToolJet/issue/JS-0050/occurrences/)

**Comment by heytulsiprasad** [comment]
Hey @Navaneeth-pk, just came across ToolJet and loving the features already! I'll be happy to take care of this 💙

**Comment by Navaneeth-pk** [comment]
Thanks, assigned the issue!
@heytulsiprasad
