### ISSUE TITLE
[docs] : For RestAPI data source define when retry happens with status codes and their description

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#10022]
In continuation to #9876 

To facilitate documentation for this feature, need to add the following in the doc:

Add a screenshot of feature described in the issue mentioned with the following details

By default, it retries only on the specified methods, status codes (408, 413, 429, 500, 502, 503, 504, 521, 522, 524), and on these network errors:
ETIMEDOUT: One of the timeout limits were reached.
ECONNRESET: Connection was forcibly closed by a peer.
EADDRINUSE: Could not bind to any free port.
ECONNREFUSED: Connection was refused by the server.
EPIPE: The remote side of the stream being written has been closed.
ENOTFOUND: Couldn’t resolve the hostname to an IP address.
ENETUNREACH: No internet connection.
EAI_AGAIN: DNS lookup timed out.

**Comment by amanregu** [comment]
Added under https://github.com/ToolJet/ToolJet/pull/10415
https://github.com/ToolJet/ToolJet/pull/10415/commits/402d6b4eb66f176a7b1d970044b239c2bd943b44
