### ISSUE TITLE
(JS-0306) Missing explicit return and argument types

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1003]
## Description
Explicit types are considered in three ways: - It serves as self-documenting code - It guard against bugs in function implementation - It acknowledge and change the explicit return type on the function signature

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ToolJet/ToolJet/issue/JS-0306/occurrences/](https://deepsource.io/gh/ToolJet/ToolJet/issue/JS-0306/occurrences/)

**Comment by alammoiz** [comment]
Here is my PR, please review https://github.com/ToolJet/ToolJet/pull/1014 @Navaneeth-pk
