### ISSUE TITLE
(JS-D009) Prefer ternary operator

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1004]
## Description
Using an `if-else` statement typically results in more lines of code than a single-line ternary expression, which leads to an unnecessarily larger codebase that is more difficult to maintain. Additionally, using an `if-else` statement can result in defining variables using `let` or `var` solely to be reassigned within the blocks. …

## Occurrences
There are 6 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ToolJet/ToolJet/issue/JS-D009/occurrences/](https://deepsource.io/gh/ToolJet/ToolJet/issue/JS-D009/occurrences/)

**Comment by dazzlerkumar** [comment]
@Navaneeth-pk How are you? I hope you're vaccinated. 
You can assign me this task.
