### ISSUE TITLE
Replace Delete link with trash icon and add loading animation(s)

### ISSUE THREAD

**Issue by AlexandruValeanu** [ToolJet/ToolJet#1007]
### Is your proposal related to a problem?

Follow up from https://github.com/ToolJet/ToolJet/issues/985. Group deletions are a simple Delete link with no progress indication involved.

### Describe the solution you'd like

Change the following Delete links to trash icons and add loading state (and/or pop-up to notify that the deletion is ongoing).

https://user-images.githubusercontent.com/11629675/136826814-a03d1e46-10dc-44fe-8c49-ecd983fcaaf5.png

https://user-images.githubusercontent.com/11629675/136827076-16493c4e-3af9-496e-8764-df7eeb826b9a.png

https://user-images.githubusercontent.com/11629675/136827156-07109a83-7cde-41a5-80e4-ac27732efc32.png

### If the feature is approved, would you be willing to submit a PR?

Yes, the PR is more or less ready.

**Comment by rutulganatra** [comment]
Hey, Can I work on this issue under hactoberfest label?

**Comment by luharuka** [comment]
hey @Navaneeth-pk can you tell me in tooljet which issue is for beginners actually no one issue in tooljet is done by me after a lot of searches is this only for professional

**Comment by withshubh** [comment]
Duplicate of https://github.com/ToolJet/ToolJet/issues/985
