### ISSUE TITLE
[dark mode]: fix color of time selection box in datepicker

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10087]
### What is the current behaviour?
When using the Datepicker component in ToolJet and enabling the "Enable Time selection" option, there is a UI issue when expanding the time section. The UI is not adopting Dark mode.

### How to reproduce the issue?
1. Switch to dark mode
2. drag a datepicker
3. enable time selection from datepicker property
4. Check the color of the Time selection box

### Screenshots or Screencast
<img width="464" alt="image" src="https://github.com/ToolJet/ToolJet/assets/77957844/aa8da99c-33ec-4dba-8ac8-929a40a3098a">

**Comment by albonwu** [comment]
interested in working on this - can you assign it to me?

**Comment by PriteshKiri** [comment]
Assigned @albonwu. Happy coding :)

**Comment by PriteshKiri** [comment]
Hey @albonwu any updates on this?

**Comment by ShyanRoyChoudhury** [comment]
Hi. If there's no response can I work on this issue?

**Comment by albonwu** [comment]
Hi, sorry for the late response.

It looks like the datepicker component uses react-datepicker, which uses the native HTML date picker. I've looked into it and [styling the time input field](https://stackoverflow.com/a/16106788) is the closest I've come to a cross-browser way to style the time selection box. I haven't yet found a way to change the theme of the component's popup.

**Comment by Sanil-Surve** [comment]
Hey can I work on this issue because I have solution to tackle this issue so can you assign to me?

**Comment by PriteshKiri** [comment]
Hey @albonwu ,

Looping @johnsoncherian in to help you with the issue.

**Comment by PriteshKiri** [comment]
@ShyanRoyChoudhury @Sanil-Surve we have these two issues open for the community. Feel free to check them out.

1. https://github.com/ToolJet/ToolJet/issues/6818
2. https://github.com/ToolJet/ToolJet/issues/10132

**Comment by PriteshKiri** [comment]
Hey @albonwu , are you still working on this issue?

**Comment by Sanil-Surve** [comment]
Hey @PriteshKiri,  Can you assign different issue so I work on it other than above issues of the community.

**Comment by albonwu** [comment]
@PriteshKiri Sorry, I've been having trouble with this one. I'm happy to let @Sanil-Surve take over if he has a solution.

**Comment by PriteshKiri** [comment]
@Sanil-Surve are you still interested in working on this issue?

**Comment by harshit078** [comment]
Hi @PriteshKiri , Can I take this issue up ?

**Comment by PriteshKiri** [comment]
Hey @harshit078, 

Let's wait for @Sanil-Surve to respond. 

Meanwhile, you can take up any of the open issues. Sharing it here 
https://github.com/ToolJet/ToolJet/issues/9953

**Comment by Sanil-Surve** [comment]
Yes I can Contribute to it.

**Comment by PriteshKiri** [comment]
Assigned @Sanil-Surve. Happy coding :)

**Comment by PriteshKiri** [comment]
Hey @Sanil-Surve. Any updates on the issue?

**Comment by Sanil-Surve** [comment]
I'm working on issue and I think it can resolve till tonight.

**Comment by PriteshKiri** [comment]
Hey @Sanil-Surve, Any updates on the issue?

**Comment by Sanil-Surve** [comment]
> Hey @Sanil-Surve, Any updates on the issue?

I've found out where the issue created but I'm getting some difficulties in setting up the application

**Comment by PriteshKiri** [comment]
@Sanil-Surve can you ask your queries about the setup in the contributor's channel? Here is the link to join our [Slack community](https://tooljet.slack.com/archives/C05SSQF138F/p1717070821941189)

**Comment by Sanil-Surve** [comment]
Ok, I will check.

**Comment by GivenBY** [comment]
Hi @PriteshKiri, I have resolved the issue. Can I take it up?

**Comment by PriteshKiri** [comment]
@GivenBY will wait for @Sanil-Surve to respond with an update on the issue. You can check other issues or you can contribute to our templates as well, sharing them here.

https://github.com/ToolJet/ToolJet/issues/9923
https://github.com/ToolJet/ToolJet/issues/9924

**Comment by PriteshKiri** [comment]
Hey @Sanil-Surve, any updates on this?

**Comment by Sanil-Surve** [comment]
I've made changes to the codebase but not able to make PR so can you grant
permission to me.

**Comment by Sanil-Surve** [comment]
> Hey @Sanil-Surve, any updates on this?
Hey @PriteshKiri !
I am not able to reproduce the issue because of that I've difficulty to contribute so you can assign it to @GivenBY

**Comment by PriteshKiri** [comment]
Okay @Sanil-Surve

**Comment by GivenBY** [comment]
Hey @PriteshKiri, can you assign me

**Comment by PriteshKiri** [comment]
@GivenBY assiged. Happy coding.

**Comment by PriteshKiri** [comment]
Thanks for your contribution @GivenBY. Moving the issue to review.
