### ISSUE TITLE
ReferenceError: onComponentClick is not defined

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1008]
### How to reproduce the issue?

1. log in to ToolJet
2. Open `console` from developer tools (Chrome)
3. Create a Folder 

**Error**:  when clicked on the input field
```
Uncaught ReferenceError: onComponentClick is not defined
```

### Screenshots or Screencast

https://user-images.githubusercontent.com/67645175/137094825-0faded10-41de-48d0-b9f3-0225677587db.mov

### Any possible solutions?
Removing the `onClick` event from the input field.
```
onComponentClick, id and component is not defined
```

### Can you identify the location in the driver source code where the problem exists?
`frontend > src > HomePage > Folders.jsx > line 102`

Also, remove the eslint comment.

**Comment by alammoiz** [comment]
Please assign to me @arpitnath

**Comment by arpitnath** [comment]
Hi, @nguyenhung15913. Our policy is FCFS, and this issue is already assigned to @alammoiz, inviting you to explore the other issues @nguyenhung15913
