### ISSUE TITLE
SMTP does not support secure configuration, when the port is 465

### ISSUE THREAD

**Issue by AviorAlong** [ToolJet/ToolJet#1010]
**This is the configuration of tooljet**
![image](https://user-images.githubusercontent.com/18592408/137116832-6eeff771-6153-466f-9653-d3922acfc7e4.png)

**This is the configuration of nodemailer**
![image](https://user-images.githubusercontent.com/18592408/137117523-ad198b43-051b-4c9a-b59a-6131b2f08ea9.png)

**Comment by dluk** [comment]
Please assign it to me
