### ISSUE TITLE
Event handlers gets unattached and disappears randomly.

### ISSUE THREAD

**Issue by johnsoncherian** [ToolJet/ToolJet#10150]
### Version Information
LTS EE
### What is the expected behaviour?
Event handlers associated with action button should persist even after version update or migration and should not be removed unless user deletes is
### What is the current behaviour?
As per user the Event handlers gets unattached and disappears randomly.
### How to reproduce the issue?
NA

### Please provide any traces or logs that could help here.
https://tooljet.slack.com/archives/C06U9EJCQRK/p1718905519125299

Duplicate - https://github.com/ToolJet/tj-ee/issues/1643

**Comment by DevangAgarwal93** [comment]
We are not able to replicate this issue.

**Comment by DevangAgarwal93** [comment]
Duplicate- https://github.com/ToolJet/tj-ee/issues/1643
