### ISSUE TITLE
SelectedRow is working differently for Checkbox selection & Row selection

### ISSUE THREAD

**Issue by DevangAgarwal93** [ToolJet/ToolJet#10154]
selectedRow is working differently for:
1. Checkbox selection, &
2. Row selection

When we're using checkbox, when unselected, it's removing the value from selectedRow. But, when we're selecting a row twice, the checkbox shows unselected, but actually the value of selectedRow still remains.

Slack: https://tooljet.slack.com/archives/C02QT13RF51/p1719224407513639

**Comment by johnsoncherian** [comment]
This isssue is fixed in Tooljet 3.0
