### ISSUE TITLE
Support passing data source connection URLs to ToolJet server as environment variables

### ISSUE THREAD

**Issue by somesocks** [ToolJet/ToolJet#1023]
### Is your proposal related to a problem?

When self-hosting a containerized service like ToolJet, you often want to copy the service "metadata" (data source / application parameters) between development / staging / production environments, so that your development instance of ToolJet is identical to your production instance.

What makes this difficult is data source parameters, especially credentials.  You can't export your service metadata from a development instance (in ToolJet's case a PG database dump), and import it into your production database because the connection parameters and credentials for your data sources will still be pointing to the data sources you use in development, which are often test datasets.

### Describe the solution you'd like

Hasura (hasura.io) has implemented an elegant solution to this problem by allowing you to specify that connection parameters to your database will be provided by a custom environment variable.  Then you can provide connection parameters for a certain data source to the docker container at runtime using an environment variable.

This allows you to keep your metadata "platform agnostic" so you can more easily share service metadata between development and production deployments.  It's also better from a security perspective; it gives you the option to keep your credentials secured in a external secrets manager like a kubernetes secrets store, and it allows you to more easily rotate out credentials without having to update your ToolJet configuration.

I've attached a screenshot from a testing Hasura dashboard, so you can see how the option is presented:
![hasura-data-source-snapshot](https://user-images.githubusercontent.com/1326765/137215972-ad03cbf3-496a-4e9d-ad57-3e175db0657c.jpg)

They also discuss it in this blog post: https://hasura.io/blog/moving-from-local-development-staging-production-with-hasura/

### Describe alternatives you've considered

I think Hasura really nailed it with this solution, I can't think of any better way of solving this problem.  They even state that this is their recommended way of handling config URLs.

### If the feature is approved, would you be willing to submit a PR?

Sure, I don't mind implementing it, though I'd appreciate some help to navigate the codebase.

**Comment by Navaneeth-pk** [comment]
Thanks for raising the feature request. We will look into this and update the thread soon.
@somesocks

**Comment by withshubh** [comment]
Hey @somesocks - Thanks for creating the issue. 🙌 

We recently releases workspace variables that can be used to pass the data source connection URLs to ToolJet server as environment variables.
You can check the documentation here: https://docs.tooljet.com/docs/tutorial/workspace-environment-variables/

Feel free to join the [slack community](https://tooljet.com/slack) if you have any questions.

Closing the issue.
