### ISSUE TITLE
Minor bug: reset password page

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1025]
![image](https://user-images.githubusercontent.com/7828962/137252241-e68de5c9-3330-4402-8965-ec5e05a80072.png)

The text on the button should be "Reset password"

**Comment by Navaneeth-pk** [comment]
No worries, assigned the issue. 
Please read our contributing guide for more information on contributing: https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md

Thanks for contributing to ToolJet!
@HVbajoria

**Comment by HVbajoria** [comment]
Thank you for accepting. 
Happy Hacktoberfest.
