### ISSUE TITLE
User group titles not visible in dark mode

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1027]
![image](https://user-images.githubusercontent.com/7828962/137253039-0ec44be0-a0a4-4f8d-b964-7ca04e66a526.png)

The contents of the table are not visible in dark mode.

**Comment by Navaneeth-pk** [comment]
Thanks for contributing again!
@RajMhatre20

**Comment by RajMhatre20** [comment]
My Pleasure, What color do you want me to set it to?
