### ISSUE TITLE
Permissions radio buttons not visible in dark mode

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1029]
![image](https://user-images.githubusercontent.com/7828962/137253390-4bea93d8-17fd-4696-af2c-ad6b393807fc.png)

The labels of the radio buttons for changing the permission is not visible in dark mode.

**Comment by ManishS6** [comment]
@Navaneeth-pk I would like to work on this. 
Please assign me

**Comment by JuniorS6** [comment]
@Navaneeth-pk I would like to work on this
