### ISSUE TITLE
Hover on one table triggers tooltip on all nearby tables

### ISSUE THREAD

**Issue by amanregu** [ToolJet/ToolJet#10291]
### Environment

ToolJet Cloud

### What is the expected behaviour?

When hovering over a single table in the canvas, only a tooltip associated with that specific table should be displayed.

### What is the current behaviour?

When hovering over the action elements (Add new row, Download, Manage Columns) on a single table in the canvas, the intended tooltip for that table appears alongside unexpected tooltips from adjacent(one cell or less than one cell, upto 4 cells incase of Manage Columns) tables. **This does NOT affect the functionality as the button click works as expected**.

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/48810579/4892536d-9445-485f-b770-bceab0fb2220

**Comment by PriteshKiri** [comment]
Hey @maxdiplogit ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.
