### ISSUE TITLE
Empty text field values are filled with "ToolJet is an open-source low-code platform [...] 🚀"

### ISSUE THREAD

**Issue by stouch** [ToolJet/ToolJet#10314]
### Environment
docker: v2.64.0

### What is the current behaviour?

I got text fields components that are used in a API query.
Their values are filled with  `ToolJet is an open-source low-code platform for building and deploying internal tools with minimal engineering efforts 🚀` when they are empty.

(see screenshots)
<img width="982" alt="Capture d’écran 2024-07-09 à 22 47 17" src="https://github.com/ToolJet/ToolJet/assets/17531455/d2853c35-2382-471b-a575-b02211ac7849">

<img width="609" alt="Capture d’écran 2024-07-09 à 22 47 01" src="https://github.com/ToolJet/ToolJet/assets/17531455/154a725f-0d57-4a3d-9c92-6c73d0c600fe">

This breaks a lot of things we use on our Tooljet platform..

**Comment by PriteshKiri** [comment]
Closing as the fix for this is merged
