### ISSUE TITLE
The placeholder for number input should be changed

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1034]
![image](https://user-images.githubusercontent.com/7828962/137263807-6da282b5-095b-4b34-ac54-d098da33cbc7.png)

The default placeholder for the number input widget should be the number `1000`.

**Comment by HVbajoria** [comment]
Hello @Navaneeth-pk ,
I can fix this issue now. Could you please assign me.
Thank you

**Comment by Navaneeth-pk** [comment]
Sorry, this issue was already fixed. Closing.
