### ISSUE TITLE
Fix alignment issue for MS SQL server data source

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1036]
![image](https://user-images.githubusercontent.com/7828962/137265738-c0aa3840-988b-44b7-8f17-a1d815631d47.png)

Steps to reproduce: 
- Click on datasources icon on the left sidebar
- Click on add new data source button
- Select MS SQL server 
- The top margin of the toggle for `Azure` option is inconsistent with the rest of the modal.

**Comment by mtwn105** [comment]
Hi @Navaneeth-pk can I do this?

**Comment by mtwn105** [comment]
Hi @Navaneeth-pk Opened PR #1120
