### ISSUE TITLE
Base URL of REST API data sources is not consistent in dark mode

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1037]
![image](https://user-images.githubusercontent.com/7828962/137268280-a630e1dd-e6e1-425f-8fcf-7a0940fc570a.png)
The disabled field for the base URL of the endpoint should be dark. 

Steps to reproduce: 
a) Create a new REST API datasource
b) Create a new query with the data source created in previous step as the source

**Comment by aloks98** [comment]
Would like to take this up. Please assign me, thanks! :)
