### ISSUE TITLE
[Bug] The app crashes when adding moment().format() manually by typing in add row operation in TJDB queries

### ISSUE THREAD

**Issue by DevangAgarwal93** [ToolJet/ToolJet#10414]
Also a common issue on every codehinter field.

https://github.com/user-attachments/assets/828547ce-7b33-487e-b5e5-f38150316e45

**Comment by punitive1729** [comment]
@DevangAgarwal93 assign the task to me

**Comment by punitive1729** [comment]
@DevangAgarwal93 raised a PR related to the issue
