### ISSUE TITLE
Marker color and 'show grid lines' options are not required for pie chart

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#1042]
### Environment

Ubuntu Linux 20.04
### What is the expected behaviour?

When user adds a chart and sets its type to 'Pie chart', there should be no configuration options for 'Marker colour' and 'show grid lines' as they are not relevant for pie chart.

### What is the current behaviour?

Configuration options for 'Marker colour' and 'show grid lines' are shown for Pie chart
### How to reproduce the issue?

1.  Add a chart
2. Set its type to pie chart
3. Observe inspector panel

**Comment by MohsinNajmuddin** [comment]
@Navaneeth-pk @sherfin94 can you please assign it to me

**Comment by MohsinNajmuddin** [comment]
@Navaneeth-pk @sherfin94 I have fixed the issue. Raised the PR for it. Link: #1182 

Please review and merge
