### ISSUE TITLE
[BUG]: Text and Background Color Visibility in Dark Mode

### ISSUE THREAD

**Issue by CuriousCoder00** [ToolJet/ToolJet#10456]
### Version Information
Version: 2.50.0-LTS or any other version
### What is the expected behaviour?
In dark mode, text should remain readable with sufficient contrast, and the background color should adjust to a darker shade to enhance readability.

### What is the current behaviour?
In dark mode, the text becomes difficult to read due to insufficient contrast, and the background color does not appropriately adjust to a darker shade. This issue is particularly noticeable when the window size is decreased.

### How to reproduce the issue?

1. Open the documentation section in a web browser.
2. Switch to dark mode.
3. Decrease the window size.
4. Observe the text and background color in the documentation.

### Screenshots or Screencast
![image](https://github.com/user-attachments/assets/9b51088a-ab76-4abf-8223-588d55cf8045)
![image](https://github.com/user-attachments/assets/cf4f6cc9-547e-41f1-96d7-80a5907a506b)
![image](https://github.com/user-attachments/assets/4a564926-9088-4c60-9b43-29bc26fbc6d7)

### Please provide any traces or logs that could help here.
N/A

### Any possible solutions?
the text color in dark mode should provide sufficient contrast against the background.
a darker background color in dark mode to enhance text visibility.
the styles should be responsive and maintain readability across different screen sizes.

### Can you identify the location in the driver source code where the problem exists?
The issue likely exists in the CSS files responsible for styling the documentation section in dark mode.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by 91FAhmed** [comment]
Is anyone working on this PR

**Comment by CuriousCoder00** [comment]
I would like to work on it myself.. 😅

**Comment by 91FAhmed** [comment]
Ok

**Comment by PriteshKiri** [comment]
Hey @CuriousCoder00, I believe you are already working on other issues, so we’d like to offer this issue to new contributors. 

@91FAhmed, are you still interested in working on it?

**Comment by 91FAhmed** [comment]
Yes I'm interested it will be my first contribution

**Comment by PriteshKiri** [comment]
Awesome @91FAhmed! I've assigned the issue to you. Congratulations on your first contribution! 🎉

We would also appreciate it if you could star our repository. Let me know if you have any questions or need any help. Happy coding :)

**Comment by PriteshKiri** [comment]
Hey @91FAhmed any update on the issue? Please let me know if you are facing any issues.

Also, feel free to drop your queries in the contributor's channel of our [Slack community](https://tooljet.com/slack).

**Comment by 91FAhmed** [comment]
I can't understand folder structure and I can't understand where exactly
css files are located

**Comment by AnkityadavIITR** [comment]
Hey @PriteshKiri if this issue is still valid and if @91FAhmed  is not working anymore on this , can i work on this issue?

**Comment by 91FAhmed** [comment]
Yes, you can do that.

**Comment by AnkityadavIITR** [comment]
hi @PriteshKiri can i work on this issue?, as @91FAhmed has no issue with it

**Comment by PriteshKiri** [comment]
Sure @AnkityadavIITR, Assigning the issue to you. Happy coding :)

**Comment by AnkityadavIITR** [comment]
Thanks @PriteshKiri for assigning it to me, I've created the PR please review it and let me know if anything requires

**Comment by PriteshKiri** [comment]
Thanks for the PR @AnkityadavIITR. Moving it to review
