### ISSUE TITLE
Rest API URL param vanish at times, and user has to click on it to reveal it

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#1045]
### Environment

Enterprise deployment

### What is the expected behaviour?

Set URL params should always be visible when a user opens a query's configuration

### What is the current behaviour?

URL params are invisible, and user has to click on it to reveal it
### How to reproduce the issue?

1. Create a REST API query
2. Set URL to `https://reqres.in/api/users`
3. Goto params tab and set first param to `page` and `2` as key and value respectively
4. Save it
5. Go to some other query's config
6. Come back to the original query
7. Open params tab

### Screenshots or Screencast

https://user-images.githubusercontent.com/20333972/137314406-d65b38d1-05ef-4d8f-9172-d5c64f2257f8.mp4

**Comment by ArnavPuri** [comment]
Hi, 
I am able to reproduce this issue and would like to try and fix it. Can I take this issue?

I am also seeing another problem, when I click on the last param field and come back to the first field it adds a new row.

Here is the video demonstrating the problem:

https://user-images.githubusercontent.com/4078339/137435239-1636c192-1e98-4947-b75b-52cc54c1ec5b.mov

Should I try to solve this in the same PR for this issue or create a separate issue for this?

**Comment by withshubh** [comment]
This issue has been resolved.
