### ISSUE TITLE
Transformation editor: weird behaviour when lines are long

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#1047]
### Environment
Enterprise deployment

### What is the expected behaviour?

Transformation editor should properly display the code and also the code should not end up overlapping line numbers.

### What is the current behaviour?

When lines are long, the transformation editor shows up a weird empty space where the typed in code is not visible.
Also the code overlaps with line numbers
### How to reproduce the issue?

1. Please refer to screencast

### Screenshots or Screencast

https://user-images.githubusercontent.com/20333972/137315431-903dbd1a-049c-4c23-824d-2547f77e444a.mp4

**Comment by amaaniqbal** [comment]
@sherfin94 Should I give it a shot?
