### ISSUE TITLE
[Bug Event Handler Loading] The loading state is replicated across all event handlers if one is loading

### ISSUE THREAD

**Issue by DevangAgarwal93** [ToolJet/ToolJet#10470]
https://tooljet.slack.com/archives/C02QT13RF51/p1720598643215379?thread_ts=1720598151.727809&cid=C02QT13RF51

https://github.com/user-attachments/assets/c744421b-087d-4416-8e4b-1d420d002d13

**Comment by CVamsi27** [comment]
Hey @DevangAgarwal93 , I found a fix for this issue, will push a PR for the same.

**Comment by PriteshKiri** [comment]
Hey @CVamsi27 ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.
