### ISSUE TITLE
[Docs] Update to Inline code and fix grammatical error

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1053]
Update default username "dev@tooljet.io" to Inline code.

### Describe the problem
> The default username of the admin is dev@tooljet.io and password is `password`.

### Describe the improvement
> The default username of the admin is `dev@tooljet.io` and the password is `password`.

**Comment by saurabh042** [comment]
Hi @arpitnath Could you please assign this to me

**Comment by arpitnath** [comment]
Sure, assigning the issue to you.
@saurabh042

**Comment by arpitnath** [comment]
@saurabh042 Would you please try to mention the issue in the PR?
