### ISSUE TITLE
[Docs] Add Divider widget documentation to widget reference

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1054]
<img width="302" alt="Screenshot 2021-10-14 at 10 01 15 PM" src="https://user-images.githubusercontent.com/67645175/137359269-64a9fa3b-f3cb-4dfc-b44f-979f0256818c.png">

**Comment by arpitnath** [comment]
> @arpitnath any reference material you want to share?

you can refer to https://docs.tooljet.io/docs/widgets/button and other widgets

**Comment by MohsinNajmuddin** [comment]
@arpitnath ok. doing it

**Comment by MohsinNajmuddin** [comment]
@arpitnath I have added the documentation. Please review
