### ISSUE TITLE
Go to app action crashes the site

### ISSUE THREAD

**Issue by Aaron-sudo-apt** [ToolJet/ToolJet#10601]
Version 2.50.9.25
### Environment
 Docker

### What is the expected behaviour?
Go to another app after clicking on a table row

### What is the current behaviour?
App doesnt seem to run after clicking at a table row

### How to reproduce the issue?

1. Click on a Table and create a "row clicked" event
2. Add the "Go to app" action
3. Click on a row on youre table

### Screenshots or Screencast
![screenshot](https://github.com/user-attachments/assets/24f03b5f-0a69-4cfc-9a92-54620365cca3)

### Error message in browser console
Uncaught (in promise) TypeError: je.pages[Ge] is undefined
    Ve https://#/main.js?e3cda00162fdad26341e:48
    xe https://#/main.js?e3cda00162fdad26341e:48
    lc https://#/vendor.js?e3cda00162fdad26341e:33547
    Qn https://#/vendor.js?e3cda00162fdad26341e:33549
    $d https://#/vendor.js?e3cda00162fdad26341e:33549
    yd https://#/vendor.js?e3cda00162fdad26341e:33549
    Ye https://#/vendor.js?e3cda00162fdad26341e:33549
    or https://#/vendor.js?e3cda00162fdad26341e:33549
    Zd https://#/vendor.js?e3cda00162fdad26341e:33549
    Tc https://#/vendor.js?e3cda00162fdad26341e:33547
    td https://#/vendor.js?e3cda00162fdad26341e:33549
    enqueueSetState https://#/vendor.js?e3cda00162fdad26341e:33547
    setState https://#/vendor.js?e3cda00162fdad26341e:34218
    xe https://#/main.js?e3cda00162fdad26341e:48
    f https://#/vendor.js?e3cda00162fdad26341e:34344
    q https://#/vendor.js?e3cda00162fdad26341e:34344
    F https://#/vendor.js?e3cda00162fdad26341e:34344
    t https://#/vendor.js?e3cda00162fdad26341e:34351
    k https:/#/vendor.js?e3cda00162fdad26341e:34351

**Comment by nakulnagargade** [comment]
Hi @Aaron-sudo-apt, we were able to reproduce this issue only on viewer, Can you please confirm this issue you are facing is on Viewer and not on editor?

**Comment by Aaron-sudo-apt** [comment]
@nakulnagargade Yes the issue only occurs when launching the app. In the Editor everything works just fine.

**Comment by ShazanRizvi** [comment]
Hey @Aaron-sudo-apt 

I am pleased to inform you that the fix for this issue has been released in version `EE-LTS-2.50.9.26`. Please ensure to take a backup of your database before upgrading to this version. Please let us know if you have any further concerns we will be here to assist you. 

Happy building with ToolJet!

**Comment by Aaron-sudo-apt** [comment]
@ShazanRizvi Thanks for the help :+1:
