### ISSUE TITLE
[Bug] Rich TextEditor's Content and scroll overflow the container

### ISSUE THREAD

**Issue by DevangAgarwal93** [ToolJet/ToolJet#10639]
Bug - Rich text editor's content & scroll overflow the container. Happens on editor, preview is fine.
See the below recording

https://github.com/user-attachments/assets/682fdd65-e68c-4dfd-9fab-6a1fe15a7679

Slack - https://tooljet.slack.com/archives/C02QT13RF51/p1723608447451409

**Comment by mani-rsg** [comment]
Hi I would like to work this can this be assigned to me?
