### ISSUE TITLE
[Password] Validation message is hidden if the box shadow is very dark

### ISSUE THREAD

**Issue by DevangAgarwal93** [ToolJet/ToolJet#10641]
The issue is that the error message is being displayed below the box shadow, rather than on top as expected, hence it is not visible when the box shadow is opaque enough.

https://tooljet.slack.com/archives/C04JQ3P9DRT/p1721977816286599

https://github.com/user-attachments/assets/eb72fc30-0f22-452f-942e-02ddd1512c73

**Comment by Monilprajapati** [comment]
Hey @PriteshKiri 
I can fix this one 
Here's the preview:

[passwordField.webm](https://github.com/user-attachments/assets/ab06540a-5e53-4398-a7bd-2d8991b813dd)

**Comment by PriteshKiri** [comment]
Hey @Monilprajapati, We greatly appreciate your interest. But this issue will be taken by the internal team.

Please check out other open issues under the `community contribution` label only.

**Comment by Monilprajapati** [comment]
> Hey @Monilprajapati, We greatly appreciate your interest. But this issue will be taken by the internal team.
> 
> Please check out other open issues under the `community contribution` label only.

Alright, I thought the same :) 
But all the ` community contribution ` labelled issues are assigned :)

**Comment by Monilprajapati** [comment]
Just to make things easier and save you time:
This might be the solution from my side:
Need to add zIndex in `PasswordInput.jsx` 
![image](https://github.com/user-attachments/assets/4ef469a9-dfc8-44c8-bca4-cff88b53629b)

**Comment by PriteshKiri** [comment]
@Monilprajapati we have added this as a community issue. Are you still interested in working on this?

**Comment by asdotdev** [comment]
Hi, can I work on this issue?

Only the `zIndex` property doesn't change anything as it does not have the `position` property, so we must add both.

**Comment by PriteshKiri** [comment]
@asdotdev assigned. Happy coding! 😊  

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by PriteshKiri** [comment]
Thanks for your contribution @asdotdev! Moving it to review
