### ISSUE TITLE
[ Login Page ] - On Clicking login button it turn gray , 

### ISSUE THREAD

**Issue by Abhii5496** [ToolJet/ToolJet#10657]
-  When user clicks on login button , it does not show any meaningful message simply turns gray . It ruins user experience.

https://github.com/user-attachments/assets/e97e2838-4bca-4e94-8fd8-38ffa2b9384b

**Comment by Naveena-V** [comment]
Hi @Abhii5496  what will be the behaviour you expect after clicking on login button, its showing some popup message.

**Comment by nechalmaggon** [comment]
@Abhii5496 @Naveena-V Hey folks, thanks for creating and showing interest for the issue. The expected behaviour is for the button to grey out and show a loading state there. Essentially, loading state is missing and this has been resolved internally and will be available in the next release
