### ISSUE TITLE
[bug] Data Type box should not overlap other elements

### ISSUE THREAD

**Issue by VanshWadhwa** [ToolJet/ToolJet#10673]
### Environment 
  ToolJet Cloud 

### What is the expected behaviour?

The data type box should be at correct position after scroll

### What is the current behaviour?
The data type box overlaps other elements

### How to reproduce the issue?

1. Create a MongoDB query
2. Focus on documents
3. Scroll to bottom

### Screenshots or Screencast
![image](https://github.com/user-attachments/assets/afb3849f-352a-454d-aefe-b5ba776bd5ff)
![image](https://github.com/user-attachments/assets/24f3e642-83bf-403a-b601-dd1f71ceca9a)

### If the bug is confirmed, would you be willing to submit a PR?
Yes,

**Comment by VanshWadhwa** [comment]
I would like to work on this, can anyone assign it to me?

**Comment by PriteshKiri** [comment]
Thank you for your interest @VanshWadhwa ! This one will be handled by our internal team, but we appreciate you pointing it out!

**Comment by PriteshKiri** [comment]
Closing this issue as it will be handled by our internal team.
