### ISSUE TITLE
Last edited user info on app to be removed

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#10692]
**Current scenario-**
`Edited 16 days ago by <user name>` 

**Pain point-** 
We don't store the last edited user's information, only time. So the app owner's information is always shown in edited which is misleading. Hence, we will remove that information. 

**Desired scenario-** 
`Edited 16 days ago` 

![Image](https://github.com/user-attachments/assets/587fd63f-1e8b-43ec-a1a9-98b07bbddfee)

**Comment by qasimahmadkhan** [comment]
hi @nechalmaggon, if is this issue still open, I'd like to work on it

**Comment by unamdev0** [comment]
@nechalmaggon  fixed this in #10708

**Comment by PriteshKiri** [comment]
Hey@qasimahmadkhan, are you still interested in working on this issue?

**Comment by qasimahmadkhan** [comment]
Hi @PriteshKiri, yes I would like to work on it.

**Comment by PriteshKiri** [comment]
@qasimahmadkhan  assigned. Happy coding! 😊  

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by qasimahmadkhan** [comment]
@PriteshKiri sure, thanks a lot . 😃

**Comment by qasimahmadkhan** [comment]
@PriteshKiri raised PR [#10712](https://github.com/ToolJet/ToolJet/pull/10712), please review it, thanks.

**Comment by PriteshKiri** [comment]
Thanks for the contribution @qasimahmadkhan. Moving it to review.
`Quick PR`

**Comment by qasimahmadkhan** [comment]
Thanks for letting me work on it @PriteshKiri
