### ISSUE TITLE
issue: loading state issue in button names "New event handler"

### ISSUE THREAD

**Issue by AnkityadavIITR** [ToolJet/ToolJet#10691]
### Environment

ToolJet Cloud

### What is the expected behaviour?

when i click on one add "New event handler" only clicked one should go in loading state

### What is the current behaviour?

when i click on one add events button, all other buttons made for adding new event handler goes in loading state

### How to reproduce the issue?

1.Create an app on tooljet app-builder
2.Drop a button and click on Add "new event handler "
3.and all the button with name "New event handler" goes into loading state

### Screenshots or Screencast

![image](https://github.com/user-attachments/assets/7dde3f1c-76f2-45f7-bd3e-26143534f47b)
video url-https://github.com/user-attachments/assets/2a253072-4abd-46a0-896b-cee2edb85eb3

### If the bug is confirmed, would you be willing to submit a PR?
YES

**Comment by PriteshKiri** [comment]
Thank you for pointing this out @AnkityadavIITR.

 This issue is already on our roadmap, and we're working on it. We appreciate your support!
