### ISSUE TITLE
app dashboard navigation text not visible properly on walk through

### ISSUE THREAD

**Issue by fkk989** [ToolJet/ToolJet#10718]
<img width="746" alt="Screenshot 2024-09-04 at 1 22 44 PM" src="https://github.com/user-attachments/assets/052f2c89-3206-481e-a25f-46d9fb1e4782">

**Comment by fkk989** [comment]
hey team can I work on this

**Comment by PriteshKiri** [comment]
Hey @fkk989, let me check with the team and get back to you on this.

**Comment by PriteshKiri** [comment]
@fkk989 we have added this issue for community contribution. Assigning it to you. Happy coding :) 

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by fkk989** [comment]
hey @PriteshKiri raised the pr you can review it.

**Comment by PriteshKiri** [comment]
Thanks for the PR @fkk989. Moving it to review
`Quick PR`

**Comment by mrhat05** [comment]
hey @PriteshKiri can i work on this

**Comment by PriteshKiri** [comment]
Hey @mrhat05, this issue has been taken. Please check other open issues on the `community contribution` label
