### ISSUE TITLE
Bulk upload drawer text alignment issues - conflicting CSS to be fixed

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#10733]
![Image](https://github.com/user-attachments/assets/11cd4722-6b01-4b84-94c1-ffac0377c526)

**Comment by Shivam250702** [comment]
hi @mansukh-tj I would like to work on this issue can you please assign this issue to me

**Comment by mansukh-tj** [comment]
Hi @Shivam250702 
Thanks for your interest. We have picked this up internally. Alternatively you may check out the issues having `community-contribution` label.
