### ISSUE TITLE
Events title not visible in dark mode

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1076]
![image](https://user-images.githubusercontent.com/7828962/137436072-af01d597-b22d-4743-9724-f5f1191eb7e6.png)

Steps to reproduce: 
a) Create a query 
b) Switch to dark mode 
c) Go to the advanced tab of the query
d) The title for the event section is not visible in dark mode

**Comment by Navaneeth-pk** [comment]
Thanks for contributing again @trevorbayless !

**Comment by trevorbayless** [comment]
@Navaneeth-pk When switching between light and dark mode, I am not seeing any difference with a title missing on the Advanced tab of queries. Has this issue already been resolved? Screenshots provided for reference:

**Light Theme**
![image](https://user-images.githubusercontent.com/3620552/137562033-0bc7888a-a4a8-471d-9d48-95c27f6b8290.png)

**Dark Theme**
![image](https://user-images.githubusercontent.com/3620552/137562087-da32622c-deed-4335-a331-a84eee0ab558.png)

**Comment by trevorbayless** [comment]
@Navaneeth-pk Can you confirm this is still an issue? From my research above, both light and dark mode show the same content.

**Comment by TheLearneer** [comment]
@trevorbayless as you can see in the image below, this is what needs to updated to be observed better
![image](https://user-images.githubusercontent.com/23402178/137671586-3518d398-fa38-4e77-af5f-55f4c8af9df6.png)
