### ISSUE TITLE
Airtable: [Add query manager features] User Locale and Timezone Input

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#10760]
According Airtable API, if cell format is string, then Timezone and User locale are compulsary inputs which ToolJet wasn't supporting until now. 

In Airtable Query Builder, the following inputs are to be added

Timezone | string | placeholder: America/Chicago
User locale | string | placeholder: en-gb

**Comment by Siddharthgup** [comment]
Hi @mansukh-tj ,Can you assign this task to me ?

**Comment by mansukh-tj** [comment]
Hi @Siddharthgup 

Thanks for showing interest. We have decided to pick this up internally. You may look at the issues tagged specifically with the label `community contribution` .
