### ISSUE TITLE
Pinecone - operations: List vector Ids, Fetch vectors, Upsert vectors, Update a vector and delete a vector

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#10776]
**1. List vector Ids**
![Image](https://github.com/user-attachments/assets/bc68b3b7-56b6-4ff5-93fc-979d578846ec)

**2. Fetch Vectors**
![Image](https://github.com/user-attachments/assets/3b391424-4f9d-4f0a-86e7-db296fd15792)

**3. Upsert vectors**
![Image](https://github.com/user-attachments/assets/a71ac28f-7ea7-441d-947d-b77fdc766d85)

**4. Update a vector**
![Image](https://github.com/user-attachments/assets/ed783ca6-5e6e-4867-a068-3b8944f3ea8e)

**5. Delete vectors**
![Image](https://github.com/user-attachments/assets/e4c05a2c-ff0f-49ab-bb33-a532c9d09f97)

**Comment by sarfarazsiddiquii** [comment]
Het @mansukh-tj i would like to work on this issue, can you please assign me?

**Comment by mansukh-tj** [comment]
Hi @sarfarazsiddiquii 

We are glad to see your interest in this issue. However, we are taking this up internally.
I'll recommend you to go through our issues that are tagged with `community contribution` label to pick up something to work on.

**Comment by wttc-nitr** [comment]
> Hi @sarfarazsiddiquii
> 
> We are glad to see your interest in this issue. However, we are taking this up internally. I'll recommend you to go through our issues that are tagged with `community contribution` label to pick up something to work on.

So that means any outsider can only contribute to issues that are tagged with `community contribution` ? 
There is nothing mentioned as such in `CONTRIBUTING.md`.
