### ISSUE TITLE
Add default value for text widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1078]
```
Hello have a great {{moment().format('dddd')}}   👋   
```

Reference:
![image](https://user-images.githubusercontent.com/67645175/137442208-9ab122ff-cdd1-4338-a652-81e0fb5f7efa.png)

**Comment by nik132-eng** [comment]
Sorry @arpitnath can you please help me with how to work on this issue? I didn't understand it.

**Comment by ThisIsFaar** [comment]
@nik132-eng this issue is already spoon feed by @arpitnath.

Feel free to pass it to me if you are not able to solve.

**Comment by arpitnath** [comment]
Hi @nik132-eng you can refer to this PR #1103
