### ISSUE TITLE
Google sheets - Add detailed error description

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#10827]
Current error response:
![Screenshot 2024-09-27 at 11 08 00 AM](https://github.com/user-attachments/assets/86d071ef-f20a-4c09-9fcd-320e78d4ad4f)

Expected error response: 
![Screenshot 2024-09-27 at 11 09 09 AM](https://github.com/user-attachments/assets/fee70c9f-42aa-4a19-b94e-0629c95c5cd0)

**Comment by akashvivek** [comment]
Is this still open

**Comment by mansukh-tj** [comment]
Hi, thanks for your interest. We have picked this up internally. Alternatively you may check out the issues having `community-contribution` label.
