### ISSUE TITLE
[Inspector] Improve tooltips and pop-up feedback for copying path and value

### ISSUE THREAD

**Issue by DevangAgarwal93** [ToolJet/ToolJet#10837]
### Issue Description
We have two options in inspector, one is copy the path and other is copy the value. However, from the tooltip it is not clear as it is showing "Copy to clipboard" instead of "copy path"
Adding to this, it would be nice to add something similar to "Path copied to clipboard" or "Value copied to clipboard" on the success snackbars/popups. Currently it is "Copied to clipboard"

### Solution to implement
Change tooltip as follows - 
1. Copy to clipboard -> Copy Path
2. Change pop-up value "Copied to clipboard" when clicked on "Copy Value" -> "Value copied to clipboard"
3. 2. Change pop-up value "Copied to clipboard" when clicked on "Copy path" -> "Path copied to clipboard"

### Supplementary Attachements
https://github.com/user-attachments/assets/d7d6d6b7-a0cb-4532-aa15-9d4d07e3fef8

**Comment by rzuhovski0** [comment]
Hello, I would like to take a look at this, is this still open?

**Comment by Jagss24** [comment]
Hello, @DevangAgarwal93 I would like to work on this task, Can you please assign this task to me?

**Comment by PriteshKiri** [comment]
@rzuhovski0 assigned. Happy coding! 😊  

The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PriteshKiri** [comment]
@Jagss24 @AnkityadavIITR please checkout other issues with `community contribution` lable

**Comment by Aditi-908** [comment]
Hey @PriteshKiri kindly let me know if this issue is reasigned . I would like o work on this issue.
.

**Comment by PriteshKiri** [comment]
Hey @Aditi-908, this issue has already been assigned.   

Please check out other open issues under the `community contribution` label.

**Comment by Codebreaker42** [comment]
Hello sir, could you assigned this to me i can definitely improve this issue.

**Comment by nsanzimana1** [comment]
import React, { useState } from 'react';
import { Tooltip, Snackbar, Button } from '@material-ui/core'; // Ensure you're using Material-UI or similar library

const CopyComponent = () => {
  const [snackbarMessage, setSnackbarMessage] = useState(''); // To store the message for Snackbar
  const [open, setOpen] = useState(false); // Snackbar visibility

  // Function to handle copy actions
  const handleCopy = (type) => {
    if (type === 'path') {
      setSnackbarMessage('Path copied to clipboard'); // Set message for "Copy Path"
      // Here you'd implement logic to copy the path
      navigator.clipboard.writeText('Your Path Value'); // Example: Path copy logic
    } else if (type === 'value') {
      setSnackbarMessage('Value copied to clipboard'); // Set message for "Copy Value"
      // Here you'd implement logic to copy the value
      navigator.clipboard.writeText('Your Value Data'); // Example: Value copy logic
    }
    setOpen(true); // Show the Snackbar after copying
  };

  // Function to handle Snackbar close
  const handleClose = () => {
    setOpen(false);
  };

  return (
    <div style={{ padding: '20px' }}>
      {/* Tooltip and Button for "Copy Path" */}
      <Tooltip title="Copy Path">
        <Button 
          variant="contained" 
          color="primary" 
          onClick={() => handleCopy('path')} 
          style={{ marginRight: '10px' }}
        >
          Copy Path
        </Button>
      </Tooltip>

      {/* Tooltip and Button for "Copy Value" */}
      <Tooltip title="Copy Value">
        <Button 
          variant="contained" 
          color="secondary" 
          onClick={() => handleCopy('value')}
        >
          Copy Value
        </Button>
      </Tooltip>

      {/* Snackbar to display messages */}
      <Snackbar
        open={open}
        autoHideDuration={3000} // Snackbar will close automatically after 3 seconds
        onClose={handleClose}
        message={snackbarMessage} // Show dynamic message based on what was copied
      />
    </div>
  );
};

**Comment by Jagss24** [comment]
@PriteshKiri In case the issue didn't get resolved in given timespan. I would like to work on it.

**Comment by PriteshKiri** [comment]
Hey  @rzuhovski0,

Any update on the issue?

**Comment by PriteshKiri** [comment]
Hey @Jagss24,
We’ll be opening the issue for contribution again if it hasn’t been resolved in the next few hours.

Thanks for your patience!

**Comment by FurquanAnwer** [comment]
Please assign me if no progress seems to be made. Thanks

**Comment by Jagss24** [comment]
Ok @PriteshKiri Just mention me whenever it will be assigned to me

**Comment by anasKhafaga** [comment]
@PriteshKiri, I'd be happy to pick this issue.

**Comment by PriteshKiri** [comment]
@Jagss24  assigned. Happy coding! 

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @anasKhafaga, We greatly appreciate your interest. 

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. We hope you understand our decision and thank you for your understanding.

**Comment by anasKhafaga** [comment]
@PriteshKiri , it's totally understood and appreciated.

**Comment by PriteshKiri** [comment]
Hey @Jagss24, any updates on the issue?

**Comment by Jagss24** [comment]
Hey @PriteshKiri I need some more time. As i was having issues with setup.

**Comment by YashwantOstwal** [comment]
Hey, Can you assign me this ?

**Comment by priteshTJ** [comment]
Hey @Jagss24,

Are you still facing issue with the setup?

**Comment by PriteshKiri** [comment]
Hey @Jagss24, are you still facing issue with the setup?

**Comment by PriteshKiri** [comment]
Hey @YashwantOstwal  , this issue has already been assigned.  

Please check out other open issues under the `community contribution`.

**Comment by Jagss24** [comment]
Heyy @PriteshKiri, I tried hard but my system is not supporting it you can give the issue to another person. I will try another one. Thanks for your patience!!

**Comment by PriteshKiri** [comment]
Sure thing, @Jagss24!

Feel free to comment on the new issues whenever you're able to complete the setup successfully.

**Comment by PriteshKiri** [comment]
This issue is open for contribution!

**Comment by AnkityadavIITR** [comment]
Hii @PriteshKiri i would be happy to work on it

**Comment by PriteshKiri** [comment]
Hey @AnkityadavIITR  , We greatly appreciate your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

We hope you understand our decision. Thanks!

**Comment by PriteshKiri** [comment]
Hey @Rohan-3337,

Thanks for your contribution! Just a reminder to please start working on an issue only after it has been officially assigned to you. We’re approving the PR this time, but please keep this in mind for future contributions.

Thank you for your understanding!

**Comment by KrishDave1** [comment]
Hey @PriteshKiri , Can I work on this issue?

**Comment by Rohan-3337** [comment]
Hey @PriteshKiri ,
Thank you for the feedback and approval! I noticed the PR hasn't been merged yet—just wanted to check if there’s anything else I need to do on my end

**Comment by PriteshKiri** [comment]
Hey @Rohan-3337,

The PR will take a week or so to review and merge. Thanks for your patience!

**Comment by ManuBM555** [comment]
Hey @PriteshKiri ,
If this issue is still open, can you please assign me to resolve this issue??

**Comment by PriteshKiri** [comment]
Hey @ManuBM555 , this issue has already been assigned.  

Please check out other open issues under the `community contribution`.

**Comment by PriteshKiri** [comment]
Hey @HSRAKTU  , this issue has already been assigned.  

Please check out other open issues under the community contribution.

**Comment by PriteshKiri** [comment]
Hey @PushpakChaudhari ,

This issue has already been assigned. I’d request you to please comment on issues that are currently unassigned only.

You can check out other open issues under the `community contribution` label. Thanks!
