### ISSUE TITLE
[docs]: Update the documentation for the Timer Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10846]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/timer

**Formatting updates:**
- Update the formatting based on the [latest](https://docs.tooljet.com/docs/contributing-guide/documentation-guidelines/style-guide) guidelines.
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Add a more descriptive introduction
- Replace the word "widget" with "component" wherever applicable. 
- Layout Table
  - Replace the header "Layout" with "Devices"
  - Update the Description and Expected Value columns [reference](https://docs.tooljet.com/docs/widgets/text-input#devices)
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)
- Update the description in the Events table [reference](https://docs.tooljet.com/docs/widgets/text-input#events)
 - Styles Table
   - Update the styles table with three headers - Property, Description, Configuration Options [reference](https://docs.tooljet.com/docs/widgets/text-input#label) 
   - Update the content of the style table [reference](https://docs.tooljet.com/docs/widgets/text-input/#additional-actions)
   - Include box-shadow under the Styles table [reference](https://docs.tooljet.com/docs/widgets/number-input#field)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/timer.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/timer.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by krishnadev7** [comment]
hey @PriteshKiri . I would like to work on this issue. Please assign it to me.

**Comment by PriteshKiri** [comment]
@krishnadev7 assigned 👍 

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PRIYANKjakharia** [comment]
i would like to work on this

**Comment by PriteshKiri** [comment]
Thanks for your contribution @krishnadev7 🙌

**Comment by SandipM03** [comment]
hey, I would like to work on this issue please assign it to me.

**Comment by PriteshKiri** [comment]
Hey @SandipM03 , this issue has already been assigned.  

Please check out other open issues under the `community contribution`.

**Comment by SandipM03** [comment]
okay thanks for your replay
