### ISSUE TITLE
[docs]: Update the documentation for the Toggle Switch Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10845]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/toggle-switch-v2

**Formatting updates:**
- Update the formatting based on the [latest](https://docs.tooljet.com/docs/contributing-guide/documentation-guidelines/style-guide) guidelines.
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Update the "Devices" content to a table  [reference](https://docs.tooljet.com/docs/widgets/text-input#devices)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/toggle-switch-v2.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/toggle-switch-v2.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by SamIsTheFBI** [comment]
Hi @PriteshKiri can I be assigned to solve this issue?

I've read through the latest guidelines so I'll be sure to provide good commits.

**Comment by PriteshKiri** [comment]
@SamIsTheFBI  assigned 🙌 

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by TarunDev1478** [comment]
Assign this to me

**Comment by SanchitMahajan236** [comment]
I would love to work on this issue. Please assign this issue to me.

**Comment by PriteshKiri** [comment]
Hey @TarunDev1478 @SanchitMahajan236,

This issue has already been assigned. Please check other issues with the `community contribution` label.

**Comment by PriteshKiri** [comment]
Hey @SamIsTheFBI,

Thanks for submitting the PR. I've added a comment to your PR—please go through it when you get a chance.

**Comment by PriteshKiri** [comment]
Hey @developer-mohitsoni,

Please start working on an issue only after it has been assigned to you. This helps us track progress more effectively.

You can check open issues under the `community contribution` label for available tasks.

**Comment by PriteshKiri** [comment]
This issue is now open for contribution. Feel free to check it out!

**Comment by Naman13112004** [comment]
Hi @PriteshKiri ,could you please assign this issue to me
Also I am new to open source so can you please guide me as well

**Comment by a-wishie** [comment]
Hello, @PriteshKiri!
I am interested. Can you please assign this issue to me?

**Comment by Sarthakkashyapp** [comment]
Hello @PriteshKiri can you please assign this issue to me

**Comment by poswalsameer** [comment]
Hi @PriteshKiri, is anyone still working on this issue? If not, I would like to start working on it. Thanks in advance.

**Comment by SanchitMahajan236** [comment]
Hi @PriteshKiri, when I commented earlier this issue was already assigned but now it is up-for-grabs. So, please assign me this issue.

**Comment by PriteshKiri** [comment]
@Naman13112004  assigned.

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by PriteshKiri** [comment]
@a-wishie @Sarthakkashyapp @poswalsameer @SanchitMahajan236  please check out other issues with `community contribution` label

**Comment by A-1evi** [comment]
Hi @PriteshKiri ,could you please assign this issue to me
Also I am new to open source so can you please guide me as well

**Comment by PriteshKiri** [comment]
Hey @A-1evi , this issue has already been assigned.   Please check out other open issues under the `community contribution`.

**Comment by A-1evi** [comment]
but all the good first issue is already assigned

**Comment by PriteshKiri** [comment]
@A-1evi We’ll be putting out some more issues next week, so please keep an eye on them.

**Comment by PriteshKiri** [comment]
Thanks for your contribution @Naman13112004 🙌

**Comment by Naman13112004** [comment]
Thank you for the opportunity @PriteshKiri sir
