### ISSUE TITLE
[docs]: Update the documentation for the Vertical Divider Component

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#10844]
### Summary

**The entire URL of the documentation with the issue**

https://docs.tooljet.com/docs/widgets/vertical-divider

**Formatting updates:**
- Update the formatting based on the [latest](https://docs.tooljet.com/docs/contributing-guide/documentation-guidelines/style-guide) guidelines.
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Add a more descriptive introduction
- Replace the word "widget" with "component" wherever applicable. 
- Layout Table
  - Replace the header "Layout" with "Devices"
  - Update the Description and Expected Value columns [reference](https://docs.tooljet.com/docs/widgets/text-input#devices)
 - Styles Table
   - Update the styles table and its content with three headers - Property, Description, Configuration Options [reference](https://docs.tooljet.com/docs/widgets/text-input#label) 
   - Include box-shadow under the Styles table 

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/vertical-divider.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/vertical-divider.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_
   
**If the issue is confirmed, would you be willing to submit a pull request?**

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by SamIsTheFBI** [comment]
Hi

I'm willing to work on this issue. I've read thoroughly the style guide and I'm confident I can make some good commits for this issue. 

Can I be assigned to work on this issue?

**Comment by SamIsTheFBI** [comment]
Ok cool, won't disappoint at that!

**Comment by PARVNEMA** [comment]
could i get assigned this issue this is the first time i am contributing to hacktoberfest and i will do my best

**Comment by ashujha301** [comment]
Hi

I'm willing to work on this issue. I have gone through the code, documentation and references. I m confident that i can resolve this.

Can I be assigned to work on this issue?

**Comment by Cvr421** [comment]
Hi @PriteshKiri 
Can i work on this issue

**Comment by PriteshKiri** [comment]
@PARVNEMA assigned!!

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PriteshKiri** [comment]
@ashujha301 @Cvr421 please checkout other issues with `community contribution` label.

**Comment by parthib2004** [comment]
Can you please assign these to me?

**Comment by PriteshKiri** [comment]
@parthib2004 please check out other issues with the `community contribution` label.

**Comment by PriteshKiri** [comment]
Thanks for your contribution @PARVNEMA

**Comment by PARVNEMA** [comment]
@PriteshKiri  thanks  for giving me this opportunity 🙏 .By the way when will my pl get merged and any more opportunity for me

**Comment by PriteshKiri** [comment]
@PARVNEMA your PR will reviewed and merged within 3-4 days.
