### ISSUE TITLE
[docs]: Update the documentation for the Text Editor Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10848]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/rich-text-editor

**Formatting updates:**
- Update the formatting based on the [latest](https://docs.tooljet.com/docs/contributing-guide/documentation-guidelines/style-guide) guidelines.
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Add a more descriptive introduction
- Replace the word "widget" with "component" wherever applicable. 
 - Properties Table
   - Update the styles table with three headers - Property, Description, Expected Value [reference](https://docs.tooljet.com/docs/widgets/text-input#properties) 
   - Update the content of the table [reference](https://docs.tooljet.com/docs/widgets/text-input#properties)
 - Update the content for the Exposed Variables Table [reference](https://docs.tooljet.com/docs/widgets/text-input#exposed-variables)
- Layout Table
  - Replace the header "Layout" with "Devices"
  - Update the Description and Expected Value columns [reference](https://docs.tooljet.com/docs/widgets/text-input#devices)
 - Styles Table
   - Update the styles table with three headers - Property, Description, Configuration Options [reference](https://docs.tooljet.com/docs/widgets/text-input#label) 
   - Update the content of the style table [reference](https://docs.tooljet.com/docs/widgets/text-input/#additional-actions)
   - Include box-shadow under the Styles table [reference](https://docs.tooljet.com/docs/widgets/number-input#field)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/rich-text-editor.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/rich-text-editor.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_
 
### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by HarshitVashisht11** [comment]
Hi, can I solve this issue

**Comment by sidhanshamil** [comment]
I would like to work on this

**Comment by PriteshKiri** [comment]
@HarshitVashisht11 assigned 🙌 

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PriteshKiri** [comment]
@sidhanshamil 7 please checkout other issues with `community contribution` label

**Comment by PriteshKiri** [comment]
Thanks for your contribution @HarshitVashisht11 🙌

**Comment by A-1evi** [comment]
is this issse resolved?

**Comment by RudraPratik30** [comment]
Hey @A-1evi, yes the issue is resolved!
