### ISSUE TITLE
Add a tooltip to the button

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1085]
### What is the current behaviour?
The button doesn't have a tooltip.

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/67645175/137475533-6c89c2d7-f279-4269-8844-49d255a64c30.png)

**Comment by alammoiz** [comment]
Please assign to me, I have completed the previous one @arpitnath

**Comment by arpitnath** [comment]
Thank you for contributing, assigned the issue.
@alammoiz
