### ISSUE TITLE
[refactor]: Invite Users Form icon's to support Dark mode

### ISSUE THREAD

**Issue by Ayyanaruto** [ToolJet/ToolJet#10868]
## **GitHub Issue Title:** Refactor Invite Users Icon Color Based on Dark/Light Mode

**Description:**
The icon in the `Invite Users` component within `frontend/src/ManagerUsers/InviteUsers.jsx` is currently not changing its icon's color to match the current dark or light mode. This inconsistency can lead to a less visually appealing user experience.

**Steps to Reproduce:**

1. Navigate to the `Invite Users` component.
2. Toggle between dark and light mode.
3. Observe that the icon's color remains unchanged.

**Expected Behavior:**

The icon's color should dynamically adjust to match the system's current theme (dark or light).

**Additional Notes:**

* Check from localstorage whether app is in darkmode or not and change the color of  icon's dynamically based on that
**Attachments:**
![WhatsApp Image 2024-10-03 at 12 03 57 PM (2)](https://github.com/user-attachments/assets/995600fa-11fe-4062-bc77-2f77946ddd98)

**Comment by FurquanAnwer** [comment]
I would like to take this issue.

**Comment by nsanzimana1** [comment]
let me work on this

**Comment by RazalBinKabeer** [comment]
Let me work on this issue. I have good experience working without with Frontend Development especially in React.

**Comment by PriteshKiri** [comment]
Hey @Ayyanaruto,

Thank you for opening the issue and taking the time to create a PR for it. 🙌 

We really appreciate your effort and contribution!

**Comment by shreyanshgoyal18** [comment]
@PriteshKiri , i would like to contribute .Could you please assign me this ?

**Comment by PriteshKiri** [comment]
Hey @shreyanshgoyal18 , this issue has already been assigned.

Please check out other open issues under the `community contribution`.
