### ISSUE TITLE
[docs]: Wrong roadmap link in README

### ISSUE THREAD

**Issue by Spid3rrr** [ToolJet/ToolJet#10870]
### Summary

This is a minor nitpick, but the roadmap link in the README specifically points to "https://github.com/ToolJet/ToolJet/projects/2", while the correct roadmap is here "https://github.com/orgs/ToolJet/projects/15". I can correct this if needed.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://github.com/ToolJet/ToolJet/blob/develop/README.md

### Steps to reproduce the issue

1. Open the default repo README.
2. Scroll down to Roadmap and click on the highlighted link
3. A 404 error will appear.

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PARVNEMA** [comment]
could i get assigned the issue

**Comment by PriteshKiri** [comment]
This issue is open for community contribution.

**Comment by PriteshKiri** [comment]
Hey @PARVNEMA  , We appreciate your interest. 

However, we would like to see if there are any first-time contributors who are also interested.

We hope you understand our decision. Thank you!

**Comment by PriteshKiri** [comment]
Hey @Spid3rrr, are you still working on this issue?

**Comment by NitinPSingh** [comment]
@PriteshKiri can i work on this?

**Comment by prathamranjansingh** [comment]
@PriteshKiri Can i work on this issue?

**Comment by Avii-KS** [comment]
Hi @PriteshKiri  can I be assigned to solve this issue?
This is my first time takin part in an Open Source Contribution and i would love to work on this issue!

**Comment by PriteshKiri** [comment]
Hey @prathamranjansingh,

Thank you for your contribution! Just a small note for future reference, it’s ideal to start working on an issue once it has been officially assigned to you. We’re considering your PR for now, and we really appreciate your effort!

Thanks again for your understanding.

**Comment by PriteshKiri** [comment]
@NitinPSingh @Avii-KS please check out other issues with the `community contribution` label.
