### ISSUE TITLE
Add a default value to the Text widget properties.

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1087]
### What is the expected behaviour?
> Show loading state should have a default value

![Screenshot 2021-10-15 at 5 05 39 PM](https://user-images.githubusercontent.com/67645175/137480962-6cfb3f81-0eb7-4bb5-8d87-d9531c4b8f81.png)

### What is the current behaviour?
> Default value is empty

![Screenshot 2021-10-15 at 5 04 58 PM](https://user-images.githubusercontent.com/67645175/137480987-4b1573c4-4b5a-412f-94b0-1db9dbdf065a.png)

### How to reproduce the issue?
 Drag Text Widget from widget manager to the canvas

### Any possible solutions?
Add a default value to the widget properties.

```
loadingState: { value: `{{false}}` }
```

### Can you identify the location in the driver source code where the problem exists?
`/frontend/src/Editor/Components/components.js > **line 648**`

**Comment by SumayyaZiyad** [comment]
Apologies for the inconvenience. Could I please have this issue assigned?

**Comment by ThisIsFaar** [comment]
can I work on this?
