### ISSUE TITLE
Community template: Strong password generator

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#10887]
**Description:**
The Strong Password Generator creates secure passwords that meet security standards, with customizable strength and complexity. It's useful for individuals or teams needing unique, strong passwords for multiple accounts.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1HXKhZGqZQEOAt8rlNYzMO_Vn0P0SCSN2hIN3tpQa4EE/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within **7 working days** and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within **7 working days** or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by FurquanAnwer** [comment]
Please assign this issue to me

**Comment by prashantrai-30** [comment]
Hey @GrowwithNaveen can you assign this to me.

**Comment by akashvivek** [comment]
Hey can you assign this to me? I would like to Contribute init

**Comment by shreyanshgoyal18** [comment]
Hey @GrowwithNaveen,

I’ve picked issue #10887, worked on it, and raised a PR #10892. Could you please take a look when you get a chance? Let me know if any changes are required. I chose this issue because I wanted to explore ToolJet, and while I’ve learned a lot, there’s still many things left to explore. It's a great tool!

Thanks!

**Comment by Mefisto04** [comment]
Hi @GrowwithNaveen ,

I would love to contribute to the **Strong Password Generator** template. Please assign this issue to me so I can start working on it.

**Approach:**
- Develop password generation logic with customizable strength.
- Create a user-friendly interface that allows users to select desired password complexity.

**Comment by Avii-KS** [comment]
Hi @GrowwithNaveen can I be assigned to solve this issue?
This is my first time takin part in an Open Source Contribution and i would love to work on this issue!

**Comment by A-1evi** [comment]
Hey @PriteshKiri kindly let me know if this issue is assigned . I would like to work on this issue.

**Comment by PriteshKiri** [comment]
Hey @FurquanAnwer!

We greatly appreciate your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. We hope you understand our decision and thank you for your understanding.

**Comment by PriteshKiri** [comment]
@prashantrai-30 assigned!

Please note that the deadline for this task is 7 days from the day of the assignment. 

Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PriteshKiri** [comment]
@A-1evi @Avii-KS @Mefisto04 @shreyanshgoyal18 @akashvivek  please check out other issues with the community contribution label.

**Comment by HimanshuKakwani** [comment]
hi @GrowwithNaveen, i would love to contribute to this

**Comment by PriteshKiri** [comment]
@HimanshuKakwani please check out other issues with the `community contribution` label.

**Comment by PriteshKiri** [comment]
Hey @prashantrai-30,

Any updates on the issue? Please let me know if you are facing any difficulties

**Comment by prashantrai-30** [comment]
I have raised a pr for this issue,you can review it.

**Comment by Nityom** [comment]
Hey @PriteshKiri  I would like to work on this issue

**Comment by PriteshKiri** [comment]
Hey @prashantrai-30,

Thanks for your contribution 🙌 

Can you please link the issue to your PR?

**Comment by PriteshKiri** [comment]
Hey @Nityom, this issue has already been assigned.  Please check out other open issues under the `community contribution`.

**Comment by ishan657** [comment]
Hlo @GrowwithNaveen .. This is my first time contributing to open source and I would love to start with this issue .. kindly assign me this issue and I will start working on it right away
Thankyou 😺

**Comment by prashantrai-30** [comment]
The PR #10914 will close this issue.

**Comment by GrowwithNaveen** [comment]
Hi @prashantrai-30,

The template looks good, but there are 39 unnecessary file changes in the codebase with the PR submission. We only need to update the `definition.json` and `manifest.json` files when submitting the PR. Can you please review this?

Feel free to reach out in the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) channel if you need any support.

Thanks!

**Comment by prashantrai-30** [comment]
Hi @GrowwithNaveen ,
Can you tell what can I do now :)

**Comment by PriteshKiri** [comment]
Hey @prashantrai-30,

Please follow the template guidelines shared in the issue description. Drop your queries in our [community](https://tooljet.slack.com/archives/C05SSQF138F) if you need any assistance with that.

**Comment by prashantrai-30** [comment]
Hi @PriteshKiri,
I have raised a new PR,please review it and suggest if you want any changes :)

**Comment by PriteshKiri** [comment]
Sure! We'll review and get back to you if needed any changes.

**Comment by prashantrai-30** [comment]
Hey @GrowwithNaveen,
Any update about the progress?

**Comment by PriteshKiri** [comment]
Hey @prashantrai-30 

The PR will be merged in a day or two. Thanks for you patience.

**Comment by GrowwithNaveen** [comment]
Hey @prashantrai-30  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!
