### ISSUE TITLE
Add a default value to the Datepicker widget properties

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1088]
### What is the expected behaviour?
> `Default Value `should have a default value

![Screenshot 2021-10-15 at 5 16 44 PM](https://user-images.githubusercontent.com/67645175/137482295-80cba0c6-64cd-47ee-b511-1ff4adc946a4.png)

### What is the current behaviour?
> Default value is empty

![Screenshot 2021-10-15 at 5 17 30 PM](https://user-images.githubusercontent.com/67645175/137482258-8769b841-4cd3-472f-ab76-743ee00c95b7.png)

### How to reproduce the issue?
 Drag Datepicker Widget from widget manager to the canvas

### Any possible solutions?
Add a default value to the widget properties.

```
defaultValue: { value: '01/04/2021' }
```

### Can you identify the location in the driver source code where the problem exists?
`/frontend/src/Editor/Components/components.js > **line 388**`

**Comment by VedanthB** [comment]
i have created a PR
