### ISSUE TITLE
Community template: Placeholder Image Generator

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#10888]
**Description:**
The Placeholder Image Generator template creates customizable placeholder images for web development, design, or content use, allowing users to specify size, colors, format, and custom text.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1zD0lfozBjuectZlApzq5s6y5RHZ3KW0CSHiuQKsYzYk/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within **7 working days** and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within **7 working days** or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by SanchitMahajan236** [comment]
I would love to contribute to this issue. Please assign me this issue.

**Comment by An525ish** [comment]
hey, I would like to work on this

**Comment by naaa760** [comment]
Hello! @GrowwithNaveen :)

I want to contribute to this issue, please assign me this issue.

**Comment by Shubhamsk07** [comment]
plz , assign me this issue.

**Comment by akashvivek** [comment]
Hey can you assign this to me? I would like to Contribute init

**Comment by PranayChavhan** [comment]
Hi, @GrowwithNaveen  I'm excited to contribute to the Placeholder Image Generator template. I have taken a look at ToolJet and am getting used to the platform. I can **complete the task within the 7-day deadline** and ensure everything works as expected. **Please assign this issue to me**—I'm eager to start contributing to the open-source community!

Looking forward to your response!
Pranay

**Comment by Mefisto04** [comment]
Hi @GrowwithNaveen ,

I'd love to contribute to the **Placeholder Image Generator** template. Please assign this issue to me so I can start working on it.

**Approach:**
- Develop customizable options for size, colors, text, and format in the image generator.
- Ensure the user interface is intuitive and aligns with the current design.
- Some Test functionality.

**Comment by Avii-KS** [comment]
Hi @GrowwithNaveen can I be assigned to solve this issue?
This is my first time takin part in an Open Source Contribution and i would love to work on this issue!

**Comment by A-1evi** [comment]
Hey @PriteshKiri kindly let me know if this issue is assigned . I would like to work on this issue.

**Comment by PriteshKiri** [comment]
@SanchitMahajan236 assigned!

Please note that the deadline for this task is 7 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PriteshKiri** [comment]
@A-1evi @Avii-KS @Mefisto04 @PranayChavhan @akashvivek @Shubhamsk07 @naaa760 @An525ish please check out other issues with the `community contribution` label.

**Comment by PriteshKiri** [comment]
Hey @SanchitMahajan236 ,

Any updates on the issue? Please let me know if you are facing any difficulties.

**Comment by SanchitMahajan236** [comment]
Working on it. I will generate a PR by day after tomorrow.

**Comment by PriteshKiri** [comment]
Hey @SanchitMahajan236!!

Any updates on the issue?

**Comment by SanchitMahajan236** [comment]
I will generate a PR by today.

**Comment by PriteshKiri** [comment]
Hey @SanchitMahajan236,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by GrowwithNaveen** [comment]
Hi @SanchitMahajan236, the template looks good overall. Great work!

There's just one bug: when entering "Custom text," the text doesn't update in the image unless we change the text or background color. Can you please fix this?

I've attached a video grab for reference.

https://github.com/user-attachments/assets/834d77c8-d02e-4fe4-b33b-3d3dc54623df

**Comment by GrowwithNaveen** [comment]
Sure @SanchitMahajan236, let us know when it's completed for review. Feel free to reach out if you have any queries.

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress.

**Comment by PriteshKiri** [comment]
This issue is not open for contribution 🙌

**Comment by PriteshKiri** [comment]
@vikashsprem  assigned!! 

Please make sure that,
 - You sign the CLA after submitting your PR.
 - You complete this task in 7 days from the day of the assignment.  
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by vikashsprem** [comment]
Hey @PriteshKiri, One small doubt, `document.getElementById("width").value`  How is the id getting set in the template when I create a text input box? Like any of the input box (let's say width)

<img width="935" alt="Screenshot 2024-11-22 at 2 17 09 PM" src="https://github.com/user-attachments/assets/3ee44793-5c91-417f-be27-17519929bcfa">

**Comment by PriteshKiri** [comment]
@GrowwithNaveen can you please look into this?

**Comment by vikashsprem** [comment]
Plz Check out this once and see the output where I am wrong.

<img width="1390" alt="Screenshot 2024-11-22 at 6 17 41 PM" src="https://github.com/user-attachments/assets/7046a41e-515a-4add-a1f8-d5d9d681e316">

**Comment by PriteshKiri** [comment]
Hey @vikashsprem 

Please use this to access the values from the components

`
const x = components.numberinput1.value
return x
`

I'll recommend you to go through the [Quick start](https://docs.tooljet.com/docs/getting-started/quickstart-guide) guide and [ToolJet concepts](https://docs.tooljet.com/docs/tooljet-concepts/what-are-components) in our docs to learn how to build apps in ToolJet.

**Comment by vikashsprem** [comment]
> Hey @vikashsprem
> 
> Please use this to access the values from the components
> 
> ```
> const x = components.numberinput1.value;
> 
> return x
> ```
> 
> I'll recommend you to go through the [Quick start](https://docs.tooljet.com/docs/getting-started/quickstart-guide) guide and [ToolJet concepts](https://docs.tooljet.com/docs/tooljet-concepts/what-are-components) in our docs to learn how to build apps in ToolJet.

Got it. Thanks

**Comment by vikashsprem** [comment]
Hey @PriteshKiri @GrowwithNaveen, This task is almost completed, but some challenges need to be addressed. Plz help me out.

<img width="1392" alt="Screenshot 2024-11-24 at 2 11 27 PM" src="https://github.com/user-attachments/assets/88ba92b5-949c-412f-a877-cbadfe3d489f">


1. Image URL is dynamically updated `queries.runjs.data` when runjs execute and when I update any component value like width runjs run every time and while runjs running placeholder image URL is an empty object. Getting a warning in the debugger. checkout below sc and when runjs completes their execution it returns the URL of the image getting set in placeholder and working fine.
<img width="338" alt="Screenshot 2024-11-24 at 2 18 10 PM" src="https://github.com/user-attachments/assets/03376f24-a9d9-4ef4-9bab-b71f07be21aa">

2. Copy Image: I can copy only the `.png` format image when I change to `.jpg, .svg` it's not getting copied to the clipboard. (Trying to resolve it). If you have any suggestions plz leave them here.

**Comment by GrowwithNaveen** [comment]
Hi @vikashsprem,
1. This is fine; since the URL updates dynamically, we can ignore the warning message from the debugger.
2. As we are only copying the image to the clipboard, formatting is not required, and we can retain it as a `.png` file.

Let us know if you have any questions!

**Comment by PriteshKiri** [comment]
Hey @vikashsprem  ,

Thank you so much for your contribution! 🙌

Can you please check the comment added on the PR?

**Comment by GrowwithNaveen** [comment]
@abhinabaadhikari can you please review the PR once and confirm?

**Comment by GrowwithNaveen** [comment]
Hi @vikashsprem,

The application looks great! Thank you for your amazing open-source contribution. We’ll handle the deployment from here and keep you updated.

Happy coding!

**Comment by GrowwithNaveen** [comment]
Hey @vikashsprem  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!
