### ISSUE TITLE
Add a default value to the Textinput widget properties

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1089]
### What is the expected behaviour?
> `Default Value ` should have a default value

![Screenshot 2021-10-15 at 5 54 52 PM](https://user-images.githubusercontent.com/67645175/137486298-778f9d72-4edf-4bd1-bbc4-7c605b5413f0.png)

**Loom**: https://www.loom.com/share/02c50d06b20e4387b51f9a4a2193951d

### What is the current behaviour?
> Default value is empty

![Screenshot 2021-10-15 at 5 54 27 PM](https://user-images.githubusercontent.com/67645175/137486501-bd5b6bda-6e85-4ad4-8dd1-275a2ff19d6b.png)

### How to reproduce the issue?
 Drag Textinput Widget from widget manager to the canvas

### Any possible solutions?
Add a default value to the widget properties.

```
value: { value: 'Hello 👋🏻 ' }
```

### Can you identify the location in the driver source code where the problem exists?
`/frontend/src/Editor/Components/components.js > **line 298**`

**Comment by idan22moral** [comment]
working on it (:

**Comment by samyakjain10** [comment]
Hey @arpitnath. Can i work on this issue?
