### ISSUE TITLE
[docs]: Update the documentation for the Steps Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10899]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/steps

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. 
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Add a more descriptive introduction
- Replace the word "widget" with "component" wherever applicable. ( please do not update the URLs)
- Update the content of the "Description" column in the Events Table [reference](https://docs.tooljet.com/docs/widgets/text-input/#events)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/steps.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/steps.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by prathamesh424** [comment]
can you assign this issue to me

**Comment by PriteshKiri** [comment]
@prathamesh424 assigned. Happy coding! 

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PriteshKiri** [comment]
Thanks for your contribution @prathamesh424  🙌 

We appreciate your efforts!
