### ISSUE TITLE
[docs]: Update the documentation for the Tags Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10897]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/tags

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. 
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Add a more descriptive introduction
- Replace the word "widget" with "component" wherever applicable. ( please do not update the URLs)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/tags.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/tags.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by sanketshinde3001** [comment]
I'm interested in making pr for this issue.

**Comment by PriteshKiri** [comment]
Hey @sanketshinde3001,

Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by Vaishnavi-Raykar** [comment]
Sir , I'm interested in making pr for this issue.

**Comment by PriteshKiri** [comment]
@Vaishnavi-Raykar  assigned!!

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by RashmitTopG** [comment]
I would also like to work on this issue. Can you please assign me this .

**Comment by PriteshKiri** [comment]
Thanks for you contribution @Vaishnavi-Raykar 🙌

**Comment by PriteshKiri** [comment]
Hey @RashmitTopG,

Please check out other issues with the community contribution label. This issue has already been assigned.
