### ISSUE TITLE
[docs]: Update the documentation for the Statistics Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10901]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/statistics

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. 
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Add a more descriptive introduction
- Replace the word "widget" with "component" wherever applicable. ( please do not update the URLs)
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/statistics.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/statistics.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PriteshKiri** [comment]
@sahilborse assigned. Happy coding! 

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by Pritish2005** [comment]
/attempt#10901

@sahilborse please assign it to me

**Comment by Rishikesh63** [comment]
@PriteshKiri  i am interested to work on this project could you please assign me

**Comment by PriteshKiri** [comment]
Hey @Pritish2005 @Rishikesh63, this issue has already been assigned.  

Please check out other open issues under the `community contribution`.

**Comment by PriteshKiri** [comment]
Hey @sahilborse,

Any updates on the issue?

**Comment by developer-mohitsoni** [comment]
Hey @PriteshKiri  can you please assign this issue to me?

**Comment by PriteshKiri** [comment]
Hey @developer-mohitsoni, this issue has already been assigned.  

Please check out other open issues under the `community contribution`.

**Comment by sahilborse** [comment]
@PriteshKiri done making changes please verify
https://github.com/ToolJet/ToolJet/pull/10929#issue-2578677396
check the PR

**Comment by PriteshKiri** [comment]
Thanks for your contribution @sahilborse 🙌

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress on PR.

**Comment by PriteshKiri** [comment]
This issue is open for contribution!

**Comment by baibhavKumar1** [comment]
@PriteshKiri please assign this to me.

**Comment by dorkydhruv** [comment]
@PriteshKiri looks doable. Assign this to me.

**Comment by kartikmehta18** [comment]
@PriteshKiri plz assign me

**Comment by AsifQamar** [comment]
@PriteshKiri assign me this

**Comment by PriteshKiri** [comment]
@baibhavKumar1 assigned. Happy coding! 

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by Salonisaroha** [comment]
please assign this issue to me @PriteshKiri

**Comment by sahilborse** [comment]
@PriteshKiri  Check the updated PR 
gh pr checkout 10956

**Comment by sahilborse** [comment]
https://github.com/ToolJet/ToolJet/pull/10956

**Comment by PriteshKiri** [comment]
Hey @sahilborse,

We appreciate your efforts! However, the issue was reassigned to another contributor, so we’ll have to close your PR.

We look forward to your contributions on other issues. Feel free to check out those labeled as community contributions.

**Comment by PriteshKiri** [comment]
Thanks for your contribution @baibhavKumar1
