### ISSUE TITLE
Home Page Support secions's branding

### ISSUE THREAD

**Issue by awezmirza** [ToolJet/ToolJet#10908]
![image](https://github.com/user-attachments/assets/b6af7f99-abf5-4fbf-8f96-2a9806f797dd)
### Is your proposal related to a problem?

The ToolJet Branding is getting vanished on black bg.

### Describe the solution you'd like

We can move it downwards so that it will be visible in all the conditions.

### If the feature is approved, would you be willing to submit a PR?

I would like to work on this issue under hacktoberfest tag.

**Comment by awezmirza** [comment]
@PriteshKiri

**Comment by PriteshKiri** [comment]
Hey @awezmirza ,

Thanks for opening this issue! Unfortunately, website-related issues are not open for community contributions. Only issues with the `community contribution` label are available for contributions.

Our internal team will take care of this one.

**Comment by awezmirza** [comment]
Ok @PriteshKiri , Thanks!
