### ISSUE TITLE
[docs]: Fix wrong redirection URL

### ISSUE THREAD

**Issue by utsavdotdev** [ToolJet/ToolJet#10917]
### Summary

The documentation contains a broken redirection link that leads to an incorrect or missing page, affecting the user experience at Workspace Variable section.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/org-management/workspaces/workspace-variables

### Steps to reproduce the issue

1. Go to https://docs.tooljet.com/docs/org-management/workspaces/workspace-variables
2. Click on the link that should redirect to another section or page.
3. Observe the broken or incorrect redirection.

### Additional Information

![image](https://github.com/user-attachments/assets/200beedd-cc0d-45de-8dca-31f2ca3f3f51)

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PriteshKiri** [comment]
Thanks for your contribution @utsavdotdev 🙌

**Comment by Tilek04** [comment]
Hi, is this issue relevant now, can i contribute on this issue? 
thanks!

**Comment by PriteshKiri** [comment]
Hey @Tilek04, this issue has already been assigned.  

Please check out other open issues under the `community contribution`.
