### ISSUE TITLE
[docs]: Broken Link at Environment Variables Setup

### ISSUE THREAD

**Issue by utsavdotdev** [ToolJet/ToolJet#10918]
### Summary

The documentation contains a broken redirection link in the Environment Variables section that leads to an incorrect or missing page, negatively impacting the user experience.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/setup/env-vars/#enable-tooljet-database--optional-

### Steps to reproduce the issue

1. Go to https://docs.tooljet.com/docs/setup/env-vars#enable-tooljet-database--optional-.
2. Click on the link intended to redirect to the ToolJet Database enabling setup section.
3. Observe the broken or incorrect redirection.

### Additional Information

![image](https://github.com/user-attachments/assets/833a3948-9d34-47a1-9da3-5b112bd1b9b3)

Correct redirection url: https://docs.tooljet.com/docs/tooljet-db/tooljet-database/#enabling-the-tooljet-database-for-your-instance

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PriteshKiri** [comment]
Thanks for your contribution @utsavdotdev 🙌
