### ISSUE TITLE
Community template: Library management system

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#10913]
**Description:**
The Library Management System template provides a comprehensive solution for managing a wide range of library resources. This template streamlines resource management and enhances the user experience with efficient cataloging and search capabilities.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1J0APNtCD5i5QN3OwXEyfUmM3y6Z_xK4kROL8dh_1epA/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within **7 working days** and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within **7 working days** or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by A-1evi** [comment]
Hey @PriteshKiri kindly let me know if this issue is assigned . I would like to work on this issue.

**Comment by PriteshKiri** [comment]
Hey @A-1evi ,
 
Thank you for your interest in contributing! 

We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by VirenderBhambra** [comment]
I would like to work on this issue.

**Comment by PriteshKiri** [comment]
@VirenderBhambra  assigned!!

Please note that the deadline for this task is 7 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by sahilborse** [comment]
@PriteshKiri I would like to work on this issue, please assign it to me

**Comment by PriteshKiri** [comment]
Hey @sahilborse  , We greatly appreciate your interest. 

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

Thank you for your understanding.

**Comment by VirenderBhambra** [comment]
working on it.

**Comment by VirenderBhambra** [comment]
> @VirenderBhambra assigned!!
> 
> Please note that the deadline for this task is 7 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

@PriteshKiri Can u please send this community invite again. The link is expired.

**Comment by PriteshKiri** [comment]
Sure! Please join via [this](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) link.

**Comment by PriteshKiri** [comment]
Hey @VirenderBhambra!

Any updates on the issue? Please let me know if you are facing any issues.

**Comment by VirenderBhambra** [comment]
Hey @PriteshKiri It is almost complete , have mentioned some issues in contributions section. [https://tooljet.slack.com/archives/C05SSQF138F/p1729078761733339?thread_ts=1728991213.229879&cid=C05SSQF138F](url)

**Comment by PriteshKiri** [comment]
Got it @VirenderBhambra!!

Let me know if you need any further assistance.

**Comment by PriteshKiri** [comment]
Hey @VirenderBhambra ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by GrowwithNaveen** [comment]
Hi @VirenderBhambra 
Thanks for submitting the PR. We reviewed it, and it looks good! We’ll take care of the deployment from here and keep you updated on the progress.

Thanks for the great contribution. Happy coding!

**Comment by GrowwithNaveen** [comment]
Hey @VirenderBhambra  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!
