### ISSUE TITLE
Add a default value to the Numberinput widget properties 

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1091]
### What is the expected behaviour?
> `Default Value ` should have a default value

![Screenshot 2021-10-15 at 6 16 51 PM](https://user-images.githubusercontent.com/67645175/137489402-dee14577-1841-4d4d-986f-8ed3a646c2e6.png)

**Loom**: https://www.loom.com/share/485d0aca20034bc8a919e7c62c3133a9

### What is the current behaviour?
> Default value is empty

![Screenshot 2021-10-15 at 6 20 35 PM](https://user-images.githubusercontent.com/67645175/137489546-18c9a179-0f19-4c64-b4e3-2eed412fedab.png)

### How to reproduce the issue?
 Drag Numberinput Widget from widget manager to the canvas

### Any possible solutions?
Add a default value to the widget properties.

```
value: { value: '99' }
```

### Can you identify the location in the driver source code where the problem exists?
`/frontend/src/Editor/Components/components.js > **line 339**`

**Comment by trevorbayless** [comment]
Can you please assign this to me?
