### ISSUE TITLE
[docs]: Broken Link at Super Admin License Section

### ISSUE THREAD

**Issue by utsavdotdev** [ToolJet/ToolJet#10919]
### Summary

The documentation contains a broken redirection link in the Super Admin License section that leads to an incorrect or missing page, negatively impacting the user experience.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/Enterprise/superadmin#license

### Steps to reproduce the issue

1. Go to https://docs.tooljet.com/docs/Enterprise/superadmin#license.
2. Click on the link intended to redirect to the licensing information.
3. Observe the broken or incorrect redirection.

### Additional Information

![image](https://github.com/user-attachments/assets/3aa48182-087f-4ce4-8e0b-e16ebb96789e)

Correct url: https://docs.tooljet.com/docs/org-management/licensing/self-hosted

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PriteshKiri** [comment]
Thanks for your contribution @utsavdotdev!!
