### ISSUE TITLE
[docs]: Update the documentation for the Spinner

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10926]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/spinner

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. make the **fx** lowercase and bold )
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( please do not update the URLs)
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/spinner.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/spinner.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by lakshita10341** [comment]
I would like to work on it. Please assign it to me

**Comment by sahilborse** [comment]
https://github.com/ToolJet/ToolJet/pull/10929#issue-2578677396
check the PR

**Comment by lakshita10341** [comment]
#10931 
done the changes

**Comment by PriteshKiri** [comment]
Thanks or your contribution @lakshita10341 🙌

**Comment by PriteshKiri** [comment]
Hey @lakshita10341 ,
Please use [this](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) link to join the community

**Comment by RudraPratik30** [comment]
Unassigned due to lack of progress.
This issue is up-for-grab now!

**Comment by himanshubalani** [comment]
Hey I'd like to work on this!

**Comment by ExPl0iT-29** [comment]
Assign me please!
Thankyou!

**Comment by AsifQamar** [comment]
@PriteshKiri assign me this

**Comment by PriteshKiri** [comment]
@himanshubalani assigned. Happy coding! 

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.
