### ISSUE TITLE
[docs]: Update the documentation for the Range Slider

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10927]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/range-slider

**Formatting updates:**
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( please do not update the URLs)
-  Layout Table:
   - Replace the header "Layout" with "Devices"
   - Update the Description and Expected Value columns [reference](https://docs.tooljet.com/docs/widgets/text-input#devices)
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/range-slider.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/range-slider.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by sahilborse** [comment]
@PriteshKirir please assign me this issue

**Comment by krishnadev7** [comment]
Hey @PriteshKiri i would like to work on this issue, please assign to me. Thanks

**Comment by prathamranjansingh** [comment]
Can you assign this to me @PriteshKiri

**Comment by PriteshKiri** [comment]
@avnish100 assigned!!

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @sahilborse @prathamranjansingh @krishnadev7 ,

We greatly appreciate your interest. However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

We hope you understand our decision.

**Comment by avnish100** [comment]
Hey @PriteshKiri , The Slack invitation link doesn't seem to work. Is there any alternative way i can join?

**Comment by PriteshKiri** [comment]
Hey @avnish100,
Please use [this](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) link to join the community

**Comment by avnish100** [comment]
Hey @PriteshKiri raised a PR, please let me know if everything looks good.

**Comment by PriteshKiri** [comment]
Thanks for your contribution @avnish100 🙌
