### ISSUE TITLE
[docs]: Several Broken Link of Tooljet Database section

### ISSUE THREAD

**Issue by utsavdotdev** [ToolJet/ToolJet#10920]
### Summary

The documentation contains a broken redirection link in the Form Component Usage section that leads to an incorrect or missing page, negatively impacting the user experience.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/how-to/use-form-component

### Steps to reproduce the issue

1. Go to https://docs.tooljet.com/docs/how-to/use-form-component.
2. Click on the link intended to redirect to the ToolJet Database section.
3. Observe the broken or incorrect redirection.

### Additional Information

![image](https://github.com/user-attachments/assets/543faa8b-8289-42cd-8224-e3702345c89e)

Other broken link for same redirection point(Tooljet Database):
1. https://docs.tooljet.com/docs/data-sources/overview#default-data-sources
2. https://docs.tooljet.com/docs/dashboard

Correct Url: https://docs.tooljet.com/docs/tooljet-db/tooljet-database/

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PriteshKiri** [comment]
Thanks for your contribution @utsavdotdev.
