### ISSUE TITLE
[docs]: Update the documentation for the Star Rating

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10925]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/star-rating

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. make the **fx** lowercase and bold )
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( please do not update the URLs)
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/star-rating.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/star-rating.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by sahilborse** [comment]
@PriteshKiri please assign this issue to me

**Comment by krishnadev7** [comment]
@PriteshKiri please assign to me if possible

**Comment by OlibhiaGhosh** [comment]
I would like to work on this issue!

**Comment by PriteshKiri** [comment]
Hey @krishnadev7  , We greatly appreciate your interest. 

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

We hope you understand our decision and thank you for your understanding.

**Comment by PriteshKiri** [comment]
@OlibhiaGhosh  assigned. Happy coding! 

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by sahilborse** [comment]
@PriteshKiri  please assign it to me i can complete it faster and more efficiently

**Comment by OlibhiaGhosh** [comment]
Thanks a lot @PriteshKiri !

I have started working on it and will be completing it within 3 days positively!

**Comment by PriteshKiri** [comment]
Hey @OlibhiaGhosh ,

Thanks for your contribution!!

You use [this](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) link to join our community

**Comment by Nityom** [comment]
Hii @PriteshKiri , I would like to work on this issue
