### ISSUE TITLE
Add a default value to the Textarea widget properties

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1092]
### What is the expected behaviour?
> `Default Value ` should have a default value

![Screenshot 2021-10-15 at 7 07 42 PM](https://user-images.githubusercontent.com/67645175/137496542-d5e88058-fc48-4cd4-92fb-90aee87e88ab.png)

### What is the current behaviour?
> Default value is empty

![Screenshot 2021-10-15 at 7 08 07 PM](https://user-images.githubusercontent.com/67645175/137496655-3357c50b-7802-4f50-95b7-609a218e5547.png)

### How to reproduce the issue?
 Drag Textarea Widget from widget manager to the canvas

### Any possible solutions?
Add a default value to the widget properties.

```
value: { value: 'ToolJet is an open-source low-code platform for building and deploying internal tools with minimal engineering efforts 🚀 ' }
```

### Can you identify the location in the driver source code where the problem exists?
`/frontend/src/Editor/Components/components.js > **line 566**`

**Comment by saideepesh000** [comment]
Hi @arpitnath , please assign this to me
