### ISSUE TITLE
[docs]: Update the documentation for the QR Scanner

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10928]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/qr-scanner

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. make the **fx** lowercase and bold )
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Events Tabel:
   - Update the event name from "onDetect" to "On detect"
   - Update the description of the "On detect" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence formatting from the given reference )
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/qr-scanner.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/qr-scanner.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by void-hr** [comment]
@PriteshKiri can you assign me ?

**Comment by rthakur2712** [comment]
Hi !! @PriteshKiri
I have made a PR, can you please review.

**Comment by PriteshKiri** [comment]
Hey @rthakur2712!

Please start working on an issue only after it has been officially assigned to you. Since this issue has already been assigned, kindly check out other issues with the `community contribution` label.

Thank you for your understanding!

**Comment by void-hr** [comment]
Thanks @PriteshKiri, I tried to join slack community link is no longer active.

**Comment by PriteshKiri** [comment]
@void-hr will look into it. Thanks for informing.

**Comment by void-hr** [comment]
@PriteshKiri drop your views, and I have a question why it is important to sign CLA ?

**Comment by PriteshKiri** [comment]
Thanks for your contribution @void-hr 🙌 

CLA ensures that all contributors have legally agreed to the project's terms regarding their contributions.

**Comment by PriteshKiri** [comment]
Hey @void-hr  ,
Please use [this](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) link to join the community
