### ISSUE TITLE
[docs]: Update the documentation for the Pagination

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10932]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/pagination

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. make the **fx** lowercase and bold )
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Events Tabel:
   - Update the description of the "On Page Change" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence formatting from the given reference )
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/pagination.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/pagination.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Suraj-kumar00** [comment]
HI @PriteshKiri, Can I work on this issue?
Please assign it to me.

**Comment by PrakharZippee** [comment]
Hi @PriteshKiri I would like to contribute to this issue. Can you assign it to me?

**Comment by PrakharBuliya** [comment]
Hi @PriteshKiri i would like to contribute on this issue. can you assign it to me?

**Comment by prathamranjansingh** [comment]
Can i work on this issue @PriteshKiri? Want to do more contribution

**Comment by Suraj-kumar00** [comment]
Hi @PriteshKiri, can you please assign the issue to me so that I can work on it?
I don't know why people don't follow community standards. Why without assigning anyone is working?

**Comment by PriteshKiri** [comment]
@Suraj-kumar00 assigned. Happy coding! 😊  

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by PriteshKiri** [comment]
@Derek-Boucher @PrakharBuliya @prathamranjansingh @Alok-Singh-ops please check out other open issues under the `community contribution`.

**Comment by PriteshKiri** [comment]
Hey @Suraj-kumar00 ,
Please use [this](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) link to join the community

**Comment by Suraj-kumar00** [comment]
Hi @PriteshKiri, how have you been?
Can you please review the draft pr and by the way i'll be open it tomorrow from draft to actuall PR.

**Comment by PriteshKiri** [comment]
Hey @Suraj-kumar00,

You just need to make changes in the two files mentioned in the issue. I recommend reading through the issue description carefully.

**Comment by Suraj-kumar00** [comment]
> Hey @Suraj-kumar00,
> 
> You just need to make changes in the two files mentioned in the issue. I recommend reading through the issue description carefully.

Got it @PriteshKiri opening PR soon...

**Comment by PriteshKiri** [comment]
Hey @Suraj-kumar00,

Any updates on the issue? Please let me know if you are facing any problems.

**Comment by Suraj-kumar00** [comment]
> Hey @Suraj-kumar00,
> 
> Any updates on the issue? Please let me know if you are facing any problems.

Hi @PriteshKiri, I opened the PR yesterday haven't you seen that?

**Comment by Suraj-kumar00** [comment]
Hi @PriteshKiri, I have opened the PR please review.
