### ISSUE TITLE
Email images in outlook are disproportionate

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#10958]
In outlook, the emails are disproportionately large. Ref screenshot - 

![Image](https://github.com/user-attachments/assets/3450515f-0390-4e05-891c-8bf7bddf30ec)

**Comment by rajesh2150** [comment]
Define Exact Width and Height in HTML:
Always specify both the width and height attributes in the image's HTML tag, even if you're using CSS for styling

Can You assist me 🍉@nechalmaggon .
Thank You.

**Comment by nechalmaggon** [comment]
@rajesh2150 Hey, thanks for showing your interest in the issue! However, this issue will be resolved by the internal team. Do keep an eye out for issues labeled as `up for grabs` - those are the ones open to the community! 
cc- @PriteshKiri
