### ISSUE TITLE
[docs]: Update the documentation for the Link Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10969]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/link

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Remove the description below the "Events" heading.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/link.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/link.md

**NOTE**
- Make sure you sign the CLA after submitting your PR.
-  _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.slack.com/) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by sikehish** [comment]
Would like to take this up!

**Comment by AsifQamar** [comment]
asignn

**Comment by officialcody** [comment]
Hi @PriteshKiri ,
I would like to work on this isssue.

**Comment by AbhinavTheDev** [comment]
Assign this to me

**Comment by PriteshKiri** [comment]
@AsifQamar assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task is 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @officialcody @Atul1231 @AbhinavTheDev , this issue has been assigned.  

Please check out other open issues under the `community contribution` label.

**Comment by AsifQamar** [comment]
> @AsifQamar assigned. Happy Hacktoberfest! 🎃  
> 
> Please make sure that,  - You sign the CLA after submitting your PR.   - You complete this task is 3 days from the day of the assignment.      Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

ok thanks
