### ISSUE TITLE
Rename Rest API to REST API across the application interface

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#10961]

**Comment by FurquanAnwer** [comment]
Please assign this to me !

**Comment by FurquanAnwer** [comment]
@mansukh-tj Could you please give a little elaboration on this issue where exactly I need to rename it ?

**Comment by mansukh-tj** [comment]
Sure @FurquanAnwer 

This has to be updated on 2 places

1. On the data sources page 
![image](https://github.com/user-attachments/assets/276af321-e630-4c61-b251-8139344d9d01)


2. Inside app builder: after adding a REST API datasource from data source page, you will be able to view it 
![image](https://github.com/user-attachments/assets/c37617bd-a6d1-4725-a5b2-4f2481528502)


Let me know if you require more help!

**Comment by ishsarin** [comment]
Hi, I would like to work on this issue. Please assign this to me.

**Comment by FurquanAnwer** [comment]
Thanks @mansukh-tj

**Comment by mayurathavale18** [comment]
Hi,  would Like this issue to be assigned to me, thank you

**Comment by mansukh-tj** [comment]
Hi @FurquanAnwer,
Any updates on the issue? Please let me know if you are facing any problems.

**Comment by FurquanAnwer** [comment]
Hey @mansukh-tj , I went through the code and I saw that the name of these datasources are being fetched from the backend but I couldn't find in which files, these are mentioned or stored so that I can rename them. Enlighten me please on this.

**Comment by ganesh8056** [comment]
Hi @FurquanAnwer ,
To update the label for the REST API datasource, you can look into the manifest.json file in plugins/packages/restapi folder. And make sure the REST API data source is listed in a commonly used section on the Datasource page.

**Comment by mansukh-tj** [comment]
Any update @FurquanAnwer?

**Comment by mansukh-tj** [comment]
Since there is no response for this, we will be un-assigning this from @FurquanAnwer and taking it up internally.

**Comment by sky-39** [comment]
Is this issue still relevant. I would like to work on it.

**Comment by PriteshKiri** [comment]
Hey @sky-39 , 

Thank you for the PR! Unfortunately, this issue will be handled by the internal team.

For future contributions, here’s the ideal process:
1. Ask for an assignment on open issues with a `community contribution` label.
2. Once you have been assigned the issue then you can start working on it.
3. Raise the PR and link it to the assigned issue. 

Looking forward to your next contribution!
