### ISSUE TITLE
[docs]: Update the documentation for the PDF Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10968]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/pdf

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Devices Table
    - Update the content in "Description" and "Expected values" of the Devices Table - [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference, the rest should remain untouched )
    - Add a full stop at the end of the sentence in the Expected values column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/pdf.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/pdf.md

**NOTE**
- Make sure you sign the CLA after submitting your PR.
-  _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.slack.com/) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by dorkydhruv** [comment]
Please assign.

**Comment by sikehish** [comment]
Would love to take this up!

**Comment by kushal34712** [comment]
Please assign.

**Comment by Aniket7292** [comment]
Could you assign this to me

**Comment by AbhinavTheDev** [comment]
Please assign this to me

**Comment by PriteshKiri** [comment]
@dorkydhruv assigned. Happy Hacktoberfest! 🎃  

Please note that
 - You sign the CLA after submitting your PR. 
 -  The deadline for this task is 3 days from the day of the assignment.   
 
Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @AbhinavTheDev @sikehish @kushal34712 @Aniket7292,  please check out other issues with the `community contribution` label.

**Comment by PriteshKiri** [comment]
Hey @Sejals-54, this issue has already been assigned.  Please check out other open issues under the `community contribution`.

**Comment by dorkydhruv** [comment]
Hi @PriteshKiri, hope you doing well.
I have created a [pr](https://github.com/ToolJet/ToolJet/pull/10987) for the issue. Please review it and let my know if it required any changes.

**Comment by PriteshKiri** [comment]
Hey @dorkydhruv ,

Thank you so much for your contribution! 🙌 

Please keep an eye on your PR, as we may add some review comments if needed before merging it.
