### ISSUE TITLE
[docs]: Update the documentation for the Iframe Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10971]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/iframe

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( please do not update the URLs)
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/iframe.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/iframe.md

**NOTE**
- Make sure you sign the CLA after submitting your PR.
-  _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.slack.com/) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by vrushabhgawas14** [comment]
assign me. I would like to work on this issue.

**Comment by PriteshKiri** [comment]
Hi @vrushabhgawas14,   

Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by dagenius007** [comment]
@PriteshKiri I can take up this one.

**Comment by PriteshKiri** [comment]
@dagenius007  assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task is 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by dagenius007** [comment]
@PriteshKiri can I get access to push. I am unable to create a PR.

**Comment by PriteshKiri** [comment]
Hey @dagenius007!!

Everyone has access to create the PR. Make sure you have done the fork of the repository. Please let me know if you need any help.

**Comment by PriteshKiri** [comment]
Hey @dagenius007 ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by dagenius007** [comment]
@PriteshKiri I am yet to get an approval. Any reason why ?

**Comment by PriteshKiri** [comment]
Hey, @dagenius007!!

Your PR will be merged soon this week. Will let you know if needed any changes before merging it.

**Comment by PriteshKiri** [comment]
Hey @sahilborse,

This issue has already been assigned. I’d request you to please comment on issues that are currently unassigned only.

You can check out other open issues under the `community contribution` label. Thanks!
