### ISSUE TITLE
[docs]: Update the documentation for the Image Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10970]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/image

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- In the Events Tabel, update the description of the "On click" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference )
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/image.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/image.md

**NOTE**
- Make sure you sign the CLA after submitting your PR.
-  _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.slack.com/) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by devagn611** [comment]
Working on it @PriteshKiri

**Comment by devagn611** [comment]
Kindly review my request for PR/MR #10975  at your earliest convenience.

**Comment by PriteshKiri** [comment]
Hey @devagn611 ,

Thanks for your contribution! 

Just a reminder to please start working on an issue only after it has been officially assigned to you. We’re approving the PR this time, but please keep this in mind for future contributions.

Thank you for your understanding!

**Comment by devagn611** [comment]
Okay @PriteshKiri ,
I'll make sure to take care of this from now on.
Thank you!

**Comment by OoONANCY** [comment]
please assign it to me

**Comment by PriteshKiri** [comment]
@Atul1231 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @OoONANCY, this issue has been assigned.  Please check out other open issues under the `community contribution` label.

**Comment by Atul1231** [comment]
@PriteshKiri Hii! I have created a pull request for issue #10970
Please! review it.

**Comment by sahilborse** [comment]
@PriteshKiri  please assign this issue to me
