### ISSUE TITLE
[docs]: Update the documentation for the Divider Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10977]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/divider

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/divider.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/divider.md

**NOTE**
- Make sure you sign the CLA after submitting your PR.
-  _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.slack.com/) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by AryanK1511** [comment]
Hello @PriteshKiri! I would love to work on this. Are you able to assign it to me?

**Comment by PriteshKiri** [comment]
Hi @vrushabhgawas14,   

Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by PriteshKiri** [comment]
@AryanK1511 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task is 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by dagenius007** [comment]
Hello @PriteshKiri I am also new to contributing here, do you mind assigning to a task I will like to take up too.

**Comment by PriteshKiri** [comment]
Hey @dagenius007, this issue has already been assigned.  Please check out other open issues under the `community contribution`.

**Comment by AryanK1511** [comment]
@PriteshKiri I have sent in a fix. Lemme know if you need me to make any changes

**Comment by PriteshKiri** [comment]
Hey @AryanK1511,

Thank you so much for your contribution! 🙌 

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by sahilborse** [comment]
@PriteshKiri please assign me this issue #10977
