### ISSUE TITLE
[docs]: Update the documentation for the Icon Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10972]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/icon

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Event Table
    - Remove the description below the "Events" heading.
    - Update the content in the "Description" of "On hover" and "On click" events - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference, the rest should remain untouched )
    - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/icon.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/icon.md

**NOTE**
- Make sure you sign the CLA after submitting your PR.
-  _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.slack.com/) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by vrushabhgawas14** [comment]
I would like to work on this issue. Assign me.

**Comment by PriteshKiri** [comment]
Hi @vrushabhgawas14,   

Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by sikehish** [comment]
Would like to take this up!

**Comment by Atul1231** [comment]
\assign

**Comment by mohdjami** [comment]
@PriteshKiri Can you assign this issue to me? I would like to work on this one to start my journey with ToolJet. Thanks.

**Comment by AdityaDeshmukh2023** [comment]
Can you assign this issue to me

**Comment by PriteshKiri** [comment]
@sikehish  assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task is 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @AdityaDeshmukh2023  @Atul1231 @mohdjami , this issue has been assigned.  

Please check out other open issues under the `community contribution` label.

**Comment by AdityaDeshmukh2023** [comment]
Okay

**Comment by sikehish** [comment]
> @sikehish assigned. Happy Hacktoberfest! 🎃  
> 
> Please make sure that,  - You sign the CLA after submitting your PR.   - You complete this task is 3 days from the day of the assignment.      Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

Thank you for the oppurtunity. I am working on it.

**Comment by sikehish** [comment]
Hi @PriteshKiri , I've raised a PR #11002. Do let me know if anything needs to be modified. Thank you!

**Comment by PriteshKiri** [comment]
Hey @sikehish ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by PriteshKiri** [comment]
Hey @sahilborse,

This issue has already been assigned. I’d request you to please comment on issues that are currently unassigned only.

You can check out other open issues under the `community contribution` label. Thanks!
