### ISSUE TITLE
[docs]: Update the documentation for the File Picker Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10976]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/file-picker

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Event Table
    - Update the content in the "Description" of given 3 events - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference, the rest should remain untouched )
    - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/file-picker.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/file-picker.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by FurquanAnwer** [comment]
Assign this to me

**Comment by vrushabhgawas14** [comment]
I would like to work on this

**Comment by PriteshKiri** [comment]
Hey @FurquanAnwer, We greatly appreciate your interest. 

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

We hope you understand our decision and thank you for your understanding.

**Comment by PriteshKiri** [comment]
@vrushabhgawas14  assigned. Happy Hacktoberfest! 🎃  

Please note that
 - You sign the CLA after submitting your PR. 
 -  The deadline for this task is 3 days from the day of the assignment.   
 
Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by vrushabhgawas14** [comment]
Hey @PriteshKiri raised a PR, please drop your views.

**Comment by PriteshKiri** [comment]
Hey @vrushabhgawas14  ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.
