### ISSUE TITLE
[docs]: Update the documentation for the HTML Viewer Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10973]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/html

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/html.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/html.md

**NOTE**
- Make sure you sign the CLA after submitting your PR.
-  _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.slack.com/) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by vrushabhgawas14** [comment]
I would like to work on this

**Comment by PriteshKiri** [comment]
Hi @vrushabhgawas14,   

Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by himanshubalani** [comment]
Hey, I'd like to work on this.

**Comment by PriteshKiri** [comment]
Hi @himanshubalani ,   

Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by Atul1231** [comment]
\assign

**Comment by eyesee11** [comment]
I would like to work on this issue
With regards!

**Comment by AnkitKolhe149** [comment]
would like to work on this issue

**Comment by PriteshKiri** [comment]
Hey @AnkitKolhe149 @Atul1231 , this issue has been assigned.  

Please check out other open issues under the `community contribution`.

**Comment by PriteshKiri** [comment]
Hey @eyesee11,

Any updates on the issue?

**Comment by RudraPratik30** [comment]
Unassigning the issue due to lack of progress!
This issue is up-for-grab now!

**Comment by sikehish** [comment]
I'd like to take this up!

**Comment by AayushPaigwar** [comment]
Hey @RudraPratik30,  
I'd like to work on this.

**Comment by OoONANCY** [comment]
Please assign me this issue @RudraPratik30

**Comment by PriteshKiri** [comment]
@AayushPaigwar assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @sikehish,

We appreciate your interest in contribution. 

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. We hope you understand our decision. Thanks!

**Comment by PriteshKiri** [comment]
Hey @OoONANCY, this issue has been assigned.  Please check out other open issues under the `community contribution` label.

**Comment by AayushPaigwar** [comment]
Hello @PriteshKiri,
I have submitted the PR #11030
Please let me know if any changes are required.
