### ISSUE TITLE
Community template: URL splitter and parser

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11006]
**Description:**
The URL Splitter and Parser template allows developers to break down a URL into its individual components. It provides a user-friendly interface for inputting URLs and viewing their parsed components. This tool is designed to simplify URL analysis and debugging for developers working with web applications.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1A0UTLSN1dIC4Fq0BMv7mBC03zYdJmKqFh-uQrikKfu0/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within **7 working days** and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within **7 working days** or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by lakshita10341** [comment]
i'm interested in working on this. Please assign the issue to me

**Comment by vrushabhgawas14** [comment]
Intersted in working on this issue.

**Comment by PriteshKiri** [comment]
Hey @lakshita10341 @vrushabhgawas14 , We greatly appreciate your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

We hope you understand our decision. Thanks!

**Comment by rudrakshnalbalwar** [comment]
Hey @PriteshKiri  I would like to work on this issue. Could you please assign it to me

**Comment by mani3807** [comment]
Hey it's Manish I am first time contributor.
 Can you assign me the issue?

**Comment by Aditya-1838** [comment]
Hello @PriteshKiri ,
I would like to contribute to your project and noticed that Issue #11006 (URL splitter and parser) is currently unassigned. After reviewing the issue, I’m confident that I can help resolve it. Could you please assign it to me?

If there are any specific guidelines or additional context I should be aware of, feel free to let me know. I look forward to contributing to the project.

**Comment by Aditya-1838** [comment]
Hello @PriteshKiri ,
I would like to contribute to your project and noticed that Issue #11006 (URL splitter and parser) is currently unassigned. After reviewing the issue, I’m confident that I can help resolve it. As a first-time contributor to this project, I’m excited to get involved and make a positive contribution. Could you please assign the issue to me?

**Comment by PriteshKiri** [comment]
@mani3807  assigned. Happy Hacktoberfest! 🎃  

Please make sure that you complete this task in 4 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @rudrakshnalbalwar @Aditya-1838, this issue has been assigned.  Please check out other open issues under the `community contribution` label.

**Comment by mani3807** [comment]
Thanks for opportunity.

**Comment by PushpakChaudhari** [comment]
Interested on this issue please assign me

**Comment by PriteshKiri** [comment]
Hey @PushpakChaudhari ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by PriteshKiri** [comment]
Hey @mani3807 ,

Any updates on the issue? Please let me know if you are facing any problem

**Comment by mani3807** [comment]
I had tried it out but the issue i reposted on slack didn't solve.

**Comment by Aditya-1838** [comment]
Hi @PriteshKiri , I noticed this issue was assigned previously but hasn’t had any progress. If possible, could I give it a try? I'd love the chance to work on it. Thanks so much!

**Comment by PriteshKiri** [comment]
Hey @mani3807, As the deadline for this issue has passed, we'll need to unassign it. 

Please feel free to request assignments for future contributions. You can check issues labeled as `community contributions` for opportunities.

**Comment by PriteshKiri** [comment]
Hey @Aditya-1838 

Assigned the issue to you. Please make sure you complete the template within 7 day from the day of assignment.

Looking forward to your contribution 🙌

**Comment by nilaygit-10721** [comment]
please assign me this issue

**Comment by PriteshKiri** [comment]
@nilaygit-10721  assigned!! 

Please make sure that,
 - You sign the CLA after submitting your PR.
 - You complete this task in 3 days from the day of the assignment.  
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @Aditya-1838,

Any updates on the issue?

**Comment by PriteshKiri** [comment]
Hey @nilaygit-10721 ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by Aditya-1838** [comment]
@PriteshKiri  
I've made progress on issue , but I can't continue working on it effectively. I suggest reassigning it to avoid delays. Thank you for your understanding.

**Comment by nilaygit-10721** [comment]
so, @PriteshKiri now assign to me

**Comment by PriteshKiri** [comment]
Hey @nilaygit-10721,
Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by PriteshKiri** [comment]
This issue is now open for contributions 🙌

**Comment by Aspireve** [comment]
Heyy Hi!!
Looks like a lot of people werent able to sort this, would it be fine if I too give it a try.
I tried working on another issue #11259 but I was told that it was for the internal team for a future release

Btw, what exactly is a template? Is it a completely different webapp created or something else?

**Comment by PriteshKiri** [comment]
Hey @Aspireve 

Templates are the apps built in ToolJet. You can go through the template guidelines for better understanding.

Assigned the issue to you. Please make sure you complete the template within 7 days from the day of assignment. Feel free to reach out to our Slack community in case of any questions.

Looking forward to your contribution 🙌

**Comment by Aspireve** [comment]
Heyy Thanks for assigning, I'll start working on it

(Btw, I was able to understand quite a lot of stuff after reading the docs, thanks)

**Comment by Aspireve** [comment]
Heyy Hi!! @PriteshKiri 

I just completed building this, is this fine?

https://github.com/user-attachments/assets/305e826e-cc2a-4c8c-8fce-fb8eac18d0fc

Also for some reason on the Submission App, I was not able to find the template name nor generate the manifest file as no option was showing
![image](https://github.com/user-attachments/assets/7350e437-487d-47a9-bd81-3337a89b8333)

**Comment by PriteshKiri** [comment]
Thanks for sharing the video @Aspireve 

@GrowwithNaveen can you please check?

**Comment by GrowwithNaveen** [comment]
Hi @Aspireve,

The application looks great overall! However, two changes are necessary:

1. Please update the application description with the content from the "Overview" section of the [Template Feature List](https://docs.google.com/document/d/1A0UTLSN1dIC4Fq0BMv7mBC03zYdJmKqFh-uQrikKfu0/edit?usp=sharing).
2. Replace the `Rich Text Editor` component with a `Text Area` component for the Split URL output.

Please reload the submission app to check if the template name appears in the dropdown.

Feel free to check with us for any clarification.

Thanks!

**Comment by Aspireve** [comment]
Ohh sure I'll add this too

**Comment by Aspireve** [comment]
Heyy Hi!! @GrowwithNaveen 
Is this fine now?

![image](https://github.com/user-attachments/assets/73844aa0-a32c-4693-9f08-379eed3b2a95)

**Comment by GrowwithNaveen** [comment]
Hey @Aspireve,

This looks fantastic! Please go ahead and create the PR. Let us know if you need any help.

Thanks for the great contribution! 🎉

**Comment by GrowwithNaveen** [comment]
Hi @Aspireve, the application looks good. Thanks for the great contribution! 🎉

@abhinabaadhikari, could you please review the PR submission process and confirm if it’s ready for the next steps of merging?

**Comment by GrowwithNaveen** [comment]
Hi @Aspireve,

The PR has been validated and approved. We will merge it in a few days and keep you updated.

Thank you for your open-source contribution 🚀
