### ISSUE TITLE
[docs]: Update the documentation for the Color Picker Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11017]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/color-picker

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Events Tabel
  - Remove the description Under the "Events" heading.
  - Update the description of the "On change" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference )
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/color-picker.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/color-picker.md

**NOTE**
- Make sure you sign the CLA after submitting your PR.
-  _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.slack.com/) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Grimshinigami** [comment]
Hi can I be assigned this issue? @PriteshKiri

**Comment by Abhishek-53** [comment]
Hi @PriteshKiri can I work on this issue?

**Comment by PriteshKiri** [comment]
@NohaFahmi  assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @Grimshinigami @NohaFahm, this issue has been assigned.  Please check out other open issues under the `community contribution` label.

**Comment by mayurathavale18** [comment]
Can I be assigned this issue? I would like to work on this, thank you

**Comment by NohaFahmi** [comment]
Hi @PriteshKiri, PR is submitted :)

**Comment by sahilborse** [comment]
hi @PriteshKiri  please assign me this issue

**Comment by PriteshKiri** [comment]
Hey @NohaFahmi  ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by sahilborse** [comment]
/attempt #11017

@PriteshKiri  assign me this issue

**Comment by PriteshKiri** [comment]
Hey @sahilborse,

This issue has already been assigned. I’d request you to please comment on issues that are currently unassigned only.

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress!

**Comment by PriteshKiri** [comment]
This issue is open for community contribution 🙌

**Comment by Sonali9737** [comment]
Hey, can I take up this issue?
@PriteshKiri

**Comment by RudraPratik30** [comment]
@Sonali9737 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @Sonali9737 ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.
