### ISSUE TITLE
[docs]: Update the documentation for the Code Editor Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11018]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/code-editor

**Formatting updates:**
- Replace  "`Fx`" and "Fx" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- In the Exposed variables Tabel, update the description of the "value" variable - [reference](https://docs.tooljet.com/docs/widgets/text-input/#exposed-variables) ( Please just check the sentence structure from the given reference )
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/code-editor.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/code-editor.md

**NOTE**
- Make sure you sign the CLA after submitting your PR.
-  _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.slack.com/) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by JP-sDEV** [comment]
Hi @PriteshKiri, could I be assigned this task?

**Comment by Niyatijain-9** [comment]
HI @PriteshKiri , I want to work on the same. Could I be assigned this task?

**Comment by rudrakshnalbalwar** [comment]
Hey @PriteshKiri , I would like to work on this issue could you please assign this task to me..

**Comment by PriteshKiri** [comment]
@JP-sDEV assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @rudrakshnalbalwar  , We greatly appreciate your interest. 

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. We hope you understand our decision.

**Comment by PriteshKiri** [comment]
Hey @Niyatijain-9 , this issue has already been assigned.  Please check out other open issues under the `community contribution` label.

**Comment by mayurathavale18** [comment]
Please assign this issue to me

**Comment by JP-sDEV** [comment]
Pull request has been submitted! Cheers! :)

**Comment by sahilborse** [comment]
@PriteshKiri  please assign me this issue

**Comment by PriteshKiri** [comment]
Hey @JP-sDEV ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by PriteshKiri** [comment]
Hey @mayurathavale18 @sahilborse , this issue has already been assigned.  Please check out other open issues under the `community contribution` label.
