### ISSUE TITLE
all the drop down buttons are chaging when we click on one questions in get answers section

### ISSUE THREAD

**Issue by mannar-1** [ToolJet/ToolJet#11031]
![image](https://github.com/user-attachments/assets/9ce6daee-a62d-420c-aa1b-68286bf8682c)
as you can see in above image i clicked on question but all drop downs are getting rotated

please assign it to me as part of hackotberfest

**Comment by Rohan-3337** [comment]
/ assign

**Comment by mannar-1** [comment]
Sorry i did not get you? Can u please assign it to me so that i can start working

**Comment by PriteshKiri** [comment]
Hey @mannar-1 ,

Thanks for opening this issue! Unfortunately, website-related issues are not open for community contributions. Only issues with the `community contribution` label are available for contributions.

Our internal team will take care of this one.
