### ISSUE TITLE
[docs]: Update the documentation for the Circular Progressbar Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11037]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/circular-progress-bar

**Formatting updates:**
- Replace  "`Fx`" and "Fx" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Layout Tabel
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Add the "Expected value" column and update the content in the "Expected value" and "Description" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/circular-progress-bar.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/circular-progress-bar.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by asdotdev** [comment]
Can I work on this issue?

**Comment by DeepanshuYadav-code** [comment]
hey @PriteshKiri I would like to work on this. can you please assign me the issue #11038 under hacktoberfest

**Comment by PriteshKiri** [comment]
@DeepanshuYadav-code  assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @asdotdev !

Please start working on an issue only after it has been officially assigned to you. 

We greatly appreciate your interest. However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

Thank you for your understanding!

**Comment by PriteshKiri** [comment]
Hey @PushpakChaudhari ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by asdotdev** [comment]
Hey @PriteshKiri 

I understand and apologize for working on the issue before it was assigned to me, you can close my PR and assign it to other first-time contributors.

**Comment by RudraPratik30** [comment]
Any updates on this @DeepanshuYadav-code?

**Comment by DeepanshuYadav-code** [comment]
hello @PriteshKiri @RudraPratik30, I have made the desired changes and have created he pull request. kindly review it

**Comment by PriteshKiri** [comment]
Hey @DeepanshuYadav-code 

Thanks for the update. We'll review it and get back to you soon.
