### ISSUE TITLE
Community template: JSON formatter

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#11041]
**Description:**
The JSON Formatter template aims to simplify the process of working with JSON data by providing a user-friendly interface for formatting and customizing the display of JSON content.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1Gng5WD2gMmHrlci_beh1FJeeo5dBZ6CgkeCDa_8GOnQ/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within **7 working days** and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within **7 working days** or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by sanketshinde3001** [comment]
Interested

**Comment by sahilborse** [comment]
/attempt #11041
Hi,@GrowwithNaveen  i can work on this issue.

**Comment by Niyatijain-9** [comment]
hi @GrowwithNaveen could you please assign me this.

**Comment by PriteshKiri** [comment]
@Abhishek-53 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 7 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @sahilborse @Niyatijain-9 , Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by PriteshKiri** [comment]
Hey @sanketshinde3001 , We greatly appreciate your interest. 

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

Thank you for understanding!

**Comment by PentesterPriyanshu** [comment]
hi

**Comment by SarvT** [comment]
@PriteshKiri Hi Pritesh, I am a first-time contributor and would like to work on this issue! Can it be assigned to me?

**Comment by yuvi-mittal** [comment]
heyy @PriteshKiri , I am a first time contributor too , and would graetly appreaciate if i can be allotted to any of the requested issue

**Comment by rahulkumarbhagat-coder** [comment]
@GrowwithNaveen  @PriteshKiri can you assign me this issue?

**Comment by PriteshKiri** [comment]
Hey @Abhishek-53 ,

Any updates on the issue? Please let me know if you are facing any problem

**Comment by Abhishek-53** [comment]
@PriteshKiri Working on it and aiming to have it completed by tomorrow. I’ll keep you updated on my progress.

**Comment by Abhishek-53** [comment]
@PriteshKiri 
PR submitted #11171.

Kindly review.

**Comment by GrowwithNaveen** [comment]
Hi @Abhishek-53,

Thanks for submitting the PR. We reviewed it, and it looks good! We’ll take care of the deployment from here and keep you updated on the progress.

Thanks for the great contribution. Happy coding!

**Comment by PriteshKiri** [comment]
Hey @Abhishek-53,

Have added a comment on your PR. Can you please check?

**Comment by Abhishek-53** [comment]
> Hey @Abhishek-53,
> 
> Have added a comment on your PR. Can you please check?

Hi @PriteshKiri,
I'll make the necessary changes by tomorrow.

**Comment by Abhishek-53** [comment]
@PriteshKiri
 I have raised a new PR #11218  for the same. Kindly review.

**Comment by abhinabaadhikari** [comment]
Hi @Abhishek-53,

I’ve left a comment on your PR — could you please take a look?

**Comment by GrowwithNaveen** [comment]
Hey @Abhishek-53  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!
