### ISSUE TITLE
Datepicker actions clear and setDate

### ISSUE THREAD

**Issue by ChudoYudo** [ToolJet/ToolJet#11049]
### Is your proposal related to a problem?

There is no possibility  to clear or set date for Datepicker component
### Describe the solution you'd like

Add actions clear and setDate for Datepicker component
### Describe alternatives you've considered
-

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by ChudoYudo** [comment]
here is my PR 

https://github.com/ToolJet/ToolJet/pull/11050

**Comment by PriteshKiri** [comment]
Hey @ChudoYudo!

We really appreciate your contribution! Just a gentle reminder to please start working on an issue only after it has been officially confirmed by the team, as there might be similar fixes in the pipeline.

Let me check with the team about this issue and then get back to you.

Thank you for your understanding!

**Comment by PriteshKiri** [comment]
Hey @ChudoYudo,

Unfortunately, this feature is already in the pipeline and will be released soon in an upcoming version. I’ll have to close this issue for now, but we really appreciate your input and look forward to your future contributions.

Thanks again!

**Comment by ChudoYudo** [comment]
> Hey @ChudoYudo,
> 
> Unfortunately, this feature is already in the pipeline and will be released soon in an upcoming version. I’ll have to close this issue for now, but we really appreciate your input and look forward to your future contributions.
> 
> Thanks again!
Hey @PriteshKiri 
Got it, Thanks for your reply!
