### ISSUE TITLE
Community template: SQL query formatter

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#11042]
**Description:**
The SQL Formatter template is a tool designed for developers to format SQL queries and display them in a readable and easily understandable format. It offers customization options to suit different coding styles and preferences.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1VThiBT3R4XORR11E7opU6J_c6vH-1aOQK8VXt7KVZh0/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within **7 working days** and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within **7 working days** or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by sahilborse** [comment]
@GrowwithNaveen assign this issue to me
/attempt #11042

**Comment by Niyatijain-9** [comment]
hi @GrowwithNaveen could you please assign me this.

**Comment by Abhishek-53** [comment]
Hi @GrowwithNaveen @PriteshKiri can you please assign me this issue??

**Comment by PriteshKiri** [comment]
@Niyatijain-9 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 7 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @sahilborse @Abhishek-53 , Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by yuvi-mittal** [comment]
heyy , is the issue resolved ?

**Comment by Niyatijain-9** [comment]
> heyy , is the issue resolved ?

on it.

**Comment by PriteshKiri** [comment]
Hey @Niyatijain-9 ,

Any updates on the issue? Please let me know if you are facing any problem

**Comment by Niyatijain-9** [comment]
> Hey @Niyatijain-9 ,
> 
> Any updates on the issue? Please let me know if you are facing any problem

Hi, I am working on it. Will try to finish it by tomorrow. I'll keep you posted about progress.

**Comment by Niyatijain-9** [comment]
@PriteshKiri 
I have raised PR #11175. 
Kindly review.

**Comment by GrowwithNaveen** [comment]
Hi @Niyatijain-9,

Thanks for submitting the PR. We reviewed it, and it looks good! We’ll take care of the deployment from here and keep you updated on the progress.

Thanks for the great contribution. Happy coding!

**Comment by PriteshKiri** [comment]
Hey @Niyatijain-9,

Have added a comment on your PR, can you please check it once?

**Comment by Niyatijain-9** [comment]
> Hey @Niyatijain-9,
> 
> Have added a comment on your PR, can you please check it once?

Sure, I'll make the required changes by tomorrow.

**Comment by Niyatijain-9** [comment]
I have raised a new PR #11219  for the same. Kindly review.

**Comment by abhinabaadhikari** [comment]
Hi @Niyatijain-9,

I’ve left a comment on your PR — could you please take a look?

**Comment by GrowwithNaveen** [comment]
Hey @Niyatijain-9  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!
