### ISSUE TITLE
Community template: UTF 8 encoder and decoder

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#11043]
**Description:**
This template empowers developers to seamlessly encode and decode UTF-8 text within the ToolJet platform. It offers a user-friendly interface for converting between UTF-8 and other text representations, enhancing text processing capabilities.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1nWz3T8aCZFFrMuJKtamyQffag8gRh-pp-qvIJK1nwFM/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within **7 working days** and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within **7 working days** or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by sahilborse** [comment]
@GrowwithNaveen  @PriteshKiri  assign this issue to me
/attempt #11043

**Comment by PriteshKiri** [comment]
@sahilborse assigned. Happy Hacktoberfest! 🎃  

Please make sure that you complete this task in 7 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by sahilborse** [comment]
Working started

**Comment by sahilborse** [comment]
PR has been submitted https://github.com/ToolJet/ToolJet/pull/11086

**Comment by sahilborse** [comment]
done changes https://github.com/ToolJet/ToolJet/pull/11096

**Comment by sahilborse** [comment]
@GrowwithNaveen @PriteshKiri please review the changes

**Comment by GrowwithNaveen** [comment]
Hi @sahilborse, the conversion to hexadecimal looks good, but we need it in the correct universal format.

Example:
    Text input: `hello`
    Current UTF-8 encoded output: `68656c6c6f`
    Expected output: `\x68\x65\x6C\x6C\x6F`

Please test the output format using other [3rd party converters](https://domsignal.com/utf8-decoder) to ensure it matches.

Thanks!

**Comment by sahilborse** [comment]
@GrowwithNaveen @PriteshKiri please review the changes

**Comment by sahilborse** [comment]
PR for #11043
Template/utf 8 encoder and decoder #11103

**Comment by sahilborse** [comment]
https://github.com/ToolJet/ToolJet/pull/11103

**Comment by sahilborse** [comment]
@GrowwithNaveen can we move for merging of the PR

**Comment by PriteshKiri** [comment]
Hey @sahilborse 

We'll merge the PR in a day or two. Thanks for your patience.

**Comment by sahilborse** [comment]
@PriteshKiri is their any problem in my PR

**Comment by PriteshKiri** [comment]
No @sahilborse, your PR has been merged. Will close the issue soon.

We have some special rewards for all the community template contributors : )

**Comment by GrowwithNaveen** [comment]
Hey @sahilborse ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!
