### ISSUE TITLE
[docs]: Update the documentation for the Checkbox Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11053]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/checkbox

**Formatting updates:**
- Replace  "`fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Event Table
    - Update the content in the "Description" of the given 3 events - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference, the rest should remain untouched )
    - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/checkbox.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/checkbox.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by eyesee11** [comment]
Hello @PriteshKiri!
Again it's me..
Thanks for assigning the previous issue to me and i would like to work on this one too.

**Comment by rudrakshnalbalwar** [comment]
Hey @PriteshKiri I would like to contribute on this could you please assign this issue to me...

**Comment by eyesee11** [comment]
Hello @PriteshKiri!
Again it's me, and I would like to work on this one.

**Comment by MuskanSaxena6** [comment]
.take

**Comment by PriteshKiri** [comment]
@eyesee11 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @rudrakshnalbalwar, We greatly appreciate your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

We hope you understand our decision! Thanks!

**Comment by PriteshKiri** [comment]
Hey @bhojrajnarwae ,  Thank you for your interest in contributing!

We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by shivankkunwar** [comment]
Hi @PriteshKiri  is this open? I am interested in fixing this issue, let me know the status.

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress.

This issue is now open for contribution 🙌

**Comment by shivankkunwar** [comment]
I am interested, would like to contribute to this

**Comment by PriteshKiri** [comment]
@shivankkunwar  assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by arkokundu500** [comment]
I am interested i would like to contribute
