### ISSUE TITLE
[docs]: Update the documentation for the Tree Select Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11058]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/tree-select

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/tree-select.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/tree-select.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by kairveeehh** [comment]
would like to work on it, please assign

**Comment by AbhinavTheDev** [comment]
I would like to work on this, assign this to me.

**Comment by PriteshKiri** [comment]
@kairveeehh assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @OoONANCY ,  Thank you for your interest in contributing!

We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by PriteshKiri** [comment]
Hey @AbhinavTheDev , thanks for your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

Thanks for understanding!

**Comment by RudraPratik30** [comment]
Hey @kairveeehh any updates on this?

**Comment by kairveeehh** [comment]
working on it .

**Comment by hahaanisha** [comment]
Hey @PriteshKiri 
Can you assign this task to me?
Thanks!

**Comment by PriteshKiri** [comment]
@hahaanisha assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our Slack community if you have any questions.

**Comment by hahaanisha** [comment]
Hey @PriteshKiri 
I've submitted my PR and signed the CLA, but it's still showing as unsigned. Could you please check? 
Thanks!

**Comment by PriteshKiri** [comment]
Hey @hahaanisha ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.
