### ISSUE TITLE
[docs]:  Update the documentation for the Text Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11059]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/text

**Formatting updates:**
- Replace  "`fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)

**Content updates:**
- Devices 
  -  In the devices section, change from text content to a table - [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  -  Add a full stop at the end of the sentence in the "Description" column.
  
**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/text.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/text.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PriteshKiri** [comment]
@OoONANCY assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @yunus102 ,

You can check out other open issues under the `community contribution` label.

**Comment by RudraPratik30** [comment]
Hey @OoONANCY any updates on this?

**Comment by PriteshKiri** [comment]
Hey @OoONANCY ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress.

This issue is now open for contributions 🙌

**Comment by vivektripaathi** [comment]
Hi @PriteshKiri, could you please assign this task to me?"

**Comment by PriteshKiri** [comment]
@vivektripaathi assigned!!  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.
