### ISSUE TITLE
[docs]: Update the documentation for the Bounded Box Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11057]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/bounded-box

**Formatting updates:**
- Replace  "`Fx`" and "**Fx**"   with "**fx**" wherever applicable. ( i.e. remove the backticks (``) and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Layout Tabel
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Add the "Expected value" column and update the content in the "Expected value" and "Description" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -**
Next - ToolJet/docs/docs/widgets/bounded-box.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/bounded-box.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Atul1231** [comment]
@PriteshKiri I would like to work on it

**Comment by OoONANCY** [comment]
please assign it to me

**Comment by PriteshKiri** [comment]
Hey @Atul1231, We appreciate your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

Thank you for your understanding!

**Comment by Atul1231** [comment]
@PriteshKiri ok!!

**Comment by AbhinavTheDev** [comment]
Assign this to me, I would like to work on this.

**Comment by PriteshKiri** [comment]
Hey @OoONANCY ,  Thank you for your interest in contributing!

We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by PriteshKiri** [comment]
Hey @AbhinavTheDev , thanks for your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

Thanks for understanding!

**Comment by eyesee11** [comment]
Hi @PriteshKiri
Can this be assigned to me please!!?

**Comment by sahilborse** [comment]
@PriteshKiri assign this issue to me
/attempt #11057

**Comment by sahilborse** [comment]
I am first time contributor

**Comment by bhojrajnarwae** [comment]
It is my first open source contribution so please assign me this issue please @PriteshKiri

**Comment by PriteshKiri** [comment]
Hey @eyesee11 @sahilborse,  Thank you for your interest in contributing!

We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by PriteshKiri** [comment]
Hey @bhojrajnarwae ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by PriteshKiri** [comment]
@bhojrajnarwae  assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by MuskanSaxena6** [comment]
I'm a first time open source contributor please assign me this issue. @PriteshKiri

**Comment by PriteshKiri** [comment]
Hey @MuskanSaxena6 ,

This issue has already been assigned.

You can check out other open issues under the `community contribution` label.

**Comment by PriteshKiri** [comment]
Hey @bhojrajnarwae ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.
