### ISSUE TITLE
[docs]: Update the documentation for the Button Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11056]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/button

**Formatting updates:**
- Replace  "`fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Event Table
    - Update the content in the "Description" of the given 2 events - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference, the rest should remain untouched )
    - Add a full stop at the end of the sentence in the "Description" column.

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/button.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/button.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by OoONANCY** [comment]
please /assign it to me

**Comment by PriteshKiri** [comment]
Hey @Naman13112004, We greatly appreciate your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

We hope you understand our decision! Thanks!

**Comment by AbhinavTheDev** [comment]
Hey @PriteshKiri Assign this to me

**Comment by PriteshKiri** [comment]
Hey @OoONANCY ,  Thank you for your interest in contributing!

We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by PriteshKiri** [comment]
Hey @AbhinavTheDev , thanks for your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

Thanks for understanding!

**Comment by sahilborse** [comment]
/attempt https://github.com/ToolJet/ToolJet/issues/11056
@PriteshKiri I can solve this issue please assign it to me

**Comment by PriteshKiri** [comment]
@Namchi7  assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @bhojrajnarwae ,  Thank you for your interest in contributing!

We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by PriteshKiri** [comment]
Hey @Namchi7 ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by yuvi-mittal** [comment]
heyy @PriteshKiri , I am a first time contributor , could you assign me a issue ?
