### ISSUE TITLE
[docs]: Update the documentation for the Button Group Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11054]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/button-group

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable.  ( i.e. remove the backticks (``) make it lowercase and bold -> fx)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Event Table
    - Remove the description under the heading.
    - Update the content in the "Description" of the "On click" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference, the rest should remain untouched )
    - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/button-group.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/button-group.md
 Version  3.0.0 (LTS) - ToolJet/docs/versioned_docs/version-3.0.0-LTS/widgets/button-group.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by rudrakshnalbalwar** [comment]
Hey @PriteshKiri,
I would like to contribute to this issue, could you please assign it to me

**Comment by PriteshKiri** [comment]
@anuj846k assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @eyesee11,  Thank you for your interest in contributing! 

We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by arkokundu500** [comment]
Hi @PriteshKiri ,I would like to contribute to this issue please assign me.

**Comment by PriteshKiri** [comment]
Hey @arkokundu500 ,

This issue has already been assigned.

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by anuj846k** [comment]
Hi @PriteshKiri  DO i need to setup the Db Also for this issue  , i tried to do it but this error is coming how to setup all this do I have to setup the postgress db also 

```
▓▒░ npm run --prefix server db:create                     ░▒▓ ✔  08:56:54 PM  ▓▒░
npm run --prefix server db:reset

> server@0.0.1 db:create
> ts-node ./scripts/create-database.ts

Error: Command failed: createdb -h your_db_host -p 5432 -U your_db_username your_database_name
createdb: error: could not translate host name "your_db_host" to address: Temporary failure in name resolution

    at checkExecSyncError (node:child_process:890:11)
    at execFileSync (node:child_process:926:15)
    at executeCreateDb (/home/anuj-kumar/Desktop/ToolJet/server/scripts/create-database.ts:60:15)
    at createDb (/home/anuj-kumar/Desktop/ToolJet/server/scripts/create-database.ts:69:5)
    at createDatabase (/home/anuj-kumar/Desktop/ToolJet/server/scripts/create-database.ts:39:11)
    at createDatabaseFromFile (/home/anuj-kumar/Desktop/ToolJet/server/scripts/create-database.ts:19:9)
    at Object.<anonymous> (/home/anuj-kumar/Desktop/ToolJet/server/scripts/create-database.ts:133:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/home/anuj-kumar/Desktop/ToolJet/server/node_modules/ts-node/src/index.ts:1618:23) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(111) [Uint8Array] [
       99, 114, 101,  97, 116, 101, 100,  98,  58,  32, 101, 114,
      114, 111, 114,  58,  32,  99, 111, 117, 108, 100,  32, 110,
      111, 116,  32, 116, 114,  97, 110, 115, 108,  97, 116, 101,
       32, 104, 111, 115, 116,  32, 110,  97, 109, 101,  32,  34,
      121, 111, 117, 114,  95, 100,  98,  95, 104, 111, 115, 116,
       34,  32, 116, 111,  32,  97, 100, 100, 114, 101, 115, 115,
       58,  32,  84, 101, 109, 112, 111, 114,  97, 114, 121,  32,
      102,  97, 105, 108, 117, 114, 101,  32, 105, 110,  32, 110,
       97, 109, 101,  32,
      ... 11 more items
    ]
  ],
  pid: 33703,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(111) [Uint8Array] [
     99, 114, 101,  97, 116, 101, 100,  98,  58,  32, 101, 114,
    114, 111, 114,  58,  32,  99, 111, 117, 108, 100,  32, 110,
    111, 116,  32, 116, 114,  97, 110, 115, 108,  97, 116, 101,
     32, 104, 111, 115, 116,  32, 110,  97, 109, 101,  32,  34,
    121, 111, 117, 114,  95, 100,  98,  95, 104, 111, 115, 116,
     34,  32, 116, 111,  32,  97, 100, 100, 114, 101, 115, 115,
     58,  32,  84, 101, 109, 112, 111, 114,  97, 114, 121,  32,
    102,  97, 105, 108, 117, 114, 101,  32, 105, 110,  32, 110,
     97, 109, 101,  32,
    ... 11 more items
  ]
}

> server@0.0.1 db:reset
> npm run db:drop && npm run db:setup


> server@0.0.1 db:drop
> ts-node ./scripts/drop-database.ts
```

**Comment by PriteshKiri** [comment]
Hey @anuj846k,

Please drop your queries in our Slack community. If possible, share screenshots of any errors you’re encountering while setting up the ToolJet repo.

**Comment by PriteshKiri** [comment]
Hey @anuj846k 

Any updates on the issue?

**Comment by anuj846k** [comment]
> Hey @anuj846k 
> 
> Any updates on the issue?

Done setup but I am facing an issue whenever I'm changing i can't see changes on website localhost .
I asked in  slack and waiting for response.

**Comment by anuj846k** [comment]
@PriteshKiri I can't do it there is some issue with my laptop as the project is large! please assign it to someone else

**Comment by fadexadex** [comment]
Hey can I be assigned this.

**Comment by PriteshKiri** [comment]
Hey @fadexadex 

Are you still interested in working on this issue?

**Comment by fadexadex** [comment]
Hi if I don't submit a pr before the end of the 5th you can assign it to someone else

**Comment by RudraPratik30** [comment]
Unassigned due to lack of progress.
This PR is now open for contributions.

**Comment by eeshalteluri** [comment]
@RudraPratik30 @PriteshKiri 
Can I work on this issue?

**Comment by eeshalteluri** [comment]
@PriteshKiri @RudraPratik30 
Is this issue resolved else where or it is still open?

**Comment by RudraPratik30** [comment]
@eeshalteluri  assigned.

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

Update
Now, you have to make changes in the following three files:

Next - ToolJet/docs/docs/widgets/button-group.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/button-group.md
Version 3.0.0 (LTS) - ToolJet/docs/versioned_docs/version-3.0.0-LTS/widgets/button-group.md

**Comment by RudraPratik30** [comment]
Unassigned due to lack of progress.
This PR is now open for contributions.

**Comment by ingridrsm** [comment]
Hello @RudraPratik30 @PriteshKiri , I'm a Computer Science student and I'd like to work on this issue, please

**Comment by PriteshKiri** [comment]
@ingridrsm assigned!!

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 5 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
@ingridrsm please update the change in - 3.0.0-LTS, 2.50.0-LTS and Next (3.1.0)

**Comment by PriteshKiri** [comment]
Hey @Harshitkant21, this issue has already been assigned.  Please check out other open issues under the `community contribution` label.
