### ISSUE TITLE
[docs]: Update the documentation for the Radio Button Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11063]
### Summary

**Formatting updates:**
- Replace  "`fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )
- Event Table
    - Update the content in the "Description" of the "On select" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference, the rest should remain untouched )
    - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/radio-button.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/radio-button.md

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/radio-button

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by 5AIPAVAN** [comment]
can you assign me any one from these document issues 
eagerly looking forward to contribute to tooljet :-) @PriteshKiri

**Comment by PriteshKiri** [comment]
Hey @5AIPAVAN, We appreciate your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

Thank you for your understanding!

**Comment by ishan657** [comment]
Hy @PriteshKiri 
I'm new to open source contribution and i would love to contribute on this issue 
Kindly assign me this issue 
Thank you

**Comment by sahilborse** [comment]
Hey @PriteshKiri Assign this issue to me as Its my first time contributing

**Comment by yunus102** [comment]
Hey @PriteshKiri, I would like to take this up.
This is my first time requesting for contribution.

**Comment by PriteshKiri** [comment]
@ishan657 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @sahilborse,

We have already assigned you an issue. Looking forward to your contribution there!

Please refrain from spamming the issues by commenting on all new issues.

**Comment by PriteshKiri** [comment]
Hey @yunus102 ,

This issue has already been assigned.

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by PushpakChaudhari** [comment]
I fix this issue please assign me

**Comment by PriteshKiri** [comment]
Hey @PushpakChaudhari ,

This issue has already been assigned.

You can check out other open issues under the `community contribution` label. Thanks!
