### ISSUE TITLE
NumberInput default value

### ISSUE THREAD

**Issue by ChudoYudo** [ToolJet/ToolJet#11084]
### Version Information
lts-2.50
### Environment

Docker
### What is the expected behaviour?

When default value of NumberInput is set to empty string or null , components.numberinput.value is null (or undefinded)
### What is the current behaviour?

When I set empty string or null to default value of NumberInput, components.numberinput.value is 99

### How to reproduce the issue?

1. Add NumberInput component to the page 
2. Set empty string or null to default value
3. Open Inspector and check  components.numberinput.value

### Screenshots or Screencast

<img width="961" alt="Screenshot 2024-10-23 at 08 34 27" src="https://github.com/user-attachments/assets/7c512b5e-e69f-4e3b-8ba5-4bfb4bfe443f">

### Please provide any traces or logs that could help here.
-

### Any possible solutions?
fix code to set null or undefined if properties.value === '' || properties.value === null

### Can you identify the location in the driver source code where the problem exists?

https://github.com/ToolJet/ToolJet/blob/1effa5e28d5d58febf1ebe21ebc472d6ae7eba0d/frontend/src/Editor/Components/NumberInput.jsx#L48

### If the bug is confirmed, would you be willing to submit a PR?

yes

**Comment by ChudoYudo** [comment]
> Hi @ChudoYudo !! I would like to work on this issue

Hey @eyesee11
I've already prepared fix for it. I'm waiting for issue official confirmation :)

**Comment by PriteshKiri** [comment]
Hey @ChudoYudo,

Thanks for creating the issue.

Unfortunately, this bug is already in the pipeline and will be taken up by our internal team. We will be releasing it soon in our upcoming versions.

I’ll have to close this issue for now, but we really appreciate your input and look forward to your future contributions.

Thanks!
