### ISSUE TITLE
[docs]: Update the documentation for the List View Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11115]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/listview/

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/listview.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/listview.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by vroomvee** [comment]
hi @PriteshKiri , I have already requested for an issue with the SVG documentation to be assigned to me and I'd like to work on this as well for hacktoberfest2024- I'll have the work completed by the end of Sunday positively. Can you please assign this issue to me?

**Comment by PriteshKiri** [comment]
Hey @DeepanshuYadav-code, We greatly appreciate your previous contributions.

However, for this issue, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

Thanks for understanding!

**Comment by PriteshKiri** [comment]
Hey @vroomvee,

Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by harith-hacky03** [comment]
Can you assign me?

**Comment by hahaanisha** [comment]
Hey @PriteshKiri !
I would like to work on this issue. Please assign it to me. 
Thank you!

**Comment by PriteshKiri** [comment]
Hey @hahaanisha ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by PriteshKiri** [comment]
Hey @harith-hacky03,

Any updates on the issue? Please let me know if you are facing any issues

**Comment by PriteshKiri** [comment]
This issue is now open for contribution 🙌

**Comment by vroomvee** [comment]
Can i take it up? will work on it rn!

**Comment by fadexadex** [comment]
Hey can I be assigned this

**Comment by vivektripaathi** [comment]
@PriteshKiri Hi! I’m new to this repository and interested in contributing to ToolJet. I'd love to take on this issue as my first contribution here if it’s available. Thanks for considering me!

**Comment by PriteshKiri** [comment]
Hey @fadexadex 

Are you still interested in working on this issue?

**Comment by PriteshKiri** [comment]
Hey @HareeshDhruva @vivektripaathi  ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by fadexadex** [comment]
It can be assigned to Hareesh

**Comment by PriteshKiri** [comment]
A different issue has already been assigned to @HareeshDhruva 

Opening this issue for contribution 🙌

**Comment by kushalsourav** [comment]
@PriteshKiri 
Hi, I’d like to work on this issue if it’s open and unassigned. Could you please assign it to me? Thank you!

**Comment by RudraPratik30** [comment]
@kushalsourav  assigned.

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Update**
Now, you have to make changes in the following three files:
- Next - ToolJet/docs/docs/widgets/listview.md
- Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/listview.md
- Version 3.0.0 (LTS) - ToolJet/docs/versioned_docs/version-3.0.0-LTS/widgets/listview.md

**Comment by kushalsourav** [comment]
@RudraPratik30 could you please review the [PR](https://github.com/ToolJet/ToolJet/pull/11316)? Please let me know if any changes are needed.
