### ISSUE TITLE
[docs]: Update the documentation for the Kanban Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11118]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/kanban/

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/kanban-board.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/kanban-board.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by MuskanSaxena6** [comment]
Hello @PriteshKiri  i would love to contribute to this issue , it will be my first contribution for hacktoberfest 2024 , thank you.

**Comment by PriteshKiri** [comment]
@MuskanSaxena6 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our Slack community if you have any questions.

**Comment by MuskanSaxena6** [comment]
Am i supposed to make change in ToolJet\docs\docs\widgets\kanban-board.md and ToolJet\docs\versioned_docs\version-2.50.0-LTS\widgets\kanban-board.md  as i can't find the two files you mentioned?

**Comment by PriteshKiri** [comment]
Hey @MuskanSaxena6 Yes, you are correct.
You have to update in the kanban-board.md files only. Apologies for the inconvenience. Have updated the issue.

Looking forward to your contribution!!

**Comment by MuskanSaxena6** [comment]
Thank you @PriteshKiri for confirming it , I've already made a PR please review it, I enjoyed working on my first contribution.

**Comment by PriteshKiri** [comment]
Hey @MuskanSaxena6  ,
Thank you so much for your contribution! 🙌
Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by MuskanSaxena6** [comment]
@PriteshKiri I'll surely keep a track of it.
