### ISSUE TITLE
[docs]: Update the documentation for the SVG Image Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11116]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/svg-image

**Content updates:**
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)
- Style Table
   -  Update the column name from "Style" to "Property" and "Default Value" to "Configuration Options"
   -  Update the content in the "Description" and "Configuration Options" for the **Visibility** property. [reference](https://docs.tooljet.com/docs/widgets/rich-text-editor#styles) ( Please just check the sentence and table structure from the given reference )
   -  Add the Box shadow property to the table. [reference](https://docs.tooljet.com/docs/widgets/rich-text-editor#styles) ( Please add the property to the table similar to that given in the reference )

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/svg-image.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/svg-image.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by vroomvee** [comment]
hi, i would like to work on this for hacktoberfest2024, could you assign this issue to me?

**Comment by PriteshKiri** [comment]
@vroomvee assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by yuvi-mittal** [comment]
heyy @PriteshKiri , i am a first time contributor and would like to work on hacktoberfest 2024 , could you assign any issue to me ?

**Comment by PriteshKiri** [comment]
Hey @yuvi-mittal,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by PriteshKiri** [comment]
Hey @vroomvee,

Any updates on the issue?? Please let me know if you are facing any problems

**Comment by vroomvee** [comment]
> Hey @vroomvee,
> 
> Any updates on the issue?? Please let me know if you are facing any problems

I have submitted the PR, does it not reflect??

**Comment by PriteshKiri** [comment]
Hey @vroomvee,

Just checked the PR, thanks for your contribution!!

Can you please link the issue to your PR?

**Comment by vroomvee** [comment]
https://github.com/ToolJet/ToolJet/pull/11144
