### ISSUE TITLE
[docs]: Update the documentation for the Map Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11114]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/map

**Formatting updates:**
- Replace  "`Fx`" with "**fx**" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> **fx**)
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/map.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/map.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by DeepanshuYadav-code** [comment]
Hey @PriteshKiri, I would like to work on this issue for hacktoberfest

can you please assign me this issue

**Comment by MuskanSaxena6** [comment]
Hi @PriteshKiri ,I'm a first time contributor, please assign me this issue.

**Comment by ArnavSingha** [comment]
Hii @PriteshKiri ,

I wanna worked on this ToolJet Issue, Can you please /assign it to me?

**Comment by PriteshKiri** [comment]
Hey @MuskanSaxena6  @ArnavSingha,  Thank you for your interest in contributing! 

We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by Avinashs7** [comment]
Hi @PriteshKiri ,I'm a first time contributor, Can you assign this issue to me.

**Comment by ShabinMuhammedKK** [comment]
@PriteshKiri i can fix this. you can assign this issue to me?.

**Comment by skdas20** [comment]
@PriteshKiri 
  I can fix please assign to me, a first time contributor for tooljet

**Comment by PriteshKiri** [comment]
@Avinashs7 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @ShabinMuhammedKK @skdas20 ,

This issue has already been assigned.

You can check out other open issues under the community contribution label. Thanks!

**Comment by sahilborse** [comment]
@PriteshKiri can you assign me this issue

**Comment by PriteshKiri** [comment]
Hey @sahilborse,

This issue has already been assigned. I’d request you to please comment on issues that are currently unassigned only.

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by PriteshKiri** [comment]
Hey @Avinashs7 ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by Avinashs7** [comment]
Sure @PriteshKiri 
Thank you!
