### ISSUE TITLE
[docs]: Update the documentation for the Steps Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11119]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/steps/

**Content updates:**
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" column.
- Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)
 
**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/steps.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/steps.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by manbhav234** [comment]
Can I be assigned this issue ? This is my first time contributing. Thanks !

**Comment by PriteshKiri** [comment]
@manbhav234 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @manbhav234  ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by ShabinMuhammedKK** [comment]
@PriteshKiri Hi, still anyone woriking with this isssue?

**Comment by PriteshKiri** [comment]
Hey @ShabinMuhammedKK ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!
