### ISSUE TITLE
[docs]: Update the documentation for the Pagination Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11122]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/pagination

**Content updates:**
- In the "Exposed Variables" Table, update the content in the "Description" and "How To Access" columns for the given two variables in the table [reference](https://docs.tooljet.com/docs/widgets/text-input/#exposed-variables) ( Please just check the sentence structure from the given reference )
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" and "Expected value" column.
  
**The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/pagination.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/pagination.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Suraj-kumar00** [comment]
Hi  @PriteshKiri, how have you been?
As I worked on previous ToolJet Issue, I would like to work in this issue as well. Can you please assign it to me?

**Comment by PriteshKiri** [comment]
Hey @Suraj-kumar00 , We greatly appreciate your previous contributions.

However, for this issue, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

Thanks for understanding!

**Comment by kabszac** [comment]
Hi @PriteshKiri  I would like to be assigned this issue

**Comment by sahilborse** [comment]
@PriteshKiri can you assign me this issue

**Comment by PriteshKiri** [comment]
Hey @kabszac ,
Thank you so much for your contribution! 🙌
Please keep an eye on your PR, as we may add some review comments if needed before merging it.
