### ISSUE TITLE
[docs]: Update the documentation for the Link Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11123]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/link

**Content updates:**
- In the "Events" Table, update the "Description" for the "On click" and "On hover" events - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference )
 - In the "Component Specific Actions (CSA)" Table, update the content in the "Description" and "How To Access" columns for the **click** action [reference](https://docs.tooljet.com/docs/widgets/button#component-specific-actions-csa) ( Please just check the sentence structure from the given reference )
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" and "Expected value" columns.
  
**The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/link.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/link.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by joshua-jinu** [comment]
Hey @PriteshKiri , I would like to work one this, can I be assigned

**Comment by PriteshKiri** [comment]
@joshua-jinu assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @joshua-jinu  ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by sahilborse** [comment]
@PriteshKiri can you assign me this issue

**Comment by PriteshKiri** [comment]
Hey @sahilborse,

This issue has already been assigned. I’d request you to please comment on issues that are currently unassigned only.

You can check out other open issues under the `community contribution` label. Thanks!
