### ISSUE TITLE
[docs]: Update the documentation for the Image Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11124]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/image

**Content updates:**
- ~~In the "Events" Table, update the "Description" for the "On click" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference )~~
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" and "Expected value" columns.
  
**The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/image.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/image.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Suraj-kumar00** [comment]
Hi @PriteshKiri, how have you been?
As I worked on previous ToolJet Issue, I would like to work in this issue as well. Can you please assign it to me?

**Comment by PriteshKiri** [comment]
Hey @Suraj-kumar00 , We greatly appreciate your previous contributions.

However, for this issue, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

Thanks for understanding!

**Comment by yunus102** [comment]
@PriteshKiri just made my first PR. If possible assign it to me

**Comment by PriteshKiri** [comment]
Hey @yunus102 , thanks for your interest.

However, for this issue, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

Thanks for understanding!

**Comment by ArnavSingha** [comment]
Hii @PriteshKiri,  

I wanna worked on this ToolJet Issue, Can you please assign it to me?

**Comment by SaurabhGurde** [comment]
hi @PriteshKiri 
I am first  time contributor can you assign this issue to me

**Comment by PriteshKiri** [comment]
Hey @ArnavSingha,   Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by SaurabhGurde** [comment]
@PriteshKiri Event table in reference do not have event named "on Click" so how should id update description in document with the issue.

**Comment by PriteshKiri** [comment]
Hey @SaurabhGurde,

You have to update the description, but it seems the fix is already made. So you can skip that part. I have updated the issue description.

**Comment by PriteshKiri** [comment]
Hey @SaurabhGurde,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by SaurabhGurde** [comment]
> Hey @SaurabhGurde,
> 
> Thank you so much for your contribution! 🙌
> 
> Please keep an eye on your PR, as we may add some review comments if needed before merging it.


sure 😊

**Comment by PriteshKiri** [comment]
Hey @hahaanisha ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!
