### ISSUE TITLE
[docs]: Update the documentation for the Star Rating Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11120]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/star-rating

**Content updates:**
- In the "Exposed Variables" Table, update the content in the "Description" and "How To Access" columns for the **value** variable [reference](https://docs.tooljet.com/docs/widgets/text-input/#exposed-variables) ( Please just check the sentence structure from the given reference )
- Events Table
   -  Update the event name from "On Change" to "On change".
   -  Update the "Description" for the "On change" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference )
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" column.
  
**The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/star-rating.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/star-rating.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by sikehish** [comment]
I'd love to take this up. Could you assign this to me?

**Comment by PriteshKiri** [comment]
Hey @sikehish  , We greatly appreciate your previous contributions.

However, for this issue, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.

Thanks for understanding!

**Comment by Parth4git** [comment]
@PriteshKiri  Please assign this issue to me. I want to contribute

**Comment by ShabinMuhammedKK** [comment]
@PriteshKiri Hi, i can work on this issue.

**Comment by skdas20** [comment]
I am a first time contributor please assign this to me

**Comment by PriteshKiri** [comment]
@Parth4git assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @ShabinMuhammedKK @skdas20 ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by PriteshKiri** [comment]
Hey @Parth4git ,
Thank you so much for your contribution! 🙌
Please keep an eye on your PR, as we may add some review comments if needed before merging it.
