### ISSUE TITLE
The Edit Icon in inspector is not noticeable in dark mode

### ISSUE THREAD

**Issue by RajMhatre20** [ToolJet/ToolJet#1114]
Icons in the inspector mode are not properly visible in dark mode
current state:
![image](https://user-images.githubusercontent.com/68785723/137589082-5557ed0c-c2a3-4faf-8d21-e3f072b8a0cc.png)
expected state:
![image](https://user-images.githubusercontent.com/68785723/137589019-2aae39c4-27a2-4550-9f61-2acb932a0c64.png)

we can add ```filter: invert(1)``` style to the icon which can be toggled on dark theme.

**Comment by Navaneeth-pk** [comment]
Thanks for reporting the issue and working on it!
@RajMhatre20
