### ISSUE TITLE
Workspace constants pagination error

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#11151]
Pagination shows `1/0` instead of `1/1` 

https://lh7-rt.googleusercontent.com/sheetsz/AHOq17EHTuYX1Tii_PER0IcfuXDfW98m3Xahw95KmzSigfYPjc_bG28_wRb_YWsONTlUaJZStyLuZqmG90-XDYgSgupIxKYz-ToWcB-UFb8XIlj66uy_d9mQMiA1X4lCNcW2f2pWQa0rPeGbbmFMy0SeVV6Q4XQ?key=r9zLQlshQc7WMbgm_6Wxog

**Comment by sambhavrana27** [comment]
pls assign this to me

**Comment by PriteshKiri** [comment]
@sambhavrana27 assigned!! Happy coding :)

**Comment by PriteshKiri** [comment]
Hey @sambhavrana27,

Any updates on the issue?

**Comment by Chetan0000** [comment]
Hay @PriteshKiri, @RudraPratik30 i would like to work on this issue,
Can you please assign it to me.

**Comment by Aspireve** [comment]
Heyy Hi @PriteshKiri 
Could I work on this issue, I was suggested to work on this by @RudraPratik30

**Comment by RudraPratik30** [comment]
Hey @Aspireve, thank you so much for your interest, but this issue is assigned, can you please check for other issues with the `community contribution` label?

**Comment by Aspireve** [comment]
Yupp sure

**Comment by PriteshKiri** [comment]
Hey @Chetan0000,

Any updates on the issue? Please let me know if you are facing any issues

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress.

This issue is open for contribution 🙌

**Comment by Aspireve** [comment]
Heyy Hi @PriteshKiri 

Could I work on this
Kinda would take me a day tho, cause my PC is currently under repair 🥲

**Comment by PriteshKiri** [comment]
Hey @Aspireve  , We greatly appreciate your interest.

However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity.   We hope you understand our decision. Thanks!

**Comment by Aspireve** [comment]
Yess sure!!

**Comment by himanshudube97** [comment]
Hi @PriteshKiri Can I work on this issue

**Comment by PriteshKiri** [comment]
Hey @himanshudube97 , thanks for showing interest in this issue.

However, we would like to wait and see if any first-time contributors are also interested in this opportunity. Thanks for understanding.

**Comment by Vignesh18280** [comment]
Hi @PriteshKiri 
is the issue still open, coz when I created a workspace constant , it works fine in my showing (1/1)
<img width="1440" alt="Screenshot 2024-12-13 at 10 34 13 AM" src="https://github.com/user-attachments/assets/279ce032-8845-4d74-85a8-38281a600c4e" />

**Comment by PriteshKiri** [comment]
Hey @Vignesh18280,

You are correct, this has been fixed in the newer versions. Thus closing the issue.

Please check other issues with `community contribution` label.
