### ISSUE TITLE
Click on body of the modal to show its properties when the modal is open

### ISSUE THREAD

**Issue by DevangAgarwal93** [ToolJet/ToolJet#11155]
### Problem
Once we drop a component on the modal or select any other component inside of it, the only way to edit modal properties is to click on the component handle at the top left corner, which is not very intuitive. 
Most of the times the developer closes the modal and opens it again to edit its properties.

### Solution
Developer should be able to select the modal on clicking on the body of the open modal and this should also open up the modal properties in the component panel for the developer to edit.

**Comment by tasbi03** [comment]
hey can you assign this to me ?
