### ISSUE TITLE
Able to create folder without any name

### ISSUE THREAD

**Issue by devblin** [ToolJet/ToolJet#1116]
### What is the expected behavior?
Creating a folder without any input should show an error that the folder name can't be empty.

### What is the current behavior?
A folder without any input can be created.

### How to reproduce the issue?
1. Visited ToolJet dashboard.
2. Create a folder without any input.

### Screenshots or Screencast
https://user-images.githubusercontent.com/55559527/137597297-bf4cf3b4-0a0d-4afd-ba53-863584896603.mp4

### Any possible solutions?
Yes, in the given function, I can add a validation to check if the `newFolderName` state is empty, and if it's empty, show a toast with the message "folder name can't be empty"
https://github.com/ToolJet/ToolJet/blob/37f9e3c4a57040b854169181198325c3d380988f/frontend/src/HomePage/Folders.jsx#L24

### Can you identify the location in the driver source code where the problem exists?
Yes

### If the bug is confirmed, would you be willing to submit a PR?
Yes, I would like to submit a PR.

**Comment by pratik9333** [comment]
rather you assigning yourself can I work on it @devblin ?

**Comment by devblin** [comment]
> rather you assigning yourself can I work on it @devblin ?

I want to work on this.
