### ISSUE TITLE
[docs]: Update the documentation for the Icon Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11168]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/icon

**Content updates:**
- Component Specific Actions (CSA) Table
   - Update the "Actions" by adding `()` at the end of action  - [reference](https://docs.tooljet.com/docs/widgets/text-input#component-specific-actions-csa)
   - Update the "Description" and "How To Access" [reference](https://docs.tooljet.com/docs/widgets/text-input#component-specific-actions-csa)
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" and "Expected value" columns.
  
**The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/icon.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/icon.md

**_The deadline for this task is 2 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions._**

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Swapnil-2502** [comment]
Hi @PriteshKiri ,

I’m interested in working on this issue and would love to contribute! Could you please assign it to me?

Thank you!

**Comment by PriteshKiri** [comment]
Hey @niranjan-kurhade ,

Thanks for your contribution! 

Just a reminder to please start working on an issue only after it has been officially assigned to you. We’re approving the PR this time, but please keep this in mind for future contributions.

Thank you for your understanding!

**Comment by PriteshKiri** [comment]
Hey @Swapnil-2502 ,

This issue has already been assigned.

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by RudraPratik30** [comment]
Unassigning due to lack of progress.

This issue is now open for contributions 🙌

**Comment by eeshalteluri** [comment]
Hi @PriteshKiri 
I'm interested in working on this issue. Could you please assign it to me?

**Comment by RudraPratik30** [comment]
@eeshalteluri assigned.  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.
