### ISSUE TITLE
[docs]: Update the documentation for the File Picker Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11169]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/file-picker

**Content updates:**
- In Component Specific Actions (CSA) Table, update the "Description" and "How To Access" for the given action [reference](https://docs.tooljet.com/docs/widgets/text-input#component-specific-actions-csa)
- In Exposed variable Table, update the "Description" and "How To Access" for the given action [reference](https://docs.tooljet.com/docs/widgets/text-input#exposed-variables)
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" and "Expected value" columns.
  
**The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/file-picker.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/file-picker.md

**_The deadline for this task is 2 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions._**

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Shreyas0410** [comment]
Can I work on this?

**Comment by Swapnil-2502** [comment]
Hi @PriteshKiri,

I’m interested in working on this issue and would love to contribute! Could you please assign it to me?

Thank you!

**Comment by kevin-joshua** [comment]
@PriteshKiri
Can you assign this to me please , i would  like to contribute to it .

**Comment by PriteshKiri** [comment]
Hey @kevin-joshua ,

Thanks for your contribution!

Just a reminder to please start working on an issue only after it has been officially assigned to you. We’re approving the PR this time, but please keep this in mind for future contributions.

Thank you for your understanding!

**Comment by PriteshKiri** [comment]
Hey @Swapnil-2502 @kevin-joshua ,

This issue has already been assigned.

You can check out other open issues under the `community contribution` label. Thanks!
