### ISSUE TITLE
[docs]: Update the documentation for the Color Picker Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11179]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/color-picker

**Content updates:**
- In Component Specific Actions (CSA) Table, update the "Description" and "How To Access" for the given action [reference](https://docs.tooljet.com/docs/widgets/text-input#component-specific-actions-csa) ( Please just check the sentence structure from the given reference )
- In the Event Table, update the "Description" for the given event [reference](https://docs.tooljet.com/docs/widgets/text-input#events)  ( Please just check the sentence structure from the given reference )
- In Exposed variable Table, update the "Description" and "How To Access" for the given action [reference](https://docs.tooljet.com/docs/widgets/text-input#exposed-variables)  ( Please just check the sentence structure from the given reference )
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" and "Expected value" columns.
  
**The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/color-picker.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/color-picker.md

**_The deadline for this task is 2 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions._**

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by ChinoUkaegbu** [comment]
Hi, could I be assigned to this?

**Comment by PriteshKiri** [comment]
@ChinoUkaegbu assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.
