### ISSUE TITLE
[docs]: Update the documentation for the Button Group Component 

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11181]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/button-group

**Content updates:**

- Remove the description under the "Events" heading.
- In the Event Table, update the "Description" for the given event [reference](https://docs.tooljet.com/docs/widgets/text-input#events)  ( Please just check the sentence structure from the given reference )
- In Exposed variable Table, update the "Description" and "How To Access" for the given action [reference](https://docs.tooljet.com/docs/widgets/text-input#exposed-variables)  ( Please just check the sentence structure from the given reference )
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Add "Expected value" column
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" and "Expected value" columns.
  
  **The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/button-group.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/button-group.md

**_The deadline for this task is 2 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions._**

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PriteshKiri** [comment]
Hey @HareeshDhruva ,

Thanks for your contribution!

Just a reminder to please start working on an issue only after it has been officially assigned to you. We’re approving the PR this time, but please keep this in mind for future contributions.

Have added a comment on your PR, can you please check it once?

**Comment by Ankush1oo8** [comment]
Can I still work on this

**Comment by RudraPratik30** [comment]
Hey @Ankush1oo8, thanks for your interest.
But we already have a PR for this particular issue.
You can check issues with `community contribution` label to contribute.
