### ISSUE TITLE
An error is displayed when the app is released (tooljet-ce:CE-LTS-2.50.19)

### ISSUE THREAD

**Issue by nzk-xyz** [ToolJet/ToolJet#11196]
### Version Information
tooljet-ce:CE-LTS-2.50.19  

### Environment
Docker

### What is the expected behaviour?
No error is displayed and the release is possible.  

### What is the current behaviour?
An error is displayed when the app is released.  

### How to reproduce the issue?
1. Create any app.  
2. Click the “Release” button at the top right of the screen to release the app.  
3. Change the app version to v2 and make any modifications to the app.  
4. Click the “Release” button at the top right of the screen to release the app again.  
5. An error message “Oops, something went wrong” appears at the top of the screen.  

### Screenshots  

![screenshot1](https://github.com/user-attachments/assets/6f4472f7-032f-4b0a-a026-fc146d15f561)
![screenshot2](https://github.com/user-attachments/assets/dba73709-9b6d-48d3-a8e9-f713c46aabf1)

**Comment by sky-39** [comment]
I am not able to replicate the issue.
I created an app and released it.
After that, I created a v2, added a button in the app, and added an event handler on Click to alert a message.
Then I released the app but it gave no error.

Is there any other kind of modification I should do before releasing the app?
Please mention.

**Comment by PriteshKiri** [comment]
Hey @nzk-xyz,

Unfortunately, we are unable to replicate the issue. Can you please share a video of how to reproduce with a certain set of configurations you have on your app?

**Comment by nzk-xyz** [comment]
I will attach this docker log.  
Please contact us if you have any other information you need.  
[docker_log.txt](https://github.com/user-attachments/files/17654167/docker_log.txt)

**Comment by nzk-xyz** [comment]
I built a new environment and tested the same version, and confirmed that the bug did not reoccur.
Thank you for your assistance.
