### ISSUE TITLE
only half nav bar is visible in mobile view on scrolling

### ISSUE THREAD

**Issue by saisumanthkumar** [ToolJet/ToolJet#1123]
### What is the expected behaviour?

on scrolling complete nav bar should be visible 

### What is the current behaviour?

![c28c5fe7-c99d-4756-bc68-427669500161](https://user-images.githubusercontent.com/74057515/137624147-f7c9f621-db58-4107-bd8a-c6d27fe00d08.jpeg)

### If the bug is confirmed, would you be willing to submit a PR?
Yes,I'd like to work on this

**Comment by saisumanthkumar** [comment]
I would like to work on this please assign me

**Comment by Navaneeth-pk** [comment]
The code for the website is not public as we are using a paid template. Closing the issue. We will fix this soon.
