### ISSUE TITLE
clickable Email in contact section

### ISSUE THREAD

**Issue by saisumanthkumar** [ToolJet/ToolJet#1124]
### Is your proposal related to a problem?
For direct access to mailing , Email should be clickable
<img height="300px" src="https://user-images.githubusercontent.com/74057515/137624449-be7b1e00-479e-42e2-a2f8-6c295d8c7fdb.jpeg" />

### Describe the solution you'd like

Email should be link. so that onclick opens mail tab

### If the feature is approved, would you be willing to submit a PR?
yes ,I'm willing to work on this

**Comment by saisumanthkumar** [comment]
please assign me for this feature

**Comment by Navaneeth-pk** [comment]
The code for the website is not public as we are using a paid template. Closing the issue. We will fix this soon.
