### ISSUE TITLE
App actions pop-up breaking near screen edge

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#11256]
The pop-up on the app card near the edge of the screen opens up outside the screen area - it should open up aligning the bottom of the pop-up instead of the top in such cases to ensure the user can always view it 

<img width="1292" alt="Screenshot 2024-11-11 at 1 49 27 PM" src="https://github.com/user-attachments/assets/a3e37387-fe2e-40c5-97b5-f5e48fc97253">

**Comment by kushalsourav** [comment]
@nechalmaggon  
Hi, I'd like to work on this issue if it's open and unassigned. Could you please assign it to me?
Thank you!

**Comment by kushalsourav** [comment]
@nechalmaggon
Hi, while fixing the issue, I noticed that in Frontend -> src -> HomePage -> AppMenu.jsx, changing the OverlayTrigger component's placement from "bottom" to "top-start" prevents the popup from breaking the screen. However, resizing the screen still causes issues in some cases due to the limited width between the margin and the cards within the container.

As a solution, would it be ideal to dynamically increase the width and height of the card wrapper whenever the popup is displayed?

**Comment by nechalmaggon** [comment]
Hey @kushalsourav, not super clear on what you mean by `dynamically increase the width and height of the card wrapper whenever the popup is displayed` would it be possible for you to share some screenshot and draw over it? 

In essence what I need is just for the pop-up to always be visible in the frame of the screen. Don't want the dashboard UI to change in any way.

**Comment by kushalsourav** [comment]
@nechalmaggon 
App actions card popup that was breaking the screen at the bottom(fixed)
![image](https://github.com/user-attachments/assets/d50550fc-e23f-42fa-b9c0-1d7fc9b77dfc)

But the popup is also breaking the screen on the right side (screen size between 1100px - 992px)
![image](https://github.com/user-attachments/assets/4b1c6dac-626d-4896-8a9c-e126f9ee10ed)

And at screen size 700px below 
![image](https://github.com/user-attachments/assets/08daa130-4efc-40c2-a4fa-f0007aeb8fde)

I need clarity on the popup actions breaking the right side of the screen.
* I tried allowing the popup to be visible on the left side of the app bar
* ![image](https://github.com/user-attachments/assets/cc85da78-b840-4515-854e-8fc111590bb9)
*  The popup of the card also moves up and down as the user scrolls when the card popup is clicked.

https://github.com/user-attachments/assets/fb0fcd9b-928d-44b1-a0da-0c0bf7d3bb93

**Comment by nechalmaggon** [comment]
Hey @kushalsourav 

- The screen sizes we currently support are within the range of `1024px` - `1920px`. We are yet to optimise for smaller screens like mobile. So you need not worry about responsiveness below 700px. 
- For the one breaking on the right side, showing the pop-up on the left works perfectly fine! 
- Once the user clicks on the button and the pop-up is opened. If the user scrolls past the `App card` linked with the pop-up, can we just close it? My understanding is that someone would be editing an app keeping that app card in view. Once it's out of view it would be confusing as to which app the pop-up belongs to. Let me know if you're able to do this part. If not, I can create a new issue for this and the rest of your work is still greatly appreciated!

**Comment by kushalsourav** [comment]
@nechalmaggon 
Hi, I'm not sure how to fix the issue with pop-ups breaking the screen on the right side, as some pop-ups appear on the left side and others on the right.


https://github.com/user-attachments/assets/1d7e0896-68b8-4188-84bc-ab3d3160890e

or

* Here i can add extra ` margin-right `  to parent component ( ` home-page-content-container `)

![image](https://github.com/user-attachments/assets/47523126-4653-42bc-8dfa-1dafa9519bdb)


I will try to fix the issue where the ` App Card ` popup closes automatically when the user scrolls past the ` App Card `. Can I use  Intersection Observer API if it is feasible, or alternatively, I will attempt to resolve it with basic CSS

**Comment by kushalsourav** [comment]
@nechalmaggon , could you please review PR #11381

**Comment by nechalmaggon** [comment]
@kushalsourav sure - passing it along to the team for review, thanks for your contribution!
