### ISSUE TITLE
Search for folders copywriting

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#11258]
Placeholder should change to `Search for folders` - first letter capital 

<img width="281" alt="Screenshot 2024-11-11 at 1 53 55 PM" src="https://github.com/user-attachments/assets/2d615b56-93f2-4f1d-85c5-8370cdc2c476">

**Comment by PriteshKiri** [comment]
Hey @harishcalvin ,

Thanks for your contribution! Just a reminder to please start working on an issue only after it has been officially assigned to you. We’re approving the PR this time, but please keep this in mind for future contributions.

Thank you for your understanding!
