### ISSUE TITLE
Dark mode - app card CTA visbility

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#11263]
`Edit` in app card button should be in white and not black in dark mode

<img width="539" alt="Screenshot 2024-11-11 at 3 02 10 PM" src="https://github.com/user-attachments/assets/1bfd66f3-3b38-43ab-ad33-3e316807b5d2">

**Comment by harishcalvin** [comment]
Hi @nechalmaggon this is ok ? 
:point_down: 

![dark-mode-edit-button-app-card-tooljet](https://github.com/user-attachments/assets/d039c1fc-c54a-4209-a19e-d6132a4b54bf)

**Comment by PriteshKiri** [comment]
Hey @harishcalvin ,

Thanks for your contribution! Just a reminder to please start working on an issue only after it has been officially assigned to you. We’re approving the PR this time, but please keep this in mind for future contributions.

Thank you for your understanding!

**Comment by harishcalvin** [comment]
sure @PriteshKiri  got it, let me if any changes needed for this PR #11279

**Comment by PriteshKiri** [comment]
Hey @harishcalvin  ,
Thank you so much for your contribution! 🙌
Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by harishcalvin** [comment]
sure :100:  @PriteshKiri
