### ISSUE TITLE
Form component breaks completely when rendering a multiselect

### ISSUE THREAD

**Issue by christian-konrad** [ToolJet/ToolJet#11275]
### Version Information

ToolJet Cloud v3.0.0

### Environment

ToolJet Cloud

### What is the expected behaviour?

Form component can render multiselect components when using a custom form schema.

### What is the current behaviour?

After the v3 update, the form component fails with "something went wrong" when the form schema contains a multiselect.

### How to reproduce the issue?

1. Add a form component
2. Enable custom JSON schema
3. Add a multiselect (take example from the docs https://docs.tooljet.com/docs/widgets/form/#multiselect)
4. --> Form component fails and can't recover until page/browser tab refresh 

### Screenshots or Screencast

<img width="1205" alt="image" src="https://github.com/user-attachments/assets/15c3d34e-0922-4f2c-b8aa-c5433e2fc2ad">

**Comment by PriteshKiri** [comment]
Hey @christian-konrad,

Thanks for creating the issue and bringing this to our attention!

There’s a syntax issue in the documentation for the custom schema in the form component. Our team is already working on fixing this, and I’ll update you as soon as the corrected docs are live.

In the meantime, you can use this example for your form component, which includes the multiselect component:

`{
   "title": "Event Registration",
   "properties": {
      "textinput1": {
         "type": "textinput",
         "value": "",
         "placeholder": "Enter Full Name",
         "label": "Full Name",
         "validation": {
            "maxLength": 30,
            "minLength": 5
         },
         "styles": {
            "backgroundColor": "#00000000",
            "borderRadius": 5,
            "borderColor": "#4299e1",
            "errorTextColor": "#4299e1",
            "disabled": false,
            "visibility": "true",
            "textColor": "#4299e1"
         }
      },
      "numberInput1": {
         "type": "number",
         "styles": {
            "backgroundColor": "#f6f5ff",
            "borderRadius": 5,
            "textColor": "#4299e1",
            "borderColor": "#4299e1",
            "disabled": false,
            "visibility": "true"
         },
         "value": 22,
         "maxValue": 100,
         "minValue": 14,
         "placeholder": "Enter your age",
         "label": "Age"
      },
      "dropdown1": {
         "type": "dropdown",
         "values": [1, 2, 3],
         "displayValues": ["Male", "Female", "Prefer not to Answer"],
         "loading": false,
         "value": 3,
         "label": "Gender",
         "styles": {
            "disabled": false,
            "visibility": "true",
            "borderRadius": 5,
            "borderColor": "#4299e1",
            "justifyContent": "center"
         }
      },
      "datepicker1": {
         "type": "datepicker",
         "styles": {
            "borderRadius": 5,
            "disabled": false,
            "visibility": "true"
         },
         "value": "09/09/2023",
         "disabledDates": ["08/09/2023"],
         "enableTime": true,
         "format": "DD/MM/YYYY",
         "label": "Select a date"
      },
      "multiselect1": {
         "type": "multiselect",
         "styles": {
            "disabled": false,
            "visibility": "true",
            "borderRadius": 5
         },
         "displayValues": ["one", "two", "three"],
         "label": "Select options of your choice",
         "value": [2, 3],
         "values": [1, 2, 3],
         "showAllOption": true
      }
   },
   "submitButton": {
      "value": "Submit",
      "styles": {
         "backgroundColor": "#3A433B",
         "borderColor": "#595959"
      }
   }
}
`

**Comment by christian-konrad** [comment]
Thank you @PriteshKiri ! It seems that the original issue has been solved two weeks ago directly after the v3 release. Do you want me to keep this issue open until the docs are fixed or should I close it?

**Comment by PriteshKiri** [comment]
Gald to hear that. Closing the issue
