### ISSUE TITLE
Form dropdowns show the first 3 options only

### ISSUE THREAD

**Issue by christian-konrad** [ToolJet/ToolJet#11312]
### Version Information

ToolJet Cloud v3.0.1

### Environment

ToolJet Cloud

### What is the expected behaviour?

A dropdown in a form using a custom schema should show all passed options.

### What is the current behaviour?

The dropdown shows the first 3 options only.

### How to reproduce the issue?

1. Add a form component and define a custom schema with a dropdown
2. Define more than 3 options for the dropdown
3. Test it (in editor, preview, or production) - it shows the first 3 options only

### Screenshots or Screencast

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/c32b4415-26d6-408f-90bc-9f00513f14d8">

### Any possible solutions?

Inspecting the (obfuscated) code, it seems that the component mixes up the predefined options and custom options. However, it should ignore these predefined options in a custom form schema.
 
<img width="525" alt="image" src="https://github.com/user-attachments/assets/a39fc5da-6cb8-4cb1-9dd7-cf9b0d6ece1e">

**Comment by PriteshKiri** [comment]
Hey @christian-konrad,

Thanks for creating the issue! This has been resolved and deployed.

Closing the issue now.
