### ISSUE TITLE
Card text in Library is not legible in dark mode

### ISSUE THREAD

**Issue by RajMhatre20** [ToolJet/ToolJet#1134]
Current state:
![image](https://user-images.githubusercontent.com/68785723/137756778-b5b927fc-6dc8-4f26-a0ca-dda28dea6446.png)
Expected state:
![image](https://user-images.githubusercontent.com/68785723/137757555-82dc4097-3ce1-45ff-bb01-2ab187a95c96.png)

**Comment by RajMhatre20** [comment]
Can I work on this?

**Comment by Navaneeth-pk** [comment]
Sorry, the code for the library component is not public yet. It will be public once the import-export feature is merged #89. Keeping this issue open. 
@RajMhatre20

**Comment by ivelin-web** [comment]
Can I take this?
