### ISSUE TITLE
Edit version CTA interaction 

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#11342]
Save CTA should be disbaled if no changes are there to be saved in Edit version popup

**Comment by AtharvaJoshi16** [comment]
Hi @nechalmaggon , need more insights on this bug to pick this up, please mention the page details where this bug has occured.

**Comment by nechalmaggon** [comment]
Hey @AtharvaJoshi16 apologies for the late response, we had intended to solve this internally earlier but since you've shown interest, allow me to elaborate on the issue - 

When `renaming` a new version, the name must be unique, must be different from the existing name and cannot be empty. If the name entered doesn't satisfy any of these parameters, the button is disabled. In this case, the difference from the existing name is not handled. Essentially if I open the modal and I don't make any change or I make a change and revert it back to the previous name, the button should be disabled since there's nothing to update in the new name. 

Your screen recording shows that you've handled the empty name case, what's missing is the `same as existing name` case. If you're still interested in working ahead on this issue, we will assign it to you. Do let us know if you have any doubts! 

cc- @PriteshKiri

**Comment by nechalmaggon** [comment]
@AtharvaJoshi16 We'd like to keep the `Save` button disabled when there's no change to the name. You can refer how we handle renaming for applications to get a better idea - 

https://github.com/user-attachments/assets/a6853908-0642-4552-9db6-12f3b4abecc3

Assigned the issue to you - happy coding! :)

**Comment by AtharvaJoshi16** [comment]
@nechalmaggon Thanks! Just one question. Should we keep the code for popup "Version name already exists" as is or is it to be removed as well?

**Comment by nechalmaggon** [comment]
@AtharvaJoshi16 That pop-up would still be needed for cases where the new version name exists for a different version. Eg. I have versions v1, v2, v3 - 

I rename version v2 -> v2 (don't make a change to the current name)  - button disabled
I rename version v2 -> v3 (change the name to a different version's name) - I click on save changes and get a pop-up stating the name already exists

**Comment by AtharvaJoshi16** [comment]
@nechalmaggon  Got it. Thanks! Will update the PR once I have bandwidth.

**Comment by AtharvaJoshi16** [comment]
@nechalmaggon Pushed changes.
PR: https://github.com/ToolJet/ToolJet/pull/11349

cc: @PriteshKiri 

Video: 

https://github.com/user-attachments/assets/5c531736-1750-4094-a724-3a947a4d2b8b

**Comment by nechalmaggon** [comment]
@AtharvaJoshi16 Looks good, and a really quick turnaround! Sending this to the team for approval - thanks for your contribution! 🙌

**Comment by AtharvaJoshi16** [comment]
@nechalmaggon Great! Looking forward to contributing to more issues! 😊
