### ISSUE TITLE
Feature:  add a clear button (search bar widget manager)

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1145]
![image (1)](https://user-images.githubusercontent.com/67645175/137866004-15337372-e06b-4f23-a360-22ed24855857.png)
Add a button to clear the search field when `No results found for the filter`

### Note: 
- the button should be along with the text "No results found"

**UI Reference:** 
<img width="242" alt="Screenshot 2021-10-19 at 1 24 42 PM" src="https://user-images.githubusercontent.com/67645175/137867637-b36cca5d-befd-4841-866f-85c371c821a3.png">

**Comment by arpitnath** [comment]
@heytulsiprasad, You are still working on it or have you already raised a PR?

**Comment by heytulsiprasad** [comment]
> @heytulsiprasad, You are still working on it or have you already raised a PR?

@arpitnath I'll work on it over this weekend, got caught up in work.
