### ISSUE TITLE
Bugfix: Number input widget shouldn't have a border radius.

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1156]
<img width="1291" alt="Screenshot 2021-10-20 at 12 01 42 PM" src="https://user-images.githubusercontent.com/67645175/138040050-a8b957e3-a08c-4dd7-9382-e1e4788f94ea.png">

For UI style consistency, the border radius of the `Numberinput` widget should be 0

**Comment by arpitnath** [comment]
Thanks, @Ksathwik03  and @chehak123. As both of your comments came in almost simultaneously. Our policy is FCFS, and I @Ksathwik03 's comment came first. I am assigning this issue to @Ksathwik03, inviting you to explore the other issues @chehak123

**Comment by Ksathwik03** [comment]
@arpitnath can you help me solving this issue i got struck 😅.
