### ISSUE TITLE
Bugfix: Add padding (left) to the datepicker widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1158]
There should be some left-side padding for datepicker widget.
<img width="1291" alt="Screenshot 2021-10-20 at 12 05 46 PM" src="https://user-images.githubusercontent.com/67645175/138040668-a8e382d0-5add-4ccf-8e02-64363df3728e.png">

**Comment by saisumanthkumar** [comment]
@arpitnath can I work on this ?

**Comment by Ksathwik03** [comment]
Can i work on this
