### ISSUE TITLE
[docs]: Update the Styles table in PDF Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11703]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/pdf#styles

- Update the columns of Style table to "Property", "Description" and "Configuration Options"
- Update the content as given in  - [Reference](https://docs.tooljet.com/docs/widgets/text-input/#additional-actions) (check the visibility row in Additional Actions table)

In current docs:

![Screenshot 2024-12-24 at 12 47 28 PM](https://github.com/user-attachments/assets/f35c583e-27b5-4e20-ae53-52fc20e11063)

Reference doc:
![Screenshot 2024-12-24 at 12 48 01 PM](https://github.com/user-attachments/assets/637b02c2-6d3d-413f-b7fa-a3070d0ca5bf)

The changes are to be implemented in three files -
Next - ToolJet/docs/docs/widgets/pdf.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/pdf.md
Version 3.0.0 (LTS) - ToolJet/docs/versioned_docs/version-3.0.0-LTS/widgets/pdf.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Himanshu3141** [comment]
can i work on this issue?

**Comment by Ayushraj1605** [comment]
hey @PriteshKiri i would like to work on this issue.

**Comment by PriteshKiri** [comment]
@Ayushraj1605  assigned!!

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 5 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment]
Hey @Himanshu3141,

Thank you for your interest in contributing! We have assigned you to another issue and are looking forward to your contributions there :)

**Comment by Ayushraj1605** [comment]
Hey, @PriteshKiri I have created a PR.

**Comment by PriteshKiri** [comment]
Hey @Ayushraj1605,
Thank you so much for your contribution! 🙌
Please keep an eye on your PR, as we may add some review comments if needed before merging it.
