### ISSUE TITLE
[docs]:Update the Devices table for the Table Component

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#11717]
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/table/table-properties/#devices

Please check the [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) for the Device Table.
- Update the column name from "Options" to "Property"
- Update the content of the table as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices).

Table in current docs:
![Screenshot 2024-12-27 at 12 16 13 PM](https://github.com/user-attachments/assets/d81f4d3a-80fe-422c-97ba-59e45f8a99da)

Table in reference:
![image](https://github.com/user-attachments/assets/d1b96641-a985-47cd-9168-d7c6f9995e56)

The changes are to be implemented in three files -
Next - ToolJet/docs/docs/widgets/table/properties.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/table/properties.md
Version 3.0.0 (LTS) - ToolJet/docs/versioned_docs/version-3.0.0-LTS/widgets/table/properties.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by mehant-kr** [comment]
Hi @PriteshKiri, may I take up this issue?

**Comment by Afomiat** [comment]
I would love to work on this issue

**Comment by Anuj012004** [comment]
Hi @PriteshKiri I've created a PR related this could you please have a look?

**Comment by PriteshKiri** [comment]
Hey @Anuj012004,

Thanks for your contribution! Just a reminder to please start working on an issue only after it has been officially assigned to you. We’re approving the PR this time, but please keep this in mind for future contributions.

Thank you for your understanding!

**Comment by PriteshKiri** [comment]
Hey @mehant-kr @Afomiat, please check other issues with `community contribution` label.
