### ISSUE TITLE
[Docs] Add documentation for DynamoDB datasource

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1225]
Reference: https://docs.tooljet.io/docs/data-sources/postgresql/

**Comment by vijaykrishna536** [comment]
Hi @arpitnath 
Can I work on this?
Thank you

**Comment by arpitnath** [comment]
Sure, assigning the issue to you @vijaykrishna536

**Comment by vijaykrishna536** [comment]
Hi @arpitnath 
From where can I get the images?
