### ISSUE TITLE
[docs] Add documentation for  Slack Api data-source 

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1234]
Reference: https://docs.tooljet.io/docs/data-sources/airtable

**Comment by nishant-giri** [comment]
@arpitnath, could I kindly work on this issue?

**Comment by arpitnath** [comment]
> @arpitnath where would it be ideal to insert the documentation? Also, I didn't come across a mention of Slack Api.

@RaOneG Hi, sorry for the delayed response.
So ideally it should be in the datasource reference.
path: `docs/docs/data-sources`

Reference of Slack Datasource Api
<img width="1169" alt="Screenshot 2021-11-03 at 2 26 42 AM" src="https://user-images.githubusercontent.com/67645175/139950465-317e3833-fe4b-40da-ab4b-652c5b1c0095.png">

**Comment by withshubh** [comment]
Closing this issue. I'll be picking this up.
