### ISSUE TITLE
[docs]: Add image/gif for Firestore datasource

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1235]
1. Adding a Firestore data source
2. Querying Firestore

Reference: https://docs.tooljet.io/docs/data-sources/airtable

**Comment by vijaykrishna536** [comment]
Hi @arpitnath 
If this issue is not worked upon by anyone
Can I work on this issue?
Thank you

**Comment by michizhou** [comment]
Hi @vijaykrishna536 I am actually in the process of making the changes for this issue and will be opening a PR soon.
