### ISSUE TITLE
[docs]: Update MySQL datasource image

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1236]
Current UI : 
<img width="750" alt="Screenshot 2021-10-24 at 11 26 19 AM" src="https://user-images.githubusercontent.com/67645175/138582731-1af0a169-5b73-4d6d-af35-a32e20fe2e94.png">

Docs: https://docs.tooljet.io/docs/data-sources/mysql

**Comment by chtnnh** [comment]
@arpitnath could I give this issue a shot? I noticed that the PR linked to this issue was closed
