### ISSUE TITLE
[docs]: Update Elasticsearch datasource image

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1237]
current UI:
<img width="750" alt="Screenshot 2021-10-24 at 11 28 33 AM" src="https://user-images.githubusercontent.com/67645175/138582796-b5fed248-ca42-45de-9928-9ce04262dcdb.png">

dos: https://docs.tooljet.io/docs/data-sources/elasticsearch

**Comment by vijaykrishna536** [comment]
Hi @Navaneeth-pk 
If this issue is still up for grabs 
Please assign this to me 
Thank you
