### ISSUE TITLE
Feature: Embed Widget/HTML Widget

### ISSUE THREAD

**Issue by lublak** [ToolJet/ToolJet#1278]
### Is your proposal related to a problem?

currently I want to display various files (as an example: PDF) directly. For this you might need some kind of embed.
Also videos would be useful.

### Describe the solution you'd like

Besides a possibility to embed html directly in case the desired widget does not exist (maybe in a kind of template system). Would be a `<iframe>`/`<embed>` handy.

### Describe alternatives you've considered

if html can be embedded directly, a kind of ifame doesn't need to exist anymore because you can embed it yourself via html.

**Comment by Navaneeth-pk** [comment]
Embedding webpages is now possible: #1401 
@lublak
