### ISSUE TITLE
Upgrade the Issue Template to use GitHub Issue forms 📜

### ISSUE THREAD

**Issue by Rutam21** [ToolJet/ToolJet#1304]
## Introduction
GitHub has recently rolled out a public beta for their issue forms feature. This would allow us to create interactive issue templates and validate them.

ToolJet currently uses the older issue template format. The task is to create GitHub issue forms for this repository. 

## Tasks summary:
 - [ ] Fork & clone this repository
 - [ ] Prepare bug report issue form in .github/ISSUE_TEMPLATE/bug.yaml
 - [ ] Prepare documentation issue form in .github/ISSUE_TEMPLATE/documentation.yaml
 - [ ] Prepare feature request issue form in .github/ISSUE_TEMPLATE/feature.yaml
 - [ ] Push changes to master and test issue forms on your fork
 - [ ] Submit pull request

## If the feature is approved, would you be willing to submit a PR?

YES

**Comment by withshubh** [comment]
Thanks for creating this issue. 
We don't require the issue forms at the moment. Closing this issue - will reopen if required.
