### ISSUE TITLE
isValid boolean not working correctly

### ISSUE THREAD

**Issue by MichalisDBA** [ToolJet/ToolJet#1312]
### Environment
ToolJet Cloud

### What is the expected behaviour?
Other widgets must return the same boolean if they use the isValid from an input text widget

### What is the current behaviour?
isValid from input text widget returns correct boolean according to the validation it has but other widgets do not return the same boolean

### How to reproduce the issue?

1. Create 1 input text widget and 1 text widget
2. On input text widget in custom validation add {{components.input1.value === 'aassdd'}}
3. On text widget name add {{components.input1.isValid}}
4.  Observe the custom validation changing from false to true on input text widget but the text widget stays true no matter what

### Screenshots or Screencast
https://recordit.co/mHqXtM0Vio

**Comment by Navaneeth-pk** [comment]
Thanks for reporting this bug. @MichalisDBA 

Can you please take a look at this issue? @arpitnath

**Comment by MichalisDBA** [comment]
> Thanks for reporting this bug. @MichalisDBA
> 
> Can you please take a look at this issue? @arpitnath

Any new info about this problem?

**Comment by arpitnath** [comment]
@MichalisDBA Sorry, I might have missed this notification. Looking into the issue as soon as possible.

**Comment by arpitnath** [comment]
@MichalisDBA Hi, Sorry I am not able to reproduce the issue.
As you can see, other widgets do return the same boolean value of the `isValid`
https://user-images.githubusercontent.com/67645175/143660602-5f040c28-d103-4eb4-a597-c8d5262392aa.mp4

https://user-images.githubusercontent.com/67645175/143660650-1ec25a39-80de-4202-94f0-029a422475de.mov

**Comment by MichalisDBA** [comment]
> 

I did the same thing as the video you shown from a test account i created on your cloud service and the result is again wrong.

Something is definitely not working right.

Check the screen record.

https://recordit.co/hwEkQonvDK

**Comment by arpitnath** [comment]
@MichalisDBA

**Comment by arpitnath** [comment]
@MichalisDBA 
At present we cannot pass in comparison there. We have to pass in something like `value === 'correct' ? true: 'Your value is not correct'`

**Comment by arpitnath** [comment]
can you use `{{components.textinput1.value === 'one' ? true : "error"}}`

**Comment by MichalisDBA** [comment]
@arpitnath 

Yes now it's working. So it's a bug then or missing feature? I have to use ternary operators to do these things then?

**Comment by arpitnath** [comment]
> @arpitnath
> 
> Yes now it's working. So it's a bug then or missing feature? I have to use ternary operators to do these things then?

Yes, at present we have to use ternary operators to validate.
We will surely add proper documentation on this.
