### ISSUE TITLE
Server-side filter

### ISSUE THREAD

**Issue by lublak** [ToolJet/ToolJet#1315]
### Is your proposal related to a problem?

Currently, the filter on the table is only client-side.
But it would be practical to establish it on the server side as well.
Especially if you work with multiple pages (pageination).

### Describe the solution you'd like

A possibility to access the filters of the table in sql and to execute this quey on change (like in search or pageination)

### Describe alternatives you've considered

Tinker your own filtering together under or above the table.

**Comment by shubh22** [comment]
Hi, 

This feature is available now. Thanks!
