### ISSUE TITLE
Unable to re-invite archived user (or re-activate)

### ISSUE THREAD

**Issue by zachspar** [ToolJet/ToolJet#1320]
### Version Information
Latest

### Environment
Linux EC2

### What is the expected behaviour?
I should be able to re-invite an archived user. Or un-archive the user. Right now, when I try to re-invite an archived user's email it throws internal server error.

### What is the current behaviour?
I should be able to re-invite an archived user, or un-archive them in some way to make them active again.

### How to reproduce the issue?

1. Create a new user
2. Archive the user
3. Re-invite the same user created from step 1

### Please provide any traces or logs that could help here.
Internal server error will be seen upon button click.

### Any possible solutions?
N/A

### Can you identify the location in the driver source code where the problem exists?
N/A

### If the bug is confirmed, would you be willing to submit a PR?
Not enough time for my own work!

**Comment by akshaysasidrn** [comment]
This has been implemented https://github.com/ToolJet/ToolJet/issues/1693
