### ISSUE TITLE
Inspector hover highlight component

### ISSUE THREAD

**Issue by lublak** [ToolJet/ToolJet#1321]
### Is your proposal related to a problem?

Currently there is no easy way to find components easily especially if you have made them invisible.
Or edit an invisible component.

### Describe the solution you'd like

In the inspector these components are listed. It would be really handy if you get a hightlight when you hover and when you "click" on the json component the options of the components are shown in the editor.

### Describe alternatives you've considered

If you have made them completely invisible and can't find a way to display them, you have no choice but to create a new form and adjust all settings beforehand. The export can help with this.

**Comment by withshubh** [comment]
This issue has been fixed in our recent upgrade of the inspector. Closing this issue.
