### ISSUE TITLE
All options as js

### ISSUE THREAD

**Issue by lublak** [ToolJet/ToolJet#1322]
### Is your proposal related to a problem?

Currently there are some options that cannot be controlled via js. And thus do not allow dynamic customization.

### Describe the solution you'd like

Currently here is a list of things I would like to dynamically customize:
- everything that has to do with colors, especially when working in the table I would like to mark certain values differently colored.
- Chart Type I would like to give the user the option to switch easily by himself.

### Describe alternatives you've considered

For the table there is currently no solution with the color of the text, for the selection of the chart type can be solved with visbility.

**Comment by withshubh** [comment]
Closing this issue as you can now customize/change the color of a particular cell or column using ternary statements.
Now JavaScript is supported by the editor.
