### ISSUE TITLE
The documentation hyperlink is not opening in new tab

### ISSUE THREAD

**Issue by ArthiSiva** [ToolJet/ToolJet#1341]
### What is the expected behaviour?

  The documentation hyperlink in footer of the pricing page should open in new tab

### What is the current behaviour?

   The documentation hyperlink in footer of the pricing page opens in same page.

I would like to work on this

**Comment by Navaneeth-pk** [comment]
The website is not part of this repository. Thanks for reporting the issue, we will fix it soon.
