### ISSUE TITLE
Feature: Option to make apps public 

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#135]

**Comment by nicoruti** [comment]
This issue has been closed without a comment. Is this possible or already implemented?
Public apps could be read-only (Viewer role) for non-logged in users.

**Comment by Navaneeth-pk** [comment]
@nicoruti This feature was implemented. You can go to the `share` menu of the editor and make apps public. You are right, the public applications will be read-only for non-logged-in users.

**Comment by nicoruti** [comment]
Hi @Navaneeth-pk 
Thanks for your quick answer. You are right, I found this setting. 👍
