### ISSUE TITLE
Show tooltip on comments tab which says indicates that the app needs to be saved to open comments

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#1357]
### Is your proposal related to a problem?

Presently, a new user will get confused why they can't open the comments tab, it is unclear that at least one version of the app needs to be saved for the comments section to be activated.

### Describe the solution you'd like

Show a tooltip on hover of the inactive comments section icon, which indicates that at least one version of the app needs to be saved.

**Comment by saisumanthkumar** [comment]
@sherfin94 can I work on this ?

**Comment by sherfin94** [comment]
@saisumanthkumar Sure, assigned you, thanks.
