### ISSUE TITLE
Alternative for componentWillReceiveProps since it is deprecated

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#139]
Alternative for componentWillReceiveProps is https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops

**Comment by saideepesh000** [comment]
Hey @Navaneeth-pk , I'll be working on it

**Comment by Navaneeth-pk** [comment]
@saideepesh000 Thanks for contributing. Assigned the issue.

**Comment by saideepesh000** [comment]
I tried this, but couldn't able to complete this properly, hence unassigning myself

**Comment by Lucifer8729** [comment]
Hey @Navaneeth-pk , I would like to work on it

**Comment by Navaneeth-pk** [comment]
@Lucifer8729 Sure, assigned the issue.

**Comment by arpitnath** [comment]
@ThisIsFaar are you still working on it?

**Comment by ThisIsFaar** [comment]
Yes.
