### ISSUE TITLE
Confirm if @types/* can be moved to devDependencies

### ISSUE THREAD

**Issue by Bhavin789** [ToolJet/ToolJet#1395]
### Version Information
Latest

### Environment

This is not a bug per se but kind of a config improvement
ToolJet Cloud / Docker / Linux / MacOS 

### What is the expected behaviour?
The `@types/*` should be in `devDependencies`

### What is the current behaviour?
The `@types/*` are in `dependencies`

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/15359575/141309210-4abd1d7d-773b-4f61-be1b-8d27470f34f8.png)

### Any possible solutions?
We can move all  `@types/*` to `devDependencies`.

### Can you identify the location in the driver source code where the problem exists?

It is present in `server/package.json`

### If the bug is confirmed, would you be willing to submit a PR?

Would be happy to help 🙂

**Comment by Navaneeth-pk** [comment]
Can you please verify this issue?
@gondar00

**Comment by gondar00** [comment]
I think it's fine to move `@types/*` to `devDependencies` as we aren't directly importing types in code currently, 

more info can be found [here](https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies)

@Bhavin789 feel free to open a PR 👍

**Comment by Bhavin789** [comment]
Got it. Thanks for the confirmation @gondar00. Will raise a PR for the same.

**Comment by Bhavin789** [comment]
Hi @Navaneeth-pk @gondar00 , really sorry for a late response on this but have created a small PR [here](https://github.com/ToolJet/ToolJet/pull/1715) for a lookout. Thanks!
