### ISSUE TITLE
Support for raw mongo queries

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1403]
Right now the MongoDB data source supports only three operations. To add more flexibility to the users, having an operation that can execute raw Mongo queries will be helpful. 

Ref: https://tooljet.slack.com/archives/C01TY0ZGH6X/p1636742594050300

**Comment by akshaysasidrn** [comment]
Looks like we would require to use mongo `eval()` to do this which is not [advisable](https://www.mongodb.com/community/forums/t/eval-replacement-in-4-2/2917) and furthermore is getting deprecated. We would have to make do with having separate actions which are tagged in issue #842. @Navaneeth-pk
