### ISSUE TITLE
Add support for SSO via OpenID Connect

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#1404]
### Is your proposal related to a problem?

Presently, there is no support for SSO via OpenID Connect.

### Describe the solution you'd like

Add support for SSO via OpenID Connect.

**Comment by xgp** [comment]
@sherfin94 Per our Slack conversation, please ping me when you have ported the Google SSO feature to the community edition. I'm happy to help with the work on a generic OIDC connector when it's there.
