### ISSUE TITLE
File Picker Incorrectly encodes binary data

### ISSUE THREAD

**Issue by igrekun** [ToolJet/ToolJet#1405]
### Environment
Docker

### What is the expected behaviour?
Being able to decode binary payloads

### What is the current behaviour?
reader.readAsText breaks binary files.

### How to reproduce the issue?
Use filepicker.file as value in post request.

### Any possible solutions?
Use base64 encoding or provide option to send file as form data.

### Can you identify the location in the driver source code where the problem exists?
Proposed crude fix in Editor/Components/FilePicker.jsx
```
reader.readAsDataURL(acceptedFile); # line 113 currently reads as text

content: zippedResults[0].srcElement.result.split(',')[1], # line 118 split data:binary data url part
```

### If the bug is confirmed, would you be willing to submit a PR?
Yes.

**Comment by arpitnath** [comment]
@igrekun Hi, https://tooljetpr-app.herokuapp.com/apps/96d4ea14-6223-4127-b751-d1184e2e8c36 , here is the first draft for the File Picker to encode binary data as a URL string correctly. 
Could you kindly check and let us know if it solves your issue?

**Comment by igrekun** [comment]
Yeah. The field data now contains base64 encoded binary. Seems great!
