### ISSUE TITLE
Incorrect placement for delete button on text input

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#1417]
![image](https://user-images.githubusercontent.com/12490590/142168296-d826eac0-03b0-4422-a420-93124bc2ae3b.png)

As per the image above the delete button (on hover) overlaps the text input, 

Possible solution: 
delete button should behave consistently as in other widgets, ex: on table widget appears on the widget drag handle

**Comment by gondar00** [comment]
![image](https://user-images.githubusercontent.com/12490590/142168707-abdf7f35-59e9-46c5-9e72-7ab2d84692d7.png)

Also, observed for button

**Comment by singh-vikas-m** [comment]
@gondar00 are you still working on this ?

**Comment by gondar00** [comment]
Nope, I'm not. Would you like to take this up?

**Comment by singh-vikas-m** [comment]
sure ✅

**Comment by ivelin-web** [comment]
Can I work on this?
