### ISSUE TITLE
Display the list of sheets as dropdown for Google sheets

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#143]
In the query editor for google sheets, fetch the list of existing sheets and make the user select a sheet from the dropdown instead of the user pasting the sheet id.

**Comment by saideepesh000** [comment]
Hi @Navaneeth-pk , can I take this up

**Comment by Navaneeth-pk** [comment]
Thanks for your interest in contributing to ToolJet. This is a very old issue, now we have more data sources requires similar feature ( eg: listing Airtable bases ). We will need a generic approach that can be extended across every data source with similar requirements. Closing this issue and will create another issue as a proposal for implementing this as a generic feature as part of plugins.

@saideepesh000
