### ISSUE TITLE
Show URL prefix for REST data source queries 

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#155]
If a query is being created using a REST data source, the URL of the data source should be shown as a prefix inside the field for URL.

**Comment by virajbahulkar** [comment]
@Navaneeth-pk working on it.

**Comment by Tam2** [comment]
Can you confirm if this will automatically include the REST data source URL as part of the query?

Currently, if I configure up a REST datasource with a URL of https://jsonplaceholder.typicode.com/

When running a GET request against `todos/1` it gives an error - same as https://github.com/ToolJet/ToolJet/pull/215 
I would expect this to form the URL as `https://jsonplaceholder.typicode.com/todos/1`

![image](https://user-images.githubusercontent.com/1256087/121489289-dc824100-c9cb-11eb-88e0-19c619e9f58b.png)

However, if I put the full URL in the GET request it works 

![image](https://user-images.githubusercontent.com/1256087/121489468-050a3b00-c9cc-11eb-888b-5741e4cb8c44.png)
