### ISSUE TITLE
Option to remove added datasource

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#1554]
### Is your proposal related to a problem?

I added the same datasource (Google Sheets) twice and I wanted to remove one but there is no option.

![Screenshot 2021-12-09 at 7 19 45 PM](https://user-images.githubusercontent.com/25361949/145408465-0ddacb09-1fcd-4870-a62c-73a565e7d5ef.png)

### Describe the solution you'd like

A delete/remove button next to the list of added datasources.

**Comment by aggmoulik** [comment]
Hey @Navaneeth-pk Can I work on this issue ?

**Comment by Navaneeth-pk** [comment]
Should we put this issue on hold until https://github.com/ToolJet/ToolJet/pull/1620 is merged?
@akshaysasidrn

**Comment by akshaysasidrn** [comment]
Would suggest so, as there will be some changes around data source deletion when versioning is added.
