### ISSUE TITLE
 Remove component if delete key is pressed after selecting the component

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#157]

**Comment by Amoghtech** [comment]
is this issue active?

**Comment by Navaneeth-pk** [comment]
@Amoghtech Yes

**Comment by Amoghtech** [comment]
> 
> 
> @Amoghtech Yes

Can you please tell me what do I have to do in this issue, briefly?

**Comment by Navaneeth-pk** [comment]
The selected widget should be deleted from the application if the delete key is pressed. However, this issue was incorrectly marked as `good first issue`, it might take some effort to ship this feature as the first contribution.

@Amoghtech

**Comment by Amoghtech** [comment]
> 
> 
> The selected widget should be deleted from the application if the delete key is pressed. However, this issue was incorrectly marked as `good first issue`, it might take some effort to ship this feature as the first contribution.
> 
> @Amoghtech

Ohkay i will try to resolve this issue, would you mind assigning it to me?
