### ISSUE TITLE
No more than 3 options can be there in either multi-select or dropdown.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#1581]
### What is the expected behaviour?
There should be multiple options available on both multi-select & dropdown.

### What is the current behaviour?
No more than 3 options are available for selection of values.

### How to reproduce the issue?

1. Drag and drop multi-select or dropdown
2. Go to options label.
3. Add more than 3 options.
4. Observe on screen.

### Screenshots or Screencast
https://drive.google.com/file/d/1U-7vQDbyIAqh1XEbiabujBTWEJniXvnp/view?usp=sharing

**Comment by Bhavin789** [comment]
Hello @Nandinisaha13, I think this issue exist because you haven't given `Option Values` for the last added option label (`"ok"`). I think if you provide the `Option Value` as `{{[1, 2, 3, 4]}}`, it should show up. Possible to confirm? Thanks cc// @gondar00

**Comment by Nandinisaha13** [comment]
@Bhavin789 tried it today and seems like what you are saying makes sense and works!

**Comment by gondar00** [comment]
Closing this issue
