### ISSUE TITLE
The date picker displays an invalid date while the format entered is wrong.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#1589]
### What is the expected behaviour?
The datepicker should display valid date or the previous date even when the date format is wrongly entered.

### What is the current behaviour?
When wrong date format was typed then the date picker showed invalid values in it and it does not change even when we correct the date format.

### How to reproduce the issue?

1. Drag and drop date picker.
2. Change the format to invalid.
3. Observe the date picker.

### Screenshots or Screencast
https://drive.google.com/file/d/1HcIZ_51IkoptV8oXBnnry0aGzXU08tA1/view?usp=sharing

**Comment by shivangT** [comment]
Resolved: confirmed by nandani
