### ISSUE TITLE
Dropdown set to "three" while the option labels are changed.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#1590]
### What is the expected behaviour?
The default should be changed as it is changed in the properties of the dropdown. The default option should be either blank or "select".

### What is the current behaviour?
The default selected option is set to "Three" even after the options label has been changed.

### How to reproduce the issue?

1. Drag and drop dropdown.
2. Change the option label.
3. Observe the default option on the dropdown

### Screenshots or Screencast
https://drive.google.com/file/d/1FY8dnmHuPoQDt9v4AP2va4Zu6E6o6s1P/view?usp=sharing

**Comment by Bhavin789** [comment]
Hi @Nandinisaha13 , I tried this, and it's weird that the `react-select-search` package which is used underneath is not giving the correct value whenever the component is getting updated 😢. There is a workaround fix that says to find the latest set of option labels from the options and serve the `value` that is recently updated. 

@gondar00 @Navaneeth-pk Let me know if I can help here. Thanks!

**Comment by gondar00** [comment]
@Bhavin789 would this issue be fixed by upgrading from `3.0.5` to `3.0.9`, I believe we can park this issue for now

**Comment by Bhavin789** [comment]
> @Bhavin789 would this issue be fixed by upgrading from `3.0.5` to `3.0.9`, I believe we can park this issue for now as we have added `react-select` in #1723

This is awesome, `react-select` is very believable 😄!
