### ISSUE TITLE
Date format ignored on range picker.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#1623]
### What is the expected behaviour?
The date format should not be ignored but should be displayable on the screen on the range picker. Also the date format if changed should reflect on the screen as well.

### What is the current behaviour?
Date format is not being taken into consideration to display on the screen, format should be reflected on the screen.

### How to reproduce the issue?

1. Drag and drop range picker
2. Observe the properties & screen.

### Screenshots or Screencast
https://drive.google.com/file/d/1w9GjcwDTMQTs-4U68zX86AXzR_MGi8_-/view?usp=sharing

**Comment by Bhavin789** [comment]
Hi @gondar00, if this is not been worked upon, can I give it a shot? Should be doable. Thanks!

**Comment by gondar00** [comment]
Sure @Bhavin789 assigning the issue to you 👍

**Comment by Bhavin789** [comment]
Hi @gondar00, added a fix in PR #1733. Thanks
