### ISSUE TITLE
[Query Manager] Preview & Create buttons show up without any datasource selected

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#1654]
![image](https://user-images.githubusercontent.com/12490590/147555402-91d87e92-70e6-4372-9c06-c0b0cff1c902.png)

Expected: 

Preview & Create button should show up only after a datasource has been selected

**Comment by karlrez** [comment]
I'd like to try fix this, can you assign me?

**Comment by gondar00** [comment]
Sure @karlrez assigning you 

P.S sorry for late reply missed the notification
