### ISSUE TITLE
[Query Manager] Display logo beside text inside data source selector 

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#1655]
![image](https://user-images.githubusercontent.com/12490590/147555678-2ab2abc5-bf51-414c-8f04-a16b238cefdb.png)

Expected: 
For quick classification show the logo of db/api/cloud beside the text

**Comment by karlrez** [comment]
Hi @gondar00, I am interested in adding this.

Would I be using the icons that already exist in: /frontend/assets/images/icons/editor/datasources ?

**Comment by gondar00** [comment]
Hey @karlrez yeah you can reuse the same icons present on the url you mentioned
