### ISSUE TITLE
Multiline JSON values causing server exceptions

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#166]
Eg: 

If the body of a Firestore document creation query is: 

```
{
"notes": "{{components.textarea1.vaue}}"
}
```

and if the value of {{components.textarea1.vaue}} is a multiline string, server crashes.

**Comment by JibranKalia** [comment]
I can try and tackle this one.

**Comment by Navaneeth-pk** [comment]
@JibranKalia Thanks :) assigned.

**Comment by JibranKalia** [comment]
I am not able to reproduce this bug. Maybe I am doing something wrong:

![image](https://user-images.githubusercontent.com/14208431/121829886-601c8600-cc89-11eb-8b90-2bb0de29957f.png)

Which successfully creates:

![image](https://user-images.githubusercontent.com/14208431/121829923-7591b000-cc89-11eb-9f8a-202b4b411989.png)

**Comment by Navaneeth-pk** [comment]
@JibranKalia 

The steps you followed are correct, might be an edge case, let's close the issue for now?

**Comment by JibranKalia** [comment]
Makes sense.
