### ISSUE TITLE
[Query manager] Select dropdown option on enter pressed

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#1663]
![image](https://user-images.githubusercontent.com/12490590/147636593-714e31f0-0599-47db-8795-1ade67463c4f.png)

Expected: 
When enter/return key is pressed the hovered option should get selected

**Comment by marboleda** [comment]
Hi @gondar00, can I work on this? I have the app up and running locally

**Comment by Navaneeth-pk** [comment]
Assigned the issue to you @marboleda.
