### ISSUE TITLE
Multiselect widget closes when single option is selected 

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#1669]
https://user-images.githubusercontent.com/12490590/147643381-c41c408b-e527-4674-8fe1-90240cfb63f3.mov

Expected:
On click multiselect should stay open until clicked outside

**Comment by Bhavin789** [comment]
Hi @gondar00 , I actually tried this but it cannot be resolved until [this](https://github.com/ToolJet/ToolJet/issues/984) bug is resolved 😢. Possible to verify once? Thanks!

**Comment by gondar00** [comment]
Hi, looks like `react-select-search` is no longer maintained, Mostly will be switching this component to `react-select` 👍

**Comment by gondar00** [comment]
fixed via #2551
