### ISSUE TITLE
Datepicker: Able to select a date when enable date selection is set to false

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#1672]
![image](https://user-images.githubusercontent.com/12490590/147644711-65449dff-14ed-4126-85db-873fd7a2f5ff.png)

Below items expected when enable date selection is set to false:
- The default value should change
- The format should change 
- Should not be able to select a date

**Comment by Bhavin789** [comment]
Hi @gondar00 , I think the issue exist in the library itself 😕. 

I tried it in [this](https://codesandbox.io/s/gifted-moon-4l6mk?file=/src/App.js) code sandbox.

It is reproducible only if we open a date picker, change the prop value to false, and then open it again. Possible to confirm once? Thanks!

**Comment by gondar00** [comment]
Yes the 3rd point looks like a issue with the datepicker library. 

For point 1 & 2 we need to add a fix

**Comment by shivangT** [comment]
Hey @gondar00 
Can you quickly update the status of this issue?
This has existed for quite a long, we should close it.

**Comment by withshubh** [comment]
This issue has been fixed.
