### ISSUE TITLE
Add disabled property to all interactive widgets

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#1673]
Sometimes, a widget might be disabled based on certain values from the api, 

need to add an additional disabled property to all interactive widgets like input, pickers etc

**Comment by Krish-bhardwaj** [comment]
Hi @gondar00 can u assign me this issue , i am new to opensource contribution, looking for some beginner level opensource contribution , if u can guide me how to go about this issue i can try solving this .

**Comment by withshubh** [comment]
Hey @Krish-bhardwaj 
Are you still interested in working on this issue?

**Comment by Shelly011s** [comment]
Hello, @gondar00 I would like to work on this issue, I would like to know more about the details of the issue.

**Comment by Gurpreet-Singh-Bhupal** [comment]
Hi @gondar00   ,please assign me this issue I have worked on similar type of bug before.Thanks in advance.

**Comment by withshubh** [comment]
Hey @Gurpreet-Singh-Bhupal - Any updates on it?

**Comment by Shelly011s** [comment]
If there are no updates from @Gurpreet-Singh-Bhupal, can I take up this issue?

**Comment by withshubh** [comment]
Sure! @Shelly011s 
Assigned it to you.

**Comment by withshubh** [comment]
Hey @Shelly011s - Any update on the PR? :)

**Comment by withshubh** [comment]
Unassigned @Shelly011s since there was no update. The issue if up for grab.

**Comment by shubh22** [comment]
Will create issues separately for all the components which do not have disabled property.
