### ISSUE TITLE
Table column configuration is resetting when we click on table data field and click outside

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#1677]
### Environment

Ubuntu 20.04 LTS
### What is the expected behaviour?

When we click on table data field and click outside, the column configuration should remain the same.
### What is the current behaviour?

The column configuration resets to the last saved value
### How to reproduce the issue?

1. Create a table
2. Remove a column
3. Click on the table data field
4. Click outside
5. Observe that the removed column automatically returns.

### Screenshots or Screencast

https://user-images.githubusercontent.com/20333972/147652458-d7b0e786-5f31-48bc-baf6-5509aafea4c9.mov

**Comment by Bhavin789** [comment]
Hi @sherfin94 , I am unable to reproduce this 😕. Can you confirm if this is still reproducible? Thanks

**Comment by sherfin94** [comment]
@Bhavin789 This got fixed yesterday. Somehow the issue was not linked to the PR. Apologies. Will close this asap.
