### ISSUE TITLE
Users status colour code varies on dark mode toggle

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#1690]
### Environment
0.12.2

### What is the expected behaviour?
Colour indication should be constant across dark/light mode toggle to avoid confusion

### What is the current behaviour?
Colour code vaires

### How to reproduce the issue?

1. login to app
2. visit `/users`
3. try toggling darkmode

### Screenshots or Screencast
![darkmode-users](https://user-images.githubusercontent.com/11629675/147745470-a1e5f497-7a93-4032-a319-403e3e3a11a7.gif)

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by ivelin-web** [comment]
Hey, I'm new to open-source and I want to try solve this issue. Can I try?
