### ISSUE TITLE
Encrypt REST query options

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#170]
Users should be given an option to encrypt certain fields of a REST query.

**Comment by Rabelaiss** [comment]
Claiming this issue
Claiming this issue
Claiming this issue

**Comment by Rabelaiss** [comment]
the issue is nto working

**Comment by vedant-z** [comment]
Claiming this issue

**Comment by vedant-z** [comment]
Claiming this issue

**Comment by Just-A-Pixel** [comment]
Can I pickup this issue?
