### ISSUE TITLE
Dark theme not applied to QueryManager

### ISSUE THREAD

**Issue by karlrez** [ToolJet/ToolJet#1745]
### Is your proposal related to a problem?

The dark theme is not applied to the QueryManager dropdown list:
![image](https://user-images.githubusercontent.com/47090434/148335723-b5d4cd36-a949-4cb6-b58a-7109d573c793.png)

(Write your answer here.)

### Describe the solution you'd like

We should change the white background in the dropdown to a darker shade like here:
![image](https://user-images.githubusercontent.com/47090434/148335950-ffc47d27-a97c-4218-82a7-cef6e1617063.png)

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by Navaneeth-pk** [comment]
Thanks for reporting the issue. Assigned to you as mentioned in the issue.
@karlrez
