### ISSUE TITLE
Invite button keeps buffering after an invitation

### ISSUE THREAD

**Issue by jithindasad** [ToolJet/ToolJet#176]
Description:
After inviting a new user, Invitation button keeps buffering without changing the page.

Refer:
![IMAGE 2021-05-28 18:02:09](https://user-images.githubusercontent.com/26083775/119984263-d315d380-bfde-11eb-870a-6c3a8ce918b9.jpg)

**Comment by prasadwalvekar** [comment]
@Navaneeth-pk Picking this up.

**Comment by prasadwalvekar** [comment]
@Navaneeth-pk Looks like this one was fixed? Not able to reproduce. Please see attached loom.

https://www.loom.com/share/289d377b41ac4c4293c3cdb150645552

**Comment by Navaneeth-pk** [comment]
@prasadwalvekar Thanks for looking into it. Let's close this issue.
