### ISSUE TITLE
Support Upper & Lower limit on Number input widget

### ISSUE THREAD

**Issue by abhinabaadhikari** [ToolJet/ToolJet#1760]
### Is your proposal related to a problem?

Presently the number input widget can go from negative infinity to positive infinity, and there’s no way to set a limit.

### Describe the solution you'd like

The widget should have properties for maximum and minimum.

### If the feature is approved, would you be willing to submit a PR?

Yes.

**Comment by sherfin94** [comment]
Thank you. This feature would be a nice add-on.
Since you mentioned you're willing to submit PR, I'm assigning you @abhinabaadhikari!
