### ISSUE TITLE
Apps and Library icon not proper

### ISSUE THREAD

**Issue by abhinabaadhikari** [ToolJet/ToolJet#1765]
### What is the current behaviour?
<img width="300" alt="Screenshot 2022-01-08 at 11 44 20 PM" src="https://user-images.githubusercontent.com/79746925/148655250-c95eb315-751d-41b7-af91-c3c38083b8f4.png">
The Apps and Library icon in the Nav bar of the homepage isn’t aligned properly and doesn’t follow the design language.

### What is the expected behaviour?
<img width="272" alt="Screenshot 2022-01-08 at 11 53 19 PM" src="https://user-images.githubusercontent.com/79746925/148655339-8a86e367-dc1b-4815-837b-5d5c9b5fc248.png">
I have designed the icons myself.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by Navaneeth-pk** [comment]
These icons and links will be removed from the header once the PR for application templates redesign is merged. 
@abhinabaadhikari
