### ISSUE TITLE
Able to create folder with existing folder name

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#1817]
### What is the expected behaviour?
Should show error that the folder name already exist

### What is the current behaviour?
Able to create folder with existing folder name

### Screenshots or Screencast
![Screenshot 2022-01-13 at 7 49 13 PM](https://user-images.githubusercontent.com/3417097/149346967-6d0ff099-39d9-4006-8770-cc0f98b3c6a5.png)

**Comment by ivelin-web** [comment]
Can I work on this?

**Comment by Navaneeth-pk** [comment]
Sorry for the delay in response, somehow missed the notification. Assigning to you @ivelin-web

**Comment by Srisuma13** [comment]
@withshubh @shubh22 Can I pick this up? I would like to work on this.

**Comment by withshubh** [comment]
Hey @Srisuma13 - Any updates on it?

**Comment by thehacklady** [comment]
@gsmithun4 closing this since we have already fixed it with this issue : https://github.com/ToolJet/ToolJet/issues/5663
