### ISSUE TITLE
email field verification is not proper

### ISSUE THREAD

**Issue by johnbabu021** [ToolJet/ToolJet#1819]
### Environment
    ToolJet Cloud 

### What is the expected behaviour?

when clicking create account in main page without entering email shows 
Please check your email for the confirmation link.

### What is the current behaviour?

if we didn't enter the mail it doesn't say an alert

### How to reproduce the issue?

1.check the length of string

### Screenshots or Screencast
![Screenshot from 2022-01-13 21-17-20](https://user-images.githubusercontent.com/58719884/149363601-004244ec-ec15-4a7b-95c4-ebab600e6d3f.png)

### If the bug is confirmed, would you be willing to submit a PR?
yes

**Comment by Navaneeth-pk** [comment]
The website is not part of this repository. Closing the issue. Thanks for reporting, it will be fixed soon.
@johnbabu021
