### ISSUE TITLE
Empty folder text in any open folder is not legible in dark mode

### ISSUE THREAD

**Issue by ivelin-web** [ToolJet/ToolJet#1835]
### Environment

`Docker`

### What is the expected behaviour?

![Capture2](https://user-images.githubusercontent.com/72993041/149582940-8e478b31-c9ef-49e3-be14-95b677a78d88.PNG)

### What is the current behaviour?

![Capture](https://user-images.githubusercontent.com/72993041/149582966-692a0608-b1d7-405d-9b26-382d97288941.PNG)

### How to reproduce the issue?

1. Open the app locally
2. Create a new folder
3. Check text

**Comment by akshitarora921** [comment]
Can I take this?

**Comment by Navaneeth-pk** [comment]
@akshitarora921 This issue got resolved when the folders section was reworked.
