### ISSUE TITLE
Forgot password not working.

### ISSUE THREAD

**Issue by keshavbiswa** [ToolJet/ToolJet#187]
Steps for reproduction

1. Try login in using confirmation email
2. Enter invalid password
3. click on forgot password

Outcome:
Blank page on `https://app.tooljet.io/forgot-password`

**Comment by amitava82** [comment]
Actually any direct link to a path isn't working. Throwing 404

**Comment by Navaneeth-pk** [comment]
Sorry, We did not build the forgot password feature. Totally missed it. It will be ready in a day or two. Thanks for reporting this important issue.

**Comment by apoorv1316** [comment]
Assign me
