### ISSUE TITLE
Allow copy and paste of widgets

### ISSUE THREAD

**Issue by mygrexit** [ToolJet/ToolJet#1882]
### Is your proposal related to a problem?

It would be nice to allow copy and pasting of widgets like input fields

### Describe the solution you'd like

Copy TEXTINPUT1, paste it and have TEXTINPUT2

### Describe alternatives you've considered

None.

### If the feature is approved, would you be willing to submit a PR?

I'm not a programmer :)

**Comment by gondar00** [comment]
Resolved in #1970
