### ISSUE TITLE
Add S3 compatible services

### ISSUE THREAD

**Issue by mygrexit** [ToolJet/ToolJet#1884]
### Is your proposal related to a problem?

Many of us prefer ToolJet because it is open source.
For this reason, or with this mindset, there are certainly many people who avoid AWS.

While minio is also offered, there are a lot of small S3-compatible providers that you could use.

Retool offers such an integration, so it would be nice if this would also find its way to ToolJet.

The only problem I see is that some providers want to see specific information in the header for CORS requests. I have to say that I have not dealt with this in depth.

### Describe the solution you'd like

The ability to use all S3-compatible services.

### Describe alternatives you've considered

None.

### If the feature is approved, would you be willing to submit a PR?

Not a programmer :)

**Comment by begna112** [comment]
The only real change needed to support most s3-compatible storage solutions is manually setting the endpoint. 

Here's Wasabi's javascript docs, for example: 

https://wasabi-support.zendesk.com/hc/en-us/articles/115002350192-How-do-I-use-AWS-SDK-for-JavaScript-with-Wasabi-

Other than that, you can use the exact same aws-sdk as for AWS S3 natively (in most cases).
