### ISSUE TITLE
Default credentials do not work (heroku)

### ISSUE THREAD

**Issue by amitava82** [ToolJet/ToolJet#190]
`The default username of the admin is dev@tooljet.io and password is password.` This does not work

**Comment by troytc** [comment]
I also deployed to Heroku, and tried wiping out the `User`, `Organization`, and `OrganizationUser` tables, then recreating the initial account as listed in https://docs.tooljet.io/docs/contributing-guide/setup/Mac%20OS, but still no luck.

**Comment by Navaneeth-pk** [comment]
@amitava82 @troytc 

Can you please make sure the environment variable `TOOLJET_SERVER_URL` is pointing to the URL of your Heroku application?

Meanwhile, let me try to reproduce the issue at my end.

Thanks for reporting the issue.

**Comment by soorajshankar** [comment]
Hello @amitava82 @troytc, 

I just tested the heroku deployment it seems working fine. let me put the exact steps that I followed here. 

1. Click on [Deploy To Heroku](https://heroku.com/deploy?template=https://github.com/tooljet/tooljet/tree/main)
2. Filled the heroku deploy form as shown below
![image](https://user-images.githubusercontent.com/8408875/121059698-65885500-c7df-11eb-95a5-3ba91b2dc246.png)
 3. Make sure `App name` is used to format the `TOOLJET_HOST` and `TOOLJET_SERVER_URL` 
 4. Provide secrets
 5. Clicked on `Deploy App`
 
Technically Heroku will pull, build and deploy the repository and afterwards it run the postDeploy script to seed the default user.

Could you try this once again?

**Comment by yoavTaieb** [comment]
Same here, very strange. I checked on the sql database and the user exist, but it's like the form don't try to fetch the server (there is no loading, immediately an error banner).

<img width="561" alt="Screen Shot 2021-06-07 at 20 33 08" src="https://user-images.githubusercontent.com/66865717/121063910-95c7f780-c7cf-11eb-825a-26f30e6822e3.png">

**Comment by tejaswinichile** [comment]
@amitava82 @troytc @yoavTaieb 
I just tested the deployment, It's working fine. 
<img width="560" alt="Screenshot 2021-06-07 at 11 10 34 PM" src="https://user-images.githubusercontent.com/10827585/121066203-3ece1c80-c7e7-11eb-9ca8-7747fcaa19f8.png">
<img width="560" alt="Screenshot 2021-06-07 at 11 08 41 PM" src="https://user-images.githubusercontent.com/10827585/121066215-41c90d00-c7e7-11eb-8e83-45f812f21bcc.png">

Although @Navaneeth-pk `dev@tooljet.io and password is password` these credentials aren't working.

**Comment by soorajshankar** [comment]
Folks,

i would need some more information to debug this 

* Does this happen only while first time deployment? 
* could you make sure that there is no errors on the build logs?
* make sure the DB has the default user added?

* could you open the browser network tab, and try logging in again then share the HTTP error if you are getting any? (request to `YOURAPP_NAME.herokuapp.com/authenticate`

**Comment by Fusion** [comment]
I had the same issue. I believe it's because I stupidly left `<app-name-in-first-step>` as-is, assuming it would be interpolated during install.
I destroyed my app and re-installed with the proper subdomain filled in, and it is now working fine.

**Comment by amitava82** [comment]
> I had the same issue. I believe it's because I stupidly left `<app-name-in-first-step>` as-is, assuming it would be interpolated during install.
> I destroyed my app and re-installed with the proper subdomain filled in, and it is now working fine.

Same here.
Closing this issue.
