### ISSUE TITLE
Ui inconsistency - update the colors of `create query` button

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#1900]
![image](https://user-images.githubusercontent.com/7828962/150665471-bcb9647b-6c93-4c3e-9488-d4444f5bba9c.png)

`Create query` button should be similar to other buttons in the editor. For example, 

![image](https://user-images.githubusercontent.com/7828962/150665487-f356a1e6-78fb-4408-8f66-c88f262b6aa8.png)

**Comment by KiDxS** [comment]
May I?

**Comment by Navaneeth-pk** [comment]
Sure, assigned @KiDxS
