### ISSUE TITLE
Add `client_credentials` as Rest API Grant Type

### ISSUE THREAD

**Issue by PiotrKrzyzek** [ToolJet/ToolJet#1903]
### Is your proposal related to a problem?

The Rest API authentication is missing a few features required to make it fully usable. Currently, an important API we use for work requires the `client_credentials` grant type and thus as of this writing, we can't use ToolJet to interact with the API (since it can't authenticate itself).

### Describe the solution you'd like

In the Rest API Authentication modal, I'd like to see `client_credentials` added to the options list and made usable.

I believe this is the file in question where it would start, though I do not know if any other areas would require tweaking to allow this grant type:

https://github.com/ToolJet/ToolJet/blob/26c9cc655c9774936e1007c07263cac89cdf181d/frontend/src/_ui/OAuth/Authentication.jsx

### If the feature is approved, would you be willing to submit a PR?

Probably.

**Comment by Navaneeth-pk** [comment]
Thanks for reporting the issue.

Along with `Authentication.jsx`, we need to make changes to `https://github.com/ToolJet/ToolJet/blob/26c9cc655c9774936e1007c07263cac89cdf181d/server/plugins/datasources/restapi/index.ts` too. 

Please let me know if you want to work on this feature. If you don't want to or if you cannot, our team can prioritise this issue for the next release.

**Comment by PiotrKrzyzek** [comment]
Ah, alas Oauth is out of my wheelhouse so I don't know how to help on this item. :( My apologies.

**Comment by twistedpro** [comment]
+1

**Comment by nabby27** [comment]
Hi everyone! I will be more than happy to create a reward for this issue through [Opire](https://opire.dev), the project I've recently launched. The only thing you have to do is install our app in your GitHub repository. Check our [documentation](https://docs.opire.dev) to know more about it

**Comment by mansukh-tj** [comment]
This will be solved by introducing another option Grant Type : "Client Credentials" for Authentication type: "OAuth 2.0"

![Image](https://github.com/ToolJet/ToolJet/assets/144771579/98f28610-5006-4079-aec6-ee3664f84ca0)
