### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by hagaiwech** [ToolJet/ToolJet#1921]
Hi ToolJet team,

I've tried to contact you several times through email, but received no response.
I'm approaching you regarding security issues found in your project. 

We have already passed the 30-days timeline since our first notice to you regarding these issues. By this time if we don't get a response we usually proceed with assigning CVEs for these vulnerabilities without a fix. This is not recommended for users of your application and for the community's security. We try to minimize the occurrences of such cases, thus we reach out to you for the last time, requesting a response.

If you intend to provide the community and your users a fix for these vulnerabilities, please get back to us through email:
hagai.wechsler@whitesourcesoftware.com

Otherwise, if we still don't get a response, we will proceed with assigning CVEs a week from now.

Looking forward to hearing from you.

**Comment by Navaneeth-pk** [comment]
I just checked the emails, there aren't any emails that originated from addresses at `whitesourcesoftware.com` domain. Can you please send the emails to `hello@tooljet.io` once again?
@hagaiwech

**Comment by hagaiwech** [comment]
@Navaneeth-pk Yes sending now
