### ISSUE TITLE
Sort icon is dull in dark mode in table widget.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#1942]
### What is the expected behaviour?
The sort icon should be bright in the dark mode in table widget.

### What is the current behaviour?
The sort icon in table widget looks dull in dark mode.

### How to reproduce the issue?

1. Drag and drop table on canvas.
2. Click on sort for eg. name column.
3. Observe

### Screenshots or Screencast
https://drive.google.com/file/d/1f1zHLFuUewacgQl3NeWwY2LmGAJoTWU3/view?usp=sharing

**Comment by victoriadealba** [comment]
Hello I'm an undergraduate student looking to work on an open source project for one of my classes. I would like to know where in the files can I find this issue. I may be interested on taking this issue on

**Comment by Navaneeth-pk** [comment]
The related file is `frontend/src/Editor/Components/Table/Table.jsx`. You will have to find the HTML element with the issue and add CSS to `theme.scss` to fix the issue.

**Comment by Prathamesh247** [comment]
I would like to work on this @Navaneeth-pk
