### ISSUE TITLE
Long text overflow from cell in table widget

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#1945]
### What is the expected behaviour?
text to be wrapped or be scrollable in cell
new option to be added to include scroll, text wrapping so that text does not overflow.

### What is the current behaviour?
long text / sentences overflows in table.

### How to reproduce the issue?

1.drag and drop table component
2.write long  text in any of the fields 
3.text can be seen overflowing from the table cell

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2022-01-26 at 1 51 54 AM" src="https://user-images.githubusercontent.com/31006028/151053487-df669935-de08-4fd3-b5af-2273304d0f8c.png">

### Any possible solutions?

option/property can be included as a dropdown to set behaviour of text with options like wrap , scroll etc.

**Comment by victoriadealba** [comment]
Hello I'm an undergraduate student looking to work on an open source project for one of my classes. I would like to know where in the files can I find this issue, any ideas on how to implement this change?  I may be interested on taking this issue on

**Comment by stepinfwd** [comment]
Thanks for your interest but this issue is already fixed , you can search for other open issues with tags up for grabs or good first issue for contributing  but still if you need to check the code its in **frontend/src/Editor/Components/Table/Table.jsx**

**Comment by stepinfwd** [comment]
> Hello I'm an undergraduate student looking to work on an open source project for one of my classes. I would like to know where in the files can I find this issue, any ideas on how to implement this change? I may be interested on taking this issue on

Thanks for your interest but this issue is already fixed , you can search for other open issues with tags up for grabs or good first issue for contributing but still if you need to check the code its in frontend/src/Editor/Components/Table/Table.jsx

**Comment by Navaneeth-pk** [comment]
Related: https://github.com/ToolJet/ToolJet/issues/1917
