### ISSUE TITLE
[Feature request] GraphQL datasources

### ISSUE THREAD

**Issue by deathemperor** [ToolJet/ToolJet#195]
hey @Navaneeth-pk, congratz on the launch and incredible work. I was referred to ToolJet from HN.

I must be honest that I'm evaluating Retool for our commercial products and it's showing lot of limitations: price, customization, on premises, etc. Now that ToolJet is open source, I'll sure explore this option.

One thing I haven't seen mentioning is GraphQL datasources. Is this in your roadmap? I hope you can support it soon as our datasources are mostly GraphQL (we're investing heavily on GraphQL).

Another option is to develop a new datasource. I'm open for that too if there's a guideline of some sort.

Thanks for your incredible work!

**Comment by Navaneeth-pk** [comment]
GraphQL is definitely on the roadmap, we will update here when we have specific details on the timeline ( hopefully in a couple of weeks ).

**Comment by deathemperor** [comment]
great work! thanks.
