### ISSUE TITLE
The search box and total count in table widget should be removed if server side pagination selected

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#1951]
### What is the expected behaviour?
The search box and total count in table widget is not removed when server side pagination selected

### What is the current behaviour?
The search box and total count in table widget should be removed if server side pagination selected

### How to reproduce the issue?

1.drag and drop table widget
2.go to properties and toggle server side pagination  option
3.observe behaviour

### Any possible solutions?

updated to hide search box on if server side pagination is true

**Comment by sherfin94** [comment]
There doesn't seem to be valid anymore.
