### ISSUE TITLE
Show Search Box options gets removed if disabled in table widget

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#1952]
### What is the expected behaviour?
Show Search Box options gets must not get removed from ui upon toggling it.

### What is the current behaviour?
Show Search Box options gets removed on disable option.

### How to reproduce the issue?

1.drag and drop table widget
2.disable Show Search Box option from options.
3.observe option gets removed from ui.

**Comment by sherfin94** [comment]
Issue doesn't seem to be valid anymore.
