### ISSUE TITLE
[Docker] Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by deathemperor** [ToolJet/ToolJet#198]
<details>
<summary>Error: ENOSPC: System limit for number of file watchers reached</summary>
client_1    | Error from chokidar (/app/src/_components): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_components/PrivateRoute.jsx'
client_1    | Error from chokidar (/app/src/_components): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_components/index.js'
client_1    | Error from chokidar (/app/src/_helpers): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_helpers/appUtils.js'
client_1    | Error from chokidar (/app/src/_helpers): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_helpers/auth-header.js'
client_1    | Error from chokidar (/app/src/_helpers): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_helpers/handle-response.js'
client_1    | Error from chokidar (/app/src/_helpers): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_helpers/history.js'
client_1    | Error from chokidar (/app/src/_helpers): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_helpers/index.js'
client_1    | Error from chokidar (/app/src/_helpers): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_helpers/utils.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/app.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/appVersion.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/authentication.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/dataquery.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/datasource.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/folder.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/index.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/openapi.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/organization.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/organization_user.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/tooljet.service.js'
client_1    | Error from chokidar (/app/src/_services): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_services/user.service.js'
client_1    | Error from chokidar (/app/src/_styles): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_styles/tabler.scss'
client_1    | Error from chokidar (/app/src/_styles): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/_styles/theme.scss'
client_1    | Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/index.html'
client_1    | Error from chokidar (/app/src): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/src/index.jsx'
client_1    | Error from chokidar (/app/node_modules/codemirror/mode/rpm/changes): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/codemirror/mode/rpm/changes'
client_1    | Error from chokidar (/app/node_modules/codemirror/mode/rpm/changes): Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/codemirror/mode/rpm/changes/index.html'
</details>

**Comment by deathemperor** [comment]
running `echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p` on host fix this issue.

**Comment by Navaneeth-pk** [comment]
Closing this issue as we were not able to replicate it.
