### ISSUE TITLE
Default value in date picker widget accepts every value.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#1993]
### What is the expected behaviour?
Default property of date picker should allow numbers or "/" or"- " only

### What is the current behaviour?
The default value is taking every value for eg. A, * etc

### How to reproduce the issue?

1. Drag and drop date picker widget on the canvas.
2. Enter any value in default.
3. Observe on the canvas.

### Screenshots or Screencast
https://drive.google.com/file/d/1qS8PTBQEVr28n3ygJSExILmo9jM1ruj0/view?usp=sharing

**Comment by Emeka-Ugbanu-hub** [comment]
I would love to help with this

**Comment by Navaneeth-pk** [comment]
Thanks for contributing. Assigned the issue to you. @Emeka-Ugbanu-hub

**Comment by Emeka-Ugbanu-hub** [comment]
do i clone the entire repo because the repo is really big
