### ISSUE TITLE
OnPrem RestApi setting tabs not chaning

### ISSUE THREAD

**Issue by bytesynthesis** [ToolJet/ToolJet#2007]
### Environment
 
   Linux Ubuntu 20
   Cloned repo working branch from Tag  v01303

### What is the expected behaviour?
When trying to create a POST message, the body text box does not appear when switching to the Body tab.  Other tabs seem impacted as well

### What is the current behaviour?
Switching settings tabs for RestAPI doesn't show additional settings

### How to reproduce the issue?
Running from source branch  v0.13.3 try creating a RestAPI post messge and go to Body settings

### Screenshots or Screencast
![tooljetissue](https://user-images.githubusercontent.com/97140356/151670487-5590e066-20cd-455f-98bc-17c85ef89f1b.gif)

### Please provide any traces or logs that could help here.
my gif shows the dev console in chrome.  no obvious errors are displayed

### Any possible solutions?
not sure yet. will try rolling back to most recent stable release

### Can you identify the location in the driver source code where the problem exists?
no. sorry

**Comment by bytesynthesis** [comment]
i just did a complete rollback to 0.13.0, database and all, ant still have this problem.  unable to at a POST body query.  I'm trying to dig into it, but I'm not a JS super star by any means. I'm not sure if it's just me either.  Since I started using Tooljet a couple months ago I've only used GET methods

**Comment by sherfin94** [comment]
Hey @bytesynthesis , I tried it out on `0.13.6` and am able to POST to dummy hookbin.com end point, with body.

I have a feeling that you're actually able to switch tabs on that query panel, however, since all tabs have the same content (while you haven't filled any data), the UI doesn't seem to change. Could you check if this is the case?

**Comment by bytesynthesis** [comment]
Sure....I guess I expected a larger text for entering in a body message
though.  Is that just how the UI is then?  I may have made a false
assumption that the fields should have looked different based on the
content expected

**Comment by bytesynthesis** [comment]
I've been trying to get this to work.  The Post method works fine but when I debug it on the service side, I'm not getting the Body.  I can use the service from Postman and Swagger just fine, and all my GET methods work in TJ but not sure how to send json as a body using the Tooljet query window.  The documentation on the website doesn't go into any detail on Body messages either

**Comment by sherfin94** [comment]
Sorry to hear that, this is an area we're yet to improve. That said, its still possible to implement any POST request. One reason why you might be facing issues would be that you're using a nested POST body.

Here is my suggestion, firstly, try with a simple key `a` and value `b` and see if that body reaches your server properly. 

If you are providing an object as value, you will have to enclose it with `{{(` and `)}}` . The curly braces are for ToolJet to understand that it is an object and the parentheses is for JavaScript to understand that it is not a code block but an object. 

If you could share a sample body here, I'll be happy to help construct the required code that you need to paste on the value field.

**Comment by bytesynthesis** [comment]
Thanks. an example of passing any JSON body in a POST message would be great.  Do I need to store the json in an object and then pass the object as a value? if so, what do I use for the key.  In the headers tab it's obvious to use "Content-Type" as key and "application/json" . Thanks for your assistance

**Comment by bytesynthesis** [comment]
I modified my service to throw an error back so I could see the actual request being sent in the TJ UI.  the a-b kv test doesn't include any body.
![image](https://user-images.githubusercontent.com/97140356/151916737-026e370b-6a6e-4498-909e-4bada701afea.png)

**Comment by sherfin94** [comment]
> Thanks. an example of passing any JSON body in a POST message would be great. Do I need to store the json in an object and then pass the object as a value? if so, what do I use for the key. In the headers tab it's obvious to use "Content-Type" as key and "application/json" . Thanks for your assistance. An example body: { "field1":"value1", "field2":"value2" }

In order to implement this body, go to the body tab, add a field with key `field1` and set its value to `value1`, add another field with key `field2` and value `value2`

Let me give you another example, consider this body:

```
{
  "character" : {
     "name": "Luke Skywalker",
     "actorName": "Mark Hamil"
   }
}
```

To implement this, add a field with key `character` and its value should be `{{({"name":"Luke Skywalker", "actorName": "Mark Hamil"})}}`

Result captured on hookbin: 
![image](https://user-images.githubusercontent.com/20333972/152094346-c6402e73-1822-492e-8c3f-3cdf5c3fe2a9.png)

**Comment by bytesynthesis** [comment]
Thanks.  That helped a lot.  it's working now.  I'll close this since it's not actually a bug
