### ISSUE TITLE
[docs] Fix incorrect indentation

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2009]
Page: https://docs.tooljet.com/docs/deployment/docker

![image](https://user-images.githubusercontent.com/7828962/151691437-63767102-88b7-4b9b-9d5a-8f12862d0345.png)
The section is not aligned properly.

**Comment by gauravagrwal** [comment]
Hey @Navaneeth-pk,  can I take this one ?

**Comment by Navaneeth-pk** [comment]
Sure, assigned to you. @gauravagrwal
