### ISSUE TITLE
Docker setup instructions seem to be broken (at least for docker 20.10.2) 

### ISSUE THREAD

**Issue by remyhonig** [ToolJet/ToolJet#202]
Hi tried following the docker instructions https://docs.tooljet.io/docs/contributing-guide/setup/docker but I am not getting anywhere.

> Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
> docker-compose version 1.28.6, build 5db8d86f

According to the manual this should work: 
> docker-compose run rails db:reset
> ERROR: No such service: rails

After that there are more errors after following the instructions concerning the database connection

**Comment by Navaneeth-pk** [comment]
Can you please check the `docker-compose build` logs and make sure there aren't any errors? I was getting too many errors today as RubyGems was down (possibly) due to the Fastly outage.

**Comment by remyhonig** [comment]
I don't think that would make a difference in this case. There just is no service in the `docker-compose.yaml` that is called `rails`.

**Comment by Navaneeth-pk** [comment]
Sorry, my bad. You are right, the command should be `docker-compose run server rails db:reset`. 
Updating the documentation to fix this issue. Thanks for reporting this.
