### ISSUE TITLE
On the website "Create an account" takes empty string without giving validation errors

### ISSUE THREAD

**Issue by Sync271** [ToolJet/ToolJet#2105]
### What is the expected behaviour?
If an empty string is provided, it should prompt you to enter a valid email or validate through other means

### What is the current behaviour?
When you click on "Create an account" by leaving the "Your business email" field empty, it still says "Please check your email for the confirmation link."

### How to reproduce the issue?
Follow the attached gif

### Any possible solutions?
Could use a guard statement

https://user-images.githubusercontent.com/67158080/152235014-e73e6b56-d760-48a7-9373-c4814e48c69b.mp4

### Can you identify the location in the driver source code where the problem exists?
Couldn't find it, probably not part of the repo. Wasn't sure if this is the right place to post this issue

### If the bug is confirmed, would you be willing to submit a PR?
If it's in the repo, yes!

**Comment by Navaneeth-pk** [comment]
@Sync271 website is not a part of this repo. We will fix this soon. Thanks fro reporting.
