### ISSUE TITLE
MongoDB Projections don't seem to work

### ISSUE THREAD

**Issue by SpaceCow404** [ToolJet/ToolJet#2110]
### What is the expected behavior?
When putting in a projection in the Options like { _id: 0 } it doesn't return this data. 

### What is the current behaviour?
The projections seem to be ignored no matter what is set and I believe I've tried every possible combination of getting the projections to work. The other options like Sort and Limit work just fine.

### Any possible solutions?
From a quick look based on the plugins/packages/mongo/lib/index.ts the queryOptions.options pull in projections within the .find() however the later NodeJS drivers for MongoDB require that you call .project() after the find for projections.

**Comment by gsmithun4** [comment]
Looks like the placeholder info is wrong, should be `projection` instead of `projections` 
```
{ projection: { _id: 0 } }
```
this will work
