### ISSUE TITLE
Use a dropdown for heading buttons in rich text editor

### ISSUE THREAD

**Issue by virajbahulkar** [ToolJet/ToolJet#214]
Icon size should be same as h1 - h6 tags

**Comment by hnhparitosh** [comment]
Please let me work on this issue.

**Comment by Navaneeth-pk** [comment]
@hnhparitosh sorry, we missed your comment. Since it has been more than a month, assigning the issue to @saisumanthkumar

**Comment by saisumanthkumar** [comment]
@Navaneeth-pk I guess both this and #211 are same
