### ISSUE TITLE
Chat icon doesn't change to dark mode

### ISSUE THREAD

**Issue by Sync271** [ToolJet/ToolJet#2141]
### Environment

ToolJet Cloud
### What is the expected behaviour?

The SVG fill should be white and the background should match with the rest of the app in dark mode

### What is the current behaviour?

In dark mode, the chat icon to the bottom left when editing the app isn't affected by dark theme

### How to reproduce the issue?

1. Go to edit or create a new app

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/67158080/152646572-68ae1e3e-cc5f-40c4-8ac6-dac894f97619.png)
### If the bug is confirmed, would you be willing to submit a PR?
yes

**Comment by ivelin-web** [comment]
Could you assign me?

**Comment by Navaneeth-pk** [comment]
@Sync271 The chat icon is not a part of this repository. We will fix this soon, thanks for reporting !
