### ISSUE TITLE
Generic JDBC connector

### ISSUE THREAD

**Issue by yusuf-jkhan1** [ToolJet/ToolJet#2210]
### Is your proposal related to a problem?

The problem is I work at a startup with only a couple of data scientists and data engineers. None of us are very familiar with front end languages or frameworks, so developing a robust plugin with basically only Python and SQL knowledge is out of reach.

### Describe the solution you'd like

If there was a generic JDBC connector, then we could connect to our data sources such as Snowflake and Databricks/DeltaLake. 

### Describe alternatives you've considered

Wait till someone else requests it

### If the feature is approved, would you be willing to submit a PR?
Probably not

**Comment by shubh22** [comment]
Hi,
We have a connector for Snowflake available now. We would definitely be adding connectors of many other datasources. Please create an issue for any specific datasource you wish to see in ToolJet.
