### ISSUE TITLE
Allow SSO From GitHub Enterprise Instances

### ISSUE THREAD

**Issue by jimmybrancaccio** [ToolJet/ToolJet#2235]
### Is your proposal related to a problem?

There is currently the ability to SSO with GitHub.com but not GitHub Enterprise instances.

### Describe the solution you'd like

Having a quick peek [at the code](https://github.com/ToolJet/ToolJet/blob/develop/server/ee/services/oauth/git_oauth.service.ts) it looks like the URL is hardcoded to GitHub.com however I believe we could set this to an environment variable so one could insert the URL of their GitHub Enterprise instance in order to use that instead for SSO. If the variable isn't set then it could default to GitHub.com.

### Describe alternatives you've considered

At this time I am just use the "local" authentication mechanism (no SSO).

### If the feature is approved, would you be willing to submit a PR?

I could certainly try my best but I am not a very good developer.

**Comment by Navaneeth-pk** [comment]
Thanks for reporting this issue. @jimmybrancaccio 
@gsmithun4 Can you please take a look at this?
