### ISSUE TITLE
Change position of layouts section on the widget sidebar

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2244]
![image](https://user-images.githubusercontent.com/7828962/153763007-c5460cce-3849-4910-bb9c-2a4f8d65cc2e.png)

The `layout` section should be shown above the `forms` section as wodgets in `layouts` are needed more often than widgets in `forms`.

**Comment by Girish-Bharadwaj** [comment]
Hey! I would like to work on this.

**Comment by Navaneeth-pk** [comment]
@Girish-Bharadwaj Thanks for contributing to ToolJet, assigning the issue to you!
