### ISSUE TITLE
Inconsistent font weight on safari for folder name 

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2245]
a) Safari
<img width="344" alt="image" src="https://user-images.githubusercontent.com/7828962/153766099-977bba35-72a3-47e1-b47e-0acf99ef4a8b.png">

b) Chrome
<img width="334" alt="image" src="https://user-images.githubusercontent.com/7828962/153766117-e07f5f29-9118-44b4-b6f3-b68a03e3aede.png">

The font-weight on Safari should be the same for both browsers.

**Comment by ParisaTork** [comment]
Is there a test account for OS contributors to see which SCSS .class selector is causing this?

**Comment by Navaneeth-pk** [comment]
@ParisaTork you can create an account at ( https://tooljet.com ) but is recommended that the contributors run ToolJet on local machine for making changes to codebase. The instructions for setting up is documented here: https://docs.tooljet.com/docs/contributing-guide/setup/docker

**Comment by deepanshumidha5140** [comment]
Hey can I work on this issue

**Comment by AyushK-101** [comment]
Can I work on this?

**Comment by harsh472000** [comment]
@Navaneeth-pk  can i work on this ?

**Comment by withshubh** [comment]
> @Navaneeth-pk can i work on this ?

Hey @harsh472000 👋  
Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.
Please feel free to join our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by deepanshumidha5140** [comment]
@withshubh Ok

**Comment by PriteshKiri** [comment]
Closing the issue as it is fixed!
