### ISSUE TITLE
Loading state for statistics widget

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2246]
Similar to the widgets like buttons and charts, statistics widget should also have a loading state depending on which we show a spinner. 

Relevant file: `frontend/src/Editor/Components/Statistics.jsx`

**Comment by arpitnath** [comment]
picking this up

**Comment by savannahvaith** [comment]
Hey @Navaneeth-pk - If this is still available I can pick it up?

**Comment by arpitnath** [comment]
Hi @savannahvaith 
Assigning the issue to you.

**Comment by savannahvaith** [comment]
Hey @arpitnath - Sorry running into License issues, my mistake - sincere apologies.
