### ISSUE TITLE
Option to hide the secondary value and it's sign and label of statistics widget

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2247]
For some use cases, the secondary value of statistics widget might not be relevant. The users should be able to show/hide the secondary value and related properties ( Label and the sign ). 

Screenshot of items to be hidden:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/7828962/153767027-870b11ee-8b82-4bdd-acf2-867377eb5152.png">

**Comment by arpitnath** [comment]
picking this up
