### ISSUE TITLE
[GoogleSheets as DataSource] Query - Update data to a spreadsheet, Issue - Unable to set object key from components

### ISSUE THREAD

**Issue by ChavanSuyash** [ToolJet/ToolJet#2249]
### Environment
ToolJet Cloud

### What is the expected behaviour?
I am creating one small attendance tracker app with sheets as a data source. As per the requirement, the column name is the date of the month, and want to update a particular row value with the attendance status. For query update data to a spreadsheet, the body param object key can't be fetched from components. 
Expected ability to set object key value from components.

### What is the current behaviour?
For query update data to a spreadsheet, unable to set body param object key value from components.

### How to reproduce the issue?
1. Connect sheets data source, select query update data to a spreadsheet.
2. In the body, paste the following {{({'{{components.datepicker1.value}}':  "P"})}}

### Screenshots or Screencast
<img width="982" alt="image" src="https://user-images.githubusercontent.com/9391301/153798027-f412116a-09cd-4d4a-a8fe-a00d3566ae2d.png">

**Comment by Navaneeth-pk** [comment]
Can you please try: 

```
{{{ [components.textinput1.value]: 'P' }}}
```

**Comment by ChavanSuyash** [comment]
Thanks, it picks up the value but the query is failing with internal server error.  
<img width="528" alt="image" src="https://user-images.githubusercontent.com/9391301/153800085-4fb020d3-7f82-4c66-808a-e0a8cc9599a6.png">

![Uploading image.png…]()

**Comment by ChavanSuyash** [comment]
Thanks, it picks up the value and shows in UI. But the query is failing with an internal server error, looks like because of date value not being passed correctly.  

<img width="994" alt="image" src="https://user-images.githubusercontent.com/9391301/153800231-a3c61d17-823c-4943-872f-07893dee615a.png">


<img width="520" alt="image" src="https://user-images.githubusercontent.com/9391301/153800262-258d39ea-e713-46f7-aa69-f03bee176a74.png">

**Comment by ChavanSuyash** [comment]
Thanks, it picks up the value and shows in UI. But the query is failing with an internal server error, looks like the body value is not JSON.  

<img width="994" alt="image" src="https://user-images.githubusercontent.com/9391301/153800231-a3c61d17-823c-4943-872f-07893dee615a.png">


<img width="520" alt="image" src="https://user-images.githubusercontent.com/9391301/153800262-258d39ea-e713-46f7-aa69-f03bee176a74.png">

**Comment by Navaneeth-pk** [comment]
Sorry, that look like a bug. We will fix it asap. Meanwhile, please copy and paste the snippet below as a workaround:

```
{{ { [components.textinput1.value]: 'P'  } }}
```

@ChavanSuyash

**Comment by Navaneeth-pk** [comment]
@sherfin94 Please take a look at the bug mentioned above.

**Comment by ChavanSuyash** [comment]
@Navaneeth-pk  I have one more question (**not related to the issue**). For query update data to a spreadsheet, is there any way to pass sheet / gid?

**Comment by arpitnath** [comment]
@ChavanSuyash Hi, you can pass sheet id for the update operation here
<img width="986" alt="Screenshot 2022-02-14 at 11 51 08 AM" src="https://user-images.githubusercontent.com/67645175/153810923-8dec4314-ee45-4927-a7fe-35608037ce5f.png">

**Comment by ChavanSuyash** [comment]
@Navaneeth-pk  this has stopped working. 

> {{ { [components.datepicker1.value] : 'P' } }}

Problem : 
The query runs though the column value is not updating. 

The following works fine

> {{ { '24/02/2022':'P' } }}

**Comment by ChavanSuyash** [comment]
@Navaneeth-pk  the issue is something else, not the mentioned one here. I have raised a new issue for the same. 
https://github.com/ToolJet/ToolJet/issues/2384
