### ISSUE TITLE
Bug: Multiple datasources being shown

### ISSUE THREAD

**Issue by Tam2** [ToolJet/ToolJet#225]
I've created a new application on tooljet cloud, created a single REST API datasource, however when creating a query it shows two datasource options

**Datasources**

![image](https://user-images.githubusercontent.com/1256087/121488812-582fbe00-c9cb-11eb-8a0f-cfb199bf62f9.png)

**Query**
Shows both the Composer API I've created and a REST API isn't configured as a datasource

![image](https://user-images.githubusercontent.com/1256087/121488917-709fd880-c9cb-11eb-90b3-42a45bc2d398.png)

**Comment by Navaneeth-pk** [comment]
@Tam2  It is a UX issue I guess. 

`REST API` is a built-in data source that doesn't need any prior configuration. Think of it as a one-off HTTP request.  If you have to create multiple requests with the same base URL, you can create a new `REST API` data source ( like you created the `Composer API` ), this can include common headers and query parameters.
