### ISSUE TITLE
Hide the scrollbar for documentation portal

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2251]
![image](https://user-images.githubusercontent.com/7828962/153804024-b370b4cd-890e-467c-8aed-3e5798e2e87a.png)

Problem: The scrollbar for the documentation sidebar is always shown.

Solution: Scrollbar can be shown only when the user hovers on the sidebar. Using `overflow-y: overlay;` might be a solution but `docusaurus` might have a config to do this.

**Comment by Girish-Bharadwaj** [comment]
Hello! May I work on this issue?

**Comment by Navaneeth-pk** [comment]
Sure, assigning to you. Thanks for contributing to ToolJet.
@Girish-Bharadwaj
