### ISSUE TITLE
SQL queries generated with Javascript does not work if it is not single-line

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#2255]
### Environment

Enterprise deployment
### What is the expected behaviour?

When a postgresql query is generated based on some condition using javascript, the query body could be single line or multiline
### What is the current behaviour?

When a postgresql query is generated based on some condition using javascript, the query body needs to defined in a single line. Multiline does not work.
### How to reproduce the issue?

1. Add a postgres data query
2. Set its body as : 

> {{1 == 1 ?  
>    'select email from users' : 'select first_name from users'}}

3. Click on preview

### Screenshots or Screencast

<img width="581" alt="image" src="https://user-images.githubusercontent.com/20333972/153866424-bdeb3ee1-7818-474e-a8bb-f2904068fcb3.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/20333972/153866482-d07019fc-2c44-4590-b1f2-8bde3b6c5447.png">

### Any possible solutions?
Update query resolution at backend to support multiple lines

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by arpitnath** [comment]
picking this up
