### ISSUE TITLE
Start 5 of Getting Started Wizard is Cut Off

### ISSUE THREAD

**Issue by jimmybrancaccio** [ToolJet/ToolJet#2258]
### Environment

ToolJet itself is deployed via Docker on my Ubuntu 20.04.x server. I am using Safari on macOS to access the instance. Here's my Safari information:

```
Version 15.2 (17612.3.6.1.6)
```

Of note, I did not test in any other web browsers so this may be an issue limited to Safari.

### What is the expected behaviour?

I expect this UI element to show properly and not be cut off.

### What is the current behaviour?

Currently the UI element is not showing properly and appears to be "cut-off".

### How to reproduce the issue?

1. Setup ToolJet. I don't imagine how it's setup should matter, but I experienced the issue using Docker.
2. Once ToolJet is setup and deployed, visit your instance in your web browser (I am using Safari on macOS so that may make a difference).
3. Sign up for an account, verify it as necessary.
4. One logged in, go through the Getting Started wizard.
5. On Step 5 note that the UI element is cut off - see attached screenshot.

### Screenshots or Screencast

<img width="410" alt="Screen Shot 2022-02-12 at 08 52 17AM" src="https://user-images.githubusercontent.com/405585/153896345-b094f9b7-9a55-44b3-bae8-4ae6a27ab7a1.png">

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions?

It's likely this can be resolved with a bit of CSS.

### Can you identify the location in the driver source code where the problem exists?

Unfortunately I finished up the wizard so it's no longer showing for me and I am not sure how to trigger it to run again (I did ask in Slack so there might be a way - in which case I can perform that action and update this issue).

### If the bug is confirmed, would you be willing to submit a PR?

Yes, I can try.

**Comment by Navaneeth-pk** [comment]
We sue this library for the walkthrough: https://github.com/kamranahmedse/driver.js 

Since you have mentioned that you want to try fixing this, I think we can fix this by changing the position to `left` at `frontend/src/Editor/Editor.jsx:221`. I haven't tried this myself though.

@jimmybrancaccio

**Comment by withshubh** [comment]
Closing this issue as we are currently working on new onboarding UI.
