### ISSUE TITLE
Field of IP Address(es) For White-Listing Is Empty When Adding a MySQL Datasource

### ISSUE THREAD

**Issue by jimmybrancaccio** [ToolJet/ToolJet#2259]
### Environment

ToolJet has been deployed via Docker on my Ubuntu 20.04.x sever. I am access ToolJet from Safari in macOS. My Safari information:

```
Version 15.2 (17612.3.6.1.6)
```

I don't believe this issue is web browser related, but it _could_ be.

### What is the expected behaviour?

I expect something to show up in this field for IP address(es) that should be whitelisted. Either that or don't show the element if there is nothing to white-list.

### What is the current behaviour?

Currently nothing appears in this field.

### How to reproduce the issue?

1. Spin up a new instance of ToolJet.
2. Sign up and verify a new user account.
3. Create a new application.
4. Go to add a new MySQL datasource. Click on the Copy button within the element that says "Please white-list our IP address..." and observe the popup.
5. Observe there's nothing in the field in the popup.

### Screenshots or Screencast

<img width="748" alt="Screen Shot 2022-02-12 at 08 55 53AM" src="https://user-images.githubusercontent.com/405585/153902155-68ed2202-ef69-47d4-85d1-176968036aeb.png">

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions?

Unknown.

### Can you identify the location in the driver source code where the problem exists?

Unknown.

### If the bug is confirmed, would you be willing to submit a PR?

I could try!

**Comment by withshubh** [comment]
Closing this issue as it is fixed.
