### ISSUE TITLE
Bug: Application Launch Errors

### ISSUE THREAD

**Issue by Tam2** [ToolJet/ToolJet#226]
Created a simple application on tooljet cloud, added a simple text box to the application and clicked launch.

Application is launched but empty screen shown with some console errors

```
main.js:202 TypeError: Cannot read property 'components' of undefined
    at xh (main.js:249)
    at Go (main.js:202)
    at Ri (main.js:202)
    at gs (main.js:202)
    at cl (main.js:202)
    at sl (main.js:202)
    at Qs (main.js:202)
    at main.js:202
    at t.unstable_runWithPriority (main.js:210)
    at Ba (main.js:202)
es @ main.js:202
main.js:249 Uncaught (in promise) TypeError: Cannot read property 'components' of undefined
    at xh (main.js:249)
    at Go (main.js:202)
    at Ri (main.js:202)
    at gs (main.js:202)
    at cl (main.js:202)
    at sl (main.js:202)
    at Qs (main.js:202)
    at main.js:202
    at t.unstable_runWithPriority (main.js:210)
    at Ba (main.js:202)
```

**Comment by Navaneeth-pk** [comment]
@Tam2 
I think this is more of a UX issue. 

You have to create a new version -> save the version -> deploy the version. Only then you can launch the app.

**Comment by zachspar** [comment]
When I create a new version, save and deploy on my simple table view, it gives me a 404.

Please see attached screenshots. Not sure if this is related, or if this warrants a new issue @Navaneeth-pk

Step 1: Create new table view
![Screenshot from 2021-06-25 01-57-14](https://user-images.githubusercontent.com/41600414/123376647-d3ab7680-d558-11eb-8c51-d87c5b99aee0.png)

Step 2: Save version and deploy
![Screenshot from 2021-06-25 01-59-49](https://user-images.githubusercontent.com/41600414/123376794-13725e00-d559-11eb-9a6f-2e2bb22f9ec9.png)

Step 3: Receive 404 not found
![Screenshot from 2021-06-25 01-57-22](https://user-images.githubusercontent.com/41600414/123376646-d3ab7680-d558-11eb-9b49-3e153c22b200.png)

**Comment by ashishmax31** [comment]
@zachspar Seems like an issue in our nginx conf.
Open `/usr/local/openresty/nginx/conf/nginx.conf` with `sudo vim /usr/local/openresty/nginx/conf/nginx.conf`
Then, replace line number 61 with  `try_files $uri $uri/ /index.html;`
Once you've made that change restart the webserver with `sudo systemctl restart openresty`.
This should solve this issue.

**Comment by zachspar** [comment]
> Then, replace line number 61 with `try_files $uri $uri/ /index.html;` and save the file.
This fixes the issue. Thanks :)
