### ISSUE TITLE
[docs] Correction in BigQuery data source reference 

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2265]
Page: https://docs.tooljet.com/docs/data-sources/bigquery

![image](https://user-images.githubusercontent.com/7828962/154192718-9df5c75a-0a7f-46a6-b72e-465e9231d11b.png)

This section is displayed on top of the page, it is not needed. Refer https://docs.tooljet.com/docs/data-sources/typesense to check how it is done for other data source reference guides.

**Comment by Aman-Mandal** [comment]
Hey.. can I work on this issue?

**Comment by Navaneeth-pk** [comment]
@Aman-Mandal Sure, assigning to you.
