### ISSUE TITLE
Create a data source plugin for Mailgun

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2268]
Mailgun node SDK: https://github.com/mailgun/mailgun.js

ToolJet command-line tool can be used to bootstrap the plugin. Instruction are given here: https://docs.tooljet.com/docs/contributing-guide/creating-a-plugin

Operations that should be supported: 
a) Create message: https://github.com/mailgun/mailgun.js#messages

**Comment by mslourens** [comment]
I would like to give this story a try, to get to know the plugin system.

**Comment by Navaneeth-pk** [comment]
Thanks! assigned the issue to you. @mslourens
