### ISSUE TITLE
Bug: Table not showing REST query data

### ISSUE THREAD

**Issue by Tam2** [ToolJet/ToolJet#227]
Configured up a query to GET data from https://jsonplaceholder.typicode.com/todos 

Table created to get data from this query - `{{queries.restapi1.data}}`

Would expect `title` key to show the title from the query result, however, the table is empty

![image](https://user-images.githubusercontent.com/1256087/121494416-a1ced780-c9d0-11eb-8325-88e40ad2e708.png)

![image](https://user-images.githubusercontent.com/1256087/121494480-b01cf380-c9d0-11eb-9595-e1aaa11060ee.png)

**Comment by Navaneeth-pk** [comment]
@Tam2 

Can you please check the query result by using the state inspector on the left side of the editor? Once a query is created, you need to set a trigger to run the query, for example, you can run the query on page load by navigating to the `advanced` section of the query pane and enabling `run on page load`. 

If you want to manually trigger a query while you are in the editor, you can use the `run` button next to the name of the query.

**Comment by Tam2** [comment]
@Navaneeth-pk  - I've got a button hooked up to run the query, in my screenshot you can see it shows Search: 200 records so the data is being pulled from the API, also we can see this

![image](https://user-images.githubusercontent.com/1256087/121664222-2a1bae00-ca9f-11eb-8919-4f86965211f8.png)

For some reason the data itself isn't being output on the table

**Comment by Navaneeth-pk** [comment]
@Tam2 Can you please check if there are any errors on the console? Haven't seen this bug before.

**Comment by Tam2** [comment]
No errors after running the query, this is the console log

![image](https://user-images.githubusercontent.com/1256087/121668204-f9d60e80-caa2-11eb-8b9c-3bb1737575d8.png)

However, there are a few errors when first launching into the editor

![image](https://user-images.githubusercontent.com/1256087/121668323-17a37380-caa3-11eb-9edc-3b3a169f6e6e.png)

**Comment by Navaneeth-pk** [comment]
Sorry to trouble you more, but would it be possible to share the screenshot of the entire editor ( please hide the API endpoint and other data ). I am not able to reproduce this issue at my end.

**Comment by Tam2** [comment]
Sure, i'm using a public API to test this anyway so you should be able to replicate

1. Create a REST GET query with this URL - https://jsonplaceholder.typicode.com/todos
2. Create a table and set table data to `{{queries.restapi1.data}}`
3. Try and map the columns as above

![image](https://user-images.githubusercontent.com/1256087/121701575-f35a8d80-cac8-11eb-9fd0-8c84d7456077.png)

**Comment by Navaneeth-pk** [comment]
I was not able to reproduce the issue. I recorded a video here: https://www.loom.com/share/4e9cc149666d49bf93a3f34ebd74fcbb

Can you please make sure all the steps were followed? 

@Tam2
