### ISSUE TITLE
Creator name and creation time is not visible in dark mode

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2274]
On ToolJet dashboard, for every application listed, the name of creator and the creation time is not readable in dark mode. The font color should be lighter.

![image](https://user-images.githubusercontent.com/7828962/154423070-eb51410a-5d92-467b-9d58-3f31ab63dc13.png)

**Comment by abhinabaadhikari** [comment]
Hi @Navaneeth-pk, can you please assign this to me?

**Comment by Navaneeth-pk** [comment]
Assigned to you, thanks for contributing ( again ) :) 
@abhinabaadhikari
