### ISSUE TITLE
Loader color option for button

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#2279]
### Is your proposal related to a problem?

Presently, there is no way to set the color of the loader icon on the button widget. If we set the button color to white, for example, the loader would be invisible.
### Describe the solution you'd like

Add a style that sets the loader color of Button widget.

**Comment by nitin094-hub** [comment]
Could you plz assign this task to me?

**Comment by sherfin94** [comment]
@nitin094-hub , assigned to you. Thank you for contributing!

**Comment by abhinabaadhikari** [comment]
Hi, could this be assigned to me?

**Comment by sherfin94** [comment]
@nitin094-hub Since you unassigned yourself, assigning issue to @abhinabaadhikari. 

Thanks @abhinabaadhikari and @nitin094-hub.
