### ISSUE TITLE
Bug: One click Heroku deployment fails with Heroku Enterprise accounts

### ISSUE THREAD

**Issue by nickramsbottom** [ToolJet/ToolJet#228]
I have just tried deploying using one click on a Heroku Enterprise account and received this error:

> error resizing dynos: Heroku Enterprise accounts only support professional and private dynos.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/21983479/121497931-d6905e00-c9d3-11eb-81b7-1d4dce193035.png">

**Comment by nickramsbottom** [comment]
My solution for this was to change [this line](https://github.com/ToolJet/ToolJet/blob/94e44a6fb172593623b25dcab2fe9b24e2a4ecf4/app.json#L40) in `app.json` to `standard-1x`.

**Comment by Navaneeth-pk** [comment]
@nickramsbottom 

Thanks for reporting this issue.

"Every Heroku account is allocated a pool of free dyno hours, which can be used by Personal apps - apps that are not part of a Heroku Team or Enterprise Team." - https://devcenter.heroku.com/articles/free-dyno-hours

Heroku enterprise accounts cannot create free dynos. I did not know about this and the default dyno-typo in `app.json` is the free dyno. Let me try to figure out how to fall back to other dyno types or at least show a meaningful error. Also adding this to the documentation.

**Comment by soorajshankar** [comment]
@nickramsbottom could you try deploying with the following link? 
https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fsoorajshankar%2Ftooljet%2Ftree%2Fheroku-remove-FREE-tier-enforcement-to-support-enterprise-installs 

I created a [PR](https://github.com/ToolJet/ToolJet/pull/231) for the same.

**Comment by nickramsbottom** [comment]
@soorajshankar sure, I'm not working until next week so I'll have a look on Monday. Thanks! 🚀

**Comment by nickramsbottom** [comment]
I just tried this out and it works, thank you!
