### ISSUE TITLE
Feature: Pages

### ISSUE THREAD

**Issue by Tam2** [ToolJet/ToolJet#229]
I can't see an option to create different pages/screens within the application?

**Comment by Navaneeth-pk** [comment]
Multiple pages/screens are not yet supported yet. We are planning to build support for multi-page apps and a `tabs` widget. Will update this issue when we have more information. Thanks!

**Comment by febinsathar** [comment]
Any plan to add support for this?

**Comment by osevenlan** [comment]
Any progress on pages?

**Comment by venomouse** [comment]
Adding my vote to pages :-) This would be such a gamechanger for us. Having several applications that are basically one application is so messy.

**Comment by shivangT** [comment]
Hey @venomouse , @osevenlan 

I’m sure about that. We too have been waiting for this feature eagerly. Our internal team in already looking into it. We’ll be rolling it out soon. Stay connected to get the updates.

Thanks

**Comment by andreasbhansen** [comment]
> Hey @venomouse , @osevenlan
> 
> I’m sure about that. We too have been waiting for this feature eagerly. Our internal team in already looking into it. We’ll be rolling it out soon. Stay connected to get the updates.
> 
> Thanks

Hi Shivang,

Thanks for looking into this. 
Do you have any updates to share on the implementation of pages?

**Comment by withshubh** [comment]
Hey everyone 👋 

**Update**: The multi-page app feature is under development and we will share an update once it is released.

**Comment by shubh22** [comment]
Hi,

This feature is available in ToolJet 2.0 onwards. Please check it out.
