### ISSUE TITLE
[docs] incorrect formatting of docker deployment guide

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2297]
Page: https://docs.tooljet.com/docs/deployment/docker
Issue: The tips/info sections are not properly formatted. 

![image](https://user-images.githubusercontent.com/7828962/154827516-39b91e50-9107-40ad-b248-246b19aa87da.png)

**Comment by eyuelberga** [comment]
Hi, I would like to take on this issue
