### ISSUE TITLE
Modal won't reappear after closing it with ESC

### ISSUE THREAD

**Issue by Robintago** [ToolJet/ToolJet#2300]
### Environment

    ToolJet Cloud: editor & running app.

### What is the expected behaviour?

The modal should show up again once triggered by an action, even after having closed it through ESC.

### What is the current behaviour?

If I close a modal with ESC in the editor and try to display it again by clicking on an action-bound button, the modal won't display again.

**Comment by arpitnath** [comment]
picking this up
