### ISSUE TITLE
Scrollbars in Container widgets

### ISSUE THREAD

**Issue by Robintago** [ToolJet/ToolJet#2301]
### Is your proposal related to a problem?

It seems sensable to make container widgets scrollable. Use-case: I want to use a modal to fill in a form. But the form will be very limited without the ability to scroll through a container.

### Describe the solution you'd like

It would be nice if the Widget-area in a Container is infinitely expandable downwards. That makes it possible to display more information, e.g. in modals, or handle overflow.

### Describe alternatives you've considered

 I can use pagination or tabs, but that's a cumbersome work-around.

### If the feature is approved, would you be willing to submit a PR?

I'm not a programmer by trade, I'm sorry. But I'm trying to help by giving feedback on usability and doing bug reports.

**Comment by withshubh** [comment]
Duplicate - https://github.com/ToolJet/ToolJet/issues/2308
