### ISSUE TITLE
Text widget doesn't align with text input widget 

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#233]
### Environment

Any

### What is the expected behavior?

Text widget should align with text input widget 

### What is the current behavior?

![image](https://user-images.githubusercontent.com/7828962/121698404-97553080-caeb-11eb-8888-8c5c03281d22.png)

### How to reproduce the issue?

Drag and drop a text input widget 
Drag and drop a text widget to the left of the text input ( like a label for the input field ) 

### Screenshots or Screencast

Refer current behavior section

**Comment by prasadwalvekar** [comment]
Picking this up.
