### ISSUE TITLE
Popout code editor closes when clicking in the middle of the editor

### ISSUE THREAD

**Issue by mslourens** [ToolJet/ToolJet#2334]
### Version Information
develop branch

### Environment
Build: Local build
OS: MacOS 12.1
Browser: Vivaldi

### What is the expected behaviour?
The popout code editor closes when you click below the first line (with the placeholder)

### What is the current behaviour?
Only clicking outside the popout should the code editor close.

### How to reproduce the issue?

1. Add a new table to the page
2. Select the table and click `add column`
3. Toggle the `make editable` to true
4. Click on the popout button on one of the validation fields
5. The code editor popout is visible
6. Click below the first line (notice the cursor changing from `text` to `default`)
7. The popout closes, although you didn't click outside the popout.

### Screenshots or Screencast

https://user-images.githubusercontent.com/1907152/155361809-6f6df7ec-63c0-4615-b29f-384d0ddc3e5c.mov

### Any possible solutions?
Not yet

### Can you identify the location in the driver source code where the problem exists?
Portal.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by sherfin94** [comment]
Hey @mslourens , since you mentioned that you're willing to submit PR, assigning you. Thank you for contributing!

**Comment by withshubh** [comment]
Hey @mslourens 
Are you working on this issue?

**Comment by mslourens** [comment]
No, I haven't found the time yet, so you can pick it up, if you like.

**Comment by geisterfurz007** [comment]
Mind if I have a shot at this?

**Comment by withshubh** [comment]
Sure @geisterfurz007 ! Assigned the issue to you.
