### ISSUE TITLE
Run Rubocop on rails tests

### ISSUE THREAD

**Issue by JibranKalia** [ToolJet/ToolJet#234]
### What is the expected behavior?
Have tests also pass Rubocop rules

### What is the current behavior?
Currently, the rest of the Ruby code is correct according to the `.rubocop.yml`. Only tests don't pass.
Maybe it might be worth adding tooling with Github Actions to ensure that code merged to main doesn't have any rubocop errors.

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by deepti-kakade** [comment]
Picking up this.
