### ISSUE TITLE
Queries with hyphen in the name do not work in a table widget 

### ISSUE THREAD

**Issue by roarwrecker** [ToolJet/ToolJet#2343]
### Version Information
Docker container image IDs
tooljet/tooljet-client-ce    latest    c5b0c44c998a
tooljet/tooljet-server-ce   latest    1d38b7ff644d

### Environment
Docker

### What is the expected behaviour?
Option 1: Do not accept query names with hyphens and show an error or similar.
Option 2: Fix access to queries with hyphens in the name.

### What is the current behaviour?
You can create a query with a hyphen in the name. However, referencing the query in a table widget does not work

### How to reproduce the issue?

1. Create a query with a hyphen in the name. e.g. "get-users"
2. Create a table widget
3. Change "Table data" of widget to "{{queries.get-users.data}}"
4. This will lead to the error "ReferenceError: users is not defined"

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/2168384/155588872-7aaac27d-39ac-4466-b358-59bd5b37cc48.png)

**Comment by Navaneeth-pk** [comment]
Thanks for reporting this bug. As a workaround, you can use `{{queries['get-users'].data}}` instead. 
@roarwrecker
