### ISSUE TITLE
Unable to connect to postgres hosted by supabase

### ISSUE THREAD

**Issue by liweihan** [ToolJet/ToolJet#2353]
### Version Information
ToolJet Cloud TOT

While connecting to a postgres hosted by supabase, Im getting this error and the connection test failed:
unsupported startup parameter: statement_timeout

**Comment by sherfin94** [comment]
Hey @liweihan , we're looking into this, will update as soon as we've more info.

**Comment by akshaysasidrn** [comment]
@liweihan Could you share which postgres version is being used? Could be due to some version incompatibilities.

**Comment by blocka** [comment]
I'm having the same issue with supabase

```
PostgreSQL 14.1 on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, 64-bit
```

**Comment by gsmithun4** [comment]
@blocka @liweihan I am able to connect to the same. Created [Supabase cloud account](https://app.supabase.io/) and tested.
Can you please confirm whether you are using cloud or self hosted?

**Comment by blocka** [comment]
it works for me now
