### ISSUE TITLE
Docs website causes infinite re-directs

### ISSUE THREAD

**Issue by mdgozza** [ToolJet/ToolJet#2382]
When navigating to 
https://docs.tooljet.com/docs/data-sources/docs/intro

I am infinitely re-directed to new urls. Each new url adds a new `/docs/` to the path prior to path ending `/intro`

I found this url when clicking the docs link in the rest api modal
<img width="733" alt="image" src="https://user-images.githubusercontent.com/9098106/156071644-d4b72f42-371c-4194-b5b3-d64dc9095b5a.png">

**Comment by withshubh** [comment]
Hey @mdgozza Thanks! for creating the issue. 👍 

Currently, the docs on the **REST API** data source modal is redirecting to `https://docs.tooljet.io/docs/data-sources/restapi`
But the correct link to the **REST API** docs is `https://docs.tooljet.com/docs/data-sources/rest-api`

So, a very easy solution that I'd suggest for this is to rename the file from `rest-api.md` to `restapi.md`. This will fix this issue.
