### ISSUE TITLE
Provide Integration with RethinkDB

### ISSUE THREAD

**Issue by ivishalgandhi** [ToolJet/ToolJet#2383]
### Is your proposal related to a problem?

RethinkDB is great for real-time web development use cases where the application is not continuously polling for records. RethinkDB will be a great addition to existing integrations ToolJet already has. 

### Describe the solution you'd like

Provide integration with RethinkDB, similar to other data sources supported by ToolJet 

### Describe alternatives you've considered

None. 

### If the feature is approved, would you be willing to submit a PR?
Yes.

**Comment by sherfin94** [comment]
Hi @ivishalgandhi , since you expressed that you're willing to submit a PR, assigning the issue to you. Thank you contributing to ToolJet! ❤️

**Comment by ivishalgandhi** [comment]
@sherfin94 Thank you. I am new to development. Would you be able to guide me on where and how to get started with some of the existing integrations within the source code, would help me easier navigate the code and review this ?

**Comment by sherfin94** [comment]
Hey @ivishalgandhi , this has become an issue of urgent priority now. We have to hand it over to an in-house developer to quickly get it delivered. With your permission I'm handing it over to @stepinfwd 

Feel free to take up any other issue that is marked as `Good first issue` or `up-for-grabs`

**Comment by Navaneeth-pk** [comment]
Closing this issue as there is a duplicate issue here: https://github.com/ToolJet/ToolJet/issues/2383.
PR for the Rethinkdb plugin is ready and is being tested (https://github.com/ToolJet/ToolJet/pull/2724). @ivishalgandhi
