### ISSUE TITLE
[GoogleSheets as DataSource] Query - Update data to a spreadsheet, not working on extra added columns(ex. AA). 

### ISSUE THREAD

**Issue by ChavanSuyash** [ToolJet/ToolJet#2384]
### Environment
ToolJet Cloud

### What is the expected behaviour?
I am creating one small attendance tracker app with sheets as a data source. Till column Z `update data to a spreadsheet` query is working fine. But when I add extra columns ex. AA `update data to a spreadsheet` is not updating those columns though query runs successfully without any errors. 
Expected - extra added columns(ex. AA) values should also be updated via `update data to a spreadsheet` query.

### What is the current behaviour?
Extra added columns(ex. AA) values are not updated via `update data to a spreadsheet` query, but query runs successfully without any error. 

### How to reproduce the issue?

1. Create an excel sheet and add a new column AA. Give a simple name to the column.
2. Write a simple `update data to a spreadsheet` and check the behavior. 
3. Observe query runs successfully but value is not updated. 

### Screenshots or Screencast
<img width="309" alt="image" src="https://user-images.githubusercontent.com/9391301/156138340-a780f02d-6b28-4643-94ab-6fd7939c3e18.png">

**Comment by sherfin94** [comment]
@ChavanSuyash Closing this issue as @arpitnath 's PR fixes it!
