### ISSUE TITLE
[docs] center align the images in SSO- Google

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2401]
### Is your proposal related to a problem?

- The images are not center-aligned in the docs of [Google SSO](https://docs.tooljet.com/docs/sso/google). 
- There are unnecessary `<br>` tags after images.

### Describe the solution you'd like

- Remove unnecessary `<br>` tags 
- Use markdown (syntax below) instead of HTML <img> tags to center-align the images:

``` mdx
<div style={{textAlign: 'center'}}>

   ![ToolJet - SSO - Google](/img/sso/google/create-project.png)

</div>
```
File path: `docs/sso/google.md`

**Comment by AnmolBansalDEV** [comment]
Please assign this issue to me

**Comment by withshubh** [comment]
Hey @AnmolBansalDEV 👋 
 @mslourens has already created a PR for this issue so assigning it to him. Please pick any other issue.
