### ISSUE TITLE
QR Scanner Ondectec firing even without QR

### ISSUE THREAD

**Issue by watollop** [ToolJet/ToolJet#2422]
### Version Information
Latest
### Environment

    Docker

### What is the expected behaviour?
  When using the QR only fires the when it detects a valid QR

### What is the current behaviour?

  Is firing even with no QR at all

### How to reproduce the issue?

1. Select the QR widget
2. Fire and ondetect event
3.

### Screenshots or Screencast
<img width="1119" alt="Captura de pantalla 2022-03-03 a las 14 13 20" src="https://user-images.githubusercontent.com/10385633/156583530-f827de18-47f5-4e1e-91e0-ec66c1c6196e.png">

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by watollop** [comment]
Fix should be pretty easy:
`if (data) `instead of  `if (data !== null || data !== undefined) {`

As this condition is not restrictive right now

!!null is always false and !!undefined is always false so, `if(data)` should do the job

**Comment by sherfin94** [comment]
Thanks @watollop, assigning you.
