### ISSUE TITLE
Increase the width of search field when focused

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2428]
The width of the search field on the dashboard should be increased by 50% when a user clicks inside the field. 

Screenshot:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/7828962/156707303-ddbafbcc-969c-448a-9936-305e895f4f52.png">

**Comment by AnmolBansalDEV** [comment]
can you please assign this issue to me?

**Comment by Navaneeth-pk** [comment]
thanks for contributing to ToolJet, assigned the issue to you.
@AnmolBansalDEV

**Comment by AnmolBansalDEV** [comment]
thank you, what name should I give to the branch solving this issue?

**Comment by Navaneeth-pk** [comment]
No conventions for branch name, you can choose something that’s convenient for you.

**Comment by AnmolBansalDEV** [comment]
okay, I'm unable to find the code location in the codebase, can you tell me where to look for it? this is my first time contributing to opensource.

**Comment by arpitnath** [comment]
Hi @AnmolBansalDEV 
you can find the component's location here : `frontend/src/_components/SearchBox.jsx`

**Comment by PiperGuy** [comment]
Hi Team. If it's still up for grab. can I pick this up?

**Comment by arpitnath** [comment]
@AnmolBansalDEV  are you still working on it?

**Comment by AnmolBansalDEV** [comment]
I tried to do it, but I couldn't. Sorry 😞

**Comment by PiperGuy** [comment]
@arpitnath please assign it to me. I will work on this
