### ISSUE TITLE
Smaller screens: components of app card on home page wiggles when hovered

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#2429]
### Environment

ToolJet Cloud
### What is the expected behaviour?

When the app cards on homepage are hovered, the labels and icon inside the card should stay steady.
### What is the current behaviour?

On smaller screens, when the app cards on homepage are hovered, the labels and icon inside the card wiggles.
### How to reproduce the issue?

1. Open ToolJet in a small screen or zoom in on a regular screen
2. Hover over the app cards

### Screenshots or Screencast

https://user-images.githubusercontent.com/20333972/156708691-3d12c5b1-c81f-430e-91f9-90ae63c95ca3.mov

### Can you identify the location in the driver source code where the problem exists?
Probably `frontend/src/HomePage/AppCard.jsx`

**Comment by Aniket-508** [comment]
Can you please assign me this issue? @sherfin94 @arpitnath

**Comment by arpitnath** [comment]
Hi @Aniket-508 
assigning the issue to you.
