### ISSUE TITLE
Unable to create a new plugin with the CI on MacOS

### ISSUE THREAD

**Issue by mslourens** [ToolJet/ToolJet#2432]
### Environment
MacOS 12.2.1
Node.js 14.17.3
Npm 7.24.2

### What is the expected behaviour?
It should create the startup project for developing a plugin

### What is the current behaviour?
An error is thrown: `ModuleLoadError: [MODULE_NOT_FOUND] require failed to load`

### How to reproduce the issue?

1. run `tooljet plugin create <PLUGIN_NAME>`
2. an error is thrown: `ModuleLoadError: [MODULE_NOT_FOUND] require failed to load. /lib/node_modules/@tooljet/cli/dist/commands/plugin/create.js`

**Note:** this is also happening on Windows 11 but NOT happening on Linux (PopOS 22.04) 

### Please provide any traces or logs that could help here.
not applicable

### Any possible solutions?
No

### Can you identify the location in the driver source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by atsuhiro** [comment]
I think this change is needed. oclif/core broke that link in the build.
[cli/node_modules/@oclif/core/lib/cli-ux/prompt.js](https://github.com/oclif/core/compare/v1.2.1...v1.3.0#diff-6a05e5a49420fd6af26d8afcb2395672f997a06678e70c50b61e5c27ec9cd4a6)

I suggest that the version of oclif/core be specified in detail.
https://github.com/ToolJet/ToolJet/blob/124f94ca6bcb557a508f1bba6beba58292b6fc41/cli/package.json#L10

I have temporarily changed the file in node_modules.
