### ISSUE TITLE
Increment `Spreadsheet ID` input field width of Google sheet query (plugin)

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#2435]
### Description
**Spreadsheet ID**  input field should be 100% of the parent container.

<img width="1034" alt="Screenshot 2022-03-04 at 5 44 29 PM" src="https://user-images.githubusercontent.com/67645175/156764710-ed67dde5-c42b-4d38-a7fd-5fce6321745a.png">

### Any possible solutions?
File: `plugins/packages/googlesheets/lib/operations.json`
Removing `width` from the schema for the **spreadsheet_id**

**Comment by meAnushree** [comment]
Can I do this?

**Comment by arpitnath** [comment]
Hi @meAnushree
Assigning the issue to you.

**Comment by meAnushree** [comment]
@arpitnath 
Done.

**Comment by meAnushree** [comment]
Hey @arpitnath 
Can You check this!
