### ISSUE TITLE
Influxdb integration (support w/ Flux)

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2441]
### Discussed in https://github.com/ToolJet/ToolJet/discussions/2437

<div type='discussions-op-text'>

<sup>Originally posted by **danmx** March  6, 2022</sup>
It would nice to see Influxdb integration with support of Flux query.</div>

**Comment by withshubh** [comment]
Hey @danmx - please keep an eye on this issue for updates on InfluxDB integration.

**Comment by Navaneeth-pk** [comment]
Closing as there is a more detailed issue here: https://github.com/ToolJet/ToolJet/issues/2564
