### ISSUE TITLE
Hide query panel tabs if a data source is not selected. 

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2451]
<img width="887" alt="image" src="https://user-images.githubusercontent.com/7828962/157166127-02ab297a-f4cf-4283-9aa3-8e7046b38a5e.png">
The `General` and `Advanced` texts can be hidden if data source is not selected. Similar to how the preview and save buttons are hidden.

**Comment by PiperGuy** [comment]
Hi Tooljet team, If this is available can I pick this up?

**Comment by Navaneeth-pk** [comment]
Sure, assigned to you.
@PiperGuy

**Comment by PiperGuy** [comment]
@Navaneeth-pk We can't hide General Tab because the Datasource option is under the General tab. I can Disable Advance Tab.. Does that work

**Comment by Navaneeth-pk** [comment]
I think it will be possible to hide both the tab headers. @PiperGuy 
@arpitnath can you please help with this issue?

**Comment by PiperGuy** [comment]
There is another bug. Once data source is selected and user switch to advance tab and return to general tab the data source state is lost. Is it the ideal way of working?

**Comment by Navaneeth-pk** [comment]
It will be fixed as part of an upcoming rework of the query panel.
@PiperGuy

**Comment by arpitnath** [comment]
> @Navaneeth-pk We can't hide General Tab because the Datasource option is under the General tab. I can Disable Advance Tab.. Does that work

Hi @PiperGuy. Currently, even if no data source is selected from the dropdown the **General** and **Advanced** tabs
Refer:
<img width="1386" alt="Screenshot 2022-03-10 at 5 58 35 PM" src="https://user-images.githubusercontent.com/67645175/157662095-61fc264d-7376-456d-8d75-b810434d60d2.png">
 are available, which can be hidden for adding a new query.
