### ISSUE TITLE
Loading state is not shown while submitting password reset form

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2478]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/7828962/157594711-efaa05dc-df86-4c9f-90e9-22ba5169a895.png">

On the page given above, when the user clicks on the submit button, the button should go to loading state.

**Comment by Olaleye-Blessing** [comment]
Can I work on this?

**Comment by Navaneeth-pk** [comment]
Definitely! Assigned the issue to you. @Olaleye-Blessing
