### ISSUE TITLE
Import/Export/Clone is slow or fails for big apps

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#2483]
### Environment

Enterprise deployment
### What is the expected behaviour?

When heavy apps with several versions are imported, exported or cloned, it should still complete within a reasonable amount of time.
### What is the current behaviour?

When heavy apps with several versions are imported, exported or cloned, it does not complete within a reasonable amount of time, or fails.
### How to reproduce the issue?

1. Create an app with several queries and components
2. Export it
3. Import it
4. Or clone it

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by victorabarros** [comment]
Hi @sherfin94 and @arpitnath 

I'm having the same problem.

the original app:
![image](https://user-images.githubusercontent.com/42843223/176281938-df83aba3-3be4-413e-8ee5-ecdbb36016a1.png)

after export and import in another environment is missing 2 data sources, 3 queries, and the tab names.:
![image](https://user-images.githubusercontent.com/42843223/176282821-9cd7eccf-c57a-4553-b4cf-75dd941fe33f.png)

**Comment by victorabarros** [comment]
The same is happend when trying to clone.

**Comment by arpitnath** [comment]
Hi @victorabarros.
It would be easier to resolve your issue if you can share it in our slack community.
Someone from the team or from the community can help you out.
[ToolJet Slack Community](https://tooljet.slack.com/ssb/redirect#/shared-invite/email)
Thanks 😅
