### ISSUE TITLE
Allow non-alphabetic characters in display names

### ISSUE THREAD

**Issue by brentschroeter** [ToolJet/ToolJet#2494]
### Is your proposal related to a problem?

Currently first/last names are validated against the regex `^[a-zA-Z]+$`, which is overly restrictive. In particular, members of our team have names that contain spaces, dashes, and/or diacritics. See: [Falsehoods Programmers Believe About Names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/).

### Describe the solution you'd like

Small Change: Updating the regex to `^[a-zA-Z -]+$` significantly expands the range of names that can be accurately represented.

Moderate Change: Updating the regex to `^[a-zA-Z0-9<XXX> -]+$`, where `<XXX>` = `àáâäæãåāÀÁÂÄÆÃÅĀçćčÇĆČ`..., allows a larger portion of Latin-character names to be accurately represented.

Easiest, but Most Significant Change: Remove first/last name validation, or at least the regex test. This solution must be carefully considered to ensure that it does not introduce security risks. However, it would be the most complete (short of changing the "first+last name" formula) in terms of representing names written with, for example, characters outside of the Latin alphabet.

### Describe alternatives you've considered

See above for multiple proposed solutions. This issue does not impede or enhance core functionality, so users can continue to work around it by altering their names to conform with the validation as currently implemented. In my view, this is primarily an issue of cultural/personal sensitivity.

### If the feature is approved, would you be willing to submit a PR?

Yes.

**Comment by akshaysasidrn** [comment]
@brentschroeter, thanks for sharing the post. Makes sense not to restrict with regex. I think we can make use of moderate change now. Then once we have handled for html/sql injection throughout the app (which is to be worked on), can remove the regex check altogether.

**Comment by brentschroeter** [comment]
@akshaysasidrn Thanks for taking a look! Sounds good. I'll whip up the full regex for the "moderate" version and open a PR in the next couple of days.

**Comment by withshubh** [comment]
Hey @brentschroeter 👋 
Please let me know if you're working on this issue.

**Comment by brentschroeter** [comment]
@withshubh Thanks for the ping! While I was working on this I noticed that this validation is only implemented client-side, which makes it rather ineffectual as far as XSS or SQL injection are concerned. With that in mind, should we follow the path @akshaysasidrn mentions above and remove the regex check altogether? Sorry I got side-tracked while puzzling through the implications and forgot to close the loop here.

If users with the `inviteUser` ability are untrusted and there's concern that pages, emails, the database, etc. might be susceptible to improper inputs, then this is probably worthy of a separate security-focused ticket.

**Comment by akshaysasidrn** [comment]
We had already added sanitization at the backend as a part of this [PR](https://github.com/ToolJet/ToolJet/pull/2694/files#diff-e91f14bcc679fb3026f3f29bdc4f74c9c616bdebedfcf2ee6036f5ad81e7362d).
Think it's fine now to keep a moderated check.

**Comment by akshaysasidrn** [comment]
Agree. That makes sense now. We can remove the validation.
