### ISSUE TITLE
Trigger queries with Javascript

### ISSUE THREAD

**Issue by rafferty-m** [ToolJet/ToolJet#2525]
### Not being able to trigger queries with javascript is very limiting - it puts a low ceiling on what can be accomplished within Tooljet

It's useful that queries can accept dynamic parameters - but it's only useful to a point if you can only trigger those queries from components or, upon completion of another query. And it's also only useful to a point if you can't pass parameters to those queries at the time they're called. 

Picture a scenario where you need to make API calls in a loop, or make specific calls based off of some conditional logic. Maybe you need to make an call to the Google Sheets API for every row in a table. Or, 
 further, maybe you need to make several chains of API calls for each row in the table. Without a way to control queries with javascript, this isn't currently possible.

### Proposed Solution

Queries have an available method, called .call() or .execute() or .run() that accepts parameters, and returns a promise, which, when resolves, returns the result of that query. 

This method can be invoked from two places:

1.) Within a the javascript query editor, you can invoke any of your existing queries. For a very simple case, imagine you have an API accepts updates for one update at a time. You have a table where you have made multiple updates. As a part of your workflow, you can write a JS query that runs on submit that does:
```
const makeUpdatesToAPIFromTableEdits = async () => {

    for(var i = 0; i < table.rows.length; i++){

        // execute another tooljet query
        await toolJetQueryThatCallsAPI.execute(

             // a JSON array with paramters to pass to the tooljet query as variables.  
             // Here, the tooljet query is expecting "id".
             {id: table.data[i].itemId} 

      ).then((result) => // do something with result... )
    }
}
makeUpdatesToAPIFromTableEdits()
```

2.) In a custom event handler.

When setting an onclick event for the button, the user can choose to execute the JS query printnumber, and pass in the named parameter myNumber, which will be available to the function at runtime.

<img width="868" alt="brave_qNxFdbyJjy" src="https://user-images.githubusercontent.com/101658801/158471036-bec95535-d572-4bee-b165-5d3257da96b0.png">

### Some workarounds

For some, very simple workflows , you can try to chain queries, using tooljet's native functionalit to add event handlers to various queries to execute other queries within them. You could do some gymnastics using localstorage to simulate passing variables between the queries, but it'd be messy and difficult, and there'd still be no way to do loops!

### If the feature is approved, would you be willing to submit a PR?
I don't think I have the skills to make this happen, but I am happy to help with concepts and/or documentation.

**Comment by rafferty-m** [comment]
Hi there - any updates on this? I know it'd been on the April Roadmap.. Or are there other workarounds that folks are using? I can't seem to be able to do any more than the absolute simplest workflows without this feature.

**Comment by withshubh** [comment]
Hey @rafferty-m 
Apology for the delay in response. We had to delay this feature due to some reasons and move it to a later time in the roadmap. We will deliver this feature soon for sure and will update here.

**Comment by withshubh** [comment]
Hey @rafferty-m 👋 
Our [latest release](https://github.com/ToolJet/ToolJet/releases/tag/v1.21.0) includes the **feature to trigger any action from the JavaScript code**. 🎉 This includes triggering queries with JavaScript as well. Try it out and let us know. :)

**Comment by withshubh** [comment]
Released in :
- https://github.com/ToolJet/ToolJet/issues/3114
- https://github.com/ToolJet/ToolJet/issues/3420
