### ISSUE TITLE
Ability to set default variables

### ISSUE THREAD

**Issue by rafferty-m** [ToolJet/ToolJet#2526]
### Right now, variables can only be set through event handlers. 

There's no clear way to set variables in the app except through component event handlers. There are many types of variables it'd be useful to have available on page load, whether it's app parameters, different text strings for messages, etc. etc.

### Describe the solution you'd like

It would be nice if it were possible to open the inspector and set default values for variables. This could be effectively done by allowing the user to input key value pairs. These would be available to queries including ones that run on page load.

![image](https://user-images.githubusercontent.com/101658801/158471913-c26ac812-2f40-46dd-9872-e2feec0a3381.png)

### Describe alternatives you've considered

Having a JS query that runs on page load that sets variables in local storage. The disadvantage of this is that using the local storage API is not as user friendly as using native components within the app/UI, especially considering the low-code userbase. It also means that no other queries can be set to run on page load if they rely on these variables.

### If the feature is approved, would you be willing to submit a PR?
Happy to help with concepts and/or documentation.

**Comment by sherfin94** [comment]
Hey @rafferty-m , there is a simple workaround for this, you can create an empty runjs query that just has some code like `return {}`.

On the advanced tab on the runjs query, you have the `On success` handler, where you can use the `Set variable` action to initialize any variable you wish to.

Closing this issue for the time being, as we are exploring other architectural solutions for the problem being expressed.

**Comment by rafferty-m** [comment]
Hey @sherfin94, thanks for the message. To me this doesn't really seem like a workaround because with what you described, there's no way to:

do something --> set a variable --> do something with that variable

Unless I'm missing something?

**Comment by sherfin94** [comment]
@rafferty-m , my workaround is to specifically address the issue of setting variables on app load, as you described on the issue.

The query I suggested you to create can be set to run on app load, thereby making the variables set by the on success handler of that query available on app load.

Nevertheless, running all actions from runjs will be introduced in the near future, and this includes the action to set variables of course.

If you could explain the specifics of your usecase, perhaps I could try to come up with some workaround for the time being?

**Comment by exetico** [comment]
@sherfin94  I ran into the same use. Having a "status" message, which defaults to "Welcome", but would update after a specific action. So I'm trying to define "defaultMsgString" as a variable, and showing that in a text-element.

**Comment by rafferty-m** [comment]
I'm sorry for the late response @sherfin94! I think that my earlier response wasn't clear at all. 

I think your workaround can work in some cases, but it does kind of make it so you can't really use the "Run Query on Page Load" for anything that would rely on those variables. Of course, you can have the variable-setting query to run those other queries, but it is a loss of functionality, unless I'm missing something.

**Comment by sherfin94** [comment]
@exetico Sorry for the late response, missed your comment

@rafferty-m Yes, with the workaround you will have to have the variable setting query run other queries which wants to use those variables.

So, in any case, it looks like we'll need to introduce some kind of feature to make it easily doable. Let me discuss with the rest of the team for a solution, and shall update here.
