### ISSUE TITLE
Add dnd test cases 

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2530]
### Is your proposal related to a problem?
Currently the drag and drop feature is missing test cases

### Describe the solution you'd like
Add test cases for drag and drop 

Can refer for test cases [here](https://github.com/react-dnd/react-dnd/blob/main/packages/examples/src/00-chessboard/__tests__/chess-integration.spec.tsx)

**Comment by Rafajrg21** [comment]
Hi, is this still needed? I would like to work on this issue 🌞 this would help me familiarize with the code
