### ISSUE TITLE
Bugfix :: Delete button in app version manager dropdown not center aligned

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#2533]
### What is the expected behaviour?
Delete button to be center aligned.

### What is the current behaviour?
Left margin is more than right (not center aligned).

### How to reproduce the issue?

1.Create a new app.
2.Open App version on top right section.
3.Hover on dropdown version.

### Screenshots or Screencast
<img width="780" alt="Screenshot 2022-03-16 at 1 17 27 PM" src="https://user-images.githubusercontent.com/31006028/158542655-1eb9dd54-5c5c-4301-9ecd-19cdac390e46.png">

<img width="644" alt="Screenshot 2022-03-16 at 1 27 46 PM" src="https://user-images.githubusercontent.com/31006028/158543075-19aed542-de5b-4f0c-9cf8-9dbbad9963cf.png">

### Can you identify the location in the driver source code where the problem exists?

frontend/src/Editor/AppVersionsManager.jsx

### If the bug is confirmed, would you be willing to submit a PR?
NO.

**Comment by GokhanKabar** [comment]
Hi @stepinfwd, i am interested by the issue , assign me this issue.

**Comment by felipeTht** [comment]
Can I take this one?

**Comment by stepinfwd** [comment]
sure, assigned to you. Thanks for contributing. @felipeTht
