### ISSUE TITLE
Bugfix :: Flickering issue in app version manager dropdown.

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#2534]
### What is the expected behaviour?
Transition from one version to another while hovering should be smooth.

### What is the current behaviour?
Small flickering while switching/hovering between versions

### How to reproduce the issue?

1.Create a new app.
2.Open App version on top right section.
3.Hover on dropdown version.
4.Observe above flickering issue.

### Screenshots or Screencast
![version](https://user-images.githubusercontent.com/31006028/158543983-d2ab5cb9-d211-4bf3-830b-4f63d8e03411.gif)

### Can you identify the location in the driver source code where the problem exists?

frontend/src/Editor/AppVersionsManager.jsx

### If the bug is confirmed, would you be willing to submit a PR?
No.

**Comment by shivansh-kul** [comment]
Hey, i am a beginner. Can i pick this up?

**Comment by stepinfwd** [comment]
sure go ahead @shivansh-kul
