### ISSUE TITLE
Link to list view docs causes infinite redirects

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2535]
### Environment

ToolJet Cloud

### What is the expected behaviour?

The link should redirect to the URL - `https://docs.tooljet.com/docs/widgets/list-view`

### What is the current behaviour?

The link is redirecting to the URL - `https://docs.tooljet.io/docs/widgets/listview`

### How to reproduce the issue?

1. Drag the `list view` widget to the canvas
2. Click on the widget to open widget properties on the right sidebar
3. Click on the link at bottom of the right sidebar that says: `Listview documentation`

### Screenshots or Screencast
![Screenshot 2022-03-16 at 1 41 02 PM](https://user-images.githubusercontent.com/25361949/158546326-8d5dd8ad-6a03-42fa-a959-027a731a77ab.png)

### Any possible solutions?

- Rename the `list-view.md` file to `listview.md`

**Comment by Aladin056** [comment]
Hi @withshubh  , i am interested by the issue , i would like to know if you are still active on the project because i can fin a solution . Thank you

**Comment by withshubh** [comment]
Hey @Aladin056 👋
Sure! Assigning this issue to you.
Let me know if you need any help.
