### ISSUE TITLE
Style fix for Dashboard Nav link menu placement

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#2544]
### Screenshots or Screencast
![Screenshot 2022-01-27 at 6 18 23 PM](https://user-images.githubusercontent.com/67645175/158608554-e34aa44a-562d-499e-8d39-94cf22e3bdac.png)

**Comment by arpitnath** [comment]
Hi @heykartikey 
Assigning the issue to you

**Comment by heykartikey** [comment]
Hey @arpitnath! I was wondering if you could help me setting up this project on docker in windows, I tried but couldn't do it..
I get `tooljet-server-1` exited with status code 1 when I run `docker-compose up`

**Comment by arpitnath** [comment]
cc: @akshaysasidrn

**Comment by akshaysasidrn** [comment]
@heykartikey could you share the logs shown upon the error?

**Comment by arpitnath** [comment]
@heykartikey Are you still working on it?
