### ISSUE TITLE
**Transformations** is not required for Custom JS `Run JavaScript code` queries.

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#2545]
### Description
Custom JS query has an option to add transformations.

### What is the expected behaviour?
**Transformations** is not required for Custom JS `Run JavaScript code` queries.

### What is the current behaviour?
**Transformations** can be enabled for Custom JS queries.

### How to reproduce the issue?

1. Create a `Run JavaScript code` query

### Screenshots or Screencast
<img width="1308" alt="Screenshot 2022-03-16 at 7 46 13 PM" src="https://user-images.githubusercontent.com/67645175/158610277-f56b8eaf-a808-4928-8647-29fcd7eee248.png">

**Comment by felipeTht** [comment]
Can I work on this?

**Comment by arpitnath** [comment]
@felipeTht Hi, thanks for your interest in this issue.
Putting this issue on hold for now as current users, who already use transformations, won't be able to edit/use it.
Feel free to look at other issues and thanks again for contributing to ToolJet 😄

Happy hacking 🚀

**Comment by arpitnath** [comment]
Closing this issue, as it is no more relevant.
cc: @shubh22
