### ISSUE TITLE
Tabs widget: active tab is not quite distinct in dark mode

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#2546]
### What is the expected behaviour?
The active tab should have a bottom border.

### What is the current behaviour?
Tabs widget: active tab is not quite distinct in dark mode

### How to reproduce the issue?

1. Add Tabs widget from widget manager
2. Toggle theme to Dark

### Screenshots or Screencast
<img width="1057" alt="Screenshot 2022-03-16 at 7 53 30 PM" src="https://user-images.githubusercontent.com/67645175/158611960-7d1a0b0d-7546-488a-b0db-9d84eb6fdf64.png">

UI Reference: 
Tabs widgets should have a distinction in dark theme.
<img width="311" alt="Screenshot 2022-03-16 at 7 54 08 PM" src="https://user-images.githubusercontent.com/67645175/158612078-2eb44377-761a-409f-8d46-cddbb49b6929.png">

**Comment by azizChebbi** [comment]
@arpitnath  Can I work on it ?

**Comment by arpitnath** [comment]
Hi @azizChebbi 
Assigning it to you

**Comment by azizChebbi** [comment]
@arpitnath can u please provide the steps to produce this unwanted behavior ?

**Comment by arpitnath** [comment]
@azizChebbi Hi!
The steps to reproduce the issue is already mentioned in the description above.
- Add a tab widget in the canvas
- In light mode, the active tab has a border-bottom.  
UI Ref: 
![Screenshot 2022-03-20 at 6 30 45 PM](https://user-images.githubusercontent.com/67645175/159163566-72b0140f-f5dc-4fe8-a04c-bbb36f90e92a.png)
- Toggle the editor theme to dark.
UI Ref:
![Screenshot 2022-03-20 at 6 34 26 PM](https://user-images.githubusercontent.com/67645175/159163660-202b4494-0e66-423b-a0d1-3346680c4991.png)

the active tab is not quite distinct in dark mode, the active tab should have a bottom border (a reference of the UI is also attached.)

**Comment by azizChebbi** [comment]
@arpitnath  I meant how to get in there, cause i'm not used to the platform, its the first time to use it.

**Comment by arpitnath** [comment]
@azizChebbi 
Screencast:

https://user-images.githubusercontent.com/67645175/159164591-146f4cea-3bb5-4248-8fa1-6b15516cde38.mov

**Comment by arpitnath** [comment]
@azizChebbi Are you still working on it?

**Comment by arpitnath** [comment]
@azizChebbi, since we haven't received any updates from your side, I am unassigning the issue.

**Comment by JLaat** [comment]
Hello @arpitnath! Can i work on this problem?

**Comment by manishkushare** [comment]
@arpitnath This is issue is not present in the lastest develop branch
<img width="787" alt="Screenshot 2022-08-25 at 4 08 30 PM" src="https://user-images.githubusercontent.com/37823141/186643653-4f02e8f2-d7a2-44c3-a56c-34ed7e4e2e54.png">
