### ISSUE TITLE
Date-rangepicker widget: fields' value are not legible in dark themed

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#2547]
### What is the expected behaviour?
On Selecting a range of dates, the values should be legible in dark mode.
 
### What is the current behaviour?
Fields' values are not legible when the dark theme is applied.

### How to reproduce the issue?

1. Add a Daterangepicker widget from the widget manager
2. Toggle to dark theme
3. Select a range of dates

### Screenshots or Screencast
<img width="405" alt="Screenshot 2022-03-16 at 7 58 49 PM" src="https://user-images.githubusercontent.com/67645175/158613738-1f66d15a-7ca6-4c4c-8417-d67b90b19366.png">

**Comment by jeremydthomas** [comment]
Hello, can I work on this?
