### ISSUE TITLE
Style fix : empty canvas container in editor

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#2548]
### What is the expected behaviour?
`guide` link looks like a text in the dark mode.

### What is the current behaviour?
Link's styles should not change for the dark theme.

### Screenshots or Screencast
<img width="757" alt="Screenshot 2022-03-16 at 8 13 44 PM" src="https://user-images.githubusercontent.com/67645175/158616478-b8505e83-acba-47f9-9513-b46c5d3f794a.png">

<img width="757" alt="Screenshot 2022-03-16 at 8 06 30 PM" src="https://user-images.githubusercontent.com/67645175/158616095-ad120720-31d3-464b-bac9-4b3893c7dbd2.png">

**Comment by Sync271** [comment]
May I fix this?

**Comment by arpitnath** [comment]
Hi @Sync271, for sure.
Assigning the issue to you
