### ISSUE TITLE
Timer widget : the start button should be disabled for "Count down" option with the default value is "00:00:00:000"

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#2549]
### What is the expected behaviour?
- If the timer type is set to "Count down" , the default value is or set to "00:00:00:000", the start button should be disabled as we can't start the timer anyway.
- Also there should be a different default value for the “count down” type f.e 00:00:10:000

### What is the current behaviour?
With timer type is set to "Count down"  with the default value being "00:00:00:000". the start button is enabled. 

### How to reproduce the issue?

1. Add a timer widget from the widget manager
2. Select **Count down** from the timer type dropdown
3. Set the default value to "00:00:00:000" and click start

**Comment by felipeTht** [comment]
Can I work on this?

**Comment by arpitnath** [comment]
@felipeTht assigning it to you
