### ISSUE TITLE
Adding a long appversion name breaks out of the container

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2554]
### What is the expected behaviour?
The appversion name should be restricted to 255 characters and validation needs to exist both on frontend and backend also when a long text is provided it shouldn't break out of the container

### What is the current behaviour?
No validation present for the character length and the text is breaking out of the container

### Screenshots or Screencast
<img width="514" alt="image" src="https://user-images.githubusercontent.com/12490590/158753540-92b0d296-19aa-49d8-adb4-29de69689b6a.png">

**Comment by KaviiSuri** [comment]
Can I pick this issue up?

**Comment by Navaneeth-pk** [comment]
@KaviiSuri sure, assigned to you.

**Comment by tanmoyopenroot** [comment]
@KaviiSuri Are you working on this?
Other i would like to pick this up.

@Navaneeth-pk @gondar00  just wanted to know how you guys generate/updated migration files (files under `server/migrations`)?
Basically after changing the AppVersions `entity`, how do i generate the updated migration file for it, Any command that makes this possible?

**Comment by withshubh** [comment]
Unassigned @tanmoyopenroot  as there was no update for more than a month.

This issue is up for grabs now.
