### ISSUE TITLE
Google SSO fails for users without Google hosted domain

### ISSUE THREAD

**Issue by brentschroeter** [ToolJet/ToolJet#2563]
### Version Information

1.4.0

### Environment

Docker

### What is the expected behaviour?

Google SSO should succeed for any Google Account, assuming that configuration variables are set correctly and the OAuth consent screen is configured as "External" in the Google Cloud Platform console.

### What is the current behaviour?

Google SSO fails when the `hd` key of the OAuth response is omitted, which is the case for any user not belonging to a hosted domain. From [https://developers.google.com/identity/protocols/oauth2/openid-connect](https://developers.google.com/identity/protocols/oauth2/openid-connect): "`hd`: The hosted G Suite domain of the user. Provided only if the user belongs to a hosted domain.".

### How to reproduce the issue?

1. Configure Tooljet for Google SSO with "External" user type. Ensure that environment variable `SSO_RESTRICTED_DOMAIN` is unset.
2. Attempt to log in to Tooljet with Google SSO using a non-GMail, non-Google Workspace account. (In my case, something akin to `example [at] brentsch.com`, which is not a Google Workspace account.)
3. Login will fail with "Invalid Email or Password" message.

### Please provide any traces or logs that could help here.

This error generates no logs, which is an issue of its own.

### Any possible solutions?

When `SSO_RESTRICTED_DOMAIN` is not set, the `OauthService.#isValidDomain` check can be short-circuited. See our version of [server/ee/services/oauth/oauth.service.ts#L26-L29](https://github.com/scholarship-junkies/ToolJet/blob/d997aa93b9fa18f45fd1d4d38e26f0ba0b1014b5/server/ee/services/oauth/oauth.service.ts#L26-L29).

### Can you identify the location in the driver source code where the problem exists?

See link in previous section.

### If the bug is confirmed, would you be willing to submit a PR?

Yes.

**Comment by gsmithun4** [comment]
@brentschroeter Issue is well described, Can you please work on it?
