### ISSUE TITLE
Adding instanceName to mssql plugin

### ISSUE THREAD

**Issue by zhydian** [ToolJet/ToolJet#2567]
### Is your proposal related to a problem?

In my situation we use an instance name for our database instead of the default instance. The plugin doesn't currently allow you to use a connection string or add an instance name to the add connection form which makes it impossible for me to connect to our sql server.

### Describe the solution you'd like

I was able to modify the plugin and add instanceName to the connection options which allowed me to connect without issues. 

### Describe alternatives you've considered

The alternative was to use a connection string instead of splitting all the fields individually but I couldn't get it to work fairly quickly so it seems a lot easier to just add the instance name.

### If the feature is approved, would you be willing to submit a PR?

I have a branch ready to go if I'm able to submit, So yes. I would like to do that.

**Comment by Navaneeth-pk** [comment]
Assigning the issue as you already have the changes in a branch. Thanks for contributing 🚀
@zhydian

**Comment by JaCoB1123** [comment]
I still cannot connect to a SQL Server with an instance name on v1.20.1. So I recreated the original PR to fix this.
