### ISSUE TITLE
Update the text while creating a new query

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2568]
### Environment
Latest develop branch

The text while creating a new query should be changed to "Select datasource".

![Screenshot 2022-03-18 at 10 57 07](https://user-images.githubusercontent.com/7828962/158942995-72c97783-11f0-4a5d-94e3-2913baa291dd.png)

**Comment by felipeTht** [comment]
I would like to help work on this. Let me know if I can. Thanks!
