### ISSUE TITLE
[UI improvement] :: App version text not center aligned

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#2570]
### What is the expected behaviour?
App version text to be center aligned

### What is the current behaviour?
App version text is not center aligned

### How to reproduce the issue?

1.Open a app.
2.Observer App version text in top right , version manager

### Screenshots or Screencast
<img width="1439" alt="original" src="https://user-images.githubusercontent.com/31006028/158946667-e5dbdad7-755a-4a51-acdc-66957a79cb95.png">

<img width="332" alt="Screenshot 2022-03-18 at 11 37 13 AM" src="https://user-images.githubusercontent.com/31006028/158946892-87e65bd8-e234-48aa-8458-dd216c89aa38.png">

### Any possible solutions?
 .app-version-menu-sm  find this class in theme.scss file apply display:flex , then text will be centered

### Can you identify the location in the driver source code where the problem exists?
frontend/src/Editor/AppVersionsManager.jsx
frontend/src/_styles/theme.scss

### If the bug is confirmed, would you be willing to submit a PR?
No.

**Comment by KaviiSuri** [comment]
Can I pick this up?

**Comment by Sync271** [comment]
Is his still up for grabs?
