### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by moracabanas** [ToolJet/ToolJet#2572]
### Is your proposal related to a problem?

I tested Tooljet on Raspberry pi 4 and there is no support for arm64 images yet.

### Describe the solution you'd like

I would use multiarch builds to generate automatic compatible build for every tag

### Describe alternatives you've considered

There is no real alternative to run this on raspberry pi due to CPU architecture.

**Comment by kausar007** [comment]
i second this. tried the same thing and then realised no arm docker images atm

**Comment by moracabanas** [comment]
I build the docker image from the same `docker-compose` whitout any issues for arm64 on raspberrypi4.

 Make sure to use the proper flag for _BUILDKIT_ otherwhise your image **will build but incomplete with no exit errors on half steps** so you end up trying to debug an image which almost no content and no binaries for `label-studio` [BUILDKIT](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds).
 
 Here is the image for your conveniece but I encourage you to build it yourserf for security reasons.
 
 albertodeduce/label-studio:dev-0.1.0

**Comment by moracabanas** [comment]
For no reason I made a mistake, I was posting for Label Studio not ToolJet but using the same aproach could make a valid image as well. Sorry about it, I willl update this thread when I make a try building ToolJet 👍
