### ISSUE TITLE
Behind Corporate Proxy Server

### ISSUE THREAD

**Issue by yapnel** [ToolJet/ToolJet#2575]
I have deployed Tooljet behind a corporate proxy server and it is blocking API calls to REST endpoints on the internet. HOw do i set proxy server details in Tooljet so that it can connect to the REST endpoints in the internet?

Thanks.

**Comment by Navaneeth-pk** [comment]
@akshaysasidrn can you please take a look at this issue?

**Comment by yapnel** [comment]
> @akshaysasidrn can you please take a look at this issue?

Any help with this please

**Comment by akshaysasidrn** [comment]
@yapnel I'd think you'd have to tweak your proxy server firewall rules to allow tooljet to be able to connect to the outside network. There is nothing to be configured for within the app.
