### ISSUE TITLE
resetting password token is invalid

### ISSUE THREAD

**Issue by azizChebbi** [ToolJet/ToolJet#2584]
When trying to reset password, I'm getting asked to enter a token which supposed to be send to my email, but nothing is send.
I thought I should enter any token in the input, but its always invalid. Also the invalid token notification supposed to be in red, but it appears in green as a success notification. Can't take a screen shot cause the notification disappears in a sec.

**Comment by Navaneeth-pk** [comment]
@azizChebbi can you please specify the environment? If self-hosted, to receive the password reset email, you will have to set SMTP config as mentioned here: https://docs.tooljet.com/docs/deployment/env-vars#smtp-configuration--optional-
