### ISSUE TITLE
[ Enhancement ]:: making heders in query panel and properties sidebar fixed

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#2600]
### What is the expected behaviour?
Headers to be fixed in top.

### What is the current behaviour?
Scrolls with the body.

### How to reproduce the issue?

1.Open a new app.
2.Check above mentioned headers ( one in query panel and other in right sidebar (properties section))
3.View screencast for more details

### Screenshots or Screencast

https://user-images.githubusercontent.com/31006028/159429023-4da035c7-223b-447f-a6a2-1ccc19d0c4ec.mov

https://user-images.githubusercontent.com/31006028/159429042-01089d78-8f48-4465-97d3-9af7bed1d081.mov

### If the bug is confirmed, would you be willing to submit a PR?
yes.

**Comment by felipeTht** [comment]
Can I work on this?

**Comment by stepinfwd** [comment]
This one is already fixed , you can check other issues in the repo. Do check ones with tags up for grabs / good first issue. @felipeTht
