### ISSUE TITLE
Popup is partially outside view when selecting something at the bottom of a list

### ISSUE THREAD

**Issue by seltar** [ToolJet/ToolJet#2603]
### Version Information
1.6.0

### Environment
ToolJet kubernetes GKE

### What is the expected behaviour?
The popup should be visible at all times. 

### What is the current behaviour?
The popup appears close to the bottom of the screen, and depending on what you do inside the popup some of the info is cut off because it's outside of the page. 

### How to reproduce the issue?

1. Add a table
2. Collapse the layout group at the bottom right side-bar
3. Add an event in the right side-bar
4. See that the popup for the event is occasionally cut off.

### Screenshots or Screencast
<img width="668" alt="Screen Shot 2022-03-22 at 11 22 43" src="https://user-images.githubusercontent.com/378890/159459440-d2a6f2aa-5ed1-40c2-8f4d-4a282b96c4b8.png">

### Any possible solutions?
Ensure the components that are positioned absolute are always within view.

**Comment by stepinfwd** [comment]
closing this issues since bug doesn't exist now.
