### ISSUE TITLE
Suggestions for improvements to the query editor

### ISSUE THREAD

**Issue by seltar** [ToolJet/ToolJet#2604]
1. When I edit the queries and scroll down the preview / save button disappears. 
- They should stick to the top, so they're always available. 
2. I've lost my changes a few times when switching between the queries. 
- There needs to be a warning before switching to another query when you have unsaved changes. 
3. Sometimes the query doesn't appear. I have to switch between the different queries a few times, or even reload the entire page to see the query. 
- Add a refresh query button, or figure out the problem with loading the query in the first place. 
4. Was a bit hard to understand how to do certain complex things. 
- Improve documentation and add more examples for how to do certain intermediate actions. 
i.e combining two data sources via a JS query.

**Comment by shubh22** [comment]
Issues in this have been addressed in ToolJet 2.0.
