### ISSUE TITLE
Change transformations toggle text font-weight 

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#2613]
### What is the expected behaviour?
Change transformations toggle text font-weight  to 400.

### What is the current behaviour?
Font weight currently is set to 600.

### How to reproduce the issue?

1.Open a new app
2.Open any datasource
3.Check for "transormations" toggle , observe

### Screenshots or Screencast

<img width="770" alt="Screenshot 2022-03-23 at 1 57 10 PM" src="https://user-images.githubusercontent.com/31006028/159656510-037e3a4a-625e-4a13-bde2-2fa8fcb2b0b6.png">

### Any possible solutions?
fontWeight: 400

### Can you identify the location in the driver source code where the problem exists?
frontend/src/Editor/QueryManager/Transformation.jsx

### If the bug is confirmed, would you be willing to submit a PR?
NO.

**Comment by Lucarnosky** [comment]
Could you please assign it to me?

**Comment by Navaneeth-pk** [comment]
@Lucarnosky assigned to you. Thanks fro contributing!

**Comment by Lucarnosky** [comment]
@Navaneeth-pk Glad to help
