### ISSUE TITLE
Sign up page does not have scroll other than on card.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#2614]
### What is the expected behaviour?
When we click on the sign up email then the page opened should be scrollable from everywhere.

### What is the current behaviour?
When we click on the sign up email then the page opened should be scrollable from everywhere but it is not scrollable anywhere other than the card in which all details should be filled in.

### How to reproduce the issue?

1. Go to sign up page.
2. Enter the email and click Sign up.
3. Go to inbox of mail.
4. Click on the email and the link.
5. Try scrolling from other than the card

### Screenshots or Screencast
https://drive.google.com/file/d/15gPHPcFFI13f3qxjCmxxUWTWpQTmnbdH/view?usp=sharing

**Comment by DinahWorld** [comment]
Hi, can you assign me? I think I resolved the bug

**Comment by withshubh** [comment]
fixed in: https://github.com/ToolJet/ToolJet/pull/2643
