### ISSUE TITLE
using react-datepicker

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#2618]
### Is your proposal related to a problem?

In the Datepicker component, we are using datetime library which is not comprehensive enough to meet the specifications of our date picker component. It has several bugs, and usage is difficult.

### Describe the solution you'd like

 We can replace the existing library with react-datepicker library

### If the feature is approved, would you be willing to submit a PR?
Yes, Willing to raise a PR

**Comment by exetico** [comment]
Hi 

Are you facing the same problem as me?

![image](https://user-images.githubusercontent.com/3549445/159931617-321cf93f-1d05-42a9-8de3-811521868e1d.png)

The calendar-picker looks very odd (Running latest version of Chrome).

**Comment by manishkushare** [comment]
Hey, the problem which you are facing, regarding the month tab display, is
working fine for me.

**Comment by exetico** [comment]
Thanks. Interesting. I'm running the latest version on docker. Wierd!

**Comment by manishkushare** [comment]
Hey, I am sorry there was a little mid-understanding from my end. I discuss
with the team, there is a bug and we are working on it.

**Comment by manishkushare** [comment]
I am sorry, there was a little misunderstanding from my side.
There is a bug and we are working on it.
I'll update you soon about it.

**Comment by exetico** [comment]
Great. Is it fxed, @manishkushare ? :)

**Comment by manishkushare** [comment]
Hello, we are working on it, I will talk with my team and inform you
accordingly.

**Comment by sherfin94** [comment]
Hey @exetico, we have a full tutorial for setting up ToolJet development environment on your local: https://docs.tooljet.com/docs/contributing-guide/setup/docker, please ping us on our slack channel if you're stuck somewhere on the tutorial.

The bugs you mentioned, the one with Table datepicker, having to click table action button twice after editing field, do exist. I've added them to my list of todos, and will prioritise accordingly. Thank you so much for reporting!
