### ISSUE TITLE
[Text widget] Text not visible in dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2620]
### Environment

ToolJet Cloud

### What is the expected behaviour?

In dark mode, when a text widget is placed on top of the container the text should be visible as by default the hex code in the **Styles** section is set to `#000`(black).

### What is the current behaviour?

In dark mode, when a text widget is placed on top of the container widget the text is not visible. The reason being the text color is white even when the default hex-code is set to `#000`. When try to change the color to black the hex-code changes to `#000000ff`

### How to reproduce the issue?

1. Switch the app editor to the dark mode
2. Drag a container
3. Drag a text on top of the container

### Screenshots or Screencast

<img width="871" alt="Screen Shot 2022-03-23 at 13 51 03" src="https://user-images.githubusercontent.com/25361949/159711505-c10e9d53-611f-487b-a9ff-2dfd41c66013.png">

<img width="856" alt="Screen Shot 2022-03-23 at 13 51 27" src="https://user-images.githubusercontent.com/25361949/159711489-91af09be-b6cb-4aee-934f-b91f4bd6fdf6.png">

**Comment by manishkushare** [comment]
This issue will get resolved by fixes in #3866

**Comment by shubh22** [comment]
This has been fixed in latest release.
