### ISSUE TITLE
GUI mode for mssql (so `Bulk update` can be used)

### ISSUE THREAD

**Issue by exetico** [ToolJet/ToolJet#2625]
### Is your proposal related to a problem?

No.

### Describe the solution you'd like

I would like to use the "GUI mode" for mssql, so I can use the `Bulk update` function. As pr. my understand I'm unable to run the `Bulk update` with mssql as the data-source.

More info for mysql (not `mssql`) [here](https://docs.tooljet.com/docs/data-sources/mysql/#gui-mode).

### Describe alternatives you've considered

An alternative way to use `Bulk update` without having to use the GUI mode. But I've not found it.

### If the feature is approved, would you be willing to submit a PR?

I won't be able to do that kind of logics.

**Comment by withshubh** [comment]
This feature has been released. Thanks for creating the issue.
