### ISSUE TITLE
Changing the backgroundColor key of  computedStyle object in the container and list item widget to change the background color in the darker theme, when we are in dark mode

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#2626]
### Is your proposal related to a problem?
In the dark mode, the container and list item widget background color is not changing to dark color

### Describe the solution you'd like
We can simply make the decision in the computed style variable and decide, whether the background color should be light or dark, depending upon the mode 
for example - 

Earlier code :

const computedStyles= {backgroundColor};

Updated Code can be:
const computedStyles = {
 backgroundColor: darkMode ? '#47505D' : '#ffffff',
}

### If the feature is approved, would you be willing to submit a PR?
I am willing to submit a PR

**Comment by arpitnath** [comment]
Closing this issue.
Refer:
#2648 
#2649
