### ISSUE TITLE
No users tab required for All users in Manage Groups.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#2633]
### What is the expected behaviour?
There should not be users tab at all for All the admins in manage groups.

### What is the current behaviour?
There is users tab in manage groups for all users.

### How to reproduce the issue?

1. Go to manage groups.
2. Go to users tab & observe.

### Screenshots or Screencast
https://drive.google.com/file/d/1kOd0HkAwbWr840Q2IfyBfODxHc9E2px5/view?usp=sharing

**Comment by najeebkp** [comment]
Hi @Nandinisaha13 @shubh22 i would like to work on this. please assign me this taks.

**Comment by arpitnath** [comment]
Hi @najeebkp, 
Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by najeebkp** [comment]
Hi @arpitnath ,
I'm not able to setup the repo in my local. I'm sorry. you can assign this issue to someone else.
Thanks.

**Comment by utkershrajvenshi** [comment]
Hi @arpitnath . I'd like to work on this one. Could you please assign this issue to me?

**Comment by arpitnath** [comment]
@najeebkp, For setup you can follow https://docs.tooljet.com/docs/contributing-guide/setup/docker/
If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by arpitnath** [comment]
Hi, @username, 
Thanks for showing interest in contributing to ToolJet. Since @najeebkp unassigned himself the issue, we've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hey @utkershrajvenshi 
Any updates on the PR?

**Comment by utkershrajvenshi** [comment]
Hi. I am facing issues in setting up ToolJet on my machine. Is there a way to work on this using Gitpod?

**Comment by withshubh** [comment]
> Hi. I am facing issues in setting up ToolJet on my machine. Is there a way to work on this using Gitpod?

Currently, we don't have the support for Gitpod. You can shoot any question regarding setting up ToolJet on our Slack community here: [Slack community](https://tooljet.com/slack)
