### ISSUE TITLE
No apps tab required for Admin in Manage Groups.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#2634]
### What is the expected behaviour?
There should be no apps tab required for Admin because admin will always have read/write permission for all the apps.

### What is the current behaviour?
Apps tab present in manage groups for admins.

### How to reproduce the issue?

1. Go to manage groups.
2. Go to admins & observe.

### Screenshots or Screencast
https://drive.google.com/file/d/1EoK-lEcAGtuv0sNW04u53QZ9BpSxj0Ge/view?usp=sharing

**Comment by DinahWorld** [comment]
Hi, can you assign me ?

**Comment by withshubh** [comment]
Duplicate issue - https://github.com/ToolJet/ToolJet/issues/2902

**Comment by daniloff200** [comment]
I would like to pick this one !
