### ISSUE TITLE
Got success message even tho email is empty while creating an account on Homepage.

### ISSUE THREAD

**Issue by Olaleye-Blessing** [ToolJet/ToolJet#2639]
### Is your proposal related to a problem?
Not really a problem but I guess it could help users to know their email isn't filled.

I had to refresh the page before the email input field could appear again. I needed to do that in order to input my email.

### Describe the solution you'd like
Check if email is empty before sending verification link.

### If the feature is approved, would you be willing to submit a PR?
Yes.

![Screenshot (220)_LI](https://user-images.githubusercontent.com/70102539/160186245-4c81d6cb-072f-4dc3-b3e4-b11c2a072cd4.jpg)
![Screenshot (221)_LI](https://user-images.githubusercontent.com/70102539/160186259-af43572a-9614-4df5-8a5a-6dfccf1b6539.jpg)
![Screenshot (222)](https://user-images.githubusercontent.com/70102539/160186278-9a5e9f06-cba9-4c2a-9613-9fd07bc10596.png)

**Comment by Navaneeth-pk** [comment]
Closing this issue as the website is not part of this repository. Currently the codebase for website is not public. We will fix this issue asap.
@Olaleye-Blessing
