### ISSUE TITLE
Recursive redirects

### ISSUE THREAD

**Issue by nljms** [ToolJet/ToolJet#2647]
### Environment
MacOS

### What is the expected behaviour?
I should be able to visit the [REST API](https://docs.tooljet.com/docs/data-sources/restapi) page.

### What is the current behaviour?
On the [integrations](https://tooljet.com/integrations) page, upon clicking the REST API card, you'll be redirected to a new tab containing the recursive redirects

### How to reproduce the issue?

1. Go to [Integrations](https://tooljet.com/integrations) page.
2. Click `SaaS/APIs` tab and click REST API card
![image](https://user-images.githubusercontent.com/25510386/160297613-15c9c39b-88cc-426c-979f-9d887c9ed922.png)

3. You'll be redirected to the issue

### Please provide any traces or logs that could help here.
Recursive redirects 🤔. I think there is no handling for the broken links
![image](https://user-images.githubusercontent.com/25510386/160297557-c02a2db1-b6b4-4c2a-b06c-23c540c589d2.png)

### Any possible solutions?
- Replace `https://docs.tooljet.com/docs/data-sources/rest-api` with `https://docs.tooljet.com/docs/data-sources/restapi`
- Create handling for broken links. 

### Can you identify the location in the driver source code where the problem exists?
- Nah I can't see the source code of the [integrations](https://tooljet.com/integrations) page.
- this might be the [culprit](https://github.com/ToolJet/ToolJet/blob/d45ef4865e6add191a445e761bca6dac35777bb5/docs/docusaurus.config.js#L7) or this [one](https://github.com/ToolJet/ToolJet/blob/d45ef4865e6add191a445e761bca6dac35777bb5/docs/docusaurus.config.js#L8) 
### If the bug is confirmed, would you be willing to submit a PR?
Yup

**Comment by Navaneeth-pk** [comment]
Thanks for reporting the issue, assigned it to you as mentioned in the description. 
@nljms
