### ISSUE TITLE
**List view** widget does not adapt to the dark theme

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#2648]
### What is the expected behaviour?
**List view** widget should adapt to the dark theme.

### What is the current behaviour?
**List view** widget does not adapt to the dark theme

### How to reproduce the issue?

1. Add List view widget to the canvas from widget manager
2. Toggle to the dark mode

### Screenshots or Screencast
![Screenshot 2022-03-28 at 2 39 15 PM](https://user-images.githubusercontent.com/67645175/160365893-e9311b3e-926e-4705-a417-fd8178b4091e.png)

**Comment by vctc** [comment]
Please assign this also to me since I am taking another issue which is related to this

**Comment by arpitnath** [comment]
Hi @vctc, happy to assign this issue to you. It will be really great if you can raise a Pull request first for the issue already assigned to you.
Thanks for contributing to ToolJet 😅
