### ISSUE TITLE
**Container** widget does not adapt to the dark theme

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#2649]
### What is the expected behaviour?
**Container** widget should adapt to the dark theme.

### What is the current behaviour?
**Container** widget does not adapt to the dark theme

### How to reproduce the issue?

1. Add Container widget to the canvas from widget manager
2. Toggle to the dark mode

### Screenshots or S
![Screenshot 2022-03-28 at 2 43 27 PM](https://user-images.githubusercontent.com/67645175/160366240-3a3af3a1-4d3a-4aac-9ee0-c255269e456b.png)
creencast

**Comment by vctc** [comment]
Shall I work on this?

**Comment by arpitnath** [comment]
@vctc sure 😁
Assigning the issue to you.

**Comment by arpitnath** [comment]
@vctc Are you still working on it?

**Comment by arpitnath** [comment]
@vctc since we haven't received any updates from your side, I am unassigning the issue.
