### ISSUE TITLE
Add repeat password input field for change password section in profile page

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#2659]
### Is your proposal related to a problem?
the repeat password field should be there at the change password section
page: `/settings`

![Screenshot 2022-03-28 at 6 35 40 PM](https://user-images.githubusercontent.com/3417097/160404067-3e3b36a8-e364-4163-95b0-e8af50435f94.png)

### Describe the solution you'd like
add repeat password field and validate if new password and repeat password are same from front-end

**Comment by zshawdev** [comment]
Hello @gsmithun4, I'd like to help with this one! Would I be able to get assigned to it?

**Comment by arpitnath** [comment]
Hi @zshawdev, assigning the issue to you.
Thanks for contributing to ToolJet 😁

**Comment by guelate** [comment]
IHello, if the task is abandoned I can do it :)

**Comment by zshawdev** [comment]
Great, I am working on it but I will let you know otherwise @guelate

**Comment by guelate** [comment]
Okay, no problem

**Comment by withshubh** [comment]
Hey @zshawdev 👋 
Any update on the fix for this issue?

**Comment by withshubh** [comment]
Hey @zshawdev 
Since there is no update from you - I'm unassigning the issue.

**Comment by rachel-l-sanchez** [comment]
I'd like to contribute to this. Would you be able to assign it?

**Comment by withshubh** [comment]
Hey @rachel-l-sanchez 👋 
Assigned it to you. Thanks for your interest in contributing to ToolJet

**Comment by samyakjain26** [comment]
can you assign me this issue

**Comment by withshubh** [comment]
Closing this issue as fixed.
