### ISSUE TITLE
 initial account password is wrong

### ISSUE THREAD

**Issue by snmin** [ToolJet/ToolJet#2663]
I encountered a problem. After deploying with docker according to the tutorial (https://docs.tooljet.com/docs/deployment/docker), the initial account password is incorrect.
(This seeds the database with a default user with the following credentials: email: [dev@tooljet.io](mailto:dev@tooljet.io) password: password)

**Comment by akshaysasidrn** [comment]
Closing this @snmin

**Comment by MartexCorp** [comment]
encountered the same problem
