### ISSUE TITLE
commandline  tool Link in README is 404

### ISSUE THREAD

**Issue by cep21** [ToolJet/ToolJet#2672]
I'm in the file README and see
```
Extend with plugins:: use our [commandline tool](https://www.npmjs.com/package/tooljet) to easily boostrap new connectors.
```

I click the link and it is a 404: package 'tooljet' not found

![image](https://user-images.githubusercontent.com/20358/160715003-4fadd956-4e1c-4ec5-bc12-70d9baae9a4b.png)

**Comment by Navaneeth-pk** [comment]
Sorry for the broken link. The package has been moved to https://www.npmjs.com/package/@tooljet/cli.
@cep21

**Comment by Sohamkayal4103** [comment]
Can I work on this?

**Comment by Navaneeth-pk** [comment]
Sure, assigning to you.
@Sohamkayal4103

**Comment by manjunath00** [comment]
@Navaneeth-pk Can you assign this to me?

**Comment by Navaneeth-pk** [comment]
Sure. @manjunath00

**Comment by manjunath00** [comment]
Thank you @Navaneeth-pk 
https://github.com/ToolJet/ToolJet/pull/2833
