### ISSUE TITLE
User group not creating on press enter

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#2679]
### Environment
development

### What is the expected behaviour?
manage groups -> create new group -> enter group name -> press enter
New group should be created

### What is the current behaviour?
Group is not created but navigated back  to manage groups page

### How to reproduce the issue?
manage groups -> create new group -> enter group name -> press enter

### Screenshots or Screencast
https://www.loom.com/share/db3e9a84b56142c8b0ca6d123ca23212

### Any possible solutions?
Fix on enter press functionality

**Comment by eyuelberga** [comment]
I would like to work on this

**Comment by arpitnath** [comment]
Hi @eyuelberga, sure! Assigning the issue to you.
