### ISSUE TITLE
[docs]: fix broken image in Audit logs

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2697]
### Summary

The image in the `Understanding information from logs` section in Audit log docs is broken.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/Enterprise/audit_logs#understanding-information-from-logs

### Steps to reproduce the issue

1. Open **Audit logs** in docs
2. Go to the `Understanding information from logs` section
3. You'll find the broken image the 

#### Fix
- Correct the typo from `Enterprise` to `enterprise` in the img src path

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by jeremydthomas** [comment]
I would like to do this one if its still available.

**Comment by aritracodes** [comment]
I have done this but i don't know if it has reached the admin. I am new to open-source project actually

**Comment by jeremydthomas** [comment]
well hello there, me too. this one looked simple enough. glad you were able to do it

**Comment by aritracodes** [comment]
Thanks @jeremydthomas

**Comment by withshubh** [comment]
Fixed in PR #2698
