### ISSUE TITLE
newGroupName value is getting persisted after clicking cancel button, it should be set to null

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#2702]
### Environment
Development

### What is the expected behavior?
When a user clicks on the Cancel button, newGroupName key in the state object should be set to null

### What is the current behavior?
If the user enters some value in the input element and later Presses the Cancel key, newGroupName value is still persisted, and when the user again, chooses to create a group, this time without entering anything in the input element, if he simply clicks the "Create Group" button, the app does not alert a warning rather simply creates a group with the persisted value of newGroupName (which is the input user given before clicking cancel, last time)

### How to reproduce the issue?

1. Go to the dashboard
2. Hover on the User Profile on the left side of the Header, next to theme mode --> It will open a dropdown
3. In the dropdown, click on Manage Groups
4. Click on Create  new group button
5. You will see the modal having an input element to create a group, without inserting any input in the element, press Create Group Button, You will get a warning, that the Group name cannot be null
6. Now,  insert some input as a group name into the input element and Press the Cancel button -->name of the group name: "Group1"
7. Again, Click on Create New Group button and, you will see  a modal having an input element, which is empty by default, and now without inserting anything, Press Create Group button, It Won't give any error, rather simply creates a group name by value "Group1"

### Screenshots or Screencast
[ToolJet - Dashboard - 1 April 2022 - Watch Video](https://www.loom.com/share/eaba208bc32d43658275b5a87b53599c)

### Any possible solutions?
When clicking on the Cancel button, make sure, we also make newGroupName in the state as null

### Can you identify the location in the driver source code where the problem exists?
Frontend > src > ManageGroupPermissions > ManagePermission.jsx

**Comment by almaraz333** [comment]
I can work on this

**Comment by Navaneeth-pk** [comment]
Sure, assigned the issue to you. Thanks for contributing to ToolJet.
@almaraz333

**Comment by almaraz333** [comment]
[PR](https://github.com/ToolJet/ToolJet/pull/2835) up for review

**Comment by almaraz333** [comment]
This issue can be closed
