### ISSUE TITLE
Split users list into active or archived

### ISSUE THREAD

**Issue by watollop** [ToolJet/ToolJet#2706]
### Is your proposal related to a problem?

When the list of users is long is difficult to differentiate from Archived or Active

(Write your answer here.)

### Describe the solution you'd like
Current:
<img width="1327" alt="current" src="https://user-images.githubusercontent.com/10385633/161249815-9075d043-7dc9-4a8e-a50e-87b389d2d775.png">

Future:
<img width="1311" alt="future" src="https://user-images.githubusercontent.com/10385633/161249812-4f5391e0-192c-420d-aebc-accb137ee30b.png">

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by withshubh** [comment]
Hey @watollop 👋 
Are you working on a fix for this issue?

**Comment by withshubh** [comment]
Hey @watollop 
Please let us know if you're working on this issue?

**Comment by withshubh** [comment]
Hey @watollop 
Unassigning this issue as there was no update from you on this issue for more than a month.

**Comment by khalatevarun** [comment]
Hey @withshubh 
I would like to take up this issue. Could you please assign it to me?

**Comment by withshubh** [comment]
Hey @khalatevarun 👋 
Sure, assigning it to you.

**Comment by shubh22** [comment]
Adding filters on users page as described in issue #4910. Closing this issue now.
