### ISSUE TITLE
Make 'Queries' `div` scrollable

### ISSUE THREAD

**Issue by prasadwalvekar** [ToolJet/ToolJet#271]
### Environment
All

### What is the expected behavior?
Queries `div` should be scrollable

### What is the current behavior?
Queries `div` is not scrollable

### Screenshots or Screencast
![image (1)](https://user-images.githubusercontent.com/4965435/122399494-7a5fa800-cf98-11eb-826b-8adff7b3c20b.png)

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by prasadwalvekar** [comment]
Picking this up.

**Comment by prasadwalvekar** [comment]
@Navaneeth-pk PR is [merged](https://github.com/ToolJet/ToolJet/pull/272). Can we close this issue?

**Comment by Navaneeth-pk** [comment]
Sure, please link PRs to issues so that the issue gets closed automatically. (https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue )
