### ISSUE TITLE
Transition animation for app search field on the dashboard

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2717]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/7828962/161416168-f33c2ef6-2204-4ee7-80f2-cb3fbb242d96.png">
When this field is clicked, the width is increased. It would be better if we add `ease-in-out` transition for width change. 

Reference: https://stackoverflow.com/questions/7861648/animate-an-elements-width-from-0-to-100-with-it-and-its-wrapper-being-only-a

**Comment by Olaleye-Blessing** [comment]
Can I work on this?

**Comment by Navaneeth-pk** [comment]
Sure, assigned the issue to you. Thanks for contributing !

@Olaleye-Blessing
