### ISSUE TITLE
Move documentation link in transformation popover to a new line

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2735]
### Environment
All

### What is the expected behaviour?
In the `Transformations` popover the documentation link should be placed on the next line 

### What is the current behaviour?
In the `Transformations` popover the documentation link is not placed on the next line 

### Screenshots or Screencast
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/12490590/161532864-666b9a0e-e518-48f5-8559-7abd59d7538b.png">

### Any possible solutions?
In [this](https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/Editor/QueryManager/Transformation.jsx#L36) line replace `{' '}` with a `<br />` html tag

**Comment by manjunath00** [comment]
I will fix this

**Comment by manjunath00** [comment]
https://github.com/ToolJet/ToolJet/pull/2832
