### ISSUE TITLE
Request url field misaligned when rest api is selected in the query editor

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2736]
### What is the expected behaviour?
Request url field should be aligned with the method selection dropdown

### What is the current behaviour?
Its not aligned

### Screenshots or Screencast
<img width="769" alt="image" src="https://user-images.githubusercontent.com/12490590/161533594-f13fbcbb-d5c6-4058-9a06-ec282e8df83f.png">

### Please provide any traces or logs that could help here.
resolution: 1440x373

**Comment by timo-tech19** [comment]
Has this issue been solved? Can I work on it?

**Comment by gondar00** [comment]
@timo-tech19 sorry this issue has been fixed, please filter using ["good first issue"](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) to pick another un-solved issue

**Comment by gondar00** [comment]
@timo-tech19 sorry this issue has been fixed, please filter using ["good first issue"](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) to pick another un-solved issue
