### ISSUE TITLE
Delete button is not aligned with the header fields in rest api query editor

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2737]
### What is the expected behaviour?
Delete button should be aligned with the header fields in rest api query editor

### What is the current behaviour?
Its not aligned

### Screenshots or Screencast
<img width="769" alt="image" src="https://user-images.githubusercontent.com/12490590/161533594-f13fbcbb-d5c6-4058-9a06-ec282e8df83f.png">

### Please provide any traces or logs that could help here.
resolution: 1440x373

**Comment by withshubh** [comment]
> there is one more problem when you click rest API section it keep getting forward [image](https://user-images.githubusercontent.com/63035982/161550618-1bb78172-28f3-46cd-83a5-9061f26ae47a.png)

This is fixed.

**Comment by prasanta10** [comment]
does this issue still need working?

**Comment by gondar00** [comment]
Seems to be fixed @withshubh
