### ISSUE TITLE
Rest api headers keep incrementing when no items are added to either key or value

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2738]
### What is the expected behaviour?
Header fields should not increment when no value is entered

### What is the current behaviour?
Header fields are incrementing when no value is entered

Same issue observed with params and body tabs too
### Screenshots or Screencast

https://user-images.githubusercontent.com/12490590/161534761-100c91d2-cdfa-4614-b80f-c5eab1c7bb44.mov

**Comment by eyuelberga** [comment]
I would like to help out with this issue

**Comment by Navaneeth-pk** [comment]
Assigned to you @eyuelberga. Thanks for contributing!
