### ISSUE TITLE
Query editor incorrect sequence of queries after creating 9 queries

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2739]
### Version Information
Latest 

### Environment
MacOS

### What is the expected behaviour?
Queries should be created in a sequential order

### What is the current behaviour?
Queries are not created in a sequential order after creating 9 queries

### Screenshots or Screencast
https://user-images.githubusercontent.com/12490590/161537486-27c711d3-e930-4b90-9f01-1cc617404407.mov

**Comment by tanmoyopenroot** [comment]
Hey @gondar00 , Gonna pick this up today.
