### ISSUE TITLE
Add search term highlighting to table widget

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2743]
### Is your proposal related to a problem?
Dynamically mark search terms when a user searches inside a table widget this can be provided as a setting option inside table widget inspector

### Describe the solution you'd like
When a user searches for a text highlight it if the setting option is set to true

Ex: When a user searches for keyword "sarah" the text can be highlighted where the keyword matches

<img width="798" alt="image" src="https://user-images.githubusercontent.com/12490590/161562189-a7ecca93-0085-43bc-b024-2cfdfe5f392d.png">

**Comment by felipeTht** [comment]
Can I work on this?

**Comment by Navaneeth-pk** [comment]
@felipeTht sure, assigned to you.
