### ISSUE TITLE
Feature: Tooltip for widgets 

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#275]
The widgets in the widget sidebar should show a tooltip on hover. `description` property of the widgets can be used as the text.

**Comment by virajbahulkar** [comment]
Picking this up

**Comment by prasadwalvekar** [comment]
@virajbahulkar Are you working on this?

**Comment by Navaneeth-pk** [comment]
Fixed in https://github.com/ToolJet/ToolJet/pull/318
