### ISSUE TITLE
Unauthorized users can change the password of a registered user

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#2750]
### Version Information
1.6.0

### Environment
all

### What is the expected behaviour?
The server should validate token being present

### What is the current behaviour?
It's possible for unauthorized users to change the password of a registered user via the `set_password_from_token` method used by the user invitation system. The user chosen is entirely dependent on the database, because the underlying implementation using findOne does not specify a particular sort order

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by withshubh** [comment]
Fixed
