### ISSUE TITLE
Tooljet navbar blinks when the page loads

### ISSUE THREAD

**Issue by a0v0** [ToolJet/ToolJet#2779]
### Version Information
Latest

### Environment
Heroku

### What is the expected behaviour?
The Tooljet navbar should not be not flash when page is refreshed.

### What is the current behaviour?
The Tooljet navbar should flashes when page is refreshed. I have disabled `hide header for launched apps`

### Screenshots or Screencast
![My Video1 (1)](https://user-images.githubusercontent.com/62926341/162586744-9f3b1dd2-9b18-4b02-ad4b-5402acf1d276.gif)

**Comment by withshubh** [comment]
@sherfin94 Can you please check this issue

**Comment by Ghafrigm** [comment]
Any updates?
