### ISSUE TITLE
[Improvement] Authentik / Generic OpenID (OIDC) SSO support

### ISSUE THREAD

**Issue by caraar12345** [ToolJet/ToolJet#2791]
### Is your proposal related to a problem?

If someone is interested in a selfhosted solution like ToolJet, there's a good chance they have a selfhosted single sign-on platform too.

### Describe the solution you'd like

Google and GitHub authentication are a great start, but a generic OpenID Connect (OIDC) implementation would get you coverage of most of the SelfHosted authentication providers too, such as Authentik, Authelia or Keycloak.

### Describe alternatives you've considered

SAML2 could also be an option, but being as you already have Google and GitHub, the steps needed for a generic OpenID Connect implementation shouldn't be too bad. OIDC is a layer on top of OAuth 2.0, much like Google and GitHub authentication!

### If the feature is approved, would you be willing to submit a PR?

The bigger and more important question is whether you'd want to read my questionable code...

Plus, I would not consider myself a JS dev, and especially not a TS dev. So no, you really don't want to read it..!

_[Issue sparked from /u/odaman8213's comment on Reddit](https://reddit.com/r/selfhosted/comments/u16p4u/_/i4b1hwr/?context=1)_

**Comment by bbigras** [comment]
Any plans to bring OIDC support from the enterprise into the community edition?

I think https://sso.tax makes good arguments as to why it should be standard.

**Comment by Navaneeth-pk** [comment]
We do not have plans to move OIDC to community edition at the moment. 
@bbigras
