### ISSUE TITLE
Manage user Archive and Unarchive button style 

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#2792]
### Is your proposal related to a problem?
Manage user page Archive and Unarchive button does not have a look and feel of a button
three dots are appearing on click and table structure in changing

https://www.loom.com/share/f8396f1ee742470bb0953222757218f1

### Describe the solution you'd like
Add look and feel of a button to Archive and Unarchive, add loading  icon on API call

<img width="1351" alt="Screenshot 2022-04-12 at 9 57 55 AM" src="https://user-images.githubusercontent.com/3417097/162880726-d5cf5692-edd6-4097-8222-cd4f3ac4eccf.png">

### If the feature is approved, would you be willing to submit a PR?
No

**Comment by SulthanNK** [comment]
Is that any chance to contribute to this issue with windows 11? I noticed the contributing guideline that listed mac os, ubuntu, and docker only.

**Comment by eyuelberga** [comment]
I would like to contribute to this issue

**Comment by Navaneeth-pk** [comment]
@SulthanNK you can use the docker guide to setup on Windows. We do not have a guide for Windows as of now. Should I assign the issue to you?

@eyuelberga Thanks for your interest in contributing. Checking with @SulthanNK first as their comment came first.

**Comment by SulthanNK** [comment]
Yeah, I'm not using the docker much before. But, I would like to give it a try by starting working on this issue. I love to learn by doing. 😃

**Comment by Navaneeth-pk** [comment]
Assigned the issue to you. Please feel free to use our Slack community if you need any help setting up ToolJet on Windows. Here is the link to join: https://join.slack.com/t/tooljet/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg
@SulthanNK

**Comment by withshubh** [comment]
Hey @SulthanNK 
There's been no update on this issue for more than a month, unassigning it.

**Comment by withshubh** [comment]
Hey @eyuelberga 👋 
Will you be willing to pick up this issue?

**Comment by eyuelberga** [comment]
Hi @withshubh yes would like to work on it

**Comment by withshubh** [comment]
Thanks @eyuelberga 
Assigned to you
