### ISSUE TITLE
For some widgets second part of the name starts in lowercase.

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#2805]
### What is the expected behaviour?
For all widgets second name must start with uppercase
ex : instead of **Range slider** ---> **Range Slider**.
ex: **List view ---> List View**

### What is the current behaviour?
Some of them start in lower case.

### How to reproduce the issue?

1.Check right widgetbar for reference , observe the names.

### Screenshots or Screencast
<img width="402" alt="Screenshot 2022-04-12 at 8 15 46 PM" src="https://user-images.githubusercontent.com/31006028/163043254-43754412-7ae7-4b77-834f-69590308bdb7.png">

###Solution
displayName property in components file for every widget with above mentioned issue can be updated.

### Can you identify the location in the driver source code where the problem exists?
frontend/src/Editor/Components/components.js

### If the bug is confirmed, would you be willing to submit a PR?
No.

**Comment by mathiasdonoso** [comment]
I think this will also imply a widget name update in the documentation, right?

**Comment by almaraz333** [comment]
I can work on this task.

**Comment by Navaneeth-pk** [comment]
@mathiasdonoso no, we do not need to update the names in documentation. We just need to change the display name of the widgets in `components.js`.

**Comment by aan-arakal** [comment]
I can work on the task

**Comment by Navaneeth-pk** [comment]
@mathiasdonoso are you already working on this issue?

**Comment by mathiasdonoso** [comment]
@Navaneeth-pk yes, I am on it. I have the change locally. But I thought that the issue need first to be confirmed as a bug.
