### ISSUE TITLE
[docs]: Fix sidebar position of Amazon S3 docs

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2810]
### Summary

All the docs in the left sidebar are placed in lexicographic order. Amazon s3 docs are not in order. 

The sidebar position of [Amazon S3 docs](https://docs.tooljet.com/docs/data-sources/s3) is currently set to 20; Make it 1.1 to place it in order.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/s3

#### Solution

1. Open `s3.md` in `docs/datasource reference`
2. Set sidebar position from `20` to `1.1`
<img width="692" alt="Screenshot 2022-04-13 at 1 31 35 PM" src="https://user-images.githubusercontent.com/25361949/163129693-afcc75ad-81cd-4ab7-bbf5-d890acdcd261.png">

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by manjunath00** [comment]
I will pick this up

**Comment by manjunath00** [comment]
https://github.com/ToolJet/ToolJet/pull/2829
