### ISSUE TITLE
Kanban Support

### ISSUE THREAD

**Issue by alta-atc** [ToolJet/ToolJet#2814]
### Is your proposal related to a problem?

Everyone loves a great Kanban board. It's a unique and effective way to visualize tasks or stage-driven workflows.

### Describe the solution you'd like

Drag & drop Kanban functionality 

### Describe alternatives you've considered

Implementing a custom workaround for the time being. 

### If the feature is approved, would you be willing to submit a PR?

Yes

**Comment by vernonstinebaker** [comment]
+1 this would be a great addition

**Comment by arpitnath** [comment]
### Feature Request : `Kanban Widget`
Refer: #3049 
**Description**
- [ ] Kanban board UI (minimalistic)
- [ ] Dark themed
- [ ] Able to build the board with predefined columns and card data provided (similar to other widgets)
- [ ] Able to build the board with **queries**
- [ ] Update `exposedVariables`: cardData
- [ ] Able to update/set column accent color from the column definition property
- [ ] Custom Card popover: expose data with `On Event selected`

**Comment by alta-atc** [comment]
Wow! Thanks guys!
