### ISSUE TITLE
Reserve admin  and all-users group names

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#2824]
### What is the expected behaviour?
It should not able to create groups with reserved group names.

### What is the current behaviour?
It can create groups with reserved group names.

### How to reproduce the issue?

1. Go to manage groups.
2. Create a group with the name Admin.
3. Create a group with the name All users.

### Screenshots or Screencast

[Video](https://www.loom.com/share/242a1872584348e69be11a040e9936de)

**Comment by eyuelberga** [comment]
Can I work on this issue?
