### ISSUE TITLE
error on MySQL operations should be reported to the end user/designer

### ISSUE THREAD

**Issue by xiangz19** [ToolJet/ToolJet#2834]
### Environment

Docker

### What is the expected behaviour?

When there are errors during MySQL execution, the end user can't get feedback. 

### What is the current behaviour?

The error should be reported to the end user.

### How to reproduce the issue?

1. create a MySQL query which has excution errors, the error might be wrong table name,  null column insert, or even system errors(such as network connection issue)
2. The query will be executed successfully while reporting errors in console log.

### Why this needs to be fixed.
We can avoid some errors in design time, however for system errors, especially update/insert failures, we need to give the feedback to the end user. Otherwise, the user will continue to input more data and waste time.

And the error message is also very helpful in design time.

### Can you identify the location in the driver source code where the problem exists?
plugins/packages/MySQL/lib/index.ts

    try {
      result = await knexInstance.raw(query);
    } catch (err) {
      console.log(err);
    }

    return {
      status: 'ok',
      data: result[0],
    };

### Solution
For production mode, just report a general system error message.
For design mode, maybe report more detailed error message.

**Comment by xiangz19** [comment]
Just checked the code for Oracle DB:

    try {
       result = await knexInstance.raw(query);

       return {
        status: 'ok',
        data: result,
      };
     } catch (err) {
      throw err;
     }

It seems oracle db won't have the same issue.  But the code for PostgreSQL is the same as for MysQL, so PostgreSQL should have the same issue.

By the way, the plugins for all kinds of SQL databases are the same, the codes are duplidated.

**Comment by shivangT** [comment]
Hey @xiangz19 

We're looking into this issue actively and resolving this soon by segregating different types of error messages and only showing the ones which are helpful for the end user.

Thanks for the suggestion
