### ISSUE TITLE
Badge column type is always editable in table row regardless of the editable property

### ISSUE THREAD

**Issue by xiangz19** [ToolJet/ToolJet#2836]
### Environment
Docker

### What is the expected behaviour?
In a table, when a column of badge type is set non-editable, it should not be editable.

### What is the current behaviour?
Badge column type is always editable in table row regardless of the editable property

### Can you identify the location in the driver source code where the problem exists?
frontend/src/Editor/Components/Table/Table.jsx
no `column.isEditable` used in below code.

    case 'badge':
    case 'badges': {
            return (
              <div>
                <CustomSelect
                  options={columnOptions.selectOptions}
                  value={cellValue}
                  multiple={columnType === 'badges'}
                  onChange={(value) => {
                    handleCellValueChange(cell.row.index, column.key || column.name, value, cell.row.original);
                  }}
                />
              </div>
            );
     }

**Comment by shivangT** [comment]
Hey @xiangz19 
Are you trying to resolve this issue? Let us know.

Apologies for reaching out late. Thanks

**Comment by xiangz19** [comment]
@shivangT，Sorry, I'm not good at front end coding.

**Comment by shivangT** [comment]
Hello @xiangz19 
No worries, we will look into it and respond asap.
Thanks
