### ISSUE TITLE
While adding a new datasource show the count of elements in the modal window

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2841]
### Version Information
Latest

### Environment
Tooljet Cloud

### What is the expected behaviour?
Show count of datasource in the left sidebar filter menu

### What is the current behaviour?
The count of elements is not shown in the add a new datasource modal window

### How to reproduce the issue?

1. Click on add a new datasource
2. In the left sidebar observer the filters
3. Count is missing

### Screenshots or Screencast
Example UI: 

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/12490590/163774572-eb292627-3d52-48f0-8d88-38ee56011e7d.png">

### Any possible solutions?
Add count as shown in screenshot

**Comment by eyuelberga** [comment]
Can I help out with this?
