### ISSUE TITLE
When requesting for a unavailable datasource nothing happens

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2842]
### Version Information
Latest

### Environment
Tooljet Cloud

### What is the expected behaviour?
An action should be triggered to capture a users requested datasource

### What is the current behaviour?
Requested datasource is not captured

### How to reproduce the issue?

1. Open add a new datasource
2. Search for a datasource which is not available
3. Click on send

### Screenshots or Screencast
<img width="765" alt="Screenshot 2022-04-18 at 2 11 52 PM" src="https://user-images.githubusercontent.com/12490590/163779167-d48f81aa-a94f-46bb-9564-5bb2aec309f4.png">

### Please provide any traces or logs that could help here.
Code can be found [here](https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/Editor/DataSourceManager/DataSourceManager.jsx#L699)

**Comment by tanmoyopenroot** [comment]
Hey @gondar00 ,
Can you tell me about the flow like on `clicking` on `send` what should happen?
