### ISSUE TITLE
Remove user adding dropdown on All-Users page.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#2845]
### Is your proposal related to a problem?

The dropdown list is not required on the All Users page.

**Comment by ajith-k-v** [comment]
[Video](https://www.loom.com/share/d3de6c18527546b4adf1bb7ef0a931d0)

**Comment by Syed-Ansar** [comment]
Hey @ajith-k-v can you assign me this issue.

**Comment by ajith-k-v** [comment]
Hey @Syed-Ansar, Assigned the issue to you.

**Comment by Syed-Ansar** [comment]
Hey @ajith-k-v and @sherfin94 Thank you for assigning me this issue but I couldn't raise PR until my semester exams end.
