### ISSUE TITLE
New widget: Color picker

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#2850]
### Is your proposal related to a problem?

There is no comfortable way to allow app users to select a color at present.
### Describe the solution you'd like

Add a color picker widget. This should be identical to the color pickers displayed on the style section of widget inspector.

<img width="190" alt="image" src="https://user-images.githubusercontent.com/20333972/163854928-bb3189bc-98c4-496a-afd8-e8138697c9ab.png">

- It should have a `Default color` property
- It should expose a variable named `selectedColor`, this should contain the hex code of the color that is selected on the color picker.

**Comment by withshubh** [comment]
https://github.com/ToolJet/ToolJet/pull/3274
