### ISSUE TITLE
Disable home page scrolling

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#2860]
### Environment
Latest Development branch

### What is the expected behaviour?
Scroll should be disabled

### What is the current behaviour?
Scroll is enabled

### How to reproduce the issue?
1. Login
2. Scroll is enabled in home page

### Screenshots or Screencast
https://www.loom.com/share/5a8fcb619b634c10b1ee0f6adc0e9510

### Any possible solutions?
Fix the height and disable scroll

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by kenleyshaw** [comment]
Can I possibly work on this issue?

**Comment by gsmithun4** [comment]
> Can I possibly work on this issue?

Sure, assigning to you

**Comment by kenleyshaw** [comment]
thanks! I am somewhat new to open source, so once I create a new feature branch and edit the code, how would I test to see  if it works?

**Comment by kenleyshaw** [comment]
sorry, just read the contributing guide on the docs so I will follow that

**Comment by withshubh** [comment]
Hey @kenleyshaw 
Any updates on the issue?

**Comment by withshubh** [comment]
Hey @kenleyshaw 
Please let us know if you're working on this issue?

**Comment by kenleyshaw** [comment]
not anymore @withshubh was having trouble with it.

**Comment by Syed-Ansar** [comment]
Hey @gsmithun4 I have solved issue can I push or commit it with another PR which closes along with this issue.

**Comment by withshubh** [comment]
Hey @Syed-Ansar 
Assigned this issue to you.

**Comment by Syed-Ansar** [comment]
Hey @withshubh Can you review my PR. #3395

**Comment by withshubh** [comment]
> Hey @withshubh Can you review my PR. #3395

Be patient 😃 A team member will review the PR soon.

**Comment by Syed-Ansar** [comment]
> > Hey @withshubh Can you review my PR. #3395
> 
> Be patient 😃 A team member will review the PR soon.

😅 I have commented to inform that's it.

**Comment by exitflynn** [comment]
Hi can I work on this issue? I am already making my way through #3630, and I feel like working with this one (which i feel is a little more on the lighter side) would be a more hands-on way to get me familiar and comfortable with the codebase, and in a way which would end up productive for the repo too. I'll completely understand if your answer is no and contributors can't work on more than one issue at a given time :cowboy_hat_face:

**Comment by withshubh** [comment]
> Hi @withshubh can I work on this issue? I am already making my way through #3630, and I feel like working with this one (which i feel is a little more on the lighter side) would be a more hands-on way to get me familiar and comfortable with the codebase, and in a way which would end up productive for the repo too. I'll completely understand if your answer is no and contributors can't work on more than one issue at a given time 🤠

Hey @exitflynn Please create the PR for the issue that is already assigned to you. We can then move to another issue.

**Comment by AyushK-101** [comment]
I would like to work on this if the issue is still unresolved @withshubh

**Comment by withshubh** [comment]
> I would like to work on this if the issue is still unresolved @withshubh

Hey @AyushK-101 

Assigned it to you.

**Comment by AyushK-101** [comment]
@kavinvenkatachalam @withshubh made a PR regarding the issue, please review and suggest changes, if any
