### ISSUE TITLE
Show proper error message while creating user group with existing group name

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#2863]
### Environment
Latest development branch

### What is the expected behaviour?
Should show `Group name already exist` error message

### What is the current behaviour?
Showing `duplicate key value violates unique constraint "UQ_9cb4cc225c96246e4d1b2e614bf"`

### How to reproduce the issue?
1. Go to manage groups
2. try to create group with existing group name

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by tanmoyopenroot** [comment]
Hey @gsmithun4 , Gonna pick this up today.
