### ISSUE TITLE
Add data source - postgress icon position

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#2865]
### Environment
Latest development branch

### What is the expected behaviour?
Icon should be vertically centre

### What is the current behaviour?
icon is aligned at top

### How to reproduce the issue?
1. open an app
2. select add data source
3. select postgres
4. observe icon position

### Screenshots or Screencast
<img width="762" alt="Screenshot 2022-04-19 at 8 09 16 PM" src="https://user-images.githubusercontent.com/3417097/164031259-310537a5-3379-4bec-8202-f1fe34346e70.png">

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by manjunath00** [comment]
Hi Can you assign this to me @gsmithun4

**Comment by withshubh** [comment]
Hey @manjunath00 
Any update on this issue?

**Comment by withshubh** [comment]
Hey @manjunath00 
Please let us know if you're working on this issue?

**Comment by manjunath00** [comment]
No, due to time constraints 
Regret the delay in informing

**Comment by TheLearneer** [comment]
Hi there,
I can work on it if it's up for grabs.

**Comment by withshubh** [comment]
Sure @TheLearneer 
Assigned this to you
