### ISSUE TITLE
Unwanted metadata API call on logout

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#2871]
### Version Information
development branch

### What is the expected behaviour?
Should not call metadata API call on logout

### What is the current behaviour?
calling metadata API and throwing unauthorised error 

### How to reproduce the issue?
1. Login
2. Logout
3. check the console

### Screenshots or Screencast
https://www.loom.com/share/e73f6f7e04ff45d9ae79d53b55b89fb4

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by withshubh** [comment]
This issue is up for grabs.
