### ISSUE TITLE
Add cmd+c shortcut to clone component

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2872]
### Environment
TJ Cloud

### What is the expected behaviour?
Component should clone on keyboard shortcut `cmd+c`

### What is the current behaviour?
Component is cloning on keyboard shortcut `cmd+d`

### How to reproduce the issue?

1. Open Inspector of a component
2. Press cmd+c 
3. Component is not cloned

### Any possible solutions?
Add cmd+c shortcut to keyboard shortcut modifier list

### Can you identify the location in the driver source code where the problem exists?
Yes

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by shivangT** [comment]
Merged: Confirmed by gandharv
