### ISSUE TITLE
Include padding style for dropdown widget 

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#2878]
### Is your proposal related to a problem?
Currently  no option  to include padding for dropdown.

### Describe the solution you'd like
Add padding style for dropdown widget.

### Describe alternatives you've considered
Other styles can also be included. 

### If the feature is approved, would you be willing to submit a PR?
No.

**Comment by rahulsunil2** [comment]
@stepinfwd I would love to work on this issue.

**Comment by stepinfwd** [comment]
closing this as it doesn't  exist now
