### ISSUE TITLE
View of widgets on mobile and desktop not matching.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#2884]
### What is the expected behaviour?
The widget size and alignment should be the same on both desktop and mobile.
### What is the current behaviour?
The widget size and alignment are different
### How to reproduce the issue?

1. Click on Create new application.
2. Drag and drop the button widget and enable Show on mobile from the layout.
3. Click on Mobile on the topbar.

### Screenshots or Screencast
[Video](https://www.loom.com/share/217920f7350e487ea2b4121d4f9a0196)

**Comment by GrowwithNaveen** [comment]
Similar bug reported: [Editor: View of widgets on mobile and desktop not matching.](https://github.com/ToolJet/ToolJet/issues/790)

**Comment by ajith-k-v** [comment]
Closing this issue since it no longer exists
