### ISSUE TITLE
Hide action options section if there are no options associated 

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#2888]
Steps to reproduce: 
1) Create a new application
2) Add a button widget 
3) Go to events section of the widget inspector 
4) Add a "logout" event 
5) "Action options" section title is shown even though there aren't any options.

![image](https://user-images.githubusercontent.com/7828962/164844260-5939a9aa-2d78-44b8-9b80-f849e97f1e2c.png)

**Comment by eyuelberga** [comment]
Hi @Navaneeth-pk  can I work on this?

**Comment by eyuelberga** [comment]
@Navaneeth-pk I have a fix for this, can I send a PR?

**Comment by withshubh** [comment]
Hey @eyuelberga 
Assigning this issue to you.
