### ISSUE TITLE
[docs]: list missing tutorial in complete tutorials section

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2891]
### Summary

The [Complete tutorials](https://docs.tooljet.com/docs/intro#complete-tutorials) section in the Intro page of docs is missing the recently published tutorial in the [blogs](https://blog.tooljet.com/).

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/intro

### Solution
- Edit the `intro.md` file in docs
- Add the link for the missing tutorial [Build a coupon code manager app](https://blog.tooljet.com/build-a-coupon-code-manager-app-in-10-minutes/)

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Mount-Blanc** [comment]
Hello, I would like to work on this issue.

**Comment by withshubh** [comment]
Hey @Mount-Blanc 
Assigned this issue to you.

**Comment by withshubh** [comment]
Fixed in #3015
