### ISSUE TITLE
[docs]: fix typo in GitHub and Google(SSO) docs

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2892]
### Summary

- The first point in both the docs (GitHub and Google SSO) starts with `Goto` instead it should be `Go to the`
![Screenshot 2022-04-24 at 2 44 57 PM](https://user-images.githubusercontent.com/25361949/164969387-dc96a4c0-ac86-4eb5-a31e-bc5ef4225ace.png)
- Use markdown to make all the steps bullet list.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/sso/github , https://docs.tooljet.com/docs/sso/google

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by gauravagrwal** [comment]
please assign it to me
