### ISSUE TITLE
[docs]: list of supported operations missing in GCS docs

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2893]
### Summary

GCS data source docs are missing the list of available operations. Create a section `Supported operations`(h2 heading) and add a bullet list for available operations.

![Screenshot 2022-04-24 at 3 06 16 PM](https://user-images.githubusercontent.com/25361949/164970116-26acaa6a-30f9-4b9d-9ec1-4119e1303859.png)

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/gcs

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Mount-Blanc** [comment]
I would like to work on this issue.
