### ISSUE TITLE
[docs]: list of supported operations missing in MinIO docs 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2894]
### Summary

MinIO data source docs are missing the list of available operations. Create a section `Supported operations` (h2 heading) and add a bullet list for available operations.

![Screenshot 2022-04-24 at 3 12 09 PM](https://user-images.githubusercontent.com/25361949/164970292-6b806205-ff3d-4e62-ad30-75b200111b28.png)

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/minio

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Mount-Blanc** [comment]
Hello, I would like to work on this issue.

**Comment by withshubh** [comment]
Hey @Mount-Blanc 
Assigned this to you.
