### ISSUE TITLE
[docs]: add gifs for keyboard shortcuts

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2895]
### Summary

Currently, the doc for keyboard shortcuts is text only. The doc needs gifs for every shortcut available to show shortcuts in action.

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/tutorial/keyboard-shortcuts

### Solution
- Create gif for every [Shortcut](https://docs.tooljet.com/docs/tutorial/keyboard-shortcuts). 
- Create a folder `keyboard-shortcuts` in `static/img/tutorial` and put the gifs inside the folder
- Add gifs using markdown in tutorial/`keyboard-shortcuts.md`

Example snippet:
```
<div style={{textAlign: 'center'}}>

![ToolJet - Tutorial - Undo keyboard shortcut](/img/tutorial/keyboard-shortcuts/undo.gif)

</div>
```

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by TriJayDore** [comment]
I would like to contribute please assign under my name

**Comment by kaggrwal** [comment]
@withshubh Can you assign this issue to me ?

**Comment by iamakhileshmishra** [comment]
I would love to contribute in this issue please assign this to me.

**Comment by withshubh** [comment]
Hey @TriJayDore 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hi @kaggrwal and @iamakhileshmishra 👋  

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by Smartmind12** [comment]
@withshubh Can i work on the issue if TriJayDore is not working on it since 9 days have passed and no commits have been published yet?

**Comment by withshubh** [comment]
Hey @TriJayDore 👋 

Any updates on the PR?

**Comment by ArmanChand** [comment]
@withshubh ,
Please validate my PR. It been a while now no one is working on it.

**Comment by withshubh** [comment]
> @withshubh , Please validate my PR. It been a while now no one is working on it.

Hey @ArmanChand 

I checked your PR and here's my review:
- You only added `undo` but the issue is for all the shortcuts mentioned in the doc
- By `adding gif` I mean the create gifs showing all the keyboard shortcuts in action in ToolJet. You have added some random gif.

**Comment by withshubh** [comment]
Hey @TriJayDore 👋 
Please let us know if you're still working on the PR. If not, we will have to assign it to another contributor.

**Comment by Smartmind12** [comment]
@withshubh Since I am in line waiting for this issue to be assigned so please assign it to me... @ArmanChand Please donot create PR without the issue being assigned to you and please wait in line for your turn! Thanks!!

**Comment by TriJayDore** [comment]
Sorry I couldn't work on this.Please assign to others.On 15-Oct-2022 1:13 am, Shubhendra Singh Chauhan ***@***.***> wrote:

Hey @TriJayDore 👋

Please let us know if you're still working on the PR. If not, we will have to assign it to another contributor.

**Comment by Smartmind12** [comment]
@withshubh Can you please assign this issue to me so that i can create the PR for the same ...Thanks!

**Comment by Smartmind12** [comment]
> > @withshubh Can you please assign this issue to me so that i can create the PR for the same ...Thanks!
> 
> Hey @Smartmind12 - An issue is assigned to you.

I have already created a PR for the previous issue...I would like to work on this next!

**Comment by iamakhileshmishra** [comment]
@withshubh  If the issue still not resolved I would like to work on this issue please assign this to me.

**Comment by withshubh** [comment]
> @withshubh If the issue still not resolved I would like to work on this issue please assign this to me.

Assigned to you

**Comment by iamakhileshmishra** [comment]
> 

As mentioned in SOlution Section I need to clarify one thing am I supposed to create a gif from my own for each shortcut?
If it is so then could you please provide me with some demos from which I can take reference? @withshubh

**Comment by withshubh** [comment]
> > 
> 
> As mentioned in SOlution Section I need to clarify one thing am I supposed to create a gif from my own for each shortcut? If it is so then could you please provide me with some demos from which I can take reference? @withshubh

@iamakhileshmishra - Yes, you are correct. Just need to create small gifs showing the shortcuts in action.
check this: https://docs.tooljet.com/img/tutorial/sharing/preview.gif

**Comment by iamakhileshmishra** [comment]
> > > 
> > 
> > 
> > As mentioned in SOlution Section I need to clarify one thing am I supposed to create a gif from my own for each shortcut? If it is so then could you please provide me with some demos from which I can take reference? @withshubh
> 
> @iamakhileshmishra - Yes, you are correct. Just need to create small gifs showing the shortcuts in action. check this: https://docs.tooljet.com/img/tutorial/sharing/preview.gif


Ok got it... but the link you shared has an option on the preview on screen in the present issue I have to press Ctrl+C, Ctrl+V, Ctrl+Z, etc from the keyboard and their effects will be shown on the screen so my question is that that I have to show only the changes occurring in the screen.

In a short time I will be sharing a demo gif could you please confirm you need such a type so that I can proceed with the others?

**Comment by withshubh** [comment]
> > > > 
> > > 
> > > 
> > > As mentioned in SOlution Section I need to clarify one thing am I supposed to create a gif from my own for each shortcut? If it is so then could you please provide me with some demos from which I can take reference? @withshubh
> > 
> > 
> > @iamakhileshmishra - Yes, you are correct. Just need to create small gifs showing the shortcuts in action. check this: [docs.tooljet.com/img/tutorial/sharing/preview.gif](https://docs.tooljet.com/img/tutorial/sharing/preview.gif)
> 
> Ok got it... but the link you shared has an option on the preview on screen in the present issue I have to press Ctrl+C, Ctrl+V, Ctrl+Z, etc from the keyboard and their effects will be shown on the screen so my question is that that I have to show only the changes occurring in the screen.
> 
> In a short time I will be sharing a demo gif could you please confirm you need such a type so that I can proceed with the others?

Sure!

**Comment by iamakhileshmishra** [comment]
> > > > > 
> > > > 
> > > > 
> > > > As mentioned in SOlution Section I need to clarify one thing am I supposed to create a gif from my own for each shortcut? If it is so then could you please provide me with some demos from which I can take reference? @withshubh
> > > 
> > > 
> > > @iamakhileshmishra - Yes, you are correct. Just need to create small gifs showing the shortcuts in action. check this: [docs.tooljet.com/img/tutorial/sharing/preview.gif](https://docs.tooljet.com/img/tutorial/sharing/preview.gif)
> > 
> > 
> > Ok got it... but the link you shared has an option on the preview on screen in the present issue I have to press Ctrl+C, Ctrl+V, Ctrl+Z, etc from the keyboard and their effects will be shown on the screen so my question is that that I have to show only the changes occurring in the screen.
> > In a short time I will be sharing a demo gif could you please confirm you need such a type so that I can proceed with the others?
> 
> Sure!

![Ctrl+C](https://user-images.githubusercontent.com/79476272/198554988-b9de772a-4026-4182-bfde-7e7978f66f28.gif)

**Comment by withshubh** [comment]
- Please capture the full screen
- Use the Giphy Capture app to create gif

**Comment by iamakhileshmishra** [comment]
> * Please capture the full screen
> * Use the Giphy Capture app to create gif

Ok, I am considering apart from these there is no issue. Like I have to create this type of GIF right?

**Comment by withshubh** [comment]
> > * Please capture the full screen
> > * Use the Giphy Capture app to create gif
> 
> Ok, I am considering apart from these there is no issue. Like I have to create this type of GIF right?
> 
> Btw Gipgy Capture is not available for windows there is Mac version only that I am getting can you please provide link or any alternatives.

Yeah, you can go ahead. Create the PR, will review and let you know if any change will be there.

**Comment by iamakhileshmishra** [comment]
@withshubh I have made a PR please check it .

**Comment by iamakhileshmishra** [comment]
@withshubh  Please accept my PR if there is no issue and if some changes required please let me know so that I can reform it soon as there is festive season and also Hacktoberfest is going to end.
