### ISSUE TITLE
Remove Apps adding dropdown on Admin group page.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#2902]
### Is your proposal related to a problem?
The app dropdown list is not required on the admin group page, since admin has all access to all apps

### Describe the solution you'd like
Remove the apps selection dropdown.

### If the feature is approved, would you be willing to submit a PR?
No

**Comment by ajith-k-v** [comment]
[Video](https://www.loom.com/share/d21ba6b777754898927c2ce0f5d7ce5a)

**Comment by withshubh** [comment]
Duplicate issue of #2634
