### ISSUE TITLE
Able to add the same application in a folder multiple times.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#2916]
### Version Information
all versions

### What is the expected behaviour?
Should not be able to add the same application in a folder multiple times.

### What is the current behaviour?
Able to add the same application in a folder multiple times

### How to reproduce the issue?
1. Add an app to a folder
2. Add it again
3. Observe the app count of folders are increasing 

### Screenshots or Screencast
[Video](https://www.loom.com/share/cb94c69231ac4bbaa889bed93d19b6f0)

### Any possible solutions?
Back-end validation if app exists in folder

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by asprazz** [comment]
Hi @gsmithun4 @ajith-k-v , I would like to work on this issue, if its oke?
