### ISSUE TITLE
Bulk update operation for MS SQL Server

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2927]
### Is your proposal related to a problem?

Currently, making bulk updates to the MS SQL server needs to write custom js for looping through the changed rows. This leads to creating extra queries and might be difficult for non-tech users.

### Describe the solution you'd like

Adding a bulk update operation for MS SQL Server might solve the issue.

**Comment by GuilhemDel** [comment]
Hi @withshubh ,
Would you mind sharing what kind of custom js you put in place to make the bulk update work, priori to it being added as a feature to the GUI?
Trying to replicate that on a Google BigQuery source, where the GUI does not offer the bulk update operation.
Thanks in advance!
