### ISSUE TITLE
Show spinner while verifying slug uniqueness

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#293]
![image](https://user-images.githubusercontent.com/7828962/122970515-a8375900-d3ab-11eb-8482-80c493f4ce9b.png)

We should show a loading spinner inside the input field while the slug uniqueness verification request is in progress.

**Comment by prasadwalvekar** [comment]
Picking this up.

**Comment by Navaneeth-pk** [comment]
Fixed in #315
