### ISSUE TITLE
initial account password is wrong 

### ISSUE THREAD

**Issue by coutouly** [ToolJet/ToolJet#2930]
voir issue : #2663
what is the good password ?

**Comment by coutouly** [comment]
so i try and it didn't succeed.
i use the docker-compose.yml for production . is it why it failed ?

**Comment by Navaneeth-pk** [comment]
@coutouly can you please share the guide that you followed to setup on production?

**Comment by coutouly** [comment]
i try this setup:
https://docs.tooljet.com/docs/setup/docker
with this choice
For PostgreSQL database setup with persistent volume:
`curl -LO https://raw.githubusercontent.com/ToolJet/ToolJet/main/deploy/docker/docker-compose-postgres.yaml
mv docker-compose-postgres.yaml docker-compose.yaml
mkdir postgres_data`
