### ISSUE TITLE
Docusaurus default redirect issue

### ISSUE THREAD

**Issue by siddharth2798** [ToolJet/ToolJet#2932]
### Environment
Hosted docs

### What is the expected behaviour?
When trying to reach a invalid URL in the documentation, the redirect to https://docs.tooljet.com/docs/intro should happen
### What is the current behaviour?
The URL in the docs keep recursively calling /docs/intro if pointed to an unavailable URL. 
### How to reproduce the issue?
Visit any of the links mentioned below and watch the URL change
1. https://docs.tooljet.com/docs/data-sources
2. https://docs.tooljet.com/docs/widgets/

### Screenshots or Screencast

https://user-images.githubusercontent.com/26953573/165904435-6cc3df66-1fd8-4f81-b4f5-01eacf0810d8.mp4

### Any possible solutions?
Unsure of the exact solution but has to be something with the default redirect URL in the docusaurus config. 

### Can you identify the location in the driver source code where the problem exists?
Not Sure

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by Ajal333** [comment]
Yeah, even I faced the same issue.

**Comment by timagixe** [comment]
@Navaneeth-pk hello, I would like to work on this bug 🤚
