### ISSUE TITLE
 cannot load a node-oracledb binary for Node.js

### ISSUE THREAD

**Issue by kanishkpuri1987** [ToolJet/ToolJet#2966]
### Environment
Docker Windows

### What is the expected behaviour?
when I run this command docker-compose run --rm server npm run db:seed . I am getting this error

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/30067441/166647372-ad1fb63c-1ff4-4b15-a1df-3445e5377790.png)

### Please provide any traces or logs that could help here.
C:\tooljet\tooljet>docker-compose run --rm server npm run db:seed
[+] Running 1/0
 - Container tooljet-postgres-1  Running                                                                           0.0s
[+] Running 1/1
 - Container tooljet-server-1  Started                                                                             1.2s

> db:create
> npm --prefix server run db:create

> server@0.0.1 db:create
> ts-node ./scripts/create-database.ts

database "tooljet_development1" already exists

> db:migrate
> npm --prefix server run db:migrate

> server@0.0.1 db:migrate
> ts-node -r tsconfig-paths/register --transpile-only ./node_modules/typeorm/cli.js migration:run

query: SELECT * FROM current_schema()
Error during migration run:
Error: NJS-045: cannot load a node-oracledb binary for Node.js 14.17.3 (linux x64)
  Node.js require('oracledb') error was:
  /app/plugins/node_modules/oracledb/build/Release/oracledb.node: invalid ELF header
  Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle Client libraries configured with ldconfig, or in LD_LIBRARY_PATH.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html

    at Object.<anonymous> (/app/plugins/node_modules/oracledb/lib/oracledb.js:88:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .js] (/app/server/node_modules/ts-node/src/index.ts:1286:43)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/plugins/node_modules/oracledb/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

**Comment by withshubh** [comment]
@akshaysasidrn Can you please take a look at this issue

**Comment by shivangT** [comment]
Hey @kanishkpuri1987 
Are you still trying to resolve this issue? Kindly let us know, and we'll fix this for you on priority.

Thanks and apologies for replying late.

**Comment by akshaysasidrn** [comment]
This has been fixed.
