### ISSUE TITLE
Able to create group name with system group names

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#2969]
### Version Information
all versions

### What is the expected behaviour?
Should not allow to create group name with `Admin` and `All Users` since they are reserved for system groups

### What is the current behaviour?
Able to create 

### How to reproduce the issue?
1. Try to create group with name `Admin`
2. Group will be created

### Screenshots or Screencast
<img width="544" alt="Screenshot 2022-05-04 at 4 52 37 PM" src="https://user-images.githubusercontent.com/3417097/166672090-bfb06cb4-a5ba-45c6-ad0f-df7e466ad4d8.png">

### Any possible solutions?
Restrict both group names in back end 

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by tanmoyopenroot** [comment]
Hey @gsmithun4 , Gonna pick this up today.
