### ISSUE TITLE
[docs]: fix hyperlink of ToolJet logo in the navbar

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2974]
### Summary

We recently made some updated in the documentation and updated the landing page URL of documentation to https://docs.tooljet.com/docs/ from https://docs.tooljet.com/docs/intro 

But the hyperlink on the ToolJet logo in the navbar still redirects to the old URL i.e docs/intro

To fix this issue a very change is required.

#### Solution
- Open `docusauras.config.js` in the root of the docs
- On line number 36, you'll find the href for the logo
- just make it `/docs` from `/docs/intro`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Wilson-Ramos** [comment]
Hello, I would like to work on this issue.

**Comment by Navaneeth-pk** [comment]
@Wilson-Ramos assigned to you. Thanks for contributing to ToolJet.
