### ISSUE TITLE
Fix typo in the operation for Notion data source

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#2975]
### Environment

ToolJet Cloud

### How to reproduce the issue?

1. Connect Notion data source
2. Create a query from the query panel
3. Select Notion data source
4. Choose `Database`from the dropdown for Resource
5. You'll see that the database in the `Create Database` operation starts with capital D instead it should be in lowercase like other operations

### Screenshots or Screencast

![Screenshot 2022-05-04 at 11 59 21 PM](https://user-images.githubusercontent.com/25361949/166803339-6af33053-60c6-4434-ae4b-257d7f46d420.png)

**Comment by mazkaaa** [comment]
Hi @withshubh!
I'd like to work on this issue, can you assign it to me?

Thanks!

**Comment by withshubh** [comment]
Hey @mazkaaa 
Awesome! Assigning this issue to you. 🚀

**Comment by mazkaaa** [comment]
Working on it👌

**Comment by mazkaaa** [comment]
Hi @withshubh,

I'm getting an error on my server watch mode when I open the localhost:8082 address on my browser.

![image](https://user-images.githubusercontent.com/5271698/167243915-024c3c9e-ba6a-4a5d-9714-ad37ce9c4ff4.png)


this is the response on the browser

![image](https://user-images.githubusercontent.com/5271698/167243999-5eff658e-4573-47cd-90fe-85d6c449f30b.png)

I'm running the ToolJet app in my ubuntu WSL2, node v14.17.3, and npm 7.20.0.

any idea?

**Comment by mazkaaa** [comment]
> > Hi @withshubh,
> > I'm getting an error on my server watch mode when I open the localhost:8082 address on my browser.
> > ![image](https://user-images.githubusercontent.com/5271698/167243915-024c3c9e-ba6a-4a5d-9714-ad37ce9c4ff4.png)
> > this is the response on the browser
> > ![image](https://user-images.githubusercontent.com/5271698/167243999-5eff658e-4573-47cd-90fe-85d6c449f30b.png)
> > I'm running the ToolJet app in my ubuntu WSL2, node v14.17.3, and npm 7.20.0.
> > any idea?
> 
> Please seed data to db
> 
> ```
> docker-compose run server npm run db:seed
> ```

ahh thank you its working now by running the db:seed command. But i'm using non docker btw because docker resulting an error `Unsupported config option for services.client: 'platform' docker-compose` when running `docker-compose up` command.

**Comment by gsmithun4** [comment]
> > > Hi @withshubh,
> > > I'm getting an error on my server watch mode when I open the localhost:8082 address on my browser.
> > > ![image](https://user-images.githubusercontent.com/5271698/167243915-024c3c9e-ba6a-4a5d-9714-ad37ce9c4ff4.png)
> > > this is the response on the browser
> > > ![image](https://user-images.githubusercontent.com/5271698/167243999-5eff658e-4573-47cd-90fe-85d6c449f30b.png)
> > > I'm running the ToolJet app in my ubuntu WSL2, node v14.17.3, and npm 7.20.0.
> > > any idea?
> > 
> > 
> > Please seed data to db
> > ```
> > docker-compose run server npm run db:seed
> > ```
> 
> ahh thank you its working now by running the db:seed command. But i'm using non docker btw because docker resulting an error `Unsupported config option for services.client: 'platform' docker-compose` when running `docker-compose up` command.

If you are not using docker
- go to `/server`
- execute `npm run db:seed`
