### ISSUE TITLE
script to disable Action-button in Table

### ISSUE THREAD

**Issue by HFolkertH** [ToolJet/ToolJet#2987]
### Is your proposal related to a problem?

There is no option for disabling the Action button in the table.

### Describe the solution you'd like

Add a Disable option for programmatically disabling the button.

**Comment by withshubh** [comment]
Hey @HFolkertH 👋 
We are looking into the issue and will update you soon.

**Comment by prateek-1606** [comment]
Hey @withshubh , i would like to work on this issue by creating an option to disable an action button. can you assign it to me ?.
Thanks

**Comment by withshubh** [comment]
> Hey @withshubh , i would like to work on this issue by creating an option to disable an action button. can you assign it to me ?. Thanks

Hey @prateek-1606 
Sorry but a team member has already submitted a PR for this #4341 
Please pick any other open issue.

**Comment by shubh22** [comment]
This is available in v2.3.0
