### ISSUE TITLE
error instalation

### ISSUE THREAD

**Issue by joaoguariglia** [ToolJet/ToolJet#2990]
### Version Information
Last version
Linux
I'm trying to install on a Linux 20.04 but when opening the front-end the screen goes white and nothing happens

when starting
$ cd ./frontend && npm start
nothing happens

### How to reproduce the issue?

`#` nano /etc/sysctl.conf
fs.inotify.max_user_watches=524288
`#` reboot

`#` curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
`#` cat /etc/apt/sources.list.d/nodesource.list
`#` apt -y install nodejs
`#` node  -v
`#` apt -y install gcc g++ make
`#` curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
`#` echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
`#` apt update && apt install yarn
`#` npm i -g npm@7.20.0
`#` apt install postgresql postgresql-contrib
`#` apt-get install libpq-dev
user:(suporte)
`$` sudo -u postgres createuser -P --interactive

Enter name of role to add: tooljet
Shall the new role be a superuser? (y/n) y
`$`  sudo adduser tooljet
pass: tooljet
`$`  sudo -u tooljet createdb tooljet

`$`  git clone https://github.com/ToolJet/ToolJet
`$` $ cd ToolJet
`$`  cp .env.example .env
`$`  openssl rand -hex 64 (SECRET_KEY_BASE)
`$`  openssl rand -hex 32 (LOCKBOX_MASTER_KEY)
`$`  nano .env (inserir as chaves geradas)

LOCKBOX_MASTER_KEY=
SECRET_KEY_BASE=

ORM_LOGGING=
PG_DB=tooljet
PG_USER=tooljet
PG_HOST=localhost
PG_PASS=tooljet

`$`  npm install
`$`  npm install --prefix server
`$`  npm install --prefix frontend
`$`  npm run build:plugins
`$`  npm run --prefix server db:reset
(sessão ssh1)
`$`  cd ToolJet
`$`  cd ./plugins && npm start 
(sessão ssh2)
`$`  cd ToolJet
`$` cd ./server && npm run start:dev 
(sessão ssh3) 
`$`  cd ToolJet
`$`  cd ./frontend && npm start

WEB: http://xxx.xxx.xxx:8082/

**Comment by akshaysasidrn** [comment]
@joaoguariglia Could you share if there is any error thrown on the browser console or if any API call is failing from the browser network tab? It'll help to debug.

**Comment by mazkaaa** [comment]
@akshaysasidrn I think my error is related to this issue.

Here is the issue link address: https://github.com/ToolJet/ToolJet/issues/2975#issuecomment-1120156547
