### ISSUE TITLE
SSO options on the Manage SSO page should be visible in dark mode.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#2997]
### What is the expected behaviour?

The SSO options on the Manage SSO page should be visible in dark mode.

### What is the current behaviour?

The SSO options on the Manage SSO page are not clearly visible in dark mode.

### Screenshots or Screencast

[Video](https://www.loom.com/share/365560270beb479ca3bddaf651eacc04)
### Any possible solutions?
Fix the css in dark mode

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by ganeshmani** [comment]
Hey, I would like to work on this issue.

**Comment by withshubh** [comment]
Hey @ganeshmani 
Assigned it to you

**Comment by withshubh** [comment]
Hey @ganeshmani 👋 
Are you still working on this issue?

**Comment by ganeshmani** [comment]
@withshubh yeah, i will create a PR soon.

**Comment by withshubh** [comment]
Thanks for the update.

**Comment by manishkushare** [comment]
This issue no longer exists in the current version - v1.23.1
<img width="1352" alt="Screenshot 2022-08-29 at 3 45 48 PM" src="https://user-images.githubusercontent.com/37823141/187179187-1b020d1a-d361-4935-a681-165ebddee0af.png">
