### ISSUE TITLE
Provide a way to get count of users across groups

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#2998]
### Is your proposal related to a problem?

Presently there is no way to know the total number of users, or the number of users inside one or more groups.

### Describe the solution you'd like

Provide a filter for groups in the user management page, and display the total number of users on application of the filter.

**Comment by prateek-1606** [comment]
Hi @sherfin94 . i would like to work on this if any one can confirm this feature. 
Thanks
