### ISSUE TITLE
Add info icons for maintenance mode, max height of canvas features

### ISSUE THREAD

**Issue by shah21** [ToolJet/ToolJet#3009]
### Is your proposal related to a problem?

<img width="349" alt="167352317-61e36208-5fa7-40d8-8b6c-798ac7f23ccb" src="https://user-images.githubusercontent.com/18279004/167374919-3d1e3ab3-d136-4b41-a8a7-862078c9d9f6.png">

![Screenshot 2022-05-09 at 2 26 30 PM](https://user-images.githubusercontent.com/18279004/167375995-3e171fe6-ec0c-4129-b2bb-c32af614c841.png)

Currently, maintenance mode & canvas height features don't have an info icon to describe the feature

### Describe the solution you'd like

Add an info icon beside the texts and show a short description of the particular option. 
like, 
for **maximum canvas height** "max height is 2400px"

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
No

**Comment by prasanta10** [comment]
Can i work on this issue?

**Comment by shah21** [comment]
> Can i work on this issue?

Yes

**Comment by shubh22** [comment]
Will handle this separately in the UI redesign. Closing this for now.
