### ISSUE TITLE
Hide user details from get applications API 

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#3030]
### Version Information
all versions

### What is the expected behaviour?
user's sensitive data should not be available in get apps API `[GET] /api/apps` API is called to list app in home page

### What is the current behaviour?
user's sensitive data is visible

### Screenshots or Screencast
<img width="1437" alt="Screenshot 2022-05-10 at 11 15 43 PM" src="https://user-images.githubusercontent.com/3417097/167691067-9371f1cc-b428-4e3e-a99d-b155f50f0794.png">

### Any possible solutions?
Empty the fields from back end
- email
- invitation_token
- forgot_password_token
- default_organization_id
- role
- created_at
- updated_at

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by gondar00** [comment]
Same issue observed for 

```
[GET] /api/threads/{appId}/all
[GET] /api/comments/{appId}/notifications
```

Note: Starting typeorm 0.3.0 now it's possible to specify select columns of the loaded relations instead of using query builder as required in 0.2.x:

```
userRepository.find({
    select: {
        id: true,
        firstName: true,
        lastName: true,
        photo: {
            id: true,
            filename: true,
            album: {
                id: true,
                name: true,
            }
        }
    }
})
```
ref: https://github.com/typeorm/typeorm/releases/tag/0.3.0
