### ISSUE TITLE
FX button misaligned with the corresponding text

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#3039]
### Version Information
Latest 
### Environment
TJ Cloud

### What is the expected behaviour?
FX button should align with the corresponding text

### What is the current behaviour?
FX button misaligned with the corresponding text

### How to reproduce the issue?

1. Dnd a table
2. Click on table to open the inspector
3. Observe the "fx" button alignment 

### Screenshots or Screencast
<img width="954" alt="image" src="https://user-images.githubusercontent.com/12490590/167852259-20740728-e4cf-4503-ac35-819a6f9fa95b.png">

**Comment by Mo7amedSMahdi** [comment]
I will work on the issue.

**Comment by withshubh** [comment]
Hey @Mo7amedSMahdi 👋 
Any updates on this issue?
