### ISSUE TITLE
Filepicker widget : Fix typo 

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#3047]
### Description

Current: `Pick mulitple files`

Expected: `Pick multiple files`

Reference: `frontend/src/Editor/Components/components.js -- Line 1255`
<img width="293" alt="Screenshot 2022-05-12 at 12 46 52 AM" src="https://user-images.githubusercontent.com/67645175/167928427-128b79b3-902b-47d5-a966-0dfacd597556.png">

**Comment by lewisyng** [comment]
Hey, I'd like to fix this for you :)

**Comment by arpitnath** [comment]
@lewisyng Hi, sure. Assigning the issue to you.

**Comment by lewisyng** [comment]
Fixed the typo

**Comment by withshubh** [comment]
Fixed in #3048
