### ISSUE TITLE
Widgets section disappears on click of undo button

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#3050]
### Version Information
latest

### Environment
latest develop

### What is the current behaviour?
Widget section disappears on click of undo button

### Screenshots or Screencast
https://www.loom.com/share/bd09ddcc00e548019d6ba1c2eafd0e4a

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by vedant-z** [comment]
Hi @gsmithun4 Sir, is this still open?
