### ISSUE TITLE
Tooljet is not deploying correctly on docker

### ISSUE THREAD

**Issue by PaulMcF1987** [ToolJet/ToolJet#3051]
I followed the setup instructions [here](https://docs.tooljet.com/docs/setup/docker)

Downloaded the YAML and edited to
`version: '3'`

`services:`
`  client:`
`    tty: true`
`    stdin_open: true`
`    image: tooljet/tooljet-client-ce:latest`
`    restart: always`
`    env_file: .env`
`    depends_on:`
`      - server`
`    volumes:`
`      - .logs:/var/log/openresty/`
`      - .certs:/etc/resty-auto-ssl/`
`      - .fallbackcerts:/etc/fallback-certs`
`    ports:`
`      - 9102:80`
`      - 9101:443`
`    command: openresty -g "daemon off;"`

`  server:`
`    image: tooljet/tooljet-server-ce:latest`
`    tty: true`
`    stdin_open: true`
`    restart: always`
`    ports:`
`      - 3000`
`    env_file: .env`
`    environment:`
`      SERVE_CLIENT: "false"`
`    command: npm run start:prod`
`    depends_on:`
`      - postgres`

`  postgres:`
`    image: postgres:13`
`    restart: always`
`    ports:`
`      - 5432:5432`
`    volumes:`
`      - .postgres:/var/lib/postgresql/data`
`   environment:`
`      - POSTGRES_PASSWORD=password`

I then edited the .env to
`TOOLJET_HOST=http://domainIP:9102`
`LOCKBOX_MASTER_KEY=replace_with_lockbox_master_key`
`SECRET_KEY_BASE=replace_with_secret_key_base`

`# DATABASE CONFIG`
`ORM_LOGGING=all`
`PG_DB=tooljet_production`
`PG_USER=user`
`PG_HOST=domainIP`
`PG_PASS=password

`# Checks every 24 hours to see if a new version of ToolJet is available`
`# (Enabled by default. Set 0 to disable)`
`CHECK_FOR_UPDATES=`

`# Checks every 24 hours to update app telemetry data to ToolJet hub.`
`# (Telemetry is enabled by default. Set value to true to disable.)`
`# DISABLE_APP_TELEMETRY=false`

I currently have 2 running containers
`tooljet/tooljet-client-ce:latest` and `tooljet/tooljet-server-ce:latest`

When I navigate to domainIP:9102 the tab at the top says `Tooljet Dashboard` but the screen is blank with nothing showing.

I ran the command
`docker-compose run server npm run db:seed` and also tried `docker-compose run server npm run db:seed --prefix server`

But I got a list of errors:

`> @ db:create /app`
`> npm --prefix server run db:create`

`> server@0.0.1 db:create /app/server`
`> ts-node ./scripts/create-database.ts`

`/app/.env file not found to create database`
`Picking up config from the environment`
`Error: Command failed: PGPASSWORD=password createdb -h domainIP -p 5432 -U user tooljet_production`
`createdb: could not connect to database template1: FATAL:  password authentication failed for user "user"`

`    at ChildProcess.exithandler (child_process.js:319:12)`
`    at ChildProcess.emit (events.js:375:28)`
`    at ChildProcess.emit (domain.js:470:12)`
`    at maybeClose (internal/child_process.js:1055:16)`
`    at Socket.<anonymous> (internal/child_process.js:441:11)`
`    at Socket.emit (events.js:375:28)`
`    at Socket.emit (domain.js:470:12)`
`    at Pipe.<anonymous> (net.js:675:12) {`
`  killed: false,`
`  code: 1,`
`  signal: null,`
`  cmd: 'PGPASSWORD=password createdb -h domainIP -p 5432 -U user tooljet_production'`
`}`

`> @ db:migrate /app`
`> npm --prefix server run db:migrate`

`> server@0.0.1 db:migrate /app/server`
`> ts-node -r tsconfig-paths/register --transpile-only ./node_modules/typeorm/cli.js migration:run`

`Unable to fetch database config from env file for environment: production`
`Picking up config from the environment`
`Error during migration run:`
`error: password authentication failed for user "user"`
`    at Parser.parseErrorMessage (/app/server/node_modules/pg-protocol/src/parser.ts:369:69)`
`    at Parser.handlePacket (/app/server/node_modules/pg-protocol/src/parser.ts:188:21)`
`    at Parser.parse (/app/server/node_modules/pg-protocol/src/parser.ts:103:30)`
`    at Socket.<anonymous> (/app/server/node_modules/pg-protocol/src/index.ts:7:48)`
`    at Socket.emit (events.js:375:28)`
`    at Socket.emit (domain.js:470:12)`
`    at addChunk (internal/streams/readable.js:290:12)`
`    at readableAddChunk (internal/streams/readable.js:265:9)`
`    at Socket.Readable.push (internal/streams/readable.js:204:10)`
`    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {`
`  length: 101,`
`  severity: 'FATAL',`
`  code: '28P01',`
`  detail: undefined,`
`  hint: undefined,`
`  position: undefined,`
`  internalPosition: undefined,`
`  internalQuery: undefined,`
`  where: undefined,`
`  schema: undefined,`
`  table: undefined,`
`  column: undefined,`
`  dataType: undefined,`
`  constraint: undefined,`
`  file: 'auth.c',`
`  line: '331',`
`  routine: 'auth_failed'`
`}`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! server@0.0.1 db:migrate: ts-node -r tsconfig-paths/register --transpile-only ./node_modules/typeorm/cli.js migration:run`
`npm ERR! Exit status 1`
`npm ERR! `
`npm ERR! Failed at the server@0.0.1 db:migrate script. `
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above. `

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /root/.npm/_logs/2022-05-12T21_38_10_386Z-debug.log`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! @ db:migrate: npm --prefix server run db:migrate`
`npm ERR! Exit status 1`
`npm ERR! `
`npm ERR! Failed at the @ db:migrate script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
`npm WARN Local package.json exists, but node_modules missing, did you mean to install?`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /root/.npm/_logs/2022-05-12T21_38_10_407Z-debug.log`

**Comment by chooimail** [comment]
I encountered a similar problem, but following the instructions [here](https://docs.tooljet.com/docs/contributing-guide/setup/docker) from 'Contributing Guide > Setup Docker'

Following everything until Step 5 & 6
- There are no errors
- But I notice the **server** does not seem to be running

![server not running](https://user-images.githubusercontent.com/77225894/168199030-127ff758-8e50-40c0-aa02-4b26c82ff9fe.png)

**Comment by sujin-lifology** [comment]
paste your errors so, I can find you a solution.

**Comment by PaulMcF1987** [comment]
@sujin-lifology
Every time I try to run the `docker-compose run server npm run db:seed` command, it adds another container with a name similar to `tooljet_server_run_85a043351243` I currently have 3 of these, all of which are stopped, along with tooljet_server_1 which is stopped.
The 4 of these, all have the same image name `tooljet/tooljet-server-ce:latest`

With regards to logs, the dialogue box is empty

![image](https://user-images.githubusercontent.com/75368133/168250706-077d1461-e710-42c7-ad7d-fbca351ae8e0.png)

Is there anything in the YAML or env that might need changed?

**Comment by sujin-lifology** [comment]
can you share your .env file and docker compose file, did you try to open the ports in docker compose file? that's where you get the localhost port no

**Comment by PaulMcF1987** [comment]
# Create .env from this example file and replace values for the environment.
# The application expects a separate .env.test for test environment configuration
# Get detailed information about each variable here: https://docs.tooljet.com/docs/setup/env-vars

TOOLJET_HOST=http://domainIP:9102
LOCKBOX_MASTER_KEY=replace_with_lockbox_master_key
SECRET_KEY_BASE=replace_with_secret_key_base

# DATABASE CONFIG
ORM_LOGGING=all
PG_DB=tooljet_production
PG_USER=user
PG_HOST=domainIP
PG_PASS=password

# Checks every 24 hours to see if a new version of ToolJet is available
# (Enabled by default. Set 0 to disable)
CHECK_FOR_UPDATES=

# Checks every 24 hours to update app telemetry data to ToolJet hub.
# (Telemetry is enabled by default. Set value to true to disable.)
# DISABLE_APP_TELEMETRY=false

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# EMAIL CONFIGURATION
DEFAULT_FROM_EMAIL=hello@tooljet.io
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_DOMAIN=
SMTP_PORT=

# DISABLE USER SIGNUPS (true or false). Default: true
DISABLE_SIGNUPS=

# OBSERVABILITY
APM_VENDOR=
SENTRY_DNS=
SENTRY_DEBUG=

# FEATURE TOGGLE
COMMENT_FEATURE_ENABLE=
ENABLE_MULTIPLAYER_EDITING=true

#SSO
SSO_DISABLE_SIGNUP=
SSO_RESTRICTED_DOMAIN=
SSO_GOOGLE_OAUTH2_CLIENT_ID=
SSO_GIT_OAUTH2_CLIENT_ID=
SSO_GIT_OAUTH2_CLIENT_SECRET=

@sujin-lifology that is the .env I have at the minute

**Comment by PaulMcF1987** [comment]
version: '3'

services:
  client:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-client-ce:latest
    restart: always
    env_file: .env
    depends_on:
      - server
    volumes:
      - .logs:/var/log/openresty/
      - .certs:/etc/resty-auto-ssl/
      - .fallbackcerts:/etc/fallback-certs
    ports:
      - 9102:80
      - 9101:443
    command: openresty -g "daemon off;"

  server:
    image: tooljet/tooljet-server-ce:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3000
    env_file: .env
    environment:
      SERVE_CLIENT: "false"
    command: npm run start:prod
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/postgres_data
  certs:
  logs:
     fallbackcerts

Above is YAML/
All ports are open although I have had to change some as they are already in use

**Comment by PaulMcF1987** [comment]
My tooljet dashboard:

![image](https://user-images.githubusercontent.com/75368133/168266023-4a85680e-bbb6-4902-a1c2-6b54a8e2445b.png)

**Comment by chooimail** [comment]
> (Windows 10)
> 
> I encountered a similar problem, but following the instructions [here](https://docs.tooljet.com/docs/contributing-guide/setup/docker) from 'Contributing Guide > Setup Docker'
> 
> Following everything until Step 5 & 6
> 
> * There are no errors
> * But I notice the **server** does not seem to be running
> 
> ![server not running](https://user-images.githubusercontent.com/77225894/168199030-127ff758-8e50-40c0-aa02-4b26c82ff9fe.png)


Attached are my .env & .yaml files
[docker-compose.yaml.txt](https://github.com/ToolJet/ToolJet/files/8691967/docker-compose.yaml.txt)
[.env.txt](https://github.com/ToolJet/ToolJet/files/8691968/default.env.txt)

**Comment by MikeMichel** [comment]
I also wonder about this `template1`error. What does it mean?

**Comment by withshubh** [comment]
Closing this issue. Please refer to this: https://github.com/ToolJet/ToolJet/issues/3331
