### ISSUE TITLE
"Sign in with Google" breaks after upgrading to 1.13.0

### ISSUE THREAD

**Issue by dlebech** [ToolJet/ToolJet#3064]
### Version Information

1.13.0 (upgrading from 1.12.1)

### Environment

Docker

### What is the expected behaviour?

"Sign in with Google" should work after upgrading from v1.12.1 to v1.13.0.

### What is the current behaviour?

After upgrading from v1.12.1 to v1.13.0, the "Sign in with Google" button disappears.

If I set `DISABLE_MULTI_WORKSPACE=true` ***before upgrading***, the "Sign in with Google" button will be shown, but I will still not be able to sign in, as the API starts throwing 401 errors which is shown as "Could not fetch library apps".

In other words, I'm completely unable to sign in to Tooljet after upgrading.

### How to reproduce the issue?

1. Use v1.12.1
2. Set up Google SSO using the old instructions, i.e. use environment variable `SSO_GOOGLE_OAUTH2_CLIENT_ID`
3. Create a user and sign in.
4. Upgrade to v1.13.0.
5. The "Sign in with Google" button is not present, and it is impossible to sign in.

### Screenshots or Screencast

Before the upgrade (on v1.12.1)

![image](https://user-images.githubusercontent.com/292796/168586100-84c4e608-38e6-46d0-ac15-ed458a1345fe.png)

After upgrading to v1.13.0:

![image](https://user-images.githubusercontent.com/292796/168587077-4d3a11bd-10bc-45ea-a91c-282134b30f37.png)

If I use `DISABLE_MULTI_WORKSPACE=true` ***before upgrading***, this error is shown:

![image](https://user-images.githubusercontent.com/292796/168588587-35cf6a7d-e8bf-470b-9626-75be9f4d7dad.png)

### Any possible solutions?

No, Google SSO seems to be broken after upgrade.

### If the bug is confirmed, would you be willing to submit a PR?

**Comment by dlebech** [comment]
Hi @gsmithun4 and thanks for the quick reply :100: 

Both of your solutions unfortunately do not work for me.

> If you have enabled Multi-workspace, you can only login through password, once you logged in you can select your work space and configure [Google SSO](https://docs.tooljet.com/docs/sso/google)

I tried this already, before submitting this issue, but I had two specific problems:
1. The existing organization simply *disappeared*, along with all its apps. I could see it in the database, but it wasn't selectable in the menu.
2. I then tried creating a *new organization*, and manually set up Google SSO for it using the instructions. However, the "Sign in with Google" *did not appear* after doing this.

> If Multi-Workspace is disabled, SSO is enabled, after upgrade
> ... 
> - Go to Google OAuth settings and add <Domain>/sso/google/<config_id> add under Authorised Redirect URIs

I did this already, before submitting this issue, and I get the Google popup and everything, but I still receive the error shown in the third screenshot when I get redirected back to Tooljet.

**Note**: I'm testing this on localhost before deploying to our server, and that has worked fine in the past for Google Sign In.

**Comment by dlebech** [comment]
Also, just to be clear, when I'm testing the two different scenarios, I'm starting with a completely wiped tooljet database to avoid other conflicts, i.e.:
1. Drop `tooljet` database completely.
2. Run 1.12.1 and create a single user/apps with Google Sign In.
3. Upgrade to 1.13.0... and as mentioned above, both of the scenarios (with or without Multi-workspace enabled) breaks the login functionality.

**Comment by gsmithun4** [comment]
1. The existing organization simply disappeared, along with all its apps. I could see it in the database, but it wasn't selectable in the menu.
 -- **Needs to look into it**
2. I then tried creating a new organization, and manually set up Google SSO for it using the instructions. However, the "Sign in with Google" did not appear after doing this.
 -- This is expected, for Multi-Workspace, user can log in only using password, SSO can be enabled when switching the app
 https://www.loom.com/share/9babd68243664550afe8ee46a0601127

**Comment by gsmithun4** [comment]
Have you tried this for Single-Workspace?

1. open <Domain>/api/organizations/public-configs
2. Find the value of the field config_id
3. Go to Google OAuth settings (https://console.cloud.google.com/apis/credentials) and add <Domain>/sso/google/<config_id> add under Authorised Redirect URIs

**Comment by dlebech** [comment]
@gsmithun4 Thanks for your time and detailed replies!

First, to answer your question, yes, that is what I tried before.

However, **I found the problem** a little bit by chance after debugging for a bit on a fork of the project:

- In the database table `organization_users`, my user had `status = 'invited'`.
- Changing the status to `active` in the table allowed it to log in via Google.

(the ORM logging is what hinted at the solution, because it used "active" as a filter in the query logs for the user)

So perhaps in v1.12.1, an "invited" user can log in via SSO, but in v1.13.0, the user has to be "active" in the database.

### Further info

The way this situation can be reproduced is quite easy:
- SSO enabled in v1.12.1
- Go to "sign up" page
- Type in a valid email
- An error occurs, but the user is *actually created in the database*
- Go back to sign in page and sign in as user
- The user is permanently in "invited" state but can do everything in Tooljet (in v 1.12.1)

Then after upgrading to v1.13.0, the user can no longer sign in.

### Solution, kind of

To successfully upgrade in the production, I guess I will have to do the followings steps:
- Ensure `DISABLE_MULTI_WORKSPACE=true` *before upgrading*
- Manually update all organization users to be "active" instead of "invited".

**Comment by gsmithun4** [comment]
> 

Thanks for finding out the solution, the changes to be made
- Invited user should be able to login via SSO, on login status should be changed to `active`
Will try to add it in the next release.

**Comment by gsmithun4** [comment]
fixed https://github.com/ToolJet/ToolJet/pull/3164

**Comment by dlebech** [comment]
Thanks @gsmithun4 :tada:
