### ISSUE TITLE
Improvement: Add an appropriate page title for each component file.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3065]
### Is your proposal related to a problem?

The page title(_ToolJet - Dashboard_)  is the same for all component files.

### Describe the solution you'd like

The page title should be appropriate for the component file.

**Comment by vedant-z** [comment]
Hey @ajith-k-v I would like to take this one. Some guidance would be helpful 😁

**Comment by withshubh** [comment]
Hey @vedant-z - Please pick the issues with `good-first-issue` or `up-for-grabs` labels
