### ISSUE TITLE
Incorrect message while enabling/disabling Password login

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#3066]
### Version Information
1.13.0

### Environment
Latest develop

### What is the expected behaviour?
Should show message `Password login disabled` and `Password login enabled` while enabling/disabling password login

### What is the current behaviour?
Showing `Form login enabled` and `Form login disabled`

### How to reproduce the issue?
1. Open Manage SSO
2. select Password Login
3. enable/disable password login

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by Joeyg61703** [comment]
Hey! I'm interested in taking this issue.

**Comment by Sam-Kohl** [comment]
I'd be happy to try and tackle this!

**Comment by gsmithun4** [comment]
@Sam-Kohl Sure, assigning to you

**Comment by withshubh** [comment]
Hey @Sam-Kohl 👋 
Any updates on this?

**Comment by withshubh** [comment]
Thanks for your contribution @Sam-Kohl 🚀 

Closing this issue - fixed in https://github.com/ToolJet/ToolJet/pull/3110
