### ISSUE TITLE
Add validation for input fields on the profile settings page.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3073]
### What is the expected behaviour?
1. The error toast message should be different for both first name and last name.
2. The first name and last name fields should not accept numbers and symbols.
3. It should not save the name if the input fields have only blank spaces.
4. It should not take the current password as the new password.
5. It should not save if the password field has only blank space as a password.

### What is the current behaviour?
1. The error toast message is same for both first name and last name field.
2. Both first name and last name input fields are accepting numbers, symbols and blank space as name.
3. It accepting the current password as the new password.
4. It accepting blank space as password. 

### How to reproduce the issue?

1.
2.
3.

### Screenshots or Screencast
[Video](https://www.loom.com/share/d1d1790247a5431c8f3e2f970f961271)

**Comment by ajith-k-v** [comment]
@mazkaaa Assigned the issue to you.

**Comment by mazkaaa** [comment]
> @mazkaaa Assigned the issue to you.

Thank you! I'm working on it🚀

**Comment by mazkaaa** [comment]
Hi @ajith-k-v,
I have created a pull request https://github.com/ToolJet/ToolJet/pull/3104
