### ISSUE TITLE
[docs]: Explain how to include variables in GraphQL queries

### ISSUE THREAD

**Issue by msp-matt** [ToolJet/ToolJet#3094]
### Summary

The doc page for GraphQL doesn't explain how to include variables in a GraphQL query. I asked on the Slack channel and somebody kindly explained that you can inject parameters directly into the query using Javascript, like this:
```
query Query {
  characters(page: {{components.textinput1.value}}, filter: {name: "Morty"}) {
    info {
      count
    }
    results {
      name
    }
  }
  location(id: 1) {
    id
  }
  episodesByIds(ids: [1, 2]) {
    id
  }
}
```

This makes perfect sense and I think it would be great to include it in the documentation.

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/graphql/

### Additional Information

It makes it easier to understand how to include variables in a GraphQL API query.

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by withshubh** [comment]
Thanks for creating the issue @msp-matt

**Comment by withshubh** [comment]
Closing the issue as we have added `variables` field so this is no more required.
