### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [ToolJet/ToolJet#3105]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@gaurav-g2) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by withshubh** [comment]
Hey @JamieSlome 👋 

Please go through this - https://docs.tooljet.com/docs/security

**Comment by JamieSlome** [comment]
@withshubh - sent an e-mail to the `security@` e-mail address 👍

**Comment by withshubh** [comment]
Thanks! @JamieSlome 🙌 
Closing this issue - A team member will continue over the email.
