### ISSUE TITLE
Confirm password field for profile- change password section

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#3108]
### Is your proposal related to a problem?
There is no confirm password field in user profile page 

### Describe the solution you'd like
Add confirm password field and verify the new password and confirm password are same

### If the feature is approved, would you be willing to submit a PR?
No

**Comment by deepakb** [comment]
Hi @gsmithun4,
Could you please assign this task to me? I want to work on this.

**Comment by withshubh** [comment]
Hey @deepakb 
Are you still working on this issue?

**Comment by deepakb** [comment]
> Hey @deepakb Are you still working on this issue?

I am facing some issues to set up the project locally.  I'll try once again and update.

**Comment by withshubh** [comment]
Hey @deepakb 👋 
Let us know if you're still working on it?
If you have any questions please feel free to ask any on our [Slack Community](https://tooljet.slack.com/join/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg#/shared-invite/email).

**Comment by Syed-Ansar** [comment]
Hey @withshubh I would like to work on this issue if deepakb isn't working.

**Comment by withshubh** [comment]
Hey @deepakb 
Unassigning this issue as there was no update for more than 20 days.

**Comment by withshubh** [comment]
Hey @Syed-Ansar - Assigned this issue to you.

**Comment by Syed-Ansar** [comment]
Hey @withshubh I have some questions over the alignment of the input elements. Before moving forward I would like to discuss. Let me know If you are available for discussion.

**Comment by withshubh** [comment]
@Syed-Ansar - I'd request you to please join our [Slack community](https://tooljet.slack.com/join/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg#/shared-invite/email) and post all your questions there.

**Comment by Syed-Ansar** [comment]
Hey @withshubh can you review #3361

**Comment by withshubh** [comment]
Hey @Syed-Ansar 
Someone from the team will review your PR in a day or two. In the meantime, you can pick the next issue you want to work on.

**Comment by Syed-Ansar** [comment]
Hey @withshubh I have made another PR please review it. #3365

**Comment by shubh22** [comment]
Issue has been fixed.
