### ISSUE TITLE
Add a button for closing the toast message.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3111]
### Is your proposal related to a problem?

Having a close button for the toast message is more convenient for the end-user

### Describe the solution you'd like

Add a button for closing the toast message. 

### Describe alternatives you've considered

(Write your answer here.)

**Comment by aiman-rizvi** [comment]
Hello, may I work on this issue?

**Comment by Navaneeth-pk** [comment]
Thanks for your interest in contributing to ToolJet. Assigned the issue to you.
@aiman-rizvi

**Comment by aiman-rizvi** [comment]
Hey @ajith-k-v  ! Just to clarify, is this issue to add a dismiss button to every toast in the app? Or just for some specific toasts?

**Comment by ajith-k-v** [comment]
Hey @aiman-rizvi  to add a dismiss button to every toast in the app.

**Comment by aiman-rizvi** [comment]
Hey @ajith-k-v I'm sorry, I won't be able to tend to this issue at this time. Can I be unassigned? Thanks!

**Comment by DonRomaniello** [comment]
May I work on this issue?

**Comment by withshubh** [comment]
Hey @DonRomaniello 
Thanks for your interest in contributing to ToolJet.
Assigned to you.

**Comment by DonRomaniello** [comment]
@withshubh , it is implemented.

Pull request sent.

**Comment by DonRomaniello** [comment]
Oops, I just realized I forgot to remove some commented out code. Line 23 of frontend/src/App/App.jsx is no longer needed.

Should I resubmit?
