### ISSUE TITLE
Add suitable error toast messages for the first name and last name input fields on the profile settings page

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3116]
[Video](https://www.loom.com/share/e67558f1152c49f1a8b70d2680293f86)

**Comment by mazkaaa** [comment]
Hi @ajith-k-v,
I have already created a pull request on your previous issue. https://github.com/ToolJet/ToolJet/issues/3073

**Comment by ajith-k-v** [comment]
Fixed by: [3104](https://github.com/ToolJet/ToolJet/pull/3104)
