### ISSUE TITLE
Feature: Delete rows from Google sheets

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#312]
Description: We need to add a new operation for the Google sheets query editor to delete a row from a sheet. 

API reference: https://developers.google.com/sheets/api/samples/rowcolumn#delete_rows_or_columns

Options needed for the operation: 
a) Sheet ID 
b) Sheet name 
c) Row Index 

The row at the given index should be deleted from the sheet.

**Comment by nisusam** [comment]
Hey @Navaneeth-pk I'll pick this up
