### ISSUE TITLE
Query panel overlaps pop out code-hinter popped out from it

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3122]
### What is the expected behavior?
Expanding the code-hinter it should be stacked above the query editor panel.

### What is the current behavior?
While expanding the code-hinter to enter the value, it gets behind the query editor panel.

### How to reproduce the issue?

1.  Expand the query panel and click on the "create query" button

<img width="1440" alt="Screenshot 2022-05-25 at 5 51 46 PM" src="https://user-images.githubusercontent.com/32157641/170260783-58a457b1-745f-4442-a402-0049dae80ff5.png">

2. Select Rest API as select Datasource

3. Expand the query editor panel (or close and reopen the query editor )

4. Hover over the "Value" input field and click on the icon to pop out the code editor

<img width="1440" alt="Screenshot 2022-05-25 at 5 54 39 PM" src="https://user-images.githubusercontent.com/32157641/170261289-ea9072c1-d4df-40f4-aa63-417e352020a4.png">

5. The code-hinter pops up behind the query editor panel. 

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2022-05-25 at 5 59 49 PM" src="https://user-images.githubusercontent.com/32157641/170262169-2b775baa-fccd-46f2-94d7-815e28635e44.png">

**Comment by jack-r-buckley** [comment]
Hi, can I work on this one?

**Comment by shivangT** [comment]
Hello Jack,

Sure you can go ahead and pick this issue. Let me know if you have any
questions or need help with anything.

Have a good time coding on ToolJet.

**Comment by shivangT** [comment]
Hello @jack-r-buckley ,
Any updates on the above issue? Let us know if you are stuck with something.

**Comment by withshubh** [comment]
Hey @jack-r-buckley 
It's been around a month since this issue was assigned to you - Please let us know if you're still working on this issue?

**Comment by shivangT** [comment]
Hello @jack-r-buckley ,

Could you please update the progress on this issue? Let us know if you need help with something else we'll assign this to someone else.

**Comment by shivangT** [comment]
Hello @jack-r-buckley ,
This issue is resolved so we're closing this issue. Please find a new issue to work on. Thank you.
