### ISSUE TITLE
typo: label should be `Allowed domains`

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3135]
### Environment

ToolJet Cloud 

### What is the expected behaviour?

The label should be `Allowed domains`

### What is the current behaviour?

The label is `Allowed domain` -  it should be `Allowed domains`

### How to reproduce the issue?

1. Go to `Manage SSO` from the navbar
2. Check the `General Setttings`

### Screenshots or Screencast
![Screenshot 2022-05-27 at 1 45 36 AM](https://user-images.githubusercontent.com/25361949/170573013-ae257a95-03e6-46b5-88e5-9d6a04bc3873.png)

**Comment by AlessandroCipolletti** [comment]
Hi everyone, I'm new here. Can I take this simple one just to start ?

**Comment by arpitnath** [comment]
Hi @AlessandroCipolletti 
Sure, assigning the issue to you.

**Comment by AlessandroCipolletti** [comment]
Thanks! I just submitted a small pull request. Id 3137
