### ISSUE TITLE
fix the height of button in navbar

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3136]
### Environment

ToolJet Cloud

### What is the expected behaviour?

The heights of the buttons in the navbar should be equal.

### What is the current behaviour?

The `Workspace` button height is lower than the `User` button

### How to reproduce the issue?

1. Go to the dashboard
2. On the navbar - hower on the buttons to see the difference in height

### Screenshots or Screencast
![Screenshot 2022-05-27 at 1 47 24 AM](https://user-images.githubusercontent.com/25361949/170574210-3357f76b-8ccb-464f-ae25-339b2baa80e7.png)

**Comment by aguin467** [comment]
I would like to work on this if that is okay?

**Comment by ithiel883** [comment]
can i work on this issue?

**Comment by shivangT** [comment]
Hello @aguin467, 

I am assigning this issue to you. You can go ahead and look into it.
Please communicate with us on our slack channel if you need any help. 

Have a good time coding on Tooljet.

**Comment by shivangT** [comment]
> can i work on this issue?

Hello @ithiel883,

We assign the issue on a first come first serve basis.  
If you want to work on other such issues, check out the open issues here: https://github.com/ToolJet/ToolJet/issues

Thanks and Regards

**Comment by prasanta10** [comment]
If there is no work being done over this. I would be happy to help

**Comment by withshubh** [comment]
Hey @aguin467 👋 
Any updates?

**Comment by aguin467** [comment]
Hey yes sorry as a I haven’t been active. I’ve been working. I work 4 days a week and today is my first day off. I’ll get to it within the next three days.

**Comment by withshubh** [comment]
Hey @aguin467 
Since there were no updates from you - I have unassigned the issue.

**Comment by withshubh** [comment]
@prasanta10  - Assigned this issue to you.

**Comment by prasanta10** [comment]
@withshubh I really want to contribute but I have semester exams going on. So, I don't think I will be able to work on this any time sooner. Sorry!

**Comment by ithiel883** [comment]
@withshubh can i be assigned this issue?

**Comment by withshubh** [comment]
Assigned this to you @ithiel883

**Comment by Syed-Ansar** [comment]
Hey @withshubh can I work on this issue ?

**Comment by withshubh** [comment]
Hey @Syed-Ansar - I just assigned an issue to you. Once a PR for that issue is created - we can assign another one.

**Comment by Syed-Ansar** [comment]
Hey @withshubh you can assign this to me now

**Comment by withshubh** [comment]
Hey @Syed-Ansar 
Assigned to you.

**Comment by Syed-Ansar** [comment]
I have raised a PR can you please review it. #3393

**Comment by withshubh** [comment]
Unassigned @Syed-Ansar as there was no update for more than a month.

This issue is up for grabs now.

**Comment by himanshu-suman** [comment]
Hi @shivangT  ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by withshubh** [comment]
> Hi @shivangT  ,
> This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
> Can you please assign this to me?

Assigned this to you @himanshu-suman
