### ISSUE TITLE
[Bug]: PDF Widget Crash

### ISSUE THREAD

**Issue by kavinvenkatachalam** [ToolJet/ToolJet#3141]
### Environment

ToolJet Cloud

### What is the expected behaviour?

PDF Widget should display the PDF whenever the `URL` field is updated

### What is the current behaviour?

When the `URL` value is cleared and when the new value is provided, it crashes

### How to reproduce the issue?

1. Insert PDF Widget into the canvas
2. Clear the URL value
3. Add new URL 

### If the bug is confirmed, would you be willing to submit a PR?

Yes

**Comment by TheLearneer** [comment]
@Navaneeth-pk Seems like the issue is resolved and can be closed 🙏

**Comment by withshubh** [comment]
@TheLearneer Thanks for the heads up.
