### ISSUE TITLE
Add validation for group creation

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3147]
### What is the expected behaviour?
The group should have a valid name.

### What is the current behaviour?
The user can create groups with the group name as a blank space.
### How to reproduce the issue?

[Video](https://www.loom.com/share/784aeadc7c5f4c70b1b35b402eac95d4)

### Screenshots or Screencast

<img width="1439" alt="Screenshot 2022-05-27 at 10 32 13 PM" src="https://user-images.githubusercontent.com/20367957/170747739-48094f11-1509-413f-bcac-852b644caddf.png">

### Any possible solutions?
Add validations.

**Comment by mazkaaa** [comment]
Hi @ajith-k-v,
I'd like to work on this issue. can you assign me?

**Comment by ajith-k-v** [comment]
@mazkaaa  Assigned the issue to you.

**Comment by withshubh** [comment]
Hey @mazkaaa 👋 
Any updates on this issue?

**Comment by withshubh** [comment]
No worries! Thanks for the update @mazkaaa 👍 
Do link this issue to the PR when you create it.

**Comment by mazkaaa** [comment]
> No worries! Thanks for the update @mazkaaa 👍 Do link this issue to the PR when you create it.

The current code in this group creation js file is using the class component. Should I change the whole code to the functional component?

**Comment by akshaysasidrn** [comment]
Hey @mazkaaa, refactoring will increase the scope of the change. Let's keep it simple to add a validation check both at frontend and backend dto to not allow whitespaces.

**Comment by mazkaaa** [comment]
> Hey @mazkaaa, refactoring will increase the scope of the change. Let's keep it simple to add a validation check both at frontend and backend dto to not allow whitespaces.

Okay. i still working on it sorry if its late almost 1 months because i've been sick because of covid.

**Comment by shivangT** [comment]
Hey @mazkaaa 

There are a few changes requested in the PR. Kindly resolve it so that we close the issue soon.

**Comment by mazkaaa** [comment]
> Hey @mazkaaa
> 
> There are a few changes requested in the PR. Kindly resolve it so that we close the issue soon.

ohh sorry! will working on it!

**Comment by shivangT** [comment]
Thanks

**Comment by ajith-k-v** [comment]
This issue no longer exists.
