### ISSUE TITLE
Autofocus on input while opening datasource modal ( Add datasource ) 

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#3148]
### Is your proposal related to a problem?
 input is not autofocused  while opening datasource modal
 
### Describe the solution you'd like
<img width="1280" alt="Screenshot 2022-05-27 at 10 39 11 PM" src="https://user-images.githubusercontent.com/31006028/170751810-223d782f-a3d2-45f0-b3fe-42d12b6ec9db.png">

Autofocus on input while opening datasource modal

### If the feature is approved, would you be willing to submit a PR?
No.

**Comment by vishnurk6247** [comment]
Hello, I'd like to take up this issue

**Comment by withshubh** [comment]
Hey @vishnurk6247 👋 
Any update on this issue?

**Comment by withshubh** [comment]
Unassigned @vishnurk6247 as there were no updates for a long time.
