### ISSUE TITLE
Query(RESTAPI): Post request cannot be successful, but in postman can

### ISSUE THREAD

**Issue by F12EN** [ToolJet/ToolJet#3149]
### Environment

    ToolJet Cloud, Chrome

### What is the expected behaviour?
Same REST API can be successfully requested as when debugging in postman.
HTTP methods: post
![image](https://user-images.githubusercontent.com/25075086/170762724-9c1793a8-f822-4f39-b3e7-1634c2e99f2b.png)

### What is the current behaviour?
API has no request success, According to the error message prompt: the lack of the required field "usercode", but the actual phenomenon has been filled in, there seems to be no parameters in body passed to the API.

### How to reproduce the issue?

1. Add Queries, Select "REST API"
2. Fill in the content as the following screenshot
3. Click “PreView”

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/25075086/170764029-0b40fccb-8a69-44de-9535-c5b54829c0ef.png)

![image](https://user-images.githubusercontent.com/25075086/170762746-5eae3391-6e7d-49c0-9265-bfa828cffb1a.png)

### Please provide any traces or logs that could help here.
```
{
    "requestObject": {
        "requestUrl": "Address/user/login.do",
        "requestHeaders": {
            "user-agent": "got (https://github.com/sindresorhus/got)",
            "content-type": "application/x-www-form-urlencoded",
            "content-length": "103",
            "accept-encoding": "gzip, deflate, br"
        },
        "requestParams": {}
    },
    "responseObject": {
        "statusCode": 400,
        "responseBody": "{\"timestamp\":1653673802825,\"status\":400,\"error\":\"Bad Request\",\"message\":\"Required String parameter 'userCode' is not present\",\"path\":\"/user/login.do\"}"
    },
    "responseHeaders": {
        "access-control-allow-credentials": "true",
        "access-control-allow-methods": "POST, GET, OPTIONS, DELETE",
        "access-control-allow-headers": "Content-Type,Accept,token,headers",
        "content-type": "application/json;charset=UTF-8",
        "transfer-encoding": "chunked",
        "content-encoding": "gzip",
        "vary": "Accept-Encoding",
        "date": "Fri, 27 May 2022 17:50:02 GMT",
        "connection": "close"
    }
}
```

### Any possible solutions?
When I put a field from the body in params, I can request success, but in fact I hope these parameters are put in body.

### Can you identify the location in the driver source code where the problem exists?
Sorry, I just used it shortly, I couldn't distinguish it.

**Comment by F12EN** [comment]
Looking forward to your reply, thank you

**Comment by shah21** [comment]
Hi @F12EN, We will check if this error is existed or not in develop and get back to you

**Comment by shah21** [comment]
Hi @F12EN We checked this issue, looks like the issue exists, we will solve this asap

**Comment by F12EN** [comment]
Got it. Thank you! Look forward to the fixed version.
