### ISSUE TITLE
[docs]: make admonitions(docusauras) compatible with dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3156]
### Summary

Currently, the admonitions in docs are of white color which doesn't look good.
Make them compatible with dark mode.
Here is the link to docusauras for reference: https://docusaurus.io/docs/next/markdown-features/admonitions

![image (1)](https://user-images.githubusercontent.com/25361949/170948724-4119218f-630b-4800-a2db-1d2ea2cc81f1.png)

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

Sample URL - https://docs.tooljet.com/docs/tracking

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Shelly011s** [comment]
Please assign this to me.

**Comment by withshubh** [comment]
Hey @Shelly011s 
Assigned this to you.

**Comment by withshubh** [comment]
Hey @Shelly011s 👋 
Are you still working on this issue?

**Comment by Shelly011s** [comment]
Hey 

> Hey @Shelly011s wave Are you still working on this issue?

Hey, so sorry I got busy and couldn't finish with this issue. You can unassign this issue.

**Comment by Syed-Ansar** [comment]
I would like to work on this issue. Assign it to me.

**Comment by withshubh** [comment]
Hey @Syed-Ansar - Let me know once you create the PR for the issue that is currently assigned to you then we can assign the another one.

**Comment by jr-b** [comment]
Hey @withshubh, I wanted to help with this, but I think it has been fixed!

Dark mode seems to apply correctly to admonitions, see [Environment variables](https://docs.tooljet.com/docs/setup/env-vars/#application-secret--required-) doc page.

<img width="881" alt="Screen Shot 2022-09-14 at 11 45 51" src="https://user-images.githubusercontent.com/8695937/190201594-a3b47df9-a72b-4212-9d59-431ab668378f.png">

**Comment by withshubh** [comment]
Hey @jr-b 👋 
Thanks for the heads up. Yes, the issue has been fixed in the latest version of docusauras.
Please feel free to pick any other open `good-first-issue` or `up-for-grabs`
