### ISSUE TITLE
Button group widget label not visible in dark mode

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#3186]
### What is the expected behaviour?
Label to be visible in dark mode.

### What is the current behaviour?
Label is not visible in dark mode

### How to reproduce the issue?

1.Drag and drop buttonGroup widget
2.Observe in dark mode.

### Screenshots or Screencast

https://user-images.githubusercontent.com/31006028/171391026-038d4b26-5d6c-431e-92d6-f89de2d4007c.mov

### Any possible solutions?

- Go to `theme.scss` file find  `widget-buttongroup-label`  class
- Update with following code

**

> .widget-buttongroup-label
> {
>   font-weight: 600;
>   margin-right: 10px;
>   color: #3e525b; // add this color in `theme.scss` fille
> }

**

### Can you identify the location in the driver source code where the problem exists?

frontend/src/_styles/theme.scss

### If the bug is confirmed, would you be willing to submit a PR?
NO.

**Comment by haikali3** [comment]
why would you not accepting the PR if the bug is confirmed?
