### ISSUE TITLE
Application Launch Error

### ISSUE THREAD

**Issue by ashishmax31** [ToolJet/ToolJet#319]
### Environment
Self hosted on AWS EC2 using the ami name `tooljet_v0.5.11.ubuntu_bionic`

### What is the expected behavior?
Should be able to visit the apps created from tooljet

### What is the current behavior?
After creating an app from tooljet, visiting the app's url leads to a 404 page.

More screenshots and info here: https://github.com/ToolJet/ToolJet/issues/226#issuecomment-868234622

**Comment by zachspar** [comment]
I can confirm this fixes the issue on my end. Thanks @ashishmax31
