### ISSUE TITLE
Add validation for the form input fields on the confirmation page

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3211]
### What is the expected behaviour?
1. The first name and last name fields should not accept numbers and symbols.
2. The error toast message should be different for all the fields.

### What is the current behaviour?
1. Both first name and last name input fields accept numbers, symbols and blank spaces as names.
2. The error toast message is the same for all the fields

### Screenshots or Screencast
[Video](https://www.loom.com/share/e2059e49fe174c7eaa6a26f49c37f7fe)

### Any possible solutions?
- Validation and error messages
- Marking mandatory params

**Comment by saimaheshtaduri** [comment]
@ajith-k-v  can I contribute to this as part of hacktoberfest ? assign to me. Thanks :)

**Comment by ajith-k-v** [comment]
Closing this issue since it no longer exists
