### ISSUE TITLE
Don't working set variable in button or unset variable

### ISSUE THREAD

**Issue by dumy** [ToolJet/ToolJet#3219]
### Version Information
Last

### How to reproduce the issue?

1.
2.
3.

### Screenshots or Screencast

  Providing relevant Screenshots/ Screencasts would help us to debug the issue quickly.
![image](https://user-images.githubusercontent.com/8275027/172382152-09be3fa3-4c64-46d7-8e28-bff4d37cbf1e.png)

**Comment by sherfin94** [comment]
Hi, the set variable action is used to set a variable in the global `variables` key. You cannot directly set the exposed value of any component using this action.
