### ISSUE TITLE
Implement draggable event handlers in widget's event property

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3225]
### What is the expected behaviour?
While adding multiple events under the widget's properties, it should be draggable to change the order of events

### What is the current behaviour?
We're unable to drag and change the order of events, in order to do that we've to delete all the events and add them as per the new sequence.

### How to reproduce the issue?

1. Drag and drop a widget ( for eg Button)
2. Now inspect and check out its properties on the left pane. 
3. Expand the events panel and add different types of event handlers

### Screenshots or Screencast
<img width="299" alt="Screenshot 2022-06-08 at 1 46 38 PM" src="https://user-images.githubusercontent.com/32157641/172567435-59054644-1631-4efd-9cf7-88c360f6a390.png">

### Any possible solutions?

This feature already exists on our platform. You can refer to the table widget. Drag and drop a table and inspect it. Look for the "Columns" property on the right. We're able to change the position of the columns by drag and drop property.

<img width="300" alt="Screenshot 2022-06-08 at 1 48 19 PM" src="https://user-images.githubusercontent.com/32157641/172567746-3a18f5ce-93ff-4f3a-846d-82a031b52626.png">

**Comment by shivangT** [comment]
hey @kavinvenkatachalam ,

Are you working on this? What's the status?

**Comment by kavinvenkatachalam** [comment]
@shivangT Merged the PR a few days back #3381

**Comment by withshubh** [comment]
https://github.com/ToolJet/ToolJet/pull/3381
