### ISSUE TITLE
Table bulk update for SQL Server does not work properly

### ISSUE THREAD

**Issue by victor-ivanov** [ToolJet/ToolJet#3236]
### Environment
latest docker images

### What is the expected behaviour?
I would like to edit table inline by using bulk update feature

### What is the current behaviour?
Getting following response from server when pressing bulk update button:
```
{"status":"failed","message":"Query could not be completed","description":"records is not iterable","data":{}}
```

### How to reproduce the issue?

1. Use MS SQL datasource
2. Create table and populate it from SELECT query
3. Make 1 table column editable
4. Add bulk update query using GUI editor. I am passing following query in **records to update** field
```
{{components.tableContents.dataUpdates}}
```
5. Try changing and saving data in one table row.
6. Check response from "run" query request

**Comment by withshubh** [comment]
Hey @victor-ivanov 👋 
We have a guide on how to [bulk update multiple rows on the table](https://docs.tooljet.com/docs/how-to/bulk-update-multiple-rows). I hope this helps.

**Comment by victor-ivanov** [comment]
@withshubh I was comparing to similar retool feature, and their query accepts `dataUpdates` with no issues. It was confusing to me that for bulk update query we have to perform some server side object transformations in client side query

**Comment by withshubh** [comment]
Thanks for your suggestion @victor-ivanov . We will look into the ways of improving this.
