### ISSUE TITLE
[docs]: fix typo in statistics widget docs

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3245]
### Summary

There is a typo `secondary label color of the primary la bbey entering` in Secondary label color and `secondary text color of the primary la bbey entering` in Secodary Text color.
This should be`secondary label color by entering` and `secondary text color of the primary la bbey entering`

<img width="733" alt="Screenshot 2022-06-09 at 6 59 52 PM" src="https://user-images.githubusercontent.com/25361949/172860621-35f3fcf6-772d-4d75-b8fc-f60b520169a8.png">

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/statistics/#secondary-label-colour , https://docs.tooljet.com/docs/widgets/statistics/#secondary-text-colour

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by yashdhanore** [comment]
Hey! Can you review the PR?
