### ISSUE TITLE
Update the button UI from filled to outlined

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3257]
### What is the expected behaviour?
You've to turn it into an outlined one.

### What is the current behaviour?
The button is of type filled.

### How to reproduce the issue?

1. Visit the [link](https://app.tooljet.com/)
2. Now on the top right corner you will find the "create new application" button
3. Click on the dropdown in the button and then "choose from template"
4. A modal will appear, you will find a button at the bottom of the modal called "create application from template". This is where you have to make the changes

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-06-10 at 1 55 57 PM" src="https://user-images.githubusercontent.com/32157641/173024214-5d4a8323-a47e-460b-8ed7-3cc47815ef73.png">

### Any possible solutions?

Reference to the final UI:

<img width="193" alt="Screenshot 2022-06-10 at 1 56 50 PM" src="https://user-images.githubusercontent.com/32157641/173024360-6a846aa5-96ea-4b38-9295-2be2e369fb6e.png">

**Comment by yashdhanore** [comment]
Hey! can you assign this to me?

**Comment by shivangT** [comment]
Hello @yashdhanore ,
Sure you can pick this issue. Let me know if you need any help.

**Comment by yashdhanore** [comment]
Hey! no updates yet, I'm still having issues logging in.

**Comment by withshubh** [comment]
Hey @yashdhanore 
Can you please share the issues in the [Slack community](https://tooljet.slack.com/join/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg#/shared-invite/email)?

**Comment by yashdhanore** [comment]
I already did, I'll try to fix it and get back at it. I'll unassign me for now.

**Comment by AAYUSH-droid** [comment]
Hey can you assign this issue to me?

**Comment by shivangT** [comment]
Hello @AAYUSH-droid 

This was resolved by our internal team. Closing this for now.

You can look for other good first issues. Let me know if you need help in shortlisting it.

Thanks
