### ISSUE TITLE
Move "show grid lines", "show axes", "loading state" under one accordion

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3261]
### What is the expected behaviour?
In the chart widget, group "show axes" , "show grid lines" and "loading state" inside one accordion  named as "options" 

### What is the current behaviour?
"Show axes" , "Show grid lines" and "Loading state" are not categorised under one.

### How to reproduce the issue?

1. Visit the [link](https://app.tooljet.com/)
2. Click on "create new application"
3. At the right-hand side drag and drop "chart" widget from the widget's inventory
4. Inspect the widget and access all three( Show axes" , Show grid lines and Loading state ) properties scrolling down.

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-06-10 at 6 02 53 PM" src="https://user-images.githubusercontent.com/32157641/173064892-3d720d35-04e7-47a7-8d56-5f19ec3413cc.png">

**Comment by hrutik7** [comment]
hey @shivangT ,
I was working on charts for a different issue. I just saw this issue to I just solved it

**Comment by hrutik7** [comment]
![image](https://user-images.githubusercontent.com/62372737/174023937-e1ece2ec-c81b-43c8-8532-c97ef47940d3.png)

**Comment by hrutik7** [comment]
if this is fine , I like to raise PR and I will continue my work on other issues

**Comment by rushikeshadhav** [comment]
Hey @shivangT can I take this up?
I am new to this project and would love to contribute

**Comment by hrutik7** [comment]
hi @rushikeshadhav ,
this issue is solved and I am working on this https://github.com/ToolJet/ToolJet/issues/3249
if you still want to work on this then, will you please see this issue https://github.com/ToolJet/ToolJet/issues/3249
it will be save our time right?
thanks :)

**Comment by shivangT** [comment]
Hello @hrutik7 
Amazing, I've assigned you the issue. We'll revert you on the PR.
Thank you for working on ToolJet.

**Comment by hrutik7** [comment]
Hey @shivangT 
I pushed the code , but unfortunately one test is giving error and I am not getting that, will you please help me in that
![image](https://user-images.githubusercontent.com/62372737/175079210-7e06b906-30ce-4580-a500-10e2d700252e.png)

**Comment by shivangT** [comment]
Hello @hrutik7 ,
We're resolving this from our end, then move ahead with the PR review.
Apologies for the delay.

**Comment by hrutik7** [comment]
Okk

**Comment by shivangT** [comment]
Hey @hrutik7 
Could you fix this issue? Let me know what are the updates on the same.
