### ISSUE TITLE
`show password` checkbox gets enabled on clicking outside the label

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3267]
### What is the expected behaviour?

On the login screen `show password` checkbox should not be enabled when clicked outside the label.

### What is the current behaviour?

The `show password` gets enabled when clicked outside the label
 
### How to reproduce the issue?

1. Go to the login screen of ToolJet
2. Click anywhere on the right side of the `show password`

### Screenshots or Screencast
![show-password](https://user-images.githubusercontent.com/25361949/173329549-efbf8065-3d10-48b0-bcdd-a3dbcfe67e8a.gif)

**Comment by Owillz01** [comment]
hello, kindly assign me to fix this.

**Comment by withshubh** [comment]
Hey, @Owillz01 Glad to know that you're interested but there's already one issue assigned to you, please submit a PR for that first.

**Comment by Owillz01** [comment]
Hi @withshubh  I have submitted a PR for that already. did that few minutes before making this post

**Comment by withshubh** [comment]
Great! Assigned this issue to you.

**Comment by withshubh** [comment]
Hey @Owillz01 👋 
Friendly bump - Are you working on this issue?

**Comment by Owillz01** [comment]
hi @withshubh 
yes i am.

**Comment by Syed-Ansar** [comment]
I have resolved issue. I will make a PR if @withshubh agree. can watch [here](https://www.loom.com/share/e9a96ba77d1246c78b38b4894ef1e717)

**Comment by withshubh** [comment]
Hey @Syed-Ansar 👋 
Glad that you were able to find a solution to this issue but it is currently assigned to @Owillz01 .
You can create a PR for this but we can't assure to merge your PR as we assign issues on a first come first serve basis.

**Comment by Syed-Ansar** [comment]
Oh that's okay. Let's see if @Owillz01 make a PR then I won't if he doesn't then I would be happy to do that.
