### ISSUE TITLE
Fix text alignment

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3268]
### What is the expected behaviour?

The "Fx" text should be aligned with the "Align Text" title left to it.

### What is the current behaviour? 
It is not aligned as per the UI.

### How to reproduce the issue?

1. Open this [link](https://app.tooljet.com/)
2. Drag and drop the text widget and inspect its properties 
3. Click on styles tab and you'll find the issue.

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-06-13 at 4 08 19 PM" src="https://user-images.githubusercontent.com/32157641/173336225-c520f7ab-d5e6-40b2-9685-0356d203a1cf.png">

### Any possible solutions?
Refer the UI for alignment of title and Fx button next to it

**Comment by rw4nn** [comment]
Hey Shivang, I can take care of this issue :+1: Feel free to assign me, thanks.

**Comment by shivangT** [comment]
Hello @rw4nn ,
Sure, let me know if you need any help with something.
Assigning this issue to you.
Have a good time working on Tooljet.
