### ISSUE TITLE
Increment and decrement buttons for numerical properties on widget inspector

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3269]
### What is the expected behaviour?
When we inspect a widget and find a numerical property  around it, up and down keys should increase or decrease the value

### What is the current behaviour?
The up and down arrow keys don't increase or decrease the values.

### How to reproduce the issue?

1. Visit the [link](https://app.tooljet.com/)
2. Drag and drop the text widget and inspect its properties
3. Click on styles tab and click on text size. In order to change the values we have to enter new ones.
4. By default if a user clicks on up or down arrow the value to start changing with respect with default value i.e 14.

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-06-13 at 3 45 47 PM" src="https://user-images.githubusercontent.com/32157641/173343156-30ebb903-c6c5-46a6-9bfa-aa6665fd60f5.png">

**Comment by pluto0004** [comment]
Hi! If no one hasn’t been assigned to this issue, could I work on this? 😊 Thanks.

**Comment by shivangT** [comment]
Hey @pluto0004 
Assigning this to you. Let me know if you need help with anything. Kindly post the query on our slack channel.
