### ISSUE TITLE
[docs]: move `Try ToolJet locally` to top in Setup category

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3278]
### Summary

Currently, the position of `Try ToolJet locally` is 3rd in Setup. It needs to be the first.

### Solution

- Edit the `sidebar.js` file and move `'setup/docker-local',` to the top of Items.

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/setup/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Owillz01** [comment]
i will love to pick this up. it is my first contribution, how do i go about it?

**Comment by withshubh** [comment]
Sure @Owillz01!
I have assigned this issue to you.
You can follow the [README here](https://github.com/ToolJet/ToolJet/tree/develop/docs) to setup docs locally and contribute to it.
