### ISSUE TITLE
Custom Environment Settings

### ISSUE THREAD

**Issue by Brendandurkin** [ToolJet/ToolJet#3284]
### Is your proposal related to a problem?
When supporting multiple applications or multiple instances of ToolJet (in separate environments)
Maintaining Data Source details can be a chore. particularly as data sourcesas defined within applications.
It would be better if the ToolJet system allowed custom environment settings, that could be used within data source fields.

### Describe the solution you'd like:
1. Allow the various property fields of data to reference variables derived from other data sources.
e.g. I would like to be able to describe the url of a rest api as being defined in the data source envsetttings.
`"dataSources":[`
`	{"id":...`
`     "kind":"restapi",`
`     "options":{`
`		 "url":{"value":"{{queries.envsettings.data.myresturl}}",`
`		  ....`
2. Create a datasource that always exists called "envsettings" (or something similar).
Obviously the env settings data source needs to be a custom data source as it may need to store passwords, and those passwords must not be visible or exportable.  It would be good if the values for settings could be imported and exported as json. The field values should be key, value and isPassword. (if isPassword is true value exported is blank or a 6 stars, or "<hidden>" or something like that)
Ideally the settings data source should be stored in the same db as the users.

### Describe alternatives you've considered
* Add a datasource type of JSON file.
* Add a datasource type that means the same db where the users are stored.
* Either  the env settings be viewable/updateable within ToolJet admin page or can you only import/export values as json.

### If the feature is approved, would you be willing to submit a PR?
no

**Comment by withshubh** [comment]
@gsmithun4 can you comment on this?

**Comment by withshubh** [comment]
Hey @Brendandurkin 👋 
We are working on this issue and we will let you know once it is released.
