### ISSUE TITLE
Add on-hover highlighting for data sources list on query panel

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#3295]
### Is your proposal related to a problem?

Presently, the data sources listed on query panel are not highlighted on hover
<img width="569" alt="image" src="https://user-images.githubusercontent.com/20333972/173810474-f407bc10-09cc-49d8-a7cc-ef7a15b0c026.png">

### Describe the solution you'd like

Add a small, fine highlight for the data source boxes when mouse pointer is hovered over them.
Appropriate styling should be applied for both light mode and dark mode.

**Comment by Osman-J** [comment]
Hi I'd like to work on this

**Comment by abdoachhoubi** [comment]
I'd suggest adding a box-shadow while hovering and setting the scale to 1.1

**Comment by Evavic44** [comment]
Hello, @sherfin94 I would love to work on this issue but I'm having a slight problem running ToolJet locally. Are there any guides to help with that?

**Comment by sherfin94** [comment]
Hey @Evavic44 , here is the [documentation for setting it up on MacOS](https://docs.tooljet.com/docs/contributing-guide/setup/macos), and [here is the documentation for setting it up on Ubuntu](https://docs.tooljet.com/docs/contributing-guide/setup/ubuntu). There is also a docker setup guide on the documentation if you'd like.

If this doesn't help you, reach out to us on our Slack community, we'll be there to help you out.

Do tell me if you'd like me to assign this issue to you.

**Comment by Syed-Ansar** [comment]
I would like to work on this issue, can assign it to me.

**Comment by Syed-Ansar** [comment]
Hey @sherfin94 can you assign this issue to me.

**Comment by shubh22** [comment]
Hi @Syed-Ansar, Assigned the issue to you. Looking forward to your solution.

**Comment by jashanshah33** [comment]
hi @sherfin94 , can i work on it.
