### ISSUE TITLE
[Query Manager]: Save & run button in disabled state post cancelling the query run

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#3308]
### Version Information
Latest

### Environment
All

### What is the expected behaviour?
Save & run button should reset

### What is the current behaviour?
Save & run button doesn't reset

### How to reproduce the issue?

1. Choose for Request confirmation before running query in query => advanced tab
2. Click Save & run
3. Click on cancel
4. The Save & run button doesn't reset 

### Please provide any traces or logs that could help here.
https://user-images.githubusercontent.com/12490590/174272807-9cd131bf-8484-491b-9b29-c53d8869f613.mov

**Comment by rw4nn** [comment]
Hey, I can work on this :+1:

**Comment by rw4nn** [comment]
Hey, sorry don't have much time anymore to work on this. I'll unassign, sorry about that.

**Comment by manishkushare** [comment]
This issue was fixed by #3641
