### ISSUE TITLE
Misaligned text in events section

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#3309]
### Version Information
All

### Environment
All

### What is the expected behaviour?
Text: Query doesn't have any event handlers should be aligned

### What is the current behaviour?
Text: Query doesn't have any event handlers is mis-aligned

### How to reproduce the issue?

1. Check SS

### Screenshots or Screencast
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/12490590/174273453-79681e9e-a125-4a1b-8f9b-7eb35b98a9e3.png">

**Comment by shubham199711** [comment]
Hi 

Can I take this issue up?

**Comment by gondar00** [comment]
@shubham199711 sure 👍

**Comment by shubham199711** [comment]
Hi @gondar00 Please find my pull request: https://github.com/ToolJet/ToolJet/pull/3318

Please review and approve. Thanks! 🚀

**Comment by withshubh** [comment]
Unassigned @shubham199711 as there was no update on the PR for more than 45 days.

This issue is up for grabs now.

**Comment by ashwin-acharya01** [comment]
Is this issue resolved? If not I would like to work on it
