### ISSUE TITLE
Change typography for run query confirmation box

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#3310]
### Version Information
All
### Environment
All

### What is the expected behaviour?
The text should also have the query name: **Do you want to run this query - ${queryname}?**

### What is the current behaviour?
The text says: **Do you want to run this query?**

### How to reproduce the issue?

1. Create a query
2. Select the query and go to advanced tab
3. Click request confirmation before run
4. run the query and observe the confirmation box

### Screenshots or Screencast
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/12490590/174274353-fa172552-f27d-4f72-89f0-2931fe45c31a.png">

**Comment by Syed-Ansar** [comment]
Hii @gondar00 can you assign me this issue I have debugged and found where is the bug. Or should I directly make a pull request.

**Comment by gondar00** [comment]
@Syed-Ansar assigned the issue to you

**Comment by Syed-Ansar** [comment]
Hey @gondar00 I have solved the bug. I just wanna confirm before making a pull request, is this the expected behaviour or should i have to make any changes.


<img width="1440" alt="Screenshot 2022-06-19 at 1 26 40 PM" src="https://user-images.githubusercontent.com/82027712/174478320-e3d7fb6f-764a-4416-a70b-517458e679bd.png">

**Comment by gondar00** [comment]
Yes this is expected behavior

**Comment by Syed-Ansar** [comment]
Okay. I will make a pull request then. Thank you.

**Comment by Syed-Ansar** [comment]
Hey @gondar00 I have made a pull request #3323 . Please review my PR.

**Comment by gondar00** [comment]
@Syed-Ansar left a few review comments

**Comment by Syed-Ansar** [comment]
I didn't understood what you are saying?

**Comment by Syed-Ansar** [comment]
Okay.
