### ISSUE TITLE
Able to see only one confirmation box for multiple queries with confirmation before running

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#3311]
### Version Information
Lastest 

### Environment
All

### What is the expected behaviour?
Should get a curated list of all the queries with request confirmation with an option to "run all"

### What is the current behaviour?
Getting the confirmation pop up only for the last element in the list

### How to reproduce the issue?

1. Create 3 queries
2. Advanced tab run on page load + request confirmation before running query set to true
3. Refresh the page
4. Observe only one popup which runs the last element in the query

### Screenshots or Screencast
Example ui: 
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/12490590/174276344-45b65382-d811-4591-9f59-94e371eed762.png">

**Comment by Mrityunjay1** [comment]
Hello, I would like to discus on this issue

**Comment by Mrityunjay1** [comment]
Facing some issue in the configuration of Db

**Comment by gondar00** [comment]
@Mrityunjay1 what issue you are facing? 
Feel free to join our [Slack](https://join.slack.com/t/tooljet/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg) group for quicker resolutions

**Comment by Mrityunjay1** [comment]
![Uploading IMG_20220620_123243.jpg…]()

**Comment by Mrityunjay1** [comment]
not able to setup db
