### ISSUE TITLE
`skip` button not visible in dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3327]
### What is the expected behaviour?

On the popup of `Finish ToolJet Installation` - the skip button should be visible in dark mode.

### What is the current behaviour?

On the popup of `Finish ToolJet Installation` - the skip button is not visible in dark mode.

### How to reproduce the issue?

1. Do a fresh install of ToolJet or login as a new user
2. Sign in and switch to dark mode
3. You'll get a popup to `Finish ToolJet Installation`

### Screenshots or Screencast
![Screenshot 2022-06-20 at 1 49 28 PM](https://user-images.githubusercontent.com/25361949/174558696-c83a7b69-5634-47c4-8c13-7040aed10551.png)

**Comment by withshubh** [comment]
Great! @akib22 
Assigned this issue to you.

**Comment by vedant-z** [comment]
Hey @withshubh I think I have figured out a solution for this....

But how should I check if it actually worked or not? I know I must clone this repository on my local system and then make the required changes....

Actually I am new to open source, so if you could guide me it would be of great help.

**Comment by akib22** [comment]
Hi @withshubh, hope you are doing well. I am trying to run the app using Docker, but I failed. I getting this error.

![error](https://i.ibb.co/MZjyqrz/Screenshot-from-2022-06-22-10-31-55.png)

```
OS: Ubuntu 20.04.4 LTS
Node: 14.17.3
NPM: 6.14.13
Docker: 20.1017
Docker-compose: 1.29.2
```

Can you please help me?

**Comment by withshubh** [comment]
@akshaysasidrn Please help here.

**Comment by TheLearneer** [comment]
Hi @withshubh this issues seems to be resolved with the merged PR, so I believe it can be closed 🙏
