### ISSUE TITLE
Server entrypoint.sh throws error on windows systems

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#3331]
### Version Information
all

### Environment
Windows

### What is the expected behaviour?
WSL2-based docker-compose should work on Windows systems.

### What is the current behaviour?
Running `docker-compose up` throws error due to disparity EOL characters on Windows machine as git by default has *autocrlf* set to * true* which converts `\n` to `\r\n`
`entrypoint.sh` file after cloning has CRLF EOL which needs to be changed to LF to have it working.

### How to reproduce the issue?
Try doing docker-compose up on windows after cloning the repo.

### Screenshots or Screencast
<img width="902" alt="image" src="https://user-images.githubusercontent.com/11629675/174584728-98b704e0-1114-4ba7-9dc7-87eda2bc6013.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/11629675/174584783-5a928123-b40f-42a5-907d-9ea1c4063bb1.png">

### Please provide any traces or logs that could help here.

```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

### Any possible solutions?
Add .gitattributes file to standardize files b/w Operating systems.

### If the bug is confirmed, would you be willing to submit a PR?
yes

**Comment by PaulMcF1987** [comment]
With regards to my post  - https://github.com/ToolJet/ToolJet/issues/3051
This was not on a windows based system.
Docker is hosted on an Ubuntu 18.04 web server

**Comment by withshubh** [comment]
Hey @akshaysasidrn 
Can you please take a look at the issue created by @PaulMcF1987 and reopen it.
