### ISSUE TITLE
Password reset: accepting blank space as a password

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3335]
### Environment

app.tooljet.com

### What is the expected behaviour?

- It should not save if the password field has only blank space as a password.

### What is the current behaviour?

- It accepts blank space as a password.

### How to reproduce the issue?

- Please refer to the screencast

### Screenshots or Screencast

[Video](https://www.loom.com/share/7ee4ab252eb848718917fcf114fa6ff8)

**Comment by Syed-Ansar** [comment]
Yes! I have tried this and It is accepting password. But if we login with space it is not logging in. Here, I wanna ask that should there be any validation like No of letters, non-spaces, special Characters to resolve this bug.

**Comment by gsmithun4** [comment]
> Yes! I have tried this and It is accepting password. But if we login with space it is not logging in. Here, I wanna ask that should there be any validation like No of letters, non-spaces, special Characters to resolve this bug.

Hi @Syed-Ansar the password complexity and policies under discussion, will be implementing soon
