### ISSUE TITLE
Nested tabs: Children of inner tabs does not disappear when outer component's tab is switched

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#3348]
### Environment

Mac OS
### What is the expected behaviour?

In the scenario of a tabs component being inside another tabs component, the children of the inner tabs is visible even if the tab containing the inner tabs component is changed.
### What is the current behaviour?

In the scenario of a tabs component being inside another tabs component, the children of the inner tabs must be invisible if the tab containing the inner tabs component is changed.
### How to reproduce the issue?

1. Add a tabs component
2. Add a tabs component inside it
3. Add something inside the inner tabs component
4. Change the outer tab
5. Observe that the children of the inner tab is still visible

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by TheLearneer** [comment]
Hi @withshubh this seems to be fixed by the merged PR as well 🙏

**Comment by withshubh** [comment]
Thanks for the heads up! @TheLearneer
