### ISSUE TITLE
grey border at the bottom of the dashboard

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3379]
### What is the expected behaviour?

The dashboard's container height should be responsive.

### What is the current behaviour?

There is a grey space at the bottom of the dashboard.

### How to reproduce the issue?

1. Log in to ToolJet
2. Check the bottom of the dashboard

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2022-06-21 at 7 06 25 PM" src="https://user-images.githubusercontent.com/25361949/175482427-be97b492-7766-4d5c-95f4-1db50c0a5ad8.png">

<img width="1437" alt="Screenshot 2022-06-21 at 7 06 57 PM" src="https://user-images.githubusercontent.com/25361949/175482453-b8bbede5-25b5-4d56-b26b-06105fdc84c5.png">

**Comment by OndrejHj04** [comment]
Hi. I am newbie to open source. I am really happy that I have found an issue that fits my skill level. I would like to contribute to this project but I am facing some dummy problems.

1. Is there a key or hint how to find which react component does represent this dashboard? In frontend/src I didnt find any component/folder named Dashboard.
2. After I will find the right component is possible to start it on localhost? To see the changes that I have made.

**Comment by Syed-Ansar** [comment]
I would like to work on this can you assign me this issue

**Comment by OndrejHj04** [comment]
> I would like to work on this can you assign me this issue

Hello I see that you are a contributor at this repo, can you maybe answer my questions? I will be pleased. Thank you

**Comment by Syed-Ansar** [comment]
> > I would like to work on this can you assign me this issue
> 
> Hello I see that you are a contributor at this repo, can you maybe answer my questions? I will be pleased. Thank you

Btw I am also new to open-source. But would like to help as ToolJet community is the one of the best Community. You can reach-out for help on [Slack](https://tooljet.slack.com/join/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg#/shared-invite/email).  Do you want me to say where to make changes in repo ?

**Comment by OndrejHj04** [comment]
@Syed-Ansar  Hi! Now I would like to know how to make this site visible on localhost and after changes in the code the localhost would reload. Do you know how to do this?

**Comment by OndrejHj04** [comment]
> > > I would like to work on this can you assign me this issue
> > 
> > 
> > Hello I see that you are a contributor at this repo, can you maybe answer my questions? I will be pleased. Thank you
> 
> Hey @OndrejHj04 Btw I am also new to open-source. But would like to help as ToolJet community is the one of the best Community. You can reach-out for help on [Slack](https://tooljet.slack.com/join/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg#/shared-invite/email). Do you want me to say where to make changes in repo ?

How did you spin up the localhost?

**Comment by Syed-Ansar** [comment]
You can go to [**ToolJet**](https://docs.tooljet.com/docs/) and to contributing Guide and can refer how to setup local development environment. Setup guide is pretty understandable, if you face any issues you can reach-out for help in Slack #general. You will get 100% response from ToolJet team. Good Luck 🚀

**Comment by OndrejHj04** [comment]
> You can go to [**ToolJet**](https://docs.tooljet.com/docs/) and to contributing Guide and can refer how to setup local development environment. Setup guide is pretty understandable, if you face any issues you can reach-out for help in Slack #general. You will get 100% response from ToolJet team. Good Luck 🚀

OK! I will try it. Thank you very much!

**Comment by rashmod** [comment]
Is this issue still open?
@OndrejHj04 are you still working on this issue or can I can do this?

**Comment by OndrejHj04** [comment]
> Is this issue still open?
> @OndrejHj04 are you still working on this issue or can I can do this?

You can nail this one!

**Comment by shivangT** [comment]
Hello @rashmod,
Are you willing to work on this issue? Please confirm before I assign this to you.

@Syed-Ansar Thanks for sharing about Tooljet.

Hey @OndrejHj04,
Let me know if you would like to work on other good first issues. I can help you in selecting a few of them. 

Thanks & have a great time working on ToolJet.
