### ISSUE TITLE
UX issues around launch/deploy

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#338]
Problem: 

Most of the users click on `launch` button before deploying the app. The process of create version -> deploy -> launch isn't obvious to new users and they end up with a blank page when an app is launched.

Quick solution:
Disable the launch button and show a tooltip if `current_version` property of an app is empty.

**Comment by vishnuchandrappan** [comment]
@Navaneeth-pk 
Can I take this up ?

**Comment by Navaneeth-pk** [comment]
@vishnuchandrappan Sure, assigning the issue to you :) Thanks.
