### ISSUE TITLE
[image widget] background color field doesn't display the hex-code and color box

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3385]
### What is the expected behaviour?

The background-color field should display the hex code and the color box.
![Screenshot 2022-06-24 at 2 31 55 PM](https://user-images.githubusercontent.com/25361949/175502635-958de8a9-4f0c-4c49-b54e-003ab63c452c.png)

### What is the current behaviour?

The background-color field is there but the color code and the color box is not there.

### How to reproduce the issue?

1. Add the image widget on the canvas
2. Click on the image widget's handle to open its properties on the right sidebar
3. Go to **Styles**
4. Check background-color field

Note: While fixing this issue, make sure the default background color is set to transparent.

### Screenshots or Screencast

<img width="730" alt="Screenshot 2022-06-24 at 1 56 52 PM" src="https://user-images.githubusercontent.com/25361949/175502857-4a4713d5-5a0c-4acf-8ad5-b90214266991.png">

**Comment by swetha789** [comment]
Hi, I would like to solve this issue. Can you please assign this to me.

**Comment by withshubh** [comment]
@swetha789 Assigned this issue to you. 🚀

**Comment by swetha789** [comment]
Hi, this is my first time contribution, I am trying to set up the environment locally using the documentation https://docs.tooljet.com/docs/setup/docker-local/ 

I am unable to login using the credentials provided above. Is there any other way I can try?

Thank you,
Swetha.

**Comment by withshubh** [comment]
Hi @swetha789 👋 

The doc you followed is only for trying out ToolJet locally using the Docker, not for setting up ToolJet locally for contributing.

Please follow this setup guide: https://docs.tooljet.com/docs/contributing-guide/setup/docker

Also, I'd suggest you join our [Slack Community](https://join.slack.com/t/tooljet/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg) - you can post your questions over there if in case you need any help.
