### ISSUE TITLE
[Table] date-picker column type should not display anything if the data is empty

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3418]
### What is the expected behaviour?

If we add a column in the table and set its type as `Date Picker` then it should not display `Invalid date` or anything if the data is empty.

### What is the current behaviour?

Currently, when we add a column in the table and set its type as `Date Picker` - it shows `Invalid date` in those cells that have empty data

### How to reproduce the issue?

1. Add data in the table that has date field with and without data
2. Add a column in the table
3. Set column type as `Date Picker`

### Screenshots or Screencast

![image (5)](https://user-images.githubusercontent.com/25361949/176167229-37ca15d7-2adf-4525-b178-8941605f2adf.png)

**Comment by eyuelberga** [comment]
Hey @withshubh can I work on this?

**Comment by withshubh** [comment]
Sure! Assigned to you. @eyuelberga
