### ISSUE TITLE
[Multiselect widget] Label text not clearly visible in dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3437]
### What is the expected behaviour?

The color of the label text of the Multiselect widget should change to dark color.

### What is the current behaviour?

The color of the label text of the Multiselect widget remains white in dark mode.

### How to reproduce the issue?

1. Toggle on dark mode and open the app editor
2. Drag multiselect widget on the canvas
3. The label will not be clearly visible 

### Screenshots or Screencast
<img width="1438" alt="Screenshot 2022-06-29 at 5 01 09 PM" src="https://user-images.githubusercontent.com/25361949/176518987-41474c70-3c23-4c6b-80ba-d06eb50eec82.png">

**Comment by jonandonigv** [comment]
Hi, can I get this issue?

**Comment by withshubh** [comment]
Sure @jonandonigv 
Assigned to you. 🚀

**Comment by withshubh** [comment]
Hey @jonandonigv 👋 
Are you still working on this issue?

**Comment by jonandonigv** [comment]
Hey @withshubh , yes I'm still working on the issue but, I'm with covid and I'm having problems working in the issue because of that

**Comment by withshubh** [comment]
No worries! Get well soon. @jonandonigv
