### ISSUE TITLE
Resizing of table columns triggeres sort action

### ISSUE THREAD

**Issue by jtseven** [ToolJet/ToolJet#3471]
### Version Information
v1.19.0
### Environment
 Docker

### What is the expected behaviour?
When resizing a column on the table component within tooljet, the width of the column should change without anything else happening.

### What is the current behaviour?
When one drags and drops on the border of two columns in the table widget it is possible to change the width of the column, but at the same time the table is sorted by that column, as if one clicks on the column header.

### How to reproduce the issue?

1. Create a webapp with Tooljet using the table component.
2. Add multiple columns with data to the table.
3. Try to resize the width of a column.
4. While the resize works the whole table is also sorted by that column.

### Screenshots or Screencast
![tooljet_bug](https://user-images.githubusercontent.com/11011511/177161704-8978394c-dabf-4ec2-95d1-91c3431e2684.gif)

### Please provide any traces or logs that could help here.
Please request, if needed

**Comment by shivangT** [comment]
Hey @jtseven 

Let us recreate this issue and get back to you. Thanks for letting us know.

Apologies for reaching out late.
