### ISSUE TITLE
Radio button widget doesn't selects the default value when dragged

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3509]
### What is the expected behaviour?

By default, the `default value` of the Radio button is set to `{{true}}`, so whenever it should be dragged on the canvas the `Yes` option should be selected by default as the value is set to `{{true}}`.

### What is the current behaviour?

Whenever the Radio button is dragged on the canvas there is no option selected, although the `default value` is set to `{{true}}` by default.

### How to reproduce the issue?

1. Drag the radio button on the canvas
2. Check the Default Value property on the right sidebar (set to `{{true}}`)

### Screenshots or Screencast

![radio-btn](https://user-images.githubusercontent.com/25361949/177531571-f285d054-d171-4b02-ad13-f0b0808d8262.gif)

**Comment by fpetrakov** [comment]
hey, I would like to try to solve this issue :)

**Comment by withshubh** [comment]
Hey @fpetrakov 👋 
Assigned to you.

**Comment by SagarSamtani** [comment]
I am interested in solving this issue.

**Comment by Shelly011s** [comment]
hey @withshubh I am interested in solving this issue.

**Comment by withshubh** [comment]
Hey @SagarSamtani 👋 
Assigned this issue to you.

**Comment by withshubh** [comment]
> hey @withshubh I am interested in solving this issue.

Hey @Shelly011s 👋 
Thanks for your interest. We assign issues on a first come first serve basis, can you check other open issues and pick one?
We are also participating in Hacktoberfest. Check out this blog to learn more: https://blog.tooljet.com/hacktoberfest-2022/
