### ISSUE TITLE
Home Page has a border drawn at the bottom

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#3519]
### What is the expected behaviour?
There should not be any border on the bottom of the page where we have pagination.

### What is the current behaviour?
There is some kind of border present on the bottom.

### How to reproduce the issue?

1. Create several applications(till the application has to go to the next page)
2. Observe the bottom

### Screenshots or Screencast

<img width="1419" alt="Screenshot 2022-08-18 at 12 36 24 PM" src="https://user-images.githubusercontent.com/32157641/185328544-4caab534-eb09-4d5a-856a-ec559e71aa33.png">

**Comment by pateketrueke** [comment]
I don't think this is an issue, because such border indicates the scrolling area above... otherwise, you'll get such items cutted from the bottom, and that's a real issue. 🤔

**Comment by SagarSamtani** [comment]
I am interested in solving this issue.

**Comment by shivangT** [comment]
Hey @SagarSamtani ,

Thanks for showing interest in working on the issue. I'm assigning this issue to you.
Let me know if you need help with the code setup or anything.
Have a great time working on Tooljet.

**Comment by SagarSamtani** [comment]
Thanks @shivangT 

Yes I am facing issue in setup, I followed the setup doc for mac os, following is the screenshot for the same - 

<img width="1432" alt="setup issue" src="https://user-images.githubusercontent.com/6712251/185335931-c9382dbd-86b8-42c8-a725-ed67377644a8.png">

**Comment by shivangT** [comment]
Hello @SagarSamtani 

Kindly post this with relevant screenshots on our  [Slack](https://tooljet.slack.com/join/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg#/shared-invite/email) channel. 
You'll be able to quickly get a response and resolve it. 

Thanks

**Comment by himanshu-suman** [comment]
Hi @shivangT ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by vinzesiddharth29** [comment]
Greetings, @SagarSamtani 

This issue seems to be a good initiation of my journey towards contribution to FOSS project. Could you please assign this issue to me?

**Comment by shivangT** [comment]
Hey @SagarSamtani 
Any update on this? Let me know if you're stuck with something.

**Comment by SagarSamtani** [comment]
@shivangT I am stuck at setup part. 
Can you or Akshay connect over call ?
I have shared all possible screenshots on slack.

**Comment by exitflynn** [comment]
Hello! I wonder if this issue is still being worked on, I'd love to take it up! 🤠

**Comment by jashanshah33** [comment]
hi @Nandinisaha13, can i work on it

**Comment by withshubh** [comment]
Hey @exitflynn - are you interested in picking up this issue?

**Comment by withshubh** [comment]
Closing the issue as we have revamped the UI in ToolJet v2.
