### ISSUE TITLE
[docs]:Add examples to elaborate the properties

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3573]
### What is the expected behaviour?
Suggest examples with enriched texts so that it's easier for users to learn easily how to use them.

### What is the current behaviour?
The single-liner text makes it difficult for the reader to understand.

### How to reproduce the issue?

1. Visit https://docs.tooljet.com/docs/widgets/datepicker
2. Scroll down to the "Custom validations" and "Disabled Dates" sections
3. Suggest examples for each to help users learn more

### Screenshots or Screencast

<img width="1130" alt="Screenshot 2022-07-11 at 3 48 07 PM" src="https://user-images.githubusercontent.com/32157641/178243148-2a750aed-5160-4c6e-82c7-48cf485c35f8.png">

<img width="872" alt="Screenshot 2022-07-11 at 3 48 23 PM" src="https://user-images.githubusercontent.com/32157641/178243186-eba20a6d-a35d-4d70-ae68-fbd24a5d0388.png">

### Any possible solutions?

You can copy the following example or create of your own. Please validate if you add your own.

a) For **Custom validations** elaborate with the following example.

**Code**:
```{{moment(components.datepicker1.value, 'DD/MM/YYYY').isAfter(moment()) ? true : 'Date should be after today'}}```

**Explanation**: This ensures that an error will be shown if the date selected is not in the future.

b) For the **Disabled dates** use the following example.

**Code**:
```{{['05-01']}}```

**Explanation**: Users wont to be able to select the following date. It will be disabled.

**Comment by YashPimple** [comment]
@shivangT Can you assign this issue to me . I would like to work on it .

**Comment by shivangT** [comment]
Hi @YashPimple 
Sure, assigning this to you.

**Comment by shivangT** [comment]
Hello @arpitnath 
Can you quickly review this when you're available?
Thanks

**Comment by arpitnath** [comment]
HI @YashPimple, can you please raise a Pull Request on our Repo and not on the forked one?

**Comment by YashPimple** [comment]
Sure!
