### ISSUE TITLE
[docs]: Feature text explanation missing in all widgets 

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3574]
### What is the expected behaviour?
Please add a section like other docs explaining the tooltip property.

### What is the current behaviour?
When we inspect the date picker widget, we scroll down to expand
General > Tooltip. There is an available section explaining the tooltip property.

### How to reproduce the issue?

1. Go to  https://docs.tooljet.com/docs/widgets/datepicker/
2. Under properties add a section called General - Tooltip 
3. Explain the following

**Comment by YashPimple** [comment]
Heyy @shivangT  I would like to work on this issue !

**Comment by shivangT** [comment]
Hey @YashPimple ,
Sure, I'm assigning this issues to you.

**Comment by YashPimple** [comment]
@shivangT can you please update the content required to add in  tooltip section?

**Comment by shivangT** [comment]
Hey @YashPimple 
The content for Tooltip needs to be updated for all the widgets. We're drafting the content so it might take some time. 
Can you look into this [issue](https://github.com/ToolJet/ToolJet/issues/3573)?  The detailed information is available in the description. 
Please comment on this link to get it assigned.

Removing you from this issue. 
Thanks

**Comment by YashPimple** [comment]
Sure!
