### ISSUE TITLE
Add toggle button to enable widget properties

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3576]
### What is the expected behaviour?

Add buttons for “Enable time selection” & “Enable date selection”, so that users can easily toggle true and false values.

### What is the current behaviour?

Toggle button missing in “Enable time selection” & “Enable date selection”  properties.

### How to reproduce the issue?

1. Go to this [link](https://app.tooljet.com/)
2. Now click on "create new application" 
3. Now drag and drop the date-picker widget from the widgets inventory
4. Inspect the widget and scroll down to its properties panel on the right
5. Now under sections “Enable time selection” & “Enable date selection” we have to add toggle buttons 

### Screenshots or Screencast

<img width="295" alt="Screenshot 2022-07-11 at 4 12 57 PM" src="https://user-images.githubusercontent.com/32157641/178247293-dc10b7ff-9583-4a73-b8d8-4f4e2faa2525.png">

### Any possible solutions?

Refer to other widgets by inspecting them to learn about the UI.

**Comment by kaggrwal** [comment]
@shivangT Can you assign this issue to me, let me take a look at this.

**Comment by kaggrwal** [comment]
@withshubh @shubh22 please review and merge 
https://github.com/ToolJet/ToolJet/pull/4255
