### ISSUE TITLE
Enable time-picker widget container clickable

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3577]
### What is the expected behaviour?

When enabling time selection to true, we’re unable to select the time by clicking the time option in the drop-down. 
It only appears when we click on the clock icon. 
- Make the container clickable, and 
- Change the cursor value to pointer in order to make it appears clickable.
- Also apply padding around the clock selection conatiner.

### What is the current behaviour?

When enabling time selection to true, we’re unable to select the time by clicking the time option in the drop-down. 
It only appears when we click on the clock icon. 

### How to reproduce the issue?

1. Go to this [link](https://app.tooljet.com/)
2. Now click on "create new application"
3. Now drag and drop the date-picker widget from the widgets inventory
4. Inspect the widget and scroll down to its properties 
6. “Enable time selection” -> {{true}} & “Enable date selection” -> {{false}} 
7. Click on the date-picker widget and click to enter a time.

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2022-07-11 at 4 31 01 PM" src="https://user-images.githubusercontent.com/32157641/178250278-7607d6c0-2b5c-43d3-adfe-9114e6340dbf.png">

**Comment by shivangT** [comment]
Hello @sherfin94 
Can you assign this to someone? Manish was looking into it but he needs help to resolve this.

**Comment by taranpreet-singh1** [comment]
@shivangT Hi there, Can I work on this issue? If yes, Kindly assign it to me.
Thank you

**Comment by shivangT** [comment]
Hello @taranpreet-singh1 

Sure, I am assigning it right away. Please reach out on slack if you have trouble
with anything. Have a good time. :) 

Thanks

**Comment by shivangT** [comment]
Hello @taranpreet-singh1 
any update on this?

**Comment by antoniusanggito** [comment]
Hello @shivangT I am interested to work on this issue as my first one. Would highly appreciate for an assignment.
Thankyou

**Comment by Sparsh-Malhotra** [comment]
Hey @shivangT I would like to work on this issue. Please assign it to me

**Comment by Sanjayrk0206** [comment]
Hey @shivangT, I am interested in working on this issue. Can you assign it to me?

**Comment by AyushK-101** [comment]
@shivangT can you maybe make a video clip of the issue, it is working fine in my app
