### ISSUE TITLE
[docs]: Tooltip information missing in the all the widget's properties

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3584]
What is the expected behaviour?

List & explain the Tooltip property.

What is the current behaviour?

No information on the tooltip is present in the properties section.

How to reproduce the issue?

1. Go to this [link](https://docs.tooljet.com/docs/widgets/container/)
2. Write about Tooltip under general properties In the doc
3. Please communicate the content that needs to be updated.

**Comment by vedant-z** [comment]
@shivangT 

https://github.com/ToolJet/ToolJet/blob/develop/docs/docs/widgets/container.md

If I am not wrong this file needs to be updated....

But I am not able to figure out where should the TOOLTIP INFORMATION be added (General properties is not visible)

**Comment by vedant-z** [comment]
@shivangT 

https://github.com/ToolJet/ToolJet/blob/develop/docs/docs/widgets/container.md

If I am not wrong this file needs to be updated

But I am not able to figure out where should the TOOLTIP INFORMATION be added (General properties is not visible)

**Comment by shivangT** [comment]
Hello @vedant-z 
Can you skip this issue?  Someone from the internal team is working on this. 
I can assign you a similar issue if you want to work on it?
Let me know
Thanks

**Comment by vedant-z** [comment]
@shivangT Yes I would like to work on a similar one

**Comment by shivangT** [comment]
Hey @vedant-z 
Please follow these steps:

1. Visit this issue link -[3688]( https://github.com/ToolJet/ToolJet/issues/3688)
2. Comment on the issue so that I can assign it to you
3. Set up your code base if you're a new contributor and start coding 😀

Let me know if you need any help with the setup. 
Have a great day!!
