### ISSUE TITLE
[docs]: Content update in Tabs widget

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3593]
### What is the expected behaviour?

Provide information for "Hide Tabs" on the document page under the "Properties section". 

### What is the current behaviour?

There is no information regarding "Hide tabs". Update the document in a similar hierarchy:

Properties 
 1. Default Tab 
 2. Hide tabs

### How to reproduce the issue?

1. Go to this [Link](https://docs.tooljet.com/docs/widgets/tabs#properties)
2. Update the content here
3. Please communicate the content that needs to be updated.

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-07-12 at 6 24 16 PM" src="https://user-images.githubusercontent.com/32157641/178494701-1b75d7a5-5b3f-4dbc-b26e-05d987c3c700.png">

**Comment by YashPimple** [comment]
I would like to work on this issue ? Can you please elaborate it since it is my First Contribution projects ?

**Comment by shivangT** [comment]
Hello @YashPimple

Thank you for showing interest in the issue. Can you make the basic codebase setup? By then I'll post the content that needs to be updated here. Let me know if you face any trouble with the setup.
Have a great day coding on Tooljet.

**Comment by YashPimple** [comment]
Sure !

**Comment by shivangT** [comment]
Thank you

**Comment by shivangT** [comment]
Hello @YashPimple ,
Sure give me some time to update it. Thanks

**Comment by YashPimple** [comment]
Thank You
