### ISSUE TITLE
[ Feature ] :: Component specific actions table widget

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#3601]
### Is your proposal related to a problem?

Currently no implementation to clear , set data and select row through RunJS query , in table widget.

### Describe the solution you'd like

Add component specific action for table widget .
- Cleardata
- SelectRow
- Setdata

**Comment by developer-honoru** [comment]
I'm looking for it too, but I can't find it. Did you find it?

**Comment by shubh22** [comment]
This is available now in ToolJet 2.0
