### ISSUE TITLE
[Bug] : Color Picker icon is not visible in the widget inspector

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#3626]
### Environment
ToolJet Cloud

### What is the expected behavior?
Color Picker icon must be visible in the widget inspector

### What is the current behavior?
The Color Picker icon is not visible in the widget inspector

### Screenshots or Screencast

<img width="209" alt="Screenshot 2022-07-18 at 1 01 06 PM" src="https://user-images.githubusercontent.com/37823141/179467045-cc054878-f083-41af-a28f-fbb5f6d4caae.png">

### Any possible solutions?
Rename the SVG file of the color picker icon to all small case alphabets

**Comment by kavinvenkatachalam** [comment]
@manishkushare Can you confirm the issue got fixed in the cloud and close the issue?

**Comment by manishkushare** [comment]
@kavinvenkatachalam ,  yes it working well now, color picker widget icon is displaying.

**Comment by manishkushare** [comment]
![Screenshot 2022-08-22 at 4 37 28 PM](https://user-images.githubusercontent.com/37823141/185907498-0d057fd5-fbc5-46fd-b42f-af194b5773c0.png)
