### ISSUE TITLE
[ BUG ] :: Clicking on close should take to widget list in widget panel 🐛 

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#3628]
### What is the expected behaviour?
Clicking on close should take to widget list in widget panel

### What is the current behaviour?
Clicking on close we go to a intermediate state saying "Please select a component to inspect"
### How to reproduce the issue?

1.Click on label of any widget 
2.Close properties

### Screenshots or Screencast

https://user-images.githubusercontent.com/31006028/179496000-73d859a5-363a-4d76-bc2c-c94abbef247b.mov

### If the bug is confirmed, would you be willing to submit a PR?
Yes.

**Comment by withshubh** [comment]
https://github.com/ToolJet/ToolJet/issues/3050 Is this issue similar? @stepinfwd
