### ISSUE TITLE
Width of the widget handle should adjust according to the name

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3630]
### What is the expected behaviour?

Width of the widget handle should adjust according the length of widget name and the delete button next to it.

### What is the current behaviour?

Currently, widgets like password input, vertical divider and many others with longer widget names have widget name and delete button going out of bound (Please go through all the widgets with longer names)

### How to reproduce the issue?

1. drag widgets on the canvas
2. hover through their handle

### Screenshots or Screencast

https://user-images.githubusercontent.com/25361949/179498666-e81e0eda-64f0-42ef-9a4c-e0c625aa529b.mov

**Comment by withshubh** [comment]
Hey @UtkarshDixit-py 
Assigned this to you. Thanks for your interest in contributing to ToolJet.

**Comment by AAYUSH-droid** [comment]
Hey i would like to work on this issue.

**Comment by withshubh** [comment]
Hey @AAYUSH-droid 
Assigned this to you.

**Comment by withshubh** [comment]
Hey @UtkarshDixit-py 
Let me know if you're still working on this issue.
Else we can assign this @AAYUSH-droid

**Comment by UtkarshDixit-py** [comment]
@withshubh I resolved this issue and submitted the PR which is still to be reviewed by @stepinfwd

**Comment by withshubh** [comment]
> @withshubh I resolved this issue and submitted the PR which is still to be reviewed by @stepinfwd  

Great! Can you please link the PR to this issue?

**Comment by UtkarshDixit-py** [comment]
@withshubh I am not able to link it the PR to this issue but here is the branch name --> utkarsh/issue_3630

**Comment by UtkarshDixit-py** [comment]
As i am not able to work on this issue. @withshubh you can go ahead and assign @AAYUSH-droid .

**Comment by withshubh** [comment]
Hey @AAYUSH-droid - are you still willing to work on this issue?

**Comment by exitflynn** [comment]
Hello there @shubh22 I'd love to work on this issue! Could you please assign it to me? 🤠

**Comment by withshubh** [comment]
Hey @UtkarshDixit-py 
Unassigning it as there was no update on it for the long time.

**Comment by withshubh** [comment]
Hi @exitflynn , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hey @exitflynn - Any updates on the PR?

**Comment by emidhun** [comment]
Closing this issue since it is already fixed.
