### ISSUE TITLE
Folder icons should be visible in dark mode.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3647]
### What is the expected behaviour?
Folder icons should be visible in dark mode.

### What is the current behaviour?
Folder icons are not clearly visible in dark mode.

### How to reproduce the issue?

[Video](https://www.loom.com/share/5844a9c7346041368d81c20e87e90ea0)

**Comment by UtkarshDixit-py** [comment]
Hey I would like to work on this issue

**Comment by withshubh** [comment]
Hey @UtkarshDixit-py 👋 
Assigned the issue to you.

**Comment by UtkarshDixit-py** [comment]
Hey I've made it 2 shades darker does that work?file:///home/utkarshdell/Pictures/Screenshots/Screenshot%20from%202022-07-26%2012-03-14.png
-58:-90:84:78

**Comment by UtkarshDixit-py** [comment]
![Screenshot from 2022-07-26 12-03-14](https://user-images.githubusercontent.com/60638489/180939852-ba615744-cee1-4bb9-a10c-b3bccb5f206e.png)

Hey @ajith-k-v I've made the the logo 2 shades darker does that work?

**Comment by ajith-k-v** [comment]
Hey, @UtkarshDixit-py this one looks better. can you try some contrasting colours instead of darker shades?

**Comment by UtkarshDixit-py** [comment]
![image](https://user-images.githubusercontent.com/60638489/180942779-4c45b203-a652-41c8-9c86-57ee0e99e962.png)
 
@ajith-k-v it already turns blue when we it is selected so I cant use blue and any other color will not go with tooljet's theme. Also as of now icon color remains same in both dark mode and light mode.

**Comment by withshubh** [comment]
@gondar00 Do you have any suggestions for this ☝️ ?

**Comment by gondar00** [comment]
I don't this issue exists on latest develop branch: 

<img width="921" alt="Screenshot 2022-08-03 at 5 31 24 PM" src="https://user-images.githubusercontent.com/12490590/182607809-a309b526-2f45-40ab-871e-ee5e8a86de2a.png">

checked on version: 1.21.5 CE

**Comment by withshubh** [comment]
Closing as the issue has been fixed already
