### ISSUE TITLE
[docs]: Documentation improvements

### ISSUE THREAD

**Issue by kvaithin** [ToolJet/ToolJet#3655]
### Summary

Notice that the docs doesn't cover details on how exactly to run this project locallly.

Example: 

Information on recommended node version.

There is a docker script given that runs. But no information given on what email and username to use.
When you try ti sign up, we get an alert that email is sent and to check email although no email received.
Is presumably just a message and email is not sent. 

Would help to get clear details on how to run it locally to aid in testing it and picking up issues. 

-----

Don't think I am the best person to raise PR for it. 
But happy to do it if can be guided on how I could obtain the details for it. 

### Issue Type

Documentation feature/update

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by withshubh** [comment]
Hey @kvaithin - Which documentation are you following, the [Setup](https://docs.tooljet.com/docs/setup/docker) one or the [Contributing Guide](https://docs.tooljet.com/docs/contributing-guide/setup/docker) one?

**Comment by joy-amoga** [comment]
Use this to set up on your local machine. 
https://docs.tooljet.com/docs/contributing-guide/setup/macos

**Comment by withshubh** [comment]
Hey @kvaithin 
Closing this issue. If you have any doubts/questions feel free to post on #general in our [slack community](https://join.slack.com/t/tooljet/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg).
