### ISSUE TITLE
Airtable Listing Records - Pagination Not Working

### ISSUE THREAD

**Issue by yapnel** [ToolJet/ToolJet#3656]
### Version Information
1.20.4 version
### Environment
Docker

### What is the expected behaviour?
Expecting the table component to display all the records from Airtable table using the Listing Records query after providing the offset using {{queries.airtable1.rawData.offset}}

### What is the current behaviour?
The table component is only showing 100 records. Even changing to sever side pagination it is still the same.

### How to reproduce the issue?

1. Create an Airtable Listing Records query
2. Enable Transformation
   `return data.records.map(row => {
let obj = {}
obj.fields = row.fields
obj.fields.id = row.id
return obj.fields
});`
4. Enter {{queries.airtable1.rawData.offset}} as the offset
5. Save and Execute
6. Bind the query to the Table component

**Comment by arpitnath** [comment]
@yapnel Hi!
We tried to reproduce but it worked fine. The initial offset will be undefined, as the offset is being resolved from the returned data after the query is being run.
Enter the offset `{{queries.airtable1.rawData.offset ?? null}}`
If it does not resolve your issue, feel free to join our highly active **[Slack Community](https://join.slack.com/t/tooljet/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg)**.
