### ISSUE TITLE
[docs]: Correct the mis-spell in the text input doc

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3688]
### What is the expected behaviour?

**Correct Text**:
"Toggle on or off to display the widget in desktop view. You can programmatically determine the value by clicking on Fx to set the value {{true}} or {{false}}."

**Note:** Please remove the "" while you copy and paste

### What is the current behaviour?

**Current text**: 
"Toggle on or off to display the widget in desktop view. You can programmatically determing the value by clicking on Fx to set the value {{true}} or {{false}}."

### How to reproduce the issue?

1.  Go to this [link](https://docs.tooljet.com/docs/widgets/text-input)
2.  Scroll below to layout property
3. Refer to the screenshot to find the mistake

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-07-27 at 5 55 15 PM" src="https://user-images.githubusercontent.com/32157641/181246141-487f9f12-2aa0-43c6-bfc7-64898884ca7b.png">

**Comment by vedant-z** [comment]
@shivangT 

Sir, Assign this to me 😊

**Comment by shivangT** [comment]
That was a quick one, thanks for the update.
We'll get it reviewed and close it soon. 
Please check for the issue log to work on simple and complex issues. 
Have a great day
