### ISSUE TITLE
Grammatical error in DATEPICKER Doc

### ISSUE THREAD

**Issue by vedant-z** [ToolJet/ToolJet#3691]
### Summary

I was reading the ToolJet documentation for Datepicker, there seems to be grammatical mistake in DEFAULT VALUE section.

Current Text: The default value needs to a `String` with respect to...

Expected Text: The default value needs to be a `String` with respect to...

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/datepicker/

### Additional Information

![IMG_20220728_084134.jpg](https://user-images.githubusercontent.com/93431609/181412241-ef0bb575-7cfd-45be-908e-784d49ecb845.jpg)

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Shednandez** [comment]
Open issues

**Comment by vedant-z** [comment]
@Shednandez 

I didn't understood what do you want to say

**Comment by Shednandez** [comment]
Yes

**Comment by Shednandez** [comment]
Mention

**Comment by Shednandez** [comment]
> Yes

Fix bug

**Comment by vedant-z** [comment]
@Shednandez Ohh!!

Thanks for confirmation ☺️
