### ISSUE TITLE
Security issue 

### ISSUE THREAD

**Issue by Gaurav-G2** [ToolJet/ToolJet#3704]
There is a critical severity security issue .The issue has been reported via huntr.dev .The details of this security issue have been communicated via email . following the security policy guidelines.

Report urls:-
https://huntr.dev/bounties/86881f9e-ca48-49b5-9782-3c406316930c/
https://huntr.dev/bounties/5ae82923-dc6d-4ddf-ac3e-c4f4ec7b5be6/

**Comment by withshubh** [comment]
Hey @Gaurav-G2 
Thanks for creating the issue. Can you please share the same over email to `security@tooljet.com`?
