### ISSUE TITLE
Success message not displayed clearly in dark mode in advanced option for queries

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#3714]
### What is the expected behaviour?
While we type something in the success message then it should be clearly visible in dark mode.

### What is the current behaviour?
While we type something in the success message it is not clearly visible in dark mode.

### How to reproduce the issue?

1. Add any query.
2. Click on dark mode icon.
3. Go to advanced tab.
4. Toogle on show notification on success?
5. Enter something in the success message.

### Screenshots or Screencast
https://drive.google.com/file/d/1-FaAxlfpunoU6LKZ2iWvdzWRX0-R03uB/view?usp=sharing

**Comment by aggmoulik** [comment]
Hey @withshubh I will be picking it up.

**Comment by withshubh** [comment]
Hey @aggmoulik 👋 
Assigned this to you 🚀
