### ISSUE TITLE
[docs]: Rename organization to workspace

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#3720]
### Summary

We should use `workspace`  instead of `organization`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/tutorial/organization-environment-variables

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PrajwalBorkar** [comment]
I like to work on this issue. Should I rename every occurrence from this https://docs.tooljet.com/docs/tutorial/organization-environment-variables like from sidebars and links?

**Comment by gsmithun4** [comment]
> I like to work on this issue. Should I rename every occurrence from this https://docs.tooljet.com/docs/tutorial/organization-environment-variables like from sidebars and links?

Yes
