### ISSUE TITLE
I want an event to occur when textinput presses enter.

### ISSUE THREAD

**Issue by developer-honoru** [ToolJet/ToolJet#3747]
### Is your proposal related to a problem?

I want an event to occur when textinput presses enter.
![image](https://user-images.githubusercontent.com/33475816/183003598-3fcfafed-ae9b-498b-beb3-64559ad474a4.png)

### Describe the solution you'd like

Add event(submit)

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
no

**Comment by withshubh** [comment]
Hey @developer-honoru 
We released the feature `TextInput widget now supports onEnterPressed event` in our latest release [ToolJet v1.22.0](https://github.com/ToolJet/ToolJet/releases/tag/v1.22.0)
