### ISSUE TITLE
OR(text) should only be displayed while SSO buttons are present.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#3750]
### What is the expected behaviour?
OR(text) should present  only when SSO buttons are present.

### What is the current behaviour?
OR is present while there are no SSO buttons are present.

### How to reproduce the issue?

1. Go to app sign up page.
2. Observe.

### Screenshots or Screencast
https://drive.google.com/file/d/1JayfO2BFCFWBkj5iN0U4jjFi7hv41IQ9/view?usp=sharing

**Comment by gsmithun4** [comment]
Merged https://github.com/ToolJet/ToolJet/pull/3766
