### ISSUE TITLE
Input enter onsubmit

### ISSUE THREAD

**Issue by developer-honoru** [ToolJet/ToolJet#3754]
### Is your proposal related to a problem?

It is inconvenient because an event does not occur when you hit enter in textinput.

### Describe the solution you'd like

I want an event to occur when I hit enter in a text input.

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approv

ed, would you be willing to submit a PR?

yes
https://user-images.githubusercontent.com/33475816/183082711-13e28d23-a839-407b-bd58-484ca14c9a4a.mp4

#3753

**Comment by developer-honoru** [comment]
#3753

**Comment by developer-honoru** [comment]
#3753

**Comment by withshubh** [comment]
Thanks for sharing the issue and fixing it. 🚀
