### ISSUE TITLE
[bug]Cannot read properties of undefined (reading 'variablesExposedForPreview')

### ISSUE THREAD

**Issue by developer-honoru** [ToolJet/ToolJet#3762]
### Environment

mac,linux
### What is the expected behaviour?

`Uncaught TypeError: Cannot read properties of undefined (reading 'variablesExposedForPreview')
    at Table (Table.jsx:105:11)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22157:1)`

### How to reproduce the issue?

1.You can get grass with #3749 and make a table and see the preview.
2.
3.

### Screenshots or Screencast

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/33475816/183352646-b545d9c5-0b59-4e1a-b851-32fd7621bd7b.png">
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/33475816/183352674-a32f2a83-70e7-46fa-981a-2586c0cf6b17.png>
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/33475816/183352794-bd913b17-5ef0-4adf-b053-b93c2dcede98.png>

### If the bug is confirmed, would you be willing to submit a PR?
no

**Comment by developer-honoru** [comment]
![image](https://user-images.githubusercontent.com/33475816/183353380-4c6ed5df-dade-4d7b-9c2d-cef5c1ce30ee.png)
![image](https://user-images.githubusercontent.com/33475816/183353399-fa740490-20e6-4add-9e4d-5e6d7ff83f7c.png)

**Comment by developer-honoru** [comment]
![image](https://user-images.githubusercontent.com/33475816/183353465-b037c6d2-781d-47b3-8ed3-929740c3096d.png)
![image](https://user-images.githubusercontent.com/33475816/183353494-67f1b1bd-bdc5-47cc-8d64-205453a19381.png)

**Comment by sherfin94** [comment]
Hey @developer-honoru , this was an error recently discovered and is being fixed by @kavinvenkatachalam . We'll merge the fix soon. Please use the latest release image for stability.
