### ISSUE TITLE
[docs]: Add Ubuntu Server Installation instructions

### ISSUE THREAD

**Issue by joy-amoga** [ToolJet/ToolJet#3787]
### Summary

I recently figured out how to run ToolJet in production, via code. 
We were facing an issue in ToolJet Docker build and someone had already posted a fix in a PR. So, to run the code via the PR Branch, we figured out (looking at your .dockerfile and docker-compose.yml) how to run Tooljet in Production via nginx + PM2.
I have those instructions written and if ToolJet team is interested, i can add that to Documentation > Contributing Guide > Setup > [New] Ubuntu Server (20.04 LTS)
I can use the Ubuntu setup document as base if you recommend. I can drop the idea, if ToolJet team isnt interested. 

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/setup/ubuntu

### Steps to reproduce the issue

1. Open tooljet.com
2. Click "Documentation"
3. Go to Contributing Guide > Setup > Ubuntu

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by withshubh** [comment]
Hey @joy-amoga 

We recommend docker-compose setup if deploying on production using Ubuntu Server.
