### ISSUE TITLE
Able to archive workspace admins if the workspace has multiple admins.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3816]
### What is the expected behaviour?
Should not allow to archive the last existing admin user if the workspace has multiple admins.

### What is the current behaviour?
Able to archive all admin users if the workspace has multiple admins.

### How to reproduce the issue?

[Video](https://www.loom.com/share/09f34265fccb4baba9f1875106f1c64c)

**Comment by snoseeds** [comment]
Hi @ajith-k-v, kindly assign this issue to me
