### ISSUE TITLE
Feature: radio-buttons

### ISSUE THREAD

**Issue by indeyets** [ToolJet/ToolJet#384]
### Is your proposal related to a problem?

We need to associate three-valued state with each row of the table. Radio-button is a nice solution as it allows to change state of rows very quick and that is exactly what we use in current system.

We evaluate migration to ToolJet and it would be really nice to have it, without needing to fall-back to dropdown. Using dropdown means that operator would need to make 2 clicks instead of one.

### Describe the solution you'd like

Radio-buttons widged with arbitrary number of values.

### Describe alternatives you've considered

Dropdown is an alternative, but it has different UX price which makes in unusable in our case.

### If the feature is approved, would you be willing to submit a PR?

No. I'm afraid I am not familiar with codebase to do it in realistic time-frame

**Comment by virajbahulkar** [comment]
Picking this up
