### ISSUE TITLE
Error Seeding database

### ISSUE THREAD

**Issue by PaulMcF1987** [ToolJet/ToolJet#3843]
### Environment
Docker

### What is the expected behaviour?
Id expect that the database would be seeded by running the command `docker-compose run server npm run db:seed`

### What is the current behaviour?
Error

When I run the above command after bringing the container up I get the errors shown in the screenshot below

![image](https://user-images.githubusercontent.com/75368133/186239107-25d8a481-6257-4a16-83a3-c722b1e23bb9.png)

I checked the logs and the logs that were mentioned in the pic above did not exist, instead there was 

2022-08-23T18_40_58_691Z-debug-0.log

    0 verbose cli /usr/bin/node /usr/bin/npm
    1 info using npm@8.11.0
    2 info using node@v16.16.0
    3 timing npm:load:whichnode Completed in 0ms
    4 timing config:load:defaults Completed in 2ms
    5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
    6 timing config:load:builtin Completed in 1ms
    7 timing config:load:cli Completed in 2ms
    8 timing config:load:env Completed in 0ms
    9 timing config:load:file:/tooljet/.npmrc Completed in 1ms
    10 timing config:load:project Completed in 13ms
    11 timing config:load:file:/root/.npmrc Completed in 0ms
    12 timing config:load:user Completed in 0ms
    13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
    14 timing config:load:global Completed in 1ms
    15 timing config:load:validate Completed in 0ms
    16 timing config:load:credentials Completed in 1ms
    17 timing config:load:setEnvs Completed in 1ms
    18 timing config:load Completed in 21ms
    19 timing npm:load:configload Completed in 21ms
    20 timing npm:load:mkdirpcache Completed in 1ms
    21 timing npm:load:mkdirplogs Completed in 0ms
    22 verbose title npm update
    23 verbose argv "update"
    24 timing npm:load:setTitle Completed in 1ms
    25 timing config:load:flatten Completed in 3ms
    26 timing npm:load:display Completed in 5ms
    27 verbose logfile logs-max:10 dir:/root/.npm/_logs
    28 verbose logfile /root/.npm/_logs/2022-08-23T18_40_58_691Z-debug-0.log
    29 timing npm:load:logFile Completed in 5ms
    30 timing npm:load:timers Completed in 0ms
    31 timing npm:load:configScope Completed in 0ms
    32 timing npm:load Completed in 33ms
    33 timing arborist:ctor Completed in 1ms
    34 silly logfile done cleaning log files
    35 timing idealTree:init Completed in 6ms
    36 timing idealTree:userRequests Completed in 0ms
    37 silly idealTree buildDeps
    38 timing idealTree:#root Completed in 0ms
    39 timing idealTree:buildDeps Completed in 2ms
    40 timing idealTree:fixDepFlags Completed in 0ms
    41 timing idealTree Completed in 9ms
    42 timing reify:loadTrees Completed in 11ms
    43 timing reify:diffTrees Completed in 1ms
    44 silly reify moves {}
    45 timing reify:retireShallow Completed in 1ms
    46 timing reify:createSparse Completed in 0ms
    47 timing reify:loadBundles Completed in 0ms
    48 silly audit report null
    49 timing reify:audit Completed in 1ms
    50 timing reify:unpack Completed in 0ms
    51 timing reify:unretire Completed in 0ms
    52 timing build:queue Completed in 0ms
    53 timing build:deps Completed in 0ms
    54 timing build Completed in 1ms
    55 timing reify:build Completed in 1ms
    56 timing reify:trash Completed in 0ms
    57 timing reify:save Completed in 2ms
    58 timing reify Completed in 39ms
    59 timing command:update Completed in 44ms
    60 verbose exit 0
    61 timing npm Completed in 133ms
    62 info ok

and
2022-08-23T18_40_28_063Z-debug-0.log

    0 verbose cli /usr/bin/node /usr/bin/npm
    1 info using npm@8.11.0
    2 info using node@v16.16.0
    3 timing npm:load:whichnode Completed in 0ms
    4 timing config:load:defaults Completed in 1ms
    5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 0ms
    6 timing config:load:builtin Completed in 2ms
    7 warn config global `--global`, `--local` are deprecated. Use `--location=global` instead.
    8 timing config:load:cli Completed in 2ms
    9 timing config:load:env Completed in 0ms
    10 timing config:load:project Completed in 13ms
    11 timing config:load:file:/root/.npmrc Completed in 0ms
    12 timing config:load:user Completed in 0ms
    13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
    14 timing config:load:global Completed in 1ms
    15 timing config:load:validate Completed in 0ms
    16 timing config:load:credentials Completed in 2ms
    17 timing config:load:setEnvs Completed in 1ms
    18 timing config:load Completed in 23ms
    19 timing npm:load:configload Completed in 23ms
    20 timing npm:load:mkdirpcache Completed in 1ms
    21 timing npm:load:mkdirplogs Completed in 0ms
    22 verbose title npm install
    23 verbose argv "install" "--global"
    24 timing npm:load:setTitle Completed in 2ms
    25 timing config:load:flatten Completed in 3ms
    26 timing npm:load:display Completed in 7ms
    27 verbose logfile logs-max:10 dir:/root/.npm/_logs
    28 verbose logfile /root/.npm/_logs/2022-08-23T18_40_28_063Z-debug-0.log
    29 timing npm:load:logFile Completed in 6ms
    30 timing npm:load:timers Completed in 0ms
    31 timing npm:load:configScope Completed in 0ms
    32 timing npm:load Completed in 40ms
    33 timing arborist:ctor Completed in 1ms
    34 silly logfile done cleaning log files
    35 timing idealTree:init Completed in 7ms
    36 timing idealTree Completed in 9ms
    37 timing command:install Completed in 29ms
    38 verbose stack Error: ENOENT: no such file or directory, open '/tooljet/package.json'
    39 verbose cwd /tooljet
    40 verbose Linux 4.15.0-163-generic
    41 verbose node v16.16.0
    42 verbose npm  v8.11.0
    43 error code ENOENT
    44 error syscall open
    45 error path /tooljet/package.json
    46 error errno -2
    47 error enoent ENOENT: no such file or directory, open '/tooljet/package.json'
    48 error enoent This is related to npm not being able to find a file.
    48 error enoent
    49 verbose exit -2
    50 timing npm Completed in 222ms
    51 verbose unfinished npm timer reify 1661280028253
    52 verbose unfinished npm timer reify:loadTrees 1661280028269
    53 verbose unfinished npm timer idealTree:userRequests 1661280028277
    54 verbose code -2
    55 error A complete log of this run can be found in:
    55 error     /root/.npm/_logs/2022-08-23T18_40_28_063Z-debug-0.log

Any help sorting this would be much appreciated.

**Comment by gondar00** [comment]
Hey, @PaulMcF1987 could you once please confirm the `node` and `npm` versions inside your server container? 

As per the logs you posted I can see that node and npm are pointing to 16.16.0 & 8.11.0, please note the supported versions are currently  `node: 14.17.3 &  npm: 7.20.0`

**Comment by PaulMcF1987** [comment]
@gondar00 the versions shown in the logs are correct
Node V16.16.0
npm V8.11.0

i Tried installing the trial version using  

    docker run \
      --name tooljet \
      --restart unless-stopped \
      -p 3000:3000 \
      -v tooljet_data:/var/lib/postgresql/13/main \
      tooljet/try:latest

And that ran fine, it seeded the database etc. Id be surprised if that worked fine but the main production ready image doesnt?

**Comment by gondar00** [comment]
Just notified the team to investigate. Thanks for reporting it. We will get back on this

**Comment by PaulMcF1987** [comment]
@gondar00 I rolled my installs back to versions?
node 14.17.3 which changed npm to version 6.14.13

but still no joy
![image](https://user-images.githubusercontent.com/75368133/186449339-aac388f3-1759-4f56-8ffd-bb2390afc2ee.png)

I have tried to view the logs but no logs have been saved

**Comment by gondar00** [comment]
@PaulMcF1987 could you pin npm version to `7.20.0` using `npm i -g npm@7.20.0` 

also got an update from the team, running the below command after pinning the npm version should resolve this issue

`docker-compose run server npm run db:seed:prod`

**Comment by PaulMcF1987** [comment]
@gondar00 thank you for your help, that seemed to work.
