### ISSUE TITLE
[bug]: Replace Navbar item names with icons

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3855]
### What is the expected behaviour?

Replace the texts(Github, Slack, Twitter) with their respective icons

### What is the current behaviour?

Currently, the navbar has social link names.

### How to reproduce the issue?

1. Visit this [link](https://docs.tooljet.com/docs)
2. On the top right-hand corner, we can see the social link names
3. Maintaining the same padding, replace these with their respective icons.
4. Kindly reach out to get color codes and other information if required.

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-08-24 at 5 10 39 PM" src="https://user-images.githubusercontent.com/32157641/186409480-3109541b-aba8-4079-ad85-663eecccb5d1.png">

**Comment by athulmekkoth** [comment]
can i work on this ?

**Comment by shivangT** [comment]
Hey @athulmekkoth 
Sure, assigning this to you 🙌🏻

**Comment by athulmekkoth** [comment]
can I get the color code ?

**Comment by shivangT** [comment]
You can use this #a4a6a8 for now, It sits both the light and dark mode.

**Comment by timagixe** [comment]
Hello @shivangT @athulmekkoth, I can help with this, just let me know. Thanks.

**Comment by timagixe** [comment]
I believe these code snippets from Docusaurus Github repository is a good start.

https://github.com/facebook/docusaurus/blob/c2ce8a02e726fec68c06be56cb6f6a305df25bc0/website/docusaurus.config.js#L504-L509

https://github.com/facebook/docusaurus/blob/c2ce8a02e726fec68c06be56cb6f6a305df25bc0/website/src/css/custom.css#L72-L88

**Comment by athulmekkoth** [comment]
@shivangT  Sorry I met with a minor accident today morning and won't be able to finish it soon. I am unassigning myself. Hope you understand

**Comment by timagixe** [comment]
@athulmekkoth I hope you are safe.

@shivangT please assign this issue on me. Thank you.

**Comment by shivangT** [comment]
Hey @athulmekkoth
Hope you’re doing fine. Takecare

Hi @timagixe , assigned this to you.please join our slack channel if you get stuck with something. 

We’re happy to take your queries there 🙌🏻
Have a great day both!!

**Comment by athulmekkoth** [comment]
> Hey @athulmekkoth
> Hope you’re doing fine. Takecare
> 
> Hi @timagixe , assigned this to you.please join our slack channel if you get stuck with something. 
> 
> We’re happy to take your queries there 🙌🏻
> Have a great day both!! 

@shivangT  thanks .

**Comment by athulmekkoth** [comment]
> @athulmekkoth I hope you are safe.
> 
> @shivangT please assign this issue to me. Thank you.

Yeah some scratches here and there

**Comment by shivangT** [comment]
Get well soon 🚀

**Comment by timagixe** [comment]
@shivangT, I will use official SVGs from:
https://brandfolder.com/slack/logos - for Slack
https://github.com/logos - for GitHub
https://about.twitter.com/en/who-we-are/brand-toolkit - for Twitter
