### ISSUE TITLE
[bug]: Increase the width of the search container in the Navbar

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3856]
### What is the expected behaviour?

Increase the search bar width up to which it has a good look and feel.

### What is the current behaviour?

Currently, the search bar is not intuitive enough. The search bar has a smaller width.

### How to reproduce the issue?

1. Visit this [link](https://docs.tooljet.com/docs)
2. On the top left-hand corner, we can see the search bar,
3. Maintaining the same padding, increase the width of the search bar
4. Kindly reach out to confirm the width you're applying.

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-08-24 at 5 10 39 PM" src="https://user-images.githubusercontent.com/32157641/186409480-3109541b-aba8-4079-ad85-663eecccb5d1.png">

**Comment by rakicodes** [comment]
hey, can i work on this?

**Comment by shivangT** [comment]
Hey @rakicodes 
Sorry for the delay in the response. I guess the PR is ready from jack. 

Can you look into some other good first issues?
Thanks

**Comment by shivangT** [comment]
Hey Jack,
I’ve to assign you this issue, can you please comment below? I can then be able to do that.

NOTE: According to our code of conduct you first have to get the issue assigned to you and then start working on the PR. 

Kindly follow the same when you pick a new issue

Thanks

**Comment by jackoliver** [comment]
Hey! Yeah it's ready to go from my end. :)
