### ISSUE TITLE
[feature] Open docs path instead of root when starting development server of docs

### ISSUE THREAD

**Issue by timagixe** [ToolJet/ToolJet#3877]
### Is your proposal related to a problem?

Right now when running `yarn start` for docs, the development server opens http://localhost:3000/ and the develop sees 'Page Not Found'.

<img width="1728" alt="Screen Shot 2022-08-26 at 8 31 41 AM" src="https://user-images.githubusercontent.com/60817786/186829161-f5f16923-77a1-4652-a615-e519d159063d.png">

### Describe the solution you'd like

Would be nice to open http://localhost:3000/docs, which opens the docs itself. I believe this will improve developer experience and in addition, developer would not more require to open /docs path by himself.

<img width="1728" alt="Screen Shot 2022-08-26 at 8 31 48 AM" src="https://user-images.githubusercontent.com/60817786/186829172-827b3fbb-afa5-4e30-843a-7d82b83432f5.png">

### Describe alternatives you've considered

Extend Docusaurus' Webpack Dev Server.

### If the feature is approved, would you be willing to submit a PR?

Yes

**Comment by timagixe** [comment]
Hello @shivangT @Navaneeth-pk please take a look on this small feature request.

I will help with extending webpack's dev server configuration if this is approved.

Cheers!

**Comment by Navaneeth-pk** [comment]
Thanks for reporting the issue. Assigned to you!
@timagixe
