### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by joys014** [ToolJet/ToolJet#3906]
### Version Information
```
tooljet/tooljet-ce:latest
DIGEST:sha256:2773dbf0ebcd9364d4fea1f3ab67845aa780f131e3a607582d74457b90223cce
```

### Environment
ToolJet Docker

### What is the expected behaviour?
Installer runs with no error.

### What is the current behaviour?
`npm ERR! Exit status 1`

### How to reproduce the issue?
url - https://docs.tooljet.com/docs/setup/docker
Step 8. `docker-compose run server npm run db:seed`

### Screenshots or Screencast

```
server@0.0.1 db:seed /app/server
> ts-node -r tsconfig-paths/register --transpile-only ./scripts/seeds.ts

Couldn't find tsconfig.json. tsconfig-paths will be skipped
Error: Cannot find module '../src/app.module'
Require stack:
- /app/server/scripts/seeds.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/server/scripts/seeds.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/app/server/node_modules/ts-node/src/index.ts:1295:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/app/server/node_modules/ts-node/src/index.ts:1298:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

### Please provide any traces or logs that could help here.

```
Ubuntu 20.04LTS
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Any possible solutions?
NA

### Can you identify the location in the driver source code where the problem exists?

```
Couldn't find tsconfig.json. tsconfig-paths will be skipped
Error: Cannot find module '../src/app.module'
```

### If the bug is confirmed, would you be willing to submit a PR?
No. I dont know the Tooljet Structure much to solve this.

**Comment by DNWEIJ** [comment]
on windows machine getting error during start of docker:

   _____           _   ___      _
  |_   _|         | | |_  |    | |
    | | ___   ___ | |   | | ___| |_
    | |/ _ \ / _ \| |   | |/ _ \ __|
    | | (_) | (_) | /\__/ /  __/ |_
    \_/\___/ \___/|_\____/ \___|\__|

Everything you need to build internal tools!
GitHub: https://github.com/ToolJet/ToolJet

[Error: EACCES: permission denied, open '/app/frontend/build/index.html'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/frontend/build/index.html'
}
[Error: EACCES: permission denied, open '/app/frontend/build/runtime.js'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/frontend/build/runtime.js'
}
[Error: EACCES: permission denied, open '/app/frontend/build/main.js'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/frontend/build/main.js'

**Comment by joy-amoga** [comment]
url - https://docs.tooljet.com/docs/setup/docker
Step 8.  `docker-compose run server npm run db:seed:prod` worked and production db got created with seeded data.

The reported command still has issue.

**Comment by joy-amoga** [comment]
This issue is duplicate of this issue ->  #3898 
Apologies

**Comment by joys014** [comment]
Closing issue. @akshaysasidrn explanation worked.
