### ISSUE TITLE
Tooltip text for hide query editor not visible

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3917]
### What is the expected behaviour?

Tooltip for hide query editor should overlap the sidebar

### What is the current behaviour?

Sidebar is overlapping the Tooltip for hide query editor

### How to reproduce the issue?

1. Open app editor
2. Hover on the hide button in query panel

<img width="420" alt="Screenshot 2022-08-30 at 12 59 02 PM" src="https://user-images.githubusercontent.com/25361949/187653166-a7754c9f-f041-4fcc-9998-d4f9d8d0cfb8.png">

**Comment by roei111** [comment]
Hey @withshubh, I would like to work on this issue! Can you assign it to me? :)

**Comment by iSatVeerSingh** [comment]
is this issue still causing?

**Comment by shivangT** [comment]
Resolved
