### ISSUE TITLE
[feature] Add pagination and filtering to users page

### ISSUE THREAD

**Issue by shah21** [ToolJet/ToolJet#3920]
### Is your proposal related to a problem?

Currently, there isn't any option to filter the users' table and paginate the results

### Describe the solution you'd like

Add pagination and add three fields to filter the users' table (email, first name, last name)

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by joeshajan** [comment]
I would like to implement this feature

**Comment by shivangT** [comment]
Hey @joeshajan 
The feature is already assigned and worked by an internal team member.
You can go through our issues log to work on other features. 

Thanks
