### ISSUE TITLE
Bug : [ Tree Select widget ] is not consistent with the dark theme

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#3947]
### Version Information
v1.24.0

### Environment
Development

### What is the expected behaviour?
The Tree Select widget should be consistent with the dark theme, text color should be white by default in the dark theme.

### What is the current behaviour?
The Tree Select widget is not consistent with the dark theme, the text color is black by default in the dark theme (it is hard to read).

### How to reproduce the issue?

1. Create a new application or open an existing one
2. Switch to the dark theme, by clicking on the half moon icon at the bottom of the left sidebar. (Please ignore step 2, if the app is in dark theme by default)
3. Look or search (you can search for any widget through the search box at the top of the right sidebar) for the Tree Select widget in the right sidebar and drag it on the canvas.
4. You can observe, that the Tree Select widget is displayed on the canvas, and it does not go well with the dark theme

### Screenshots or Screencast
[Tooljet - Dashboard - 5 September 2022 - Watch Video](https://www.loom.com/share/f123ae125aad4ac9a47703def13aa0cb)

### Any possible solutions?
Change the text color to white by default in the dark theme

### Can you identify the location in the driver source code where the problem exists?
frontend > src > Editor > Components > TreeSelect.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by Kirito-Excalibur** [comment]
HI! Can you assign me this issue?

**Comment by shivangT** [comment]
Hey @Kirito-Excalibur 
This is already resolved by our internal team member. Kindly explore other good first issues from the issue log. 
Thanks
