### ISSUE TITLE
MariaDB integration

### ISSUE THREAD

**Issue by vishnurk6247** [ToolJet/ToolJet#3953]
### Is your proposal related to a problem?

I saw MariaDB integration in your roadmap. I've already done most of the work related to this and need a bit more time on testing this out

### Describe the solution you'd like

MariaDB integration

### If the feature is approved, would you be willing to submit a PR?

Yes

**Comment by shivangT** [comment]
Hey @vishnurk6247 
Any updates on the following issue?

**Comment by vishnurk6247** [comment]
Hey @shivangT,
Sorry for causing the delay. Will create a PR for this by EOD

**Comment by shivangT** [comment]
Hello @vishnurk6247 

Sure, Thanks for the update.
