### ISSUE TITLE
Bug : Canvas background colour is not consistent with the dark theme

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#3955]
### Version Information
v1.24.0

### Environment
Development

### What is the expected behaviour?
The canvas background color in the editor should be consistent with the applied theme

### What is the current behaviour?
The canvas background color in the editor is not consistent with the applied theme.

1. Suppose a new application is created in the light theme, even if we change the theme to a dark theme from the application, the background colour of the canvas will persist colour from the light theme only.
2. Suppose a new application is created with the dark theme, even if we change the theme to a light theme from the application, the background colour of the canvas will persist colour from the dark theme only.

### How to reproduce the issue?

Steps for the **light theme** by default
1. Let's assume, you are in light mode by default 
2. Now create a new application from the dashboard (In the dashboard you are in light theme by default)
3. Once the application is open, check the background colour of the canvas (You can also observe it, from the settings section in the left sidebar), it is "#edeff5" for the light theme by default.
4. Now, change to a dark theme, by clicking on the half moon icon at the bottom of the left sidebar. You can observe entire application is changed to a dark theme, except for the canvas background color, still persist the colour from the light theme as "#edeff5" instead of "#2f3c4c" (to confirm it, check the canvas background colour in the settings from the left sidebar again)

Steps for the **dark theme** by default
1. Let's assume, you are in dark mode by default 
2. Now create a new application from the dashboard (In the dashboard you are in dark theme by default)
3. Once the application is open, check the background colour of the canvas (You can also observe it, from the settings section in the left sidebar), it is "#2f3c4c" for the dark theme by default.
4. Now, change to a light theme, by clicking on the half moon icon at the bottom of the left sidebar. You can observe entire application is changed to a light theme, except for the canvas background color, still persist the colour from the dark theme as "#2f3c4c" instead of "#edeff5" (to confirm it, check the canvas background colour in the settings from the left sidebar again)

### Screenshots or Screencast
[Tooljet - Dashboard - 5 September 2022 - Watch Video](https://www.loom.com/share/7c59b9d060f643c6b67af33f18aea13e)

### Any possible solutions?
when toggling the theme, change the background colour  of the canvas accordingly 

### Can you identify the location in the driver source code where the problem exists?
frontend > src > Editor 

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by DronSKM044** [comment]
Hello, if you don't mind  I will try to figure out why background color does not work right.

**Comment by shivangT** [comment]
Hey @DronSKM044 
This issue is resolved by an internal team member. 

Kindly explore our issue logs to other good first issues.

Thanks
