### ISSUE TITLE
[Table]: Add an option/property to programmatically pre-select a table row on page load

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3962]
### What is the expected behaviour?
Provide an option in the table widget that allows users to preselect a row when app initially loads

### What is the current behaviour?
We've no such action available as of now.

### How to reproduce the issue?

1. Visit the [link](https://app.tooljet.com/) and create a new application.
2. Drag and drop table widget from the widgets inventory on the left
3. Now inspect the widget to access its properties
4. Toggle ON "Highlight SelectedRow"
5. If we click on any table row, it will be highlighted
6. If we refresh the app, selected row is disappears
7. Enable an option to select a row in the table when app initially loads  
### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-09-06 at 10 06 15 AM" src="https://user-images.githubusercontent.com/32157641/188547841-df264ecb-4c8f-43bf-8955-7eb57c4d744b.png">

**Comment by mikebarr24** [comment]
Hey! I would be eager to take a shot at this if it's OK.

**Comment by AyushK-101** [comment]
Can I work on this?

**Comment by Sanjayrk0206** [comment]
Hey @shivangT, I am interested in working on this. Can you assign this to me?

**Comment by sherfin94** [comment]
Hey @manishkushare , we are delivering this in 1.2 milestone, please change the branch accordingly.

**Comment by sherfin94** [comment]
Hey @manishkushare , letting you know that this is no longer on hold, please take it up whenever you are onto this, and lets discuss blockers if any. cc: @kavinvenkatachalam
