### ISSUE TITLE
Security concerns with default admin seed credentials

### ISSUE THREAD

**Issue by TheLearneer** [ToolJet/ToolJet#3975]
### Is your proposal related to a problem?

Just earlier today I went through a slack conversation where one of user was having issues with certain aspect with their custom deployed version of Tooljet.
In the message they had also shared a screenshot which also displayed the full URL of the deployed version of tooljet.

The problem now is that, since they followed the entire tutorial of deployment process, they had also seeded the default admin credentials.
And since I knew the URL of their tooljet instance, I was able to login and access it.

**I believe this is a major security concerns.**

### Describe the solution you'd like

One of the best solution I could think up of is take the email and password from environment variables and then use those in the seeder service i.e. 
- https://github.com/ToolJet/ToolJet/blob/develop/server/src/services/seeds.service.ts#L17
- https://github.com/ToolJet/ToolJet/blob/develop/server/src/services/seeds.service.ts#L38-L39
- https://github.com/ToolJet/ToolJet/blob/develop/server/src/services/seeds.service.ts#L59 (It's just console log, but we need to be persistent)

**NOTE**: We will also need to update the documentation to mention about this so that all the users are fully aware about it.

### Describe alternatives you've considered

**N/A**

### If the feature is approved, would you be willing to submit a PR?

Yes

**Comment by Navaneeth-pk** [comment]
This behaviour will be changed as part of our redesigned onboarding process for self-hosted instances.
