### ISSUE TITLE
[Bug]: All users have access to the users route

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#3996]
### Environment

    ToolJet Cloud 

### What is the expected behaviour?

The `/users` route is accessible for admin only.

### What is the current behaviour?

The `/users` route is accessible for all users.

### Screenshots or Screencast

[Video](https://www.loom.com/share/13997176b9d34f9088e44f62c0789bbf)

**Comment by shivangT** [comment]
Closing, Duplicate created
