### ISSUE TITLE
[RadioButton]: "Default value" property not working

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3997]
### What is the expected behavior?

Changing the default option from `true->false` should select the other option in the widget.

### What is the current behavior?
Changing the default option from `true-> false` is not working

### How to reproduce the issue?

1. Visit the [link](https://app.tooljet.com/) and create a new application.
2. Drag and drop the radio button widget from the widgets inventory on the left
3. Now inspect the widget to access its properties
4. Update the "default value" field from `{{true}}->{{false}}` 
5. This should update the Widget's UI by selecting the other option.

Note: Do check the same for multiple options. Try different values in "Default Value" and test this.

### Screenshots or Screencast

1. **Default field values**
<img width="1142" alt="Screenshot 2022-09-09 at 1 24 59 PM" src="https://user-images.githubusercontent.com/32157641/189300854-2dbdcc90-4c64-4b17-8312-293ecdb49b14.png">

2. **Updated values**
<img width="1108" alt="Screenshot 2022-09-09 at 1 25 18 PM" src="https://user-images.githubusercontent.com/32157641/189300919-106ce76e-3d36-48a5-bfc4-cecf242ff4ae.png">

**Comment by yashdhanore** [comment]
Hey! I would like to give it a try

**Comment by shivangT** [comment]
Hey @yashdhanore 
Assigning this to you. Have a good time coding on Tooljet 👍🏼

**Comment by iSatVeerSingh** [comment]
is anyone working on it?

**Comment by shivangT** [comment]
Hey @yashdhanore 
Any updates on this?


Hello @iSatVeerSingh 
This issue is assigned to Yash and he is working on it. Let's wait for his response. 

Thanks

**Comment by yashdhanore** [comment]
Hey! Yeah i'm still working on it

**Comment by shivangT** [comment]
Sure, thanks for the update

**Comment by yashdhanore** [comment]
Hey @shivangT Can you have a look at the pull request?
