### ISSUE TITLE
Bug : Organization avatar and profile avatar is not consistent with the dark theme.

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#4004]
### Environment
Development

### What is the expected behaviour?
The organization avatar and profile avatar on the Headers on the Home page should be consistent with the dark theme.

### What is the current behaviour?
The organization avatar and profile avatar on the Headers on the Home page is not consistent with the dark theme.

### How to reproduce the issue?

1. Login into ToolJet Account. You will be redirected to the Home Page.
2. Switch to a dark theme, by clicking on the half moon icon, present in the header section. (Ignore step 2, if already in dark theme)
3. On the Home page, on the rightmost side of the headers section, look for the Organization avatar and profile avatar. They are not consistent with the dark theme.

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2022-09-09 at 7 26 06 PM" src="https://user-images.githubusercontent.com/37823141/189367556-c007c57f-40f9-43bd-8760-529d50dbe869.png">

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by AdwitiyaMishra** [comment]
Hi @manishkushare, I would like to work on this issue. It'd be great if you could assign it to me.

**Comment by manishkushare** [comment]
@AdwitiyaMishra , I am sorry, but this issue is already resolved by our internal team.  Kindly explore other good first issues from the issue log. Thanks
