### ISSUE TITLE
Unexpected behaviour when accessing parsed data from file picker with csv files

### ISSUE THREAD

**Issue by PrasanthKumar77** [ToolJet/ToolJet#4011]
### Version Information
1.14.0
### Environment
Docker - self host

### What is the expected behaviour?
when csv files are uploaded using file picker component and accessing the parsed data
1. Even if a column value is of multiple lines then it should be considered as single value.
2. Even if the column value is with multiple comma's then the whole value should be considered as single value

### What is the current behaviour?
when csv files are uploaded using file picker component and accessing the parsed data
1. If a column value is of multiple lines then each line in that column is being read as new line.
2. If the column value is with multiple comma's then the value is being considered only upto first comma and remaining content is missing.

### How to reproduce the issue?

1. Add two rows in sheet
2. In first row add multiple lines in a single column value
3. In second row add a value with multiple comma's in it
4. Download it as csv file
5. Select a file picker component. enable the parsed content option for it
6. Upload the csv file using file picker component.
7. Check the parsed data value for both rows

### Screenshots
![downloaded_sheet_csv](https://user-images.githubusercontent.com/78995399/189469009-b36fc150-8510-4c0c-be3a-6f367252a276.png)
![sheet_sample](https://user-images.githubusercontent.com/78995399/189469011-e0126cc0-7645-494a-bc87-59eb7802546e.png)

![parsed_data_screenshot](https://user-images.githubusercontent.com/78995399/189469405-09fc1a34-a946-4373-917d-1898126a173f.png)

This issue is reproduced in latest version also.

**Comment by shivangT** [comment]
Hey @PrasanthKumar77 
Let us recreate this issue and get back to you with an update.
Thanks for pointing this out.

**Comment by PrasanthKumar77** [comment]
hi @shivangT 
Could you let me know if there is any update on this?
Thank you.

**Comment by shivangT** [comment]
Hey 
You’ll get an update by EOD. 
Thanks for waiting.

**Comment by PrasanthKumar77** [comment]
hi @shivangT 

is this issue fixed in 1.26.0 version?

we have been using the this in different applications

**Comment by PrasanthKumar77** [comment]
may i know if this was picked for next version release?

**Comment by withshubh** [comment]
Hey @PrasanthKumar77 👋 

Thanks for following up. We still haven't released a fix for this. We will share an update on the issue once it is fixed, rest assured.

**Comment by PrasanthKumar77** [comment]
hi @withshubh 

may i know if this was picked for next version release?

we have a lot of applications build on this.
