### ISSUE TITLE
[Bug]: All users have access to the audit_log route

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#4015]
### Environment

    ToolJet Cloud 

### What is the expected behaviour?

The `/audit_log` route is accessible for admin only.

### What is the current behaviour?

The` /audit_log` route is accessible for all users.

### Screenshots or Screencast

[Video](https://www.loom.com/share/469d0191115b4f32ac600220080a3c5c)

**Comment by snoseeds** [comment]
Hi @ajith-k-v, kindly assign this issue to me

**Comment by withshubh** [comment]
> Hi @ajith-k-v, kindly assign this issue to me

Hey @snoseeds - Thanks for your interest in contributing to ToolJet. Assigned the issue to you.

**Comment by snoseeds** [comment]
Thanks @withshubh, I will commence work on it

**Comment by snoseeds** [comment]
Hi @withshubh , I just figured out now that Audit Logs is only part of the enterprise edition of ToolJet, and I thereby didn't see any related code to it in the publicly available repo code. Is there still any way I can work on this issue?

**Comment by withshubh** [comment]
My bad - thanks for pointing that out. Unassigned the issue.
