### ISSUE TITLE
[Table]: The currentData values in the inspector are not updating 

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#4021]
### What is the expected behavior?

After updating the table data, the `currentData` values in the inspector should be updated as well 

### What is the current behavior?

The `currentData` values in the inspector are not updating

### How to reproduce the issue?

1. Visit the [link](https://app.tooljet.com/) and create a new application.
2. Drag and drop the Table widget from the widgets inventory on the left
3. Now inspect the widget to access its properties
4. Open the inspector panel on the right and navigate through the following- components > table1 > currentData
5. Now observe the data here
6. Inspect the Table widget and update the values in Table Data
7. Now again inspect the `currentData` under is inspector 

### Screenshots or Screencast

https://drive.google.com/drive/folders/1QtKW-nhTEdr4pIrLPm_4ZLp3F5lCFsJn?usp=sharing

**Comment by arpitnath** [comment]
Additional description
The exposed variable `currentData` is not updated if the length of the data is the same as previous one.
