### ISSUE TITLE
Add Event trigger to RangePicker

### ISSUE THREAD

**Issue by venomouse** [ToolJet/ToolJet#4026]
### Is your proposal related to a problem?

Currently, there is no way to trigger an event if the dates are changed on the RangePicker widget. That means that if we want to change the dates on the dashboard and reload the charts, we have to use two DatePickers.

### Describe the solution you'd like

RangePicker configuration pane should have "Events" section, just like DatePicker pane.

### Describe alternatives you've considered

Currently using two separate DatePickers, but it's not ideal.

**Comment by shivangT** [comment]
Hey @venomouse 

I’m sure that must be a pain point. I was using rangepicker recently and had pointed out the same issue. 
Let me check with the product team and fix this soon.
Thanks

**Comment by shivangT** [comment]
Hey @venomouse 

We've discussed this with the product team and assigned this to an internal team member.

Resolving this soon, stay in loop for the updates.

Thanks
