### ISSUE TITLE
User (or user group) with view access to an application is able to edit the app using the editor link.

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#4028]
### Version Information
[v1.24.0](https://github.com/ToolJet/ToolJet/releases/tag/v1.24.0)
### Environment
    ToolJet Cloud/MacOS 

### What is the expected behaviour?
The user with view access to an application should not be able to access the editor page.

### What is the current behaviour?
Users with read-only permission can edit the app with the editor link, and it saves the changes when two or more users are editing the app simultaneously.

### How to reproduce the issue?

`Admin user:`
   1. Add a new user to the workspace.
   2. Add a new app.
   3. Add view-only access to the `all user` group.
   4. Open the newly created app and copy the editor page URL.

`New user:`
      5. Open a new browser/profile.
      6. Login and open the copied URL.
      7. Edit the application.

### Please provide any traces or logs that could help here.
[Slack discussion](https://tooljet.slack.com/archives/C02QT13RF51/p1663045474273489)

### Any possible solutions?
  1. We can add one error message and redirect to the dashboard.
  2. The link should show a 403 error page.

**Comment by snoseeds** [comment]
@emidhun and @withshubh , kindly assign this issue to me
