### ISSUE TITLE
Add SQLite as datasource

### ISSUE THREAD

**Issue by christophberger** [ToolJet/ToolJet#4030]
### Is your proposal related to a problem?

No specific problem involved here.

### Describe the solution you'd like

Please add SQLite as a datasource for ToolJet. SQLite is a widespread in-app database that many tools and services use as their go-to file format. (See e.g. [Grist](getgrist.com).) 

The ability to access SQLite files would greatly increase the possibilities of ToolJet.

### Describe alternatives you've considered

None available AFAICT

### If the feature is approved, would you be willing to submit a PR?

Unfortunately, I neither have the time nor the necessary expertise to contribute code.  I would be happy to help with testing.

**Comment by shivangT** [comment]
Hello @christophberger 

We’re already working on introducing SQLite on our Tooljet. We got multiple request recently.

Thanks for the suggestion, stay in loop to get an update on the same.

**Comment by gondar00** [comment]
Hi @christophberger, I appreciate your time and effort in suggesting new data sources, but unfortunately, SQLite is not planned to be added to the list of data sources.

**Comment by christophberger** [comment]
Why the sudden change of mind? 

@gondar00 @shivangT

**Comment by gondar00** [comment]
Well, post-discussion we came to a conclusion that SQLite won't make much sense if on the same container as containers might mostly be read-only + horizontal scalability is also an issue.

**Comment by christophberger** [comment]
Makes sense. It would seem that SQLite-over-GraphQL could be a suitable alternative (like, for example, [WunderBase](https://github.com/wundergraph/wunderbase)). 

Thanks for clarifying.
