### ISSUE TITLE
Add CockroachDB as datasource

### ISSUE THREAD

**Issue by christophberger** [ToolJet/ToolJet#4032]
### Is your proposal related to a problem?

I would like to use ToolJet with a distributed, open-source SQL database.

### Describe the solution you'd like

Please add [CockroachDB](https://github.com/cockroachdb) to the list of Database sources. 

CockroachDB is a distributed SQL database compatible with the Postgres wire protocol. It 

### Describe alternatives you've considered

PostgreSQL -> difficult to set up in a distributed fashion
Proprietary Cloud DBs -> these are proprietary and bound to their respective cloud service.
NoSQL DBs -> while some of them may be distributed, they serve different needs than a SQL DB does.

### If the feature is approved, would you be willing to submit a PR?

Unfortunately, I have neither the time nor the expertise to contribute code to this project. I would be happy to help with testing.

**Comment by shivangT** [comment]
Hey @christophberger 

Thanks for the request. Let me discuss the same with the product team and revert you with an update.

**Comment by gondar00** [comment]
Closing as duplicate #2529
