### ISSUE TITLE
[feature]: Translation in French

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#4046]
### What is the expected behavior?

Add support for French localization.

### What is the current behavior?

We don't support French localization for now

Kindly refer the doc below before proceeding with the issue. 

[ToolJet Localization Guide](https://docs.tooljet.com/docs/contributing-guide/l10n)

**Comment by appledora** [comment]
@shivangT @shubh22 I would like to do the localization for Bengali. Can you assign an issue to me?

**Comment by withshubh** [comment]
Hey @appledora 👋 
Another issue is assigned to you already.

**Comment by Srisuma13** [comment]
@withshubh @shivangT I would like to work on this translation task.

**Comment by arpitnath** [comment]
@Srisuma13 assigning the issue to you 😅

**Comment by Srisuma13** [comment]
Thanks for assigning @arpitnath!

**Comment by Srisuma13** [comment]
@arpitnath Just noticed that this issue is broken down into smaller subtasks - https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+french. 
This would be redundant I believe. Let me know what you would suggest.

**Comment by arpitnath** [comment]
@Srisuma13 Thanks for addressing, and closing this issue
