### ISSUE TITLE
i18n.js is not using the SUB_PATH variable, if any defined (used in reverse-proxy setups)

### ISSUE THREAD

**Issue by exetico** [ToolJet/ToolJet#4053]
### Version Information

`:latest` [tag](https://hub.docker.com/layers/tooljet/tooljet-ce/latest/images/sha256-3e70e97672cb0e9f702a3311e2fd9c3bdd643f4f48bd53cef00fd2dc8516e889?context=explore).

### Environment
Docker `tooljet/tooljet-ce:latest` behind Caddy.

### What is the expected behaviour?
i18n.js should use `SUB_PATH`  (process.env.SUB_PATH)

It looks like following files is impacted:
https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/i18n.js

Insted of just the hardcoded string:
https://github.com/ToolJet/ToolJet/blob/e8ae8a9fe64eb1c7783fbc5ae91655671a007b35/frontend/src/i18n.js#L16

### What is the current behaviour?
It's just using `/assets/translations/{{lng}}.json`, so the lang-files can't be resolved if the user is trying to visit the system from a reverse-proxy solution.

### How to reproduce the issue?

1. Setup ToolJet
2. Use `SUB_PATH` as documented in the docs
3. Try and open up a page in the front-end

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/3549445/190633916-4cd3ac7f-ffc9-4f65-ba9a-fe4bcb4759d1.png)

### Any possible solutions?

Use `process.env.SUB_PATH` like it's implemented in other logics. I can see that `maybeSetSubPath` would be useful.

### Can you identify the location in the driver source code where the problem exists?

Here: https://github.com/ToolJet/ToolJet/blob/e8ae8a9fe64eb1c7783fbc5ae91655671a007b35/frontend/src/i18n.js#L16

### If the bug is confirmed, would you be willing to submit a PR?

I guess so... ;)

**Comment by shivangT** [comment]
Hey @exetico 

Let me discuss this with the team & get back to you in sometime to resolve this.

Thanks

**Comment by exetico** [comment]
@kavinvenkatachalam : I just noticed that some logics is also required here:
https://github.com/ToolJet/ToolJet/blob/fb2540b4d803bd8f2387f04b919a0b832839009c/frontend/src/_components/PrivateRoute.jsx#L16

Also mentioned on Slack:
https://tooljet.slack.com/archives/C01TY0ZGH6X/p1663673494826299

> I noticed another small bug, with the reverse-proxy "support" (SUB_PATH) option.
> 
> If the user is not logged in and try to visit https://domain.com/tooljet/applications/1a22b111-111a-1111-a1f0-fa11a11e1a15?=, the user is redirected to https://domain.com/login?redirectTo=/tooljet/applications/1a22b111-111a-1111-a1f0-fa11a11e1a15  instead of https://domain.com/tooljet/login?redirectTo=/tooljet/applications/1a22b111-111a-1111-a1f0-fa11a11e1a15 .
> 
> Bug: The SUB_PATH are not added to the login-url.
> 
> Problematic workaround: I could make a specific URL handling in my proxy-service, but that would be kind of odd, cause I'd need to both add /tooljet after domain.com/, but also strip /tooljet/ from the redirectTo parameter - else the user will end up on https://domain.com/tooljet/login?redirectTo=/tooljet/applications/1a22b111-111a-1111-a1f0-fa11a11e1a1 after sign-in.
