### ISSUE TITLE
Bug : [ Event Manager ] event manager pop-up is getting closed upon changing Event value

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#4059]
### Environment
Development / Production

### What is the expected behaviour?
When event management pop-up is opened, selecting any value with select dropdown input element, pop-up should not get closed by this action. Pop-up should get closed ,only when se click outside the event management pop-up

### What is the current behaviour?
When we select any value from the select dropdown, pop-up tends to close itself.

### How to reproduce the issue?

1. Create a new application or open an existing application.
2. Drag any widget on the canvas from right sidebar. (For better understanding of issue, let's consider text input widget). So, drag text input widget.
3. Click on the label of the text input widget, which was dragged on the canvas to open widget inspector. A text input widget inspector will appear in the right sidebar.
4. Look for Events menu in the widget inspector. If no events are present , you can create event by clicking on +add handler
5. Open any existing event handler or newly created one.
6. A event manager pop-up will appear.
7. In the pop-up, For **Event** field , change the value in the select input field. (for eg - if the default value in the respective field for Event  is on Change, then change to on Enter Pressed, and vice a versa. )
9. Upon Clicking, you can observe pop-up is getting closed. That's not what we desire.

### Screenshots or Screencast
[Tooljet - Dashboard - 19 September 2022 - Watch Video](https://www.loom.com/share/8c4f629e2ebc417aa2a91679db74dbd5)

### Can you identify the location in the driver source code where the problem exists?
frontend/src/Editor/Inspector/EventManager.jsx

**Comment by saimaheshtaduri** [comment]
The issue seems interesting, can I contribute to this as part of hacktoberfest? @manishkushare

**Comment by arpitnath** [comment]
Hi @saimaheshtaduri , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by thenishantsapkota** [comment]
The issue has been stagnant for a while
Can I do this one?

**Comment by withshubh** [comment]
Hey @saimaheshtaduri - Any updates on it?

**Comment by saimaheshtaduri** [comment]
@withshubh I'll raise a pr in a day or two. 
Thanks :)

**Comment by withshubh** [comment]
Hey @saimaheshtaduri - Let us know if you're still working on it :)

**Comment by withshubh** [comment]
Closing the issue as it is fixed in ToolJet V2-beta.
