### ISSUE TITLE
[docs]: Add copy paste commands in keyboard shortcuts

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4081]
### Summary

ToolJet supports copy-pasting the components using keyboard shortcuts. In the current keyboard shortcuts, it is missing.
Copy: `ctrl/cmnd + c`
Paste: `ctrl/cmnd + v`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/tutorial/keyboard-shortcuts

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by ighmaZ** [comment]
@withshubh ! i would love to work on this issue

**Comment by shay2442** [comment]
I could fix this for you!

**Comment by withshubh** [comment]
> I could fix this for you!

Hey @shay2442 - Thanks for your interest in contributing to ToolJet, but this issue is already assigned to Ighmaz. 

Can you please pick another issue from [here](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aup-for-grabs)?

**Comment by withshubh** [comment]
> @withshubh what needs to be done exactly?

Hey @ighmaZ - You just need to document the keyboard shortcuts for copy and paste (mentioned in the description).

You'll need to clone the repo, setup the documentation locally, and then update the changes in the `keyboard-shortcuts.md` file.

**Comment by ighmaZ** [comment]
Thanks mate! Will do that

**Comment by withshubh** [comment]
> @withshubh ! my pleasure! i would love to contribute to more issues

That's great!
You can check other [open issues](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aup-for-grabs) and comment on the issue that you want to take up next.
