### ISSUE TITLE
'Select folder' dropdown on dashboard showing incorrect results.

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#410]
**Steps to recreate the issue:**
1. Log in to Tooljet.
2. Create an app.
3. Create few folders with names - 'test', 'folder1', 'older', 'td', 'der'.
4. On the app  select the 'Add to folder' option.
5. Enter text 'folder' in the 'Select folder' dropdown input placeholder.

**Expected Result:** This should not show any entry as we have not created a folder named 'folder' yet. 
The dropdown results should only show matches that have input-string as a substring.

**Actual Result:** Showing folder name which does not have word 'folder' as a substring. Please check Screenshot attached.

<img width="1792" alt="Tooljet - Select folder- Dropdown issue" src="https://user-images.githubusercontent.com/5313625/126158028-ef66df36-7711-445b-90b4-68d879377568.png">

**Comment by ajinkyaa** [comment]
@Navaneeth-pk  I am picking this issue.

**Comment by arpitnath** [comment]
picking this up
