### ISSUE TITLE
[ Enhancement ] : Calendar in date picker and range date picker components is not consistent with the dark theme

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#4110]
### Environment
Development

### What is the expected behaviour?
The calendar in the date range picker and date picker should  be consistent with the dark theme

### What is the current behaviour?
The calendar in the date range picker and date picker is  not consistent with the dark theme

### How to reproduce the issue?

1. Create a new application or open an existing one.
2. Switch to the dark theme by clicking on the half moon icon at the bottom of the left sidebar. (Please, ignore step 2, if already in dark theme.)
3. Now, let's have two component's on the canvas. One will be **Date Picker** and another will be **Range Picker**. You can look for each component in the right sidebar and drag them on the canvas.
4. Now, let's first look into the date picker, click on the date picker input field, and a calendar will appear to select the date. Please observe, the calendar is not consistent with the dark theme. That's our issue, with the date picker component.
5. Similarly, click on the Range picker component's input field, and a calendar will appear, showing two months at a time, where we can select a range of dates, which is also not consistent with the dark theme.
6. From steps 4 and 5, we understood the issue of the dark theme. Both components, persisting light theme styles, even though they are in dark themes. To understand better, try switching to the light theme and compare both components.

### Screenshots or Screencast
[ToolJet - Dashboard - 26 September 2022 - Watch Video](https://www.loom.com/share/b24c25a8527f4bb09b512989fd8b9270)

### Any possible solutions?
Apply custom CSS for dark theme in both the component

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by Shelly011s** [comment]
I would like to work on this issue.

**Comment by manishkushare** [comment]
Hey @Shelly011s , This issue has already been resolved by the internal team. You can find more such issues, in the Issue tab.
