### ISSUE TITLE
Docker development setup fails to start server

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#4127]
### Version Information
v1.26.0
### Environment

Docker development setup

### What is the expected behaviour?
Should start the server at the specified port

### What is the current behaviour?
Server fails to start at entrypoint script

### How to reproduce the issue?
Follow [documentation](https://docs.tooljet.com/docs/setup/docker)

### Screenshots or Screencast
N/A

### Please provide any traces or logs that could help here.
```
tooljet-server-1    | ./server/entrypoint.sh: 13: ./server/entrypoint.sh: declare: not found
tooljet-server-1 exited with code 127
```

### Any possible solutions?
Update the shebang for the `./server/entrypoint.sh`
From `#!/bin/sh` to `#!/bin/bash`

**Comment by mikebarr24** [comment]
As per the Slack thread. It would be great if I could pick this up.

**Comment by akshaysasidrn** [comment]
Please go ahead 👍🏾
