### ISSUE TITLE
[ hotfix ] : [ Datepicker widget ] height is not adjusting with the container height

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#4143]
### Version Information
v1.26.0

### Environment
Production

### What is the expected behaviour?
The height of the Datepicker widget should be consistent with the height of its parent container.

### What is the current behaviour?
The height is not consistent with the parent container. When we increase the height of the container, the height of the widget still remains where it was earlier.

### How to reproduce the issue?

1. Create a new application or open an existing one.
2. Drag Datepicker widget on the canvas from the right sidebar.
3. Try to increase the height of the container of the widget. You can observe, the height of the date picker is not consistent with the container height. That's our issue.
4. To understand better, drag TextInput widget on the canvas from the right sidebar. and Increase container height. The same behaviour is supposed to be with the date picker widget.

### Screenshots or Screencast

https://user-images.githubusercontent.com/37823141/192963249-c7f49f88-73e7-445a-9e62-856ad10f1384.mov

### Any possible solutions?
Make the height of the Date picker widget consistent with the parent container.

### Can you identify the location in the driver source code where the problem exists?
frontend/src/Edior/Components/Datepicker.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by AnmolBansalDEV** [comment]
I can see a PR merged for this issue, but why is this issue still open?
