### ISSUE TITLE
RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support

### ISSUE THREAD

**Issue by Houx2001** [ToolJet/ToolJet#416]
### Environment
 Docker 

### What is the current behaviour?
When create MySQL connect and test connect, the issue RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support. Connect test failed.

### Screenshots or Screencast

<img width="762" alt="截屏2021-07-23 上午11 34 46" src="https://user-images.githubusercontent.com/5194161/126734700-27738f98-eb02-4bbe-a463-727fd7090716.png">

**Comment by withshubh** [comment]
@akshaysasidrn please check this issue
