### ISSUE TITLE
Toggle Button For dark Theme

### ISSUE THREAD

**Issue by nihal-soni** [ToolJet/ToolJet#4162]
Add Toggle Button--

What I'm asking for is that add a toggle button at right corner to change the light theme into dark theme 
 
What is the current behaviour?
it has only light theme.
![Screenshot (46)](https://user-images.githubusercontent.com/109461841/193386538-4bfd30fd-5a46-4237-ab93-eff79e954450.png)
 

I hope you would like my opinion and try to improve that....

thanks....

**Comment by Navaneeth-pk** [comment]
Thanks for the suggestion. This feature is on our roadmap. Closing the issue since the website is not part of this repo. 
@nihal-soni
