### ISSUE TITLE
Add border color style property to Container widgets

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4164]
## Proposed feature
Option to change the border color of the container widget with the `Border color` property in the style tab.

### Description
Currently, the container widget only supports **Background color** , **Border radius**, **Visibility** and **Disable** as style definition.

<img width="821" alt="Screenshot 2022-10-01 at 9 56 46 AM" src="https://user-images.githubusercontent.com/67645175/193392526-355fa82a-a2a2-46d2-991f-32038a3060d0.png">

reference: https://github.com/ToolJet/ToolJet/pull/1721

**Comment by prateek565** [comment]
I would like to work on this issue.

**Comment by arpitnath** [comment]
Hi @prateek565, assigning the issue to you.
Please make sure to mention the issue in your PR, it will be easier for us to review and merge faster.
Thanks for contributing and happy hacking 🚀

**Comment by Sumitmaithani** [comment]
Hey @arpitnath I'm frontend developer and also want to contribute to this project but want ask in /frontend is built by reactjs because i can't see any public folder there like how i can run frontend code in my local machine?

**Comment by prateek565** [comment]
hi @arpitnath i have done changes in container.jsx as mentioned in reference but im unable to find components.js file in  repo which is shown in reference .can you please help.

**Comment by arpitnath** [comment]
> Hey @arpitnath I'm frontend developer and also want to contribute to this project but want ask in /frontend is built by reactjs because i can't see any public folder there like how i can run frontend code in my local machine?

@Sumitmaithani You can follow the docs for setting up ToolJet locally and also about the architecture [here]( https://docs.tooljet.com/docs/category/contributing-guide)

**Comment by arpitnath** [comment]
> hi @arpitnath i have done changes in container.jsx as mentioned in reference but im unable to find components.js file in repo which is shown in reference .can you please help.

Hi @prateek565, that pull request was just for reference. As we recently migrated the file to `widgetConfig.js`, path: `/ToolJet/frontend/src/Editor/WidgetManager/widgetConfig.js`

**Comment by prateek565** [comment]
Hi @arpitnath i have done it please review 😊.

**Comment by nilanshu24** [comment]
Hello, Can i work on this?
