### ISSUE TITLE
Proposal to add border color option to Text Input widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4165]
## Proposed feature
Option to change and update the border color of the text input widget with the `Border color` property in the style tab.

### Description
Currently, the text input widget only supports **Border radius**, **Visibility**, and **Disable** as style definitions.

<img width="616" alt="Screenshot 2022-10-01 at 10 19 24 AM" src="https://user-images.githubusercontent.com/67645175/193393088-1548028e-d521-42f8-b4c7-db3d96d7b6b2.png">

reference: https://github.com/ToolJet/ToolJet/pull/1721

**Comment by TheLearneer** [comment]
If it is up for grabs, I would love to work on it 🤚

**Comment by arpitnath** [comment]
Hi @TheLearneer, assigning the issue to you.
Please make sure to mention the issue in your PR, it will be easier for us to review and merge faster.
Thanks for contributing and happy hacking 🚀
