### ISSUE TITLE
Proposal to add border color option to Number Input widget 

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4166]
## Proposed feature
Option to change and update the border color of the number input widget with the `Border color` property in the style tab.

### Description
Currently, the number input widget only supports **Border radius**, **Visibility**, and **Disable** as style definitions.

<img width="528" alt="Screenshot 2022-10-01 at 10 23 36 AM" src="https://user-images.githubusercontent.com/67645175/193393311-aba9d486-c8bc-4624-a15f-f2be89f20338.png">

reference: https://github.com/ToolJet/ToolJet/pull/1721

**Comment by Srisuma13** [comment]
Hi @arpitnath, I would like to work on this.

**Comment by anuj98** [comment]
Hi @arpitnath Let me know if this issue is still up for grabs. I would like to work on this. Thanks

**Comment by arpitnath** [comment]
Hi @Srisuma13, assigning the issue to you.
Please make sure to mention the issue in your PR, it will be easier for us to review and merge faster.
Thanks for contributing and happy hacking 🚀

**Comment by arpitnath** [comment]
Hi @anuj98, as we assign to whoever comments first, and assigned to him/her.
You are free to explore other issues listed as [`hactoberfest`](https://github.com/ToolJet/ToolJet/labels/hacktoberfest) and will be adding more soon.

**Comment by Srisuma13** [comment]
@arpitnath Opened a PR for the above issue, https://github.com/ToolJet/ToolJet/pull/4175.
