### ISSUE TITLE
Create a data source plugin for Amazon SES

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#4167]
### Goal
Create a new datasource plugin for Amazon SES to send emails using SES API.

Operations to be supported: 
- Send a text/html email. 

### Implementation
Guide for building ToolJet plugins: https://docs.tooljet.com/docs/contributing-guide/tutorials/creating-a-plugin
Amazon SES SDK reference: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/ses-examples-sending-email.html

### Related plugins
- AWS S3
- Sendgrid 
- Mailgun

**Comment by aloks98** [comment]
I can work on this. Can you please assign this to me?

**Comment by withshubh** [comment]
Hey @aloks98 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Ruchika30** [comment]
hi  @withshubh   Kindly assign it to me too. Would like to look into as it looks like there is no update on the issue

**Comment by aloks98** [comment]
Working on it still ✌🏻
