### ISSUE TITLE
[localization] Translate global strings in french

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4169]
### Is your proposal related to a problem?

Add translations for global strings in french.

### Describe the solution you'd like

The strings needs to be translated:

```
"globals":{
        "readDocumentation":"Read Documentation",
        "cancel":"Cancel",
        "save":"Save",
        "back":"Back",
        "edit":"Edit",
        "search":"Search",
        "update":"Update",
        "delete":"Delete",
        "add":"Add",
        "view":"View",
        "create":"Create",
        "enabled":"Enabled",
        "disabled":"Disabled",
        "yes":"Yes",
        "submit":"Submit"
    },
```

Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)

**Comment by akk312000** [comment]
@withshubh  I would like to contribute to this issue

**Comment by withshubh** [comment]
Hey @akk312000 👋 
Assigned it to you.

**Comment by appledora** [comment]
@withshubh I would like to do the localization task here for Bengali. Could you assign me to an issue, if that is okay with you? 
Thanks!

**Comment by withshubh** [comment]
Hey @appledora - The issue https://github.com/ToolJet/ToolJet/issues/4174 is already assigned to you.

**Comment by appledora** [comment]
Yes, I will clear that PR first, then :D

**Comment by celcarpe** [comment]
Is anyone working on this?
