### ISSUE TITLE
[localization] Translate global strings in spanish

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4170]
### Is your proposal related to a problem?

Add translations for global strings in Spanish.

### Describe the solution you'd like

The strings need to be translated:

```
"globals":{
        "readDocumentation":"Read Documentation",
        "cancel":"Cancel",
        "save":"Save",
        "back":"Back",
        "edit":"Edit",
        "search":"Search",
        "update":"Update",
        "delete":"Delete",
        "add":"Add",
        "view":"View",
        "create":"Create",
        "enabled":"Enabled",
        "disabled":"Disabled",
        "yes":"Yes",
        "submit":"Submit"
    },
```

Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)

**Comment by akk312000** [comment]
@withshubh I would like to contribute to this issue

**Comment by withshubh** [comment]
Hey @akk312000 👋 
Please comment on one issue at a time - we have already assigned an issue to you.

**Comment by intSpartan** [comment]
@withshubh I would like to look over this. Can you please assign this to me?
Thank You

**Comment by withshubh** [comment]
Hey @intSpartan 👋 
assigned this to you.

**Comment by Elegidoadedo** [comment]
Hey! the trnaslations are not correct, some keys like save is not "ahorrar" ( as saving money), this save is related to save data so should be  "Guardar". Another point the isocode for spanish is not sp is "es" .

I added theses changes in this PR -> https://github.com/ToolJet/ToolJet/pull/4230

**Comment by WadekarPrashant** [comment]
Hey, can I work on this issue? Please assign it to me.
@Elegidoadedo

**Comment by withshubh** [comment]
Hey @intSpartan 
We're prioritizing native speakers' PR for localization as we're getting wrong translations when a non-native submit a PR.
We'll have to assign it to @Elegidoadedo.
Feel free to look for other open issues.
