### ISSUE TITLE
Add background color style in text input widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4171]
## Proposed feature
Option to change and update the background color of the text input widget with the `Background color` property in the style tab.

### Description
Currently, the text input widget only supports **Border radius**, **Visibility**, and **Disable** as style definitions.

<img width="573" alt="Screenshot 2022-10-01 at 11 13 34 AM" src="https://user-images.githubusercontent.com/67645175/193394576-9cc2ba3b-6dae-47eb-8276-b237d6a808a0.png">

reference: https://github.com/ToolJet/ToolJet/pull/1721

**Comment by rahulsunil2** [comment]
@arpitnath I would love to work on this issue.

**Comment by arpitnath** [comment]
Hi @rahulsunil2, assigning the issue to you.
Please make sure to mention the issue in your PR, it will be easier for us to review and merge faster.
Thanks for contributing and happy hacking 🚀

**Comment by shreyas20003** [comment]
@arpitnath  Hey , I am Shreyas . I like to Work on this issue . I am new to this platform please help me.

**Comment by withshubh** [comment]
Hey @shreyas20003 This issue is already assigned. Can you check other issues with `Hacktoberfest` tag?

**Comment by arpitnath** [comment]
Hi @shreyas20003, as we assign to whoever comments first, and assigned to him/her.
You are free to explore other issues listed as [hactoberfest](https://github.com/ToolJet/ToolJet/labels/hacktoberfest) and will be adding more soon.

cc: @shubh22

**Comment by shreyas20003** [comment]
@arpitnath It's Okay .Thankyou for ur help

**Comment by rahulsunil2** [comment]
@arpitnath I have added this feature and posted a PR #4194. Please take a look at it.
