### ISSUE TITLE
Add on change event in Number Input Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4172]
### Is your proposal related to a problem?

Currently, there are no event handlers for the number Input component. We should have an event `on change` whenever value in the component is changed.

### Describe the solution you'd like

The number input configuration pane should have an "Events" section, just like other components.

Refer to this PR: https://github.com/ToolJet/ToolJet/pull/4058

**Comment by rahulsunil2** [comment]
@withshubh I would love to work on this issue.

**Comment by withshubh** [comment]
Hey @rahulsunil2 👋 
Assigned this to you.

**Comment by withshubh** [comment]
Hey @rahulsunil2 There is already an issue assigned to you. Please don't comment on multiple isses.

**Comment by mikebarr24** [comment]
I'd love to work on this if that's OK.

**Comment by withshubh** [comment]
Hey @mikebarr24 👋 
Sure, assigned this to you.

**Comment by shreyas20003** [comment]
@withshubh Can i do this
