### ISSUE TITLE
Add On change event in Password Input Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4173]
### Is your proposal related to a problem?

Currently, there are no event handlers for the Password Input Component. We should have an event `on change` whenever the value in the component is changed.

### Describe the solution you'd like

The Password Input's configuration pane should have an "Events" section, just like other components.

Refer to this PR: https://github.com/ToolJet/ToolJet/pull/4058

**Comment by MohammedBajuaifer** [comment]
Hey @withshubh, I'd love to work on this if that's OK.

**Comment by withshubh** [comment]
Hey @MohammedBajuaifer 👋 
Assigned it to you.
