### ISSUE TITLE
Add background color style in number input widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4177]
## Proposed feature
Option to change and update the background color of the number input widget with the `Background color` property in the style tab.

### Description
Currently, the number widget only supports **Border radius**, **Visibility**, and **Disable** as style definitions.

<img width="530" alt="Screenshot 2022-10-01 at 11 51 37 AM" src="https://user-images.githubusercontent.com/67645175/193395767-aad634ae-ebc6-4c4d-9f0f-c67a9de4f2b9.png">

reference: https://github.com/ToolJet/ToolJet/pull/1721

**Comment by carefreeav09** [comment]
I would like to take this one please.

**Comment by SanjaySargam** [comment]
Can U plz assign me ?

**Comment by arpitnath** [comment]
Hi @SanjaySargam,
Thanks for showing interest in contributing to ToolJet, but we have to assign the issue to the first person who expressed interest. 

You can check out other open issues here: [hactoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest.)

**Comment by SanjaySargam** [comment]
> Hi @SanjaySargam, Thanks for showing interest in contributing to ToolJet, but we have to assign the issue to the first person who expressed interest.
> 
> You can check out other open issues here: [hactoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest.)

Okk Thank You

**Comment by arpitnath** [comment]
Hi 👋🏻 @carefreeav09,

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by carefreeav09** [comment]
Thank you. And thanks SanjaySargam for being a good sport.
