### ISSUE TITLE
Add On change event in range slider component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4178]
### Is your proposal related to a problem?

We should have an event `on change` event handler for the range slider component whenever the value in the component is changed.

### Describe the solution you'd like

The range slider configuration pane should have an option `On change` in the events section, just like other components.

Refer to this PR: https://github.com/ToolJet/ToolJet/pull/4058

**Comment by Srisuma13** [comment]
@withshubh Could you please assign this to me? I would like to work on it.

**Comment by withshubh** [comment]
Hi @Srisuma13 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by arpitnath** [comment]
@Srisuma13 There is an issue already assigned to you.
Please resolve the assigned one first and then get a new issue assigned to yourself 😁

Thanks for contributing! Happy hacking 🚀
cc: @withshubh

**Comment by Srisuma13** [comment]
Raised a [PR](https://github.com/ToolJet/ToolJet/pull/4190)  for it @arpitnath @withshubh. Is it fine if I could take this up now?

**Comment by arpitnath** [comment]
@Srisuma13 Sure 😁
