### ISSUE TITLE
Correction in documentation for 'Adding a new widget to mobile layout' 

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#418]
1. In the section _**Mobile layout**_ , update the first line - "_Widgets can be shown **on** desktop, mobile, or both_".
2. In the section ‘_**Adding a new widget to mobile layout**_’, the last line should be corrected to - "_This widget will not be shown on desktop layout unless enabled “from” the widget inspector via the “Show on desktop?” button manually._"

     URL: https://docs.tooljet.io/docs/tutorial/mobile-layout

<img width="1054" alt="Screenshot 2021-07-23 at 10 24 59 PM" src="https://user-images.githubusercontent.com/5313625/126816043-38e3d85b-d92e-4da1-b391-9f1dca7dc3a8.png">

**Comment by arpitnath** [comment]
picking this up
