### ISSUE TITLE
Add background color style in password input widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4181]
## Proposed feature
Option to change and update the background color of the password input widget with the `Background color` property in the style tab.

### Description
Currently, the password widget only supports **Border radius**, **Visibility**, and **Disable** as style definitions.

<img width="528" alt="Screenshot 2022-10-01 at 10 34 16 AM" src="https://user-images.githubusercontent.com/67645175/193396284-8922517e-48d5-435d-8c50-febc058256e4.png">

reference: https://github.com/ToolJet/ToolJet/pull/1721

**Comment by Srisuma13** [comment]
Hi @arpitnath, I would like to work on this :)

**Comment by arpitnath** [comment]
Hi @Srisuma13 , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Srisuma13** [comment]
@arpitnath Thanks for assigning!

**Comment by harshit-dugar** [comment]
Hi is this issue resolved? @arpitnath

**Comment by WadekarPrashant** [comment]
Hey, the person to whom you assigned this seems inactive.
Hey, can I work on this issue? Please assign it to me.
@arpitnath
