### ISSUE TITLE
[localization] Translate Component Manager in French

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4182]
### Is your proposal related to a problem?

Add translations for the component manager in French

### Describe the solution you'd like

The strings need to be translated:

![Screenshot 2022-09-30 at 3 40 23 PM](https://user-images.githubusercontent.com/25361949/193396346-b5b3f0cf-fb30-490f-969e-5fd90e684f07.png)

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

**Comment by Zunaid24** [comment]
I'd like to work on this issue.

**Comment by arpitnath** [comment]
Hi @Zunaid24, 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by arushmangal** [comment]
Incase the assignee is unable to resolve the issue, I can resolve it!

**Comment by Zunaid24** [comment]
> Incase the assignee is unable to resolve the issue, I can resolve it! @arpitnath

Hey @arushmangal, Thanks but I'm still working on it.
