### ISSUE TITLE
[localization] Translate Component Manager in Spanish

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4184]
### Is your proposal related to a problem?

Add translations for the component manager in Spanish

### Describe the solution you'd like

The strings need to be translated:

![Screenshot 2022-09-30 at 3 40 23 PM](https://user-images.githubusercontent.com/25361949/193396346-b5b3f0cf-fb30-490f-969e-5fd90e684f07.png)

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

**Comment by varun7singh** [comment]
assign it to me please

**Comment by withshubh** [comment]
> assign it to me please
> 

Hey @varun7singh 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by varun7singh** [comment]
do i need to make a new es.json file with only widget manager in spanish

**Comment by withshubh** [comment]
> do i need to make a new es.json file with only widget manager in spanish

Correct. @varun7singh

**Comment by LPRegen** [comment]
Hi, I'm not sure if @varun7singh will continue working on this but if this is available, I would like to take it.

**Comment by withshubh** [comment]
Hey @varun7singh - Unassigning this issue as there was no update on it for more than 15 days.

Assigning it to @LPRegen
