### ISSUE TITLE
[localization] Translate Profile Settings Page in French

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4185]
### Is your proposal related to a problem?

Add translations for the Profile Settings Page in French

### Describe the solution you'd like

The strings need to be translated:

![Screenshot 2022-09-30 at 3 41 54 PM](https://user-images.githubusercontent.com/25361949/193396532-e5a922d7-d0ec-424e-b0bc-e444b240f243.png)

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

**Comment by Shelly011s** [comment]
I would like to work on this.

**Comment by arpitnath** [comment]
Hi @Shelly011s , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Anshumansengar** [comment]
Hey, I would Like to work on this issue too.

**Comment by withshubh** [comment]
> Hey, I would Like to work on this issue too.

Hi @Anshumansengar , 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by WadekarPrashant** [comment]
Hey, the person to whom you assigned this seems inactive.
Hey, can I work on this issue? Please assign it to me.
@withshubh @arpitnath

**Comment by Shelly011s** [comment]
@arpitnath hello, I am sorry but I am having trouble setting up the project and no one on slack is able to help me, hence I will not be able to work on this issue.

**Comment by arushmangal** [comment]
Hey, I can take this issue up! @withshubh

**Comment by Shelly011s** [comment]
@withshubh @arpitnath Hey I just figured the issues with setting up the project and I have started working on this issue. So kindly do not unassign me.
