### ISSUE TITLE
[localization] Translate Profile Settings Page in Spanish

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4186]
### Is your proposal related to a problem?

Add translations for the Profile Settings Page in Spanish

### Describe the solution you'd like

The strings need to be translated:

![Screenshot 2022-09-30 at 3 41 54 PM](https://user-images.githubusercontent.com/25361949/193396532-e5a922d7-d0ec-424e-b0bc-e444b240f243.png)

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

**Comment by Ambareen09** [comment]
Please assign this to me

**Comment by withshubh** [comment]
Hi @Ambareen09 👋  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by taicoding** [comment]
Hi there, I'm a native spanish speaker and after chekking the [PR #4205](https://github.com/ToolJet/ToolJet/pull/4205) I found some grammar mistakes that make the texts lose its meaning. Since the PR is not merged I would like to work in a better translation.

**Comment by Ambareen09** [comment]
Can you please leave a review, as I have done what I could do, and allow my correct contributions to reflect towards this PR?

**Comment by taicoding** [comment]
@Ambareen09 I open a [PR ](https://github.com/Ambareen09/ToolJet/pull/1) on your forked repo with the corrections

**Comment by Ambareen09** [comment]
@taicoding I merged you PR in my repo. I have opened PR in this main repo, #4205 , If you want you can sign the CLA as well!
