### ISSUE TITLE
[localization] Translate App Card in French

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4187]
### Is your proposal related to a problem?

Add translations for the App Card in French

### Describe the solution you'd like

The strings need to be translated:

![Screenshot 2022-09-30 at 3 43 04 PM](https://user-images.githubusercontent.com/25361949/193396625-72a1d252-9f8e-410e-8dc9-19657a6d44c6.png)

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

**Comment by vedant-z** [comment]
Hey @withshubh 

I want to take this issue

**Comment by withshubh** [comment]
> Hey @withshubh 
> 
> I want to take this issue

Hey @vedant-z 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by vedant-z** [comment]
If I am not wrong in **frontend/assets/translations/fr.json** file I need to just translate the strings i.e.  "Change Icon, Add to folder...." leaving their respective variable names unchanged 

Am I on the right track?

**Comment by withshubh** [comment]
> If I am not wrong in **frontend/assets/translations/fr.json** file I need to just translate the strings i.e. "Change Icon, Add to folder...." leaving their respective variable names unchanged
> 
> Am I on the right track?

Correct @vedant-z

**Comment by vedant-z** [comment]
@withshubh I have made PR 
Please check it
