### ISSUE TITLE
[localization] Translate App Card in Spanish

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4188]
### Is your proposal related to a problem?

Add translations for the App Card in Spanish

### Describe the solution you'd like

The strings need to be translated:

![Screenshot 2022-09-30 at 3 43 04 PM](https://user-images.githubusercontent.com/25361949/193396625-72a1d252-9f8e-410e-8dc9-19657a6d44c6.png)

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

**Comment by Sujithkumardola** [comment]
i would like to take up this issue

**Comment by withshubh** [comment]
Hey @Sujithkumardola 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Sujithkumardola** [comment]
@withshubh could you please look at this [repo](https://github.com/Sujithkumardola/ToolJet/tree/feature/support-for-spanish)

**Comment by SupOrg** [comment]
the translations that you have added are not correct... I say this as a native Apanish speaker. If you want me to fix them, mention me and I can work on it :)

**Comment by Sujithkumardola** [comment]
> the translations that you have added are not correct... I say this as a native Apanish speaker. If you want me to fix them, mention me and I can work on it :) 

@withshubh Could you please assign him this issue.

Since I'm not a native speaker my translations could be wrong.

**Comment by arpitnath** [comment]
@SupOrg Would you like to work on this issue as @Sujithkumardola won't be working on it?

**Comment by Sujithkumardola** [comment]
@arpitnath I would like to contribute to the localization of Hindi And Telugu if Possible

**Comment by arpitnath** [comment]
Hi @Sujithkumardola, 
Thanks for showing interest in contributing to ToolJet.
Localization support for Hindi and Telugu is not in our roadmap.

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

Thanks 😅

**Comment by exitflynn** [comment]
Hello there! :wave: 
I'd love to take up this issue if no one's working on it!

**Comment by vedant-z** [comment]
@withshubh May I work on this please

**Comment by exitflynn** [comment]
could you check the above PR please?

**Comment by dmdbilal** [comment]
Is this issue still open?

**Comment by SupOrg** [comment]
@arpitnath yes, i would love to work on this one :) The translation from @exitflynn still not correct. Please assign it to me

**Comment by Elegidoadedo** [comment]
Hey! i created a PR for the spanish translation card keys.  Since is not yet assigned i just make the PR. 
Regards :)

https://github.com/ToolJet/ToolJet/pull/4229

**Comment by Navaneeth-pk** [comment]
Thanks but there is already another PR for this issue. Also please work only on issues that are assigned to you. Since there are two PRs already, we will take a look and merge the one that's more accurate in this case. 
@Elegidoadedo

**Comment by withshubh** [comment]
Hey @SupOrg 
Assigning this issue to you.

**Comment by withshubh** [comment]
Hey @SupOrg 
Are you still working on it?

**Comment by vedant-z** [comment]
Hey @withshubh if @SupOrg isn't available for working I would like to work on this

**Comment by withshubh** [comment]
> Hey @withshubh if @SupOrg isn't available for working I would like to work on this

Hey @vedant-z - As mentioned by Navaneeth in the previous comment, we already have two PRs for this issue. You can look for any other open issues.

**Comment by withshubh** [comment]
@Navaneeth-pk - Closing the PR by @exitflynn as it was reviewed by a native speaker and there are no updates on it.

**Comment by ShankyJS** [comment]
I'm happy to do this one, I'm native Spanish speaker.

**Comment by withshubh** [comment]
> I'm happy to do this one, I'm native Spanish speaker.

Hey @ShankyJS 
Thank you for your interest in contributing to ToolJet but there is already a PR #4229 by a native speaker. You can look for other open issues.

**Comment by withshubh** [comment]
Hey @ShankyJS - Check the comment here https://github.com/ToolJet/ToolJet/issues/4523#issuecomment-1283830862

**Comment by ShankyJS** [comment]
Hey @withshubh, thanks! Already commented please assign that one to me, will start working on it!

**Comment by Elegidoadedo** [comment]
@ShankyJS is already done the PR, i'm just waiting for the merge :)
