### ISSUE TITLE
Add text color style in number input widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4189]
## Proposed feature
Option to change and update the text color of the number input widget with the `Text color` property in the style tab.

### Description
Currently, the number input widget only supports **Border radius**, **Visibility**, and **Disable** as style definitions.

<img width="528" alt="Screenshot 2022-10-01 at 10 23 36 AM" src="https://user-images.githubusercontent.com/67645175/193396732-78fe88ac-30b9-4686-85fe-c3191335d6d3.png">

reference: https://github.com/ToolJet/ToolJet/pull/1721

**Comment by danielevilela** [comment]
Can I work on this one?

**Comment by arpitnath** [comment]
Hi @danielevilela , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by navyansh007** [comment]
Hello, I am eager to work on this issue

**Comment by Ruchika30** [comment]
hi  @arpitnath  Kindly assign it to me too. Would like to look into as it looks like there is no update on the issue
