### ISSUE TITLE
Minimise canvas button showing scale text in decimals if value less than 70%

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#419]
Steps to recreate :
1. Log in to Tooljet.
2. Click on 'Create new app' on the dashboard to open Editor. (Click on the 'Edit' button if an app is already created.)
3. On the top navigation bar, click on minimize button to change the canvas scale.

Expected result: Canvas scale minimizes and scale value is shown on Navigation bar beside the 'minimize/maximize' buttons in percentage.

Actual result: If the canvas scale is reduced to less than 70%, the value is showing in decimals(50.000000000000014% and 60.00000000000001%) as shown in the screenshot below.

<img width="1792" alt="Screenshot 2021-07-26 at 1 16 33 PM" src="https://user-images.githubusercontent.com/5313625/126953281-cd294433-0482-418f-b1e7-4320161b846b.png">

**Comment by xrimpy** [comment]
Needs to be rounded, assign me.

**Comment by mohinid** [comment]
> Needs to be rounded, assign me.

@Navaneeth-pk Please assign
