### ISSUE TITLE
Docker: The Server Container Keeps Shutting Down.

### ISSUE THREAD

**Issue by rahulsunil2** [ToolJet/ToolJet#4197]
### Environment
Docker

### What is the expected behaviour?
The server getting deployed properly

### What is the current behaviour?
The server container keeps shutting down.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/22911414/193403956-57039203-5f1d-47af-80da-fb089d2b1542.png)

### Can you identify the location in the driver source code where the problem exists?
server\entrypoint.sh

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by arpitnath** [comment]
@rahulsunil2 
can you share the logs pls?

**Comment by rahulsunil2** [comment]
![image](https://user-images.githubusercontent.com/22911414/193404219-c84dc8c1-f066-4ef2-ab63-c4688ec551a3.png)
I have figured a fix, Can I post a PR for that?

**Comment by arpitnath** [comment]
ref: https://github.com/ToolJet/ToolJet/issues/4127

**Comment by rahulsunil2** [comment]
@arpitnath I'm sorry, I was facing this issue when I was working on a different issue and I fixed it for that. Can you please merge the PR posted before and fix this issue?

**Comment by arpitnath** [comment]
@rahulsunil2 Yeah will merge it as soon as possible.
Thank you 😅

**Comment by arpitnath** [comment]
@rahulsunil2 
For the time being, can you just update the shebang and carry on with your issue?
Just don't commit the `entryfile.sh` 
Thanks 😁

**Comment by rahulsunil2** [comment]
@arpitnath Sure, Thanks 👍

**Comment by arpitnath** [comment]
@rahulsunil2 Resolved!
