### ISSUE TITLE
Dashboard is empty

### ISSUE THREAD

**Issue by MLeissner** [ToolJet/ToolJet#4200]
When i start tooljet, the dashboard is empty, but on the console there are two errors

### Environment

    ToolJet Docker / Synology

### What is the expected behaviour?

  Tooljet should start with a functional dashboard

### What is the current behaviour?

  Tooljet starts with an empty dashboard and on the console there are two errors

### How to reproduce the issue?

1. Start Tooljet
2. Dashboard is empty

### Screenshots or Screencast

![2022-10-01 13_16_20-](https://user-images.githubusercontent.com/114809154/193407040-8a140093-38b7-458c-8b57-545a7483ee34.jpg)

### Please provide any traces or logs that could help here.
------------------ stack .env

version: '3'

services:
  client:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-client-ce:latest
    restart: always
    env_file: stack.env
    depends_on:
      - server
    volumes:
      - logs:/var/log/openresty/
      - certs:/etc/resty-auto-ssl/
      - fallbackcerts:/etc/fallback-certs
    ports:
      - 9102:80
      - 9101:443
    command: openresty -g "daemon off;"

  server:
    image: tooljet/tooljet-server-ce:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3000
    env_file: stack.env
    environment:
      SERVE_CLIENT: "false"
    command: npm run db:seed:prod

volumes:
  certs:
  logs:
  fallbackcerts:

----------- docker-compose.yaml

TOOLJET_HOST=http://XXXXXXXXXXX:9102
LOCKBOX_MASTER_KEY=replace_with_lockbox_master_key
SECRET_KEY_BASE=replace_with_secret_key_base
ORM_LOGGING=all
PG_DB=tooljetDB
PG_USER=postgres
PG_HOST=XXXXX
PG_PASS=XXXXX
DEFAULT_FROM_EMAIL=hello@tooljet.io

**Comment by akshaysasidrn** [comment]
Could you kindly share the logs?

**Comment by MLeissner** [comment]
This issue is done because i discussed it then on slack. And now i don't have the logs anymore. So this issue can be closed.

Thank you
Michael

Von: Akshay
Gesendet: Donnerstag, 13. Oktober 2022 14:19
An: ToolJet/ToolJet ***@***.***>
Cc: Michael Leissner ***@***.***>; Author ***@***.***>
Betreff: Re: [ToolJet/ToolJet] Dashboard is empty (Issue #4200)


Could you kindly share the logs?
