### ISSUE TITLE
Text input widget: Option to customise the error message styles for validations

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4204]
## Proposed improvement
Option to customise the error message styles for validation.

Currently, the error message color is red.
<img width="208" alt="Screenshot 2022-10-01 at 7 26 43 PM" src="https://user-images.githubusercontent.com/67645175/193413005-03b0919f-0e48-4e6c-ade6-1d281dcd907d.png">

**Proposed improvement is the ability to change the color of the error message.**

**Comment by andreaevolo** [comment]
I'll take care of that !

**Comment by arpitnath** [comment]
Hi @andreaevolo , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Manthan-Kuber** [comment]
@arpitnath Can you assign it to me if it's still unsolved? I am willing to solve it.

**Comment by withshubh** [comment]
Hey @andreaevolo 
Let me know if you're still working on the issue?
Else we can assign it to @Manthan-Kuber.

**Comment by withshubh** [comment]
Hey @andreaevolo - Unassigned the issue since there was no update for a long time.

Hey @Manthan-Kuber - Assigned the issue to you.
