### ISSUE TITLE
Text widget: Default value for background color

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4207]
## Proposed improvement
Add default value for background color
Default value: **#fff00000**

> This won't set the default value for text widgets that are already dropped in the editor for older apps.

**Comment by laurisseau** [comment]
Hey, can I work on this?

**Comment by arpitnath** [comment]
Hi @laurisseau , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by laurisseau** [comment]
where is the CSS file

**Comment by arpitnath** [comment]
@laurisseau 
Add `backgroundColor: { value: '#fff00000' }` in widgetConfig.js
Line: 1841

**Comment by laurisseau** [comment]
ok

**Comment by nilanshu24** [comment]
Hi, I am interested to work, can i work on this?

**Comment by AbhishekTiwari23** [comment]
If the issue still exists, then please let me know. I want to contribute

**Comment by arpitnath** [comment]
@laurisseau Any updates on this issue?

**Comment by Abhay5855** [comment]
Can I work on this issue?

**Comment by biswadeep25** [comment]
@arpitnath Can you assign this issue to me?

**Comment by withshubh** [comment]
Unassigned @laurisseau as there was no update on it.

**Comment by withshubh** [comment]
Hey @biswadeep25 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by SanjoyPator1** [comment]
Hi, I am interested in this issue. Can I work on this issue?

**Comment by withshubh** [comment]
Hey @biswadeep25 - Any update on the PR?

**Comment by Aviroop-001** [comment]
Hi @withshubh, I'd like to enhance the feature, please assign me the issue.

**Comment by withshubh** [comment]
@Aviroop-001 Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you.

**Comment by rushikeshadhav** [comment]
Is this issue still open? If yes then I would like to work on it.
