### ISSUE TITLE
`tooljet-plugins-1` container fails to start

### ISSUE THREAD

**Issue by appledora** [ToolJet/ToolJet#4208]
### Environment

*Docker* : 20.10.18
*Docker Desktop* : 4.12.0
*Linux* : Pop!_OS 22.04 LTS x86_64 
*Shell* : zsh 5.8.1 
### What is the expected behaviour?

After doing `docker compose up`, 4 containers are supposed to be running : 
1. tooljet-server-1
2. tooljet-client-1
3. tooljet-plugins-1
4. tooljet-postgres-1
![image](https://user-images.githubusercontent.com/27975232/193413637-914f69f4-26a6-4780-8c81-7e08e06f62da.png)

### What is the current behaviour?

`tooljet-plugins-1` container doesn't work. Throws the following error : 
`tooljet-server-1 | ./server/entrypoint.sh: 13: ./server/entrypoint.sh: declare: not found`
### How to reproduce the issue?
use a `zsh` or `bash` terminal

### Any possible solutions?
Yes, the `shebang-line` used in the `entrypoint.sh` is not appropriate for `bash` or `zsh` based shells. Current shebang should be manually replaced by developers if trying to run locally to something like `#!/bin/bash`. 

### Can you identify the location in the driver source code where the problem exists?
`server/entrypoint.sh`

### If the bug is confirmed, would you be willing to submit a PR?
Yes, technically, there need not be a change in the `entrypoint.sh` file. But a **Note** should added in the contribution guideline file. I would be really happy to get this assigned to me.

**Comment by appledora** [comment]
@withshubh

**Comment by arpitnath** [comment]
@appledora 
Can you pull the latest **develop** and try once again?
Reference https://github.com/ToolJet/ToolJet/issues/4127

**Comment by appledora** [comment]
Yeah, checked the changes in the merged commit. Works now. Should it still get mentioned in the contributors guideline?

**Comment by arpitnath** [comment]
Awesome 👍🏻 
Closing the issues!
