### ISSUE TITLE
Text widget: Default value for text color

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4209]
## Proposed improvement
Add default value for text color
Default value: **#000000**

> This won't set the default value for text widgets that are already dropped in the editor for older apps.

**Comment by PrabeshPP** [comment]
Hey! I am interested in this issue .Can you assign me ?

**Comment by arpitnath** [comment]
Hi @PrabeshPP, 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by dmdbilal** [comment]
I want to work on this issue.

**Comment by vedant-z** [comment]
@dmdbilal I think if someone has already been assigned this issue, you can't make PR for this one.

This is upto my knowledge regarding ToolJet's guidelines.

**Comment by dmdbilal** [comment]
Can you assign me this issue.

**Comment by Navaneeth-pk** [comment]
@dmdbilal please do not spam by commenting on issues that are assigned to someone else and by creating PRs for issues on which others are working on.

**Comment by dmdbilal** [comment]
Ok sorry
