### ISSUE TITLE
'Launch' button on dashboard should be disabled if app is not saved with an assigned version

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#421]
Steps to recreate:

1. Log in to Tooljet
2. Click on 'create new app' on the dashboard. It should open the app in the editor.
3. Navigate back to the dashboard from the browser or by clicking the Tooljet icon on the top left corner.

**Expected result:** 'Launch' button on the app should be _'disabled'_ with a _'tooltip'_ showing appropriate description.

**Actual result:** 'Launch' button is _enabled_ on the dashboard even if no version is assigned to the app.

<img width="1792" alt="Screenshot 2021-07-27 at 1 16 41 PM" src="https://user-images.githubusercontent.com/5313625/127143767-bb741d44-18ea-4923-a3d6-6e8ab4c12bbe.png">

**Comment by virajbahulkar** [comment]
Picking this up.
