### ISSUE TITLE
Need deployment flow from one stage to another

### ISSUE THREAD

**Issue by PrasanthKumar77** [ToolJet/ToolJet#4211]
### Is your proposal related to a problem?

Need to separate app changes between stages. currently if i wanted to make some changes and test with beta creds i am taking a new version and updating all sources creds and after changes i am taking a new version and replacing all prods creds. this is a tedious process and error prone.

### Describe the solution you'd like

apps should have stages and creds should be available for stages all the changes made in the stage should have creds setup for that stage
should be able to update queries and ui changes of app beta stage to prod stage like how we merge branches in git. this would be a wonderful feature if provided.

**Comment by withshubh** [comment]
Hey @PrasanthKumar77 

Thanks for creating the issue. This feature is under development, we will let you know once the feature is released.

**Comment by PrasanthKumar77** [comment]
Hi @withshubh, May i know if this in your roadmap for future releases

**Comment by withshubh** [comment]
Hey @PrasanthKumar77 - This feature will be released along with ToolJet V2.
