### ISSUE TITLE
Queries and source creds can be changed in published version

### ISSUE THREAD

**Issue by PrasanthKumar77** [ToolJet/ToolJet#4213]
### Environment
Docker

### What is the expected behaviour?
queries and source creds should not be allowed to change like how it is handled for ui changes

### What is the current behaviour?
queries can be changed and a mistake in updation of query is leading to issues

### How to reproduce the issue?

1. create a app 
2. add some queries and database source
3. publish the app
4. change the query

**Comment by withshubh** [comment]
Hey @PrasanthKumar77 

We are looking into it. We'll share updates on it soon.
