### ISSUE TITLE
Query is missing when version is published or new version is created

### ISSUE THREAD

**Issue by PrasanthKumar77** [ToolJet/ToolJet#4214]
### Environment
 Docker 

### What is the expected behaviour?
queries should persist and should not disappear

### What is the current behaviour?
when a version is published or new vesion is released the first query is getting disappeared and asking for confirmation that `query is changed. do you want to save` in reality i have not made any changes. if i accidentally click on yes it is being removed totally else on clicking no and switch between other query and coming back to the same query again will show the actual query

### How to reproduce the issue?

1. create a app
2. add some queries
3. publish the version
4. it will ask form confirmation saying query is changed.

**Comment by shubh22** [comment]
Hi @PrasanthKumar77 ,
What is the version for your ToolJet instance?

**Comment by PrasanthKumar77** [comment]
hi  @shubh22,
i am currently using 1.14.0 but the issue can be reproduced in latest version also.

**Comment by shubh22** [comment]
This has been fixed.
