### ISSUE TITLE
Customizing the Toast notification for different pages

### ISSUE THREAD

**Issue by Roaster05** [ToolJet/ToolJet#4226]
### Is your proposal related to a problem?

I am too much bored with the same toast notification floating on every website.
### Describe the solution you'd like

I can customize the Toastify notification according to the need for the site each time a success ,warn or error notification has to be pushed.
### If the feature is approved, would you be willing to submit a PR?
Definitely Yes

**Comment by withshubh** [comment]
Hey @Roaster05 
Thanks for creating the issue. Closing this issue as the feature is currently not on our roadmap.
