### ISSUE TITLE
On hovering the Link widget, a tooltip should be displayed 

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4233]
### Environment
The latest `develop`

### What is the expected behaviour?
On hovering the widget, a tooltip should be displayed if a tooltip is provided in the widget inspector.

### What is the current behaviour?
With a tooltip provided, on hover, there is no tip that is being displayed

### How to reproduce the issue?

1. Add Link widget from widget manager
2. Click on the config handler of the widget to open up the widget inspector
3. Provide a tooltip (expected type is a **String)**
4. Hover on the widget

**Comment by PaarthAgarwal** [comment]
Assign it to me please

**Comment by zainbinfurqan** [comment]
@arpitnath Can i work on this issue?

**Comment by Gurpreet-Singh-Bhupal** [comment]
Hi @arpitnath  ,please assign me this issue I have worked on similar type of bug before.Thanks in advance.

**Comment by Sukriti-m** [comment]
Hi @arpitnath 
I'd like to work on this issue. Please assign it to me.

**Comment by harshit-dugar** [comment]
@arpitnath I would like to work on this

**Comment by arpitnath** [comment]
Thanks, everyone, for showing interest in contributing to ToolJet but we have to assign the issue to the first person who expressed interest.

Since @PaarthAgarwal has already one issue assigned for which no PR has been raised yet, so assigning this issue to the second person who showed interest.

Assigning to @zainbinfurqan 😅

You can check out other open issues here: https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest.
cc: @HVbajoria @Borges53 @exitflynn @alammoiz @PaarthAgarwal

**Comment by keerthanasathya** [comment]
> Thanks, everyone, for showing interest in contributing to ToolJet but we have to assign the issue to the first person who expressed interest.
> 
> Since @PaarthAgarwal has already one issue assigned for which no PR has been raised yet, so assigning this issue to the second person who showed interest.
> 
> Assigning to @zainbinfurqan 😅
> 
> You can check out other open issues here: https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest.

Hey @arpitnath , where can I find unassigned issues to contribute?!

**Comment by Abhay5855** [comment]
Can I work on this issue?

**Comment by akarsh-jain-790** [comment]
@zainbinfurqan are you still working? If not @arpitnath can you assign this issue to me?

**Comment by zainbinfurqan** [comment]
@akarsh-jain-790  yes i am working on it.

**Comment by zainbinfurqan** [comment]
HI @arpitnath  i just tried to reproduce the issue but seems like its behaving as expected.
<img width="295" alt="Screen Shot 2022-10-19 at 2 01 02 PM" src="https://user-images.githubusercontent.com/30855000/196646410-764dc73f-ae7f-41c3-9055-ebc0ec81c6c2.png">
