### ISSUE TITLE
Remove duplicate code from codebase

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4234]
## Description
Remove duplicate **onHover** events from `appUtils.js`

Source: `frontend/src/_helpers/appUtils.js` ~ **Line 487**

**Comment by unnikrishnan2002** [comment]
Can I do that ?

**Comment by AnkushGoel251** [comment]
I have been looking to contribute in hacktoberfest, assign this to me.

**Comment by PaarthAgarwal** [comment]
Please assign it to me

**Comment by arpitnath** [comment]
Hi @AnkushGoel251 and @PaarthAgarwal,

Thanks for showing interest in contributing to ToolJet but we have to assign the issue to the first person who expressed interest. 

You can check out other open issues here: [hacktober issues](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by arpitnath** [comment]
Hi @unnikrishnan2002 , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by PaarthAgarwal** [comment]
> Hi @AnkushGoel251 and @PaarthAgarwal,
> 
> Thanks for showing interest in contributing to ToolJet but we have to assign the issue to the first person who expressed interest.
> 
> You can check out other open issues here: [hacktober issues](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

All good. Found another open issue😄
