### ISSUE TITLE
Clear input field after creating a group.

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#4235]
### Environment
    ToolJet Cloud

### What is the expected behaviour?

It should clear the input field after creating a group.

### What is the current behaviour?
It is not clearing the input field after creating a group.

### How to reproduce the issue?

1. Select Manage groups 
2. Create a group 
3. Click on Create new group button

### Screenshots or Screencast
[Video](https://drive.google.com/file/d/1gdtv4eJzoV4Q_71Hqi5SJYyd6PxhvFQM/view?usp=sharing)

**Comment by ShaunThayil** [comment]
Hey @arpitnath I would like to work on this issue

**Comment by abhishek-goswamii** [comment]
hey @arpitnath, is anyone working on this bug? 
can you share some references on how to get started with tooljet enviroment

**Comment by arsalan-nasir** [comment]
Hey @arpitnath , I would like to work on this issue, please assign it to me. I know the solution of this bug. I will raise the PR ASAP
Thanks

**Comment by exitflynn** [comment]
hi @arpitnath, I'd LOVE to work on this issue too!

**Comment by GovindaTakekar** [comment]
Hey I am a new contributor, Can you please please assign me this issue?

**Comment by Gurpreet-Singh-Bhupal** [comment]
Hi @ajith-k-v , I am very well known with the solution of the issue and fixed this type of problems before,please assign me this issue.

**Comment by Frenchtoast0** [comment]
Hi, if no one else has been assigned this issue, I would be interested in tackling it.

**Comment by arpitnath** [comment]
Thanks, everyone for showing interest in contributing to ToolJet but we have to assign the issue to the first person who expressed interest. 

Assigning to @ShaunThayil 

You can check out other open issues here: https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest.
