### ISSUE TITLE
Layout accordion of widget inspector in Chart widget should be open by default

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4238]
### What is the expected behaviour?
Layout accordion of widget inspector in Chart Component should be open by default

### What is the current behaviour?
By default, it is closed.

### How to reproduce the issue?

1. Drop a Chart widget
2. Open the widget inspector
3. On the property tab, the Layout accordion is closed by default

ref: https://github.com/ToolJet/ToolJet/pull/4024/files#diff-56125a6db3222d10ff566ab146e36e1b56b08c5fd8dd8fb5cb8b5eb09afd1281

**Comment by PaarthAgarwal** [comment]
I'd like to work on it. Please assign it to me

**Comment by arpitnath** [comment]
Hi @PaarthAgarwal , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hey @PaarthAgarwal - Any update on it?

**Comment by Ponnada96** [comment]
Hi @arpitnath ,
I would like to work on this issue, Can you Please assign it to me.

**Comment by withshubh** [comment]
Hey @Ponnada96 - Thanks for showing interest in contributing to ToolJet. Assigned it to you.
