### ISSUE TITLE
Layout accordion of widget inspector in Table widget should be open by default

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4240]
### What is the expected behaviour?
Layout accordion of widget inspector in Table Component should be open by default

### What is the current behaviour?
By default, it is closed.

### How to reproduce the issue?

1. Drop a Table widget
2. Open the widget inspector
3. On the property tab, the Layout accordion is closed by default

ref: https://github.com/ToolJet/ToolJet/pull/4024/files#diff-56125a6db3222d10ff566ab146e36e1b56b08c5fd8dd8fb5cb8b5eb09afd1281

**Comment by PaarthAgarwal** [comment]
I'd like to work on it. Please assign it to me

**Comment by alammoiz** [comment]
Hi, Can you please assign to me @arpitnath ?

**Comment by exitflynn** [comment]
Hi @arpitnath I'd love to work on this issue!

**Comment by Borges53** [comment]
Hi @arpitnath , I would like to make my first collaboration with you. It would be nice to be able to help you solve the problem. Could you assign it to me?

**Comment by HVbajoria** [comment]
Hello @arpitnath,
Could you please assign me this issue? 
Thank you

**Comment by arpitnath** [comment]
Thanks, everyone, for showing interest in contributing to ToolJet but we have to assign the issue to the first person who expressed interest.

Since @PaarthAgarwal has already one issue assigned for which no PR has been raised yet, so assigning this issue to the second person who showed interest.

Assigning to @alammoiz 😅

You can check out other open issues here: https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest.
cc: @HVbajoria @Borges53 @exitflynn @alammoiz @PaarthAgarwal

**Comment by arpitnath** [comment]
@alammoiz 
This is the same file from the latest develop https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/Editor/Inspector/Components/DefaultComponent.jsx#L145

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by alammoiz** [comment]
https://github.com/ToolJet/ToolJet/pull/4372
@arpitnath , please review
