### ISSUE TITLE
Events accordion of widget inspector in Table widegt should be open by default

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4241]
### What is the expected behaviour?
Events accordion of widget inspector in Table Component should be open by default

### What is the current behaviour?
By default, it is closed.

### How to reproduce the issue?

1. Drop a Table widget
2. Open the widget inspector
3. On the property tab, the Events accordion is closed by default

ref: https://github.com/ToolJet/ToolJet/pull/4024/files#diff-56125a6db3222d10ff566ab146e36e1b56b08c5fd8dd8fb5cb8b5eb09afd1281

**Comment by PaarthAgarwal** [comment]
Hi. Assign this issue to me please

**Comment by Akash-Raj-ST** [comment]
@arpitnath I would like to work on this issue can you please assign it to me?

**Comment by Syed-Ansar** [comment]
Hii @arpitnath  would Like to work on this.

**Comment by harshit-dugar** [comment]
Hi @arpitnath I would like to work on it

**Comment by AnmolBansalDEV** [comment]
hey, I would like to work on this issue

**Comment by Gurpreet-Singh-Bhupal** [comment]
Hi @arpitnath  ,please assign me this issue I have worked on similar type of bug before.Thanks in advance.

**Comment by HVbajoria** [comment]
Hi @arpitnath ,
Could you please assign me this issue?

**Comment by arpitnath** [comment]
Thanks, everyone, for showing interest in contributing to ToolJet but we have to assign the issue to the first person who expressed interest. 

You can check out other open issues here: https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest.
cc: @HVbajoria @Gurpreet-Singh-Bhupal @AnmolBansalDEV @harshit-dugar @Syed-Ansar @Akash-Raj-ST @PaarthAgarwal
