### ISSUE TITLE
The default loader color value for the button widget should be set to `#fff`

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4244]
### Environment
Latest `develop`

### What is the expected behaviour?
The default loader color value for the button widget should be set to `#fff`

### What is the current behaviour?
The default value is not set for the loader color style definition.

### How to reproduce the issue?

1. Drop a Button widget into the editor
2. Open the widget inspector and navigate to the **styles** tab

### Any possible solutions?

**Source**: `frontend/src/Editor/WidgetManager/widgetConfig.js` ~ **Line 486**
**Solution**
```
      styles: {
        loaderColor: { value: '#fff' },
        ...
      },
```

**Comment by Rahul-Palahwat** [comment]
Hey @arpitnath i would love to work on this issue , can you assign this issue to me

**Comment by Aman0786-git** [comment]
Can you assign this issue to me

**Comment by arpitnath** [comment]
Hi @Aman0786-git ,
Thanks for showing interest in contributing to ToolJet but we have to assign the issue to the first person who expressed interest. 

You can check out other open issues here: https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest.

@Rahul-Palahwat Hello, assigning the issue to you.

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Rahul-Palahwat** [comment]
Thanks @arpitnath for assigning the issue , and i am on it

**Comment by ABHISHEK-PANDEY2** [comment]
from what i can experience , the button already has the default textColor as white(#fff), do you want the background color to change ?

**Comment by rushikeshadhav** [comment]
Hey, @Rahul-Palahwat are you still working on it?
If not I would like to take it up?

**Comment by shivani1706** [comment]
can you assign me this issue

**Comment by ismailbohra** [comment]
i can do this can you please assign me this issue

**Comment by tanishk-23** [comment]
@withshubh can you please assign this issue to me?

**Comment by withshubh** [comment]
Hey @Rahul-Palahwat 
Any update on this?
If you're not working on it then let us know, we will assign the issue to someone else.

**Comment by withshubh** [comment]
Unassigned @Rahul-Palahwat as there was no update for more than 20 days

**Comment by AyushK-101** [comment]
Can I work on this? I've raised a PR for my current assignment

**Comment by withshubh** [comment]
Assigned to you @AyushK-101

**Comment by AyushK-101** [comment]
![image](https://user-images.githubusercontent.com/86164395/197933745-fe96d8df-6576-4a93-b1f5-2973ed3b8bea.png)

@withshubh I guess the issue was resolved, it shows loader color #fff by default

**Comment by withshubh** [comment]
Thanks @AyushK-101 

Closing the issue as it seems to be fixed. (cc: @arpitnath - checked on cloud)
