### ISSUE TITLE
The default marker color value for the chart widget should be set

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4245]
### Environment
Latest `develop`

### What is the expected behaviour?
The default marker color value for the chart widget should be set to `#CDE1F8`

### What is the current behaviour?
The default value is not set for the loader color style definition.

### How to reproduce the issue?

1. Drop a Chart widget into the editor
2. Open the widget inspector and navigate to the **styles** tab

### Any possible solutions?

**Source**: `frontend/src/Editor/WidgetManager/widgetConfig.js` ~ **Line 633**
**Solution**
```
      styles: {
        markerColor: { value: '#CDE1F8' },
        ...
      },
```

**Comment by PaarthAgarwal** [comment]
Assign it to me please

**Comment by kushal-gopal** [comment]
Let me know if I can this up, thanks!

**Comment by arpitnath** [comment]
Hi @kushal-gopal , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by PaarthAgarwal** [comment]
> Hi @kushal-gopal ,
> 
> Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you.
> 
> If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

I commented earlier btw😅

**Comment by arpitnath** [comment]
@PaarthAgarwal You already have issue #4238  assigned to yourself. Please raise a PR for the same first and then pick new issues.
Thanks 😅

**Comment by PaarthAgarwal** [comment]
> @PaarthAgarwal You already have issue #4238 assigned to yourself. Please raise a PR for the same first and then pick new issues. Thanks 😅

I've opened two prs. Please assign further new issues to me. Thanks!
