### ISSUE TITLE
Onhover effect on the comapanies name and logo using ToolJet i

### ISSUE THREAD

**Issue by AbhishekTiwari23** [ToolJet/ToolJet#4250]
### Is your proposal related to a problem?

I want to add the HOVER effect on the company's name and logo, which are using the toolset. This will make the website more eye-catching
<img width="1242" alt="Screenshot 2022-10-03 at 2 07 52 PM" src="https://user-images.githubusercontent.com/97469132/193535080-5c75013b-9427-405c-8d02-a8e736cf125e.png">

If the hover effect is added, it will be more attractive and eye-catching.

### Describe the solution you'd like

I will use CSS effects to carry out the task and will give the best effects that will make it the best.

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
Yes, I will give my best and will make a PR for this if it is assigned to me.

**Comment by Navaneeth-pk** [comment]
Website is not part of this repository.
