### ISSUE TITLE
Socials Icons

### ISSUE THREAD

**Issue by AbhishekTiwari23** [ToolJet/ToolJet#4251]
### Is your proposal related to a problem?

I want to add social icons in the page's follow us section. This will become more eye-catching, and the hover effect will make it much more attractive.

### Describe the solution you'd like

I will use CSS or Material UI to complete this task. I will Add the hover effect by using CSS commands.

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
Yes, I would submit a PR for this if it will be assigned.

**Comment by zainbinfurqan** [comment]
@AbhishekTiwari23 Can i take this issue, if you can add hacktoberfest tag in it?

**Comment by AbhishekTiwari23** [comment]
@Syed-Ansar Please apologise me as I am a beginner, Will I have to make a new issue for this?

**Comment by zainbinfurqan** [comment]
> @Syed-Ansar Please apologise me as I am a beginner, Will I have to make a new issue for this?

I don't think so you can edit it.

**Comment by Syed-Ansar** [comment]
> @Syed-Ansar Please apologise me as I am a beginner, Will I have to make a new issue for this?

No, Now it is fine.

**Comment by Navaneeth-pk** [comment]
Website is not part of the repo.
