### ISSUE TITLE
[localization] Translate global strings in italian

### ISSUE THREAD

**Issue by TheZal** [ToolJet/ToolJet#4257]
### Is your proposal related to a problem?

Add translations for global strings in Italian.

### Describe the solution you'd like

The strings need to be translated:

```
"globals":{
        "readDocumentation":"Read Documentation",
        "cancel":"Cancel",
        "save":"Save",
        "back":"Back",
        "edit":"Edit",
        "search":"Search",
        "update":"Update",
        "delete":"Delete",
        "add":"Add",
        "view":"View",
        "create":"Create",
        "enabled":"Enabled",
        "disabled":"Disabled",
        "yes":"Yes",
        "submit":"Submit"
    },
```
Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)

Assign to me and I'll work on it!

**Comment by RegishShrestha** [comment]
can you assign me this issue?
