### ISSUE TITLE
[localization] Translate App Card in italian

### ISSUE THREAD

**Issue by TheZal** [ToolJet/ToolJet#4258]
### Is your proposal related to a problem?

Add translations for App Card strings in Italian.

### Describe the solution you'd like

The strings need to be translated:

```
"appCard":{
            "changeIcon":"Change Icon",
            "addToFolder":"Add to folder",
            "move":"Move",
            "to":"to",
            "selectFolder":"Select folder",
            "deleteApp":"Delete app",
            "exportApp":"Export app",
            "cloneApp":"Clone app",
            "launch":"Launch",
            "maintenance":"Maintenance",
            "noDeployedVersion":"App does not have a deployed version",
            "openInAppViewer":"Open in app viewer",
            "removeFromFolder":"Remove from folder"
        },
```
Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)

Assign to me and I'll work on it!

**Comment by Syed-Ansar** [comment]
I would like to work on this

**Comment by TheZal** [comment]
Once #4259 will be closed I will do the PR for this one

**Comment by Syed-Ansar** [comment]
> Hey @Syed-Ansar The issue will be assigned to @TheZal since he mentioned in the issue description that he is willing to work on it. You can look for other open issues.

Okay

**Comment by withshubh** [comment]
Closing this issue as the Italian is completely localized.
