### ISSUE TITLE
[docs]: Create Documentation for Tree Select Widget

### ISSUE THREAD

**Issue by sanjus-robotic-studio** [ToolJet/ToolJet#4260]
### Summary

Currently there is no documentation for the ```Tree Select``` Widget. 

### Issue Type

Documentation feature/update

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by sanjus-robotic-studio** [comment]
Can someone assign this to me?

**Comment by AbhishekTiwari23** [comment]
If the issue still exists, please assign it to me.

**Comment by withshubh** [comment]
Closing this issue as we already have the docs for tree select: https://docs.tooljet.com/docs/widgets/tree-select
