### ISSUE TITLE
[Feature request]: Ukrainian / Russian locales

### ISSUE THREAD

**Issue by daniloff200** [ToolJet/ToolJet#4261]
I do see localisation folder, but, it's kinda empty ;) 
Can Ukrainian and Russian localisations be useful?

I'm from Ukraine, and know both languages natively, so, can help with that.
If it's not useful, feel free to close this issue

- [x]  Russian
- [x]  Ukrainian

**Comment by withshubh** [comment]
Hey @daniloff200 👋 

Thanks for your interest in localizing ToolJet. 

Assigned the issue to you.
