### ISSUE TITLE
Unknown character being printed on the home page

### ISSUE THREAD

**Issue by VoidCupboard** [ToolJet/ToolJet#4264]
### Environment
ToolJet homepage 

### What is the expected behaviour?
There should not be a unexpected character

### What is the current behaviour?
There is a unwanted character in the home page 

### How to reproduce the issue?

1. Visit https://toolject.com
2. Scroll down to the Flexible and Extensible section
3.See a character in the description (after the heart icon)

### Screenshots or Screencast
![annotely_image](https://user-images.githubusercontent.com/82395440/193598440-6098a892-1499-4ac4-a475-50f06e4be6d5.png)

### Any possible solutions?
Remove the character

### If the bug is confirmed, would you be willing to submit a PR?
Yes

PS: Im gonna fix it

**Comment by mohithgupta** [comment]
Is this an issue that I can contribute to? If yes, Can you assign this to me cause I know why this happens and I guess I can fix it .

**Comment by Gurpreet-Singh-Bhupal** [comment]
@VoidCupboard  
Please assign me this issue,I know how to fix it

**Comment by VoidCupboard** [comment]
Uh, you see, Im gonba work on it

**Comment by arpitnath** [comment]
Hi, @VoidCupboard @Gurpreet-Singh-Bhupal and @mohithgupta  

Thanks for showing interest in contributing to ToolJet but the website is not part of the repo and hence cannot be considered as `hacktoberfest` contributions.

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).
