### ISSUE TITLE
Shows wrong number of Github stars on smaller screens

### ISSUE THREAD

**Issue by mohithgupta** [ToolJet/ToolJet#4267]
### Version Information
Latest
### What is the expected behaviour?

Correct GitHub star count should appear when looking at the website on smaller screens.

### What is the current behaviour?

The Github star count is Hardcoded (maybe) to 12000 on smaller screens.

### How to reproduce the issue?

If you're on PC:
1. Go to the home page
2. Reduce the screen size (if on PC) and the Github Star count changes to 12000

If you're on smaller screens, just open the HomePage and you'll see the Github Star count as 12000 

### Screenshots or Screencast

![Screenshot (437)](https://user-images.githubusercontent.com/50448748/193618774-85c3fea7-4c0c-448c-9faf-48520ffd0871.png)

### Please provide any traces or logs that could help here.

(Not sure) None as such.

### Any possible solutions?

I think using the return value that you receive from the GitHub API should be put there.

### Can you identify the location in the driver source code where the problem exists?

Not sure yet, need to check.

### If the bug is confirmed, would you be willing to submit a PR?

Yes, Sure!

**Comment by Croustys** [comment]
I can work on this issue if you assing it to me!

**Comment by mohithgupta** [comment]
> I can work on this issue if you assing it to me!

Hi @Croustys, I'm sorry but I'm planning to work on it. I'm just waiting for them to confirm it as a bug...

**Comment by arpitnath** [comment]
@stepinfwd Can you have a look into it?

**Comment by arpitnath** [comment]
@Croustys @mohithgupta Website contributions are not a part of `hacktoberfest`.

Thanks for showing interest in contributing to ToolJet and creating an issue.

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by mohithgupta** [comment]
Oh ok Thanks Arpit! I guess I can close the issue now?
