### ISSUE TITLE
Run query from js

### ISSUE THREAD

**Issue by DanyaBrain** [ToolJet/ToolJet#4273]
### Version 

Information 1.21

### Environment

ToolJet Cloud

### What is the expected behaviour?

I want to have ability to run any query from custom code on app load.

### What is the current behaviour?

ONLY IN EDIT MODE, when application just loaded, "queries" variable is empty. And all queries failing because they are undefined. But in production everything works fine/

### How to reproduce the issue?

1. Add javascript query and turn on "run on page load" toggle.
2. Run any query inside code like queries.SOMECUSTOMQUERYNAME.run()
3. Reload the page. You will see multiple warnings and your SOMECUSTOMQUERYNAME will not start

### Any possible solutions?

You can run query using "on success" part of the app. Everything will work as expected.

**Comment by withshubh** [comment]
Hey @DanyaBrain 

Thanks for creating this bug. The bug is valid and we will fix it soon.

**Comment by shubh22** [comment]
H @DanyaBrain,
This has been fixed in ToolJet 2.0.
