### ISSUE TITLE
js queries parameters

### ISSUE THREAD

**Issue by DanyaBrain** [ToolJet/ToolJet#4274]
### Is your proposal related to a problem?

If you will add this feature, everyone will be able to use queries like a js functions - devide code on smaller parts and reuse some parts multiple times

Right now I can do that, but this solution SO UGLY. I can use some global variable in some js query, and to change this variable before I start the query

### Describe the solution you'd like

I want to have ability to run any query with additional parameters, like in Retool. 
Rettol example:

somequery.trigger({additionalScope: {customprop1: 100}});

**Comment by sherfin94** [comment]
Hey @johnsoncherian , we are delivering this in 1.2 milestone, please change the branch accordingly.
