### ISSUE TITLE
Show unsaved progress confirmation

### ISSUE THREAD

**Issue by DanyaBrain** [ToolJet/ToolJet#4275]
### Is your proposal related to a problem?

Yes. Every time I using tooljet and writing some js code, I forget to click "SAVE AND RUN" button. So I missing my progress so often. And in this moment I want to kill someone.

### Describe the solution you'd like

Just to show confirmation if I have unsaved changes, like retool does.

**Comment by shubh22** [comment]
Hi @DanyaBrain, we are already working on fixing this on priority. Should be available in a week. Cheers.

**Comment by shubh22** [comment]
Hi @DanyaBrain ,

This has been fixed in ToolJet 2.0.
