### ISSUE TITLE
Changing parent component

### ISSUE THREAD

**Issue by DanyaBrain** [ToolJet/ToolJet#4277]
### Is your proposal related to a problem?

Sometimes I want to put some existing component inside another component. For example, I made some page with tables and some buttons. And after that I realized that I need to make tabs on this page. So I need to put all content inside tabs. 

### Describe the solution you'd like

I want to have ability to change parent object

### Describe alternatives you've considered

I can copy & paste some content that I need to move inside another container. But sometimes it's don't want to work

**Comment by withshubh** [comment]
Hey @DanyaBrain 
Thanks for creating the issue. We will discuss this internally and add to the roadmap.

**Comment by sriArca** [comment]
Faced the same problem today! would love this feature!
