### ISSUE TITLE
Toggle switch column type not editable by default

### ISSUE THREAD

**Issue by bobbintb** [ToolJet/ToolJet#4278]
### Is your proposal related to a problem?

I spent a good deal of time trying to figure out why the toggle switch column type wasn't working as expected. It was greyed out and it took me a while to realize the "editable" property is disabled by default.

### Describe the solution you'd like

I think it should be made editable by default. It doesn't really make sense for that column type to not be editable by default

### Describe alternatives you've considered

Live with it, I guess. 🤷 

### If the feature is approved, would you be willing to submit a PR?

Possibly. I don't imagine it would involve more than changing one variable.

**Comment by vedant-z** [comment]
Hi @bobbintb I would like to try this if you allow

**Comment by bobbintb** [comment]
> Hi @bobbintb I would like to try this if you allow

Oh, you mean as a PR? That's fine. It should be a quick fix but I'm a quite busy so go for it.

**Comment by vedant-z** [comment]
@bobbintb Thanks

**Comment by withshubh** [comment]
Hey @bobbintb Thanks for creating the isssue.
Closing this issue as it is not relevant as of now. We might add it in the roadmap in the future.
