### ISSUE TITLE
Rename Environment Variables to Workspace Variables 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4288]
### Is your proposal related to a problem?

Currently, we have named the workspace environment variables as Environment variables which can be confusing at times.

### Describe the solution you'd like

Rename the Environment Variables to Workspace Variables in the dropdown menu as well as from the page.

<img width="390" alt="Screenshot 2022-10-04 at 3 04 48 PM" src="https://user-images.githubusercontent.com/25361949/193787036-0ee83647-7fa9-460e-b7ec-5402945beb35.png">

<img width="1370" alt="Screenshot 2022-10-04 at 3 05 06 PM" src="https://user-images.githubusercontent.com/25361949/193787003-cd381594-3a41-4248-b21d-950b8517f503.png">

**Comment by Syed-Ansar** [comment]
I would like to work

**Comment by Syed-Ansar** [comment]
> Hey @withshubh I would like to work on this issue.

**Comment by Sarita-Singh** [comment]
Hello, @withshubh, I would like to resolve this issue. Can you please assign me this.

**Comment by withshubh** [comment]
> Hey @withshubh I would like to work on this issue. Please assign it to me

Hey @Syed-Ansar - You already have a few issues assigned. We will assign new issues once there's PR for them. Let me know if you need any help with them.

**Comment by withshubh** [comment]
> Hello, @withshubh, I would like to resolve this issue. Can you please assign me this.

Hi @Sarita-Singh 👋  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by adityapathakk** [comment]
I see that this issue is still open. If required, I can contribute!

**Comment by withshubh** [comment]
Hey @adityapathakk 👋 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).
