### ISSUE TITLE
[docs] Add links to slack and twitter

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#429]
Add the links to slack and Twitter on the header ( near Github link ) on the header of documentation pages.
Add the same links to the footer of the pages ( below the Github link ).

Slack: https://join.slack.com/t/tooljet/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg
Twitter: https://twitter.com/ToolJet

**Comment by arpitnath** [comment]
taking this up
