### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [ToolJet/ToolJet#4291]
I want to Add Pull Request Template to this repo.
Can I?

@withshubh

**Comment by devtayade** [comment]
@tooljet-bot  hey i really want to work on this issue. this can be my first step towards open source. can you please assign me this issue ?

**Comment by MrKrishnaAgarwal** [comment]
> @tooljet-bot  hey i really want to work on this issue. this can be my first step towards open source. can you please assign me this issue ?

I've created this issue and I'll only work on it
Sorry

**Comment by Navaneeth-pk** [comment]
One of our team members is working on this. Closing the issue.
