### ISSUE TITLE
[localization] translate strings (editor & header) section in Indonesian

### ISSUE THREAD

**Issue by depapp** [ToolJet/ToolJet#4293]
### Is your proposal related to a problem?

Add translations in Indonesian for `editor` and `header` section

![image](https://user-images.githubusercontent.com/6134774/193795502-9ccfd9bc-c445-4389-aa3b-c6691081caf0.png)

### Describe the solution you'd like

The strings needs to be translated:
```json
"editor": {
},
"header": {
}
```

hi @withshubh please assign to me & I'll work on it!

**Comment by withshubh** [comment]
Hey @depapp - Sure!
Assigned this issue to you.
