### ISSUE TITLE
Add multi-select filter on Status in Manage Users

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4295]
### Is your proposal related to a problem?

There's no way to filter the `active` and `archive` users on the `Manage Users` page. 

### Describe the solution you'd like

Add multi-select filter on Status. The default should be active and invited.

<img width="1425" alt="Screenshot 2022-10-04 at 4 17 57 PM" src="https://user-images.githubusercontent.com/25361949/193800851-7dedfa33-12c8-4164-a537-18774d486aaa.png">

**Comment by Syed-Ansar** [comment]
Hey @withshubh assign it to me

**Comment by Anuran12** [comment]
hi @withshubh I would like to work on this

**Comment by Syed-Ansar** [comment]
Hey @withshubh I have raised PR for my previous issues and one of them was unassigned because it was deleted from head repository and you can assign this issue to me as I have finished other issues. 👍

**Comment by SahilSingh177** [comment]
Please assign this to me.

**Comment by withshubh** [comment]
> Hey @withshubh I have raised PR for my previous issues and one of them was unassigned because it was deleted from head repository and you can assign this issue to me as I have finished other issues. 👍

Hey @Syed-Ansar 
Assigned this issue to you.

**Comment by withshubh** [comment]
Hi @AyushK-101 & @SahilSingh177 👋  

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by arpitnath** [comment]
Accidentally marked as **good first issue,** unassigning the issue as we require to close some UX decisions on it.

cc: @withshubh removing the `good-first-issue`

**Comment by AnasMansy** [comment]
can i work on this

**Comment by shubh22** [comment]
Duplicate issue of 4910. Closing this.
