### ISSUE TITLE
Change sort to lexicographic order on first name in Manage Users

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4296]
### Is your proposal related to a problem?

Currently, on the manage users page, the users are listed according to the way they were added/invited.

### Describe the solution you'd like

Sort the first name according to lexicographic order

<img width="1425" alt="Screenshot 2022-10-04 at 4 17 57 PM" src="https://user-images.githubusercontent.com/25361949/193801541-e99786f9-0beb-45f8-a891-2b726f8cf1ae.png">

**Comment by Syed-Ansar** [comment]
Hey @withshubh can you assign it to me, no issue has been assigned to me until now.

**Comment by yashdhanore** [comment]
Hey, can i give it a shot?

**Comment by amit-ksh** [comment]
I would like to work on this issues if @yashdhanore not able to fix.

**Comment by freakomonk** [comment]
Hi. @yashdhanore Are you currently working on this ? Please let us know if we can take this up

**Comment by yashdhanore** [comment]
@freakomonk I'm working on it. will let you know if i get stuck

**Comment by yashdhanore** [comment]
@freakomonk you can have it

**Comment by withshubh** [comment]
Hey @amit-ksh 👋 
Are you interested in working on this issue?

**Comment by amit-ksh** [comment]
Yup! I'm interested @withshubh

**Comment by withshubh** [comment]
> Yup! I'm interested @withshubh
> 
> One small doubt, we need to sort the users using the first name only right?

Yes!!

Assigned it to you.

**Comment by amit-ksh** [comment]
@withshubh I'm facing difficulties setting up Tooljet locally.  
Server was not able to make connections with DB. And my best guess is that I'm setting env variables right. Can you help me with that?

**Comment by withshubh** [comment]
> @withshubh I'm facing difficulties setting up Tooljet locally. Server was not able to make connections with DB. And my best guess is that I'm setting env variables right. Can you help me with that?

You can always join our slack community and ask for any help with ToolJet : https://tooljet.com/slack
