### ISSUE TITLE
Add border color property for outer border to the list view styles

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4298]
### Is your proposal related to a problem?

Currently, There's no option to set a border color to the outer border of the list view component.

### Describe the solution you'd like

Add an Outer border-color property to the list view component.

<img width="1037" alt="Screenshot 2022-10-04 at 4 42 28 PM" src="https://user-images.githubusercontent.com/25361949/193804641-81028867-df7b-4d9c-ba42-ecee13a63932.png">

**Comment by FroostyCodes** [comment]
Hi, Can you assign this to me please. I would like to work on it

**Comment by Ruchika30** [comment]
hi @withshubh  Kindly assign it to me too. Would like to look into it if not fixed yet

**Comment by withshubh** [comment]
> hi @withshubh Kindly assign it to me too. Would like to look into it if not fixed yet

Hey @Ruchika30 👋 

Thanks for your interest in contributing to ToolJet but the assignee has already created a PR for this issue.

You can look for other open issues and make sure it isn't assigned to someone.
