### ISSUE TITLE
[localization] Translate App Card in Romanian

### ISSUE THREAD

**Issue by donheshanthaka** [ToolJet/ToolJet#4301]
### Is your proposal related to a problem?

Add translations for the App Card in Romanian.

### Describe the solution you'd like

Translate the strings to romanian language according to the [localization guide](https://docs.tooljet.com/docs/contributing-guide/l10n)

![image](https://user-images.githubusercontent.com/61963664/194006694-f1292128-c2a3-4e8a-bdf7-cc4e5b19e4f9.png)

### If the feature is approved, would you be willing to submit a PR?

Yes i would be happy to contribute to this project, do assign me this issue

**Comment by donheshanthaka** [comment]
Do assign me this issue, i would be happy to work on it :)

**Comment by Navaneeth-pk** [comment]
@donheshanthaka are you a native Romanian speaker? 
Translations by non-native language speakers using tools like Google translate is causing us a lot of trouble.

**Comment by donheshanthaka** [comment]
> @donheshanthaka are you a native Romanian speaker? Translations by non-native language speakers using tools like Google translate is causing us a lot of trouble.

@Navaneeth-pk  no i would not be using google translator and even though i'm not born in Romania i do know people that are native which are my closets friends, so everything i contribute will be run through them as well to make sure it is up to standards, furthermore, you can just assign me this issue out of the 4 that i have opened for now and keep the others until i have completed this one to make sure that i provide quality work and afterwards you can assign me the rest.

Thank you. :)

**Comment by Navaneeth-pk** [comment]
Sorry, we do not have bandwidth to review everything. We will create issues for languages once we have enough feature requests from native speakers. It is very hard to maintain the translations as the project is iterating on a fast pace.

**Comment by donheshanthaka** [comment]
@Navaneeth-pk  

Btw i came across am issue regarding Spanish being assigned to a non native Spanish person in here 

https://github.com/ToolJet/ToolJet/issues/4184

by the Collaborator @withshubh 

what about that situation?
