### ISSUE TITLE
[localization] Translate Profile Settings in German

### ISSUE THREAD

**Issue by Ambareen09** [ToolJet/ToolJet#4313]
### Is your proposal related to a problem?

Add translations for Profilestrings in German.

### Describe the solution you'd like

The strings need to be translated:

"profileSettingPage":{
            "profileSettings":"Profile Settings",
            "firstName":"First name",
            "lastName":"Last name",
            "enterFirstName":"Enter First Name",
            "enterLastName":"Enter Last Name",
            "email":"Email",
            "avatar":"Avatar",
            "update":"Update",
            "profile":"Profile",
            "changePassword":"Change password",
            "currentPassword":"Current password",
            "newPassword":"New password",
            "confirmNewPassword":"Confirm new password",
            "enterCurrentPassword":"Enter current password",
            "enterNewPassword":"Enter new password"
        },
        "profile":"Profile",
        "logout":"Logout"
    },
Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)

Assign to me and I'll work on it for hacktoberfest!

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by appledora** [comment]
@Navaneeth-pk are you guys localizing for Bengali? I am a native speaker, so I will be happy to do it.

**Comment by Navaneeth-pk** [comment]
Thanks for your interest but we are not planning to at the moment. We prioritise translations as per the requests from community. Please feel free to ask these questions on Slack.
@appledora

**Comment by Ambareen09** [comment]
No, I am not a native german speaker but have proficiency in german.

**Comment by Navaneeth-pk** [comment]
@Ambareen09 closing this issue as I just found that the team is already working with someone on translating to German.
