### ISSUE TITLE
[localization] Translate Globals in Norwegian

### ISSUE THREAD

**Issue by Azanul** [ToolJet/ToolJet#4317]
### Is your proposal related to a problem?

Add translations for Global strings in Norwegian.

### Describe the solution you'd like

The strings need to be translated:

"globals":{
"readDocumentation":"Read documentation",
"cancel":"Cancel",
"save":"Save",
"back":"Back",
"edit":"Edit",
"search":"Search",
"update":"Update",
"delete":"Delete",
"add":"Add",
"view":"View",
"create":"Create",
"enabled":"Enabled",
"disabled":"Disabled",
"yes":"Yes",
"submit":"Submit",
"select":"Select",
"environmentVar":"Environment Variables",
"saving":"Saving...",
"saveDatasource":"Save data source",
"authorize":"Authorize",
"connect":"Connect",
"reconnect":"Reconnect",
"components":"components",
"send":"Send",
"noConnection":"could not connect",
"connectionVerifeid":"connection verified",
"left":"Left",
"center":"Center",
"right":"Right",
"justified":"Justified",
"host":"Host",
"operation":"Operation",
"header":"HEADER",
"path":"PATH",
"query":"QUERY",
"requestBody":"REQUEST BODY"
},
Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)

Assign to me and I'll work on it for hacktoberfest!

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by Navaneeth-pk** [comment]
@Azanul are you a native speaker or are you using online tools for translation?

**Comment by Azanul** [comment]
@Navaneeth-pk I learnt using Duolingo and whatever I'll miss Ill use some tool.

**Comment by Navaneeth-pk** [comment]
Sorry, we are not accepting new translation requests unless there are enough requests from native speakers.

**Comment by Azanul** [comment]
@Navaneeth-pk Norwegian has to be my native tongue for me to translate it?

**Comment by Navaneeth-pk** [comment]
We do not have requests from Norwegian speaking users for this translations. It is difficult for the team to maintain it over time. Since there is not enough requirements at the moment, we cannot accept this issue considering the bandwidth of our core team in reviewing PRs.
@Azanul

**Comment by Azanul** [comment]
> We do not have requests from Norwegian speaking users for this translations. It is difficult for the team to maintain it over time. Since there is not enough requirements at the moment, we cannot accept this issue considering the bandwidth of our core team in reviewing PRs. @Azanul

Understood
