### ISSUE TITLE
[localization] translate all strings in Indonesian

### ISSUE THREAD

**Issue by depapp** [ToolJet/ToolJet#4320]
### Is your proposal related to a problem?

Add translations in Indonesian for `homePage`, `confirmationPage`, `onBoarding`, `redirectSso`, `oAuth2`, `widgetManager` section

### Describe the solution you'd like

The strings needs to be translated:

![Screen Shot 2022-10-05 at 20 08 35](https://user-images.githubusercontent.com/6134774/194068386-5d5f753f-35aa-4733-aa59-d3713894740f.png)

anyone please assign this to me & I'll work on it!

**Comment by withshubh** [comment]
Hey @depapp 
Thanks for helping localize ToolJet. Let's finish the whole Indonesian in this Issue?

**Comment by depapp** [comment]
sure @withshubh , I'll update the issue title and working on it 🍻

**Comment by withshubh** [comment]
Hey @depapp - Any update on it?

**Comment by depapp** [comment]
hi @withshubh 
I've working on it, I'll raise the PR tomorrow 🙇
