### ISSUE TITLE
Modal widget: Children should be able to dragged to the bottom, making the modal's body scrollable 

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4322]
### What is the expected behaviour?
Widgets dropped to the Modal as its children, should be able to drag to the bottom with scroll active

### What is the current behaviour?
Dragging children down causes them to reposition and stick to the top.

### How to reproduce the issue?

1. Drop a Modal widget, and open the modal from the default trigger button
2. Add a widget (eg., button) to the modal
3. Drag it to the very bottom of the modal

**Comment by Syed-Ansar** [comment]
Hey @arpitnath I would like to work on this issue
