### ISSUE TITLE
create account issue

### ISSUE THREAD

**Issue by Ahmed-chouaya** [ToolJet/ToolJet#4325]
### Environment

ToolJet Cloud

### What is the expected behaviour?

to send and email for verification 
### What is the current behaviour?

when you put your email in the input and click on create account button the page stuck on please wait and no email recived
### How to reproduce the issue?

1.
2.
3.

### Screenshots or Screencast

![Screenshot from 2022-10-05 17-02-58](https://user-images.githubusercontent.com/64323786/194108745-4fc04d82-a3a6-4292-b6b8-55a6a2ffe185.png)

**Comment by stepinfwd** [comment]
Thanks for reporting 🎉  , it's fixed . Closing as website is not part of this repo.
@Ahmed-chouaya
