### ISSUE TITLE
Pricing Page has Messy Styling (Mobile)

### ISSUE THREAD

**Issue by Frenchtoast0** [ToolJet/ToolJet#4331]
### Environment
Tooljet Website (Mobile)

### What is the expected behaviour?
Styling should leave enough space to look aesthetically pleasing.

### What is the current behaviour?
Prices are not centered and enterprise section doesn't give enough room to all the points.

### How to reproduce the issue?

1. Go to https://www.tooljet.com/pricing
2. Examine styling on pricing cards

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/38544250/194187617-8a326ecb-27eb-4964-9ac3-9a12257d0036.png)
![image](https://user-images.githubusercontent.com/38544250/194187493-ef267f7e-8b99-4cc1-964f-b9ce577ab139.png)

### Please provide any traces or logs that could help here.
N/A

### Any possible solutions?
Fix the CSS.

### Can you identify the location in the driver source code where the problem exists?
Not sure where the pricing page is located at the moment.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by Navaneeth-pk** [comment]
Thanks for reporting. Closing as website is not part of this repo.
