### ISSUE TITLE
Fix linting errors across the app

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#434]
### Is your proposal related to a problem?
Even though linting rules are present, currently these aren't enforced using a pipeline to be strict about it.

### Describe the solution you'd like
Let's fix the lint errors and also add recommended/custom rules (like 80 line width) we'd want to have initially. After this is done, we can incorporate strict checking with a pipeline later on.

### Describe alternatives you've considered
None

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by gondar00** [comment]
I can see a eslintrc file present, a good alternative can be https://standardjs.com/
