### ISSUE TITLE
[localization] Translate App Card in Nepali Language

### ISSUE THREAD

**Issue by sidbelbase** [ToolJet/ToolJet#4343]
### Is your proposal related to a problem?

Add Nepali language support for App Card `Strings`

### Describe the solution you'd like

I would really love it if the following strings were translated into the Nepali language

```json

"appCard":{
            "changeIcon":"Change Icon",
            "addToFolder":"Add to folder",
            "move":"Move",
            "to":"to",
            "selectFolder":"Select folder",
            "deleteApp":"Delete app",
            "exportApp":"Export app",
            "cloneApp":"Clone app",
            "launch":"Launch",
            "maintenance":"Maintenance",
            "noDeployedVersion":"App does not have a deployed version",
            "openInAppViewer":"Open in app viewer",
            "removeFromFolder":"Remove from folder"
}

```

### Describe alternatives you've considered

I followed the guide provided in [this link (tooljet localization documentation)](https://docs.tooljet.com/docs/contributing-guide/l10n/)

### If the feature is approved, would you be willing to submit a PR?

Yes please, assign it to me as soon as this feature request is confirmed.

**Comment by shubh22** [comment]
Hi,
We do not have any plans to support the Nepali language as of now. So closing the issue.
