### ISSUE TITLE
[docs]: github flow link broken

### ISSUE THREAD

**Issue by washbin** [ToolJet/ToolJet#4344]
### Summary

I was reading the contributing guides for tooljet and while opening the associated links, The link to Github Flow was broken and I was redirected to the main docs page.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md

### Steps to reproduce the issue

1. Open ToolJet github repo
2. Head over to contributing.md
3. Click on the link to GithubFlow

### Additional Information

When the link is fixed, It becomes easier to know about GithubFlow as was orginially inteneded and users don't have to manually search GithubFlow on Github's docs.

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by withshubh** [comment]
Hey @washbin 
Thanks for raising the issue.
From next time please wait for the issue to be confirmed and assigned to you before creating a PR.

**Comment by washbin** [comment]
@withshubh doesnt it make sense to not include up-for-grabs label for issues that are already taken or have an open PR, I have surfed through various repositries hoping to come across issues open for working but sadly most come up already taken even with the up-for-grabs label.
Is the label meant for something else or am I misunderstanding something  ?

**Comment by washbin** [comment]
> Hey @washbin Thanks for raising the issue. From next time please wait for the issue to be confirmed and assigned to you before creating a PR.

Ohh, sure, was rushing a little, my bad.
