### ISSUE TITLE
Data is not immediately available after running "set variable" in runjs

### ISSUE THREAD

**Issue by bestpika** [ToolJet/ToolJet#4347]
### Environment

- ToolJet | v1.26.1 (docker)

### What is the expected behaviour?

Use `actions.setVariable` to set the global variable and then read `variables` to get the data.

### What is the current behaviour?

I got `undefined`.

### How to reproduce the issue?

1. Reload page.
1. Execute the following runjs code.
```javascript
actions.setVariable('t', 'yes');
alert(variables.t);
```

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/5698157/194504475-180d8146-ab67-4f41-b7eb-8e4f415c5088.png)

**Comment by sherfin94** [comment]
Hey @bestpika , this seems to be a valid bug that needs to be fixed. I'm tagging it as a bug and we'll get to it as soon as possible.

**Comment by ricardojlrufino** [comment]
I got a error running online 

Running this in preview mode
![image](https://user-images.githubusercontent.com/515675/198169772-1fb5db30-5798-45bc-95d1-609e688496a6.png)

i got this error
![image](https://user-images.githubusercontent.com/515675/198170163-d82a07c5-7a36-452a-8e59-6ab252271649.png)

this error not hapen if i click in preview button , see ..
![image](https://user-images.githubusercontent.com/515675/198170357-5e56080b-589d-4af3-aec4-b609b1d9207a.png)

**Comment by ricardojlrufino** [comment]
PS: Similar to this: https://github.com/ToolJet/ToolJet/issues/4444

**Comment by bestpika** [comment]
@ricardojlrufino The change in number #4445 (#4444) did not fix my problem.

**Comment by Bhautik0110** [comment]
I am getting same issue!

**Comment by kavinvenkatachalam** [comment]
Ref - #8242
