### ISSUE TITLE
"Unlimited" Character Title Possible

### ISSUE THREAD

**Issue by Frenchtoast0** [ToolJet/ToolJet#4354]
### Environment
ToolJet Cloud - Windows

### What is the expected behaviour?
I can create a title with an "unlimited" amount of characters.

### What is the current behaviour?
Currently, I can bypass the 25 character limit with simple developer tools and then make a title with an unlimited length.

### How to reproduce the issue?

1. Go to the create dashboard page
2. Open developer tools (F12 key)
3. Delete the max="25"
4. Voila! Unlimited characters allowed.  Breaks a bunch of stuff.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/38544250/194695423-4fb69bc0-a81f-48bf-a0a4-49bd6988ef96.png)

### Any possible solutions?
Add a backend validation.

### Can you identify the location in the driver source code where the problem exists?
Didn't look a lot, but likely in the server folder somewhere.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by tanishk-23** [comment]
@Frenchtoast0 Can you assign this to me?

**Comment by marazzax** [comment]
I can help you with this one, can you assign this to me.

**Comment by shubh22** [comment]
Hi @Frenchtoast0,
Assigned the issue to you.

**Comment by rushikeshadhav** [comment]
Is this open? @Frenchtoast0  are you working on it?

**Comment by Frenchtoast0** [comment]
I'm having some difficulties getting the local development environment running with docker-compose.  Any idea of the cause of this error? 
![image](https://user-images.githubusercontent.com/38544250/195269257-749333b5-a226-4a98-9724-77b196fb8ab6.png)
I tried to follow these instructions as close as possible. https://docs.tooljet.com/docs/setup/docker/

**Comment by Frenchtoast0** [comment]
Entrypoint script needed to be updated to: 


#!/bin/bash
set -e

if [ -d "./server/dist" ]
then
  SETUP_CMD='npm run db:setup:prod'
else
  SETUP_CMD='npm run db:setup'
fi

if [ -f "./.env" ]
then
  declare $(grep -v '^#' ./.env | xargs) 
fi

npm run db:setup

exec "$@"

**Comment by Frenchtoast0** [comment]
https://github.com/ToolJet/ToolJet/pull/4402
