### ISSUE TITLE
Negative Canvas Widths

### ISSUE THREAD

**Issue by Frenchtoast0** [ToolJet/ToolJet#4355]
### Environment
Tooljet Cloud - Windows

### What is the expected behaviour?
Negative canvas width's not allowed.

### What is the current behaviour?
App allows me to enter a negative canvas width.

### How to reproduce the issue?

1. Open settings
2. Set max canvas width to a negative number

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/38544250/194695786-c85b9a2f-7f93-4665-8b73-3a47de2657c0.png)

### Any possible solutions?
Make validation the same as max height.

### Can you identify the location in the driver source code where the problem exists?
Didn't look.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by tanishk-23** [comment]
@Frenchtoast0 Can you please assign this issue to me?

**Comment by anshu189** [comment]
@Frenchtoast0 I'd like to fix this issue as I did a similar one earlier, kindly assign it to me.

**Comment by Frenchtoast0** [comment]
I’m not a repository manager.  I just posted the issue for them to review.

**Comment by shubh22** [comment]
Hi @Frenchtoast0,
Have assigned the issue to you.
