### ISSUE TITLE
docker-compose contains unsupported option "platform"

### ISSUE THREAD

**Issue by gottfired** [ToolJet/ToolJet#4357]
### Version Information
develop branch, git hash: 6b655b7f17b7848f4948e2f6037ae932cd63bd1d

### Environment
ToolJet Cloud / Docker 

### What is the expected behaviour?
docker-compose build should work

### What is the current behaviour?
Running `docker-compose build` gives

```
~/development/ToolJet$ docker-compose build
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.client: 'platform'
Unsupported config option for services.plugins: 'platform'
Unsupported config option for services.server: 'platform'
```

platform is not supported with docker-compose version "3" (see e.g. https://github.com/docker/cli/issues/1050)

### How to reproduce the issue?

1. clone latest develop
2. run docker-compose build

Used versions
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.26.2, build eefe0d31

### Any possible solutions?
Commenting out the platform lines in the docker-compose file works, but not sure if that's the desired behaviour for your project.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by akshaysasidrn** [comment]
Hey @gottfired I'm using versions
```
❯ docker-compose -v
docker-compose version 1.29.2, build 5becea4c

❯ docker -v
Docker version 20.10.12, build e91ed57

```
And the docker-compose with version 3 works. Could you try updating your docker and docker-compose once?

**Comment by gottfired** [comment]
Thanks, yes it's working in docker-compose v2.10.2
