### ISSUE TITLE
Drag and drop of comment kills the UI

### ISSUE THREAD

**Issue by jibe-b** [ToolJet/ToolJet#4363]
### Environment
Tooljet cloud, using Firefox on Linux

### What is the expected behaviour?
Drag and drop of comment moves the pin.

### What is the current behaviour?
The full UI disappears

### How to reproduce the issue?

1. Create a comment 
2. Click on the comment to drag it
3. See the 

### Screenshots or Screencast

Here is the pin of a comment
![image](https://user-images.githubusercontent.com/6146483/194866068-2954f82c-f369-4d16-ab5b-1c88b924fec9.png)

and here is a portion of the screen after dragging the pin (the full screen is just blank with the background color)

![image](https://user-images.githubusercontent.com/6146483/194866276-5f88ad5d-19b1-4ee5-b14e-aba1ca2ebac7.png)

**Comment by withshubh** [comment]
Thanks, @jibe-b for creating the issue. We will work on fixing it soon.
