### ISSUE TITLE
[docs]: Making Changes to Contributing.md 

### ISSUE THREAD

**Issue by Drishti-jain21** [ToolJet/ToolJet#4367]
### Summary

We can add proper guide on how to contribute to this repository, including some helpful pictures. 
This can be useful for the first time contributors.

We can also add text according to the different issues that can be created along with making them into clickable link for easier user experience
<img width="784" alt="image" src="https://user-images.githubusercontent.com/100796147/194930850-c83ee2b1-741a-4890-8e8a-669595f23c6f.png">

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by TKirtan** [comment]
Can I work on this issue ?

**Comment by Drishti-jain21** [comment]
@TKirtan I am working on this issue

**Comment by withshubh** [comment]
Hey @Drishti-jain21 👋 

Thanks for showing interest in contributing to ToolJet but the current version of our Contributing Guide is really simple and straight forward, and we would like to keep it that way. :) 

Having said that I would like you to pick other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).
