### ISSUE TITLE
Needs check and fix in Sigin in the Mobile Website of Tooljet 

### ISSUE THREAD

**Issue by ShabanaNaik** [ToolJet/ToolJet#4369]
### Version Information
Mobile Phone: Samsung J8 

### Environment

    ToolJet Mobile  

### What is the expected behaviour?
  The Sig In and  Try Tooljet Cloud links should direct to respective webpages 

### What is the current behaviour?

  When I am trying to Sign in or use the Try Tooljet Cloud it is not redirecting me to any webpages rather the navbar just closes.
 I tried the same with other phones Vivi V25 Pro 5G and  OPPO A47 5G but the same issue is seen.

### How to reproduce the issue?

1. Open Tooljet.com from the Chrome Browser on a Mobile Phone 
2. Click open the Nav bar  and click on the Sign in link
3. Try the above for Try Tooljet Cloud link too

### Screenshots or Screencast
 ![Screenshot_20221011-100217_Chrome](https://user-images.githubusercontent.com/76608039/195001082-7e12bb07-bd72-4e4e-9828-b7045d58f985.jpg)
 

### Any possible solutions?
Check the HTML docs for the 
 

### Can you identify the location in the driver source code where the problem exists?
I am unable to find where the docs for the web pages.

### If the bug is confirmed, would you be willing to submit a PR?
I would like to do the required with your permission and guidance. As this is my first time for open source contribution please let me know if the issue posted is relevant or useful.
Let me also know  if I can add this as my hacktoberfest contribution.

**Comment by stepinfwd** [comment]
Hey , @ShabanaNaik  Thanks for reporting the issue its fixed 🎉   , ToolJet website and platform is managed separately so  closing this here.Please feel free to check on other open issues with `[hacktoberfest]` or `good-first-issue` tags.

**Comment by ShabanaNaik** [comment]
Thank you for your timely reply.
Please also check the signup page where the login button is hidden by the chatbox mobile phone 
![Screenshot_20221011-100716_Chrome](https://user-images.githubusercontent.com/76608039/195006166-cc06c81d-e420-4096-a32f-1b70eeb74d7a.jpg)
