### ISSUE TITLE
[localization] Translate Confirmation Page Strings Spanish 

### ISSUE THREAD

**Issue by Drishti-jain21** [ToolJet/ToolJet#4374]
### Is your proposal related to a problem?
Add translations for confirmation page strings in Spanish

### Describe the solution you'd like
The strings need to be translated.

![image](https://user-images.githubusercontent.com/100796147/195082367-2b337242-a9a6-40ea-9459-3276d0e93fe2.png)

### If the feature is approved, would you be willing to submit a PR?
yes

**Comment by Drishti-jain21** [comment]
@withshubh please assign me this issue

**Comment by rushikeshadhav** [comment]
Can you please assign me?

**Comment by Navaneeth-pk** [comment]
Closing as one of the contributors is already working Spanish translation.

**Comment by Drishti-jain21** [comment]
No one is working on this part. Everyone is working on translating different strings than this
I request you to check it once, please

**Comment by Drishti-jain21** [comment]
@Navaneeth-pk
