### ISSUE TITLE
Change the `delete` modal color in dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4380]
### Is your proposal related to a problem?

The delete modal color is `light` even in dark mode.

### Describe the solution you'd like

Change the modal color to match the dark mode.

<img width="405" alt="Screenshot 2022-10-09 at 7_24_21 AM" src="https://user-images.githubusercontent.com/25361949/195271038-f7176cfb-bd9c-422f-8ffe-42fd7057f0b0.png">

### Steps to reproduce the issue
- Go to Manage groups from the dashboard
- Toggle dark mode from the header
- Click on `delete` button next to any group

**Comment by Hrx4** [comment]
Hey so how exactly do we contribute? where can we see the current modal? i am new to this , it would be great if you could help me this

**Comment by D1ang** [comment]
Hi I would like to take this one up.

**Comment by Omm2005** [comment]
I also wanna contribute in this but I am confused how to! I am new to this

**Comment by PratyayDhond** [comment]
@withshubh 

![image](https://user-images.githubusercontent.com/80563848/195282918-2d74f92c-ae61-4c79-8771-f5d49e2f647a.png)

do you want the whole card's color to meet the dark mode? I can do this, and what we can do is, how about we make the text for permanantly delete as bold, so that people's attention goes there whenever deleting.

**Comment by PratyayDhond** [comment]
@withshubh Continuing the previous comment, 

For the card in dark mode, what I can do is make the  background a bit more blur/reduce opacity and focus on the card. The card will have the same color as of the background of dark mode, but when the card is opened, the background will have lowered opacity so that the card is in focus.

**Comment by Abhay5855** [comment]
Can I work on this issue, please?

**Comment by withshubh** [comment]
Hey @PratyayDhond 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
> @withshubh Continuing the previous comment,
> 
> For the card in dark mode, what I can do is make the background a bit more blur/reduce opacity and focus on the card. The card will have the same color as of the background of dark mode, but when the card is opened, the background will have lowered opacity so that the card is in focus.

Create a PR with your solution. We will review it and let you know if any change is required.

**Comment by withshubh** [comment]
> Can you please assign me this issue

Hi @shivani1706  

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by PratyayDhond** [comment]
@withshubh I needed a bit help, I tried to go through the code but it is very confusing and I am unable to find where the css part is located, can you help me with it? :)

**Comment by Ruchika30** [comment]
Check this file 
frontend/src/_components/ConfirmDialog.jsx
@PratyayDhond

**Comment by shivani1706** [comment]
Can you plz assign me this.

**Comment by withshubh** [comment]
Any update on it @PratyayDhond ?

**Comment by Abhay5855** [comment]
@withshubh Is it still pending can I take this task?

**Comment by withshubh** [comment]
Unassigned @PratyayDhond as there was no update on it.

**Comment by withshubh** [comment]
> @withshubh Is it still pending can I take this task?

Hi @Abhay5855 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hey @Abhay5855 - Any update on the PR? :)
