### ISSUE TITLE
[localization] Translate Confirmation Page strings to Hindi

### ISSUE THREAD

**Issue by Rutam21** [ToolJet/ToolJet#4381]
### Is your proposal related to a problem?

Add translations for Confirmation Page strings in Hindi.

### Describe the solution you'd like

Add translations for Confirmation Page strings in Hindi:

![Confirmation Page](https://user-images.githubusercontent.com/47860497/195289038-8b3810e4-bfb8-4ef8-97de-6208d1fcda60.jpg)

### If the feature is approved, would you be willing to submit a PR?
- [x] Yes, I am willing to submit the PR.

**Comment by Rutam21** [comment]
@withshubh Please review, and assign it to me if approved.

**Comment by withshubh** [comment]
Hi @Rutam21 👋  

Thanks for showing interest in contributing to ToolJet.
Closing this issue as the Hindi localization is currently not on our roadmap. We will create the issue if we plan to add it in the future.

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).
