### ISSUE TITLE
[Manage Groups] Highlight the selected apps in dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4382]
### Is your proposal related to a problem?

The selection is not clearly visible when the apps are selected for a group (in dark mode)

### Describe the solution you'd like

Change the color for the selected apps to be visible

### Steps to reproduce the issue
- Go to the `Manage Groups` from the dashboard
- Toggle dark mode
- Open a group
- Select apps to add to the group

https://user-images.githubusercontent.com/25361949/195290208-93a463f6-2fdd-4bc2-a085-99614b6959d0.mov

**Comment by alammoiz** [comment]
Could you please assign it to me?

**Comment by tanishk-23** [comment]
@withshubh Can you assign this to me?

**Comment by withshubh** [comment]
> I would love to work on this Please assign me

Hi @Shoray2002  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by tanishk-23** [comment]
@withshubh can i work on this issue?

**Comment by withshubh** [comment]
Hey @Shoray2002 
Is there any update on it?

**Comment by Shoray2002** [comment]
> Hey @Shoray2002 
> Is there any update on it?

Yes I am still working on this and will update by end of week.

**Comment by AyushK-101** [comment]
Hey @withshubh can I work on this, I have raised a PR for the current assignment

**Comment by withshubh** [comment]
Hey @AyushK-101 
Assigned the issue to you.

**Comment by AyushK-101** [comment]
@withshubh I've raised a PR regarding the issue, kindly review

**Comment by AyushK-101** [comment]
![image](https://user-images.githubusercontent.com/86164395/197863045-4e8f5f84-fb85-47c0-aed7-e83011d3f97d.png)

@withshubh I've made a new PR(#4608), the selected apps will appear in blue and the hover over non-selected apps will be light blue
