### ISSUE TITLE
[localization] Translate Widget and Widget Manager to Hindi

### ISSUE THREAD

**Issue by Rutam21** [ToolJet/ToolJet#4383]
### Is your proposal related to a problem?

Add translations for Widget and Widget Manager strings in Hindi.

### Describe the solution you'd like

Add translations for Widget and Widget Manager strings in Hindi:

![194688840-ee305f5a-6256-4119-bcd3-a39833ef9999](https://user-images.githubusercontent.com/47860497/195290146-ebdea929-97fc-4e26-86b0-b57da62d86c9.jpg)

### If the feature is approved, would you be willing to submit a PR?

- [x]  Yes, I am willing to submit the PR.

**Comment by Rutam21** [comment]
@withshubh Please review, and assign it to me if approved.

**Comment by withshubh** [comment]
Hi @Rutam21 👋  

Thanks for showing interest in contributing to ToolJet.
Closing this issue as the Hindi localization is currently not on our roadmap. We will create the issue if we plan to add it in future.

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).
