### ISSUE TITLE
[Manage Users] Change the invite link copied toast position to top

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4384]
### Is your proposal related to a problem?

When the invite link for the user is copied, the toast notification is displayed on the bottom right corner.

### Describe the solution you'd like

Change the location of the toast notification to the top.

### Steps to reproduce the issue
- Go to the `Manage Users` from the dashboard
- Invite a user
- On the `Status` field click on the copy button next to the `invited`

https://user-images.githubusercontent.com/25361949/195291479-ccf1e0e6-cad7-44a3-ab13-b5ae438a7d5e.mov

**Comment by gagandeepp** [comment]
interested please assign

**Comment by alammoiz** [comment]
Could you please assign it to me?

**Comment by RachitGarg-12** [comment]
Hey @withshubh   please assign me this issue.

**Comment by Abhay5855** [comment]
can you assign me this issue?

**Comment by withshubh** [comment]
> interested please assign

Hey @gagandeepp 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hi all, 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

cc: @AbhishekRP2002 @alammoiz @RachitGarg-12 @Abhay5855

**Comment by daniloff200** [comment]
hi, @withshubh 
I saw it was assigned before, but, right now there's no assignment for this one.
Can I pick this?

**Comment by withshubh** [comment]
> hi, @withshubh I saw it was assigned before, but, right now there's no assignment for this one. Can I pick this?

Hey @daniloff200 👋 
There is one issue assigned to you, we will assign more issues once the PR for the currently assigned one is up. 😇

**Comment by gagandeepp** [comment]
@withshubh  please review my PR for the same and assign issue to me.

**Comment by withshubh** [comment]
> @withshubh please review my PR for the same and assign issue to me.

The issue is assigned to you and the PR will be reviewed soon 🙌
