### ISSUE TITLE
The workspace switching arrow appears only when hovered over in dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4385]
### Is your proposal related to a problem?

The option to switch the workspace has an arrow that is not visible in the dark mode until the cursor hovers over the workspace name.

### Describe the solution you'd like

Make the cursor and workspace image visible in dark mode.

### Steps to reproduce the issue
- Toggle dark mode 
- Go to the dropdown on the navbar 
- Hover over the workspace name

![Screenshot 2022-10-12 at 2 02 03 PM](https://user-images.githubusercontent.com/25361949/195293596-88395fa3-0314-4b73-b45c-aca15f00ed56.png)
![Screenshot 2022-10-12 at 2 01 46 PM](https://user-images.githubusercontent.com/25361949/195293602-faef02a4-1c58-4811-8f2c-d4da8201fd8d.png)

**Comment by KushalRaut** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by alammoiz** [comment]
Could you please assign it to me?

**Comment by tanishk-23** [comment]
@withshubh can you assign this issue to me?

**Comment by Abhay5855** [comment]
Can you assign me this issue?

**Comment by withshubh** [comment]
Hey @Abhay5855 👋 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).
