### ISSUE TITLE
Shows 2 toast notifications when the widget name is empty

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4386]
### Is your proposal related to a problem?

When a value of a widget name is set to empty, it throws two toast errors.

### Describe the solution you'd like

Show only one toast notification for this error.

### Steps to reproduce the issue
- On the app builder, drag a widget and set its name to an empty value
- Click anywhere on the canvas

[screen-capture (7).webm](https://user-images.githubusercontent.com/25361949/195294937-3df7dde9-cc88-45a5-8a7f-ae0fce1580fd.webm)

**Comment by TheLearneer** [comment]
Hi @withshubh 👋 

I would like to give it a shot 🙇

**Comment by alammoiz** [comment]
Could you please assign it to me?

**Comment by tanishk-23** [comment]
@withshubh can you assign this issue to me?

**Comment by withshubh** [comment]
> Hi @withshubh 👋
> 
> I would like to give it a shot 🙇

Hi @TheLearneer 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you.

**Comment by withshubh** [comment]
Hey @alammoiz & @tanishk-23 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by TheLearneer** [comment]
Hi @withshubh 

I was debugging this issue and realized that the `onBlur` event is firing multiple times itself, causing the toast notification to tigger multiple times itself.

Would love to hear the thoughts from you guys about what would the best way to handle the issue.

**Comment by tanishk-23** [comment]
@withshubh can I work on this issue?

**Comment by TheLearneer** [comment]
Hi @tanishk-23 if you feel you can debug and solve the issue then sure, please pick it up if the maintainers assign it to you.

**Comment by tanishk-23** [comment]
@withshubh I am ready to work on it please assign it to you

**Comment by withshubh** [comment]
Hey @TheLearneer - Are you sure you don't want to work on this issue?

**Comment by TheLearneer** [comment]
Well @withshubh I mean whoever works on it will have to go on a discussion with you guys.
Because it definitely is not an easy to fix from what I debugged.

If @tanishk-23 wanna give it a shot, then sure, I am find with it 🙇

**Comment by withshubh** [comment]
Cool! @TheLearneer 
Assigned the issue to @tanishk-23

**Comment by TheLearneer** [comment]
BTW @withshubh just to add on it.
The toast doesn't appear just twice but even more times.

For e.g. set the name to empty string, click somewhere on the editor in the right, click on the section where components can be added.
You will be able to see that the toast will even appear multiple times
