### ISSUE TITLE
Redirect to Tutorials Page Error

### ISSUE THREAD

**Issue by Smartmind12** [ToolJet/ToolJet#4387]
### What is the expected behaviour?

The Expected behaviour would be to redirect page to tutorials page on tooljet.

### What is the current behaviour?

Currently the "Tutorials" section in the footer of Tooljet Docs takes you to a "Page Not Found".

### How to reproduce the issue?

1. Go to (https://docs.tooljet.com/docs/)
2. Scroll down to the page footer
3. Click "Tutorials" and find the error

### Screenshots or Screencast

<img width="956" alt="tooljet issue" src="https://user-images.githubusercontent.com/91927689/195312993-ac976743-091f-447d-9107-91d764c8839f.png">

### Any possible solutions?
To edit the redirect link to the proper path for proper implementation of the feature.

### Can you identify the location in the driver source code where the problem exists?
Yes i have identified the location where the issue exist in the source code.

### If the bug is confirmed, would you be willing to submit a PR?
Yes I am willing to submit a PR (Hacktoberfest)

**Comment by Smartmind12** [comment]
> Can you assign it to me?

Hey! I have raised this issue as i would be working on it...so I request you to find another issue to work on ...Thanks!!

**Comment by ghousahmed** [comment]
Okay

**Comment by withshubh** [comment]
Hi @Smartmind12  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

Also, you'll need to put this URL for Tutorial: https://docs.tooljet.com/docs/category/tutorial

**Comment by withshubh** [comment]
> Fix Redirect error #4395

Hey @Smartmind12 👋 

Thank you for contributing to ToolJet.
Unfortunately, we won't be able to add Hacktoberfest labels as we are not encouraging typos or minor URL fixes as meaningful contributions.

**Comment by withshubh** [comment]
Hey @Smartmind12 👋 

Thank you for contributing. 😇 
Only the issues with the [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest) label are valid for `hacktoberfest-accepted` label in their PRs.
