### ISSUE TITLE
[cypress] Fix failing manage SSO spec in single workspace

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4390]
### Specify the kind of test

Due to some recent updates, the manageSSO spec in single workspace is failing.

### Describe the test

Fix the cypress test to avoid failure.

Link to file: https://github.com/ToolJet/ToolJet/blob/develop/cypress-tests/cypress/e2e/dashboard/single-workspace/manageSSO.cy.js

**Comment by tanishk-23** [comment]
@withshubh can you assign this issue to me?

**Comment by alammoiz** [comment]
Please assign this to me.

**Comment by withshubh** [comment]
> @withshubh can you assign this issue to me?

Hey @tanishk-23 

You already have an issue assigned. We can only assign another issue once a PR is created for the assigned one.
- https://github.com/ToolJet/ToolJet/issues/4391

**Comment by withshubh** [comment]
> @withshubh Please assign this to me.

Hey @alammoiz 👋 

Assigned this to you.

**Comment by alammoiz** [comment]
Please review https://github.com/ToolJet/ToolJet/pull/4509
