### ISSUE TITLE
[cypress] Fix failing manage SSO spec in multi workspace

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4391]
### Specify the kind of test

Due to some recent updates, the manageSSO spec in multi-workspace is failing.

### Describe the test

Fix the cypress test to avoid failure.

Link to file: https://github.com/ToolJet/ToolJet/blob/develop/cypress-tests/cypress/e2e/dashboard/multi-workspace/manageSSO.cy.js

**Comment by tanishk-23** [comment]
@withshubh  can you assign this issue to me?

**Comment by akarsh-jain-790** [comment]
@withshubh can you assign this to me?

**Comment by alammoiz** [comment]
Please assign this to me.

**Comment by withshubh** [comment]
> @withshubh can you assign this issue to me?

Hi @tanishk-23 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by alammoiz** [comment]
@withshubh How can I run specific test file?

**Comment by alammoiz** [comment]
Thanks @emidhun , I'm getting this error, Do you have any idea?
<img width="1020" alt="Screenshot 2022-10-18 at 3 20 54 PM" src="https://user-images.githubusercontent.com/24625561/196404363-f17e3b2b-5a92-4717-94be-9b10168305b0.png">

**Comment by emidhun** [comment]
@alammoiz I hope you `did npm install` on `cypress-tests` directory.

**Comment by alammoiz** [comment]
It worked @emidhun Thanks

**Comment by alammoiz** [comment]
@emidhun please assign this to me, want to fix that as well

**Comment by withshubh** [comment]
Hey @alammoiz - Assigned this issue to you.

**Comment by alammoiz** [comment]
Please review this PR https://github.com/ToolJet/ToolJet/pull/4658
