### ISSUE TITLE
[cypress] Fix failing manage groups spec 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4392]
### Specify the kind of test

Due to some recent updates, the manageGroups spec is failing.

### Describe the test

Fix the cypress test to avoid failure.

Link to file: https://github.com/ToolJet/ToolJet/blob/develop/cypress-tests/cypress/e2e/dashboard/manageGroups.cy.js

**Comment by akarsh-jain-790** [comment]
@withshubh can u assign this issue to me?

**Comment by FroostyCodes** [comment]
Can I work on it?

**Comment by withshubh** [comment]
> @withshubh can u assign this issue to me?

Hi @akarsh-jain-790  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hi @FroostyCodes  

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by chaiwattsw** [comment]
since @akarsh-jain-790 remove their assignment please assign this issue to me @withshubh

**Comment by gagandeepp** [comment]
@withshubh no one is assigned to this please assign

**Comment by withshubh** [comment]
> @withshubh no one is assigned to this please assign

Hey @gagandeepp - There is another issue assigned to you.
