### ISSUE TITLE
[localization] translate all strings in Nepali

### ISSUE THREAD

**Issue by thenishantsapkota** [ToolJet/ToolJet#4396]
### Is your proposal related to a problem?
Add translations in Nepali for `homePage`, `confirmationPage`, `onBoarding`, `redirectSso`, `oAuth2`, `widgetManager` section

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

**Comment by shubh22** [comment]
Hi @thenishantsapkota,
Thanks for showing interest, but we do not intend to support Nepali Language for now.
