### ISSUE TITLE
[docs]: Add more Keyboard Shortcuts 

### ISSUE THREAD

**Issue by Smartmind12** [ToolJet/ToolJet#4399]
### Summary

Currently there are only a limited number of shortcuts added in the [Keyboard Shortcuts Page](https://docs.tooljet.com/docs/tutorial/keyboard-shortcuts). 
Some existing shortcuts are operational but they are yet to be added in the documents as they help users work in a faster manner.

### Issue Type

Documentation feature/update

### Additional Information

Kindly assign this issue to me so that i can start working on the issue and add these shortcuts...Thanks!

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by BhaskarKarnatak** [comment]
Please assign this to me @Smartmind12. I will work on this

**Comment by Smartmind12** [comment]
@withshubh @shubh22 Please approve this issue so that i can start working on it! Thanks!

**Comment by Smartmind12** [comment]
> Please assign this to me @Smartmind12. I will work on this

Hey @BhaskarKarnatak thanks for volunteering however I would be working on this issue so requesting you to work on another issue in the meantime...thanks!

**Comment by withshubh** [comment]
Hey @Smartmind12 
Can you mention what is missing in the documentation and what are you proposing to add?

**Comment by Smartmind12** [comment]
> Hey @Smartmind12 Can you mention what is missing in the documentation and what are you proposing to add?

Shortcuts like:

**Comment by withshubh** [comment]
> > Hey @Smartmind12 Can you mention what is missing in the documentation and what are you proposing to add?
> 
> Shortcuts like:
> 
> 1. Cut
> 2. Drag of multiple widgets
> 3. Finding objects/text
> 4. Select all text at once
> 5. Save the app locally
> 6. scrolling page shortcut
> 7. switching between user profile and tooljet apps

Sorry @Smartmind12 but the changes that you're suggesting are not relevant.
Closing the issue.
