### ISSUE TITLE
Fix spacing on login page

### ISSUE THREAD

**Issue by Frenchtoast0** [ToolJet/ToolJet#4412]
### Environment
Tooljet Cloud

### What is the expected behaviour?
Spacing should exist between "Don't have an account..." and "Sign up".

### What is the current behaviour?
Two phrases are stuck together.

### How to reproduce the issue?

1. Go to the login screen
2. Also check the signup screen as the issue exists there as well.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/38544250/195693623-a0d4a15e-9081-4653-b8b2-3060628a0b78.png)

### Please provide any traces or logs that could help here.
N/A

### Any possible solutions?
Fix the CSS to add spacing.

### Can you identify the location in the driver source code where the problem exists?
Haven't checked.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by amit-ksh** [comment]
Same issue also exists on "Sign Up" page.

![Signup Page](https://user-images.githubusercontent.com/91947037/195745116-c79ba025-ac91-4684-bf68-56bedb5b9efb.png)

**Comment by shubh22** [comment]
hi @Frenchtoast0 ,
This page is under revamp and the issue will no longer exist. So closing this for now.
