### ISSUE TITLE
Unlimited version name length allowed

### ISSUE THREAD

**Issue by Frenchtoast0** [ToolJet/ToolJet#4413]
### Environment
Tooljet Cloud

### What is the expected behaviour?
Version name length should be restricted

### What is the current behaviour?
Version name length is unlimited.

### How to reproduce the issue?

1. Click "Create Version"
2. Set version to a super long string
3. After creating, app will look very messed up

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/38544250/195694745-ac7d1367-064b-43fb-a953-3a037ffcdc28.png)

### Any possible solutions?
Add length restriction.

### Can you identify the location in the driver source code where the problem exists?
Haven't checked.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by shubh22** [comment]
Hi @Frenchtoast0 ,

It seems like a valid issue, please feel free to create a PR with a length restricted to 25 and the minimum length to be 1.

**Comment by Surajrane45** [comment]
@shubh22 If no one is working, can you assign this to me. I would like to fix this

**Comment by surajrane42** [comment]
@shubh22 If no one is working, can you assign this to me. I would like to fix this
