### ISSUE TITLE
Can't add widgets to dashboard

### ISSUE THREAD

**Issue by Frenchtoast0** [ToolJet/ToolJet#4415]
### Environment
ToolJet Cloud

### What is the expected behaviour?
I can add widgets to the dashboard.

### What is the current behaviour?
Can't drag widgets onto the dashboard.

### How to reproduce the issue?

1. Create a version
2. Create a version based off this version
3. Can't add widgets anymore

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/38544250/195695174-be181568-b300-453f-b9ed-0cd5adc63729.png)

### Any possible solutions?
No

### Can you identify the location in the driver source code where the problem exists?
Haven't checked.

**Comment by tanishk-23** [comment]
Please assign this issue to me?

**Comment by TalhaQuddoos** [comment]
I would like to work on this, please assign it to me.

**Comment by shubh22** [comment]
Hi @Frenchtoast0 ,
we are not able to reproduce this. can you please be more descriptive?

**Comment by Frenchtoast0** [comment]
Unable to reproduce anymore either.  Must be super rare.
