### ISSUE TITLE
Unlimited Folder Name Possible

### ISSUE THREAD

**Issue by Frenchtoast0** [ToolJet/ToolJet#4420]
### Environment
ToolJet Cloud

### What is the expected behaviour?
Folder name creation gives error when attempt to make a folder with over 25 chars.

### What is the current behaviour?
No backend validation, can create long folder names.

### How to reproduce the issue?

1. Click "Create Folder"
2. Open inspect tools (F12)
3. Delete the max characters = 25
4. Unlimited characters possible due to no backend validation.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/38544250/195772070-b36fd08e-7f7a-4aee-ab24-99ee5899d7b2.png)

### Any possible solutions?
Add backend validation.

### Can you identify the location in the driver source code where the problem exists?
Haven't looked.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by shubh22** [comment]
Hi @Frenchtoast0 ,
Assigning this to you.

**Comment by CalArcher** [comment]
Has this been fixed? If not I can get it done ASAP

**Comment by shubh22** [comment]
Hi @Frenchtoast0,
Gentle reminder for this :)

**Comment by Frenchtoast0** [comment]
Hi, @shubh22.  I'm aware of it.  I was hoping that my other MR's would get merged in before I began on this so I could update my local branch to match tooljet fresh again.  If not, I might need to figure out another way to get a fresh branch.

**Comment by Frenchtoast0** [comment]
https://github.com/ToolJet/ToolJet/pull/4612
