### ISSUE TITLE
[docs]: Spelling error

### ISSUE THREAD

**Issue by Frenchtoast0** [ToolJet/ToolJet#4422]
### Summary

Spelling error that makes the instructions strange.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/setup/docker

### Steps to reproduce the issue

1. Open docs
2. Go to "Making changes to the codebase"
3. Text says "would" when it should say "will".
![image](https://user-images.githubusercontent.com/38544250/195774651-88c3ca92-b244-4dcf-8bec-dc4373344814.png)

### Additional Information
Looks like there are a couple places below where the wording is weird as well.

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by BhaskarKarnatak** [comment]
I would like to work on this issue. can you assign me this issue @Frenchtoast0

**Comment by withshubh** [comment]
Hey @Ishika414 & @BhaskarKarnatak 

Thanks for showing interest in contributing to ToolJet.

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by withshubh** [comment]
Closing this issue as fixed. It will be up on the next release.
