### ISSUE TITLE
Plotly layout barchart stacked doesn't work

### ISSUE THREAD

**Issue by pbjorklund** [ToolJet/ToolJet#4437]
### Environment
Docker

### What is the expected behaviour?
Setting "layout": { "barmode": "stack" } should display stacked bars.

### What is the current behaviour?
Nothing happens.

### How to reproduce the issue?

Create data with 2 bar objects like https://plotly.com/javascript/bar-charts/

Add barmode
{
"data": {{queries.mssql7.data}},
"layout": { "barmode": "stack" }
}

See that it's still using grouped.

### Any possible solutions?
Not sure if the layout prop is actually passed down.

### Can you identify the location in the driver source code where the problem exists?
https://github.com/ToolJet/ToolJet/blob/2bf4707624940f33867fe053bc26d058b1f58d85/frontend/src/Editor/Components/Chart.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Not sure

**Comment by tanishk-23** [comment]
Can you assign this issue to me?
