### ISSUE TITLE
Add a modal with warning message on disabling password

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4448]
### Is your proposal related to a problem?

In the Password login section in Manage SSO, user can simply disable the password login without any getting any information.

### Describe the solution you'd like

Add a modal when a user toggles off the password login.

**Message**: Users won’t be able to login via username and password if password login is disabled. Please make sure that you have setup other authentication methods before disabling password login.

![Screenshot 2022-10-16 at 12 19 43 PM](https://user-images.githubusercontent.com/25361949/196022750-a4330e53-c0af-4e76-9872-1fb6185f6c4c.png)

**Comment by akarsh-jain-790** [comment]
@withshubh  can you assign this issue to me?

**Comment by amit-ksh** [comment]
Can i work on this issue?

**Comment by gagandeepp** [comment]
@withshubh interested please assign

**Comment by akarsh-jain-790** [comment]
I’m working on it

**Comment by gagandeepp** [comment]
It's not assigned to anyone as of now.
So anyone can ask for it to be assigned.

**Comment by akarsh-jain-790** [comment]
Yeah I already asked above

**Comment by SurojN** [comment]
Can i work on this issue???

**Comment by withshubh** [comment]
Hey @akarsh-jain-790 
Assigned this issue to you.
