### ISSUE TITLE
Version names should not start with space 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4450]
### Is your proposal related to a problem?

Currently, the version names are can include a leading space, so it could make similar versions since the version dropdown doesn't show any space.

### Describe the solution you'd like

add a check for leading or trailing space in version names

![Screenshot 2022-10-14 at 10 44 29 AM](https://user-images.githubusercontent.com/25361949/196023649-ee11bb61-7583-483d-9c21-bab6746e8c80.png)

**Comment by akarsh-jain-790** [comment]
@withshubh can you assign this issue to me?

**Comment by tanishk-23** [comment]
@withshubh can you assign this to me?

**Comment by withshubh** [comment]
Hey @akarsh-jain-790 & @tanishk-23 
Thanks for your interest in contributing to ToolJet.
There is an issue already assigned to both of you. 🙌

**Comment by daniel-shuy** [comment]
@withshubh I'd like to take a stab at this

**Comment by daniel-shuy** [comment]
@withshubh would it be better to simply trim the input?

**Comment by withshubh** [comment]
> @withshubh I'd like to take a stab at this

Hi @daniel-shuy 👋  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)
