### ISSUE TITLE
fix the error message: Apps removed from the group

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4451]
### Is your proposal related to a problem?

When an app is deleted from the group it shows the error message `Apps removed from the group`

### Describe the solution you'd like

Fix the error message `App removed from the group`

### Steps to reproduce
- Go to Manage Groups
- Create a new group and add a few apps
- Delete an app and check the error toast

![Screenshot 2022-10-16 at 1 00 47 PM](https://user-images.githubusercontent.com/25361949/196023787-4030b7a2-261f-42e9-b8bf-43ebcb660f4b.png)

**Comment by surajrane42** [comment]
@withshubh I would like to work on this issue. Can you assign it to me

**Comment by leimath** [comment]
Can this be assigned to me? Incase, Surajrane42 is assigned https://github.com/ToolJet/ToolJet/issues/4449

**Comment by withshubh** [comment]
> Can this be assigned to me? Incase, Surajrane42 is assigned #4449

Hey @leimath 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)
