### ISSUE TITLE
fix the error message: Users removed from the group

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4452]
### Is your proposal related to a problem?

When a user is deleted from the group it shows the error message `Users removed from the group`

### Describe the solution you'd like

Fix the error message `User removed from the group`

### Steps to reproduce
- Go to Manage Groups
- Create a new group and add a few users
- Delete a user and check the error toast

![Screenshot 2022-10-16 at 1 07 09 PM](https://user-images.githubusercontent.com/25361949/196024002-5c5835ad-8857-4154-b724-ff6d14eb6ca4.png)

**Comment by akarsh-jain-790** [comment]
@withshubh can you assign this issue to me?

**Comment by FroostyCodes** [comment]
Hi @withshubh can I please work on this?

**Comment by tanishk-23** [comment]
@withshubh can you assign this to me?

**Comment by ashishkashyap31** [comment]
Hi @withshubh , I would love to work on this issue.

**Comment by withshubh** [comment]
> Hi @withshubh , I would love to work on this issue. Can you please assign it to me?

Hi @ashishkashyap31 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)
