### ISSUE TITLE
Fix the error message when editing the workspace with same name

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4453]
### Is your proposal related to a problem?

When editing a workspace name, if a workspace already exists then you get the error message " XYZ workplace already exists."

### Describe the solution you'd like

Make the error message clear like "The workspace *XYZ* already exists. "

### Steps to reproduce
- Go to the dropdown on the header
- Edit the workspace
- Click on the Save button without changing the name

![Screenshot 2022-10-16 at 1 20 13 PM](https://user-images.githubusercontent.com/25361949/196024453-b10a659f-970d-472e-9133-bf65d3053241.png)

**Comment by akk312000** [comment]
Can I work on this? @withshubh

**Comment by tanishk-23** [comment]
@withshubh please assign this issue to me

**Comment by Ananyamadhu08** [comment]
Hey @withshubh I would like to work on this issue.

**Comment by withshubh** [comment]
> Hey @withshubh I would like to work on this issue.

Hey @Ananyamadhu08 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by tanishk-23** [comment]
@withshubh can I work on this issue?

**Comment by developer-diganta** [comment]
@withshubh  Is this issue still open? If so, then can I work on it?

**Comment by withshubh** [comment]
Hey @developer-diganta 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)
