### ISSUE TITLE
Make environment variable's delete modal's color in dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4454]
### Is your proposal related to a problem?

The delete modal color is `light` even in dark mode.

### Describe the solution you'd like

Change the modal color to match the dark mode.

![Screenshot 2022-10-16 at 1 25 46 PM](https://user-images.githubusercontent.com/25361949/196024798-ee1e31e0-e56e-435c-82e8-deca82b1393d.png)

### Steps to reproduce the issue
- Go to Manage Environment Variable from the dropdown in header
- Toggle dark mode
- Add an env variable
- Click on the `delete` button next to the env var

**Comment by akarsh-jain-790** [comment]
@withshubh can you assign this issue to me?

**Comment by withshubh** [comment]
> @withshubh can you assign this issue to me?

Hey @akarsh-jain-790 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)
