### ISSUE TITLE
Error toast should be at center in profile settings

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4455]
### Is your proposal related to a problem?

All the error messages in the Profile setting currently appear on the top-left.

### Describe the solution you'd like

Change the position of the error message in profile settings to the center.

### Steps to reproduce the issue
- Go to Profile setting
- Create an error either by saving empty values for any field
- Click on the `update`

![Screenshot 2022-10-16 at 1 32 20 PM](https://user-images.githubusercontent.com/25361949/196025269-6c64dd43-97fa-43f1-a176-d108ea2b5d07.png)

**Comment by tanishk-23** [comment]
@withshubh please assign this issue to me

**Comment by amit-ksh** [comment]
I would like to work on this issues.

**Comment by navya-Singla-1-3-0-9** [comment]
I would like to take this up. Please assign this issue to me.

**Comment by withshubh** [comment]
> @withshubh please assign this issue to me

Hey @tanishk-23 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hi @amit-ksh & @navya-Singla-1-3-0-9 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).
