### ISSUE TITLE
Selecting a heading on rich text editor redirects to dashboard

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4460]
### Is your proposal related to a problem?

When selecting headings (H1, H2, H3 etc) in the Rich text editor component, the page redirects to the dashboard of ToolJet.

### Describe the solution you'd like

Fix the Rich Text Editor heading selection.

### How to reproduce the issue?
- Open ToolJet app builder
- Drag and drop Rich Text Editor on the canvas
- Select any heading

[richtext_1.webm](https://user-images.githubusercontent.com/25361949/196038716-b6e52f51-0ca6-4700-a66b-45b92ced5b94.webm)

**Comment by jerempy** [comment]
Can I take this one?

**Comment by Revortni** [comment]
I'd like to try this one

**Comment by withshubh** [comment]
> Can I take this one?

Hi @jerempy 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
> I'd like to try this one

Hi @Revortni 👋  

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by Revortni** [comment]
@withshubh Ok ill check other issues.  Quick question. I was trying to setup the project using docker and got this error. Not sure what to do about it
![image](https://user-images.githubusercontent.com/19191940/196043372-b707ecaa-428a-4b14-8f20-a7fedfe801b4.png)

**Comment by withshubh** [comment]
> @withshubh Ok ill check other issues. Quick question. I was trying to setup the project using docker and got this error. Not sure what to do about it ![image](https://user-images.githubusercontent.com/19191940/196043372-b707ecaa-428a-4b14-8f20-a7fedfe801b4.png)

Hey @Revortni 👋 
You can shoot setup related questions on our slack channel. Feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Revortni** [comment]
@withshubh  sure

**Comment by MOHAMMED-AAJ** [comment]
4487
