### ISSUE TITLE
[refactor]: refactor of translation keys

### ISSUE THREAD

**Issue by daniloff200** [ToolJet/ToolJet#4461]
### What area of the codebase is to be refactored?
 
During my work on #4261 I've noticed one thing in all translation JSON's:
 
 
<img width="489" alt="12323232" src="https://user-images.githubusercontent.com/13692220/196038920-37f32a6d-7a88-4cc2-9dd0-f0ae38fe9a57.PNG">
 
One of the keys has a typo in the name, and also, few lines down we have the same one, but, with the correct name. I'm pretty sure, that should be removed.

Also, there are a few typos in other keys, which I also want to change, for example, in keys like `connectionVerifeid`

### What are the potential advantages of this proposed refactoring?
We gonna get rid of unnecessary and incorrect duplicated translation key, which is not really needed, because, we have the correct one already

**Comment by withshubh** [comment]
Hey @daniloff200 👋 
Thanks for creating the issue (and the PR) but there is already another PR for the same changes - https://github.com/ToolJet/ToolJet/pull/4400

Unfortunately, we will have to close this issue and the PR for this issue.

**Comment by daniloff200** [comment]
oh!
I haven't seen that :)
