### ISSUE TITLE
Appwrite database need "databaseId" request parameter

### ISSUE THREAD

**Issue by jqlblue** [ToolJet/ToolJet#4475]
### Environment

    ToolJet  MacOS ...

### What is the expected behaviour?

    i want to config ToolJet connect to Appwrite database

### What is the current behaviour?

    but it failed with “404 | database_not_found | Database not found”。maybe the databaseId is required in appwrirte 1.0.3。

### How to reproduce the issue?

1. Appwrite database verison：1.0.3
2. ToolJet verison：current release。1.27.1
3. add Appwrite database

**Comment by shah21** [comment]
I will look into this issue @jqlblue let me test it from my side too

**Comment by shah21** [comment]
look like the current implementation is deprecated, will fix this

**Comment by stepinfwd** [comment]
Hi , @jqlbluei  had tested appwrite and did get the same error when my appwrite setup was not correct but i was able to connect after setting up correctly . 
few points to keep in mind -
1)Specify port number in host 
2) in appwrite create user in auth section and give update permissions
 for collection in `collection ->  settings`

**Comment by byawitz** [comment]
I've created a PR for it

https://github.com/ToolJet/ToolJet/pull/5612

**Comment by neozhu** [comment]
I also encountered the same issue. I suspect it's because the Database Id is not mentioned in the Host connection. However, how should I configure this Database Id?
![image](https://github.com/ToolJet/ToolJet/assets/1549611/a7635206-8f13-4c54-85fc-d460fe00b45f)

**Comment by mansukh-tj** [comment]
PR Merged, marking as closed
