### ISSUE TITLE
[Bug] there's no space on hyperlink text at Login, Sign Up & Forgot Password page 

### ISSUE THREAD

**Issue by depapp** [ToolJet/ToolJet#4478]
### Version Information
v1.27.1

### Environment

All envs

### What is the expected behaviour?

expected text should be 
- `Don't have account yet? Sign up`
- `Already have an account? Sign in`

### What is the current behaviour?

there's no space on `Don't have account yet?Sign up` & `Already have an account?Sign in` text

### How to reproduce the issue?

1. open page at `/login` or `/signup` or `/forgot-password`
2. observe

### Screenshots or Screencast

![before - tooljet](https://user-images.githubusercontent.com/6134774/196145490-f6e267bb-1e03-4e4c-861b-e8c891f18fd4.png)

### Any possible solutions?
![Screen Shot 2022-10-17 at 16 48 27](https://user-images.githubusercontent.com/6134774/196146866-1b500bd2-af25-4af3-84f4-a7a3e99d5afa.png)

### If the bug is confirmed, would you be willing to submit a PR?

please assign this issue for me. I'll work on it!
cc @withshubh

**Comment by withshubh** [comment]
Hey @depapp 
Assigned this issue to you.

**Comment by depapp** [comment]
> Hey @depapp Assigned this issue to you.

thanks @withshubh , I'll work on it 🙇🏻

**Comment by Frenchtoast0** [comment]
Hi @withshubh, why was my request to fix this issue closed: https://github.com/ToolJet/ToolJet/issues/4412 but this one is allowed now?

**Comment by depapp** [comment]
@withshubh @Frenchtoast0 sorry guys, I didn't know if this kind of issue was reported.
I didn't check on closed issues, I only check on open issues 🙇

**Comment by shubh22** [comment]
These pages are under revamp so this issue will not be accepted as well.
