### ISSUE TITLE
actions.showAlert cannot show danger type alerts

### ISSUE THREAD

**Issue by tunix** [ToolJet/ToolJet#4480]
### Version Information

```
docker run \
  --name tooljet \
  --user root \
  --restart unless-stopped \
  -p 3000:3000 \
  -v tooljet_data:/var/lib/postgresql/13/main \
  docker.io/tooljet/try:latest
```

### Environment

Docker on Linux

### What is the expected behaviour?

I expect to see an alert when clicking on a button.

### What is the current behaviour?

The alert doesn't show up. If I change alert type to `info` or `warning` the alert shows up.

### How to reproduce the issue?

1. Create a runJS query with this code: `actions.showAlert("danger", "testing")`
2. Assign this query to a button on `click` event.
3. Click the button to trigger the query. (running the query directly doesn't also show the alert)

### If the bug is confirmed, would you be willing to submit a PR?

Not at this moment

**Comment by shubh22** [comment]
Hi @tunix,

Thanks for bringing this up. We have replicated it. 
We will fix it soon.

**Comment by gagandeepp** [comment]
@withshubh interested please assign

**Comment by tanishk-23** [comment]
@withshubh can I work on this issue?

**Comment by withshubh** [comment]
Hi @gagandeepp  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hey @gagandeepp - Any update on the PR? :)

**Comment by withshubh** [comment]
Unassigned @gagandeepp since there was no update. The issue is up for grab.
