### ISSUE TITLE
Table client side filter not applying as expected

### ISSUE THREAD

**Issue by sureshveernala** [ToolJet/ToolJet#4483]
### Version Information
1.14.1

### Environment
Docker

### What is the expected behaviour?
Filtered data should be displayed when table data is updated

### What is the current behaviour?
When the table data is updated client-side filter is not applied but the icon shows as applied

### How to reproduce the issue?
1. Add a table component with some data
2. Add & Apply a client-side filter on table data
3. Update the table data using a query
4. Now the data without filter will appears

**Comment by withshubh** [comment]
Hey, @sureshveernala - Can you please try to use the latest version of ToolJet? We recently made some major fixes and updates to the table

**Comment by sureshveernala** [comment]
> Hey, @sureshveernala - Can you please try to use the latest version of ToolJet? We recently made some major fixes and updates to the table

Thank you @withshubh, this issue was fixed in the latest version
