### ISSUE TITLE
[Datasource] - Create a new data source plugin for Microsoft Azure Blob Storage

### ISSUE THREAD

**Issue by shubh22** [ToolJet/ToolJet#4484]
**Goal**
Create a new data source plugin for **Microsoft Azure Blob Storage** to store large objects

**Operations to be supported:**

- List Containers
- List blobs in a container (paginated)
- Delete a blob
- Upload a new blob
- Read a blob

**Implementation**
Guide for building ToolJet plugins: https://docs.tooljet.com/docs/contributing-guide/tutorials/creating-a-plugin
Azure Blob SDK reference: https://learn.microsoft.com/en-us/javascript/api/overview/azure/storage?view=azure-node-latest

**Related plugins**
AWS S3 - https://docs.tooljet.com/docs/data-sources/s3

**Comment by vishnurk6247** [comment]
Hey @shubh22, I'd like to give this a shot. Could you please assign this issue to me?

**Comment by shubh22** [comment]
@vishnurk6247 sure. assigning it to you :)

**Comment by withshubh** [comment]
Hey @vishnurk6247 - Please let us know if you're still working on this issue :)

**Comment by vishnurk6247** [comment]
Hey @withshubh, will create a PR for this soon. I was kind of busy with things at workplace

**Comment by withshubh** [comment]
> Hey @withshubh, will create a PR for this soon. I was kind of busy with things at workplace

Thanks for the update @vishnurk6247 🙌
