### ISSUE TITLE
[docs]: Errors in Docker Setup Doc

### ISSUE THREAD

**Issue by SarojWasti** [ToolJet/ToolJet#4488]
### Summary

There are many grammatical errors in Docker Setup doc which in my opinion should be fixed for improving documentation (user instructions).

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/setup/docker

### Steps to reproduce the issue

Visit the doc link and there are many fixable errors throughout the documentation

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by withshubh** [comment]
Hey @SarojWasti 
Thanks for creating the issue. 
The issue doesn't have enough information about the errors, can you share screenshots with marks on those errors?

**Comment by SarojWasti** [comment]
1. Repeated words and punctuation mistake here:
![ss2](https://user-images.githubusercontent.com/69208771/196316227-7c568983-e809-40dc-bc0a-283dcac03ad0.png)

2. to use -> using the (could be improved), and some missing commas.
![ss3](https://user-images.githubusercontent.com/69208771/196316355-8bd2727e-5d60-45b4-aa7f-581046108f2a.png)

3. `If you are running a Linux server` makes more sense (could be improved), comma after `In that case` and the punctuation mistake could be improved.
![ss4](https://user-images.githubusercontent.com/69208771/196316544-e1ac5b9b-e24f-4d59-96ae-31f17fbb389e.png)

4. using `TCP` to instead of `tcp` would be better but @withshubh take a look and tell me if it should be improved or not.
![ss5](https://user-images.githubusercontent.com/69208771/196316940-c873bb40-851e-4485-a7d2-e7ef0e71ced6.png)

**Comment by SarojWasti** [comment]
And the use of `Docker` word throughout the documentation isn't consistent. Should use capital letter for starting letter. You can make the call for improvements.

**Comment by withshubh** [comment]
Hi @SarojWasti  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
For point number 4 - let's make `TCP` caps.

**Comment by SarojWasti** [comment]
Okay
