### ISSUE TITLE
Line number is displayed while show line number is set to false in code editor

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4489]
### What is the expected behaviour?

The code editor component has **show line number** property which when set to `{{false}}` should hide the line number from the component

### What is the current behaviour?

Currently, **show line number** property when set to `{{false}}` doesn't hides the line numbers from the component.

### How to reproduce the issue?

1. Add code editor to canvas
2. Click on the component handle of the code editor
3. Set **show line number** property to `{{false}}`

### Screenshots or Screencast

![Screenshot 2022-10-18 at 2 55 19 AM](https://user-images.githubusercontent.com/25361949/196287941-de699de1-8af7-4103-a9f6-3bf00fbe1136.png)

**Comment by thenishantsapkota** [comment]
Hi I would like to get assigned on this issue!

**Comment by tanishk-23** [comment]
@withshubh can I work on this issue?

**Comment by withshubh** [comment]
Hi @thenishantsapkota  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by thenishantsapkota** [comment]
> Hi @thenishantsapkota
> 
> Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you.
> 
> If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

Thank you 💯 
I am working on this 😄

**Comment by withshubh** [comment]
Hey @thenishantsapkota - Please let us know if you're still working on this issue. :)

**Comment by withshubh** [comment]
Unassigned @thenishantsapkota as there was no update on the PR.
The issue is up for grabs now.

**Comment by stepinfwd** [comment]
closing this as its already fixed in current develop
