### ISSUE TITLE
chart loading spinner is not at the centre vertically

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4492]
### What is the expected behaviour?

The loader in the chart component should be at the center

### What is the current behaviour?

The loading state spinner is at the top of the chart component.

### How to reproduce the issue?

1. Add chart component
2. Click on the component handle of the chart 
3. Toggle on the loading state

### Screenshots or Screencast

![Screenshot 2022-10-18 at 4 09 47 AM](https://user-images.githubusercontent.com/25361949/196296980-b2c8a63c-4e34-4495-bef7-de8a5c62964a.png)

**Comment by fcoiuri** [comment]
Hi, can I work on this issue?

**Comment by withshubh** [comment]
Hey @fcoiuri 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by tanishk-23** [comment]
@withshubh can I work on this issue?

**Comment by akarsh-jain-790** [comment]
@withshubh can you assign this issue to me ?

**Comment by ishantagarwal00** [comment]
Hey @withshubh, if the issue still exists, I would like to work on the same. Can you please assign this to me?

**Comment by withshubh** [comment]
Hey @fcoiuri Are you still working on it?

**Comment by zaahmed-nisum-com** [comment]
@withshubh  Can i work on it please.

**Comment by withshubh** [comment]
Hi @zaahmed-nisum-com 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by zaahmed-nisum-com** [comment]
@withshubh  can you please review the ME https://github.com/ToolJet/ToolJet/pull/4640
