### ISSUE TITLE
set default color for Tabs highlight color

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4493]
### What is the expected behaviour?

There should be a default color value for Highlight color of tabs component

### What is the current behaviour?

Currently, there is no value set to Highlight Color in styles of Tabs

### How to reproduce the issue?

1. Add Tabs component
2. Click on the component handle of the tabs to open properties 
3. Go to styles and check Highlight color

### Screenshots or Screencast

![Screenshot 2022-10-18 at 4 14 13 AM](https://user-images.githubusercontent.com/25361949/196297495-1d4c065b-b733-49d6-a41f-bccf5368a36d.png)

**Comment by adripo** [comment]
I would like to work on this issue
