### ISSUE TITLE
Table Event - Change label from Bulk update to 'Save Changes'

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4494]
### What is the expected behaviour?

There is an event in the Table named `Bulk Update`.

### What is the current behaviour?

The `Bulk Update` label should be renamed as `Save Changes`

### How to reproduce the issue?

1. Add Table component
2. Open table properties, and go to the events
3. Add an Event, and on the events dropdown you'll find `Bulk Update`

### Screenshots or Screencast
![Screenshot 2022-10-18 at 4 19 51 AM](https://user-images.githubusercontent.com/25361949/196298372-9215736f-fcd3-44ec-a696-5ce86636fa99.png)

**Comment by 3t8** [comment]
Can I also work on this issue?

**Comment by Henrique-Gouvea** [comment]
Hi, I would like to work on this issue... could you please assign it to me?

**Comment by 3t8** [comment]
Changed label #4499

**Comment by withshubh** [comment]
Hey @Henrique-Gouvea 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment]
Hey @3t8 
Sorry, but there is an issue already assigned to you.
Also, Please don't create PRs unless the issue is assigned to you. Please follow the [Contributing Guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md).

**Comment by Henrique-Gouvea** [comment]
Hi @withshubh ,
Thanks, very happy to contribute

**Comment by Henrique-Gouvea** [comment]
Hi, 
Thanks for the opportunity to collaborate on my first issue.
#4515

**Comment by Henrique-Gouvea** [comment]
#4516
