### ISSUE TITLE
Table Event - Change label from on sorting to 'Sort Applied'

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4495]
### What is the expected behaviour?

In table, there is an event named `On sorting columns`

### What is the current behaviour?

The `On sorting columns` label should be renamed as `Sort Applied`

### How to reproduce the issue?

1. Add Table component
2. Open table properties, and go to the events
3. Add an Event, and on the events dropdown you'll find `On sorting columns`

### Screenshots or Screencast

![Screenshot 2022-10-18 at 4 24 05 AM](https://user-images.githubusercontent.com/25361949/196298694-1e99ee32-f7a6-4a9c-85c7-8000bd24ae75.png)

**Comment by 3t8** [comment]
Can I also work on this issue?

**Comment by Henrique-Gouvea** [comment]
Hi, I would like to work on this issue... could you please assign it to me?

**Comment by 3t8** [comment]
Changed label https://github.com/ToolJet/ToolJet/pull/4500

**Comment by tanishk-23** [comment]
@withshubh can I work on this issue?
