### ISSUE TITLE
Table Properties - Change label from 'Show bulk update actions' to 'Show Update Buttons'

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4496]
### Is your proposal related to a problem?

In the table, we have a property called `Show bulk update actions`, rename the label to `Show update buttons`

### How to reproduce the issue?

1. Add Table component
2. Open table properties, and go to the options
3. You'll find an option to enable/disable 'Show bulk update actions'

![Screenshot 2022-10-18 at 4 27 53 AM](https://user-images.githubusercontent.com/25361949/196299036-a8c246a5-8394-4d14-9c6d-ab0f6ff0aa47.png)

**Comment by 3t8** [comment]
I'd like to work on this

**Comment by withshubh** [comment]
Hi @3t8 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by 3t8** [comment]
Let me know if I should change anything else #4497

**Comment by 3t8** [comment]
Did you get a chance to look at it? @withshubh
