### ISSUE TITLE
Deleting component shows toast with MacOs shortcut by default

### ISSUE THREAD

**Issue by 3t8** [ToolJet/ToolJet#4512]
### Version Information
Latest
### Environment
ToolJet Cloud
### What is the expected behaviour?
When deleting any component a toast message with `Component deleted! (⌘ + Z to undo)` should be shown on MacOs.
When deleting any component a toast message with `Component deleted! (ctrl + Z to undo)` should be shown on Windows/Linux.
### What is the current behaviour?
When deleting any component an alert with `Component deleted! (⌘Z to undo)` is shown on all platforms
### How to reproduce the issue?

1. Create a new application
2. Add any component
3. Delete the component

### Screenshots or Screencast
![toast](https://user-images.githubusercontent.com/62209650/196441045-8dac0e93-2b44-4f8a-975b-87aeac87f024.png)

### Any possible solutions?
Identify the user platform and change the message of the toast with the according shortcut keys

### Can you identify the location in the driver source code where the problem exists?
`frontend/src/Editor.jsx`

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by withshubh** [comment]
Hey @3t8 
Thanks for creating this issue. Assigned this issue to you.

**Comment by 3t8** [comment]
Thanks! @withshubh check #4513
