### ISSUE TITLE
[localization] Finish the Spanish translation

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4523]
### Is your proposal related to a problem?

We got community contribution of Spanish translation for the following strings:
- `globals`
- `loginSignupPage`
- `appCard`
- `widgetManager`

The rest of the strings are left to be translated.

### Describe the solution you'd like

Translate the remaining strings to completely localize ToolJet in Spanish

Note: This issue requires a native speaker

**Comment by withshubh** [comment]
Hey @ShankyJS - Are you interested in this issue?

**Comment by LPRegen** [comment]
Hi, if @ShankyJS doesn't want to take it I would like to @withshubh

**Comment by ShankyJS** [comment]
> Hey @ShankyJS - Are you interested in this issue?

I can take it @withshubh 

Thanks a lot, please assign!

**Comment by withshubh** [comment]
Hey @ShankyJS 
Assigned to you.

**Comment by ShankyJS** [comment]
Thank you @withshubh, going to work on it this weekend!

**Comment by ShankyJS** [comment]
Currently working on this PR: https://github.com/ToolJet/ToolJet/pull/4600/files will finish it probably tomorrow!
