### ISSUE TITLE
[Localization] Add Hebrew Translation

### ISSUE THREAD

**Issue by TomerPacific** [ToolJet/ToolJet#4556]
### Is your proposal related to a problem?
Seeing as there are other languages ToolJet is being translated, I thought to also help ToolJet support Hebrew.

### Describe the solution you'd like

Being a native Hebrew speak, I'd be happy to help out in translating ToolJet to Hebrew following this [guide](https://docs.tooljet.com/docs/contributing-guide/l10n/).

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by withshubh** [comment]
Hey @TomerPacific 
Thanks for showing interest in contributing to ToolJet.
Unfortunately, we will have to close this issue as the Hebrew translation is not on our roadmap at the moment.
Also, please follow the [contributing guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md) before creating a PR.
