### ISSUE TITLE
[docs]: docs/docs/Enterprise/audit_logs.md needs some Grammatical and spelling improvement.

### ISSUE THREAD

**Issue by Abubakrce19** [ToolJet/ToolJet#4563]
### Summary

I found some crucial errors which need to fixed

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

docs/docs/Enterprise/audit_logs.md

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Abubakrce19** [comment]
Please assign me this issue
with hacktoberfest tag 
Thank you

**Comment by Navaneeth-pk** [comment]
@Abubakrce19 closing the issue as it doesn't mention the specific mistakes.

**Comment by Abubakrce19** [comment]
@Navaneeth-pk 
I have already generated a PR for this issue which got merged! but just because
that PR was not resolving an issue[with hacktoberfest tag] my PR is not valid for swags, thats why I created this issue.
Please consider my PR for Tooljet swags even it does not adress an
issue with hacktoberfest tag.
Thank you
