### ISSUE TITLE
[Localization] Support for Tamil - Translation

### ISSUE THREAD

**Issue by Gokul-Ks** [ToolJet/ToolJet#4565]
### Is your proposal related to a problem?

I would like to extend accessibility to Tooljet by adding Tamil translation

### Describe the solution you'd like

I'm a native Tamil speaker and would like to Translate Tooljet. I will use this guide for this issue [guide](https://docs.tooljet.com/docs/contributing-guide/l10n/)

### If the feature is approved, would you be willing to submit a PR?

Yes

**Comment by shubh22** [comment]
Hi @Gokul-Ks , 
This is not our roadmap as of now.
