### ISSUE TITLE
Add color to the lines above and below Property and Styles

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4573]
### Is your proposal related to a problem?

In dark mode, when you click on a widget to edit its properties, you'll see that the color of the lines of the Property and Styles bar is white.

### Describe the solution you'd like

Change the color of the lines according to the Dark mode in ToolJet.

### Steps to reproduce the issue
- On the app builder, drag a widget and check the top of the right sidebar 

![image](https://user-images.githubusercontent.com/25361949/197395618-1cb67d82-63a1-4992-a5b1-869e345dfbd7.png)

**Comment by tanishk-23** [comment]
@withshubh can I work on this issue?

**Comment by Jasleen-001** [comment]
hey,i would like to work on this issue .Kindly assign it to me

**Comment by alammoiz** [comment]
Could you please assign to me?

**Comment by Saikatssd** [comment]
I have already started working on this. Please Assign me

**Comment by withshubh** [comment]
Hey @Jasleen-001 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Saikatssd** [comment]
ok

**Comment by TheLearneer** [comment]
@withshubh You might have actually forgot to assign though 🙈

**Comment by ckragarwal** [comment]
Can I work on this if this is still pending?

**Comment by withshubh** [comment]
Hey @Saikatssd - Are you still working on it?

**Comment by Pranay-Tej** [comment]
Hi, Can I pick this up?

**Comment by withshubh** [comment]
@Pranay-Tej Assigned to you

**Comment by shubh22** [comment]
This issue doesnt exist in latest version.
