### ISSUE TITLE
fix the broken calendar icon (App Icon in dashboard)

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4574]
### Is your proposal related to a problem?

Go to the dashboard and click on the three dots on the app card. Select the `Change icon` option and you'll see that one of the icons is broken.

### Describe the solution you'd like

Fix the breaking Calendar icon

![Screenshot 2022-10-20 at 10 34 03 AM](https://user-images.githubusercontent.com/25361949/197395755-08547829-fffb-450c-90ef-21aebaadf67c.png)

**Comment by tanishk-23** [comment]
@withshubh can I work on this issue?

**Comment by akarsh-jain-790** [comment]
@withshubh can you assign this to me?

**Comment by ishantagarwal00** [comment]
Hey @withshubh, I would love to work on this. Can you please assign this to me?

**Comment by withshubh** [comment]
Hey @ishantagarwal00 
Assigned this issue to you.

**Comment by AAYUSH-droid** [comment]
Hey @withshubh i would like to take this issue!

**Comment by withshubh** [comment]
Hey @ishantagarwal00 - Any update on this?

**Comment by withshubh** [comment]
Hey @ishantagarwal00 - Unassigned the issue as there was no update.

**Comment by AAYUSH-droid** [comment]
Hey can you tell me more about the file where the code for this is?!

**Comment by stepinfwd** [comment]
file :: frontend/src/HomePage/AppCard.jsx
fix 
frontend/assets/images/icons/app-icons/calender.svg
change this file name to `calendar.svg`
@AAYUSH-droid

**Comment by Pranay-Tej** [comment]
Hi, Can I pick this up?

**Comment by withshubh** [comment]
@Pranay-Tej assigned to you.
