### ISSUE TITLE
While deleting a version, show the name of version in the confirmation modal.

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4575]
### Is your proposal related to a problem?

Currently, when you delete a version from the app. The modal that shows doesn't confirm which version is being deleted.

### Describe the solution you'd like

Display the version that the user is trying to delete in the modal.

### Steps to reproduce the issue
- Create/Open an app in ToolJet
- Create a version and try to delete it
- Check the warning in the delete modal that pops-up

![Screenshot 2022-10-23 at 6 57 49 PM](https://user-images.githubusercontent.com/25361949/197395890-cb6a0c3b-9a32-4fe4-a4d9-965525391c8e.png)

**Comment by tanishk-23** [comment]
@withshubh can I work on this issue?

**Comment by ishantagarwal00** [comment]
Hey @withshubh , I would like to work on this issue. Can you please assign this to me?

**Comment by withshubh** [comment]
> Hey @withshubh , I would like to work on this issue. Can you please assign this to me?

Hey @ishantagarwal00 This issue is already assigned to you - https://github.com/ToolJet/ToolJet/issues/4574

**Comment by ishantagarwal00** [comment]
Hey @withshubh, issue #4574 is assigned to me, thanks for that, but I would like to work on issue #4575 also if you allow.

**Comment by FroostyCodes** [comment]
@withshubh can I work on this?

**Comment by withshubh** [comment]
Hey @FroostyCodes 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)
