### ISSUE TITLE
Alert does not break lines if there are no spaces in the message

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4576]
### Is your proposal related to a problem?

Currently, when you try to show a long alert message it won't break the line and will go out of bounds.

### Describe the solution you'd like

Fix the alert message to break the line.

### Steps to reproduce the issue
- Create/Open an app in ToolJet
- Add an event handler to show the alert 
- Add a long alert message and trigger the event to show alert

![image (1)](https://user-images.githubusercontent.com/25361949/197395973-4fb86f40-11a4-4d86-8efa-bd7b3b7f7c0b.png)

**Comment by ishantagarwal00** [comment]
Hey @withshubh, I would like to work on this issue. Can you please assign this to me?

**Comment by alammoiz** [comment]
Could you please assign to me?

**Comment by withshubh** [comment]
Hey @ishantagarwal00 - There is already an issue assigned to you #4574

**Comment by withshubh** [comment]
> Could you please assign to me?

Hey @alammoiz 
Assigned the issue to you.

**Comment by alammoiz** [comment]
> > Could you please assign to me?
> 
> Hey @alammoiz Assigned the issue to you.

Hi, Thanks for assigning me. Should I add ellipses here or move this to the next line?

**Comment by alammoiz** [comment]
@withshubh  Please review PR https://github.com/ToolJet/ToolJet/pull/4636
