### ISSUE TITLE
dark mode on table's `striped` and `Striped & Bordered` table type mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4578]
### Is your proposal related to a problem?

The columns on the table show up in light mode when the table type is selected as `Striped` or `Striped & Bordered`

### Describe the solution you'd like

Make the particular table type compatible with dark mode.

### Steps to reproduce the issue
- Create/Open an app in ToolJet
- Add a table widget
- Click on the table to edit its properties
- Go to the styles and change the table type 

![image (1) (1)](https://user-images.githubusercontent.com/25361949/197396413-d9091a61-fe10-4e26-9306-627b4b61aa89.png)

**Comment by akarsh-jain-790** [comment]
@withshubh can you assign this to me? I have already raised PR for my current assignments.

**Comment by withshubh** [comment]
Hey @akarsh-jain-790 
Assigned the issue to you.
