### ISSUE TITLE
text not saved of `Copy to clipboard` action for `on click` event of table's action button

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4579]
### Is your proposal related to a problem?

When adding the `on click` event for the action button on the table widget and selecting the `Copy to Clipboard` action, when you enter the text, it won't save. It resets after you close the event handler popup.

### Describe the solution you'd like

Fix the `Copy to clipboard` action for the action button

[copy-to-clipboard.webm](https://user-images.githubusercontent.com/25361949/197396927-f2271097-0ed2-4946-821e-153519698875.webm)

**Comment by Smartmind12** [comment]
@withshubh Can you assign this to me so that i can work on it!

**Comment by alammoiz** [comment]
Could you please assign it to me?

**Comment by withshubh** [comment]
> @withshubh Can you assign this to me so that i can work on it!

Hi @Smartmind12 , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)
