### ISSUE TITLE
Email click at privacy page is not clickable 

### ISSUE THREAD

**Issue by PrakashGatiyala** [ToolJet/ToolJet#4583]
### Is your proposal related to a problem?

![image](https://user-images.githubusercontent.com/34413515/197418715-e4bee2e5-811a-462f-a4e0-343f03b0fdd6.png)

Hi,  Email click at privacy page(https://www.tooljet.com/privacy) is not clickable. When clicking on email, it should automatically open the email app. 
I want to work on this issue. 
Can you assign it to me?

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

**Comment by Navaneeth-pk** [comment]
Thanks for reporting the issue. Website is not part of this repo, we will fix this asap.
