### ISSUE TITLE
Image overflown on the homepage

### ISSUE THREAD

**Issue by diwash007** [ToolJet/ToolJet#4598]
### Environment
ToolJet Cloud

### What is the expected behaviour?
The image should not be overflown and should fit within the viewport.

### What is the current behaviour?
Image is being overflown

### How to reproduce the issue?

1. visit https://www.tooljet.com/

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/39879720/197708985-412c715c-9b4b-4aff-a160-f691a44df164.png)

### Please provide any traces or logs that could help here.
Chrome Version 106.0.5249.119 (Official Build) (64-bit)

### Any possible solutions?
Changing the provided alt size from 100vw to 625px

### Can you identify the location in the driver source code where the problem exists?
I will figure it out soon.

### If the bug is confirmed, would you be willing to submit a PR?
yes

**Comment by withshubh** [comment]
Hey @diwash007 - Thanks for creating the issue but this repository does not include the code for the website. We'll get it fixed internally.

**Comment by withshubh** [comment]
This is fixed now. Thanks again!
