### ISSUE TITLE
website overflow x-axis

### ISSUE THREAD

**Issue by Ali7040** [ToolJet/ToolJet#4599]
### Version Information
Version 106.0.5249.119 (Official Build) (64-bit)
### What is the expected behavior?

image overflow x-axis. 

### What is the current behavior?

overflow
 x-axis

### How to reproduce the issue?

1.
2.
3.

### Screenshots or Screencast
![25 10 2022_13 42 11_REC](https://user-images.githubusercontent.com/81979505/197727215-f8de46c1-caa3-4d13-b9a9-f0d10a63e5c8.png)
![25 10 2022_13 42 25_REC](https://user-images.githubusercontent.com/81979505/197727248-fcca502d-aa2d-4bb9-8f2a-36ed177404d4.png)

### If the bug is confirmed, would you be willing to submit a PR?
         yes

**Comment by withshubh** [comment]
Hey @Ali7040 I don't find any image overflow on the website. Can you specify?

**Comment by Ali7040** [comment]
@withshubh  now it's done
