### ISSUE TITLE
[Deprecation warning] Update Github actions node version to Node 16

### ISSUE THREAD

**Issue by sudhinm** [ToolJet/ToolJet#4617]
### Version Information
NA
### Environment
NA

### What is the expected behaviour?
Node version 16 should be used in all the actions in the Github workflow config.

### What is the current behaviour?
Github actions have stopped supporting Node 12 since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases).  And the usage of old version is leading to warning annotations as seen in the below screenshot.

### How to reproduce the issue?

1. Go to Github Actions
2. Click on a workflow run which is completed successfully from any workflow.
3. You will find Annotations showing deprecated warnings.

### Screenshots or Screencast
<img width="1348" alt="Screenshot 2022-10-26 at 7 46 41 PM" src="https://user-images.githubusercontent.com/34642968/198052519-95b8804a-143c-43c5-85fe-4eba7305217e.png">

### Please provide any traces or logs that could help here.
NA

### Any possible solutions?
Update the Node version to 16. Follow this [page](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12) for reference.

### Can you identify the location in the driver source code where the problem exists?
https://github.com/ToolJet/ToolJet/blob/develop/.github/workflows/packer-build.yml
https://github.com/ToolJet/ToolJet/blob/develop/.github/workflows/ci.yml
https://github.com/ToolJet/ToolJet/blob/develop/.github/workflows/packer-build.yml

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by Smartmind12** [comment]
@withshubh Can you assign this issue to me so that i work on this issue as part of hacktoberfest?

**Comment by withshubh** [comment]
Hey @sudhinm - Thanks for creating the issue. We'll get this fixed soon.

**Comment by FroostyCodes** [comment]
Hi @withshubh can I work on it?

**Comment by withshubh** [comment]
Hey @FroostyCodes - Are you willing to work on this issue?
