### ISSUE TITLE
[docs]: add image to button group docs

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4630]
### Summary

There is no image of the button group widget.

Add the following image in the button group doc below the description:
![Screenshot 2022-10-27 at 3 10 44 PM](https://user-images.githubusercontent.com/25361949/198250963-c29a2806-6c5e-465a-8942-772b7e0c526d.png)

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/button-group

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by FroostyCodes** [comment]
Hi @withshubh 
Can I work on this?

**Comment by withshubh** [comment]
Assigned to @hemanthhari2000 . ref: https://github.com/ToolJet/ToolJet/pull/4631#issuecomment-1293453924
