### ISSUE TITLE
fix the logo of Amazon SES in datasource modal

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4633]
### Is your proposal related to a problem?

The logo of Amazon SES datasource doesn't show up in the datasource modal.

### Describe the solution you'd like

Fix the broken image of the Amazon SES datasource

### How to reproduce the issue?

1. Go to the `Sources` in the left sidebar
2. Click on Add datasource
3. On the modal that pops up, scroll to find the Amazon SES

![Screenshot 2022-10-27 at 4 22 46 PM](https://user-images.githubusercontent.com/25361949/198272261-349b447f-5762-4288-914f-5b62ab6482ed.png)

**Comment by alammoiz** [comment]
Please assign this to me

**Comment by withshubh** [comment]
Hey @AyushK-101 - Assigned this issue to you.

**Comment by AyushK-101** [comment]
![image](https://user-images.githubusercontent.com/86164395/198587114-9fe92e53-e595-4902-a26c-b8a27adab3a0.png)

@withshubh the Amazon SEZ option is not there anymore, should I fix the mailgun logo instead?

**Comment by withshubh** [comment]
> ![image](https://user-images.githubusercontent.com/86164395/198587114-9fe92e53-e595-4902-a26c-b8a27adab3a0.png)
> 
> @withshubh the Amazon SEZ option is not there anymore, should I fix the mailgun logo instead?

Hey @AyushK-101 - You need to be on the latest version to see the Amazon SES datasource. If you're checking it on cloud then the latest version is not yet deployed to ToolJet Cloud.
Also, Mailgun logo is already fixed.
Please setup ToolJet's latest version locally.

**Comment by AyushK-101** [comment]
@withshubh Can you please tell the file name where the changes are to be made, I am unable to find it

**Comment by withshubh** [comment]
> @withshubh Can you please tell the file name where the changes are to be made, I am unable to find it

@stepinfwd - Please help here

**Comment by stepinfwd** [comment]
Hey @AyushK-101  `plugins/packages/amazonses/lib/icon.svg` this would be the location of icon.

**Comment by withshubh** [comment]
Hey @AyushK-101 - Any update on the PR? :)

**Comment by AyushK-101** [comment]
@withshubh Hey, the ses logo has been updated in #5121

**Comment by withshubh** [comment]
Thanks @AyushK-101
