### ISSUE TITLE
Unlimited character title possible while editing a workspace name

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4635]
### Environment
ToolJet Cloud - Windows

### What is the expected behaviour?
While editing a workspace name, the user should not be able to add more than 25 characters to update a workspace name.

### What is the current behaviour?
Currently, users can bypass the 25-character limit with simple developer tools and then update the workspace name.

### How to reproduce the issue?

1. Go to the dashboard 
2. Go to the dropdown and edit a workspace name
3. Open developer tools (F12 key)
4. Select the text input of workspace name
5. Delete the maxlength="25"
6. Now you can update the workspace name with more than 25 chars

### Any possible solutions?
Add a backend validation.

Similar to the issue: https://github.com/ToolJet/ToolJet/issues/4354

**Comment by alammoiz** [comment]
@withshubh could you please assign it to me?

**Comment by kirti1211c** [comment]
@withshubh can I work on this issue?

**Comment by withshubh** [comment]
Hey @tanishk-23 - Assigned this issue to you.

**Comment by withshubh** [comment]
Hi @kirti1211c & @alammoiz 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

You can also use the "watch" feature of GitHub at the top right corner to get notified when new issues are created in this repository.
