### ISSUE TITLE
[docs]: replace the woocommerce connection screenshot from dark to light one

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4642]
### Summary

Currently, the image used in woocommerce datasource reference is captured in dark mode. Capture the connection screenshot in light mode and replace.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/woocommerce/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Pakeetharan** [comment]
Can you assign me this?

**Comment by withshubh** [comment]
Hey @Pakeetharan 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)
