### ISSUE TITLE
[docs]: update contributing.md

### ISSUE THREAD

**Issue by saimaheshtaduri** [ToolJet/ToolJet#4653]
### Summary

The report bug link can be even more specific.
change the docs from 
We use GitHub issues to track public bugs. Report a bug by [opening a new issue](https://github.com/ToolJet/ToolJet/issues/new/choose). It's that easy!
to
We use GitHub issues to track public bugs. Report a bug by [opening a new issue](https://github.com/ToolJet/ToolJet/issues/new?assignees=&labels=bug%2C+needs+triage&template=01_bug_report.md). It's that easy!

### Issue Type

Documentation feature/update

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by saimaheshtaduri** [comment]
@withshubh can I raise a pr ?

**Comment by withshubh** [comment]
Hey, @saimaheshtaduri - Closing this issue as we are already working internally on improving it.
