### ISSUE TITLE
fix the logo of Mailgun in datasource modal

### ISSUE THREAD

**Issue by Smartmind12** [ToolJet/ToolJet#4655]
### What is the expected behaviour?

Logo for Mailgun should be visible like all the other data source logos.

### What is the current behaviour?

The logo of Mailgun datasource is not visible in the datasource modal as an error is causing icon to be in white colour which is invisble in white background.

### How to reproduce the issue?

1. Go to the Sources in the left sidebar
2. Click on Add datasource
3. On the modal that pops up, scroll to find the Mailgun

### Screenshots or Screencast

![Screenshot 2022-10-28 at 8 08 57 PM](https://user-images.githubusercontent.com/91927689/198651521-9f62cbd4-397f-43b6-acdb-fa93d7e47fb1.png)

### Any possible solutions?

Updating the mailgun white logo to the latest and updated mailgun logo which is orange in colour.

### Can you identify the location in the driver source code where the problem exists?

Yes, I know where the problem exists.

### If the bug is confirmed, would you be willing to submit a PR?

Yes, I am willing to submit a PR rightaway!

**Comment by withshubh** [comment]
Closing this issue as this has already been fixed.
