### ISSUE TITLE
Readme.md Tooljet logo doesn't send to the website when clicked

### ISSUE THREAD

**Issue by Arkaroy147** [ToolJet/ToolJet#4657]
In the Readme.md in the Tooljet repo, the image of Tooljet logo doesn't take us to the Tooljet site when clicked. But in Tooljet/server, the nest logo can take us to the site when clicked.
I wish to add this feature in main Readme.md. Can you assign me this issue? Also, can I get a hacktoberfest tag in this issue?
I wish to do a pull request if got assigned

**Comment by withshubh** [comment]
Hey @Arkaroy147 - Thanks for creating the issue.
Closing this issue as we are already working on improving this internally.
