### ISSUE TITLE
Users page is not scrollable and therefore does not show all the users

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#466]
In the screenshot below, there are three more users after the user named 'Some one'. But they are not visible as you can see in the screenshot and the scrollbar is disabled. We need to either enable the scroll bar or install some sort of pagination.

![image](https://user-images.githubusercontent.com/20333972/128514302-80fabf29-2da9-4492-8f78-dc098e968c83.png)

**Comment by Navaneeth-pk** [comment]
There is already an issue for adding pagination: https://github.com/ToolJet/ToolJet/issues/148

**Comment by sherfin94** [comment]
Closing.
