### ISSUE TITLE
Duplicate Workspace Names shouldn't be allowed under any scenario 

### ISSUE THREAD

**Issue by snoseeds** [ToolJet/ToolJet#4673]
### Version Information
- v1.28.1

### Environment
- Docker

### What is the expected behaviour?
- Whenever a new workspace is to be created or an existing workspace name is to be updated, the application should not accept a duplicate workspace name irrespective of if the user is a member of that existing workspace or not.
- Beyond the business logic constraint desired above, there should also be a unique constraint on the `name` column of the `organizations` table.

### What is the current behaviour?
- When a new workspace is to be created or an existing workspace is to be updated, it allows a duplicate name once the user creating the duplicate workspace or updating to the duplicate workspace is not a member of the existing workspace.
- This leads to duplicate workspace names persisted at the database level

### How to reproduce the issue?
1. Have `userA` in a workspace named "Workspace A"
2. Have `userB` in a workspace named "Workspace B"
3. Login `userA` and click `Add Workspace` in his dashboard and enter "Workspace B" as the name of the new workspace.
4. The new but duplicate workspace named "Workspace B" would be created.
5. Selecting all the records in the `organizations` table of the database would also show the duplicate entries for "Workspace B"
6. This leads to several confusions, one of which is if `userA` is invited to the initial "Workspace B" and he accepts it, he would end up having multiple workspaces named `Workspace B` in his list of workspaces.

### Screenshots or Screencast
![duplicate_workspaces_tooljet](https://user-images.githubusercontent.com/38457061/199041745-66181f05-16f8-4677-be6d-3323b896889a.jpg)

### Any possible solutions?
- Add validation that checks duplicate workspace name while adding new workspace at the API level (`POST /api/organizations` and `PATCH /api/organizations`) irrespective of if the user adding the duplicate belongs to the existing workspace.
- Add a unique constraint to the `name` column of the `organizations` table of the database.

### Can you identify the location in the driver source code where the problem exists?
- The duplicate organization validation is only being done in the frontend presently at line 66 of `/frontend/src/_components/Organizations.jsx` and that only checks the duplicate from the prefetched list of organizations (workspaces) that the user belongs to.

### If the bug is confirmed, would you be willing to submit a PR?
Sure

**Comment by withshubh** [comment]
Hey @snoseeds - Thanks for creating the issue. 
This issue seems valid. Assigned the issue to you.

**Comment by snoseeds** [comment]
Great, thanks @withshubh. I've commenced work on it even while noting the issue can also happen when editing the name of an existing workspace, and I would do the fix for both!

**Comment by snoseeds** [comment]
Hi @withshubh, I think it would be good if we add a minimum length requirement for the organization name validation just as we have a max length for it. If you think so as well, what do you suggest should be the minimum length?

**Comment by withshubh** [comment]
> Great, thanks @withshubh. I've commenced work on it even while noting the issue can also happen when editing the name of an existing workspace, and I would do the fix for both!

Great! Can you please update the issue with the same information

**Comment by withshubh** [comment]
> Hi @withshubh, I think it would be good if we add a minimum length requirement for the organization name validation just as we have a max length for it. If you think so as well, what do you suggest should be the minimum length?

1 character minimum length is fine.

**Comment by thehacklady** [comment]
Hey @snoseeds, our team has worked on this issue and fix will be available in upcoming release. Hence, I'm closing this issue. 

P.S. : In case you want to refer to the PR - [](https://github.com/ToolJet/ToolJet/issues/5661)
