### ISSUE TITLE
add DTO validation for folder name, on folder creation

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4684]
### Is your proposal related to a problem?

The folder name (on folder creation) validation should have a data transfer object.

### Describe the solution you'd like

Create a DTO ([example](https://github.com/ToolJet/ToolJet/blob/develop/server/src/dto/version-create.dto.ts)) for validation for folder name (on folder creation)

reference: https://github.com/ToolJet/ToolJet/pull/4402#discussion_r1005465650

**Comment by mikebarr24** [comment]
@withshubh Could I take this issue?

**Comment by withshubh** [comment]
Sure @mikebarr24 - Assigning the issue to you.

**Comment by mikebarr24** [comment]
@withshubh 
I'm trying to get my head round DTOs and I'm just wondering if this has already been completed by Akshay.

This is within create-folder.sto.ts
```
import { Transform } from 'class-transformer';
import { IsString, IsNotEmpty } from 'class-validator';
import { sanitizeInput } from 'src/helpers/utils.helper';

export class CreateFolderDto {
  @IsString()
  @IsNotEmpty()
  @Transform(({ value }) => sanitizeInput(value))
  name: string;
}
```
