### ISSUE TITLE
Allow to add extra connection options to the PostgreSQL connection settings

### ISSUE THREAD

**Issue by christophberger** [ToolJet/ToolJet#4686]
### Is your proposal related to a problem?

Some hosted PosgreSQL databases require extra connection parameters. See e.g. the [cluster/routing parameter for the Cockroach DB Cloud database]( https://www.cockroachlabs.com/docs/stable/connect-to-the-database.html).

Example: `postgresql://<username>:<password>@<host>:<port>/<database>?sslmode=verify-full&options=--cluster%3D<routing-id>`

Here, `sslmode=verify-full` describes the SSL mode to use, and `options=--cluster=<routing-id>` specifies the database cluster to connect to. 

### Describe the solution you'd like

Please enhance the PostgreSQL connection form to allow entering extra connection parameters. They should be appended to the connection URL as `?<option1>=<value1>&<option2>=<value2>` (with proper URL escaping inside the values, see the cluster option as an example). 

### Describe alternatives you've considered

I would happily consider an alternate approach if someone can come up with one.

### If the feature is approved, would you be willing to submit a PR?

Sorry, I am not a JS/TS developer.

**Comment by mjyoung** [comment]
+1
