### ISSUE TITLE
Text Field Overlapping in Application Name Edit field

### ISSUE THREAD

**Issue by AkhilGKrishnan** [ToolJet/ToolJet#469]
### What is the current behavior?
  
  Text field overlapping
 
### How to reproduce the issue?

1. click on Create New Application
2. Edit Application Name
3. Add a long application name

### Screenshots or Screencast
<img width="1101" alt="Screenshot 2021-08-08 at 12 40 48 PM" src="https://user-images.githubusercontent.com/22231095/128624101-e6261314-d1b6-4ab2-9fe6-feb56cc13b2a.png">

**Comment by saideepesh000** [comment]
Hi, can I take this up ?

**Comment by Navaneeth-pk** [comment]
@saideepesh000 we are planning to change the layout of the app builder, it will free up some space from the header and this issue will be resolved.

**Comment by Navaneeth-pk** [comment]
The issue is resolved after we redesigned the editor layout.
