### ISSUE TITLE
Support for S3 type storage services

### ISSUE THREAD

**Issue by shubh22** [ToolJet/ToolJet#4710]
There are many object storage services which conform with AWS S3 protocol. They use the same AWS SDK to access the objects. Currently, we do not support such services. 

It will be an enhancement in the current AWS S3 plugin.

**Comment by poaudet** [comment]
+1 :)

Will be nice to add custom endpoint for s3 local gateway or storj.io

**Comment by shubh22** [comment]
@poaudet 
Feature is released in v1.30.0. 
Hence closing the issue.
