### ISSUE TITLE
failed to delete application

### ISSUE THREAD

**Issue by arioki1** [ToolJet/ToolJet#4721]
### Version Information
v1.28.3-ee1.5.3-cloud1.1.3

### Environment
ToolJet Cloud 

### What is the expected behaviour?
successfully delete application

### What is the current behaviour?
failed to delete application

### How to reproduce the issue?

1. delete application
2.
3.

### Screenshots or Screencast
<img width="1000" alt="Screenshot 2022-11-05 at 20 37 51" src="https://user-images.githubusercontent.com/1139881/200122790-17c02c38-7b7f-4a89-bd73-eefcec2cab40.png">

### Please provide any traces or logs that could help here.
vendor.js:26 HomePage.jsx (318:8) update or delete on table "app_versions" violates foreign key constraint "fk_rails_5a8dcbd85d" on table "apps"

**Comment by withshubh** [comment]
Hey @arioki1 - Thanks for creating the issue. We are already working on fixing this bug. We'll update here once it is fixed.
