### ISSUE TITLE
TypeError: Cannot read property 'body' of undefined - RestAPI 

### ISSUE THREAD

**Issue by congvmit** [ToolJet/ToolJet#4722]
### Environment

ToolJet Docker / Linux 

### What is the current behaviour?

I add a RestAPI as a source. Then write a query associating with that RestAPI source. 
I click on preview button and receive this error messsage.

```bash
server_1    | TypeError: Cannot read property 'body' of undefined
server_1    |     at RestapiQueryService.<anonymous> (/app/plugins/dist/packages/restapi/lib/index.js:177:233)
server_1    |     at Generator.throw (<anonymous>)
server_1    |     at rejected (/app/plugins/dist/packages/restapi/lib/index.js:25:65)
server_1    |     at runMicrotasks (<anonymous>)
server_1    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by withshubh** [comment]
Hey @congvmit - Thanks for creating the issue. Let me check this and get back to you.

**Comment by congvmit** [comment]
Hi @withshubh, 
Thank you so much! I realize that tooljet in docker cannot access to the API from another because of privacy. 
By change the rule, It works now. 
However, at the moment the issue is raised, the error message is quite ambiguous to me. It takes a long time to check the reason.
