### ISSUE TITLE
docker server does not start at v.1.28.3

### ISSUE THREAD

**Issue by tolgaulas** [ToolJet/ToolJet#4723]
### Version Information
1.28.3

### Environment
Docker

### What is the expected behaviour?
Server to start 

### What is the current behaviour?
Server exits with error
tooljet-1283-server-1    | > tooljet@1.18.0 db:setup
tooljet-1283-server-1    | > npm --prefix server run db:setup
tooljet-1283-server-1    |
tooljet-1283-server-1    |
tooljet-1283-server-1    | > server@0.0.1 db:setup
tooljet-1283-server-1    | > npm run db:create && npm run db:migrate
tooljet-1283-server-1    |
tooljet-1283-server-1    |
tooljet-1283-server-1    | > server@0.0.1 db:create
tooljet-1283-server-1    | > ts-node ./scripts/create-database.ts
tooljet-1283-server-1    |
tooljet-1283-server-1    |
tooljet-1283-server-1    | /app/server/node_modules/typescript/lib/typescript.js:42537
tooljet-1283-server-1    |         ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
tooljet-1283-server-1    |                  ^
tooljet-1283-server-1    | Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
tooljet-1283-server-1    |     at Object.resolveTypeReferenceDirective (/app/server/node_modules/typescript/lib/typescript.js:42537:18)
tooljet-1283-server-1    |     at /app/server/node_modules/ts-node/src/index.ts:737:16
tooljet-1283-server-1    |     at Array.map (<anonymous>)
tooljet-1283-server-1    |     at Object.resolveTypeReferenceDirectives (/app/server/node_modules/ts-node/src/index.ts:734:33)
tooljet-1283-server-1    |     at actualResolveTypeReferenceDirectiveNamesWorker (/app/server/node_modules/typescript/lib/typescript.js:116674:163)
tooljet-1283-server-1    |     at resolveTypeReferenceDirectiveNamesWorker (/app/server/node_modules/typescript/lib/typescript.js:116974:26)
tooljet-1283-server-1    |     at processTypeReferenceDirectives (/app/server/node_modules/typescript/lib/typescript.js:118456:31)
tooljet-1283-server-1    |     at findSourceFileWorker (/app/server/node_modules/typescript/lib/typescript.js:118341:21)
tooljet-1283-server-1    |     at findSourceFile (/app/server/node_modules/typescript/lib/typescript.js:118196:26)
tooljet-1283-server-1    |     at processImportedModules (/app/server/node_modules/typescript/lib/typescript.js:118602:25)
tooljet-1283-server-1 exited with code 1

### How to reproduce the issue?

1. Download mentioned release
2. Follow setup instcutions on the web
3. Docker compose up

**Comment by withshubh** [comment]
Hey @tolgaulas - Thanks for creating the issue. Let me check this and get back to you.

**Comment by akshaysasidrn** [comment]
Hey @tolgaulas, I'm unable to replicate the same locally. Would you mind sharing your .env file after masking the sensitive information?

**Comment by tolgaulas** [comment]
> Hey @tolgaulas, I'm unable to replicate the same locally. Would you mind sharing your .env file after masking the sensitive information?

Ouch, deleted that after I could manage to compile from the source. Sorry. If you say no replication then it's probably my fault as no one has contributed so far.
