### ISSUE TITLE
[ Bug ] : [ Manage Group Permissions Resources ] active tab switches to Apps on update in group permissions

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#4733]
### Environment
Development

### What is the expected behaviour?
On the Manage Groups page, whenever we change any permissions from the respective tab, the respective changes should get updated without switching the tab

### What is the current behaviour?
On changing any permission, under the Permissions Tab, data is updated but the active tab switches to `Apps` in place of `Permissions`

### How to reproduce the issue?

1. Login into ToolJet. It will redirect you to the dashboard
2. In the dashboard, look for the Workspace button in the headers section, the second button from right to left
3. Hover on the workspace button, and a pop-up will appear. Click on `Manage Groups` in the pop-up. You will be redirected to 
`User Groups `Page
4. In the User Group page, click on any group  except `Admin` Group
5. In the selected group, switch to the `Permissions` tab
6. Try to change any one of the permission, you will observe the toast message displaying `Group permissions updated` and the active tab switches to 'Apps', even though we made changes in the `Permissions` tabs. On changing any group permissions, it should stay in the Permissions tab itself.

### Screenshots or Screencast
[ToolJet - Dashboard - 8 November 2022 - Watch Video](https://www.loom.com/share/9e39542a150f4c54a5d6592c00eb2231)

### Can you identify the location in the driver source code where the problem exists?
frontend/src/ManageGroupPermissionsResources/ManageGroupPermissionsResources.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by jalajk24** [comment]
Can I work in this issue? I don't know a lot about how to proceed with this.

**Comment by withshubh** [comment]
> Can I work in this issue? I don't know a lot about how to proceed with this.

Hey @jalajk24 - Thanks for your interest in contributing to ToolJet.
There is already a PR created for this issue. Please pick other open issues.
