### ISSUE TITLE
[docs]: Adding Restack as a way to deploy ToolJet on k8s on the users' AWS infrastructure.

### ISSUE THREAD

**Issue by kuberaspeaking** [ToolJet/ToolJet#4762]
### Summary

I wish to add [Restack](https://www.restack.io) as a way to deploy Tooljet on kubernetes on the user's AWS infrastructure.
I propose to add it on the same level as the option with Heroku under [Setup](https://docs.tooljet.com/docs/setup/).
Please let me know if you have any suggestions.

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/setup/

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Navaneeth-pk** [comment]
We are adding more deployment options as per the requests from our community. Will reopen the issue if there is enough requests from our community. 
@kuberaspeaking
