### ISSUE TITLE
Need the ability to reuse query results in source headers and/or send custom headers on graphQL queries

### ISSUE THREAD

**Issue by a-c-m** [ToolJet/ToolJet#4768]
### Is your proposal related to a problem?

Yes, it's currently not possible to send customer headers to a graphQL source, based on data in the app. Which is critical if you are to use api's which are authenticated per user / something they entered, vs per app at the env. var level.

### Describe the solution you'd like

1. Ability to use app data in source headers (strong preference for this)
2. Ability to send custom headers in graphQL queries (this is a weak work around).

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?

Willing to review it, but not (at the moment) invest the time. Still evaluating solutions.

**Comment by yuku** [comment]
@withshubh Is this on your roadmap? Because of this issue, my company cannot adopt ToolJet. So, if this feature is approved, I'd like to try to submit a PR. 😉

**Comment by withshubh** [comment]
> @withshubh Is this on your roadmap? Because of this issue, my company cannot adopt ToolJet. So, if this feature is approved, I'd like to try to submit a PR. 😉

Hey @yuku - This feature is approved and that is on our roadmap.
It is great that you are willing to submit the PR - I am assigning this issue to you. 🙌
