### ISSUE TITLE
Tab switching from component controls not working correctly

### ISSUE THREAD

**Issue by GlenEaston** [ToolJet/ToolJet#4769]
### Version Information
1.29
### Environment
Docker
### What is the expected behaviour?
Event>Action>Control Components>Set Current Tab
When this is activated (eg from a Button), the app switches to the correct tab, but the tab is completely blank. (?? maybe rendering in the foreground??)

What should happen is the same as when one clicks on a tab: the tab renders correctly with components showing.

**Comment by withshubh** [comment]
Hey @GlenEaston - 
Sorry for the delay in response.
Can you share the screenshot of the event handler? 
I just want to take a look at how you're setting the `Current Tab` value.

**Comment by withshubh** [comment]
My bad. I'm closing this issue, please feel free to open this issue again if required.
You can join our [slack community](https://www.tooljet.com/slack) if you have any questions.

**Comment by prachi-sequoia** [comment]
Hi @withshubh, I'm facing a similar issue. We developed our application `(with version 1.29.0-ee1.5.4-cloud1.1.3)` last year and was working fine in production since. Tried running the same in my cloud account today, when I to click on a Tab or switch tabs via component controls the UI is completely blank. Even though components are visible in Inspector (Text / Input / Checkboxes etc.), they are not showing up on the UI. Attaching screenshots for reference.

<img width="1062" alt="image" src="https://github.com/ToolJet/ToolJet/assets/94529955/48175186-5d46-451d-a2d4-c60b1554bd56">

<img width="1102" alt="image" src="https://github.com/ToolJet/ToolJet/assets/94529955/6271d47a-881b-42b4-8ad1-418f6580d67d">

**Comment by kavinvenkatachalam** [comment]
Hey @prachi-sequoia,

Is there any errors on the debugger?

**Comment by prachi-sequoia** [comment]
Hi @kavinvenkatachalam, 
No errors showing up in the debugger.

**Comment by kavinvenkatachalam** [comment]
@prachi-sequoia Thanks for checking it. We will check the issue and get back to you

**Comment by prachi-sequoia** [comment]
Thanks, for the quick response!

Also, the same app is working in production but when I try to export > import the json to cloud getting the error 
`Could not import the app: Cannot read properties of undefined (reading 'options')` Could it be some version compatibility issue since the application was developed in previous version ? Or some other way to import it. Thanks!

**Comment by gsmithun4** [comment]
> Thanks, for the quick response!
> 
> Also, the same app is working in production but when I try to export > import the json to cloud getting the error `Could not import the app: Cannot read properties of undefined (reading 'options')` Could it be some version compatibility issue since the application was developed in previous version ? Or some other way to import it. Thanks!

Hi @prachi-sequoia , cloud in running on v2 and it supports imports only from ToolJet v2

**Comment by prachi-sequoia** [comment]
Hi @gsmithun4, in that case how do we run version 1 import ? Or some way out to transform the imported json to be compatible with v2 ?

**Comment by kavinvenkatachalam** [comment]
@prachi-sequoia Related to the tab issue - 

- Is it not working on both `Editor` and `Preview`? 
- Can you check the data that is passed while controlling the component? It should be the same data type that is being passed to the tab. For eg, if tabs data is 
`[{ title: 'Home', id: '0' }, 
		{ title: 'Profile', id: '1' }, 
		{ title: 'Settings', id: '2' }]` 
 then the ID passed in the control component should be string as attached in the screenshot.
 
<img width="335" alt="image" src="https://github.com/ToolJet/ToolJet/assets/50441969/e5570c10-081c-4ca5-abb9-b6adb724666f">

**Comment by prachi-sequoia** [comment]
Yes same behaviour in `editor` and `preview` mode. Also, the main thing is even the display components don't show up when I'm clicking on the tab (First tab is working fine, second tab is blank as shared in the screenshots in previous threads.)

<img width="1430" alt="image" src="https://github.com/ToolJet/ToolJet/assets/94529955/6e25e20f-b311-4941-b774-71c0d7e16bff">

**Tab 1:**
<img width="1318" alt="Screenshot 2023-06-02 at 4 34 44 PM" src="https://github.com/ToolJet/ToolJet/assets/94529955/335a78dc-e67c-4651-8445-38aef0a18edd">

**Tab 2:**
<img width="1464" alt="image" src="https://github.com/ToolJet/ToolJet/assets/94529955/eaefd02d-3a50-4cd4-8ec7-93d78d790b10">

**Comment by gsmithun4** [comment]
> Hi @gsmithun4, in that case how do we run version 1 import ? Or some way out to transform the imported json to be compatible with v2 ?

@prachi-sequoia can you please open the imported file and check if it starts with `appV2`

**Comment by prachi-sequoia** [comment]
> @prachi-sequoia can you please open the imported file and check if it starts with `appV2`

@gsmithun4 Since the file is exported from version `"1.26.1-ee1.5.1"`, it doesn't have appV2. Is there a way to transform the exported json to make it v2 compatible and make it run on Cloud ?

**Comment by gsmithun4** [comment]
> > @prachi-sequoia can you please open the imported file and check if it starts with `appV2`
> 
> @gsmithun4 Since the file is exported from version `"1.26.1-ee1.5.1"`, it doesn't have appV2. Is there a way to transform the exported json to make it v2 compatible and make it run on Cloud ?

Hi @prachi-sequoia , you have to setup version `1.26.1-ee1.5.1` and import app, then upgrade to latest v2 and export app
