### ISSUE TITLE
Dashboard- Logged in username initials are not displayed

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#477]
**Expected result:** 

- Log in to Tooljet.(Username- dev@tooljet.io)
- Dashboard should show initials 'TD' after fetching the same from DB. 

**Actual result:** 

- Username initials are not displayed on the Logout button. Coming blank as shown in the screenshot. 

<img width="1443" alt="Screenshot 2021-08-09 at 1 09 40 PM" src="https://user-images.githubusercontent.com/5313625/128673555-2dfe44bb-6e95-4596-b51c-ee9fd9c4dce3.png">

**Comment by sherfin94** [comment]
Thanks, I'll get this done today.
