### ISSUE TITLE
Ability to reference current row on tables

### ISSUE THREAD

**Issue by a-c-m** [ToolJet/ToolJet#4774]
### Is your proposal related to a problem?

For custom columns, it would be great to be able to use data from the current row. E.g. the table has first and last names, you want to make a full name.

### Describe the solution you'd like

Being able to do something like `"{{currentRow.firstName}} {{currentRow.lastName}}"` to generate a full name when the row already had first and last.

### Describe alternatives you've considered
None.

### If the feature is approved, would you be willing to submit a PR?
I would test it.

**Comment by withshubh** [comment]
Hey @a-c-m 
You can use transformations to just combine the `firstName` & `lastName` columns and create a new column `fullName`:

Try this:
```js
return data.map(row => ({
 fullName: row.firstName+ ' ' + row.lastName,
 ...row
}))
```

**Comment by a-c-m** [comment]
Thats a good work around thanks!

Other similar tools (appSmith) let you use it directly in the table as I indicated.

**Comment by withshubh** [comment]
Thanks for your feedback. We will look into it. 🙌
