### ISSUE TITLE
Dashboard- App creation date not readable

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#478]
**Expected result:**
App creation date should be displayed in a user-readable format.

**Actual result:**
App creation date coming as a string as shown in the screenshot below.

<img width="1317" alt="Screenshot 2021-08-09 at 1 20 48 PM" src="https://user-images.githubusercontent.com/5313625/128674673-15b790f8-e0e1-4c4e-bd1e-29659a3a6213.png">

**Comment by arpitnath** [comment]
taking this up
