### ISSUE TITLE
Table :: dragged column not sticking to cursor

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#4781]
### What is the expected behaviour?
Dragged column to stick to cursor

### What is the current behaviour?
Dragged column not sticking to cursor

### How to reproduce the issue?

1.Use table widget
2.Try dragging columns
3.Observe above issue

### Screenshots or Screencast

https://user-images.githubusercontent.com/31006028/202279152-2f3f2171-8e68-48ca-b479-769e1c96d8ed.mov

### Any possible solutions?
Implement a portal

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by prajval-tooljet** [comment]
this issue is fixed
