### ISSUE TITLE
DTO validation for version name validation

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4787]
### Is your proposal related to a problem?

The Version Name Validation should have a data transfer object.

### Describe the solution you'd like

Create a DTO ([example](https://github.com/ToolJet/ToolJet/blob/develop/server/src/dto/version-create.dto.ts)) for title length validation of the workspace

reference: https://github.com/ToolJet/ToolJet/pull/4612

**Comment by vedant-z** [comment]
Hi @withshubh May I try this?
Also if you could explain a little bit on what needs to be done it would be great.

**Comment by mikebarr24** [comment]
@withshubh If my current PR gets accepted, could you assign me to this. I think it's similar to what I've just submitted.
Thanks!

**Comment by withshubh** [comment]
Sure! @mikebarr24 - assigned the issue to you.
