### ISSUE TITLE
[docs]: fix the grammatical errors in localization doc

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4796]
### Summary

There are a few grammatical errors in the localization documentation.
Example: the note at the bottom of the page,

```
Feel free to reach out us on [Slack](https://tooljet.com/slack) for any help related with Localization.
```

It should be:
```
Feel free to reach us on [Slack](https://tooljet.com/slack) for any help related to Localization.
```

Please find all the errors on the page and create a PR.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/l10n

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by gogoiakash2311** [comment]
Can you assign this to me?

**Comment by withshubh** [comment]
> Can you assign this to me?

Hey @gogoiakash2311 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by gogoiakash2311** [comment]
I have made PR check #4800
