### ISSUE TITLE
Dashboard- Unable to delete app

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#480]
**Steps to recreate:** 
1. Log in to Tooljet.
2. Create an App.
3. Go to the dashboard and select the rightmost button on the app.
4. Select the 'Delete app' option.
5. Click on Yes.

**Expected result:**
Should be able to delete the app.

**Actual result:**
Throwing error message 'Could not delete app' as shown in the screenshot below.

<img width="1792" alt="Screenshot 2021-08-09 at 1 28 25 PM" src="https://user-images.githubusercontent.com/5313625/128675547-6bac9bc1-71b8-40d2-9849-8e16884b59a1.png">

**Comment by sherfin94** [comment]
Working on it :v:
