### ISSUE TITLE
fix typo on login page

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4805]
### What is the expected behaviour?

Currently. the text says `Don't have account yet? Sign up`

### What is the current behaviour?

The text should be `Don't have an account yet? Sign up`

### How to reproduce the issue?

1. Go to tooljet.com
2. click on sign in button

### Screenshots or Screencast

<img width="1438" alt="Screenshot 2022-11-20 at 9 30 25 AM" src="https://user-images.githubusercontent.com/25361949/202920568-4a61e7ca-975d-4ec0-aaba-9f43e93d6ce4.png">

**Comment by yajatvishwak** [comment]
I'm on it

**Comment by yajatvishwak** [comment]
#4807 check this out
