### ISSUE TITLE
Scrollbar for editor sidebar and queries tab 

### ISSUE THREAD

**Issue by Shelly011s** [ToolJet/ToolJet#4815]
### Is your proposal related to a problem?
The editor sidebar and Queries tab do not show the overflowing content.

### Describe the solution you'd like
There should be a scrollbar to show the rest of the content in the editor sidebar and Queries tab.

### If the feature is approved, would you be willing to submit a PR?
I will try to.
### Screenshot
![image](https://user-images.githubusercontent.com/84381373/203039985-0b2eabdb-a43f-428e-8b33-6c72f59ed047.png)

**Comment by withshubh** [comment]
Hey @Shelly011s - Can you please share the device and browser details?

**Comment by Shelly011s** [comment]
I am on Ubuntu 20.04.5 using chrome as a browser.

**Comment by withshubh** [comment]
Hey Shelly - In the screenshot you shared, the resolution doesn't seem valid. can you share the resolution?

Also, I tried the scroll seems to work fine on my end.

![scroll](https://user-images.githubusercontent.com/25361949/203241197-00949850-1072-475a-a199-8a2e8ccc206b.gif)

**Comment by Shelly011s** [comment]
The resolution I am working on is 1366*78(16:9).

**Comment by withshubh** [comment]
Hey @Shelly011s - Please check the screenshot, the resolution is the same as yours but the app editor fits well enough. 
Can you please check if the web page on the browser is not zoomed out more than 100%? Try adjusting the webpage using  `ctrl` + `-` and `ctrl` + `+` keys

<img width="1176" alt="Screenshot 2022-11-23 at 5 56 54 PM" src="https://user-images.githubusercontent.com/25361949/203547436-37961a84-46c5-4536-bff4-1ac4f5f4d013.png">

**Comment by withshubh** [comment]
Hey @Shelly011s - Closing this issue as we couldn't replicate the issue.
Feel free to open the issue if you have more information to share.
