### ISSUE TITLE
[ Bug ] : Canvas background color is not getting applied in the viewer mode

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#4816]
### Version Information
v1.29.0

### Environment
All

### What is the expected behaviour?
If we apply any color to the background of the canvas, it should persist in the viewer mode as well.

### What is the current behaviour?
The applied background color for the canvas is not persisting in the viewer mode

### How to reproduce the issue?

1. Create a new application or open an existing one
2. In the left sidebar, look for the Settings section, and click on it, a pop-up window will appear, displaying all the available settings.
3. From the options, that will be focusing on the background color, click on the field displaying the default color to open the color picker.
4. Choose any color from the picker, you can observe the background color of the canvas got changed to the applied color.
5. Now let's move on to the next phase, look for the preview button on the header section of the application, and click on it, to view the application in the viewer mode. After clicking on it, you will be redirected to a new tab, showing the application in viewer mode. As you can observe, the background color of the canvas is the default one, not the one which we applied in the editor mode. That's our problem statement. Whatever color we apply should persist in the viewer mode as well.

### Screenshots or Screencast
[ToolJet - Dashboard - 21 November 2022 - Watch Video](https://www.loom.com/share/5222e46564c34e7aaf0d0b47d7411cc2)

### Can you identify the location in the driver source code where the problem exists?
frontend > src > Editor > Viewer.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by withshubh** [comment]
Hey @shantanuSakpal - Thanks for your interest in contributing to ToolJet. The PR is already created for this issue. Please look for other open issues.
