### ISSUE TITLE
plugins.Dockerfile.dev does not contain tsc

### ISSUE THREAD

**Issue by frafra** [ToolJet/ToolJet#4822]
### Version Information
devel, 86917971a6fb12575c642fdff4e9d7725472eb3a

### Environment
Docker.

### What is the expected behaviour?
The container should start without errors

### What is the current behaviour?
tsc cannot start

### How to reproduce the issue?

1. Run the plugins container

### Any possible solutions?
Add typescript under `devDependency` in `plugins/package.json`?

### If the bug is confirmed, would you be willing to submit a PR?
Sure.

**Comment by frafra** [comment]
I added it and executed `npm lock`. I get a different error now:

```
tooljet-plugins-1   | packages/airtable/lib/index.ts(1,55): error TS2307: Cannot find module '@tooljet-plugins/common' or its corresponding type declarations.
tooljet-plugins-1   | packages/amazonses/lib/index.ts(1,55): error TS2307: Cannot find module '@tooljet-plugins/common' or its corresponding type declarations.
tooljet-plugins-1   | packages/appwrite/lib/index.ts(1,77): error TS2307: Cannot find module '@tooljet-plugins/common' or its corresponding type declarations.
[...]
```

I am not familiar with TypeScript, so I do not know how to proceed.

**Comment by frafra** [comment]
@akshaysasidrn I see that you created the `*.Dockerfile.dev` files. I wonder if you know more about these issues.

**Comment by adishM98** [comment]
Hi @frafra 

I tried to recreate the above issue with the steps above steps which you mentioned. But was not able to duplicate the issue. 

I verified using the latest develop branch and did not find any error. I have also attached the logs when use the command `docker-compose up`

`Os version: MacOs 13.0.1 (22A400) `

Here is my docker version: 

```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:41 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

[logs.odt](https://github.com/ToolJet/ToolJet/files/10228397/logs.odt)


unable to reproduce as well #4820

**Comment by adishM98** [comment]
i tried by newly cloning the develop branch. Could you try doing it once again, using a newly cloned develop branch.
