### ISSUE TITLE
vertical divider not visible when dropped on canvas

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4829]
### What is the expected behaviour?

Vertical divider, when dropped on the canvas, should have a default color, preferably black(`#000000`)

### What is the current behaviour?

Set the default color of the vertical divider component to black(`#000000`)

### How to reproduce the issue?

1. open the app editor
2. select a vertical divider from the widget sidebar and drop it on the canvas

### Screenshots or Screencast
<img width="311" alt="Screenshot 2022-11-22 at 5 04 06 PM" src="https://user-images.githubusercontent.com/25361949/203304791-9d2600d0-5a58-4031-bde9-ebc6c30ce19d.png">

**Comment by ishaanparlikar** [comment]
Can I take this ?

**Comment by withshubh** [comment]
> Can I take this ?

Sure @ishaanparlikar - Assigned it to you.

**Comment by ishaanparlikar** [comment]
Hi @withshubh 
Fixed the issue. Please have a look.
Thanks
