### ISSUE TITLE
change position of `cell background color` option in column properties

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4838]
### What is the expected behaviour?

`Cell background color` is not a conditional property so it should not be inside the `Validations` accordion

### What is the current behaviour?

Currently, when you edit the column property and when the `make editable` is turned on then the `cell background color` property goes inside the validations accordion.

Put the `cell background color` property above validations section

### How to reproduce the issue?

1. add table on the canvas
2. go to table properties, edit a column property
3. enable `make editable` and notice the `cell background color` property goes in validations

### Screenshots or Screencast
1. 
<img width="211" alt="Screenshot 2022-11-23 at 2 53 04 PM" src="https://user-images.githubusercontent.com/25361949/203511902-2ea9e61f-7267-4002-b49f-6c26785dca8d.png">

2. 
<img width="211" alt="Screenshot 2022-11-23 at 2 53 21 PM" src="https://user-images.githubusercontent.com/25361949/203511924-510e69af-83d5-4f0a-bb5c-4567c9a67f2d.png">

**Comment by ishaanparlikar** [comment]
Hi @withshubh Can you assign this to me ?

**Comment by withshubh** [comment]
Hey @ishaanparlikar - Another issue is already assigned to you, please create a PR for that: https://github.com/ToolJet/ToolJet/issues/4829

**Comment by withshubh** [comment]
Hey @ishaanparlikar - Assigned the issue to you.

**Comment by prithvi009** [comment]
Hey @withshubh Can I work on this issue?

**Comment by withshubh** [comment]
Hey @ishaanparlikar - Let me know if you're still working on it.
Else we can assign the issue to @prithvi009

**Comment by ishaanparlikar** [comment]
It is fixed. PR #4891
