### ISSUE TITLE
Page design performance Issue when having bunch of data

### ISSUE THREAD

**Issue by tuutoo** [ToolJet/ToolJet#4861]
### Version Information
v1.29.1
### Environment

Docker

### What is the expected behaviour?

Expect to limit the records show for debug purpose, or even just remove them if they are causing the performance issue.

### What is the current behaviour?

The page is getting stuck, very bad experience to continue the design. I have to change my query to limit the records or columns to let it get smooth, but after design, i need to change the query back.

### How to reproduce the issue?

1. Have over 16000 records
2. Over 70 columns
3. After the query runs, the page during design will stuck, very hard to design.

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/9068314/204444572-e255c77c-574e-4d27-97d8-9d42cff4ac28.png)

### Any possible solutions?
I hope the sample data can be restricted to only a few lines for programmer to continue the design. I don't want all the records show up during the design time.

The auto complete of each field/column is important to me, but those data/records are not that important for design, i think even remove them is also OK for me, reason is
1. I can see those records on the screen of my widget if the query is successful.
2. Actually as a program designer, I don't care those records show on the design page, I will debug them somewhere else. 

### If the bug is confirmed, would you be willing to submit a PR?
No. Sorry not familiar with React.

**Comment by withshubh** [comment]
Hey @tuutoo - Can you try using the `Server side pagination` option available in the Table component?

**Comment by tuutoo** [comment]
@withshubh I can not get result if using `Server side pagination`

![image](https://user-images.githubusercontent.com/9068314/204833539-bf1d065a-1fcd-4a07-b44e-ac78100b6830.png)

**Comment by tuutoo** [comment]
Switch "Server-side Pagination" I can get results, but the page design is slow.

![image](https://user-images.githubusercontent.com/9068314/204835462-be9fad34-0885-4d3a-98a1-48fe61e4fe05.png)

![image](https://user-images.githubusercontent.com/9068314/204835249-f7e2b0eb-698f-46ee-a755-231757907ca9.png)

**Comment by tuutoo** [comment]
Above is using Graphql, I also tested using MSSQL as below, the result is same.

Switch "Server-side Pagination" Option On, I can not get results.
![image](https://user-images.githubusercontent.com/9068314/204845757-1402270b-2882-4b95-afc1-f704102873c7.png)

Switch "Server-side Pagination" Option off, I can get results, page design is slow or unresponsive.
![image](https://user-images.githubusercontent.com/9068314/204846532-a6046119-57bf-466c-8586-52637a44495c.png)

**Comment by withshubh** [comment]
Hey @tuutoo 
Can you try this -  toggle on the server side pagination, decide on the page size (number of rows per page), and implement the query using `pageIndex` exposed by the table in such a way that, only the data required for the current page is fetched and displayed.

**Comment by tuutoo** [comment]
@withshubh 
Thanks for your reply.

I try to use select top 2 from my ms sql query (but still client-side pagination), then the page speed is OK. I believe use server side pagination will also speed up if it return small data, if the server side reponse data is big, the page may still be stuck.

So i think the problem is not about client-side or server-side, it should related to the reponse data size where used them.  

During design time, if some pop-up function need those data to auto-complete column name, suggest to use a small copy of the raw data, e.g. 1st record of raw data.  As those pop-up only need raw data's column/propeties, not all the values.

Those values are not helpful for page design.

**Comment by withshubh** [comment]
Hey @tuutoo - Thanks for the suggestions. I will discuss them with the team and see if we can improve it.

Closing the issue for now.
