### ISSUE TITLE
All API routes are 404ing on GKE deployment

### ISSUE THREAD

**Issue by minism** [ToolJet/ToolJet#487]
Hello!

I followed the instructions at https://docs.tooljet.io/docs/deployment/kubernetes to deploy tooljet to our GKE cluster.

The service is up and running and is responding as expected to the /health endpoint.  However all other endpoints the client is attempting to reach such as `/api/signup` and `/api/authenticate` are 404ing.

### Version Information
`tooljet/tooljet-server-ce:latest`

### Environment
Kubernetes

### What is the expected behaviour?
Routes the client talks to should not 404

### What is the current behaviour?
Routes the client talks to are 404ing

**Comment by akshaysasidrn** [comment]
@minism I was unable to replicate this. Could you kindly check again with the latest image?

**Comment by akshaysasidrn** [comment]
Please make use of the latest [deployment](https://raw.githubusercontent.com/ToolJet/ToolJet/main/deploy/kubernetes/deployment.yaml) manifest when you retry. Have opened an issue separately to fix this at the docs.
https://github.com/ToolJet/ToolJet/issues/553
