### ISSUE TITLE
[docs]:  add `cut` shortcut in keyboard shortcuts

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4886]
### Summary

We recently added a `cut` shortcut but it is missing from the `keyboard shortcuts` document.

Update the doc with `cut` shortcut details along with gif.

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/tutorial/keyboard-shortcuts

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Sheikh-JamirAlam** [comment]
I would like to contribute. Can you provide the gif to be added?

**Comment by Sheikh-JamirAlam** [comment]
@withshubh I already submitted a pull request. Will it be reviewed?

**Comment by Sheikh-JamirAlam** [comment]
@withshubh My pr shows "1 workflow awaiting approval" is there anything I need to do on my end?

**Comment by withshubh** [comment]
> @withshubh My pr shows "1 workflow awaiting approval" is there anything I need to do on my end?

Nope! it's fine. We will merge it soon.
