### ISSUE TITLE
[Table widget] Horizontal scroll missing for table widget

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#489]
### Version Information
Latest
### Environment
Docker

### What is the expected behaviour?
Table should have a horizontal scroll

### What is the current behaviour?
Table is missing a horizontal scroll

### How to reproduce the issue?
Add a table with a large number of keys

### Any possible solutions?
overflow-x: scroll [css]

**Comment by saideepesh000** [comment]
Hey @Navaneeth-pk , can I work on this ?

**Comment by Navaneeth-pk** [comment]
> Hey @Navaneeth-pk , can I work on this ?

Thanks for contributing! Assigned the issue.

**Comment by saideepesh000** [comment]
Hey @gondar00 , I think this is fixed now, can u confirm


![image](https://user-images.githubusercontent.com/43727167/129351400-9747ac3b-2f10-4c64-8ebe-8603540ca369.png)

**Comment by gondar00** [comment]
@saideepesh000 can you once tell me which browser is it? in my browser I am not able to see the scrollbar,,,

**Comment by saideepesh000** [comment]
> @saideepesh000 can you once tell me which browser is it? in my browser I am not able to see the scrollbar,,,

Oh, it's in Firefox
