### ISSUE TITLE
Dashboard- Apps view showing incorrect numbering on footer

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#492]
**Steps to recreate:**
1. Log in to Tooljet.
2. Create a few apps.
3. Check the page count on the footer.

**Expected**: 
The text should be 'Showing X to Y(Range of apps on the current page) of N(where N is the total number of apps ).
For eg. in the attached screenshot, it should show- Showing 1-3 of 3.

**Actual:**
Showing incorrect count. Kindly check the below SS.

<img width="1792" alt="Screenshot 2021-08-11 at 12 52 08 PM" src="https://user-images.githubusercontent.com/5313625/129009799-b7f77b77-fc7f-4a2d-b343-d0f1cb794597.png">

**Comment by kg-kartik** [comment]
Hey @Navaneeth-pk , Can I work on this issue?

**Comment by Navaneeth-pk** [comment]
Sure, assigned. Thanks for contributing!

**Comment by akshaysasidrn** [comment]
@kg-kartik picking this up as a priority, assigning it to myself
