### ISSUE TITLE
[Feature] :: Persisting old credentials while editing datasources

### ISSUE THREAD

**Issue by vjaris42** [ToolJet/ToolJet#4923]
### Is your proposal related to a problem?

When editing datasources even if the encrypted values have not been changed they get altered in the backend and this forces the user to enter secrets/credentials every time while saving or else the credentials will be replaced.

### Describe the solution you'd like

Have a placeholder for encrypted fields so that the user gets a sense of value being persisted and fix the mechanism on how/when the credentials are being updated

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by gsmithun4** [comment]
Duplicate https://github.com/ToolJet/ToolJet/issues/5007
