### ISSUE TITLE
[docs]: correct the command in testing doc

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4928]
### Summary

Go to the Headless mode in the Testing document, the command for `For running specific spec in headless mode, run for specific spec`:
```
npm run cy:run  --spec "cypress/e2e/dashboard/multi-workspace/manageSSO.cy.js
```
Update the command to:

```
npm run cy:run --  --spec "cypress/e2e/dashboard/multi-workspace/manageSSO.cy.js
```

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/testing

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by wrola** [comment]
Hi, assign me please to this issue.

**Comment by wrola** [comment]
@withshubh I don't have permission to create a new branch, can you grant me permission?

**Comment by withshubh** [comment]
> @withshubh I don't have permission to create a new branch, can you grant me permission?

Hey @wrola - You don't have to create the branch directly on this repository. You'll have to fork the ToolJet repo first and then make the changes on the forked repo, after that you can create a PR.

You can follow the steps here: https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md#we-use-github-flow-so-all-code-changes-happen-through-pull-requests

**Comment by withshubh** [comment]
This is fixed
