### ISSUE TITLE
Dashboard- Apps view page navigation not working

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#493]
Steps to recreate:
1. Log in to Tooljet
2. Create a few apps
3. Click on the left arrow of the navigation on the right side of the footer as highlighted in the first screenshot.

Expected: If it's on the first page the left arrow should be disabled. And for more pages, the navigation should work correctly.

Actual: The page is getting stuck on clicking left navigation on the first page. Should be able to navigate properly if more than one page.

<img width="1792" alt="Screenshot 2021-08-11 at 12 52 08 PM" src="https://user-images.githubusercontent.com/5313625/129011052-97945b25-14b9-479b-841c-a336c46a780c.png">

<img width="1769" alt="Screenshot 2021-08-11 at 3 31 50 PM" src="https://user-images.githubusercontent.com/5313625/129011101-b2c4189b-7f02-4708-a37f-bba03789eb06.png">

**Comment by kg-kartik** [comment]
Can i work on this issue?

**Comment by Navaneeth-pk** [comment]
> Hey @Navaneeth-pk , Can i work on this issue?

Sure, assigned.

**Comment by akshaysasidrn** [comment]
@kg-kartik reassigning and picking this up as a priority
