### ISSUE TITLE
[docs]: fix broken link in rethinkdb doc

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4934]
### Summary

In the description, there is an incorrect url:
```
ToolJet can connect to RethinkDB databases to read and write data. For more info visit::https://rethinkdb.com/api/javascript/.com/
```
Fix this to:

```
ToolJet can connect to RethinkDB databases to read and write data. For more info visit this [doc](https://rethinkdb.com/api/javascript).
```

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/rethinkdb

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by maddy020** [comment]
Please assign this issue to me
