### ISSUE TITLE
[docs]: fix broken image in airtable doc

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4935]
### Summary

The image is not being loaded due to the typo. 

```
<img className="screenshot-full" src="/img/datasource-reference/airtable/airtable_delee.png" alt="Delete airtable record" />
```

Make the `airtable_delee.png` to `airtable_delete.png`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/airtable/#deleting-a-record

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by maddy020** [comment]
Please assign this issue to me 
I have solved this issue and just going to create a PR

**Comment by maddy020** [comment]
I have created PR 
Please assign this to me

**Comment by withshubh** [comment]
Assigned to you - @maddy020
