### ISSUE TITLE
[docs]: fix the typo in how-to: use inspector

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4936]
### Summary

Go to the variable section, in the info block the link to `event handler` is broken. To fix it, just add `/` before the hyperlink.

P.s - The `how-to: use inspector` doc is still not deployed. To fix this you'll need to setup the `develop` branch locally

### Issue Type

Documentation bug

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by AAYUSH-droid** [comment]
Hey I would like to work on it.
Can you assign it to me? @withshubh

**Comment by withshubh** [comment]
Hey @AAYUSH-droid - Assigned this to you.

**Comment by withshubh** [comment]
Line number 103 of this file
- https://github.com/ToolJet/ToolJet/blob/develop/docs/docs/how-to/use-inspector.md

**Comment by AAYUSH-droid** [comment]
https://github.com/ToolJet/ToolJet/pull/4939#issue-1489971304
fixes #4939
