### ISSUE TITLE
Setup Email text indentation incorrect

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#494]
**Steps to recreate:** 
1. Launch Tooljet
2. Enter email and press Signup.

**Expected:** Correct indentation. No extra spaces.

**Actual:** Too many extra spaces and line breaks in salutation and body. Check SS below.

<img width="890" alt="Screenshot 2021-08-11 at 3 42 20 PM" src="https://user-images.githubusercontent.com/5313625/129012316-bbfd326d-b5d3-4e09-bf35-a609b41c156a.png">

**Comment by saideepesh000** [comment]
Hi @Navaneeth-pk , can I take this up ?

**Comment by Navaneeth-pk** [comment]
Thanks, assigned the issue. 

@saideepesh000
