### ISSUE TITLE
mutiselect component's option label doesn't update until selected

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4965]
### What is the expected behaviour?

The `option label` should reflect on the component as soon as the value is updated in the property

### What is the current behaviour?

The `option label` values doesn't reflects on the component until selected on the component

### How to reproduce the issue?

1. Add multiselect component on the canvas
2. update the `option label`
3. check the options on the component

### Screenshots or Screencast

https://user-images.githubusercontent.com/25361949/207298829-8ac7f188-6a06-4900-a254-a5eaefce5e26.mp4

**Comment by Budhathoki356** [comment]
I'd love to work on this. Can you assign this to me?

**Comment by withshubh** [comment]
Hey @Budhathoki356 - Assigned this to you. 🙌
