### ISSUE TITLE
`secondary text color` doesn't update when secondary sign display is changed to negative

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4969]
### What is the current behaviour?

In the Statistics component, when the `Secondary sign display` is set to `negative` the the secondary value and text changes to red color but when we go to `Styles` the `Secondary text color` is still set to green. It doesn't updates when the `Secondary sign display` is changed to `negative`

### What is the expected behaviour?

When the `Secondary sign display` is changed to `negative` the `Secondary text color` should update to red from green.

### How to reproduce the issue?

1. Add statistics component on the canvas
2. Set `Secondary sign display` to `negative`
3. Go to styles, and check the secondary text color

### Screenshots or Screencast

![tree-select](https://user-images.githubusercontent.com/25361949/207308279-bc7573a7-8808-410e-b103-b75e594fa2d9.gif)

**Comment by sloth30799** [comment]
Can I take this?

**Comment by withshubh** [comment]
> Can I take this?

Hey @sloth30799 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.
