### ISSUE TITLE
the `default value` of the date-picker doesn't update when a date is selected

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4971]
### What is the current behaviour?

Date-picker's default value doesn't updates when we manually select a date from the component

### What is the expected behaviour?

the `default value` field's value should update when the different date is selected on the component

### How to reproduce the issue?

1. Add date-picker on the canvas
2. open its properties on the right sidebar
3. now change the date from the date-picker and notice the default value remains the same

### Screenshots or Screencast

https://user-images.githubusercontent.com/25361949/207312045-37e4256c-fdd4-4fe1-8b70-33146f15ffa0.MP4

**Comment by DA-Mike** [comment]
I'd like to take a shot at this if it's still open.

**Comment by withshubh** [comment]
Hey @DA-Mike - Thanks for your interest in contributing to ToolJet. I have assigned the issue to you.

**Comment by Ubaid-Manzoor** [comment]
@shubh22 please assign to me if not already done.

**Comment by tejakummarikuntla** [comment]
Thanks for the interest, @Ubaid-Manzoor
Assigning this to you.

**Comment by withshubh** [comment]
Hey @Ubaid-Manzoor - Any update on the PR?
