### ISSUE TITLE
[number input] allows to set default value more than the max value

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4974]
### What is the current behaviour?

In number-input component, when we set the max value and then set the default value more than the max value the component allows it to be set.

### What is the expected behaviour?

Ideally when max value is set, user should not be able to set the default value > max value

### How to reproduce the issue?

1. Add number input component on the canvas 
2. set max value 2000
3. set default value 4000

### Screenshots or Screencast

https://user-images.githubusercontent.com/25361949/207323893-636468be-e479-4a59-81fa-57b5de780aa7.MOV

**Comment by harshmange44** [comment]
@withshubh Hey I would like to fix this.

**Comment by AldrinoS** [comment]
Hi @withshubh, I would like to work on this issue

**Comment by Aviroop-001** [comment]
I'd like to fix this issue. Please assign me the issue.

**Comment by shubh22** [comment]
Assigned to you, @Aviroop-001

**Comment by Ubaid-Manzoor** [comment]
@shubh22 Seem nobody has worked on it yet, please do assign it to me.

**Comment by Sonali-Behera** [comment]
Hey, I would love to work on this issue. Please assign this to me.

**Comment by withshubh** [comment]
Hey @Sonali-Behera - The PR for this issue is under review. We have already assigned an issue to you: https://github.com/ToolJet/ToolJet/issues/5981

**Comment by MajidBabaeifar** [comment]
If it's still open, I'm eager to fix it (¬_¬ )

**Comment by PriteshKiri** [comment]
Recreated the issue https://github.com/ToolJet/ToolJet/issues/10324

**Comment by PriteshKiri** [comment]
@MajidBabaeifar you can comment on https://github.com/ToolJet/ToolJet/issues/10324 if you are still interested in this issue.
