### ISSUE TITLE
Delete button in user group section not visible in dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4976]
### What is the expected behaviour?

The delete button should be visible in dark mode 

### What is the current behaviour?

The delete button is not clearly visible

### How to reproduce the issue?

1. Go to the manage groups from the dashboard
2. Open a group
3. switch to dark mode

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-11-28 at 4 29 32 PM" src="https://user-images.githubusercontent.com/25361949/207328715-971ec161-327a-4a30-84fd-853ac417b5b9.png">

**Comment by PrashantIndurkar** [comment]
Hi, I want to work on this I have seen this issue on-website. 
can anyone tell me the file structure  which file should i work on please guide me

**Comment by PrashantIndurkar** [comment]
hello, i found the file structure. now the question is what should be the colour of this button when use is using dark theme currently we have this styles to it 
```
.text-muted {
  color: #3e525b !important;
}
```

should i change this colour or i create new class and give new colour to this??

**Comment by withshubh** [comment]
> Hi, I would like to work on this issue I have seen this issue on-website. can someone tell me the file structure which file should I work on please guide me. kindly could you please assign me

@PrashantIndurkar - the issue is assigned to you.

**Comment by PrashantIndurkar** [comment]
Hello should i create new color p we have color palette or just change to visible colo??

**Comment by harsh472000** [comment]
@withshubh can you assign this task for me? i would like to work on that

**Comment by withshubh** [comment]
Hey @harsh472000 - I just checked on the ToolJet Cloud - the issue has been fixed by the team internally. I would request you to look for other open issues with the `good-first issue` or `up-for-grabs` label.
