### ISSUE TITLE
arrow to switch workspace is not clearly visible in dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4977]
### What is the current behaviour?

In light mode, the arrow to switch workspace is visible but when switched to dark mode the arrow is not clearly visible

### What is the expected behaviour?

The arrow should be visible in dark mode

### How to reproduce the issue?

1. Go to the tooljet dashboard
2. Open workspace menu from the navbar in light mode, 
3. you'll see an arrow to switch workspace
4. Switch to dark mode and the arrow wont be clear

### Screenshots or Screencast

https://user-images.githubusercontent.com/25361949/207338197-a159fccf-43ec-42a9-9f31-3b15b8c15e57.mov

**Comment by AAYUSH-droid** [comment]
I would like to work on this issue. Can i get assigned @withshubh

**Comment by withshubh** [comment]
> I would like to work on this issue. Can i get assigned @withshubh

Hey @AAYUSH-droid - Let's create the PR for the issue that is already assigned to you.

**Comment by mikebarr24** [comment]
@withshubh Would it be OK for me to work on this issue?

**Comment by withshubh** [comment]
> @withshubh Would it be OK for me to work on this issue?

Sure @mikebarr24 - Assigned to you.

**Comment by withshubh** [comment]
Closing as the issue is fixed
