### ISSUE TITLE
able to delete the only version in the app

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4978]
### What is the current behaviour?

Currently, when there is only single version on the app, we are able to delete it.

### What is the expected behaviour?

Ideally, the user should not be able to delete the last/only version in the app

### How to reproduce the issue?

1. Create an app with a version
2. delete the version from the version manager

### Screenshots or Screencast

https://user-images.githubusercontent.com/25361949/207345333-5ef2bb3f-9720-4e4b-827e-c7c1b0ea77bc.mov

**Comment by mikebarr24** [comment]
@withshubh Could I take a look at this issue?

**Comment by mikebarr24** [comment]
@withshubh Could I take a look at this issue? Could you assign it to me. 
Thanks

**Comment by withshubh** [comment]
> @withshubh Could I take a look at this issue? Could you assign it to me. Thanks

Sure @mikebarr24 - Assigned to you.
