### ISSUE TITLE
[docs]: Imporve custom JS query `INFO` section 

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#4987]
### Summary

The `INFO` section of the "Create a custom JS query" is missing to mention about updating the table name in the code snippet.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/how-to/bulk-update-multiple-rows#5-create-a-custom-js-query

### Steps to reproduce the issue

A line from the code snippet.
```
const cols = Object.values(components.table1.changeSet).map((col, index) => {
```
the `table1` is taken as an example, It would be good to mention updating the table1 with the uses in the INFO section below

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by wrola** [comment]
Please assign to me

**Comment by withshubh** [comment]
Assigned to you @wrola

**Comment by tejakummarikuntla** [comment]
Unassigned due to the inactivity of the contributor.

**Comment by krimoelbahri** [comment]
Hi, can i work on this issue

**Comment by withshubh** [comment]
Hey @krimoelbahri - Assigned the issue to you.
