### ISSUE TITLE
Multi level json data, table display

### ISSUE THREAD

**Issue by Avey777** [ToolJet/ToolJet#5005]
I hope that the json data returned by the following api can be processed into the table below. Does ToolJet support it? I tried many times without success

`{
    "success": true,
    "base": "GHS",
    "rates": {
        "2022-12-15": {
            "AED": 0.403447,
            "AFN": 9.556748,
            "ALL": 11.808015,
            "AMD": 43.308356,
            "ANG": 0.198057,
            "AOA": 55.406054,
            "ARS": 18.929951
        },
        "2022-12-16": {
            "AED": 0.410378,
            "AFN": 9.720288,
            "ALL": 12.09449,
            "AMD": 44.182554,
            "ANG": 0.201421,
            "AOA": 56.352001,
            "ARS": 19.266475
        },
        "2022-12-17": {
            "AED": 0.406725,
            "AFN": 9.710817,
            "ALL": 11.951775,
            "AMD": 43.921728,
            "ANG": 0.200244,
            "AOA": 55.85256,
            "ARS": 19.095719
        }
    }
}`

Expected results
![image](https://user-images.githubusercontent.com/35259040/208304787-aa8d6d94-ee94-4865-ac51-febac7ba9baf.png)

**Comment by withshubh** [comment]
Hey @Avey777 
Thanks for creating the feature request. To show the unstructured data you will have to use the `Transformations` using JS/Python to transform the data into the array of objects which is required by the table component.

We are closing the issue for now. Please feel free to join our [slack community](https://www.tooljet.com/slack) if you have any questions.
