### ISSUE TITLE
Cant seed data

### ISSUE THREAD

**Issue by thephilluk** [ToolJet/ToolJet#506]
### Environment

Tooljet latest, Docker version 20.10.6, build 370c289, docker-compose version 1.29.1, build c34c88b2, Ubuntu 18.04.5 LTS
### What is the expected behaviour?

running `docker-compose run server npm run db:seed` which will put standard login data in the database

### What is the current behaviour?

running `docker-compose run server npm run db:seed` throws this error message:
```
theph@mainserver:~/tooljet$ sudo docker-compose run server npm run db:seed
Creating tooljet_server_run ... done
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /app/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### How to reproduce the issue?

1. do a clean install using the docker method and the versions stated above.
2. change the ports from standard to 8001 & 8002
3. run the seeding command

**Comment by thephilluk** [comment]
Hey @akshaysasidrn, any updates on this?

**Comment by drdee** [comment]
I am running into the same issue as well.

**Comment by akshaysasidrn** [comment]
Hey folks, the WORKDIR is not set properly at the dockerfile. You can therefore run it likewise for now:
`docker-compose run server npm run db:seed --prefix server`

**Comment by akshaysasidrn** [comment]
Hey folks, please use this command instead: 
`docker-compose run server npm run db:seed --prefix server`

We had missed to update the workdir accordingly at the dockerfile. Keeping the issue open until dockerfile or docs is updated for this.
