### ISSUE TITLE
[icon component] cursor should become pointer when `onClick` event handler is added

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5066]
### What is the current behaviour?
When an onClick event is added to the icon component, the cursor doesn't change to a pointer which doesn't make it clear to the user that action can be performed on clicking the icon.

### What is the expected behaviour?
When an onClick event handler is added to the icon component, the cursor should become a pointer on hovering the icon so that it is apparent to the user that the action can be performed on clicking.

### How to reproduce the issue?

1. Add an icon component
2. Add an onClick event handler to icon
3. Preview the app and hover over the icon 

### Screenshots or Screencast
![Dec-27-2022 15-16-49](https://user-images.githubusercontent.com/25361949/209647921-60c37e2f-d691-4f5e-9002-39d9a497740d.gif)

**Comment by maddy020** [comment]
Hey @withshubh 
I would like to work over this issue 
Please give me some info on which page this issue occurs

**Comment by withshubh** [comment]
> Hey @withshubh I would like to work over this issue Please give me some info on which page in the site this issue occurs

Hey @maddy020 - 
- Sign in to [ToolJet](https:///www.tooljet.com)
- create new app
- drag icon component on the canvas
- Add an onClick event handler to icon
- Preview the app and hover over the icon

**Comment by ayobamiseun** [comment]
can i work on this

**Comment by Navaneeth-pk** [comment]
@ayobamiseun assigned to you.

**Comment by withshubh** [comment]
Hey @maddy020 - Are you still working on this issue?

**Comment by maddy020** [comment]
No I am not 
I am sorry for not giving any update

**Comment by withshubh** [comment]
Hey @ayobamiseun - Assigning this issue to you.

**Comment by Aviroop-001** [comment]
I'd like to work on the issue. Assign it to me if still not fixed.

**Comment by shauryag2002** [comment]
I'd like to work on the issue. Assign it to me if still not fixed. I can fix it quickly enough.

**Comment by shubh22** [comment]
Assigning to @shauryag2002

**Comment by Sonali-Behera** [comment]
Hey, is this issue is still open ??  Would love to work on this. If this is open, and no one is assigned for the moment then please assign this to me.

**Comment by withshubh** [comment]
> Hey, is this issue is still open ?? Would love to work on this. If this is open, and no one is assigned for the moment then please assign this to me.

Hey @Sonali-Behera - The issue is assigned and the PR is under review, you'll find it on the right side under the `Assignees` and `Development` sections.
We have assigned another issue to you: https://github.com/ToolJet/ToolJet/issues/5981
