### ISSUE TITLE
[docs]: update the border radius of search bar

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5074]
### Summary

Currently, the search bar on the documentation website is too rounded.
Update the border radius of the search bar to `5px` to align with the ToolJet design.

<img width="300" alt="Screenshot 2022-12-28 at 1 42 26 PM" src="https://user-images.githubusercontent.com/25361949/209780487-6aabd580-0ad8-4b50-9a96-a69ddc5fe362.png">

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs

### Steps to reproduce the issue

1. Open Docs
2. Check the search bar on top-left

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by maddy020** [comment]
It is already 5px

**Comment by withshubh** [comment]
> It is already 5px

This is a closed(already fixed) issue @maddy020
