### ISSUE TITLE
Homepage overflow horizontal scroll on https://tooljet.io/

### ISSUE THREAD

**Issue by jaydeepkhatri** [ToolJet/ToolJet#508]
### What is the expected behaviour?
There should be no overflow scroll on horizontal 

### What is the current behaviour?
Problem with overflow

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/29619945/129307796-7bf4dcff-336d-485a-ba92-f6055f5d4dfc.png)

### Any possible solutions?
By removing the `--bs-gutter-x` property from `.row` class

![image](https://user-images.githubusercontent.com/29619945/129308082-842d9b74-784e-4d21-a342-51c115c9df06.png)

### Can you identify the location in the driver source code where the problem exists?
SCSS partials >` _grid.scss` > line 6

### If the bug is confirmed, would you be willing to submit a PR?
Yes, but couldn't find the code in repo

**Comment by Navaneeth-pk** [comment]
@jaydeepkhatri 

thanks for reporting the issue. The website is a private repo for now. Noted down the issue, will fix it soon. Closing this issue as this is not related to ToolJet app.
