### ISSUE TITLE
QR Reader widget

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#509]
We need a widget that can

- Use the user's camera to scan and detect QR codes
- Store the data contained in the QR and make it available to be referred from elsewhere

**Comment by sherfin94** [comment]
I'm working on this.

**Comment by Navaneeth-pk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QR scanner widget](https://trello.com/c/BK1MkBwM/24-qr-scanner-widget)
