### ISSUE TITLE
[docs] resize `Search` text on search bar

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5101]
### Summary

Currently, the search text on the search bar of the documentation is a bit large.
Its current value is `1rem `
set it to `0.85rem`

<img width="300" alt="Screenshot 2022-12-28 at 1 42 26 PM" src="https://user-images.githubusercontent.com/25361949/209780487-6aabd580-0ad8-4b50-9a96-a69ddc5fe362.png">

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs

### Steps to reproduce the issue

1. Open Docs
2. Check the search bar on top-left

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by rhinoxD** [comment]
!assign

**Comment by Aashish-Upadhyay-101** [comment]
I will fix this search text size

**Comment by pankajkrbansal** [comment]
!assign

**Comment by AAYUSH-droid** [comment]
Would like to work on this issue can i get assigned!

**Comment by withshubh** [comment]
The issue is up for grab now.

**Comment by AAYUSH-droid** [comment]
@withshubh can i get assigned?

**Comment by withshubh** [comment]
Sure @AAYUSH-droid - assigned the issue to you

**Comment by asma-mughal** [comment]
can I work with you on this issue, since I am new to open source contributions. @AAYUSH-droid

**Comment by withshubh** [comment]
> can I work with you on this issue, since I am new to open source contributions. @AAYUSH-droid

Hey @asma-mughal - This issue is already assigned to someone. Please look for other open good-first-issue that are not assigned to anyone.

**Comment by AAYUSH-droid** [comment]
@withshubh Unable to find the Search Placeholder.Can you link me the file.

**Comment by tejash023** [comment]
hi @withshubh  Can I work on this?

**Comment by withshubh** [comment]
Hey @tejash023 - Assigned it to you.

**Comment by krimoelbahri** [comment]
hi can i work on this

**Comment by Ponnada96** [comment]
Hi @withshubh ,
I can fix this issue, Can you please assign it to me.

**Comment by tejakummarikuntla** [comment]
Hey @Ponnada96 , were you able to progress with the issue?

**Comment by Ponnada96** [comment]
Hi @tejakummarikuntla , will raise the PR by tomorrow EOD.

**Comment by JunedKhan101** [comment]
Hi, I would like to take this up. Kindly assign this task to me.

**Comment by ishsarin** [comment]
Hi, if this issue is open could I contribute?

**Comment by tejakummarikuntla** [comment]
Hey @JunedKhan101 , @ishsarin since there's already an issue assigned to you, let's wait to welcome first time contributors like yourself.

**Comment by vishalbalani** [comment]
I would like to work on this issue, kindly assign task to me.

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @vishalbalani. Assigned the issue to you.

**Comment by Brag2gr8** [comment]
assign to me

**Comment by tejakummarikuntla** [comment]
Unassigning @vishalbalani due to inactivity.
@Brag2gr8 , would you be interested in taking this up?

**Comment by Brag2gr8** [comment]
@tejakummarikuntla yes, you can assign to me

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @Brag2gr8. Assigned the issue to you.

**Comment by Brag2gr8** [comment]
@tejakummarikuntla here is my PR #7432
