### ISSUE TITLE
Change the editor look and feel

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#511]
### Is your proposal related to a problem?
This Proposal is in regards with having a smaller left sidebar for displaying `inspector`, `datasources` a `debugger` (future), `back` occupying around 3% space of the available viewport, 

An example of the suggested change can be found in below image:

![image](https://user-images.githubusercontent.com/12490590/129313821-9dd6a7ca-a9c2-4942-9d78-242f8c5ac3d5.png)

The idea is to have a simplistic UI with focus on utilizing proper available space and having a better UX overall. 

Any changes/opinions are welcome

**Comment by Navaneeth-pk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Left sidebar redesign](https://trello.com/c/i2VMK96o/22-left-sidebar-redesign)
