### ISSUE TITLE
Change onboarding email label in signup from `work email` to ` email`

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#5125]
### What is the expected behaviour?
`Work email` to be changes as `Email`  in every onboarding screen and user invite screens
### What is the current behaviour?
Its mentioned as work email in every onboarding screen and user invite screens where user email is to be entered as `Work email`

### How to reproduce the issue?

1.Check on onboarding screens where email is asked from users

### Screenshots or Screencast

<img width="454" alt="Screenshot 2023-01-02 at 10 31 55 AM" src="https://user-images.githubusercontent.com/31006028/210196457-b906dcac-296d-4c96-a282-7d60bcc5db27.png">

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by TheLearneer** [comment]
Hi @stepinfwd 👋 
I believe the issue has been resolved and can be closed? 🙇

**Comment by withshubh** [comment]
Thanks, @TheLearneer
