### ISSUE TITLE
[docs]: fix the widgets description at the bottom of this page

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5138]
### Summary

Current description Widgets is:
```
UI components such as tables, buttons, dropdowns.
```

Correct description for widgets:
```
UI components such as tables, buttons, and dropdowns etc.
```

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/tutorial/creating-app/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by prateekchaplot** [comment]
Hi! I'd like to take up this issue, as it is marked as "good first issue", if possible.

**Comment by prateekchaplot** [comment]
Hi! I'd like to take up this issue, as it is marked as "good first issue", if possible.

**Comment by sajdakabir** [comment]
@withshubh can i work on this?

**Comment by withshubh** [comment]
Hey @sajdakabir - Thanks for showing interest in contributing to ToolJet.
Assigned the issue to you.

We recently added versioning to our documentation and this doc is part of v1. So, you'll need to make the change in this file:
- https://github.com/ToolJet/ToolJet/blob/develop/docs/versioned_docs/version-1.x.x/tutorial/creating-app.md

**Comment by sajdakabir** [comment]
@withshubh can you please check the PR?
