### ISSUE TITLE
[docs]: redirect to `develop` branch rather than `main` when clicked on `edit this page`

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5150]
### Summary

There is an option to edit the doc directly on GitHub by clicking on `Edit this page` button at the bottom of every doc.
Currently, clicking that button opens up the doc on the `main` branch.
Fix it to open up the doc on `develop` branch.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/

### Additional Information

Fix: just update the `main` to `develop` in docusauras config file

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Jittojoyes98** [comment]
Can I work on this issue

**Comment by withshubh** [comment]
> Can I work on this issue

Hey @Jittojoyes98 - Thanks for showing interest in contributing to ToolJet.
Assinged to you.

**Comment by withshubh** [comment]
Hey @Jittojoyes98 
All you need to do is just remove the `main` in editurl and make it `develop` in line number 118 here:
https://github.com/ToolJet/ToolJet/blob/develop/docs/docusaurus.config.js#L118

**Comment by harshmange44** [comment]
@withshubh Hey, I'd like to fix this issue.

**Comment by withshubh** [comment]
Hey @harshmange44 - The issue is already assigned to @Jittojoyes98

**Comment by TheLearneer** [comment]
@withshubh this issue seems to be fixed.

- <https://github.com/ToolJet/ToolJet/blob/develop/docs/docusaurus.config.js#L128>

**Comment by withshubh** [comment]
Hey @TheLearneer - Thanks :D
