### ISSUE TITLE
SMTP datasource: rename the `user` to `username` in connection modal

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5152]
### What is the problem?

Currently, the `Username` field is set as `User` in the connection modal of the SMTP datasource. Rename the `User` to `Username` to fix it.

### How to reproduce the issue?

1. Create new app in ToolJet
2. Add SMTP datasource
3. In the connection modal, the user field should be username

### Screenshots or Screencast
![Screenshot 2023-01-03 at 10 46 32 AM](https://user-images.githubusercontent.com/25361949/210303801-265c80c2-d210-4603-8841-21c2788488a1.png)

**Comment by TheLearneer** [comment]
Hi @withshubh 👋 
I would love to pick it up if it's `up for grabs`

**Comment by harshmange44** [comment]
@withshubh Hey, I'd like to work on this.

**Comment by withshubh** [comment]
Hey @TheLearneer - Assigned this to you.

**Comment by Vansh-Baghel** [comment]
@withshubh Hey, could you assign it to me? I could fix it.

**Comment by TheLearneer** [comment]
Hey @withshubh 👋 
The PR fixing this issue has been merged, I believe we are good to close this issue.
