### ISSUE TITLE
Docker compose setup from documentation fails.

### ISSUE THREAD

**Issue by Oreilles** [ToolJet/ToolJet#518]
**Version:** latest to date

**Environment:** Docker (compose)

**How to reproduce the issue**

* From the [docs](https://docs.tooljet.io/docs/deployment/docker), download the `docker-compose.yml` and `.env` file fill them properly.
* Run `docker compose up`
* Going to client host, the main page stays in a loading state, with three identical error messages in the console:

```
{
  "error": "ENOENT: no such file or directory, stat '/app/frontend/build/index.html'",
  "data": {
    "statusCode": 404,
    "message": "ENOENT: no such file or directory, stat '/app/frontend/build/index.html'"
  }
}
```

Looking back at the server, it errors with:
```
[Nest] 27 - 08/13/2021, 8:04:03 PM ERROR [ExceptionsHandler] ENOENT: no such file or directory, stat '/app/frontend/build/index.html'
```

**Any possible solutions?**

I suppose the docs are not up to date.

**Comment by joaodubas** [comment]
@Oreilles I changed the server image from `tooljet/tooljet-server-ce:latest` to `tooljet/tooljet-ce:latest`. Aparently the server also delivers the static content from the frontend.

**Comment by Navaneeth-pk** [comment]
@Oreilles @joaodubas 

This issue will be fixed soon, until then, a quick fix/hack is to either create an empty `index.html` under `frontend/build` directory or  run `npm build --prefix frontend` from the root directory. Apologies for the inconvenience.
