### ISSUE TITLE
Add a search bar on docs

### ISSUE THREAD

**Issue by apoorv1316** [ToolJet/ToolJet#521]
Feature: Add a search bar on the documentation site to search the keywords or content

**Comment by Navaneeth-pk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Search feature for documentation](https://trello.com/c/wqljm7ew/30-search-feature-for-documentation)

**Comment by Jassi10000** [comment]
I don't think this needs additional feature
you can use Ctrl + F to search for any keywords

**Comment by Navaneeth-pk** [comment]
This feature is for a global search and not to search within a page. @Jassi10000

**Comment by Jassi10000** [comment]
Then its cool to implement 
Go on @apoorv1316 🤘

**Comment by trevorbayless** [comment]
:+1: This would be very useful.

I've looked into this and it seems very straightforward. However, the website owner has to be the one to put in the request to [DocSearch](https://docsearch.algolia.com/apply/)

The steps to enabling the search bar in Docusaurus are here: https://v1.docusaurus.io/docs/en/search

I'd be more than willing to take on this issue, but the website owner first has to obtain the `siteConfig.js` from DocSearch.

**Comment by Navaneeth-pk** [comment]
We were trying to implement a search using Typesense. Here is the PR: https://github.com/ToolJet/ToolJet/pull/635 ( we had to close it as the author did not have the bandwidth to finish it, also it was taking more time than expected due to some issues ).

Let me take a look at DocSearch, I think Typesense is also using the same under the hood.

@trevorbayless

**Comment by trevorbayless** [comment]
> We were trying to implement a search using Typesense. Here is the PR: #635 ( we had to close it as the author did not have the bandwidth to finish it, also it was taking more time than expected due to some issues ).
> 
> Let me take a look at DocSearch, I think Typesense is also using the same under the hood.
> 
> @trevorbayless

Thanks - please get back with me when you have some more information (or the `siteConfig.js`) and I can get things hooked up.

**Comment by withshubh** [comment]
@Navaneeth-pk picking up the issue

**Comment by withshubh** [comment]
- https://github.com/ToolJet/ToolJet/pull/3134
