### ISSUE TITLE
Improve application logging for production

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#522]
Currently, logging is very basic and doesn't help in tracking down or filtering requests through logs.
Make use of Winston (suggested at Nestjs docs) or any other logging library to be added at our application middleware.  
https://docs.nestjs.com/techniques/logger#use-external-logger

**Comment by gondar00** [comment]
https://www.papertrail.com/blog/best-practices-for-logging-in-nodejs/

winston+papertrail is a combination i can suggest
