### ISSUE TITLE
npm install is failing

### ISSUE THREAD

**Issue by thangaraja** [ToolJet/ToolJet#5220]
### Version Information
1.31.2

### Environment
Windows 10 with Node 16.18.1

### What is the expected behaviour?

npm install should install all the packages. 

### What is the current behaviour?

npm install is throwing the below error

npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-native@0.70.6
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"16.8.x" from react-konva@16.8.6
npm WARN   node_modules/react-konva
npm WARN     peer react-konva@"^16.8.0  || ^17.0.0" from @react-spring/konva@9.2.4
npm WARN     node_modules/@react-spring/konva
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"18.1.0" from react-native@0.70.6
npm WARN node_modules/react-native
npm WARN   peer react-native@">=0.58" from @react-spring/native@9.2.4
npm WARN   node_modules/@react-spring/native
npm WARN   1 more (@react-three/fiber)
npm WARN
npm WARN Conflicting peer dependency: react@18.1.0
npm WARN node_modules/react
npm WARN   peer react@"18.1.0" from react-native@0.70.6
npm WARN   node_modules/react-native
npm WARN     peer react-native@">=0.58" from @react-spring/native@9.2.4
npm WARN     node_modules/@react-spring/native
npm WARN     1 more (@react-three/fiber)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-select-search@3.0.5
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"16.8.x" from react-konva@16.8.6
npm ERR!   node_modules/react-konva
npm ERR!     peer react-konva@"^16.8.0  || ^17.0.0" from @react-spring/konva@9.2.4
npm ERR!     node_modules/@react-spring/konva
npm ERR!       @react-spring/konva@"~9.2.0" from react-spring@9.2.4
npm ERR!       node_modules/react-spring
npm ERR!         react-spring@"^9.2.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from react-select-search@3.0.5
npm ERR! node_modules/react-select-search
npm ERR!   react-select-search@"^3.0.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.1" from react-select-search@3.0.5
npm ERR!   node_modules/react-select-search
npm ERR!     react-select-search@"^3.0.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\tst\AppData\Local\npm-cache\eresolve-report.txt for a full report.

### How to reproduce the issue?

1. Get the latest source and extract
2. navigate to frontend folder
3.run the command **npm i**

**Comment by withshubh** [comment]
Closing this issue.
Feel free to join our [Community Slack](https://www.tooljet.com/slack) if you have any problem setting up ToolJet.
