### ISSUE TITLE
[refactor]: Improvise validation on Create account page

### ISSUE THREAD

**Issue by Madhavkabra** [ToolJet/ToolJet#5289]
### What area of the codebase is to be refactored?

API calls are made for every click on the created account in input fields. Validation is done at backend level, which should be done at frontend level to make it work super fast. Once all the frontend validation passes then a single api call should be made.

### What are the potential advantages of this proposed refactoring?

Faster sign up process since the user doesn't have to wait for network call to see error messages

### Screenshot

![Screenshot 2023-01-10 193953](https://user-images.githubusercontent.com/36595067/211727066-8dd5528c-2ed5-4bd2-8be1-b1d87a680ff3.png)

**Comment by withshubh** [comment]
Hey @Madhavkabra - Thanks for creating the issue. We'll take a look into it.
