### ISSUE TITLE
Preview, release and share tutorial freezes screen because of an overlay with high zIndex

### ISSUE THREAD

**Issue by Madhavkabra** [ToolJet/ToolJet#5290]
### Environment
Tooljet windows web app (https://app.tooljet.com/)

### What is the expected behavior?
After a signup, during the first session when this tutorial in below screenshot pops up, If the user clicks on previous next or skip the overlay should be gone and user must be able to proceed.

### What is the current behaviour?
If the user clicks on previous next or skip the overlay doesn't disappear and user is not able to click anywhere.

### How to reproduce the issue?

1. Signup
2. Start using app
3. Tutorial pops up
4. User freezes at review, release and share step

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/36595067/211728163-8e5fe9fb-4bb7-401f-ae66-378832a132d1.png)

### Any possible solutions?
zIndex of the overlay doesn't allow any user clicks (Even the skip and previous buttons have lower zIndex than overlay, hence they are not clickable). 

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by withshubh** [comment]
Hey @Madhavkabra - Our team was not able to replicate the bug.
Closing the issue now - feel free to open it again if you thing the bug is still there.
