### ISSUE TITLE
[user management] no way to edit information for an existing user

### ISSUE THREAD

**Issue by Gabuzomeuh67** [ToolJet/ToolJet#5296]
in case of mistyping on one's name or even swap between field contents, there is no way to edit the first name and last name for a given user

morever,  there is no way to easily get the groups a user belongs to.

**Comment by ajith-k-v** [comment]
Hey @Gabuzomeuh67, The user can update their details on the profile settings page.
![Screenshot 2023-01-13 at 12 25 22 PM](https://user-images.githubusercontent.com/20367957/212257115-06f767d0-4846-4528-8d19-91dfdf0c0c27.png)

**Comment by Gabuzomeuh67** [comment]
thanks for the feedback, I meant in the admin view

**Comment by thehacklady** [comment]
@Gabuzomeuh67 yeah, got your point. We don't have that functionality yet. We are planning to work on this in future, will update once we have it! I hope this helps :)
