### ISSUE TITLE
Not able to  complete onboarding process in firefox browser

### ISSUE THREAD

**Issue by stepinfwd** [ToolJet/ToolJet#5303]
### Version Information
Firefox browser

### What is the expected behaviour?
Users to be able to signup in any browser

### What is the current behaviour?
on last step of signup after submission it goes to invalid screen

### How to reproduce the issue?
1.Try signup in a firefox browser

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by dynamicdoyle** [comment]
I'm still not able to. I get the following error whether I sign up via email or Github. 

Token expired.

Invalid verification link

This verification link is invalid.
