### ISSUE TITLE
PostgreSQL not working as datasource

### ISSUE THREAD

**Issue by joaolessab** [ToolJet/ToolJet#5305]
I cannot connect any PostgreSQL as a datasource at all **(even after testing the connection and getting "Connection Verified" message):**

<img width="288" alt="Screenshot 2023-01-11 at 17 34 03" src="https://user-images.githubusercontent.com/21973502/211912056-4e33a7b2-0084-420f-993c-f4b86032db71.png">

The same happens with the official examples from ToolJet. They cannot retrieve any information from their own sample PostgreSQL Databases as well:

<img width="881" alt="Screenshot 2023-01-11 at 17 33 03" src="https://user-images.githubusercontent.com/21973502/211912181-b6f99a8e-70b8-4134-a699-7064f0a23510.png">

___________________________________________________________________________________________

**REPRODUCING THE ERROR:**

1. Open the Tool Jet website app: https://app.tooljet.com/
2. Create your account
3. Create your first app based on a Template using PostgreSQL:
(Choose from template)

<img width="474" alt="Screenshot 2023-01-12 at 09 10 08" src="https://user-images.githubusercontent.com/21973502/212065123-2ac23741-aabb-4d07-a55c-ce718e5dd72a.png">

4. All Categories >> Customer Dashboard (using a PostgreSQL sample DB):

<img width="980" alt="Screenshot 2023-01-12 at 09 10 18" src="https://user-images.githubusercontent.com/21973502/212065450-f1ce1cb4-25ea-4985-87c1-264439a51749.png">

5. Right when you app the app, an **INTERNAL ERROR** message pops-up, saying that the query of the tables created could not be loaded. If you also try to execute the Query, it won't work at all:

<img width="1052" alt="Screenshot 2023-01-12 at 09 11 00" src="https://user-images.githubusercontent.com/21973502/212065626-b1ed0e32-2331-4953-bfd9-573b3109a6e2.png">

6. I've added a Database hosted on Heroku, which it's working normally (I'm using its tables on Budibase CMS to create some screens as well) and I see this message, saying that the connection is okay and verified:

<img width="288" alt="Screenshot 2023-01-11 at 17 34 03" src="https://user-images.githubusercontent.com/21973502/211912056-4e33a7b2-0084-420f-993c-f4b86032db71.png">

7. When I try to execute a simple command, like `select * from Classes` or even `show tables`, the Tool Jet interface throws back again the message: **"INTERNAL SERVER ERROR"** and the console log says this:

<img width="509" alt="Screenshot 2023-01-12 at 09 28 33" src="https://user-images.githubusercontent.com/21973502/212066643-7401619c-186c-499a-ba59-9cdc6fef4a63.png">

**Obs. Nothing wrong with my browser, I also tried on another computer using Chrome**

**Comment by tmstieff-heaven** [comment]
Same issue, seems the password changes after clicking save on the modal, possibly due to the encryption.

**Comment by emidhun** [comment]
Hey @joaolessab 
Currently, we are not able to reproduce the issue.
Could you please share more information about this?
<img width="694" alt="Screenshot 2023-01-12 at 4 02 40 PM" src="https://user-images.githubusercontent.com/20367955/212044105-cee0c632-2d7a-4ff9-9ac8-01d35f6c7d11.png">

**Comment by gsmithun4** [comment]
Hi @joaolessab Please make sure that you have created and trying out the data source in same environment

**Comment by joaolessab** [comment]
> Hey @joaolessab Currently, we are not able to reproduce the issue. Could you please share more information about this? <img alt="Screenshot 2023-01-12 at 4 02 40 PM" width="694" src="https://user-images.githubusercontent.com/20367955/212044105-cee0c632-2d7a-4ff9-9ac8-01d35f6c7d11.png">

**REPRODUCING THE ERROR again:**

1. Open the Tool Jet website app: https://app.tooljet.com/
2. Create your account
3. Create your first app based on a Template using PostgreSQL:
(Choose from template)

<img width="474" alt="Screenshot 2023-01-12 at 09 10 08" src="https://user-images.githubusercontent.com/21973502/212065123-2ac23741-aabb-4d07-a55c-ce718e5dd72a.png">

4. All Categories >> Customer Dashboard (using a PostgreSQL sample DB):

<img width="980" alt="Screenshot 2023-01-12 at 09 10 18" src="https://user-images.githubusercontent.com/21973502/212065450-f1ce1cb4-25ea-4985-87c1-264439a51749.png">

5. Right when you app the app, an **INTERNAL ERROR** message pops-up, saying that the query of the tables created could not be loaded. If you also try to execute the Query, it won't work at all:

<img width="1052" alt="Screenshot 2023-01-12 at 09 11 00" src="https://user-images.githubusercontent.com/21973502/212065626-b1ed0e32-2331-4953-bfd9-573b3109a6e2.png">

**Comment by joaolessab** [comment]
Ok, this does not close the issue yet.

Even if the password does not reset anymore when going back again to the app, the PostgreSQL Datasource cannot connect at all. 

May you guys please, check the Tool Jet template that I've described?
Thank you!

**Comment by gsmithun4** [comment]
@joaolessab able to connect to the database, please take a look
https://www.loom.com/share/2dd5946258024e138af33a2ce3431fdb

**Comment by joaolessab** [comment]
### **The password bug is still happening!**

This is a screenshot of right now. **Just tested!**
May we re-check it again, please?

When I validate my password, this screen is being displayed:

<img width="701" alt="Screenshot 2023-01-13 at 09 30 08" src="https://user-images.githubusercontent.com/21973502/212320941-34371874-630e-4337-a8af-c5bf221530a6.png">

When I reopen the App project, and I go check the datasource, the DB password is not working anymore!
Every time that I open the app, I have to go and re-insert the password again:

<img width="715" alt="Screenshot 2023-01-13 at 09 28 22" src="https://user-images.githubusercontent.com/21973502/212321137-a7c55cda-e9b1-4b1b-b62e-daf3e89fd0bf.png">

**Comment by cr3a7ure** [comment]
```QueryManager.jsx (610:22) SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string

{​
message: "SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string",
path: "/api/data_queries/preview",​
statusCode: 500,​
timestamp: "2023-01-15T17:30:02.712Z"
}
```
