### ISSUE TITLE
Docker tooljet/try image from Docker Hub seems to be broken

### ISSUE THREAD

**Issue by mdocter** [ToolJet/ToolJet#5307]
### Version Information
tooljet/try latest image from today : Digest: ead3511a6f44

### Environment
Docker

### What is the expected behaviour?
Pull the new image, start the container, load the homepage, login

### What is the current behaviour?
load the homepage, the loading/spinner icon sytays visible and noting happens. 

### How to reproduce the issue?

1. Pull the new image
2. start the container
3. load the homepage

### Screenshots or Screencast
<img width="492" alt="2023-01-11 22_42_14-Settings" src="https://user-images.githubusercontent.com/796916/211924553-32da07a1-2339-4393-b6e0-a55a61e8de2b.png">

### Please provide any traces or logs that could help here.
The Docker log is fine. In the browser I see a JavaScript error from the vendor.js file:

`unreachable code after return statement vendor.js:115:451350`

### Any possible solutions?
Maybe a js error in vendor.js. Updated a js depency which was buggy?

### Can you identify the location in the driver source code where the problem exists?
n/a

### If the bug is confirmed, would you be willing to submit a PR?
n/a

**Comment by cueup** [comment]
localhost doesn't even load for me

**Comment by akshaysasidrn** [comment]
There was an error in the command given in README, please check now after pulling the latest image again.

**Comment by mdocter** [comment]
The new version works for me. Thanks @akshaysasidrn !
