### ISSUE TITLE
tooljet/try v2.0.1: HTTP 403 after answering company size. On-screen message: "forbidden resource"

### ISSUE THREAD

**Issue by christophberger** [ToolJet/ToolJet#5322]
### Version Information

tooljet/try v2.0.1

### Environment

- ToolJet Docker
- containerd v1.6.8, runc: v1.1.4
- Colima 0.5.2 on macOS 13.1

### What is the expected behaviour?

Clicking either "Continue" or "Skip" on the page "What is the size of your company?" should advance to the next page.

### What is the current behaviour?

Clicking either "Continue" or "Skip" on the page "What is the size of your company?" shows an on-screen error "forbidden resource". On the terminal where the container runs, a large JSON blob is printed (see "traces or logs" section).

### How to reproduce the issue?

1. Run the `tooljet/try` image v2.0.1 (I use `containerd`):

```sh
nerdctl run \
                     --name tooljet \
                     -p 7001:80 \
                     -v tooljet_data:/var/lib/postgresql/13/main \
                     tooljet/try:latest
```

2. Start entering requested data (username etc)
3. On the page asking for the company size, either click a size and click the Continue button, or click Skip.

### Screenshots or Screencast

![Screenshot 2023-01-12 at 14 28 32](https://user-images.githubusercontent.com/3835890/212081871-3a579b7e-2af7-4556-9b27-f650ddf0e6ca.png)

### Please provide any traces or logs that could help here.

`{"level":30,"time":1673530318874,"pid":184,"hostname":"faaf61b9f6e1","req":{"id":13,"method":"POST","url":"/api/setup-admin","query":{},"params":{"0":"/setup-admin"},"headers":{"host":"localhost:7001","connection":"keep-alive","content-length":"173","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","content-type":"application/json","accept":"*/*","sec-gpc":"1","accept-language":"en-US,en","origin":"http://localhost:7001","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:7001/setup","accept-encoding":"gzip, deflate, br","cookie":"metabase.DEVICE=d8fdb7b8-2ce8-4ac9-958d-0d483611dd46; metabase.TIMEOUT=alive; metabase.SESSION=4f0ceb3d-41e9-4a9b-9489-e2683b06d840; redirectPath=/; amp_adc4c4=5EQegSMGBAap78eOZS1dCJ...1gmj1a45h.1gmj2knpo.0.0.0"},"remoteAddress":"10.4.0.1","remotePort":32782},"res":{"statusCode":403,"headers":{"x-powered-by":"Express","access-control-allow-origin":"*","content-security-policy":"img-src * data: blob:;script-src maps.googleapis.com storage.googleapis.com apis.google.com accounts.google.com 'self' 'unsafe-inline' 'unsafe-eval' blob: https://unpkg.com/@babel/standalone@7.17.9/babel.min.js https://unpkg.com/react@16.7.0/umd/react.production.min.js https://unpkg.com/react-dom@16.7.0/umd/react-dom.production.min.js cdn.skypack.dev cdn.jsdelivr.net;default-src maps.googleapis.com storage.googleapis.com apis.google.com accounts.google.com *.sentry.io 'self' blob:;connect-src ws://localhost 'self' *;frame-ancestors *;frame-src *;base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'","content-type":"application/json; charset=utf-8","content-length":"114","etag":"W/\"72-qSB4xEeZFDGWYbp7csQF2tAxr+c\"","vary":"Accept-Encoding"}},"responseTime":52,"msg":"request completed"}`

### Any possible solutions?

No

### Can you identify the location in the driver source code where the problem exists?

No

### If the bug is confirmed, would you be willing to submit a PR?

n/a (Not a JS/TS developer)

**Comment by christophberger** [comment]
UPDATE: The issue **disappeared**. 

The only thing I changed is the setup of Colima (the container VM on macOS). 

I assume that the change of the DNS resolver has something to do with the issue. Previously, I used 1.1.1.1, now I am using the local DSL router. All other changes to Colima (that is, VM changed from qemu to macOS vz, filesystem changed from sshfs to virtiofs) do not seem relevant to the problem (from my perspective).

**Comment by blitzdakka** [comment]
I am having the same issue, but running the docker in a Debian VM. I hadn't touched the DNS settings, but tried setting it to my router, but got the exact same error.

**Comment by lazyest** [comment]
same issue with reversed proxying using traefik

**Comment by cmaclennan** [comment]
same issue here on docker instance on vultr

**Comment by swthor** [comment]
Same issue here on EC2 instance

**Comment by akshaysasidrn** [comment]
I'm having trouble replicating this issue. Could you folks please help confirm and share:
1. try/tooljet image sha
2. Is existing data present on the attached postgres volume ?
3. Browser console errors thrown if any

**Comment by lazyest** [comment]
1. Digest: sha256:1582da2e7d933abbcaa691bdcf0c5375f3e286c1badcf53b19191f3cfebc8676
Status: Downloaded newer image for tooljet/try:latest
2. clean installation
3. Have only this:
[HTTP/2 403 Forbidden 214ms]

        
statusCode      403
timestamp       "2023-01-17T11:40:17.787Z"
path    "/api/setup-admin"
message "Forbidden resource"

**Comment by lazyest** [comment]
Image with Digest: sha256:212d9e035b95744080a4c97d9ed5e6a3e1b9d731e95481273b3138eab4b55570 seems to be working for me

**Comment by lazyest** [comment]
after few hours running it started to act same way

**Comment by avfuturist** [comment]
I had the same issue...I created my login and got the 403 as I went to complete the company info form. I deleted the container, the recreated it with the same mapped volume. That put me to a password prompt and the tool is working...as a workaround at least.

**Comment by tankilo** [comment]
I follow the latest doc and get the same error.
![image](https://user-images.githubusercontent.com/10413284/215436911-7bd45312-5153-4096-8174-1786e5342610.png)

![image](https://user-images.githubusercontent.com/10413284/215436723-d800698c-e9a4-461a-ad01-261492444958.png)

**Comment by fy0** [comment]
error still exists on version sha256:1143c8e21fcb2d4d5c920d8be48ac0dce7ff9f97cdbd1185a77a53b5ffa33db9

**Comment by fy0** [comment]
> Try with login used in https://app.tooljet.com/ @sulaimaan26 

I switched to chatgpt, write tailwind.css and golang code
Just use two days,  first version of my service is online.

**Comment by damaspi** [comment]
Installed locally via the Docker command
`docker run --name tooljet --restart unless-stopped -p 8081:80 -v tooljet_data:/var/lib/postgresql/13/main tooljet/try:latest`
Had the same issue. This concludes my test of the Tooljet platform.

**Comment by Azathoth88** [comment]
I have same problems. Installed with 

```
docker run \
>   --name tooljet \
>   --restart unless-stopped \
>   -p 8066:80 \
>   -v tooljet_data:/var/lib/postgresql/13/main \
>   tooljet/try:latest
```

When I look into developer console on the browser I get this errors:
https://i.imgur.com/pW5SFj6.png

**Comment by gsmithun4** [comment]
> I have same problems. Installed with
> 
> ```
> docker run \
> >   --name tooljet \
> >   --restart unless-stopped \
> >   -p 8066:80 \
> >   -v tooljet_data:/var/lib/postgresql/13/main \
> >   tooljet/try:latest
> ```
> 
> When I look into developer console on the browser I get this errors: https://i.imgur.com/pW5SFj6.png

Updated the try tooljet image

**Comment by Azathoth88** [comment]
The application is now no longer accessible with the latest image.

**Comment by adishM98** [comment]
@Azathoth88 May i know what is the error message that you are getting ?

**Comment by Azathoth88** [comment]
@adishM98 In principle, I would like to do that. However, I don't get any errors in the Docker container. Nothing happens at all.
I start the container via Portainer - the port addressed can be seen for a short time. Then it disappears immediately.
The container log remains completely empty.

**Comment by adishM98** [comment]
@Azathoth88 I checked the same on my local machine the application is up and running. Also may i know if there is any other container running on the same in Portainer.

**Comment by Azathoth88** [comment]
I had already used another port and had the same problem. I had already deleted the container and created it again - none of this worked.

Now I have completely deleted the downloaded image and recreated it - now it works.
