### ISSUE TITLE
The password bug for PostgreSQL is still happening!

### ISSUE THREAD

**Issue by joaolessab** [ToolJet/ToolJet#5336]
### **The password bug is still happening!**

This is a screenshot of right now. **Just tested!**
May we re-check it again, please?

When I validate my password, this screen is being displayed:

<img width="701" alt="Screenshot 2023-01-13 at 09 30 08" src="https://user-images.githubusercontent.com/21973502/212320941-34371874-630e-4337-a8af-c5bf221530a6.png">

When I reopen the App project, and I go check the datasource, the DB password is not working anymore!
Every time that I open the app, I have to go and re-insert the password again:

<img width="715" alt="Screenshot 2023-01-13 at 09 28 22" src="https://user-images.githubusercontent.com/21973502/212321137-a7c55cda-e9b1-4b1b-b62e-daf3e89fd0bf.png">

_Originally posted by @joaolessab in https://github.com/ToolJet/ToolJet/issues/5305#issuecomment-1381790757_

**Comment by cr3a7ure** [comment]
After successful testing the password, I try running a simple query. 

```QueryManager.jsx (610:22) SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string

{​
message: "SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string",
path: "/api/data_queries/preview",​
statusCode: 500,​
timestamp: "2023-01-15T17:30:02.712Z"
}
```

**Comment by gsmithun4** [comment]
Hi @joaolessab, @cr3a7ure Which version/branch are you trying? released the fixes in v2.0.2
@emidhun Can you please re-check

**Comment by cr3a7ure** [comment]
hi @gsmithun4 from the UI I see v1.31.1. I did use docker-compose tagged `tooljet/tooljet-ce:latest`

**Comment by joaolessab** [comment]
@gsmithun4 @cr3a7ure haven't you guys released it to the Cloud yet?
I'm not using self hosting. I'm using [app.tooljet.com](https://app.tooljet.com/)

**Comment by gsmithun4** [comment]
> that's why. Any news of when it's going to be available on app.tooljet.com?

Done, please check
