### ISSUE TITLE
Feature: star rating widget

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#534]
### Is your proposal related to a problem?
This proposal is regarding creating a new widget - **star rating widget**

### Describe the solution you'd like
Create a new widget in the widget ecosystem which has the basic characteristics like drag & drop into the can have the following **widget properties**

```
max count - 5, type: numeric
default rating - 5, type: numeric
active color - #ffcb45, type: string
inactive color - #f2f2f2, type: string
tooltips: sets tooltip content of star: array of strings, type: array
size: small medium large, type: string
allow half star: bool, type: boolean
visibility, type: boolean
disabled , type: boolean
actions whenever the star rating changes: maxCount, value, isVisible can be read
```

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by Navaneeth-pk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Star rating widget](https://trello.com/c/4pXyCwC2/23-star-rating-widget)

**Comment by Manas1820** [comment]
Is this issue still open?
