### ISSUE TITLE
Show on Mobile missing

### ISSUE THREAD

**Issue by superwolfi82** [ToolJet/ToolJet#5340]
### Version Information
2.0.1

### Environment
Docker

### What is the expected behaviour?
i have placed a table in the desktop canvas, and i have a show on mobile switch to enable to it in the mobile view.

### What is the current behaviour?
show on on mobile switch is missing
### How to reproduce the issue?

1. create an app
2. drag and drop a table
3. scroll down to layout and search for "show on mobile"

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/61870040/212552390-4c81a8aa-560a-4b51-b178-b172eaf7ac5f.png)

### If the bug is confirmed, would you be willing to submit a PR?
sure

**Comment by withshubh** [comment]
Fixed in #5353
