### ISSUE TITLE
[docs]: rename the star-rating component doc

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5375]
### Summary

The link to the documentation of the star-rating component from the app builder redirects to :
- https://docs.tooljet.com/docs/widgets/star-rating

but the current URL is 
- https://docs.tooljet.com/docs/widgets/star

To fix this issue just rename the `star.md` file to `star-rating.md`

### Issue Type

Documentation bug

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by maddy020** [comment]
Hey @withshubh 
I would love to contribute over this issue

**Comment by Jittojoyes98** [comment]
Hey anyone working on this issue? If not I would like to work .

**Comment by withshubh** [comment]
Hey @maddy020 - Assigned this to you.

**Comment by withshubh** [comment]
> Hey anyone working on this issue? If not I would like to work .

Hey @Jittojoyes98 - We assign the issues on a first come first served basis. Please find other open issues.

**Comment by maddy020** [comment]
hey @withshubh 
I am unable to find the file .
Can you help me out?

**Comment by Ali7040** [comment]
Is anyone working on this issue? if not then assign me.

**Comment by withshubh** [comment]
The issue has been fixed
