### ISSUE TITLE
Custom React components fail at dealing with objects

### ISSUE THREAD

**Issue by jibe-b** [ToolJet/ToolJet#5390]
### Environment
ToolJet Cloud

### What is the expected behaviour?
When passing an object in the props of a custom react component, the object should be accessible and the component should render.

### What is the current behaviour?
When passing an object as a prop of a custom react component, the object is not handled correctly and the components is not rendered.

### How to reproduce the issue?

1. Create a new Custom React componen
2. Pass the following data as props
```
{{ {
        title: 'Hi! There',
        some_data: {
               some_key: "some_value"
        }
}
}}
```
3. Enter some code that calls the prop that contains the object 
```
import React from 'https://cdn.skypack.dev/react';
import ReactDOM from 'https://cdn.skypack.dev/react-dom';

const MyCustomComponent = ({data, updateData, runQuery}) => (
  <div>
    {data.some_data}
  </div>
);
const ConnectedComponent = Tooljet.connectComponent(MyCustomComponent);
ReactDOM.render(<ConnectedComponent />, document.body);
```
4. Notice that the rendering fails
![image](https://user-images.githubusercontent.com/6146483/213758251-c03b9ec7-9763-48d0-b113-d925967e5bc5.png)

5. Notice that a prop containing a string leads to a correct rendering of the component
![image](https://user-images.githubusercontent.com/6146483/213758098-5aa5ffdd-8e28-4d67-ac83-e5ca81194c7b.png)

**Comment by kavinvenkatachalam** [comment]
Hey @jibe-b - It's not an issue with the custom component and the error is thrown by React when we try to render the object . 

Attaching the link for your reference - https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7Ba%7D
