### ISSUE TITLE
Add DTO validation for update organization API

### ISSUE THREAD

**Issue by gsmithun4** [ToolJet/ToolJet#5400]
### Describe the solution you'd like
Create DTO validation for update organization API
[PATCH] /api/organizations

name - Optional, string, max length 25
domain - optional, string, max length 250
enableSignUp - Optional, boolean
inheritSSO - Optional, boolean

### If the feature is approved, would you be willing to submit a PR?
No

**Comment by Jittojoyes98** [comment]
Can I work on this issue?

**Comment by withshubh** [comment]
Hey @Jittojoyes98 Assigned to you.

**Comment by Jittojoyes98** [comment]
Heyy i have updated the file 
![Screenshot from 2023-01-31 11-36-19](https://user-images.githubusercontent.com/51293782/215679911-1cabd052-ca92-4e6e-a3a9-6eabcf2f9c61.png)
For the optional parameter does the (?) required along with the name of the field.

**Comment by gsmithun4** [comment]
> Heyy i have updated the file ![Screenshot from 2023-01-31 11-36-19](https://user-images.githubusercontent.com/51293782/215679911-1cabd052-ca92-4e6e-a3a9-6eabcf2f9c61.png) For the optional parameter does the (?) required along with the name of the field.

Not mandatory, good to add. 
can use `@Transform(({ value }) => sanitizeInput(value))` for domain also
for name, shall we add @IsOptional followed by @IsString
