### ISSUE TITLE
[listView] selectedRowId does not update when a button is clicked in a row

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5407]
### What is the expected behaviour?

When a button is clicked in any of the rows inside listView the selectedRowId should update.

### What is the current behaviour?

Currently, the user will have to click on the row itself to update selectedRowId variable and then click on the button.

### How to reproduce the issue?

1. Add a listview
2. add a button in listview
3. add event handler to the button -> show alert -> message `{{components.listview1.selectedRowId}}` 
4. try to click on the buttons in different row the message will remain same unless you select a row first then click on the button

ref:
<img width="646" alt="Screenshot 2023-01-24 at 10 47 36 AM" src="https://user-images.githubusercontent.com/25361949/214217532-c7f2f18b-2d37-4baf-a599-739c72488512.png">

**Comment by jibe-b** [comment]
Thanks for opening this issue. This behaviour is currently a limit to some use cases I am developing.

**Comment by poaudet** [comment]
Here's a workaround!

1. add a text field with the id of the query item (in my case, the field was text1 and referred to the "_id" field in the query)
2. hide this field if it is not required to be seen (set visibility to false)
3. set the disable property of the button to:
{{components.listview1.selectedRow == undefined || components.listview1.selectedRow.text1.text != listItem._id}}

What happens: 
- <components.listview1.selectedRow == undefined> will be true if no row is selected, so all the buttons on each are disable by default
- || is an "or" operator
- <components.listview1.selectedRow.text1.text != listItem._id> will be true if the text field of the selected row is not equal (!=) to the field equivalent of the listItem where the button is.

If one or the other is true, the button will be disable.

**Comment by jibe-b** [comment]
Thanks a lot for having fixed this issue!

**Comment by Wjs0068** [comment]
Still seeing an issue here.
