### ISSUE TITLE
Tooljet DB is not accessible for public apps.

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#5423]
### Version Information
v2.0.2

### Environment
ToolJet Cloud

### What is the expected behaviour?
For publicly shared apps, all the users should be able to access/view the data from  Tooljet database.

### What is the current behaviour?
The data from tooljet_db is not visible on the public apps.

### How to reproduce the issue?

1. Create an app.
2. Connect with tooljet_db.
3. Show the DB data by using any widgets.
4.  Release the app.
5. Make the app public and copy the link.
6. Open the link in incognito mode.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/20367955/214473478-063c1464-ab9d-488b-9932-fea1dd1fdc4a.png)

### Any possible solutions?

--No--
### Can you identify the location in the driver source code where the problem exists?

--No--
### If the bug is confirmed, would you be willing to submit a PR?
--No--

**Comment by yogasw** [comment]
Is there an update to this issue?
