### ISSUE TITLE
Feature: toggle switch button as a cell type for tables

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#543]
**Feature: toggle switch button as a cell type for tables**

**Comment by arpitnath** [comment]
picking this up

**Comment by Navaneeth-pk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Toggle switch as table cell type](https://trello.com/c/VGTN8GoA/18-toggle-switch-as-table-cell-type)

**Comment by arpitnath** [comment]
That Board is private.

I have added the toggle, working on the bugs, there is some unusual behaviour.
![Screenshot 2021-08-19 at 10 16 58 AM](https://user-images.githubusercontent.com/67645175/130009657-321105cd-b429-4621-81d5-29f5a475bb65.png)
