### ISSUE TITLE
Stale main.js is cached by browser

### ISSUE THREAD

**Issue by merlinran** [ToolJet/ToolJet#5450]
### Version Information
2.0.3, but should present in other versions as well.

### Environment
Docker

### What is the expected behaviour?
After migrating to 2.0, the ToolJet home page should load.

### What is the current behaviour?
Page fails to load in either Brave browser or Safari, with js error in console. Page can be loaded in "Private window" mode with either browser.

### How to reproduce the issue?
With v1.x (mine was v1.25.5), open the web page in any browser so the files can be cached.
Upgrade to v2, then open the page again, should fail to load.
The same page can be open in private window / incognito mode.

### Screenshots or Screencast

Visit ToolJet page at the same time, the ETag and Last-Modified are different in a normal window vs Private Window

Normal:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/1369696/215716253-9b2cb2c5-f938-41a4-bd35-73f19718481d.png">

Private:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/1369696/215716538-b9a6cf97-916c-4017-8c7a-9481d303a434.png">

### Any possible solutions?
In building pipeline, append the hashes of the asset files to the file names, so any file will get a different name whenever it changes, avoid stale cache.

**Comment by adishM98** [comment]
Hi Merlin, 

I down-graded the instance as you mentioned to v1.25.5 loaded the page and then changed the image to to v2.0.4. The page was loading for me. I think i am not able t replicate the issue. 

Also are you still facing this issue ?

**Comment by merlinran** [comment]
The issue was persistent to me, though I no longer see it after force refreshing the page to clear the cache.

I think what the browsers do are expected without explicit [`Cache-Control` headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), see https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#heuristic_caching. I think adding hash to the filenames or as `no-cache` query parameter is a common way to avoid stale cache.

**Comment by adishM98** [comment]
Understood, thank you for the input will note it down.

**Comment by merlinran** [comment]
The fact that I was using SOCKS proxy might have affected browsers' behaviour, though I can't verify that at this moment.

**Comment by adishM98** [comment]
Could be one of the reasons. No worries will keep a eye on the issue. If it occurs for any other user will check it out.
