### ISSUE TITLE
Radio button widget gives error when not boolean

### ISSUE THREAD

**Issue by GlenEaston** [ToolJet/ToolJet#5472]
Anything other than true/false gives an error

**Comment by kavinvenkatachalam** [comment]
Hey @GlenEaston Thanks for creating an issue. I'm able to create the radio button widget with `number` as well as `string` datatype. Attaching the screenshot

<img width="713" alt="image" src="https://user-images.githubusercontent.com/50441969/216896472-80c7ebc6-443c-4e5b-87c6-82c85818ca2c.png">

**Comment by GlenEaston** [comment]
This is what's causing an error:
[image: image.png]

**Comment by GlenEaston** [comment]
![image](https://user-images.githubusercontent.com/85961759/216992155-015ce42f-1564-4769-b2b8-6ee8078913d2.png)

**Comment by kavinvenkatachalam** [comment]
@GlenEaston Seems to be working for me. There is an error in the debugger which can be fixed

<img width="744" alt="image" src="https://user-images.githubusercontent.com/50441969/217732315-646c0bd6-6061-4026-8ea6-5ab5a3bfe933.png">

**Comment by GlenEaston** [comment]
Yes, that is the error that I am referencing. I didn't know if it was just
a false error or there was more going on.
