### ISSUE TITLE
On sending a workspace invite, user is not being redirected to the invited workspace

### ISSUE THREAD

**Issue by thehacklady** [ToolJet/ToolJet#5476]
### What is the expected behaviour?
On sending a workspace invite to a user, they should be redirected to the invited workspace.

### What is the current behaviour?
On sending a workspace invite to a user, they are not redirected to the invited workspace.

### How to reproduce the issue?

1. Go to Settings > Click on 'Invite new user' 
2. Invite any user by adding details
3. Click on 'accept invite' and you will land on workspace dashboard (but not the one for which you are invited)

### Screenshots or Screencast
<img width="1421" alt="Screenshot 2023-02-03 at 4 44 05 PM" src="https://user-images.githubusercontent.com/32910986/216589752-0945930f-7db0-462c-abca-032d1f166b57.png">

In this, bhive is my workspace. But the workspace I got invited for is - Templates and I'm not getting redirected to it.

**Comment by Vansh-Baghel** [comment]
@thehacklady I didn't understand what issue you are facing, so if you click on workspace, aint you getting redirected to it?

**Comment by thehacklady** [comment]
@Vansh-Baghel yes and no. let me explain it to you. 

On being invited to a particular workspace : user gets an invite. 
In case of user accepting the invite - 
user clicks on the invite > user accept invite & check creds > gets redirected to the current active session (if already logged in) 
in this case, the user is redirected to 'current' active session workspace and not to the invited workspace. 

does this help?
