### ISSUE TITLE
[docs]: remove duplicate info in athena doc

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5491]
### Summary

The same info is mentioned twice in the doc. Remove the first one.
<img width="922" alt="Screenshot 2023-02-07 at 11 32 07 AM" src="https://user-images.githubusercontent.com/25361949/217167922-993983c9-6a1c-4664-947b-b0a71bb48135.png">

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/athena/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Sheikh-JamirAlam** [comment]
I can work on it.

**Comment by withshubh** [comment]
Hey @Sheikh-JamirAlam - Assigned this issue to you.

**Comment by Queen-codes** [comment]
I can work on this if you could please assign me

**Comment by withshubh** [comment]
Hey @Queen-codes - The PR for fixing the issue has already merged as you can see in the thread above.
Please look for other open and unassigned issues and comment if you're interested.
