### ISSUE TITLE
[RestAPI] add option `allowGetBody` to allow GET requests with payload

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5493]
### Is your proposal related to a problem?

Currently, there is no option to pass the body in GET.

### Describe the solution you'd like

Add the option for `allowGetBody` to allow get requests with payload
ref: https://github.com/sindresorhus/got/pull/1081
<img width="707" alt="Screenshot 2023-02-07 at 12 51 22 PM" src="https://user-images.githubusercontent.com/25361949/217175643-6051a2a0-d262-4d6d-940d-fb4fbf5b093c.png">

**Comment by Just-A-Pixel** [comment]
Can I work on this issue?

**Comment by vivektripaathi** [comment]
Hi @PriteshKiri, could you please assign this issue to me?"

**Comment by PriteshKiri** [comment]
This issue no longer exist
