### ISSUE TITLE
Nav Item selection bug

### ISSUE THREAD

**Issue by Vansh-Baghel** [ToolJet/ToolJet#5495]
### How to reproduce the issue?

1. Could change the styling.
2. Add proper html and css code to fix it.

### Any possible solutions?
* Yes, by adding proper styling, this could be fixed, I could fix it as well.

### If the bug is confirmed, would you be willing to submit a PR?
* Yes, I'll submit it asap.

**Comment by withshubh** [comment]
Hey @Vansh-Baghel - Can you please explain what's the bug in detail? Also, please share the screenshots or screen record?

**Comment by Vansh-Baghel** [comment]
@withshubh look at this padding. This is applied at every nav item, so even if user is in the green box, the nav item could be selected.
![tooljet](https://user-images.githubusercontent.com/103327712/217335154-92fb782b-8c40-4af5-b601-03d5eb95a4c5.png)

**Comment by shubh22** [comment]
Hi, 
This repo doesn't track bugs for ToolJet.com website but only for the product ToolJet.
Closing this issue.
