### ISSUE TITLE
Able to select other available options if `isEditable` is **true** - Radio Table cellType

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#550]
### What is the expected behaviour?
Should be able to select other available options if `isEditable` is **true**

### What is the current behaviour?
Can only select the original option/value provided when `isEditable` is **true**

### How to reproduce the issue?

1. Drag the Table widget and inject data into it.
example: 
```
{{[
    { 
    "id": "000102",
    "name": "sam",
    "email": true,
    }
]}}
```
2. select **Radio** from `Column type` for `email`
3. set values and labels
f.e.
values : `{{[true,false]}}`
labels: `{{["yes","no"]}}`

### Screenshots or Screencast
https://www.loom.com/share/d2ffd9980bf8412683c797b05d61f195

### Any possible solutions?
**One way to fix**: 
- update
```
// frontend/src/Editor/Components/Table/Radio.jsx
value = value || [];
```
to 
`value = value ? value : [];`

**OR** Just removing that line.

**Comment by Navaneeth-pk** [comment]
This bug was fixed.
