### ISSUE TITLE
Incorrect heading in runpy documentation

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5500]
### Summary

Remove `using` from `Parse CSV data`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/how-to/import-external-libraries-using-runpy#parse-csv-data-using

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by TheLearneer** [comment]
Hi @withshubh 👋 
I can pick it up 🙌

**Comment by withshubh** [comment]
Hey @TheLearneer - Assigned to you.

**Comment by Queen-codes** [comment]
HI, I can fix the issue
