### ISSUE TITLE
Custom components with skypack import issue

### ISSUE THREAD

**Issue by bestpika** [ToolJet/ToolJet#5527]
### Version Information

- All version.

### Environment

- ToolJet all platform.

### What is the expected behaviour?

The function to include a reference to the package of the skypack when using custom components.

### What is the current behaviour?

Skypack has been having a lot of problems since last August, and it can't reference some npm package properly.
For related issues, see skypack's github repository.
<https://github.com/skypackjs/skypack-cdn/issues>

I know it's their problem and not yours, but the over-reliance of the custom components of this product on that service is a big problem.

**Comment by kavinvenkatachalam** [comment]
@bestpika Thanks for creating an issue. 
Agree! We will discuss internally with the team and come up with a plan

**Comment by yogasw** [comment]
hi @shubh22 or @kavinvenkatachalam 
maybe you can change skypack to esm.sh

I have created an example here
tooljet application : https://app.tooljet.com/applications/68d5c552-5fb3-4ac6-987a-7b94a1685f47
repo : https://github.com/yogasw/tooljet-custom-component
html build : https://yogasw.github.io/tooljet-custom-component/
