### ISSUE TITLE
Update kubernetes deployment docs

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#553]
[Doc](https://docs.tooljet.io/docs/deployment/kubernetes/) currently states to curl for missing file
```
 kubectl apply -f https://raw.githubusercontent.com/ToolJet/ToolJet/main/deploy/kubernetes/server-deployment.yaml
 ```
Update to reference the latest file instead wiz. 
https://raw.githubusercontent.com/ToolJet/ToolJet/main/deploy/kubernetes/deployment.yaml

**Comment by RhnSharma** [comment]
I would like to take this one.
