### ISSUE TITLE
Query driven tabs fail with no data and cannot be recovered

### ISSUE THREAD

**Issue by SGarno** [ToolJet/ToolJet#5533]
### Version Information
2.1.1

### Environment
Linux

### What is the expected behaviour?
If a dataset cannot be generated or returns no rows, the Tabs component should just display no tabs.   

### What is the current behaviour?
It generates a "Something went wrong" text and that cannot be recovered from.   Neither, quitting the app and returning nor a hard browser refresh  fixes the problem.   

### How to reproduce the issue?

1.  Create a dataset that returns a proper tab data structure, but one that does not refresh on page start.
2.  Save the query again or leave the app and return.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/8698262/218194574-954e3ba2-1544-40bf-a272-41336c4e9f29.png)

### Any possible solutions?
One solution is to check for undefined within the path navigation in the tabs data definition and default to something that is displayable.   I.e.:

{{queries?.myQuery?.data?.events  || [ { title: 'None', id: '0'}  ]}}

### Can you identify the location in the driver source code where the problem exists?
No.

### If the bug is confirmed, would you be willing to submit a PR?
No.

**Comment by SGarno** [comment]
Also, I recognize that this poses a bigger issue;  How to create tab content dynamically?

**Comment by kavinvenkatachalam** [comment]
The issues is fixed by #5759
