### ISSUE TITLE
Cannot change home page

### ISSUE THREAD

**Issue by PrasanthKumar77** [ToolJet/ToolJet#5536]
### Version Information
2.1.1
### Environment

Docker
### What is the expected behaviour?

Home page can be changed

### What is the current behaviour?

Home page cannot be changed

### How to reproduce the issue?

1.create app
2.add pages
3.click on home page on newly added page
4. reload

**Comment by sherfin94** [comment]
Hey @PrasanthKumar77 , I'm able to make a different page homepage. 

When you make a page homepage (or do any other action of that sort), the platform will take around 3 seconds to get saved, you can see the saving status on the header bar.

I'm feeling that you mat have reloaded a bit too quickly after setting a page as homepage.

So could you try again once more, this time wait a few seconds until it says `Saved changes` on the header bar.

Thanks!
