### ISSUE TITLE
The public application are not hidden on the dashboard

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#5540]
### What is the expected behaviour?

When the admin creates a group and hides a public application from dashboard then that group of users should not be able to see that application on the dashboard.

### What is the current behaviour?

When the admin creates a group and hides a public application from the dashboard then that group of users are  able to see that application on the dashboard.
### How to reproduce the issue?

1. Create an application.
2. Make it public.
3. Create a group with n number of users and add the public application in the group.
4. Click on Hide from dashboard.
5. One user should login and observe the dashboard.

### Screenshots or Screencast

https://user-images.githubusercontent.com/41302917/218414968-7940ae23-560a-40e1-9ed6-d27ceb418537.mp4

**Comment by thehacklady** [comment]
fixed.
