### ISSUE TITLE
[docs]: Need examples for DynamoDB queries.

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#5542]
### Summary

Dynamo DB need more details on the documentation.
Currently there is only one operation mentioned on the documentation.

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/dynamodb/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by withshubh** [comment]
Fixed https://github.com/ToolJet/ToolJet/pull/6736
