### ISSUE TITLE
Problem with Importing Large App in local hosted (on ec2 instance) tooljet server

### ISSUE THREAD

**Issue by JeetKaria56** [ToolJet/ToolJet#5583]
### Version Information
tooljet v2.1.1 

### Environment 
AWS EC2 instance (t2.small)
AMI: tooljet_v1.27.0.ubuntu_bionic

### What is the expected behaviour?

Ideally it should import the app and it should work fine as it works normally from where it's imported.

### What is the current behaviour?

On setting up the server, when we try to import the large app (json file of size 4.2 MB in my case) it doesn't import and the UI shows the error saying ```Could not import the app: undefined``` and on inspect panel in chrome the endpoint which is responsible for importing (```/api/apps/import```) returns status code 413 and the error message Request Entity is too large.

### How to reproduce the issue?

1. Set up a tooljet server on ec2 instance of any hardware configs with the above mentioned AMI
2. Try having a json file of some exported app of size greater than 1 MB. (in my case it was 4.2 MB) and ```size``` of size of a json file. 
3. Import it into the already setup tooljet server.

### Please provide any traces or logs that could help here.
On looking at network tab in inspect panel at ```import``` request, it will show the following response
```
POST http://hostname/api/apps/import 413 (Request Entity Too Large)
```

### Any possible solutions?
I first searched for error in codebase but didn't find anything and also in response it said that it was returned by openresty so concluded that this is some auto-generated error from reverse proxy side and there might be some issue with nginx configuration file (because openresty is also an nginx based reverse proxy).

So, setting a max body size limit in nginx configuration file would solve the issue.

And with the spontaneous help by @amold96 I was able to make changes at the right place quickly.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by shubh22** [comment]
@JeetKaria56 - are you exporting many versions at once?

**Comment by PrasanthKumar77** [comment]
hi, i am also facing the similar issue with ec2 instance. my exported app size is around 7 mb. i am getting the same 413 in api that's called when making some adding/changes in components.
my app has only one version.

**Comment by JeetKaria56** [comment]
@shubh22 No, it was only one version (2.1.3 of tooljet cloud)

**Comment by JeetKaria56** [comment]
@PrasanthKumar77 For now, you can edit ```/etc/openresty/nginx.conf``` file and allow request size to be greater than 1 MB for the openresty reverse proxy, for whatever port you are requesting on (http/https). 

And then restarting ```openresty``` and `nest` service will solve the issue.

**Comment by shubh22** [comment]
@JeetKaria56 - I meant when you are exporting, are you exporting 1 version of the app or all the versions?

**Comment by JeetKaria56** [comment]
@shubh22 - I was trying only one version at a time and tried with all the versions including the latest one.
