### ISSUE TITLE
Datasource: connect to MySQL on Cloud SQL via Unix socket

### ISSUE THREAD

**Issue by kariem** [ToolJet/ToolJet#5600]
### Is your proposal related to a problem?

The data we would like to process in ToolJet is stored in a restricted Cloud SQL instance.

In our setup, ToolJet runs on Google Cloud Run and we would like to be able to connect to a database running on Cloud SQL. Cloud Run connects to the Cloud SQL instance via the container settings. According to the [documentation](https://cloud.google.com/sql/docs/mysql/connect-run#connect_to), the connection should be established via Unix sockets.

The current UI to configure a MySQL connection only provides inputs for host, port, and database name.

![image](https://user-images.githubusercontent.com/459324/220111462-01389bff-2d3e-4ac1-9937-3c18b8272968.png)

Trying to replace the host with the socket connection string (`/cloudsql/...`) results in an `ENOTFOUND` error

### Describe the solution you'd like

Add an option to the MySQL configuration dialog that allows to set the socket connection details. Something like `/cloudsql/INSTANCE_IDENTIFIER` should be sufficient.

### Describe alternatives you've considered

- Use a similar mechanism as for postgres as it seems this is supported to connect the ToolJet database
        See [ToolJet Setup | Deploying ToolJet on Google Cloud Run](https://docs.tooljet.com/docs/setup/google-cloud-run/#deploying-tooljet-application), list item 5, _Tip_:
    > If you are using [Public IP](https://cloud.google.com/sql/docs/postgres/connect-run) for Cloud SQL, then database host connection (value for `PG_HOST`) needs to be set using unix socket format, `/cloudsql/<CLOUD_SQL_CONNECTION_NAME>`.
- If this is already supported but not exposed via a UI, we could change the configuration in the table `data_source_options`
- Add an SSH tunnel to a machine on the same network as the Cloud SQL instance
- It is possible to connect to Cloud SQL instances via a [Cloud SQL connector](https://cloud.google.com/sql/docs/mysql/connect-connectors). I assume this also means additional integration efforts.

### If the feature is approved, would you be willing to submit a PR?

Yes

**Comment by kariem** [comment]
Would it be ok to just add a pull request even if there is no response here yet?

I hope this is the correct way to quickly discuss this, before opening a PR. I will quickly outline the steps involved ...

From what I have understood, Knex already supports socket connections and it should be possible to add a field to the `Knex.Config` field `connection` in mysql plugin's 

According the Knex [documentation](https://knexjs.org/guide/#configuration-options), we only need a socket path

``` javascript
const knex = require('knex')({
  client: 'mysql',
  connection: {
    socketPath : '/path/to/socket.sock',
    user : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test'
  }
});
```

What the PR would need to do

- Extend mysql plugin [SourceOptions](https://github.com/ToolJet/ToolJet/blob/1cad523478c01b3e7bf3b6c2403debc9fbc6929e/plugins/packages/mysql/lib/types.ts#L1C14-L8) to include a `socketPath`
- Adapt the [buildCconnection function](https://github.com/ToolJet/ToolJet/blob/1cad523478c01b3e7bf3b6c2403debc9fbc6929e/plugins/packages/mysql/lib/index.ts#L68C5-L80) to include a `socketPath` in the knex config `connection`, if the corresponding field is set in the source options
- Add this property to data_source_options.options for the MySQL data source:
    ```` json
    {
        "socketPath": { "value": "<the actual socket path>", "encrypted": false }
    }

Does that make sense. May I open a PR with this?

**Comment by shubh22** [comment]
Hi @kariem ,

Yes please open a pull request. We would review and merge it.

Thanks,
Shubham
