### ISSUE TITLE
Datasource in released version gets terminated after new version

### ISSUE THREAD

**Issue by AlJ95** [ToolJet/ToolJet#5608]
### Version Information
v2.1.4

### Environment
Kubernetes 

### What is the expected behaviour?

I expect that old unreleased versions get terminated after I created a new one, but released versions should not get terminated at all.

### What is the current behaviour?

When I release an application, I get frequently asked if I want to create a new version to make some changes, because the released version must not be changed.
However if you create a new version, the data source of our Snowflake connection gets terminated **in the released version**.

I have to re-enter the credentials for the datasources in the released one to fix it.

### How to reproduce the issue?

1. create new app
2. add data source snowflake
3. release application
4. create new version based on released version
5. try to query data in released version

### Please provide any traces or logs that could help here.
-

### Any possible solutions?
No

### Can you identify the location in the driver source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
No

Unfortunately there aren't much information I can provide yet.

**Comment by AlJ95** [comment]
### What is the expected behaviour?

I expect that old unreleased versions get terminated after I created a new one, but released versions should not get terminated at all.

### What is the current behaviour?

When I release an application, I get frequently asked if I want to create a new version to make some changes, because the released version must not be changed.
However if you create a new version, the data source of our Snowflake connection gets terminated **in the released version**.

### How to reproduce the issue?

1. create new app
2. add data source snowflake
3. release application
4. create new version based on released version
5. try to query data in released version

**Comment by shubh22** [comment]
Issue has been resolved in latest release.
