### ISSUE TITLE
Height control does not work when loading an image into a table

### ISSUE THREAD

**Issue by Karmin24** [ToolJet/ToolJet#5652]
**Version Information**
2.1.0

**Environment**
ToolJet Cloud

**What is the expected behaviour?**
the maximum fixed height for pictures in the table (and height manipulation through the row settings on the right)

**What is the current behaviour?**
the image height sets the height of the entire line and it is impossible to manipulate the line height from a certain minimum in any way

**How to reproduce the issue?**
1- add "image" field in mongo query
2- write the path there - example (
         "https://***.com/***/",
         { "$toString": "$_id" },
         ".jpeg"
       ]
     }
   })
3-change column type to "image"
4- compress the image size to a minimum

**Screenshots or Screencast**
<img width="84" alt=" 2023-02-28 в 20 11 51" src="https://user-images.githubusercontent.com/94185026/221926886-1e6cf868-e6aa-4a7e-9559-b0ecd8010d21.png">

**If the bug is confirmed, would you be willing to submit a PR?**
Yes

**Comment by johnsoncherian** [comment]
FIxed under issue: https://github.com/ToolJet/ToolJet/issues/8790
