### ISSUE TITLE
AWS S3 feature request - Operation to create a new S3 bucket

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#5690]
## Proposal
The proposed feature is to add a new operation called "**Create a new bucket**" that allows users to create a new bucket.

**Comment by nemarugommula** [comment]
Hey @arpitnath, I would like to work on this feature, would you assign it to me, Thanks!

**Comment by withshubh** [comment]
Hey @nemarugommula - Assigned to you.
