### ISSUE TITLE
[docs]: Missed the Slack channel hyperlink 

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#5703]
### Summary

The Slack channel hyperlink missed the format
https://docs.tooljet.com/docs/contributing-guide/setup/docker/
<img width="1024" alt="Screenshot 2023-03-04 at 6 04 54 PM" src="https://user-images.githubusercontent.com/34749692/222901352-fd85cb5d-1009-4324-b665-33c8b646bf91.png">

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/setup/docker/

### Steps to reproduce the issue

Move to the end of the documentation page

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Suraj-kumar00** [comment]
Hi @tejakummarikuntla can I work on this issue? Can you please assign it to me?
