### ISSUE TITLE
Delete icon overlaps with version name in version list

### ISSUE THREAD

**Issue by Mekhla-Asopa** [ToolJet/ToolJet#5711]
### What is the expected behaviour?
The delete icon should not overlap with the version name.

### What is the current behaviour?
The delete icon overlaps with the version name.

### How to reproduce the issue?

1. Login with the valid credentials
2. Create an application
3. Click on the version field, having the current version as the value
4. Click on the create new version link and create a new version with 25 characters
5. Click on the version field and move the mouse cursor to the newly created version

### Screenshots or Screencast
<img width="1426" alt="Screenshot 2023-03-06 at 3 54 25 PM" src="https://user-images.githubusercontent.com/59684099/223084014-8951cd85-27d0-45a1-a332-c6648a7ec54c.png">

**Comment by Chadokar** [comment]
@Mekhla-Asopa  I would like to solve this issue. Please assign this issue to me.
