### ISSUE TITLE
[docs]: Self-hosting documentation link in Quickstart section is broken

### ISSUE THREAD

**Issue by xlogix** [ToolJet/ToolJet#5718]
### Summary

I was going through the Quickstart section of the readme and found that the self-hosting deployment link which redirects [here](https://docs.tooljet.com/docs/setup/architecture) shows a "Page not found" error.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/setup/architecture

### Steps to reproduce the issue

1. Scroll down to the QuickStart section of the ToolJet GitHub page.

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by withshubh** [comment]
Hey @xlogix - Thanks for pointing this out. We will fix it soon.

**Comment by xlogix** [comment]
I was willing to submit a PR btw... just didn't know the correct link

**Comment by withshubh** [comment]
Hey @xlogix - My bad. Please feel free to create the PR and assign that to me, I will close the existing one.

**Comment by xlogix** [comment]
@withshubh It's cool. Now that it's raised already, no need for it. I was just saying...
