### ISSUE TITLE
Can't set JSON body of OpenAPI Query

### ISSUE THREAD

**Issue by tunix** [ToolJet/ToolJet#5723]
### Version Information

2.2.1

### Environment

Docker

### What is the expected behaviour?

Select a POST/PUT endpoint and you should be able to fill in request JSON data as you can with REST queries.

### What is the current behaviour?

I'm able to choose host and operation but JSON text input next to Preview is not clickable and therefore I cannot write my payload in it.

### How to reproduce the issue?

1. Load PetStore YAML file from [this link](https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml) as a new OpenAPI datasource.
2. Create query out of the new OpenAPI datasource and select `PUT /pet` as operation
3. Try to input request payload into the box.

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/47731/224152220-514b30d5-7874-40ae-a5f4-88564c216c39.png)

**Comment by Nandinisaha13** [comment]
Hey @tunix it seems like the yaml file is not proper format that is why you are not able to see the "JSON" input field.  And also the JSON you are talking about will only show output of the query. Ps- Could you try to have a JSON input field as you see in the screenshot by changing your yaml file.
<img width="1210" alt="Screenshot 2023-03-10 at 5 56 37 PM" src="https://user-images.githubusercontent.com/41302917/224315880-2d20a538-1d95-43cd-ac6a-a7daf966a800.png">

**Comment by tunix** [comment]
Hi @Nandinisaha13 ,

I copied and pasted Pet Store OpenAPI spec but cannot see that field you marked.

**Comment by shah21** [comment]
Hey @tunix
I have followed your steps and this looks like an issue. We will verify again and fix it.
