### ISSUE TITLE
Cant add tags if there are no tags in a cell.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#5724]
### Environment

    ToolJet Cloud / Docker / Linux / MacOS ...

### What is the expected behaviour?
If the tags is editable even if there are no tags present the user should be able to add new tags if the column is editable.

### What is the current behaviour?
User not able to add tags while the column is editable when no tags are already present.

### How to reproduce the issue?

1. Create an application.
2. Drag & drop table.
3. Click on "+ Add Column".
4. Click on new_column1.
5. Select "Tags" in column type & toggle the editable.
6. Observe.

https://user-images.githubusercontent.com/41302917/224233601-2ba3f91b-ef14-4da6-ab31-056020574abb.mov

**Comment by Ubaid-Manzoor** [comment]
Please assign this to me

**Comment by withshubh** [comment]
Closing this issue as fixed.
cc: @Nandinisaha13
