### ISSUE TITLE
Create a new datasource plugin for AWS Redshift

### ISSUE THREAD

**Issue by shubh22** [ToolJet/ToolJet#5725]
**Goal**
Create a new data source plugin for AWS Redshift

**Connection/Authentication**
1. Username/Password based authentication

**Operations to be supported:**

SQL support to interact with data

**Implementation**
Guide for building ToolJet plugins: https://docs.tooljet.com/docs/contributing-guide/tutorials/creating-a-plugin

**Comment by scullinan** [comment]
This would be great
