### ISSUE TITLE
Validation issues with 'number' data type of table widget

### ISSUE THREAD

**Issue by thehacklady** [ToolJet/ToolJet#5730]
### Version Information
v2

### What is the expected behaviour?

The number data type in table widget should function properly and the validations should save to the latest values.

### What is the current behaviour?

If user has added Number type column in the table component and kept it editable and added minimum and maximum value validation then :
- the validation values provided disappears
- provided different validation values, closed and opened the pop up again, still shows old values
- if user has provided invalid input, system shows the error notification but still accepts those values

### Screenshots or Screencast

<img width="565" alt="input_validation" src="https://user-images.githubusercontent.com/32910986/224332546-10d6ce44-ce99-41ee-a93f-17c3503d19eb.png">
<img width="533" alt="validation_not_getting_updated" src="https://user-images.githubusercontent.com/32910986/224332563-497a253f-3208-4591-8313-f1541d9e306b.png">
<img width="407" alt="validation_not_saved" src="https://user-images.githubusercontent.com/32910986/224332566-0683821c-f6d4-4a4a-b4e6-18b083308677.png">

**Comment by Ubaid-Manzoor** [comment]
PLease assign this to me will fix.

**Comment by akarsh-jain-790** [comment]
Hey @leecalcote, I would like to work on this.

**Comment by leecalcote** [comment]
@akarsh-jain-790, I suspect this was an accidental mention / wrong project.

**Comment by shubh22** [comment]
Hi @Ubaid-Manzoor , assigned this to you.

**Comment by Ubaid-Manzoor** [comment]
@shubh22 sure

**Comment by johnsoncherian** [comment]
Fixes in PR #8442
