### ISSUE TITLE
Deleting version of an existing app with multiple versions

### ISSUE THREAD

**Issue by thehacklady** [ToolJet/ToolJet#5731]
### Version Information
v2

### What is the expected behaviour?

1. Deleting the current version should move the version to last edited version in editor. Right now it becomes empty.
2. Should not see option to delete the released version

### Screenshots 
Related to point 1 above: 

<img width="1431" alt="blank" src="https://user-images.githubusercontent.com/32910986/224335343-da52a743-4cdc-4a28-aa3b-a6af6f8ddf01.png">
<img width="1438" alt="deleting_version_of_app" src="https://user-images.githubusercontent.com/32910986/224335375-9e74a2f1-332c-43cd-8053-4d055209eb77.png">

Related to point 2 above:

<img width="1433" alt="released_version_delete" src="https://user-images.githubusercontent.com/32910986/224335494-fc88f534-6ad3-466f-b7c3-335688b71b36.png">

**Comment by akarsh-jain-790** [comment]
Hey @thehacklady, I would like to work on this.

**Comment by Chadokar** [comment]
Hi @thehacklady, I would like to solve this issue.

**Comment by withshubh** [comment]
Hey @akarsh-jain-790 - Assigned the issue to you.

**Comment by withshubh** [comment]
> Hi @thehacklady, I would like to solve this issue.

Hey @Chadokar 👋 - Thanks for showing interest in contributing to ToolJet. We assign issues on FCFS basis. Please feel free to comment on any other good-first-issue that is open and unassigned.
