### ISSUE TITLE
Appwrite plugin is not working (package is deprecated)

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#5775]
### Environment

    ToolJet Cloud / Docker / Linux / MacOS ...

### What is the expected behaviour?
We should be able to connect appwrite and run queries.

### What is the current behaviour?
Not able to connect to appwrite 7 run queries.

### How to reproduce the issue?

1. Try to connect to appwrite with valid credentials.
2. Observe

**Comment by blank0537** [comment]
@Nandinisaha13 @karan-rathod-316 I have raised PR for this. Please assign the issue. Linked PR will close these issues as well #4764 & #4475 .

**Comment by mansukh-tj** [comment]
PR Merged

**Comment by parthamjangir2020** [comment]
@mansukh-tj  **thank you so much**
