### ISSUE TITLE
[Table Component] Add support to date time type

### ISSUE THREAD

**Issue by rhuanbarreto** [ToolJet/ToolJet#5778]
I want to make a table column where I can display formatted dates, like using moment(value).format("L"), but still retaining the original value for sorting client-side. If I do a string column, dates like DD/MM/YYYY will get sorted incorrectly.

A date picker column is not suitable fo my case because it displays an input, thus taking place in the table.

### Describe the solution you'd like

Add a column type called "date/time" with specific options. One example from openblocks.dev:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/283004/226263875-415264ec-1781-4dfa-bcd7-ae9eccf0f6b9.png">

### Describe alternatives you've considered

Only alternative for now is making a custom component.

**Comment by johnsoncherian** [comment]
Fixed in PR #8442
