### ISSUE TITLE
Improve template: S3 File explorer

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#5780]
## About
The ToolJet template "S3 File explorer" needs improvising, the template can be beautified and revamped with the following points

1. Add a container in the background
2. Improve the title design
3. Format the size column values with ‘kb’ units
4. Add an action button to download the file from table records
5. Beautify the template in possible ways.

**Comment by dblinkhorn** [comment]
@tejakummarikuntla, is this a good first issue for someone brand new to open source or a good first issue for someone new to this codebase?

**Comment by dblinkhorn** [comment]
@tejakummarikuntla, that sounds like the perfect place to start. If you don't mind I'd like to take a stab at this issue. It sounds like there is an existing S3 File Explorer template within ToolJet, but this issue entails building a new one with the listed improvements? Excuse my ignorance on ToolJet--I found this project on [up-for-grabs.net](https://up-for-grabs.net/#/) (I am looking to start contributing to open source projects) and the app sounded interesting to me.

**Comment by tejakummarikuntla** [comment]
Sure @dblinkhorn, assigning this to you. Hope you'll have a good time building the template.
If you get stuck, you can post your questions in our slack channel: http://tooljet.com/slack

**Comment by dblinkhorn** [comment]
@tejakummarikuntla, I will definitely hit up the Slack if i get stuck. Thanks!

**Comment by tejakummarikuntla** [comment]
Hey @dblinkhorn , were you able to progress with the issue?

**Comment by dblinkhorn** [comment]
@tejakummarikuntla Actually I think I may need some help getting started. I am not familiar with the software and need to find the right starting point. Can I find help on the Discord?

**Comment by tejakummarikuntla** [comment]
As time has passed, we made a decision to upgrade our S3 template, in which this mentioned issue is no longer valid. While we couldn't find the specific PR related to it, we sincerely appreciate your work.
