### ISSUE TITLE
Improve template: WhatsApp and SMS CRM

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#5781]
## About
The ToolJet template "WhatsApp and SMS CRM" needs improvising; the template can be beautified and revamped with the following points.

1. Add a container in the background.
2. Improve the title design
3. Improve the application description text
4. Align the “compose message” box and the “Send message” button.
5. Beautify the app in possible ways.

**Comment by vedantchourey** [comment]
Hi Teja !
Can I work on this? can you assign me?

**Comment by withshubh** [comment]
> Hi Teja ! Can I work on this? can you assign me?

Hey @vedantchourey - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by tejakummarikuntla** [comment]
Hey @vedantchourey, were you able to make any progress on this?

**Comment by nemarugommula** [comment]
Hey @tejakummarikuntla, I would like to work on this issue, would you like to assign it to me? Thanks!

**Comment by withshubh** [comment]
Hey @nemarugommula - Assigned to you.
