### ISSUE TITLE
Throwing error while connecting to Oracle DB .

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#5791]
### What is the expected behaviour?
Oracle DB connection should be possible.

### What is the current behaviour?
Throwing error while connecting Oracle DB.

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2023-03-20 at 2 22 09 PM" src="https://user-images.githubusercontent.com/20367957/226293137-5f0a22d9-7397-414a-947a-9518353f31e1.png">

**Comment by akshaysasidrn** [comment]
@ajith-k-v could you help check if this is still valid?

**Comment by akshaysasidrn** [comment]
This will happen only when the oracle instant client binaries are missing. We have added it in our docker envs. On local the user is expected to set it up. Closing this issue.
