### ISSUE TITLE
Target parameter is being removed silently from the a tag in HTML Viewer

### ISSUE THREAD

**Issue by codiflow** [ToolJet/ToolJet#5794]
### Version Information
v2.2.1

### Environment
Tooljet Docker

### What is the expected behaviour?
If I add the additional parameter `target` to a hyperlink inside a HTML viewer widget it should not being dropped silently.

### What is the current behaviour?
The source contains:
`<a href="https://www.tooljet.io" target="_blank" rel="noopener noreferrer">Tooljet</a>`

The app creates this in the DOM:
`<a rel="noopener noreferrer" href="https://www.tooljet.io">Tooljet</a>`

### How to reproduce the issue?

1. Create HTML viewer
2. Add the a element with target set
3. Open the app and inspect the element in the browser – it won't carry the target parameter

**Comment by CKanishka** [comment]
`DOMPurify.sanitize()` used underneath to sanitise the input HTML seems to be the reason behind it. 
Reference thread- https://github.com/cure53/DOMPurify/issues/317
