### ISSUE TITLE
Not able to trigger the modal inside a form by on Submit or by submit button

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#5796]
### Environment
    ToolJet Cloud / Docker / Linux / MacOS 
### What is the expected behaviour?
We should be able to open modal inside a form by using a form on submit action or on submit button click.

### What is the current behaviour?
Not able open the modal by onSubmit on onClick.

### How to reproduce the issue?

1. Drop a form.
2. Drop a modal inside the form.
3. Add a action on onSubmit  to open the form.

### Screenshots or Screencast

https://user-images.githubusercontent.com/20367955/226375742-7c025459-5cdf-4062-83ce-a393dc6b37ba.mp4

**Comment by utkarsh1212-i** [comment]
@emidhun  i have tried all the steps, and i think now its working. 

https://user-images.githubusercontent.com/85296972/226537937-44103d7f-b822-4468-8507-601b5a4b0111.mp4

**Comment by emidhun** [comment]
@utkarsh1212-i To reproduce this we need to add modal inside the form.

**Comment by utkarsh1212-i** [comment]
Okay , now i tried when modal is inside in the form, if all conditions remain same but ->
 --- if we assign 'button to submit from' in FORM  to none, it works, as button component also have SHOWMODAL listener
 But yeah !! the functionality should also work when the button is choosen in FORM submit,
---

**Comment by utkarsh1212-i** [comment]
Okay , now i tried when modal is inside in the form, if all conditions remain same but ->
--- if we assign 'button to submit from' in FORM to none, it works, as button component also have SHOWMODAL listener
But yeah !! the functionality should also work when the button is choosen in FORM submit,

**Comment by DevangAgarwal93** [comment]
We do not allow modal to be added to a form now. Hence closing this issue.
