### ISSUE TITLE
Add option to programatically change value of cells of a column in table

### ISSUE THREAD

**Issue by shubh22** [ToolJet/ToolJet#5801]
Assuming the column is of type number and getting data from a query. 
Business logic requires this number to be added with a constant 5, then the developer should be able to specify at the column level to add 5 in all the cell values. 
e.g. - {{current + 5}}

**Comment by rhuanbarreto** [comment]
Can't this be done with a transformation instead? This has the potential to affect sorting and filtering once the value in the state is different than the value displayed on the table.

**Comment by shubh22** [comment]
This feature is available now.
