### ISSUE TITLE
Pagination improvements in listview component

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#5814]
### What is the expected behaviour?
User should be able to see the proper data on the page as per provided number of rows per page. Pagination behaviour should be consistent across all the components.

### What is the current behaviour?
For listview:
- if user provides huge number for 'rows per page' field (from other page except first one), data is not appearing for listview unless user navigates back to the first page
- if user provides input with different data type (string/array) than the expected one (number), user can see incorrect pagination information, also NAN is appearing on the screen

### How to reproduce the issue?

1. Drag listview
2. Enter invalid input for 'rows per page' field
3. Notice the component behaviour after correcting the inputs

**Comment by stepinfwd** [comment]
Not able to replicate this issue @dishag18 
cc : @shubh22
