### ISSUE TITLE
Unable to control Text component inside Form component

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#5819]
### Version Information
v2.2.2-ee2.0.5-cloud2.0.1

### Environment
ToolJet Cloud 

### What is the expected behavior?
While trying to control(Set Text/ Set visibility) the `text` component inside a `form` component, it is expected to update accordingly. 

### What is the current behavior?
The component text control actions are not reflected inside the form component. 

### How to reproduce the issue?
1. Add a form component
2. Add a text component inside the form component
3. Add a button component inside the form component
4. Set an event to button, On click: Control component; set an action Set text/ Set visibility
5. Try to trigger the action

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/34749692/226980257-ea515d39-30e5-4d77-a3d5-ce7eeb7665a2.png)

### Please provide any traces or logs that could help here.
No logs were found.

### If the bug is confirmed, would you be willing to submit a PR?

**Comment by sherfin94** [comment]
@stepinfwd , as described in #6893, expose a separate key called `children` and in that expose all the child components and their CSA, the `data` key should remain the same.
