### ISSUE TITLE
Unable to delete or edit newly added elements inside a  container widget.

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#582]
### What is the expected behaviour?
 Should be able to delete or remove newly added elements inside a  container widget.
### What is the current behaviour?
Unable to delete or remove newly added elements inside a  container widget.

### How to reproduce the issue?

1. create an app
2. add a container widget
3. add a button to the container widget
4. try to delete the button

### Screenshots or Screencast
https://www.loom.com/share/ad911ab3f7f643ff9a12803ff656cb79

**Comment by arpitnath** [comment]
Not only button but the same behaviour can also be observed with other widgets too

https://www.loom.com/share/2cd43333466f444c83bc31aeb7543f1f

**Comment by sherfin94** [comment]
I'm working on this.
