### ISSUE TITLE
fix the typo: `Json description` to `JSON description`

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5833]
### What is the issue?

The title for the JSON description is `Json description` which should be `JSON description`

### What is the solution?

Fix the typo `Json` to `JSON`

### How to reproduce the issue?

1. Add a chart component on the canvas
2. Edit its properties
3. Enable `Use Plotly JSON schema`
4. Check that the field title for JSON description is `Json description`

### Screenshots or Screencast

<img width="969" alt="Screenshot 2023-03-24 at 10 42 24 AM" src="https://user-images.githubusercontent.com/25361949/227431203-7dcefbf4-a380-4c32-9af6-084b821dcdc1.png">

**Comment by satishkumarsajjan** [comment]
Hey can you assign me this issue. I will work and send you PR.
