### ISSUE TITLE
Login fails if tooljet address change

### ISSUE THREAD

**Issue by rhuanbarreto** [ToolJet/ToolJet#5845]
Steps to reproduce: 

- Self Host Tooljet in an address (example.com)
- Register your account (email a@a.com) in the first run
- Change the address of your tooljet (example2.com)
- Try to login. You get "Invalid Credentials" message
- Try to register an account with the same email. You get an error "Email already exists"

**Comment by gsmithun4** [comment]
@rhuanbarreto you should change .env file, `TOOLJET_HOST`

**Comment by rhuanbarreto** [comment]
`TOOLJET_HOST` is correctly configured as an environment variable before and after changing the address.

**Comment by rhuanbarreto** [comment]
Tooljet is behind an envoy proxy in k8s (Azure Container Apps). But address is not in a folder.

**Comment by adishM98** [comment]
@rhuanbarreto could you check the Envoy proxy if the host is changed there.

**Comment by rhuanbarreto** [comment]
The host in envoy is the same as it's configured in tooljet. I made an echo function and the "host" header received is also the same as the url.

**Comment by adishM98** [comment]
Just a test case, could try changing it back to the old host url which you set earlier (example.com) and see if your getting the error ?

**Comment by adishM98** [comment]
Just a test case, could try changing it back to the old host url which you set earlier (example.com) and see if your getting the error ?

**Comment by adishM98** [comment]
Just a test case, could try changing it back to the old host url which you set earlier (example.com) and see if your getting the error ?

**Comment by rhuanbarreto** [comment]
@adishM98 I can't. Addresses in azure container apps have a unique component.

**Comment by adishM98** [comment]
@rhuanbarreto when you invite url was it with the first host url (example.com) or after the new host (example2.com)

**Comment by rhuanbarreto** [comment]
Sorry for that. I had a typo on the email. Discovered after doing a SELECT * from users in the psql
