### ISSUE TITLE
In new version dropdown, default select current version

### ISSUE THREAD

**Issue by jibe-b** [ToolJet/ToolJet#5852]
When creating a new version, the default selected upstream version is the first created version.

![image](https://user-images.githubusercontent.com/6146483/227951438-9047d64f-99e7-4a15-9f0c-d48310310a27.png)

It would save a few clicks that the default selected version be the current version (not the last created but the "editingVersiong").

**Comment by shubh22** [comment]
Duplicate #5732

**Comment by withshubh** [comment]
Hey @jibe-b - Thanks for creating the issue. Closing this one as this is a duplicate of #5732.
