### ISSUE TITLE
Range slider with two handles value input error

### ISSUE THREAD

**Issue by gzarruk** [ToolJet/ToolJet#5855]
### Version Information
v2.2.1

### Environment
ToolJet Cloud

### What is the expected behaviour?
No error in debugger when a list with two values is given

### What is the current behaviour?
When providing the field Value with a list, for example `{{[12, 18}}`, the range slider displays the correct values but the debugger outputs the error: 

> Invalid property detected: Expected the value to satisfy a union of `string | number`, but received: 12,18

But there is no error.

### How to reproduce the issue?

1. Insert range slider component
2. In field `Value` type `{{[12, 18]}}
3. Enable `Two handles`

### Screenshots or Screencast

https://user-images.githubusercontent.com/24595022/228148831-b3be85ba-1233-4d23-b1bc-1211c40c645b.mov

### Please provide any traces or logs that could help here.

 [Component rangeslider1 - Value]Invalid property detected: Expected the value to satisfy a union of `string | number`, but received: 30,80.

### If the bug is confirmed, would you be willing to submit a PR?

**Comment by shubh22** [comment]
Bug is not present in develop branch. Will be fixed in next release.
