### ISSUE TITLE
Add the Placeholder property to the Dropdown component

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#5886]
### Is your proposal related to a problem?
The component "Dropdown" do not offer the property to set a placeholder text.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/34749692/228894531-48e44981-b63a-48ea-87b7-80a8df9520ed.png">

### Describe the solution you'd like
Add the Placeholder property to the "Dropdown" component.

For inspiration, check out the "Text input" component's Placeholder property, expecting the same for the Dropdown component.

**Comment by shreyashghadge11** [comment]
@tejakummarikuntla claim

**Comment by munnokd** [comment]
Hey @tejakummarikuntla can I work on this issue?

**Comment by withshubh** [comment]
Hey @shreyashghadge11 - thanks for showing interest in contributing to ToolJet. Assigned this issue to you.

**Comment by withshubh** [comment]
> Hey @tejakummarikuntla can I work on this issue?

Hey @munnokd - Sorry, the issue has been assigned to Shreyas, we assign issues on a first come first served basis. Could you please look for any other open issues?

**Comment by shreyashghadge11** [comment]
![image](https://user-images.githubusercontent.com/55745865/229492435-1059922f-274c-41af-99e0-ce9ed89bf495.png)

**Comment by tejakummarikuntla** [comment]
Hey @shreyashghadge11 , the label for the Dropdown component is like a description to the left of the dropdown.
In the image you shared, the Lable value "Hello" was set to the dropdown box's left as a title/description. Could you please re-check?

**Comment by shreyashghadge11** [comment]
Yes @tejakummarikuntla so what does placeholder over here mean if not label

**Comment by tejakummarikuntla** [comment]
It is similar to the "Text input" component's [placeholder](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder) property, @shreyashghadge11 . It should help to specify a hint to describe the expected value of the dropdown

**Comment by shreyashghadge11** [comment]
@tejakummarikuntla for that reason we have the label to specify what the dropdown is for like for gender or category like. You have label to specify it.

**Comment by shreyashghadge11** [comment]
Also we can have placeholder in input box as it contains default dropdown value
