### ISSUE TITLE
Typo in event handler screen in page menu

### ISSUE THREAD

**Issue by shubh22** [ToolJet/ToolJet#5893]
<img width="418" alt="Screenshot 2023-03-31 at 1 38 58 PM" src="https://user-images.githubusercontent.com/2677855/229063404-e6b56e4e-92e0-4445-b435-93393584c2b5.png">
The text "This query doesnt have any event handlers" should be changed to "This page doesn't have any event handlers"

**Comment by shreyashghadge11** [comment]
@shubh22 Can I work on this issue?

**Comment by Avirup-001** [comment]
Hi @shubh22 , can you please assign this issue to me? I've already fixed it.
