### ISSUE TITLE
Page Event not able set

### ISSUE THREAD

**Issue by ledison-gomas** [ToolJet/ToolJet#5909]
Page Event not able set

No Model was opening

![image](https://user-images.githubusercontent.com/24950497/229269705-1ff2241d-0006-4a7c-bf24-cf5e4cd66f00.png)

**Comment by shubh22** [comment]
Duplicate - #5894

**Comment by anbraten** [comment]
I had a look at the code, but wasn't able to find the part to fix this one yet.
Its a pretty frustrating issue as its blocking all the page options only accessible by that menu.

@shubh22 Any news on this one from your side?

**Comment by shubh22** [comment]
@anbraten - we have done the fix, it will be released early next week.

**Comment by akhudolev** [comment]
Actially this issue was not fixed. I can still reproduce it using touchbar in 2.6.2 version. When I use mouse for clicking it works as expected.
