### ISSUE TITLE
[docs]: How to use a query inside chart?

### ISSUE THREAD

**Issue by yamelsenih** [ToolJet/ToolJet#5920]
### Summary

Hello, I saw a docs of [Charts](https://docs.tooljet.com/docs/widgets/chart) but I don't create a Crate from some query. 

I don't see a concrete example using a real data instead test data.

Exists a way for know it?

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/chart

### Steps to reproduce the issue

Open any char example and it just show the template and static data but I don't see some real example using query or transformation 

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by withshubh** [comment]
Thanks for creating the issue. We have added examples using plotly in this PR: https://github.com/ToolJet/ToolJet/pull/5875
You can check the docs here: https://docs.tooljet.com/docs/widgets/chart/#using-plotly-json-chart-schema
Closing the issue.

**Comment by abulka** [comment]
How to set the Chart data from a query? Having hard wired JSON for the Chart is a bit limiting.
