### ISSUE TITLE
Unnecessary UI component on dark mode app loading.

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#5921]
### Environment
Develop v2.3.1

### What is the expected behaviour?
On application load page should be blank if there is any delay. 

### What is the current behaviour?
A rectangular box is visible on app load.

### How to reproduce the issue?

1. Change the app to Dark mode.
2. Open an APP.

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2023-04-03 at 5 20 59 PM" src="https://user-images.githubusercontent.com/20367955/229701175-46351594-22a4-41cd-8e12-e9f24929cc85.png">

### Any possible solutions?
The page response on load should be similar to the on which is present on light mode.

**Comment by yashrajbothra** [comment]
Hii emidhun, I would like to take this issue.

**Comment by withshubh** [comment]
Hey @yashrajbothra - Unfortunately, this issue has been already fixed interally. Please feel free to choose other open issue with `good first issue` or `up for grabs` label.
