### ISSUE TITLE
Expired slack invitation link

### ISSUE THREAD

**Issue by sebastian-jansson** [ToolJet/ToolJet#5923]
[Slack invitation link ](https://tooljet.slack.com/join/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg#/shared-invite/error)on website + github is no longer active.

![image](https://user-images.githubusercontent.com/54795430/229705331-3ff608e4-4b9c-4310-8aa3-91923fa193dd.png)

**Comment by withshubh** [comment]
Hey @sebastian-jansson - Thanks for creating the issue. We will fix this issue soon.

**Comment by shubh22** [comment]
Issue has been fixed.
