### ISSUE TITLE
"Could not clone the app" error

### ISSUE THREAD

**Issue by lukasugar** [ToolJet/ToolJet#5928]
### Version Information
v2.2.2
### Environment
Docker

### What is the expected behaviour?
I want to clone an app. 
### What is the current behaviour?
When I press "Clone app", nothing happens for a second and then a message "Could not clone the app" pops up.
### How to reproduce the issue?

1. Click on an existing app's three dots
2. Click "Clone app"
3. Error message pops up

### Screenshots or Screencast
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/22435018/229799365-7025b099-bd76-4052-80cb-77c762cb77dd.png">

I do have all the permissions:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/22435018/229799966-757abd07-33d2-4f0f-be56-a3739003cb6a.png">
(The account I'm logged with is in the Admin group)

**Comment by thehacklady** [comment]
Not able to replicate above issue. Closing it.
