### ISSUE TITLE
Bounding box cannot be prepopulated

### ISSUE THREAD

**Issue by lukasugar** [ToolJet/ToolJet#5929]
### Version Information
v2.2.2
### Environment
Docker

### What is the expected behaviour?
I'm using BoundedBox. I want to populate it with bounding boxes I already have.

Then users can:
- leave the correct ones
- modify/delete the existing ones
- add new bounding boxes

### What is the current behaviour?
When I programmatically add annotation object to the BoundBox object, it isn't shown on the image. I'd expect that it's shown on imagen (bug 1)

After programmatically adding an image to the annotations, if a new boundind box is drawn, it overwrites the programmatically driven one (bug 2).

### How to reproduce the issue?

1. Add Bound Box
2. Run javascript query to add an annotation programmatically:
```
var new_annotation = {}
new_annotation.type = 'POINT'
new_annotation.x = 20.0
new_annotation.y = 20.0
new_annotation.width = 10.0
new_annotation.height = 10.0
new_annotation.text = 'Tree'
new_annotation.id = 'd6b0e0ff-358f-4e34-b6e4-7d2fe5304ae5'

components.boundedbox_2.annotations.push(new_annotation)
```
3. The component now has the new annotation in it, but it's not shown on the image (Screenshot 1). This is the first bug.
4. Draw new bounding box on the image.
5. The new bounding box is shown on the image, but the programmatically added bounding box is removed from annotations (Screenshot 2).

### Screenshots or Screencast
Screenshot 1:
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/22435018/229824937-f32c7e4b-a6eb-43c2-8409-c1eff2c4da3f.png">

Screenshot 2:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22435018/229825632-02a48e77-b114-454f-9420-28171bb84346.png">

**Comment by lukasugar** [comment]
Hey all,any updates on this? 🤗

**Comment by kavinvenkatachalam** [comment]
@lukasugar Thanks for the issue. I can see that you're update the object directly using JS which is not recommended. 

`components.boundedbox_2.annotations.push(new_annotation)`

We will try to add a property for a default value.
cc: @shubh22 @johnsoncherian

**Comment by lukasugar** [comment]
Thanks for the comment! I've tried using `.push` instead, but it doesn't change the behavior, as expected.

Adding the property to add default value sounds great 🚀 
This feature is very important to my team, let me know if we can help by testing some early versions of the new feauture.

**Comment by lukasugar** [comment]
Hi @kavinvenkatachalam , @shubh22 , @johnsoncherian , is there an ETA for this fix?
We'd like to have it in our project, but need to know if it's coming or if we should look into alternatives 😐

**Comment by kavinvenkatachalam** [comment]
Hey @lukasugar - We're working on it and an ETA will be 2 to 3 weeks.

**Comment by lukasugar** [comment]
@shubh22 great to see that this is included in a milestone 🙌  When can we expect 2.8.0 to be released?

**Comment by lukasugar** [comment]
Hey @shubh22 @withshubh is the fix planned for deployment this week?

**Comment by kavinvenkatachalam** [comment]
Hey @lukasugar - The fix will be available by this week
