### ISSUE TITLE
[Modal Widget] Unable to delete elements from inside modal widget

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#595]
### Version Information
Latest
### Environment
Docker

### What is the expected behaviour?
Able to delete a widget from modal window

### What is the current behaviour?
Unable to delete a widget inside a modal window

### How to reproduce the issue?

- Add a modal
- Add elements inside modal (ex:  Text input)
- Try to delete the newly added element

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/12490590/130568384-5b4b4275-0686-4cb3-81fa-d9435d0cba27.png)

**Comment by virajbahulkar** [comment]
@Navaneeth-pk this is can be closed as it is fixed in this (commit)[https://github.com/ToolJet/ToolJet/pull/641/commits/7ac7f6cd56b5cb319107262d2f369d6162f44a8b] of (PR)[https://github.com/ToolJet/ToolJet/pull/641]
