### ISSUE TITLE
box-shadow should be applicable on the border radius and not the actual component shape

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5959]
### What is the expected behaviour?

When we change the border radius of a component(let's say button) the box shadow should be applied on the current shape and not the actual shape of the component.

### What is the current behaviour?

When we change the border radius of a component the box shadow should is being applied to the actual shape of the component.

### How to reproduce the issue?

1. Drag button on the canvas
2. Change border radius
3. Add a box-shadow

### Screenshots or Screencast
![Screenshot 2023-04-06 at 7 43 56 PM](https://user-images.githubusercontent.com/25361949/230432434-1bac5a85-db6f-4166-b928-96483bbf2469.png)

**Comment by mikebarr24** [comment]
@shubh22 Could I take a look at this?

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,please assign it to me

**Comment by withshubh** [comment]
Hey @mikebarr24 & @karthiknadar1204 - Sorry but this is not open for community members. Please find issues with `up-for-grabs` or `good-first-issue` label
