### ISSUE TITLE
Bug with OAuth 2.0 authorization

### ISSUE THREAD

**Issue by NazarNazaryshyn** [ToolJet/ToolJet#5961]
Have problem with OAuth2.0 authorization after redirection from Keycloak login page listed on the screen below

![image](https://user-images.githubusercontent.com/94219552/230498854-56f12b92-38f3-47ac-85bb-fc3e68656dcc.png)

**Comment by withshubh** [comment]
Hey @NazarNazaryshyn - Thanks for creating the issue. I'll check this and get back to you.

**Comment by gsmithun4** [comment]
@NazarNazaryshyn Please share more details
- Oauth provider used
- screenshot of your REST API data source configurations (masking credentials)

**Comment by shubh22** [comment]
Closing it since there is no response from the user.
