### ISSUE TITLE
Inverted drop-downs (soar-ups? :grimacing:)

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#598]
### Is your proposal related to a problem?
Whenever a drop-down is displayed and it cuts through the boundary of the viewport, a portion of the drop down is not displayed and also makes a scroll bar appear, and that scroll-bar shrinks infinitely as we scroll down, thereby never being able to actually scroll down.

https://www.loom.com/share/50478500acb345b18c4011625f500f87

### Describe the solution you'd like

If the height of the dropdown is greater than the distance between viewport bottom and the origin of the dropdown, display an inverted drop-down, thereby avoiding the disruption of the app boundary.

**Comment by ampsteric** [comment]
I want to give this one a try, please assign me this issue.

**Comment by Bivas-Biswas** [comment]
can you share screenshot ? I didn't find anything . 😕
