### ISSUE TITLE
Add support to generate `PDF` file using generate file action

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5981]
### Is your proposal related to a problem?

When we add an action to generate a file to the event handler, we only get two options: `CSV` and `Text`.  It should also include an option to generate a `PDF` file from the provided data(array of objects)

### Describe the solution you'd like

- Add a button on the canvas
- Add an event handler -> select `Generate File action`
- On the `Type` dropdown, you'll find `CSV` and `Text`

Add an option to select the Type as `PDF` and provide the name and data dynamically.

### If the feature is approved, would you be willing to submit a PR?
No

**Comment by sumitshinde-84** [comment]
Can you provide playground link ?

**Comment by withshubh** [comment]
> Can you provide playground link ?

Hey @sumitshinde-84 - I did not understand, could you please tell what's playground link?

**Comment by tejakummarikuntla** [comment]
If you are asking about the ToolJet application builder, you should be able to find it once your sign in and create a new app,
Could you elaborate on the question?

**Comment by sumitshinde-84** [comment]
![toolJet](https://user-images.githubusercontent.com/110285294/231458020-d97f5d2b-2271-4259-84c9-e0be7f1cecb8.png)

Is it correct that this button needs a "Generate PDF" feature?

**Comment by Sonali-Behera** [comment]
Hey, I would love to work on this issue. Please assign this to me.

**Comment by withshubh** [comment]
Hey @Sonali-Behera - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.
Please feel free to join our [slack community](https://tooljet.com/slack) if you have any questions.

**Comment by mud1tx** [comment]
@withshubh I can work on this issue can you please assign me?

**Comment by withshubh** [comment]
Hey @Sonali-Behera - Any update on the PR?

**Comment by withshubh** [comment]
Unassigned @Sonali-Behera since there was no update for a long time.

**Comment by nemarugommula** [comment]
Hey @withshubh, I'd like to work on this issue, I have changes ready in my branch, Could you assign it to me? Thanks!
