### ISSUE TITLE
Add page name in delete page confirmation popup

### ISSUE THREAD

**Issue by shubh22** [ToolJet/ToolJet#5991]
When a user is trying to delete a page, they see a popup to confirm the deletion.
In this popup, a user should be shown the name of the page as well and not just the generic message to make sure that user is deleting the right page.

![Screen Shot 2023-04-07 at 15 04 29](https://user-images.githubusercontent.com/2677855/231074219-12c414b9-156b-4716-a0b7-0ea2aa45c443.png)

The message should say - 
Do you really want to delete <b>{{page name}}</b> page?

**Comment by mittalsam20** [comment]
Hello @shubh22 
This issue seems like a good start. I would love to work on this issue. Could you please assign it to me?

**Comment by withshubh** [comment]
> Hello @shubh22 This issue seems like a good start. I would love to work on this issue. Could you please assign it to me?

Hey @mittalsam20 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by apshada** [comment]
Hello @withshubh, can I work on this issue?

**Comment by withshubh** [comment]
Hey @mittalsam20 - Any update on the PR for this issue?
