### ISSUE TITLE
Fix typo in app builder empty canvas text

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5995]
### What is the current behaviour?
When you create a new application on ToolJet, the canvas has a text says:
```
You haven't added any components yet. Drag components from the right sidebar and drop here. Check out our guide on adding widgets.
```

### What is the expected behaviour?
Rename the widgets to components
```
You haven't added any components yet. Drag components from the right sidebar and drop here. Check out our guide on adding components.
```

### How to reproduce the issue?

1. Create a new application
2. Check the text on the center of the canvas

![Screenshot 2023-04-11 at 3 58 36 PM](https://user-images.githubusercontent.com/25361949/231148534-bbfc3e8d-bad7-4b81-8403-f4dca5de9e01.png)

**Comment by LalitChauhan27** [comment]
Hello @withshubh, can I work on this issue?

**Comment by withshubh** [comment]
Hey @LalitChauhan27 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.
Feel free to join [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by rajarshisamaddar** [comment]
Hey @withshubh I would like to work with @LalitChauhan27 on this issue if possible.

**Comment by LalitChauhan27** [comment]
Hey @withshubh, I had made a pull request regarding the issue. Can you please review it? #6005

**Comment by withshubh** [comment]
Hey @LalitChauhan27 - Would it be possible for you to fix the above typo as well in the PR that you created?
