### ISSUE TITLE
Pagination component's length increases with number of pages.

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#6017]
### Environment

    ToolJet Cloud / Docker / Linux / MacOS 

### What is the expected behaviour?
The length of the pagination component should not change with the number of pages.
It should be something like the screenshot.
![image](https://user-images.githubusercontent.com/20367955/231371110-112a3aa4-6768-4b0b-8809-e09813166102.png)

### What is the current behaviour?
Pagination component's length increase with the number of pages.

### How to reproduce the issue?

1. Create an app.
2. Drop a pagination component.
3. Set the number of pages to a higher number.

### Screenshots or Screencast
![Screenshot 2023-04-12 at 11 58 37 AM](https://user-images.githubusercontent.com/20367955/231371548-8aad2f88-7307-4ebc-8997-8904e2118e19.png)

### Any possible solutions?
We should use something like the expected behaviour.

### Can you identify the location in the driver source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by surajsingh542** [comment]
Can I be assigned on this task?

**Comment by surajsingh542** [comment]
Hello @emidhun @shubh22 Can I get assigned to work on this issue?

**Comment by surajsingh542** [comment]
Hello @emidhun Can I get assigned to work on this issue?

**Comment by iSatVeerSingh** [comment]
@shubh22 Is this issue still needs to be resolved?

**Comment by emidhun** [comment]
@sherfin94 Please priorities the issue.

**Comment by sunnykantkr** [comment]
I am facing the same issue with the pagination component. It should add ellipsis in between like reported by @emidhun


![image](https://github.com/ToolJet/ToolJet/assets/19726703/45fc333f-8d73-4d4e-99aa-b9a2ede302b9)

Thanks!!

**Comment by emidhun** [comment]
Closing this issue since it is duplicate of #8684 .
