### ISSUE TITLE
Add close on clicking outside property in modal widget

### ISSUE THREAD

**Issue by kavinvenkatachalam** [ToolJet/ToolJet#6033]
### Is your proposal related to a problem?

In the editor, we're not closing the modal when we click on the backdrop. But in the viewer, the modal is getting closed when the backdrop is clicked. This is creating a confusion and it needs to be consistent in both viewer & editor

### Describe the solution you'd like

A new property can be added to the modal `close on clicking outside` and closing can be decided by the property when the backdrop is clicked

### Describe alternatives you've considered

No

### If the feature is approved, would you be willing to submit a PR?

NA

**Comment by khushi89012** [comment]
Modal will automatically close on clicking outside or you can add property on mui 

<Button onClick={handleOpen}>Open modal</Button>
<Modal
  open={open}
  onClose={handleClose}
  aria-labelledby="modal-modal-title"
  aria-describedby="modal-modal-description"
>
  <Box sx={style}>
    <Typography id="modal-modal-title" variant="h6" component="h2">
      Text in a modal
    </Typography>
    <Typography id="modal-modal-description" sx={{ mt: 2 }}>
      Duis mollis, est non commodo luctus, nisi erat porttitor ligula.
    </Typography>
  </Box>
</Modal>
