### ISSUE TITLE
Change text of CTA for first application

### ISSUE THREAD

**Issue by shubh22** [ToolJet/ToolJet#6052]
Change text from "New app from scratch" to "Create new application"
![ToolJet-Dashboard (3)](https://user-images.githubusercontent.com/2677855/232475677-6599d98e-65b7-4744-a73d-7b28935fec01.png)

**Comment by snehal741** [comment]
Hey @shubh22 can I work on this issue?

**Comment by withshubh** [comment]
> Hey @shubh22 can I work on this issue?

Hey @snehal741 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.
Please feel free to join our **[Slack Community](https://tooljet.com/slack)** if you have any questions.

**Comment by k-deepak04** [comment]
@shubh22 shall i work on this ?

**Comment by withshubh** [comment]
> @shubh22 shall i work on this ?

Hey @k-deepak04 - The issue is already assigned to someone. Please find other open issues with `good-first-isssue` or `up-for-grabs`

**Comment by snehal741** [comment]
@shubh22 I have made a pull request #6087 , can you review it?
