### ISSUE TITLE
Date picker on table does not work properly with time

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#6075]
### Environment

    ToolJet Cloud / Docker / Linux / MacOS ...

### What is the expected behaviour?
Date picker in table widget should work properly with time also.

### What is the current behaviour?
Date picker in table widget is not working properly with time.

### How to reproduce the issue?

1. Create an application.
2. Drag & Drop Table on the canvas.
3. Create a runjs for showing date with time.
4. Click on the column & toggle on for show time.
5. Observe

### Screenshots or Screencast

https://user-images.githubusercontent.com/41302917/233249804-25e64a6c-8de0-4b40-a7cd-3fb9850253c2.mov

**Comment by nakulnagargade** [comment]
This issue is fixed with new Date picker revamp in appbuilder-1.6 milestone. Hence closing this issue.
cc: @johnsoncherian
