### ISSUE TITLE
White space is present on the right side 

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#6078]
### What is the expected behaviour?
There should not be any white space.

### What is the current behaviour?
White space is present on the right side on every page after login.

### How to reproduce the issue?

1. Log in
2. Change pages from dashboard/settings/database.
3. Observe.
![Screenshot 2023-04-20 at 10 37 12 AM](https://user-images.githubusercontent.com/41302917/233286919-74bd35aa-1f0a-44d7-b409-8488ffda053c.png)

**Comment by manavsiddharthgupta** [comment]
I have checked the issue and it appears that the white space you mentioned is caused by an unnecessary scrollbar.

**Comment by bottercode** [comment]
I have reproduced the said issue in both chrome and firefox. 
Attached the screenshots below for reference.

Chrome:
![image](https://user-images.githubusercontent.com/74648201/233845985-9e292e7a-c92c-4ad9-b02e-f4e7f5c2ff36.png)

Firefox:
![image](https://user-images.githubusercontent.com/74648201/233846033-d5be8910-5cff-4420-a3ec-b71fbbd0c734.png)

**Comment by stepinfwd** [comment]
This issue is not present in current develop , can u confirm and close @Nandinisaha13
