### ISSUE TITLE
Change cursor to poiner on hover of Page menu options

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6111]
Hovering the cursor on top of the Page menu options shows the `default` cursor 

<img width="814" alt="image" src="https://user-images.githubusercontent.com/34749692/234057949-c6eebdaf-9e90-4a06-a16a-d3feaaa75a26.png">

Change the default cursor to `pointer` on hovering over the Page menu options.

**Comment by vishwakulkarni6116** [comment]
I can take this issue, but I have windows machine. As per contributing.md file Mac OS and Ubuntu machine is specified in setup.

**Comment by tejakummarikuntla** [comment]
Setting up in Mac and Ubuntu is smoother, @vishwakulkarni6116.
You can use the [docker set-up](https://docs.tooljet.com/docs/contributing-guide/setup/docker) for Windows.

Kindly confirm your interest in taking this up. You can choose to set up first and decide.

**Comment by Donbasilpeter** [comment]
Hello I can take this issue if it is not assigned. already tested the issue and fix is ready.
