### ISSUE TITLE
Change cursor to poiner on hover of Global settings toggle options

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6112]
Hovering the cursor on top of the toggles of Global settings options shows the `default` cursor.

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/34749692/234072915-e0813d66-5c7b-45fd-9b60-d583c7df6071.png">

Change the default cursor to the `pointer` on hovering over the toggles of Global Settings options.

**Comment by tejakummarikuntla** [comment]
Sure, thanks for your interest, @Sdaewa . Assigned.

**Comment by Sdaewa** [comment]
Hi @tejakummarikuntla, I am running the frontend locally but its stuck loading. 

<img width="1260" alt="Screenshot 2023-04-25 at 14 01 08" src="https://user-images.githubusercontent.com/30057590/234271070-41f1d541-bc85-40cf-bbdd-8facc786d50f.png">

**Comment by nazrul7711** [comment]
hey @Sdaewa  i also faced the same issue  , follow the set up instruction step by step . here [https://docs.tooljet.com/docs/contributing-guide/setup/macos/]

**Comment by Sdaewa** [comment]
@nazrul7711 thanks for the tip! Already fixed tho
