### ISSUE TITLE
Change cursor to poiner on hover of Global settings width dropdown

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6120]
Hovering the cursor on top of the width dropdown of Global settings shows the `default` cursor.

<img width="475" alt="Screenshot 2023-04-25 at 2 37 39 PM" src="https://user-images.githubusercontent.com/34749692/234230060-b48781b9-2701-43c3-949c-7808345e8d41.png">
Change the default cursor to the `pointer` on hovering over the width dropdown of Global Settings options.

**Comment by tejakummarikuntla** [comment]
Hey @apshada , as you know, this is a `good-first-issue`, let us wait for any interest from first-time contributors to ToolJet. Shall assign this to you if no first-time contributors turn up. Thank you for your understanding.

**Comment by projectnoa** [comment]
Hi @tejakummarikuntla I would like to take on this issue as my first contribution.

**Comment by tejakummarikuntla** [comment]
Thank you for your interest, @projectnoa . Assigned.
For queries related to set-up, you can post them in our #general [slack](https://tooljet.com/slack) channel.

@apshada , kindly explore our `up-for-grabs`

**Comment by projectnoa** [comment]
Hi @tejakummarikuntla 

I'm trying to get the development build running to validate my fix, but I have not been able to get it to run.

For context y tried on: Ubuntu 20.4, Docker, MacOS, even Docker PWD

I keep getting these errors on the server and frontend. PostgREST will not install on Ubuntu and the database just says redirection unexpected.

In MacOS, postgREST installs but the database wont load anyway.

I have followed all the steps on https://docs.tooljet.com/docs/contributing-guide/setup/ubuntu

I have never been this stomped with trying to get something running. Is there any wisdom that you can provide?

<img width="1392" alt="Screenshot 2023-04-27 at 5 56 28 AM" src="https://user-images.githubusercontent.com/102206/234872875-768140ab-507a-45fd-8236-77882e1de8ec.png">
<img width="1669" alt="Screenshot 2023-04-27 at 5 57 23 AM" src="https://user-images.githubusercontent.com/102206/234872882-bdbf715a-48d6-406e-8d2d-c6a5ff3fca25.png">
<img width="970" alt="Screenshot 2023-04-27 at 6 07 12 AM" src="https://user-images.githubusercontent.com/102206/234872889-2170b903-8ab8-49be-9c87-4bafc79145ec.png">

**Comment by projectnoa** [comment]
Pull request submitted.

https://github.com/ToolJet/ToolJet/pull/6180
