### ISSUE TITLE
Change cursor to poiner on hover of toggle in Share dialogue box

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6121]
Hovering the cursor over the toggle of Share dialogue box shows the `default` cursor.

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/34749692/234233059-b807358c-6a4f-48ed-b78b-a2cdef13b07b.png">

Change the default cursor to the `pointer` on hovering over the toggle.

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @nazrul7711 . Assigned.

**Comment by nazrul7711** [comment]
can u tell me help me with installing @tooljet/plugins/client

**Comment by tejakummarikuntla** [comment]
Hey @nazrul7711 , please follow our set-up guide in the [documentation](https://docs.tooljet.com/docs/setup/). For queries related to installation, you can post in our #general [slack](https://tooljet.com/slack) channel

**Comment by nazrul7711** [comment]
hi @tejakummarikuntla I have made a pull request #6159. kindly review it
