### ISSUE TITLE
After change the share URL, the application show nothing and log shows unauthorized.

### ISSUE THREAD

**Issue by tuutoo** [ToolJet/ToolJet#6139]
### Version Information
2.4.9
### Environment

Docker

### What is the expected behaviour?

Update the application share URL, and user should get a normal webpage.

### What is the current behaviour?

After admin update the share URL, normal user open the new url from workspace, it shows an empty screen, and in the console I can see 401 unauthorized. But if the URL cleared and have default random url, user can get the correct page.

### How to reproduce the issue?

1.  Please see below screen shots to reproduce.

### Screenshots or Screencast

App is working when the url is random. (Admin User)
![image](https://user-images.githubusercontent.com/9068314/234453790-56b15966-3d49-4e54-aeb3-630cd4e45e0d.png)

![image](https://user-images.githubusercontent.com/9068314/234452643-550e14d3-af56-41a5-94ae-7bac86ddda0c.png)

After I update the URL with a custom name. (Admin User)
![image](https://user-images.githubusercontent.com/9068314/234453951-f49303ec-8936-4634-88d3-ca33ef635bae.png)

Normal user refresh the workspace, and click launch.
![image](https://user-images.githubusercontent.com/9068314/234454394-49760584-1189-4dfa-8c75-aeb31c6faa71.png)

The URL seems updated correctly, but content is not shown.
![image](https://user-images.githubusercontent.com/9068314/234453157-d7346909-8cac-4194-afe9-83415bef8027.png)

**Comment by shah21** [comment]
Hi @tuutoo I have tried your steps 
But it seems working for the currently released version 2.5.0. could you please try that version?

**Comment by shah21** [comment]
It seems like 2.4.9 has some issues with custom URLs. So upgrading to the new version will be a good idea @tuutoo

**Comment by tuutoo** [comment]
@shah21 Yes, I can confirm this is solved in v2.5.0

Thanks a lot~
