### ISSUE TITLE
Change cursor to poiner on hover over the toggle in Page settings

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6140]
Hovering the cursor over the "Disable Menu" toggle of Page settings shows the `default` cursor.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/34749692/234490533-f16892b6-ad77-4307-9945-49fccfd73822.png">

Change the default cursor to the `pointer` on hovering over the toggle.

**Comment by SshibamDebnathh** [comment]
hey I can help you with this...

**Comment by tejakummarikuntla** [comment]
Thank you for your interest, @SshibamDebnathh . Assigned.
please follow our set-up guide in the [documentation](https://docs.tooljet.com/docs/setup/) for installation. For queries related to installation, you can post in our #general [slack](https://tooljet.com/slack) channel

**Comment by SshibamDebnathh** [comment]
can you please tell me in which particular folder in can I find the code to make changes? #6140

**Comment by Sdaewa** [comment]
Hi @tejakummarikuntla @SshibamDebnathh I have fixed https://github.com/ToolJet/ToolJet/issues/6112 and I think this one has been solve automatically as the CSS rule I had created applies to this too.
<img width="380" alt="Screenshot 2023-04-26 at 14 04 44" src="https://user-images.githubusercontent.com/30057590/234569896-f78e6a70-bb94-4d5f-8a9c-33f9fa33d805.png">

**Comment by SOMKUVAR** [comment]
I want to work on this.

**Comment by paritbhardwaj019** [comment]
Hey, Can you assign this issue to me ?

**Comment by SOMKUVAR** [comment]
Does it is assigned to me?

**Comment by tejakummarikuntla** [comment]
Hey @SshibamDebnathh , closing this issue as the fix for this issue was in effect from other contributions. Sorry about this.
Kindly review the list of [good-first-issues](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and feel free to comment on the ones you wish to work on.
