### ISSUE TITLE
Sidebar overlaps Global settings modal when clicked

### ISSUE THREAD

**Issue by Sdaewa** [ToolJet/ToolJet#6144]
### Environment

MacOS - Firefox developer edition

### What is the expected behaviour?

When Global settings in clicked the modal should overlap the sidebar

### What is the current behaviour?

Sidebar overlaps Global settings modals when clicked

### How to reproduce the issue?

1. Run project locally
2. Create app
3. Click global settings 

### Screenshots or Screencast

 
<img width="665" alt="Screenshot 2023-04-26 at 14 09 05" src="https://user-images.githubusercontent.com/30057590/234571276-744c5664-8b09-48ce-aba3-da317bc025f2.png">

### If the bug is confirmed, would you be willing to submit a PR?

Yes

**Comment by withshubh** [comment]
Hey @Sdaewa - Thanks for creating the issue. We have replicated it and will fix it soon.
