### ISSUE TITLE
Data is taken from the current version when creating a new version, not from the default version selected in the "version from" dropdown

### ISSUE THREAD

**Issue by Mekhla-Asopa** [ToolJet/ToolJet#6189]
### What is the expected behaviour?
It should take the data from the default version selected in the "version from" dropdown If the other version is not selected from the dropdown.

### What is the current behaviour?
it has taken data from the latest version, not from the default version selected in the "version from" dropdown

### How to reproduce the issue?

1. Login with valid credentials 
2. Create an application (version of an application is "v1")
3. Add a widget on the editor
4. Click on the version field  and click on the "create new version" link
5. Create a new version modal should appear.
6. Enter the "v2" in the "version name" field and Create a new version as "v2" 
7. Repeat step number 4, 5
8. Without changing the "version from" dropdown value, Enter the "v3" in the "version name" field.
9. Click on the "Create new version" button

**Comment by thehacklady** [comment]
Working as expected. Closing.
