### ISSUE TITLE
Server workspace variables with `_` in ther names ain't accessable in the app builder

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6193]
While setting the ToolJet Workspace variables the client variables are working fine with `_` 's b/w the variable names.
But, the servers variables with `_`'s in b/w isn't working as expected.

Steps to reproduce.
1. Set a server workspace variable without  _'s ex: BASEURL
2. Set an other server workspace variable with _'s ex: BASE_URL
3. make an API request with %%server.BASEURL%% , it should work fine.
4. Try to make an API request with  %%server.BASE_URL%% , it would throw an error.

**Comment by thehacklady** [comment]
Not needed.
