### ISSUE TITLE
Color Difference In Toggling Icons.

### ISSUE THREAD

**Issue by prajapatiomkar** [ToolJet/ToolJet#6197]
## On Desktop Icon
![image](https://user-images.githubusercontent.com/72141037/235285760-b2755a35-c1b0-4a6a-ba58-9678a50567ff.png)
## On Mobile Icon
![image](https://user-images.githubusercontent.com/72141037/235285798-e81d5adf-7e9b-42d1-8710-6ee19be57704.png)

### The color of desktop icon should be same as the mobile icon.

# I try to do it but unable to find how to make changes in file to reflect the change in project, please guide me :)
## Here is the code to navigate 👇
![image](https://user-images.githubusercontent.com/72141037/235285961-19581818-d3f8-4f08-8bbe-f72404a2c606.png)

**Comment by Sheikh-JamirAlam** [comment]
Can I work on it?

**Comment by Sheikh-JamirAlam** [comment]
@withshubh Hey man can you help me setup this repo locally?
I am using Ubuntu and I am following this guide to setup my project locally: https://docs.tooljet.com/docs/contributing-guide/setup/ubuntu.
While running npm run --prefix server db:reset command I am facing this error. Can you tell me what to do?

![Screenshot from 2023-04-30 21-12-33](https://user-images.githubusercontent.com/48979376/235362535-aa77f66f-3947-4885-b8c9-da100899f9d3.png)
