### ISSUE TITLE
Update the text and UI of `Continue Editing` query popup modal

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6207]
### What is the current behaviour?

When you edit a query and switch to another query without saving the changes, a modal pops up to continue editing or Discard the query changes. The `Continue editing` button is red, and the `Discard Changes` is white.

### What is the expected behaviour?

Change the text on the popup modal and button placements & color according to the UI below:

![Screenshot 2023-05-01 at 7 31 21 PM](https://user-images.githubusercontent.com/25361949/235594546-ac73040d-e08c-405f-ab5a-f70885d0e2f5.png)

### Steps to reproduce
1. Open ToolJet, create a new app
2. Create 2 queries and save them
3. Edit a query1 and switch to query2 without saving the query1
4. A modal will popup

**Comment by Mohith234** [comment]
Seems like a good first issue, I would like to work on this

**Comment by withshubh** [comment]
> Fix 'Continue Editing' query modal UI #6221

Hi @Mohith234 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by Mohith234** [comment]
@withshubh I have made a PR. Please review it
