### ISSUE TITLE
Dashboard: Inconsistency in naming convention

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6217]
### What is the expected behaviour?
The naming convention should be consistent, for hover over pop up and actual tab name
-Dashboard vs Applications : 'Dashboard'
-Global Datasources vs Datasources - 'Data sources'
-Marketplace (Beta) vs Integrations - 'Marketplace'
-Comment notifications vs Notifications 'Notifications'
-Users vs Users & permissions - 'Users'
-Profile vs Profile settings - this is fine as it is. 

### What is the current behaviour?
The tab names appearing on hovering over the left side panel vs the actual tab name displayed on the screen are inconsistent

### How to reproduce the issue?

1. Login to tooljet application
2. On Dashboard screen, hover over all the left side options and verify the names displayed on the actual screen vs pop up appearing by hover over the menu
3.

**Comment by JayeshJanyani** [comment]
@shubh22 I am willing to work on this, please assign it to me

**Comment by iSatVeerSingh** [comment]
@dishag18 I want to work on this issue. Please assign me.

**Comment by iSatVeerSingh** [comment]
@withshubh Please take a look at the PR.
