### ISSUE TITLE
get Error query could not be completed

### ISSUE THREAD

**Issue by kasun-sonic-devs** [ToolJet/ToolJet#6254]
### Environment
ToolJet Cloud 

### What is the expected behaviour?
I want to when i click the button save input field data in mysql database

### What is the current behaviour?
When I try to insert data to mysql database getting query could not be completed error but I insert same query in mysql command in workbench It working

### How to reproduce the issue?

1.
2.
3.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/110441833/236130976-0e34eac0-8eb7-4125-bf74-6d53ce894acf.png)
![image](https://user-images.githubusercontent.com/110441833/236131129-fd43a263-121a-47da-bdfd-42f67bebb8b4.png)

### Please provide any traces or logs that could help here.
![image](https://user-images.githubusercontent.com/110441833/236131270-7b686754-bc07-472b-b001-65920722eb94.png)

**Comment by akshaysasidrn** [comment]
Hey @kasun-sonic-devs, could you check the browser network logs and attach the error response message when you try running the query? The whole error message isn't visible in the debugger.

**Comment by GrowwithNaveen** [comment]
@kavinvenkatachalam We are not really sure on the issue. We cannot see the entire error message on debugger as it is truncated. Can we create a new item for showing the full message.
