### ISSUE TITLE
[dark mode] fix text color of `Time` in datepicker

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6270]
### What is the current behaviour?

In dark mode, the color of the text should be white but its black.

### How to reproduce the issue?

1. Switch to dark mode
2. drag a datepicker
3. enable time selection from datepicker property
4. Check the color of the `Time`

### Screenshots or Screencast

<img width="656" alt="Screenshot 2023-05-05 at 6 00 14 PM (1)" src="https://user-images.githubusercontent.com/25361949/236473181-1416696b-2de5-4164-8187-463bea7d2024.png">

**Comment by wxomi** [comment]
I would like to work on this issue.

**Comment by wttc-nitr** [comment]
Is it still open ? 
I can fix this bug. 
Please assign it to me.

**Comment by withshubh** [comment]
> Is it still open ? I can fix this bug. Please assign it to me.

Hey @wxomi - We have assigned another issue to you.

Hey @wttc-nitr - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by wttc-nitr** [comment]
@withshubh , Is there any section for FAQs ? I having some problems setting up the project locally.
I'm following given setup-guide for Ubuntu (https://docs.tooljet.com/docs/contributing-guide/setup/ubuntu).

At step 5:

> 5. Set up database
`npm run --prefix server db:reset`

I got the following error message:
> server@0.0.1 db:reset
 npm run db:drop && npm run db:setup
server@0.0.1 db:drop
ts-node ./scripts/drop-database.ts
/bin/sh: 1: Syntax error: redirection unexpected

**Comment by withshubh** [comment]
Hey @wttc-nitr - Could you please join our [slack community](https://tooljet.com/slack) and ask the question there?

**Comment by mikebarr24** [comment]
@withshubh Could I take a look at this?

**Comment by withshubh** [comment]
Sure @mikebarr24 - Assigned it to you.

**Comment by iSatVeerSingh** [comment]
@mikebarr24 Are you working on this issue. If not please assign me.
