### ISSUE TITLE
[dark mode] fix color of time selection box in datepicker

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6271]
### What is the current behaviour?
In dark mode, the color of the time selection box in datepicker should be dark.

### How to reproduce the issue?
1. Switch to dark mode
2. drag a datepicker
3. enable time selection from datepicker property
4. Check the color of the Time selection box

### Screenshots or Screencast
<img width="656" alt="Screenshot 2023-05-05 at 6 00 14 PM" src="https://user-images.githubusercontent.com/25361949/236473985-04bc734b-cf0b-4137-b537-ce1b035c4dbb.png">

**Comment by wxomi** [comment]
I would like to work on this issue

**Comment by JayeshJanyani** [comment]
I too can work on this.

**Comment by Sheikh-JamirAlam** [comment]
The selection items are all white background. Should be make dark themed.

![image](https://user-images.githubusercontent.com/48979376/236517523-3c80583e-26ef-4cc2-b7c6-c0630eb03f55.png)

**Comment by PrasannaBH** [comment]
Hey, i would like to work on this issue

**Comment by Sheikh-JamirAlam** [comment]
@withshubh Came up with this. Unfornately I don't think it is possible to edit the color for the clock icon in the time section.
![image](https://user-images.githubusercontent.com/48979376/236638593-a51fc21e-bea8-434d-9fbe-f4f1bd4b9799.png)

**Comment by PrasannaBH** [comment]
@withshubh @Sheikh-JamirAlam 
i pulled the latest code and made changes but i cant see the the clock image that is present in your screenshot

![Screenshot from 2023-05-06 23-38-03](https://user-images.githubusercontent.com/55347026/236640236-d0d6420e-6872-4417-b90e-bae7017c4a7e.png)

**Comment by Sheikh-JamirAlam** [comment]
@PrasannaBH That's weird. I also pulled the latest repo only.

**Comment by withshubh** [comment]
Hey @wxomi - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by PrasannaBH** [comment]
> @PrasannaBH That's weird. I also pulled the latest repo only.

Which branch are you using ? I am using the **develop** branch

**Comment by PrasannaBH** [comment]
Hey @withshubh can you please assign this to me nobody is working. I can make PR for this issue

**Comment by withshubh** [comment]
Hey @wxomi - Any updates on the PR?

**Comment by iSatVeerSingh** [comment]
@withshubh Please assign me.

**Comment by withshubh** [comment]
Hi @JayeshJanyani - Are you still interested in picking up this issue?

**Comment by withshubh** [comment]
@JayeshJanyani  - Thanks for showing interest. Assigned to you.

**Comment by JayeshJanyani** [comment]
> Hey @JayeshJanyani - Any updates on the PR?

@withshubh Can you please assign it to someone else, as I am a bit occupied with another issue.
Thanks in advance.

**Comment by iSatVeerSingh** [comment]
@withshubh Can you please check my PR?

**Comment by atharvnaik1** [comment]
@karan-rathod-316  Please assign me if its still open .

**Comment by atharvnaik1** [comment]
Implemented changes in theme.scss and respective files input.react-datepicker-time__input background color from white to dark mode.
Updated the time popper for dark theme.
