### ISSUE TITLE
[Dark mode]- Calendar popover- Text component is not visible

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6281]
### What is the expected behaviour?
All the components added on calendar popover should be visible in dark mode

### What is the current behaviour?
Text component is not visible

### How to reproduce the issue?

1. Select calendar
2. Add popover
3. Drag few components in popover and switch to dark mode

### Screenshots or Screencast

https://user-images.githubusercontent.com/125240229/236757927-7092a811-9a33-4824-aac1-9c4405598877.mp4

**Comment by iSatVeerSingh** [comment]
@dishag18 @shubh22 I have reproduced it and I have a fix for it. Please assign me.
