### ISSUE TITLE
[table] set maximum height for the cell

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6284]
### What is the expected behaviour?

There should be an option to set the maximum height for the table cell, so that whenever the text is large it gets overflow.

### What is the current behaviour?

Currently, there is no option to set the maximum height for the table cell, causing the cell size to get big if the text is large. 

### How to reproduce the issue?

1. drag a table
2. create a query that returns the data that has large strings
3. load it on the table

### Screenshots or Screencast
![Screenshot 2023-05-08 at 5 09 28 PM](https://user-images.githubusercontent.com/25361949/236814553-a986e19d-a826-417b-bb2a-1f8c94cec167.png)

**Comment by kavinvenkatachalam** [comment]
Adding `on hold` tag as this will change with the new design.  
cc: @sherfin94 @manishkushare

**Comment by johnsoncherian** [comment]
This is handled under issue: https://github.com/ToolJet/ToolJet/issues/8706
And fixed in PR: https://github.com/ToolJet/ToolJet/pull/8764
