### ISSUE TITLE
Cross button to close the pop-up is not consistent with the dark theme

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6285]
### What is the current behaviour?
When we try to change the version name in dark mode, the popup for renaming the version has close button which is not properly visible in dark mode.

### How to reproduce the issue?

1. Open app builder
2. switch to dark mode
3. change the version name from the topbar

### Screenshots or Screencast
![Screenshot 2023-05-08 at 5 33 39 PM](https://user-images.githubusercontent.com/25361949/236820723-51766c3f-8a8e-4fd8-a8cb-ce8e55d96dd1.png)

**Comment by Abjcodes** [comment]
Can I work on this?

**Comment by iSatVeerSingh** [comment]
@shubh22 @withshubh I have reproduced this and I have a fix for this. Please assign me.
