### ISSUE TITLE
[docs]: Fix the broken URL in /contributing-guide/slackcoc

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6302]
### Summary

The hyperlink of "The ADA Initiative" in the [Enforcement](https://docs.tooljet.com/docs/contributing-guide/slackcoc/#enforcement) section is broken.

Broken URL: http://adainitiative.org/2014/02/18/howto-design-a-code-of-conduct-for-your-community/

To fix it, please remove the text and hyperlink "The ADA Initiative".

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/slackcoc/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by PoweredByPorridge** [comment]
May I take this?

**Comment by tejakummarikuntla** [comment]
Hey @PoweredByPorridge , thank you for commenting about your interest; I assigned this to you.

@eshwarhs I'd like to remind that this issue this tagged with the label `good-first-issue`, intending to welcome first time contributors to the project, kindly be sure to comment about your interest to get the issue assigned before addressing it. Thank you for your understanding.
