### ISSUE TITLE
[docs]: Fix the broken URL in /setup/kubernetes

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6303]
### Summary

In the [ToolJet Database](https://docs.tooljet.com/docs/setup/kubernetes/#tooljet-database) section the hyperlink of the text `here` in `2` is broken.
 
![Screenshot 2023-05-09 at 3 18 17 PM](https://user-images.githubusercontent.com/34749692/237059996-23ca4e5a-4cb8-4513-9e7c-a778f8fb773b.png)

Fix the broken hyperlink by replacing it with: https://raw.githubusercontent.com/ToolJet/ToolJet/main/deploy/kubernetes/deployment.yaml

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/setup/kubernetes/#tooljet-database

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by nazrul7711** [comment]
hey @tejakummarikuntla i want to work on the issue

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @nazrul7711 , Assigned this to you.

**Comment by Abjcodes** [comment]
Hey @tejakummarikuntla , Can I fix this ?

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @Abjcodes. Assigned this issue to you.
