### ISSUE TITLE
[docs]: Remove the broken hyperlink in contributing-guide/marketplace/marketplace-setup

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6307]
### Summary

The hyperlink to the text `marketplace` in the section "[Step 2. Enabling the marketplace for your instance](https://docs.tooljet.com/docs/contributing-guide/marketplace/marketplace-setup/#step-2-enabling-the-marketplace-for-your-instance)" is broken

![Screenshot 2023-05-09 at 4 12 31 PM](https://github.com/ToolJet/ToolJet/assets/34749692/e71ebab8-5a64-4395-83ff-d0ae71312027)

To fix it, please remove the hyperlink and set it to plain text "marketplace"

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/marketplace/marketplace-setup/#step-2-enabling-the-marketplace-for-your-instance

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by vizzv** [comment]
please assign me this issue .I am new to opensource but I like to work on it.

**Comment by tejakummarikuntla** [comment]
Thank you for your interest, @vizzv . Assigned this issue to you.
