### ISSUE TITLE
[docs]: fix broken image in deployment doc for google cloud run

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6317]
### Summary

Solution:
- Go to the `docs/docs/setup/google-cloud-run.md` 
- On line number 50 change the image name to `port-and-capacity-postgrest.png`

Note: `docs/docs` is the base directory and is not available on the docs.tooljet.com

### Issue Type

Documentation bug

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Bigboss288** [comment]
please assign the issue to me

**Comment by withshubh** [comment]
Hey @Bigboss288 - Thanks for showing interest in contributing to ToolJet. Assigned it to you

**Comment by Bigboss288** [comment]
Hi @withshubh raised a PR yesterday.Please let me know if there is an issue as I am new to open source contributions.
