### ISSUE TITLE
[docs]: Extra space in page heading

### ISSUE THREAD

**Issue by HassanTanveer** [ToolJet/ToolJet#6328]
### Environment

MacOS

### What is the expected behaviour?

The heading should be `Components: Overview`

### What is the current behaviour?

The heading is `Components : Overview`

### How to reproduce the issue?

1. Go to [Components Catalog Overview](https://docs.tooljet.com/docs/widgets/overview) in docs

### Screenshots or Screencast

![image](https://github.com/ToolJet/ToolJet/assets/57575219/c53f0cd1-0c10-45f0-9a46-cff942c82cb2)

### Any possible solutions?
Fix Heading

### Can you identify the location in the driver source code where the problem exists?
`docs/docs/widgets/overview.md`

### If the bug is confirmed, would you be willing to submit a PR?
Yes!

**Comment by tejakummarikuntla** [comment]
Hey @HassanTanveer , want to re-check if you'd be interested in addressing this issue, can I assign this issue to you?

**Comment by HassanTanveer** [comment]
Yes, please assign this to me

**Comment by withshubh** [comment]
Hey @HassanTanveer - There is another issue assigned to you. Let's get the PR merged for that one. 🙌

**Comment by HassanTanveer** [comment]
Sure, I'll fix the other issue shortly.

**Comment by Bhavyaatrivedi** [comment]
Can assign me this issue

**Comment by tejakummarikuntla** [comment]
Thanks for commenting about your interest @Bhavyaatrivedi , Assigned this to you.

@Mohiit70 I'd like to remind that this issues hold the tag `good-first-issue`in which we welcome new contributors to the project. Before addressing any issues kindly comment about your interest to contribute, and please raise PRs only for the issues that are assigned to you.

 Thanks for your understanding.

**Comment by Mohiit70** [comment]
> Thanks for commenting about your interest @Bhavyaatrivedi , Assigned this to you.
> 
> @Mohiit70 I'd like to remind that this issues hold the tag `good-first-issue`in which we welcome new contributors to the project. Before addressing any issues kindly comment about your interest to contribute, and please raise PRs only for the issues that are assigned to you.
> 
> Thanks for your understanding.

Hi there, thank you for the reminder about the good-first-issue tag. I am definitely interested in contributing to the project and appreciate the opportunity to do so. I will be sure to comment on any issues I plan to work on to avoid any duplication of effort, and I understand that I should only raise pull requests for issues that are assigned to me. Thank you for creating a welcoming environment for new contributors.

**Comment by Bhavyaatrivedi** [comment]
> Thanks for commenting about your interest @Bhavyaatrivedi , Assigned this to you.
> 
> @Mohiit70 I'd like to remind that this issues hold the tag `good-first-issue`in which we welcome new contributors to the project. Before addressing any issues kindly comment about your interest to contribute, and please raise PRs only for the issues that are assigned to you.
> 
> Thanks for your understanding.

**Comment by Bhavyaatrivedi** [comment]
> Thanks for commenting about your interest @Bhavyaatrivedi , Assigned this to you.
> 
> @Mohiit70 I'd like to remind that this issues hold the tag `good-first-issue`in which we welcome new contributors to the project. Before addressing any issues kindly comment about your interest to contribute, and please raise PRs only for the issues that are assigned to you.
> 
> Thanks for your understanding.

Sure sr. I will update it shortly.

**Comment by Bhavyaatrivedi** [comment]
> Thanks for commenting about your interest @Bhavyaatrivedi , Assigned this to you.
> 
> @Mohiit70 I'd like to remind that this issues hold the tag `good-first-issue`in which we welcome new contributors to the project. Before addressing any issues kindly comment about your interest to contribute, and please raise PRs only for the issues that are assigned to you.
> 
> Thanks for your understanding.

Created PR to fix this issue #6390
