### ISSUE TITLE
[docs]: remove the `Tutorial` option from the footer

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6331]
### Summary

Go to the bottom of the docs, you'll find the link to Tutorial is broken. Remove the Tutorial from the footer of the docs.

Solution:
- This can be removed from the docusauaras.config.js file present at the root of the docs folder.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Bigboss288** [comment]
Please assign it to me.
