### ISSUE TITLE
[table] highlighted row color doesn't update when Action button from another row has been clicked

### ISSUE THREAD

**Issue by neshorg** [ToolJet/ToolJet#6334]
### Version Information
2.5.0
### Environment

Docker
### What is the expected behaviour?

When toggle switch for "Highlight selected row" is turned on, I expect the highlighted row color to change to the row on which I used an Action button at the end of it.
### What is the current behaviour?

Clicking on an Action button while toggle switch for "Highlight selected row" is turned on doesn't seem to update the highlighted style color for that row on which the Action button has been clicked. Instead, the highlighted color stays on the last clicked row (where the row has been clicked, not an Action button)
### How to reproduce the issue?

1. Create table
2. Add an Action Button (no event handlers needed)
3. Turn on toggle switch "Highlight selected row"
4. open 'Inspector' and navigate to the Object "selectedRow" of newly created table component (pin inspector window)
5. Select a random row in the table. "selectedRow" will show current highlighted row
6. Now, click within a different row on an Action button at the end of it. "selectedRow" will update nicely, but visually the highlighted row will remain unchanged.

### Screenshots or Screencast

In this screenshot I clicked on the email field of "sam@example.com" in order to select & highlight that row. 
After that, I clicked on the Action button "Button" within the row of 'sarah@example.com '. Notice that "selectedRow" Object will update, but the highlighted row color remains on the row with "sam@example.com":
![image](https://github.com/ToolJet/ToolJet/assets/86983837/f6bdae58-922c-4165-b4e5-f360433db273)

### If the bug is confirmed, would you be willing to submit a PR?
I can't

**Comment by shubh22** [comment]
Will be fixed with #5406
