### ISSUE TITLE
Marketplace builds failing when pull requests are deployed to Render

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#6408]
## Description
Lately, we have noticed a recurring issue with marketplace builds failing during the deployment of pull requests to Render. These failures have a substantial impact on the deployment process and create inconvenience when testing pull requests.

### Expected Behavior:
Marketplace builds should successfully complete when pull requests are deployed to Render, ensuring the proper deployment of changes.

### Actual Behavior:
Currently, we are experiencing consistent marketplace build failures whenever pull requests are deployed to Render. This issue is resulting in deployment issues and delays, and it is specifically impacting the ability to install plugins and uninstall existing ones due to the build failures.

**Comment by GrowwithNaveen** [comment]
This is no longer affected.
