### ISSUE TITLE
[docs]: link `The Ada initiative` on slack code of conduct

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6419]
### Summary

A PR (https://github.com/ToolJet/ToolJet/pull/6383/files) was made to remove `The Ada initiative` from the slack code of conduct. Add it again from where it was removed and change the URL to `https://adainitiative.org/`

Solution:
- Go to the `docs/docs/contributing-guide/slackcoc.md`
- On line number 63 update the info section:
  ```
  Portions derived from the [Django Code of Conduct](https://www.djangoproject.com/conduct/), [The Rust Code of Conduct](https://www.rust-lang.org/conduct.html), and [The Ada Initiative](http://adainitiative.org/) under a Creative Commons Attribution-ShareAlike license.
  ```

### Issue Type

Documentation bug

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by jajjibhai008** [comment]
Can you please assign this issue to me?

**Comment by tejakummarikuntla** [comment]
Thank you for your interest, @jajjibhai008 . Assigned this issue to you.

**Comment by jajjibhai008** [comment]
@tejakummarikuntla I have created the PR. Please review it.
