### ISSUE TITLE
socket error connecting to Microsoft SQL Server for DataSource

### ISSUE THREAD

**Issue by JavaJosh89** [ToolJet/ToolJet#642]
### Environment

   ToolJet latest version, Ubuntu 20.04, Running in VirtualBox, connecting to Microsoft SQL Server running on Windows Server 2012. ...

### What is the expected behavior?

  Add SQL Server as DataSource with successful connection test.

### What is the current behavior?

  Using either hostname or IP of SQL server, default port, database name (have tried multiple), with correct username and password, when clicking test connection I receive a socket hang up error. 

### How to reproduce the issue?

1. Add MS SQL Server data source
2. Input server/database info
3. Click test connection

### Screenshots or Screencast

  
![socket hang up](https://user-images.githubusercontent.com/77753972/131361718-9d3c1e54-9031-4c65-9cba-974ab49ff6ed.JPG)

### Any possible solutions?
I've researched this and found that some people have had issues connecting to Microsoft SQL Server from a Virtual Linux PC. I have not tried from another physical PC because I do not currently have one to test with. 
Not certain if this is due to the Virtual machine or something in the code. I've looked into both (with what little knowledge I have) and cant seem to find anything that sticks out.

**Comment by withshubh** [comment]
@gsmithun4 Please check if this issue still exists.

**Comment by shubh22** [comment]
This issue doesn't exist anymore.
