### ISSUE TITLE
Fix the typo in inspector, replace the text 'widget' with 'component'

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6424]
### What is the expected behaviour?
In the inspector panel, when user clicks on component and hover over trash icon, system shows tooltip message as ' Delete widget ..', instead it should be 'Delete component ..'. Need to fix the typo.

### What is the current behaviour?
"Widget" is being displayed instead of the text "component".

### How to reproduce the issue?

1. create an application by dragging few components
2. click on inspector and expand the list of components
3. hover over the trash icon displayed besides any component and verify the tooltip text

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/68f7856b-c32e-4ac6-baaf-4a26e9cf7baf

### Solution
On hovering the trash icon, replace the text "widget" with "component"

**Comment by johnnam1121** [comment]
Hi I'd like to give this one a go. I found the typo in SidebarInspector.jsx on line 148.

**Comment by tejakummarikuntla** [comment]
Thank you for your interest, @johnnam1121 . As this issue hold the tag `good first issue` let's wait to welcome new contributors to the project, I hope you understand.

**Comment by Sukriti-m** [comment]
Hi @tejakummarikuntla 
I just came across this project and I am really excited to contribute to ToolJet. 
I would like to work on this issue. I'd be grateful if you could assign this to me.

**Comment by trishas95** [comment]
Hello @tejakummarikuntla , I've recently started contributing to open source and I'll be glad if I got this issue assigned to me.

**Comment by tejakummarikuntla** [comment]
Thank you for your interest @Sukriti-m. Assigned this issue to you.

@trishas95, we assign an issue on FCFS basis, I'd encourage you to explore other `good first issues` 
- https://github.com/ToolJet/ToolJet/issues/6399
- https://github.com/ToolJet/ToolJet/issues/6313
- https://github.com/ToolJet/ToolJet/issues/6308
Feel free to comment about your interest to assign the issue. Thank you.

**Comment by iSatVeerSingh** [comment]
@tejakummarikuntla Please close this issue now.
