### ISSUE TITLE
UI enhancement for dropdown and multi-select column type

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6425]
### Is your proposal related to a problem?

The UI and filter selection is inconsistent when user adds column type as dropdown or multi-select in table component.

(Write your answer here.)

### Describe the solution you'd like

-can display (V) icon to indicate that the column type is dropdown
-can add checkboxes in multi-select dropdown column, to indicate the filter value selections

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

**Comment by johnsoncherian** [comment]
Fixed in PR #8442
