### ISSUE TITLE
BigQuery request timesout

### ISSUE THREAD

**Issue by gitars** [ToolJet/ToolJet#6427]
### Version Information
2.15

### Environment
Docker

### What is the expected behaviour?
The BiqQuery query returns data even if the request takes > 1 minute.

### What is the current behaviour?
Request that take > 1 minute result in a 504 from the ToolJet server.

`POST /api/data_queries/9e34b195-627f-4686-b3fc-894f12510a57/run`

Result: 504 Gateway Time-out 

![Screenshot 2023-05-16 at 5 36 11 PM](https://github.com/ToolJet/ToolJet/assets/4552296/a697b896-a9f0-439b-910c-d67db4c41a1e)

![Screenshot 2023-05-16 at 5 30 41 PM](https://github.com/ToolJet/ToolJet/assets/4552296/89d1f601-9fb1-474c-b770-e9a1827c4d15)

### How to reproduce the issue?

1. Make a sufficiently long query to BigQuery.
2. The query fails from a timeout.

### Screenshots or Screencast
![Screenshot 2023-05-16 at 5 30 41 PM](https://github.com/ToolJet/ToolJet/assets/4552296/f121916c-f22f-4079-bfb2-272a15d7b573)

### Any possible solutions?
Allow timeout to be configurable

### Can you identify the location in the driver source code where the problem exists?
Not sure

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by Navaneeth-pk** [comment]
Can you please confirm there isn't a loadbalancer or reverse proxy?

**Comment by gitars** [comment]
🤦  this might be a load balancer issues. Will close and re-open if I rule out that out. Thank you!
