### ISSUE TITLE
Pop up for request confirmation is inconsistent for dark mode in viewer mode

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#6431]
### Environment

    ToolJet Cloud / Docker / Linux / MacOS ...

### What is the expected behaviour?
Pop up for request confirmation should not be inconsistent for dark mode in viewer mode.

### What is the current behaviour?
Pop up for request confirmation is inconsistent for dark mode in viewer mode.

### How to reproduce the issue?

1. Create an application.
2. Create a query and toggle on request confirmation & run on page load.
3. Click on preview mode & observe.
<img width="1440" alt="Screenshot 2023-05-17 at 12 06 28 PM" src="https://github.com/ToolJet/ToolJet/assets/41302917/e143514d-4f07-4980-aee1-c44ef027387f">

**Comment by iSatVeerSingh** [comment]
@Nandinisaha13 @shubh22 I have reproduced this issue and I know how to fix this. Can you please assign me.

**Comment by iSatVeerSingh** [comment]
@withshubh can you check my PR
