### ISSUE TITLE
Restarted docker container does not show UI

### ISSUE THREAD

**Issue by farindk** [ToolJet/ToolJet#6444]
### Version Information
2.5.0

### Environment
Docker

### How to reproduce the issue?

1. Install ToolJet with Docker container (as described on webpage):
````
curl -LO https://raw.githubusercontent.com/ToolJet/ToolJet/main/deploy/docker/docker-compose-db.yaml
mv docker-compose-db.yaml docker-compose.yaml
mkdir postgres_data
````
2. start
````
docker-compose up
````

Now, the web UI comes up and works as expected.

3. stop
````
docker-compose stop
````
4. restart
````
docker-compose start
````

Now, the web UI is stuck at the progress animation:
![image](https://github.com/ToolJet/ToolJet/assets/968944/b7da55d1-7958-465e-8d94-d66c84d7aea3)
Nothing will show up.

Even deleting the `postgres_data` directory before restarting does not help to resolve this.
The only way to get the web UI back seems to be to delete `postgres_data` and also completely remove the docker images and reinstall. Just removing the docker containers is also not enough.

I have this behavior when deploying to my server. On the local desktop, it seems to work.
On the server, ToolJet is behind a reverse proxy, which is the only difference I can see.

### Please provide any traces or logs that could help here.

Log output when restarting the docker container does not show any problem. Ends with:
````
Version: 2.5.0
Initializing server modules 📡 
Ready to use at https://tooljet.EXAMPLE.com
````
I don't know how to get more detailed logs. I can obtain them when you tell me where to look.

**Comment by farindk** [comment]
Update: a local setup which is simply using the `tooljet/try:latest` docker image as described here: https://docs.tooljet.com/docs/setup/try-tooljet/ worked for a few days and now also just shows the three progress-dots forever.
Nothing changed between the last uses of the app created within it and the currently broken state.

````
$ docker images 
REPOSITORY                               TAG       IMAGE ID       CREATED         SIZE
tooljet/try                              latest    2ec126987c62   8 weeks ago     2.71GB

$ docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED       STATUS          PORTS                                       NAMES
53261910dda4   tooljet/try:latest               "/bin/sh -c 'service…"   10 days ago   Up 39 minutes   0.0.0.0:3080->80/tcp, :::3080->80/tcp       tooljet
````

**Comment by adishM98** [comment]
Hi@farindk , 

Could you try restarting try-tooljet using the command `docker stop tooljet` to stop the container and `docker start tooljet` to start

**Comment by farindk** [comment]
Hi @adishM98 ,
yes, I had also tried this. After the initial `docker-compose up` and setting up the account, I tried `docker stop`/`start` and immediately got stuck at the progress dots. Then I tried `docker-compose down`/`up`, hoping that this would reset it, but no.
Only deleting everything could reset it.

On my other (local) machine, it was working for several days, but then suddenly also got stuck. I reinstalled everything and now it works again though `start`/`stop`.

Is there any log I could attach to see where it is stuck exactly?

**Comment by adishM98** [comment]
Hi @farindk, 

I believe this was a built failure which resulted in the loading screen. This is issue is fixed in the new release. Going forward you shouldn't face this issue.

**Comment by farindk** [comment]
I tried again with 2.6.1 and so far, it works fine.
Thanks.

**Comment by withshubh** [comment]
Closing as fixed.
