### ISSUE TITLE
Shareable app link input field is accepting empty string as a slug value

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#6445]
### Environment
    ToolJet Cloud
### What is the expected behaviour?
The shareable app link input should throw an error or trim the empty string in the slug value. 

### What is the current behaviour?
Shareable app link input is accepting empty string as slug value

### How to reproduce the issue?

1. Create an App.
2. Open the share app modal
3. Clear the app name slug input field and add an empty string.

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/20367957/8c29c4be-82a9-437f-bc77-576c8bb45c56

### Any possible solutions?
Add validations.

**Comment by ydv-ankit** [comment]
this is serious issue. can i work on it?
