### ISSUE TITLE
Expose download event for Table component?

### ISSUE THREAD

**Issue by tuutoo** [ToolJet/ToolJet#6455]
### Is your proposal related to a problem?

It seems there is not download event trigger in the table widget, there are triggers for row actions and filter.

Is it possible to add the event for download action?

That would be helpful for some further automation actions. 

Thank you very much.
![image](https://github.com/ToolJet/ToolJet/assets/9068314/8d314f2d-8854-45f8-b261-6a9a75e44bb8)

**Comment by withshubh** [comment]
Hey @tuutoo - Thanks for creating the issue. This feature is already in the pipeline. Ref: https://github.com/ToolJet/ToolJet/pull/6132

Closing the issue.
