### ISSUE TITLE
Dashboard: Hand cursor/ pointer is not appearing for 'See all templates' link

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6458]
### What is the expected behaviour?
Hand cursor or pointer should appear on hovering over 'See all templates' link on the dashboard screen

### What is the current behaviour?
There is no pointer displayed for the link, so hard to know whether the link is clickable or not.

### How to reproduce the issue?

1. Login to tooljet
2. On Dashboard/ landing screen hover over the link 'See all templates'
3.

**Comment by Prasad-mutnale** [comment]
@dishag18 Would you please assign me this issue so I can solve this issue.

**Comment by shubh22** [comment]
@Prasad-mutnale assigning you the issue.

**Comment by dishag18** [comment]
@Prasad-mutnale : please find the attached reference screencast.

Uploading Screenshare - 2023-05-23 10_46_54 AM.mp4…

**Comment by MauryanKansara** [comment]
hey @Prasad-mutnale are you still working on this issue? If not, can you assign it to me?

**Comment by Prasad-mutnale** [comment]
> hey @Prasad-mutnale are you still working on this issue? If not, can you assign it to me?

Currently, I'm not working on this issue ask @shubh22 he will assign you

**Comment by MauryanKansara** [comment]
> > hey @Prasad-mutnale are you still working on this issue? If not, can you assign it to me?
> 
> Currently, I'm not working on this issue ask @shubh22 he will assign you

ohkayyyy thanksss

**Comment by shauryag2002** [comment]
@shubh22  Would you please assign me this issue so I can solve this issue.

**Comment by withshubh** [comment]
Hey @MauryanKansara - We have assigned the issue to you. Please feel free to join our [Slack community](https://tooljet.com/slack) is you have any questions.

**Comment by withshubh** [comment]
> @shubh22 Would you please assign me this issue so I can solve this issue.

Hey @shauryag2002 - Thanks for showing interest in contributing to ToolJet, we have assigned the issue to someone else. Please find other open good first issues that are unassigned.

**Comment by MauryanKansara** [comment]
> Hey @MauryanKansara - We have assigned the issue to you. Please feel free to join our [Slack community](https://tooljet.com/slack) is you have any questions.

I've joined the Slack Community... I'm having some issues with setting up ToolJet locally.... I've opened a thread there, would you please help me???

**Comment by withshubh** [comment]
> > Hey @MauryanKansara - We have assigned the issue to you. Please feel free to join our [Slack community](https://tooljet.com/slack) is you have any questions.
> 
> I've joined the Slack Community... I'm having some issues with setting up ToolJet locally.... I've opened a thread there, would you please help me???

Thanks for creating the thread. Since it's weekend, you'll get a reply on Monday :)

**Comment by iSatVeerSingh** [comment]
@dishag18 @shubh22 Please take a look at my PR.

**Comment by withshubh** [comment]
Hey @iSatVeerSingh
We kindly request that you only create a pull request if an issue has been assigned to you. Otherwise, we may need to close the pull request. We appreciate your contribution and acknowledge that the [pull request](https://github.com/ToolJet/ToolJet/pull/6578) has already undergone the initial review. 
Moving forward, please comment on the issues and patiently wait for someone to assign it to you before proceeding with creating the pull request. Thank you for your understanding.
