### ISSUE TITLE
Support displaying table action buttons on the left

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#646]
Presently, action buttons come after table's data columns. We need to make it such that, action buttons can also be displayed on the left.

**Comment by ckbhatiaredef** [comment]
Can you share the current screenshot and also desired result screenshot (edited) if possible?

**Comment by sherfin94** [comment]
@ckbhatiaredef I've already made the changes. I've attached a loom video in the PR. https://github.com/ToolJet/ToolJet/pull/647
