### ISSUE TITLE
[docs]: change the color of bold text from blue to black/white according to light/dark mode

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6495]
### Summary

Currently, the color of bold text in documentation is blue which makes it hard to differentiate it from the hyperlink text as the hyperlink text color is also set to blue.
Change the bold text color to black/white according to light/dark mode of the documentation.
<img width="701" alt="Screenshot 2023-05-23 at 2 16 38 AM" src="https://github.com/ToolJet/ToolJet/assets/25361949/583ede9a-6d14-4009-ad1c-e0293cb22037">

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

docs.tooljet.com

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by GODINME** [comment]
Hi @withshubh am new to ToolJet Open Source, can you kindly assign me issue #6495 for me to solve to help me learn the workflow

**Comment by withshubh** [comment]
Hey @AmalChandru - Unfortunately, we will have to close that PR. There is already 1 issue assigned to you.

**Comment by mnmt7** [comment]
Hey @withshubh, can I work on this issue?

**Comment by withshubh** [comment]
Hey @mnmt7 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by Ar-Akhil** [comment]
is it still up for grabs??

**Comment by withshubh** [comment]
Yes

**Comment by Ar-Akhil** [comment]
would love to work on it

**Comment by withshubh** [comment]
> would love to work on it

@Ar-Akhil ASsigned the issue to you.

**Comment by ishsarin** [comment]
Hi, if this is still available could I work on it?

**Comment by tejakummarikuntla** [comment]
Hey @Ar-Akhil , since it has been a while we heard from you, we'd need to unassign it from you.

Thanks for your interest @ishsarin, assigned this to you.

**Comment by ishsarin** [comment]
@tejakummarikuntla created a PR for the changes #7161
