### ISSUE TITLE
[docs] fix the link to event handlers in versioned docs

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6496]
### Summary

The versioned docs directory (https://github.com/ToolJet/ToolJet/tree/develop/docs/versioned_docs) holds the docs for all the versions of the documentation, the link to components event handler is incorrect.
Replace the correct URL for `Event Handlers`:  `/docs/widgets/overview/#component-event-handlers` on every [Overview](https://github.com/ToolJet/ToolJet/blob/develop/docs/versioned_docs/version-2.0.0/widgets/overview.md) doc of each version from `2.0.0` to `2.6.0`
![237077603-6847d803-4378-491f-ae82-748bc5082907](https://github.com/ToolJet/ToolJet/assets/25361949/f9d9ea2e-af5e-4214-8082-d8a407075cb4)

### Issue Type

Documentation bug

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by GODINME** [comment]
Hi @withshubh am new to ToolJet Open Source, can you kindly assign me issue #6496

**Comment by withshubh** [comment]
> Hi @withshubh am new to ToolJet Open Source, can you kindly assign me issue #6496

Hey @GODINME - I have assigned another issue (https://github.com/ToolJet/ToolJet/issues/6308#issuecomment-1558960568) to you.

**Comment by AmalChandru** [comment]
Hi @withshubh you can assign this to me. I already raised the [PR](https://github.com/ToolJet/ToolJet/pull/6497) 🫠 without knowing the fact that, issues need to be assigned in order to start working on it. My bad!
