### ISSUE TITLE
[Bug] UI items go to wrong positions after select multiple items to move to another place on page

### ISSUE THREAD

**Issue by dandeancook** [ToolJet/ToolJet#6502]
### Version Information
2.2.2

### Environment
ToolJet docker

### What is the expected behaviour?
Items should maintain relative positioning with others

### What is the current behaviour?
Items are moved to wrong positions

### How to reproduce the issue?
1. Create a few items and put inside a container item
2. Select all of them (use mouse to make a select rectangle)
3. Press left mouse on them to start dragging
4. Drag to new location on page and release left mouse

### Screenshots or Screencast
Before dragging:
![image](https://github.com/ToolJet/ToolJet/assets/116571017/d8df93db-bb88-4373-b3a2-2cf8d098b1a8)

After dragging:
![image](https://github.com/ToolJet/ToolJet/assets/116571017/4801a372-d805-473f-bdde-29f8bb2bced4)

### Please provide any traces or logs that could help here.
No logs

### Any possible solutions?
Drag items one by one, or drag the container only. It's okay to drag the container only but anyway it's a real bug.

### Can you identify the location in the driver source code where the problem exists?
On UI only, no code

### If the bug is confirmed, would you be willing to submit a PR?
No PRs

**Comment by Sheikh-JamirAlam** [comment]
Can i work on this?
