### ISSUE TITLE
App is getting crashed upon clicking on codehinter expand icon in isEditable field in table column

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#6509]
### Environment
Cloud

### What is the expected behaviour?
Upon clicking on the code-hinter expand icon in table columns for isEditable field, it should open the code-hinter pop-up

### What is the current behaviour?
Upon clicking on the code-hinter expand icon in table columns for isEditable field, the app is crashing

### How to reproduce the issue?

1. Open new application
2. Drag a Table component from the right sidebar on the canvas
3. Click on the component on the canvas to open the component inspector in the right sidebar
4. In the table inspector, look for the column section inside the properties tab
5. Open any one of the available columns by clicking on the respective card in the column section
6. A pop-up window will appear to the left of the card, inside the pop-up at the bottom look for the make editable field and press the fx button corresponding to the same field.
7. A code-hinter will be showing up instead of a toggle switch, hover on the code-hinter, inside the code-hinter to its right, you will see one icon to expand the code-hinter, please click on it, the app will crash

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/37823141/babdb1c9-c5ca-4063-ad36-e9bb4c1eaac6

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by iSatVeerSingh** [comment]
Please close this issue now.

**Comment by withshubh** [comment]
@iSatVeerSingh - Thanks for heads up.
