### ISSUE TITLE
Empty folder notification and search bar is not appearing for newly added folder

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6512]
### What is the expected behaviour?
The empty folder notification and search bar should be displayed on the screen to maintain the consistency for the folder structure.

### What is the current behaviour?
When signed in with different user and created new folder, the icon and search bar is missing.

### How to reproduce the issue?

1. create new user and login with that user
2. on successful login, try to create new folder on the dashboard
3. verify if icon and search bar is displayed on the screen

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/722f5bc4-851f-4d10-b5c9-83321879b804

**Comment by jobayer12** [comment]
@withshubh I would like to work on this ticket. Please assign me.

**Comment by thehacklady** [comment]
fixed with PR : https://github.com/ToolJet/ToolJet/pull/6396

**Comment by thehacklady** [comment]
fixed with PR : https://github.com/ToolJet/ToolJet/pull/6396
