### ISSUE TITLE
[docs]: set max size of contributors grid to 360 on README and docs landing page

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6515]
### Summary

At present, the GitHub repository of ToolJet has a total of 340 contributors. However, the displayed grid on both the Docs landing page and README only reflects 300 contributors. To rectify this, the solution is to modify the value of `max` to `360`.
This can be fixed by updating the `max` to `360`

The files needed to updated:
- README
- Getting Started file in `tooljet/docs/docs`
- Getting Started file of each version in the `tooljet/docs/versioned_docs/` except the `v1.x.x`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by kumar-kalyan** [comment]
Hey @withshubh can I work on this issue ?

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue.

**Comment by themohammadsa** [comment]
Hey @withshubh, I'd like to pick this task up. Could you assign it to me? 
It would be my first contribution, and hopefully more to come.

**Comment by withshubh** [comment]
Hey @kumar-kalyan - Assigned the issue to you.

**Comment by withshubh** [comment]
Hey @tarunsamanta2k20 - Thanks for showing interest in contributing to ToolJet. We assign issues on the first come first served basis, this has been assigned to someone else. Please feel free to comment on other open `good first issues`.
