### ISSUE TITLE
[widget-sidebar]: search doesn't work as expected on selecting whole text

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#652]
### Version Information
Latest
### Environment
MacOS
### What is the expected behaviour?
Should return searched items
### What is the current behaviour?
Not returning search items

### Screenshots or Screencast

https://user-images.githubusercontent.com/12490590/131518645-112aa3a0-f87f-4f4c-bb38-77d3352c4861.mov

**Comment by virajbahulkar** [comment]
@Navaneeth-pk picking up this

**Comment by saideepesh000** [comment]
Hey @Navaneeth-pk , we can close this issue
