### ISSUE TITLE
[docs] fix the broken link in workspace variables doc

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6523]
### Summary

The link of the text `here` on the section **Using variable in an app** is broken.
Fix the link by changing it to 
```
/docs/tutorial/workspace-variables/#adding-the-environment-variable
```

<img width="1022" alt="Screenshot 2023-05-24 at 7 13 13 PM" src="https://github.com/ToolJet/ToolJet/assets/25361949/da980576-501f-42b9-b060-8a6c4745345e">

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/tutorial/workspace-variables/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by tungbq** [comment]
Hello @withshubh Can I pick up this task?

**Comment by withshubh** [comment]
Hey @tungbq - Assigned the issue to you.
