### ISSUE TITLE
Change widget sidebar design

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#654]
![image](https://user-images.githubusercontent.com/12490590/131530925-68a53000-8348-4fa5-8e06-9a03737ef998.png)

The above image is an example of the widget sidebar changes proposed. 

To summarize, 

- Segregate the items based on 3 different criteria, 
- Box look and feel changes

**Comment by ckbhatiaredef** [comment]
Hi @gondar00, Can you assign this to me?

**Comment by Ckbhatia** [comment]
Hi @gondar00, Can you assign this?
