### ISSUE TITLE
[UI]: The position of icon to expand the code editor in new window is not fixed

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6542]
### What is the expected behaviour?
The icon position should be fixed, so that if there is large amount of data and user scrolls down in the code editor grid, the icon should always be visible

### What is the current behaviour?
The icon only appears at the top right side, and on scroll it is not accessible.
Also the window close icon takes some time to load.

### How to reproduce the issue?

1. Drag any component like table or chart
2. Enter some data in code editor and try to scroll down
3. Verify if the icon to open/expand  the code editor is visible or not

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/e973c07d-e327-411a-9fe8-d5e1e5ffe8f3

**Comment by ShahriyaSiddique** [comment]
@dishag18 I have fixed this bug. Please review the PR.

**Comment by ShahriyaSiddique** [comment]
Hello @withshubh, I have fixed this issue. Please assign it to me.
