### ISSUE TITLE
Global Settings: The fields in the popup are not aligned

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6547]
### What is the expected behaviour?
The fields present in the pop up should be aligned properly

### What is the current behaviour?
There is un-alignment issue in the pop up, need to adjust the positioning

### How to reproduce the issue?

1. Create new app
2. Click on Global settings
3. Verify the alignment of fields: Max width of canvas, Max height of canvas vs Background color of canvas

**Comment by iSatVeerSingh** [comment]
@dishag18 Is this really an issue?
