### ISSUE TITLE
Dark mode [UI]: Global data source search bar and page rename input box text is not visible clearly

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6554]
### What is the expected behaviour?
The input string should be clearly visible to the user

### What is the current behaviour?
The text/font color is not that intuitive, so hard to read the provided search string

### How to reproduce the issue?

1. Go to Global datasource and provide search string
2. Or open any app and try to rename page
3.

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/68753d0a-4c91-4451-b16c-30e440d3cf53

**Comment by iSatVeerSingh** [comment]
@dishag18 Please take a look at my PR.

**Comment by iSatVeerSingh** [comment]
@dishag18 @shubh22 Please take a look at my PR.

**Comment by md-ahsanhabib** [comment]
@dishag18  can i work on this issue?
