### ISSUE TITLE
Edit Workspace popup related observations

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6567]
### What is the expected behaviour?
When user clicks on pencil icon besides the selected workspace, the popup should appear and display the name of selected workspace by default.
When user enters workspace name and clicks on Cancel button or cross icon, on reopening the same popup the prior input should get vanished.

### What is the current behaviour?
The default workspace name is not appearing in the popup
On cancel and reopen, user can still see the prior input

### How to reproduce the issue?

1. Click o pencil icon for any workspace
2. Enter workspace name
3. Click on cancel button or cross icon

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/05fff6b1-7b73-415b-b000-82725dce0ee9

**Comment by mnmt7** [comment]
@dishag18, I would like to work on this issue.

**Comment by iSatVeerSingh** [comment]
@dishag18 I know how to fix this issue. Please assign me.

**Comment by iSatVeerSingh** [comment]
@dishag18 Please take a look at my PR.

**Comment by shubh22** [comment]
Fixed by #6299
