### ISSUE TITLE
[Dashboard]: Naming inconsistency for Edit folder link and the popup

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6569]
### What is the expected behaviour?
The names should be consistent, if the link is showing 'Edit Folder', the pop up header should also be the same. Currently it has different header 'Update Folder'.

### What is the current behaviour?
Link and popup header is inconsistent

### How to reproduce the issue?

1. Select any folder
2. Select the Edit Folder option
3. Verify the header displayed in the popup

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/e0e1843c-9cac-49af-9f63-722482058cb4

**Comment by prabhjotlamba1655** [comment]
Hi, 

I would like to work on this issue, I have a fairly good idea where the change should go. 

Thank you

**Comment by iSatVeerSingh** [comment]
@dishag18 Please take a look at my PR.

**Comment by iSatVeerSingh** [comment]
@dishag18 @shubh22 Please take a look at my PR

**Comment by iSatVeerSingh** [comment]
@shubh22 can you check my PR.
