### ISSUE TITLE
Unreasonable integer range

### ISSUE THREAD

**Issue by dandeancook** [ToolJet/ToolJet#6580]
### Version Information
2.2.2

### Environment
ToolJet docker

### What is the expected behaviour?
* Integer should to maxed at Number.MAX_SAFE_INTEGER
* Integer should not be maxed at 2^32

### What is the current behaviour?
Integer type in ToolJet db is limited to a very small number unknown.

### How to reproduce the issue?
Create an insert query to ToolJet db, set the value of a column to insert at a big number, eg. `new Date().getTime()`

### Screenshots or Screencast
![image](https://github.com/ToolJet/ToolJet/assets/116571017/625ae901-7754-433d-9c14-cd0d5a8053d0)

### Please provide any traces or logs that could help here.
{
  "code": "22003",
  "details": null,
  "hint": null,
  "message": "value \"1685348029461\" is out of range for type integer"
}

### Any possible solutions?
Divide the new Date() value by 1000, but the time stored (as float) will be exact to seconds instead of milliseconds

### Can you identify the location in the driver source code where the problem exists?
None

### If the bug is confirmed, would you be willing to submit a PR?
None

**Comment by adityaKrModak** [comment]
@dandeancook  Can i work on this ?

**Comment by dandeancook** [comment]
> @dandeancook Can i work on this ?

i think you may tag tooljet team; im just user
