### ISSUE TITLE
[dark-mode] rest api icon is not visible in dark mode

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#659]
In dark mode the rest api icon is not visible properly, 

ex: 

![image](https://user-images.githubusercontent.com/12490590/131619978-fb24ab56-cb71-46b5-b34f-14af347f0e2d.png)

**Comment by karan-rathod-316** [comment]
@gondar00 I think I can fix this issue, can I take it up?

**Comment by gondar00** [comment]
@karan-rathod-316 yes sure assigned the issue to you

**Comment by Navaneeth-pk** [comment]
@karan-rathod-316 are you still working on this issue?

**Comment by karan-rathod-316** [comment]
@Navaneeth-pk I had started working on it but don't have access to my system for the next 2-3 of days due to hardware issues. I am unassigning it at the moment just to prevent any delays.

**Comment by ajinkyaa** [comment]
Working on it.

**Comment by TheLearneer** [comment]
@Navaneeth-pk Hi there, This issue has obtained a PR to fix, but is still open 😄
