### ISSUE TITLE
Some templates return error "Cannot read properties on undefined (reading 'options')"

### ISSUE THREAD

**Issue by samibul** [ToolJet/ToolJet#6595]
### Version Information
Version 2.5.0-ee2.0.15-cloud2.0.2
### Environment

    ToolJet Cloud / Linux Fedora 38
![Screenshot from 2023-05-30 11-08-56](https://github.com/ToolJet/ToolJet/assets/57390243/6e6f4a35-50b4-45a5-b865-28be8e12cfe9)

### What is the expected behaviour?

  When i'm choosing "Job application tracker" i expect to receive "App created" and "Create new version" window.

### What is the current behaviour?

  When i click on "Job application tracker" i've got the error "Cannot read properties on undefined (reading 'options') and cannot continue.

### How to reproduce the issue?

1.
2.
3.

### Screenshots or Screencast

  Attached screenshot.

**Comment by withshubh** [comment]
Closing this as fixed here:
- https://github.com/ToolJet/ToolJet/pull/6629
