### ISSUE TITLE
[docs]: Change the callout type from tip to warning

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6604]
### Summary

Change the callout in the [documentation page](https://docs.tooljet.com/docs/contributing-guide/setup/docker) from `Tip` to `warning`

<img width="1325" alt="image" src="https://github.com/ToolJet/ToolJet/assets/34749692/0706b92e-bf05-4b99-b225-f4cf07609e61">

**The files needed to updated:**
[All the versions](https://github.com/ToolJet/ToolJet/tree/develop/docs/versioned_docs) from 1.x.x to 2.6.0 and the base [`docs/docs`](https://github.com/ToolJet/ToolJet/tree/develop/docs/docs)

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/setup/docker

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Mohith234** [comment]
Hey @tejakummarikuntla I can take up this issue

**Comment by gantanikhilraj** [comment]
I can work on this @tejakummarikuntla , assign it to me.

**Comment by tejakummarikuntla** [comment]
Hey @Mohith234 , as this issue holds the tag `good first issue` let's welcome the first-time contributors to the project, I hope you are doing well with the issues assigned to you. Thanks for your understanding.

Thanks for your interest @gantanikhilraj , assigned this issue to you.

**Comment by akash1520** [comment]
@tejakummarikuntla can I take up this issue?
