### ISSUE TITLE
Can't install plugins from marketplace

### ISSUE THREAD

**Issue by andreyazbarov** [ToolJet/ToolJet#6647]
### Environment

    ToolJet  Docker on Ubuntu

### What is the expected behaviour?

Trying to install plugins, put ENABLE_MARKETPLACE_FEATURE=true in .env file during installation, doing all the instructions from Setup manual. When docker containers up, entering ToolJet, openning Marketplace section, selecting OpenAI plugin, pressing button "Install" and the plugin installed.

### What is the current behaviour?

  Trying to install plugins, put ENABLE_MARKETPLACE_FEATURE=true in .env file during installation, doing all the instructions from Setup manual. When docker containers up, entering ToolJet, openning Marketplace section, selecting OpenAI plugin, pressing button "Install" and got "Invalid plugin files" popup.

### How to reproduce the issue?

1. Fresh install via Docker on Ubuntu
2. ENABLE_MARKETPLACE_FEATURE=true
3. run
4. goto Marketplace section
5. select OpenAI plugin
6. press Install

### Screenshots or Screencast

![image](https://github.com/ToolJet/ToolJet/assets/87981916/43dbcdfa-aedb-422c-97b1-63422bb6c9d8)

### Please provide any traces or logs that could help here.
[tooljet-logs.txt](https://github.com/ToolJet/ToolJet/files/11655120/tooljet-logs.txt)

### Any possible solutions?
Can't realize

### Can you identify the location in the driver source code where the problem exists?
ToolJet/server/src/services/plugins.service.ts

**Comment by akshaysasidrn** [comment]
@andreyazbarov can you check with the latest develop / release? Are you still facing the issue?

**Comment by andreyazbarov** [comment]
@akshaysasidrn thanks! Now it works! Installed successfully on clean system.
