### ISSUE TITLE
On pressing enter should trigger `create workspace` action

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6653]
### What is the issue?
When a user creates a new workspace, a modal pops up where the user enters the workspace name and clicks on the `create workspace` button to create a new workspace.
Ideally, The user should also be able to create the new workspace by pressing the enter key after entering the new workspace name.

### How to reproduce the issue?

1. Go to ToolJet dashboard
2. From workspaces dropdown in the bottom, select create new workspace  
3. On the modal, enter the workspace name and press enter

### Screenshots or Screencast
![image (11)](https://github.com/ToolJet/ToolJet/assets/25361949/d78a7b37-2385-4826-aa1c-1851276152fc)

**Comment by coderSuren** [comment]
@withshubh I would like to work on this issue

**Comment by withshubh** [comment]
Hey @coderSuren - Thanks for showing interest in contributing to ToolJet.
Assigned it to you.

**Comment by Rahulcheerio** [comment]
@coderSuren have you started working on it ? If not I would like to work on it .
@withshubh should I pic this ?

**Comment by coderSuren** [comment]
@withshubh I am unable to set up tooljet on docker locally, so please assign it to @Rahulcheerio

**Comment by parmarKaran01** [comment]
@withshubh is this issue still open?, I would like to work on it

**Comment by withshubh** [comment]
Hey @coderSuren - Any update on the PR?

**Comment by coderSuren** [comment]
Hey @withshubh, sorry for for the delay. I got stuck with setting up docker. I have created a PR that solves the issue #6699
