### ISSUE TITLE
rename `widget` to `component`

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6657]
### What is the issue?
There are still some places in the app builder where component is displayed as `widget`. Make the required changes to rename widget to components in the app builder. Follow the steps to reproduce the issue with all the components available.

### How to reproduce the issue?

1. Open ToolJet app builder
2. Drag a table component from the component library to the canvas
3. Click on table to edit its properties from the right sidebar
4. Go to table data property input box, click on the expand button on the right of input box
5. Notice that on the header of the expanded box, it is mentioned `widget`

### Screenshots or Screencast
![123 (1)](https://github.com/ToolJet/ToolJet/assets/25361949/4b23da63-f043-4736-b792-a930bb361930)

**Comment by Aryan123-rgb** [comment]
Would like to work on this issue @withshubh

**Comment by withshubh** [comment]
Hey @Aryan123-rgb - [Another issue](https://github.com/ToolJet/ToolJet/issues/6654) has been assigned to you.

**Comment by justinpv98** [comment]
I would like to work on this issue.

**Comment by withshubh** [comment]
Hey @justinpv98 - Thanks for showing interest in contributing to ToolJet.
Assigned it to you.
