### ISSUE TITLE
Profile settings: Error in console on click of 'Update' button

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6669]
### What is the expected behaviour?
User should be able to click on update button and the recent changes should reflect on UI and if 'Last name' field is blank it should throw error.

### What is the current behaviour?
If there is no last name, system is throwing error in console and Update button is not working as per expectations. User is not able to update first name and avatar in this case.

### How to reproduce the issue?

1. Create user without last name and then go to Profile settings tab
2. If there is no value in last name fields, try to change first name or avatar or simply click on Update button
3.

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/c72c03e7-5151-4995-9061-f9410824f0c0

**Comment by aamani98** [comment]
@dishag18 Can I work on this?
