### ISSUE TITLE
DISABLE_MULTI_WORKSPACE=true no longer disables workspaces and Google SSO is hidden

### ISSUE THREAD

**Issue by dlebech** [ToolJet/ToolJet#6706]
### Version Information

2.6.2

### Environment

Docker on Cloud Run

### What is the expected behaviour?

I was expecting:
- After upgrading from 2.3.0 to 2.6.2, I was expecting to see my "Sign In With Google" when visiting my tooljet installation.
- Multiple workspaces should be disabled, and it shouldn't be possible to create new workspaces.

I have:
- DISABLE_MULTI_WORKSPACE=true in environment variables
- Only a single organization in the database
- Configured Google SSO with no signups

### What is the current behaviour?

- I am presented with username and password login when visiting the root url for my Tooljet installation
- There is a "Create an account" button which didn't use to be there.
- Even though I have disabled multi workspace via environment variable, it allows me to log in with the username and password I configured a long time ago, and it automatically creates a new empty workspace, and I'm able to create new workspaces here as well.

### How to reproduce the issue?

1. Install 2.3.0
2. Set up Google SSO and disable signup
3. Verify the Sign in with Google works.
4. Upgrade to 2.6.2 (maybe just 2.4.0 see below).
5. The login page shows username and password instead of Google Signin

### Screenshots or Screencast

Not applicable, it's the normal login screen

### Any possible solutions?

None that I know of

### Can you identify the location in the driver source code where the problem exists?

I think this happened after the 2.4.0 upgrade as part of the PR #5487 

Specifically this change: https://github.com/ToolJet/ToolJet/commit/32740743e1e2420f0e5bbd32fe54610cc242d59d#diff-09052b60d122cac522850f30c05736316a45043c1e8e67c154c25d0b725eba0dL89-L92

The public-configs endpoint started returning different data which hides the Google Login unless a specific workspace url is used.

### If the bug is confirmed, would you be willing to submit a PR?

No

**Comment by gsmithun4** [comment]
Hi @dlebech 
In the latest update, we have deprecated the practice of restricting access to a single workspace solely through the use of the environment variable `DISABLE_MULTI_WORKSPACE`. Instead, we have introduced an alternative method in the enterprise edition to achieve this.

**Comment by gsmithun4** [comment]
To enable login via Google SSO in the Community edition, it is necessary to configure the environment variable `SSO_GOOGLE_OAUTH2_CLIENT_ID` in the system's environment variables.

**Comment by dlebech** [comment]
@gsmithun4 Adding `SSO_GOOGLE_OAUTH2_CLIENT_ID` shows the Google sign in button, but *it doesn't work*. When you click the button, Google provides the error "Error 400: redirect_uri_mismatch"

I think the reason for this is the `public-configs` API no longer returns the correct JSON data:
1. The sign in button expects a `configId` field in the SSO config: https://github.com/ToolJet/ToolJet/blob/v2.6.2/frontend/ee/components/LoginPage/GoogleSSOLoginButton.jsx#L17
2. This field is never returned from the [public-configs](https://github.com/ToolJet/ToolJet/blob/c9f6b9073891aa52a6d034c20f597a16b0f2d26b/server/src/controllers/organizations.controller.ts#L78-L91) API endpoint
3. I believe this is because the function enters the `!organizationId` path and [`constructSSOConfigs`](https://github.com/ToolJet/ToolJet/blob/c9f6b9073891aa52a6d034c20f597a16b0f2d26b/server/src/services/organizations.service.ts#L109) doesn't return the config ID as part of the request.

SSO with Google still works if I use the workspace-specific login url, i.e. /login/abcd-1234-etc-etc but it's a shame I can't login with Google from the root of my domain :disappointed:

**Comment by gsmithun4** [comment]
Hi @dlebech Please configure redirect URL `<host/sso/openid>` in Google console and try.

**Comment by dlebech** [comment]
@gsmithun4 I see, instead of `/sso/google/ABCD-1234` ID, it's now just `/sso/google`. Adding that URL to the approved redirects in the Google console indeed fixed it. Thanks! :clap:
