### ISSUE TITLE
[docs]: minor fixes in Form doc

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6719]
### Summary

Under the [Component Specific Actions](https://docs.tooljet.com/docs/widgets/form/#component-specific-actions-csa), the following changes need to be made:
- In the `Actions` columns, replace `resetForm` to `submitForm` and `submitForm` to `resetForm`
- In the `Description` of resetForm there are two `await` make it one

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/form/#component-specific-actions-csa

### Additional Information

The files needed to updated:
[All the versions](https://github.com/ToolJet/ToolJet/tree/develop/docs/versioned_docs) from version-2.3.0 to version-2.6.0 and the base [docs/docs](https://github.com/ToolJet/ToolJet/tree/develop/docs/docs)

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by IshaanAdarsh** [comment]
I’m on it.

**Comment by withshubh** [comment]
Hey @IshaanAdarsh - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by withshubh** [comment]
@IshaanAdarsh - I noticed that you have created 4 different PRs for 4 different versions of the docs, this should have been done in the single PR itself.
Still, the fix for the base [docs/docs](https://github.com/ToolJet/ToolJet/tree/develop/docs/docs) is missing.

**Comment by IshaanAdarsh** [comment]
> @IshaanAdarsh - I noticed that you have created 4 different PRs for 4 different versions of the docs, this should have been done in the single PR itself.
> Still, the fix for the base [docs/docs](https://github.com/ToolJet/ToolJet/tree/develop/docs/docs) is missing.
> If possible please make all the changes in the single PR.

I’ll remove the previous PR’s. I try to make the changes in a single PR only.

**Comment by IshaanAdarsh** [comment]
https://github.com/ToolJet/ToolJet/pull/6746
Did the changes in 1 PR.
