### ISSUE TITLE
text of the name of global datasource overflows in the datasources page

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6720]
### What is the current behaviour?

When a datasource name is of higher length it overflows.

### How to reproduce the issue?

1. Go to Global datasource page
2. Add any datasource
3. Rename the datasource name from the modal
4. check the datasource list on the left

### Screenshot

https://github.com/ToolJet/ToolJet/assets/25361949/f77e9f77-c3dd-40ce-a85e-b9c0b4861ae0

**Comment by habeeb-an** [comment]
could you assign me this issue?

**Comment by nabeel001** [comment]
Hey I would like to fix this issue. Can you assign this to me.

**Comment by withshubh** [comment]
Hey @habeeb-an - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by nabeel001** [comment]
If this issue is still open, i would like to fix it.

**Comment by habeeb-an** [comment]
I'm working on it

**Comment by habeeb-an** [comment]
Hi 
This is my first open-source contribution

Came across a **problem** that system hanging when running tests locally
any to bypass that OR is there any way to do PR it run tests using GitHub ?

update on issue
 I resolved error
using ellipsis when overflowing
also, the data-source icon size reducing issue faced ->solved 
if you want to solve this issue using any other way please comment
