### ISSUE TITLE
text of the name of global datasource overflows in the query panel

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6721]
### What is the current behaviour?

When a datasource name is of higher length it overflows.

### How to reproduce the issue?

1. Go to Global datasource page
2. Add any datasource
3. Rename the datasource name from the modal
4. Go to the app
5. Click on the `+Add` button on the query panel at the bottom
6. Check the datasource name 

### Screenshot

![Screenshot 2023-06-14 at 4 43 02 PM](https://github.com/ToolJet/ToolJet/assets/25361949/de9e41c8-cc96-4ee7-a4ed-bccc18582c42)

**Comment by mikebarr24** [comment]
Could I take this issue?

**Comment by withshubh** [comment]
Hello, @mikebarr24. Given that this particular issue has been labeled as a "good first issue," intended to encourage new contributors, would it be possible for us to consider assigning this task to someone who is new to contributing to ToolJet? Your understanding in this matter would be greatly appreciated.

**Comment by mikebarr24** [comment]
No worries😊. I'll have a look for something else. Cheers.

**Comment by nabeel001** [comment]
Hey I would like to work on this issue. Can you please assign this to me

**Comment by withshubh** [comment]
Hey @nabeel001 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by tejakummarikuntla** [comment]
Hey @nabeel001, were you able to progress with the issue? Please link this issue to the PR if you raise it.

**Comment by nabeel001** [comment]
This is no longer an issue as it has been fixed in the recent releases. That's why I closed my PR as well. You can close this issue.
