### ISSUE TITLE
[docs]: Text correction in /docs/setup

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6730]
### Summary

Correct the spelling of text `differenet` to different in [/docs/setup/digitalocean](https://docs.tooljet.com/docs/setup/digitalocean)
in all the versions of the documentation.

### Issue Type

Documentation bug

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by jibranabsarulislam** [comment]
on it 👍

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @jibranabsarulislam . Assigned this to you.
