### ISSUE TITLE
On pressing enter should save the new workspace name

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6759]
### What is the issue?
When a user edits a workspace name, a modal pops up where the user enters the `new workspace name` and clicks on the `save` button to rename the workspace.
Ideally, The user should be able to save the new name by pressing the enter key after entering the new workspace name.

### How to reproduce the issue?

1. Go to the ToolJet dashboard
2. From the workspaces dropdown at the bottom, click on the edit button next to the selected workspace
3. On the modal, rename the workspace name and press enter

### Screenshots or Screencast
![Screenshot 2023-06-16 at 2 31 35 PM](https://github.com/ToolJet/ToolJet/assets/25361949/90001602-e11f-4614-a477-eae4784fe118)

similar to this issue: https://github.com/ToolJet/ToolJet/issues/6653

**Comment by gokullan** [comment]
Hi, there! I would like to work on this. Can this be assigned to me?

**Comment by omarPerez1987** [comment]
Hello! I would like to work on this. Can I be assigned this would be my first contribution to an open source project?

**Comment by withshubh** [comment]
Hey @gokullan - Thanks for showing interest in contributing to ToolJet. Assinged the issue to you.

**Comment by withshubh** [comment]
> Hello! I would like to work on this. Can I be assigned this would be my first contribution to an open source project?

Hey, @omarPerez1987 - Thanks for showing interest in contributing to ToolJet, unfortunately, we can't assign this issue to you as we assign on a first come first served basis. Please comment on the other open good first issues, I would be happy to assign them to you.
