### ISSUE TITLE
On pressing enter does not work in `create folder` and `update folder` modal

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6760]
### What is the issue?
When a user creates a new folder on the ToolJet dashboard, a modal pops up where the user enters the `new folder name` and clicks on the `create folder` button to create the folder and similarly for updating the folder name
Ideally, The user should be able to create or update a folder by pressing the enter key.

### How to reproduce the issue?

1. Go to the ToolJet dashboard
2. From the dashboard, click on the `+` button to create a new folder, a modal will popup from where you'll be able to enter folder name and create it, name the folder and press enter to save it but it wont work
3. Similary when you try to edit the name of existing folder, pressing enter key won't work while renaming folder

similar to this issue: https://github.com/ToolJet/ToolJet/issues/6653

### Screenshots or Screencast

![Screenshot 2023-06-16 at 2 39 08 PM](https://github.com/ToolJet/ToolJet/assets/25361949/53762030-531d-4b34-8f22-6c2ff05f72c0)
![Screenshot 2023-06-16 at 2 39 48 PM](https://github.com/ToolJet/ToolJet/assets/25361949/f9204d03-663d-4ef5-9d0a-b9bcb1913a37)

**Comment by web-dev-kushal** [comment]
Hey, I came across your repository and I'm interested in contributing to the project. I noticed the issue and I would like to work on it. Could you please provide more details or guidance on how I can get started?

**Comment by withshubh** [comment]
Hey @web-dev-kushal - Thanks for showing interest in contributing to ToolJet. Assigned this issue to you.

**Comment by withshubh** [comment]
> Hey I would like to work on this issue

Hey, @Alok-1512 - Thanks for showing interest in contributing to ToolJet, unfortunately, we can't assign this issue to you as we assign on a first come first served basis. Please comment on the other open good first issue, I would be happy to assign to you.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by web-dev-kushal** [comment]
![image](https://github.com/ToolJet/ToolJet/assets/68588123/65898074-282d-4ec4-8a43-c7edebad030a)
I am getting this error

**Comment by withshubh** [comment]
Hey @web-dev-kushal - Please ask in our [Slack community](https://tooljet.com/slack).

**Comment by tejakummarikuntla** [comment]
Hey @web-dev-kushal , were you able to progress with the issue?

**Comment by web-dev-kushal** [comment]
@tejakummarikuntla I am having issues setting the code locally!!
