### ISSUE TITLE
[ Cloud ] Event is not getting fired upon change in the cell value in the table

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#6784]
### Version Information
Version 2.6.2-ee2.1.0-cloud2.0.3

### Environment
Cloud

### What is the expected behaviour?
There is an event named `cell value changed`, which should get fired upon a change in the cell values in the table.

### What is the current behaviour?
We do have an event, but we are not making it to fire upon change in the cell values.

### How to reproduce the issue?

1. Create a new app
2. Drag a table from the right sidebar inspector onto the canvas
3. Click anywhere on the table to open its widget inspector in the right sidebar.
4. In the table inspector, look for the columns section, and click on any one of the cards in this section to open the window pop-up to configure a particular column in the pop-up look for the editable field at the bottom and toggle it on
5.  Now, looks for the events section in the same table inspector, add a new event and a card will get added, click on that particular card to open the event manager pop-up.
6. In the event manager pop-up, look for the event field, and in that field, we have to select `cell value changed` and configure other fields according to your needs if needed
7. Now, in the table edit any cell in the particular column, which we made editable as soon as we change the value, on cell value changed event should get triggered and perform specific tasks configured in the event manager

### Screenshots or Screencast
[My app 1687184613320 - Tooljet - 19 June 2023 - Watch Video](https://www.loom.com/share/3763cc817fe544e3ba4a8301d811534a)

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by Avi98** [comment]
@manishkushare if it's okay can I take this up? It seems like one-liner change
