### ISSUE TITLE
Boolean column type in table 

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#6786]
### Is your proposal related to a problem?

Presently, there is no column type that represents boolean data except the ones that are specifically used in editable mode.

### Describe the solution you'd like

Make a boolean column type.

- It should show a plain tick mark  (✓) or cross mark (✗) when the value is true or false respectively
- It should show a checkbox when the column is editable
- The column options should contain
  - tick/cross/checkbox  color

**Comment by sherfin94** [comment]
@manishkushare on-hold

**Comment by GrowwithNaveen** [comment]
Closing this item as we are handling this on Table column type: Boolean [#8023](https://github.com/ToolJet/ToolJet/issues/8023)
