### ISSUE TITLE
[docs]: move `visibility` and `disable` to Styles table

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6801]
### Summary

Move the Visibility and disable's title and description on the Styles table.
![Screenshot 2023-06-21 at 5 59 09 PM](https://github.com/ToolJet/ToolJet/assets/25361949/43b6fe51-7f97-4fa5-92b3-a517c3dff521)

Note: The following change is required in all the versions of the docs: [All the versions](https://github.com/ToolJet/ToolJet/tree/develop/docs/versioned_docs) from `1.x.x` to `2.7.0` and the base [docs/docs](https://github.com/ToolJet/ToolJet/tree/develop/docs/docs)

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/text/#visibility

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by ShivangRawat30** [comment]
I would like to take this one

**Comment by Lovepreet013** [comment]
I would like to take this issue
