### ISSUE TITLE
fix the input padding in the folder search box

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6817]
#### Current Behavior:
The input box for folder search in ToolJet has an unnecessary padding.

#### Steps to Reproduce:

1. Log in to ToolJet.
2. Navigate to the dashboard.
3. Click on the Search icon to initiate a folder search.
4. The input box will appear, and its padding is currently set to 33, which is unnecessary.

#### Expected Solution:
To resolve the issue, the padding should be removed from the input box. This will ensure that the input aligns properly inside the search box and maintains a consistent design.

### Screenshots or Screencast
![Screenshot 2023-06-22 at 3 02 11 PM](https://github.com/ToolJet/ToolJet/assets/25361949/1aaaa8ef-b2f8-45bf-b7fd-c227516a96b9)

**Comment by matheuscaldas1** [comment]
Hi @withshubh, can I take this up? I'm new at open-source contributions

**Comment by withshubh** [comment]
Hey @matheuscaldas1 - Thanks for showing interest in contributing to ToolJet. Assigned it to you.
