### ISSUE TITLE
Marketplace: display scrollbar only if the items exceed on the page 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6818]
#### Current Behavior:
The Installed & Marketplace page in ToolJet displays a scrollbar at all times, even when there are no items present on the page.

#### Steps to Reproduce:

1. Set up ToolJet locally.
2. Enable the Marketplace feature following the instructions provided in the ToolJet documentation (https://docs.tooljet.com/docs/contributing-guide/marketplace/marketplace-setup).
3. Navigate to the Marketplace section.
4. Observe that a scrollbar is present on the page, regardless of the number of items displayed.

#### Expected Solution:
To resolve this issue, the scrollbar should only appear when the number of items on the page exceeds the available space. When there are no items or when the items fit within the page, the scrollbar should not be displayed, providing a more visually streamlined and intuitive user interface.
### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/25361949/9c8561f9-b341-4a2d-be90-b71d44796697

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by withshubh** [comment]
Hey @ShivangRawat30 - Thanks for showing interest in contributing to ToolJet. Assigned it to you.

**Comment by tejakummarikuntla** [comment]
Hey @ShivangRawat30 , were you able to progress with the issues?

**Comment by tejakummarikuntla** [comment]
Hey @ShivangRawat30 , We noticed that you were working on an issue, and we wish you the best in making progress on it. However, given this issue is labeled as a `good first issue`, we were wondering if it's possible to assign it to someone new to the project. If you haven't started working on it yet, kindly let us know so we can proceed accordingly. We appreciate your understanding and cooperation.

**Comment by webAbhi** [comment]
Hey @tejakummarikuntla i would like to help here. can u please assign this to me ?

**Comment by tejakummarikuntla** [comment]
Hey @webAbhi , I appreciate your interest in contributing; thank you.
Since this issue holds the label `good first issue` let's wait to welcome other first-time contributors like yourself.

**Comment by VinayakSingh2001** [comment]
Hey @tejakummarikuntla I would like to work on this, can you please assign this to me !!

**Comment by Shweta-Tapele** [comment]
Hey @tejakummarikuntla I would like to work on this, if anyone hasn't already started working on it.

**Comment by tejakummarikuntla** [comment]
Hey @VinayakSingh2001 , since there's an issue assigned to you. Assigned this issue to @Shweta-Tapele

**Comment by tejakummarikuntla** [comment]
Hey @Shweta-Tapele Given the duration of the assignment with no recent updates, we need to unassign the task. Your understanding and cooperation in this matter are greatly appreciated.

**Comment by JunedKhan101** [comment]
@tejakummarikuntla Can you assign this to me? I'd like to work on it.

**Comment by tejakummarikuntla** [comment]
Hey @JunedKhan101 , We greatly appreciate your interest. However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. We hope you understand our decision and thank you for your understanding.

**Comment by Abhinav-CHD** [comment]
@tejakummarikuntla Can I work on this issue?

**Comment by dpsi9** [comment]
Hey anyone working on this , if not can someone assign this to me or can I work without being assigned

**Comment by sarthaksharma27** [comment]
Hey @tejakummarikuntla i am new to open source and i think i can solve this issue

**Comment by Ramana5564** [comment]
Hello @tejakummarikuntla, 

I'm excited to contribute to this project, and I've been exploring the issue related to the scrollbar in the Marketplace section.

To resolve it, I plan to implement a conditional scrollbar that will only appear when the content in the Marketplace exceeds the available space. This will provide users with a cleaner and more user-friendly interface.

As this is my first contribution to this project, I'd greatly appreciate the opportunity to work on this issue. It's a great chance for me to learn more about the project and make a meaningful contribution to its improvement.

Please consider assigning this issue to me, and I'll do my best to deliver a high-quality solution promptly.

Thank you for your consideration!

**Comment by sarthaksharma27** [comment]
Hey @Ramana5564 I am getting some error while setting up project locally can you help me out ?

**Comment by Ramana5564** [comment]
Yeah @sarthaksharma27, tell me exactly where you getting error. I am happy if i can help in any way possible.

**Comment by Robert-Kovalcuk** [comment]
Hello may I work on this issue?

**Comment by sharathkumar55** [comment]
HI @withshubh can i work on this issue to start my open source contribution

**Comment by igurisandhu** [comment]
@tejakummarikuntla please if you may assign this issue to me, I will be very thankful because this will be my very first open source contribution. Thanks.

**Comment by PrinceSachan** [comment]
> #### Current Behavior:
> The Installed & Marketplace page in ToolJet displays a scrollbar at all times, even when there are no items present on the page.
> 

> #### Steps to Reproduce:
> 1. Set up ToolJet locally.
> 2. Enable the Marketplace feature following the instructions provided in the ToolJet documentation (https://docs.tooljet.com/docs/contributing-guide/marketplace/marketplace-setup).
> 3. Navigate to the Marketplace section.
> 4. Observe that a scrollbar is present on the page, regardless of the number of items displayed.
> 
> #### Expected Solution:
> To resolve this issue, the scrollbar should only appear when the number of items on the page exceeds the available space. When there are no items or when the items fit within the page, the scrollbar should not be displayed, providing a more visually streamlined and intuitive user interface.
> 
> ### Screenshots or Screencast
>  Screen.Recording.2023-06-22.at.4.39.19.PM.mov

Hi, Shubhendra I understand this issue and I can work on this, if you assign this issue to me. It'll be great.

**Comment by karan-rathod-316** [comment]
Hi @PrinceSachan, Are you still interested in picking this issue?

**Comment by maniksharma424** [comment]
Hi @karan-rathod-316 if this issue is not picked up 
I would like to fix this and make my first OS contribution

**Comment by karan-rathod-316** [comment]
Hi @maniksharma424, assigning this to you. Thank you for your interest in contributing to ToolJet.

**Comment by 2001asjad** [comment]
Hello @maniksharma424, are there any updates from your side? Do let us know if you're still interested in working on this issue.

**Comment by Ded-Codes** [comment]
Hello @maniksharma424 Can you assign this to me? I'd like to work on this issue.

**Comment by 2001asjad** [comment]
Sure @Ded-Codes, I am assigning this issue to you. Thanks for contributing to ToolJet :)

**Comment by nick2432** [comment]
can i work on this?

**Comment by 2001asjad** [comment]
Hi @Ded-Codes , are you still working on this issue?

**Comment by Ded-Codes** [comment]
> Hi @Ded-Codes , are you still working on this issue?

I'm trying to contribute for the first time and encountered some issues while setting it up on my local machine (macOS).

**Comment by 2001asjad** [comment]
Hey @Ded-Codes , you con join ToolJet's [Slack](https://join.slack.com/t/tooljet/shared_invite/zt-2gr7yuwgm-PXK9I33xbtYhbv5IrfElGw), and ask your queries in the Contributors channel.

**Comment by 2001asjad** [comment]
@Ded-Codes, let me know if you're going forward with the issue.

**Comment by karan-rathod-316** [comment]
Unassigned due to lack of progress.

**Comment by gdhyani** [comment]
can i work on this? @karan-rathod-316

**Comment by 2001asjad** [comment]
Hey, @gdhyani, I am assigning this issue to you. Happy Coding :)

**Comment by 2001asjad** [comment]
@gdhyani , are there any updates?

**Comment by SohamPatel0810** [comment]
Hi,
Can you please assign this task to me ?

**Comment by 2001asjad** [comment]
Hi @SohamPatel0810, I am assigning this issue to you. Thanks for your interest in contributing to ToolJet!

**Comment by PriteshKiri** [comment]
Hey @SohamPatel0810 ,
Any updates on this issue?

**Comment by ShyanRoyChoudhury** [comment]
Please assist it to me. I would love to fix it.

**Comment by PriteshKiri** [comment]
@ShyanRoyChoudhury assigned it to you. Happy coding :)

**Comment by PriteshKiri** [comment]
Thanks for the quick fix @ShyanRoyChoudhury. Moving it to review.

**Comment by ShyanRoyChoudhury** [comment]
@PriteshKiri Someone else who is not assigned did it. Not me.

**Comment by PriteshKiri** [comment]
Sorry @ShyanRoyChoudhury I missed that. Moving it back to development. Let me know when you are done with the issue.

**Comment by Sanil-Surve** [comment]
Hey @PriteshKiri , Can you assign me this issue bcoz I can solve this I have came across such issues in earliar development Experience.

**Comment by PriteshKiri** [comment]
Thank you for your contribution @ShyanRoyChoudhury. I am moving the PR to review.
