### ISSUE TITLE
[docs]: update generate file action

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6833]
### Summary

The two pages in the docs needs to be updated:
- https://docs.tooljet.com/docs/actions/generate-file - In the description, it is mentioned that the only supported file type is `csv`, add `text` also as the supported file type. Add a info section below the description to link to how to run actions using RunJS doc
```
:::info
Check the how-to guide to [run actions using RunJS](https://docs.tooljet.com/docs/how-to/run-actions-from-runjs)
:::
```
- https://docs.tooljet.com/docs/how-to/run-actions-from-runjs - In the generate file section, update the file type from `text` to `plaintext`

### Issue Type

Documentation bug

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by ankitmohanty18** [comment]
Hi @withshubh, I would like to work on this issue if its still open.

**Comment by withshubh** [comment]
Closing this as fixed internally.
