### ISSUE TITLE
Inconsistency in field name and placeholder

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6845]
### What is the expected behaviour?
Field name and the corresponding placeholder should be consistent

### What is the current behaviour?
Users tab: Enter full name (field name) vs Enter first name (placeholder)
Groups tab: Add new group (field name) vs Enter name (placeholder)

### How to reproduce the issue?

1. Go to workspace settings- Users tab and Groups tab
2. Verify the field name and the placeholders
3.

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/8a87cc40-da74-40ed-9be3-595b7fa635ac

**Comment by habeeb-an** [comment]
can i do this? @dishag18

**Comment by habeeb-an** [comment]
@dishag18 Implemented suggested change.
Please check.

**Comment by Dvinod1** [comment]
I want to work on this issue, please assign me ?

**Comment by JunedKhan101** [comment]
This seems like a good issue to kickstart contributing to this project. Kindly assign this to me if it's open.

**Comment by JunedKhan101** [comment]
@tejakummarikuntla @dishag18 I have created a pull request for this please review and let me know if it required any changes:
https://github.com/ToolJet/ToolJet/pull/6959

**Comment by JunedKhan101** [comment]
Hi, just following up that the PR hasn't been reviewed, please review and let me know if it requires any changes.

**Comment by tejakummarikuntla** [comment]
Hey @JunedKhan101 , thank you for the PR; our team will promptly review the PR and provide comments if any changes are required
