### ISSUE TITLE
Left sidebar inspector gets blurred when query panel is opened

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#6866]
### Environment

All environments
### What is the expected behaviour?

Left sidebar inspector should be clearly and legibly rendered.

### What is the current behaviour?

Left sidebar inspector gets blurred when query panel is opened

### How to reproduce the issue?

1. Open the query panel
2. Open the inspector
3. Try to expand more and more nodes in the inspector tree

### Screenshots or Screencast
<img width="411" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20333972/043402f3-e9a7-49cb-805f-08d201303bbc">

**Comment by Noothan-am** [comment]
Hey, @sherfin94. I got the error. where clicking somewhere outside the tree causes it to become unblurred, but clicking on the tree makes it blur again. I have attached video in which i could get the exact problem. I think it might help to fix this issue
please assign it to me i will try to fix this issue.

https://github.com/ToolJet/ToolJet/assets/100135382/b30f497d-d204-4228-ad4a-58eebfb1d6d6

**Comment by emidhun** [comment]
Additional Point: all the left side panel, (Inspector, pages, Debugger..) are blur when it is scrollable, or it has more  elements that its normal height.
