### ISSUE TITLE
PasswordInput Component Not Adapting to Dark Mode

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6880]
### Overview
The `passwordinput` component in ToolJet does not adjust its appearance when switching to dark mode. While other components, such as the `textinput`, display correctly in darker versions, the password input component remains in white even when dark mode is enabled.

### Steps to Reproduce:
1. Navigate to the ToolJet dashboard.
2. Cerate a new app
3. Drag and drop the `passowrdinput` component
4. Enable dark mode from the left side bar

### Expected Behavior:
When dark mode is enabled, the `passwordinput` component should adapt to the darker color scheme, similar to how the `textinput` component behaves.

![image](https://github.com/ToolJet/ToolJet/assets/34749692/d31caeb4-668c-4891-8375-265c54021b50)

**Comment by rahul5522** [comment]
Hi @tejakummarikuntla , i would like to work on this issue.

**Comment by anipr2002** [comment]
hey, I would like to work on this issue!

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @rahul5522 assigned this to you.

@anipr2002 we assign issues on FCFS, kindly look into other good first issue ex: # 6881

**Comment by tejakummarikuntla** [comment]
Hey @rahul5522 , were you able to progress with the issue?

**Comment by rahul5522** [comment]
Hi @tejakummarikuntla , yes I did some progress, but as my system(windows) is running slow while using docker, it's taking more  than expected time for debugging.

**Comment by rahul5522** [comment]
Hi @tejakummarikuntla , please review the changes.

**Comment by tejakummarikuntla** [comment]
Hey @rahul5522 , thanks for raising the PR; our team will promptly review it for the coming releases.
