### ISSUE TITLE
Page Rename UI Not Adapting to Dark Mode

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6881]
### Description 

When editing the page name in ToolJet Pages, while in dark mode, the UI for the rename section does not transition to the darker color scheme. This inconsistency is noticeable, especially when comparing it to the behavior while creating a new page, which correctly adapts to dark mode.

### Steps to Reproduce:

1. Create a new app.
2. Enable dark mode in the settings.
3. Locate a page that you wish to rename.
4. Click on the page options and select `Rename` action.
5. Observe the UI elements and color scheme of the rename section.

### Expected Behavior:

When entering the page rename mode in dark mode, the UI elements related to the renaming functionality should adjust their appearance to match the darker color scheme, similar to how the query name editing UI behaves.

### Actual Behavior:

The UI elements within the rename section retain their lighter styling and do not transition to the dark mode color scheme.

### Screenshot
<img width="370" alt="Screenshot 2023-06-29 at 10 22 33 PM" 
src="https://github.com/ToolJet/ToolJet/assets/34749692/1cf98bab-cabc-4a11-9f9c-b0abf440943d">

**Comment by nemarugommula** [comment]
Hi @tejakummarikuntla, I've been testing it on the localhost instance that I took from the develop branch, but I couldn't replicate the problem(it is working as expected in Chrome, safari, and Firefox). However, when I checked in the Tooljet production instance(https://app.tooljet.com/), I could see the issue occurring there. 

Local  👇 
Image : 


<img width="652" alt="Screenshot 2023-06-30 at 5 22 17 PM" src="https://github.com/ToolJet/ToolJet/assets/35486999/64b51319-d86a-42dd-baaf-8e71e58594f2">

Video : 

https://github.com/ToolJet/ToolJet/assets/35486999/ce8a50a7-b93e-47b0-a648-0732cb40764e

**Comment by itsajay1029** [comment]
Can you assign this issue to me and explain on what needs to be done ? @tejakummarikuntla

**Comment by tejakummarikuntla** [comment]
Yes, @nemarugommula, the issue got addressed in the recent upgrade; thank you for brining this up.
Closing this issue.

**Comment by tejakummarikuntla** [comment]
Yes, @nemarugommula, the issue got addressed in the recent upgrade; thank you for bringing this up.
Closing this issue.
