### ISSUE TITLE
[Dark mode]- UI inconsistency when user selects autofill values

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6928]
### What is the expected behaviour?
UI should be consistent in dark mode when user either enters any value or selects the value from autofill option

### What is the current behaviour?
Background colour of the input box is different if user enters value vs when auto selects it.

### How to reproduce the issue?

1. Go to Workspace settings- User & permissions tab
2. Click on Add user, enter name in one box and use any available option from autofill popup in another input box
3. seems there across all the input boxes
4. verify workspace variable creation popup as well

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/e2e030ad-bf38-474f-81fa-2d246f7634f7

**Comment by Dvinod1** [comment]
@thehacklady Can I work on this issue? Please assign me.

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @Dvinod1. Assigned this issue to you.

**Comment by Paras0750** [comment]
If @Dvinod1 is not doing it can you assign it to me?, I would like to work on this issue.

**Comment by JunedKhan101** [comment]
Hi @tejakummarikuntla, would you be kind enough to assign this to me?

**Comment by Dvinod1** [comment]
Hey @JunedKhan101 ,I have sorted the issue, It will take minimum time to PR

**Comment by JunedKhan101** [comment]
No worries Thanks! @Dvinod1 :)
