### ISSUE TITLE
Enhance "Send" button behavior in Suggest Datasource

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6940]
### Overview
There is an issue with the behavior of the "Send" button in the "Suggest Datasource" section of the Global Datasources modal. The problem is that the button remains enabled even when no text is entered in the corresponding input field.

### Here are the steps to find and address the issue:

1. Go to the Global Datasources section in ToolJet.
2. Click on the `Suggest` in "Don't see what you were looking for? Suggest" text in the bottom left of the modal.
3. Observe that the "Send" button is enabled by default without any input in the field.
3. Enable the "Send" button only when text is entered in the input field.

### Screenshot

<img width="1673" alt="image" src="https://github.com/ToolJet/ToolJet/assets/34749692/f33c0144-4b17-45aa-9506-0fbcdbf7f306">

Whenever the input field is empty, the "Send" button should be automatically disabled.
This is to ensure that the "Send" button remains disabled unless there is valid input text entered in the associated input field.

**Comment by habeeb-an** [comment]
can you assign this to me?

**Comment by Anikets08** [comment]
hey @tejakummarikuntla can i get the issue

**Comment by JunedKhan101** [comment]
@tejakummarikuntla I would like to take this up. Kindly assign this to me.

**Comment by tejakummarikuntla** [comment]
Hey @habeeb-an , @JunedKhan101 , thanks for your interest. Given this issue holds the tag good first issue, let's wait to welcome first-time contributors like yourself to the project.

**Comment by tejakummarikuntla** [comment]
Hey @gl-cardillo , thanks for your interest; assigned this to you.

**Comment by tejakummarikuntla** [comment]
Hey @gl-cardillo , were you able to progress with the issue? kindly let us know if you need any help.

**Comment by tejakummarikuntla** [comment]
Thanks for your contribution, @Raju-github-profile. We shall progress this for reviews.
