### ISSUE TITLE
Dark Mode Inconsistency in Query confirmation dialog box

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6942]
### Overview
There is an issue with the confirmation dialog box when executing a query with the "Request Confirmation before Running Query?" toggle turned on. The problem arises when the application is in dark mode, as the confirmation dialog box fails to adopt the dark mode styling. To reproduce and address this issue, please follow the steps below:

### Steps to Reproduce:

1. Switch to dark mode in the application.
2. Create a dummy query.
3. Add a button and set an event to execute the previously created dummy query.
3. Preview the application by clicking on the eye icon located at the top right corner in the app builder.
4. In the application preview, click on the button to observe that the confirmation alert does not adopt the dark mode styling.

To resolve this issue, we need to refactor the code responsible for the confirmation dialog box, ensuring that it appropriately adopts the dark mode styling when the application is in dark mode.

### Video

https://github.com/ToolJet/ToolJet/assets/34749692/fafec125-5813-4600-bc40-d2705e84c2ea

**Comment by DSY4444** [comment]
Hi @tejakummarikuntla  can you please assign this issue to me.

**Comment by tejakummarikuntla** [comment]
Thank you for your interest @DSY4444 , assigned this issue to you.
