### ISSUE TITLE
Refactor: Modify the prompt text with corrections

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#6946]
**Description:**

On creating a new application in a fresh workspace without any datasources, when going into the query panel the text in the query panel under Global Datasources which is “No global datasource have been added. add new datasource to connect it to your app” needs to be updated.

**Steps to Reproduce:**

1. Create a fresh workspace by clicking on bottom of the sidebar where it says “Tooljet” with an arrow on its side.
2. After creating the workspace create a new application in that workspace by clicking on the “Create New App” button.
3. Open the query panel which is situated in the lower half of the app builder window.
4. Check for the text under the “Global Datasources” heading.

**Expected Output:**

The text states “No global datasource have been added. add new datasource to connect it to your app” needs to be updated to “No global datasources have been added. Add a new datasource to connect to your app.”

<img width="778" alt="Screenshot 2023-07-05 at 5 51 00 PM" src="https://github.com/ToolJet/ToolJet/assets/85864291/d25a2238-7d86-48c7-9482-85c15bdcf00f">

**Comment by PrabhjeetKalsi** [comment]
@ShazanRizvi can you assign this to me please?

**Comment by tejakummarikuntla** [comment]
Hey @PrabhjeetKalsi , thank you for your interest; assigned this issue to you.

**Comment by PrabhjeetKalsi** [comment]
@tejakummarikuntla raised a PR for fix [here](https://github.com/ToolJet/ToolJet/pull/6962)
