### ISSUE TITLE
Able to rename query in released version

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6953]
### What is the expected behaviour?
User should not be able to rename the query for released version

### What is the current behaviour?
User is able to rename query from query manager even for released version

### How to reproduce the issue?

1. create app with some datasource query
2. release the version of app
3. reopen application and try to rename the saved query

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/3afca430-d5b7-497d-8fe3-45cb63a7495e

**Comment by habeeb-an** [comment]
Can you assign this to me?

**Comment by Nandinisaha13** [comment]
Closing because it is fixed.
