### ISSUE TITLE
Number input component shows with decimal values instead of the given.

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#6984]
### Version Information
2.9.2
### Environment
    ToolJet Cloud / Docker / Linux / MacOS 

### What is the expected behaviour?
  - If  we are entering a value  less that the minimum or greater that maximum value,
  The entered value should change to the minimum or maximum values without any decimal changes. (ie: If min value is 5 it should show 5 only, not 5.00)
 - It is hard to enter the value which start with a number less that the minimum value.

### What is the current behaviour?
- If we are entering a value lesser than the minimum value, it is changing to the minimum value with two decimal points.
5=> 5.00
- Assume min value is 9, and if we are trying to edit the value to 111 then just after entering the first digit, it is changing to 9.00

### How to reproduce the issue?

1.Add a number input component.
2. Set min value as 5.
3. Enter 3 on the input (case-1)
4. Enter 111 on the input.

**Comment by DSY4444** [comment]
Hi @emidhun, I would like to work on this issue. can you please assign this issue to me?
