### ISSUE TITLE
ToolJet Database Query restricting the number of columns in create rows

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7020]
### Environment

ToolJet Cloud

### What is the expected behaviour?

The ToolJet Database query when making the create rows query and adding columns, should add the desired number of columns that are available in the ToolJet Database Table.

### What is the current behaviour?

When creating a ToolJet Database query in the query panel and adding columns, it takes 5 columns as expected. After adding 5 columns when clicking on **add column** button it would randomly delete one of the pre-existing 5 columns to add a new column and it would not add a new 6-column fields

### How to reproduce the issue?

1. Create an application using the **Create new App** button.
2. Create a new table in the ToolJet Database and add more than 6 columns
3. Go to the application created in step1 and add a ToolJet Database Query from the query panel
4. In the query created, select the Table name as the name of the table created in step 2.
5. In the operations dropdown select create rows.
6. Add input components to the application which can take some inputs individually
7. In the columns section of the ToolJet Database query click to add columns and map the values from the input to it
8. Try adding more than 5 columns in the ToolJet database query and observe the scenario

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/85864291/03d5191b-0b0e-404f-b4b1-217464b36a21

**Comment by DSY4444** [comment]
Hi @ShazanRizvi , I would like to work on this bug. Can you please assign this me?
