### ISSUE TITLE
Enhancement: Enable submitting on the create folder dialog box on pressing Enter/Return key

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7021]
**Description:**

The Create folder dialog box on the create new app page does not submit on pressing enter key on the keyboard, and can only be submitted by clicking the Create folder button.

**Steps to Reproduce:**

1. Open ToolJet and you will be presented with the create new app page.
2. In the sidebar just below the create new app button lies the section of folders.
3. Click on the **+** icon on the side of the heading **Folders.**
4. A **Create folder** dialog box opens up write a folder name and try to create it by pressing the enter/return key

**Expected Output:**

The create folder dialog box should submit and create folder when the user enters folder name and presses enter/return on the keyboard

https://github.com/ToolJet/ToolJet/assets/85864291/0ebbd375-3f45-4c68-bdd6-10bd8d0a9b62

**Comment by tejbhatt** [comment]
hi can i work on this issue? what is the deadline and is there any other way to run the project apart from docker?

**Comment by mustajab-ikram** [comment]
Hi @ShazanRizvi. I've already completed the enhancements for issue #7021. If it's still unassigned, please assign it to me. I would love to contribute.
Thank you!

**Comment by tejbhatt** [comment]
hi @tejakummarikuntla you can merge @mustajab-ikram pr i dont have any issue.i am having some interview scheduled next week so wont be able to work thanks

**Comment by mustajab-ikram** [comment]
Hi @tejbhatt,
If you are not working on it, can u please unassign yourself so it could be reassign to me? @tejakummarikuntla Can I now take this up?
Thank you for your understanding and consideration!

**Comment by FaroqueAbdullah** [comment]
Hi @tejakummarikuntla . I want to work on this issue . Can you please assign it to me ?

**Comment by tejakummarikuntla** [comment]
Hey @FaroqueAbdullah , thanks for your interest. Assigned the issue to you.

**Comment by FaroqueAbdullah** [comment]
@tejakummarikuntla  . Sorry I had removed the assignment of this task for the first time. But I have completed it now. Can you please check and let me know. Thank!
