### ISSUE TITLE
Copilot screen UI is not consistent in dark mode

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#7030]
### What is the expected behaviour?
UI should be consistent and user should be able to see entire screen in dark mode similar to light mode

### What is the current behaviour?
User is not able to see the information message displayed on the screen in dark mode

### How to reproduce the issue?

1. go to copilot screen
2. change the mode to dark and verify UI
3.

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/143b12c7-7deb-4020-8e27-5cfceceb482e

**Comment by JunedKhan101** [comment]
I'd like to take this up. Kindly assign this to me.
