### ISSUE TITLE
Queries is returning 'undefined' as blank in preview.

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#7058]
### Environment

    ToolJet Cloud / Docker / Linux / MacOS 

### What is the expected behaviour?
- If data is undefined it should show undefined on preview.

### What is the current behaviour?
- Preview tab is empty.

### How to reproduce the issue?

1. Add a runjs query `return undefined`
2. Click on preview.
3. Verify.

**Comment by shubh22** [comment]
This is fixed.
