### ISSUE TITLE
Need to expose page's data on runPy.

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#7059]
### Version Information
2.10.1
### Environment

    ToolJet Cloud / Docker / Linux / MacOS

### What is the expected behaviour?
RunPy is not able to access page data.

### What is the current behaviour?
RunPy should be able to use page data.

### How to reproduce the issue?

1.  Create a runPy query `page`
2. Preview / run
3. Verify

### Screenshots or Screencast
<img width="786" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20367955/ecbc5872-ab62-473e-9c33-08ad4359e226">

**Comment by blank0537** [comment]
@emidhun @sherfin94 @shubh22 I have fixed this issue. After fix it returns page data
<img width="1374" alt="runpy page data exposed" src="https://github.com/ToolJet/ToolJet/assets/111295371/ce8c9a6e-cdc8-4766-b2be-43d9aa2f1953">
I have raised PR #8608
