### ISSUE TITLE
Dark Mode compatibility issue with datepicker component in time selection UI

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#7072]
### Description:
When using the Datepicker component in ToolJet and enabling the "Enable Time selection" option, there is a UI issue when expanding the time section. The UI is not adopting Dark mode.

### Steps to reproduce:
1. Add a datepicker component to a Tool Jet application.
2. Toggle the "Enable Time selection" option for the Date Picker component.
3. Click on the time section part, and notice the UI.

### Screenshot
<img width="995" alt="image" src="https://github.com/ToolJet/ToolJet/assets/34749692/1f5fd43e-fd7e-4f0f-9fdf-f4b268d6a3be">

**Comment by UtkarshDixit-py** [comment]
I can work on this. Please assign this issue to me.

**Comment by JunedKhan101** [comment]
@tejakummarikuntla Can I pick this up?

**Comment by tejakummarikuntla** [comment]
Hey @UtkarshDixit-py , thanks for your interest; assigned this to you.

**Comment by tejakummarikuntla** [comment]
Hey @UtkarshDixit-py , were you able to progress with the issue? Feel free to let us know if you need any help.

**Comment by UtkarshDixit-py** [comment]
> Hey @UtkarshDixit-py , were you able to progress with the issue? Feel free to let us know if you need any help.

@tejakummarikuntla Pinged you on slack

**Comment by AAYUSH-droid** [comment]
@tejakummarikuntla in any case can i work on this issue

**Comment by tejakummarikuntla** [comment]
Hey @UtkarshDixit-py ,
Given the duration of the assignment with no recent updates, we need to unassign the task. Your understanding and cooperation in this matter are greatly appreciated.

**Comment by JaswanthJeethu18** [comment]
Hey @tejakummarikuntla I would like to work on this issue.

**Comment by JaswanthJeethu18** [comment]
As I am familiar with your tech stack and codebase, I would able to solve this issue quickly

**Comment by sharathkumar55** [comment]
Hey @tejakummarikuntla can i work on this issue to start my open source contribution

**Comment by harshbsharma** [comment]
Would like to work on it.

**Comment by karan-rathod-316** [comment]
Hi @harshbsharma, Assigning this issue to you. We appreciate your interest in contributing to ToolJet.

**Comment by harshbsharma** [comment]
@karan-rathod-316 Sorry I was unable to work on issue due to health reasons. Please feel free to reassign it.

**Comment by karan-rathod-316** [comment]
Hi @harshbsharma, this is still assigned to you. Let me know if you are working on it.

**Comment by leviduncan** [comment]
Hi @karan-rathod-316 , I would like to try to fix this issue.

**Comment by aarjun8060** [comment]
hi @karan-rathod-316  I am new in this repo . would you assign this issue to me ??

**Comment by 609harsh** [comment]
hi @karan-rathod-316 please assign this issue to me

**Comment by patelmilanun** [comment]
@karan-rathod-316 I have checked this issue and found out that we can customize the clock icon and input field, but it is not possible to customize the popover which opens up when we click the clock icon.

![image](https://github.com/ToolJet/ToolJet/assets/20059797/0ee5d569-ef8d-4101-9fd0-3b7e352a9124)

I'm only able to customize this much (see screenshot). Do you know any way to do it?

**Comment by karan-rathod-316** [comment]
Hi @patelmilanun, let me loop in @kavinvenkatachalam on this to see if there's some solution to this.

**Comment by patelmilanun** [comment]
I think the screenshot I posted kinda fixing something #6271

**Comment by kavinvenkatachalam** [comment]
@patelmilanun Can you raise a PR and link the issue?

**Comment by patelmilanun** [comment]
Sure I will link both the issues its trying to fix.

**Comment by karan-rathod-316** [comment]
Fixes [#6271](https://github.com/ToolJet/ToolJet/issues/6271)

Hi @patelmilanun, please comment on the related issue so that I can assign it to you.

**Comment by karan-rathod-316** [comment]
Hi @patelmilanun, is there any progress on this?

**Comment by atharvnaik1** [comment]
@karan-rathod-316 Please assign me if its still open .

**Comment by gdhyani** [comment]
If the bug is still there Please let me know i can contribute and can solve this issue. @2001asjad

**Comment by 2001asjad** [comment]
Hi @gdhyani, currently the issue #6818, has been assigned to you :)

**Comment by 2001asjad** [comment]
Hi @atharvnaik1 , are there any updates on this issue?

**Comment by atharvnaik1** [comment]
hi, I am upto it got rushed on office work , will pr this weekend.....

**Comment by 2001asjad** [comment]
Hey @atharvnaik1 , is there any progress from your side?

**Comment by atharvnaik1** [comment]
yes, @2001asjad 
1. Implemented changes in theme.scss an respective files  for select month, year background in dark mode  , day is already correct.
2. Implemented changes in theme.scss and respective files input.react-datepicker-time__input background color from white to dark mode.
3. Updated the time popper for dark theme.

**Comment by 2001asjad** [comment]
Thanks @atharvnaik1 , we will be reviewing your PR.

**Comment by atharvnaik1** [comment]
@2001asjad  Okay, has anyone looked over it?

**Comment by 2001asjad** [comment]
Hello @atharvnaik1, yes, your PR is under review. I will update you soon.
