### ISSUE TITLE
Fix unstable moving top-bar in App Builder

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#7073]
### Description

The moving top-bar in the App Builder is currently experiencing instability and lacks the expected behavior of remaining fixed and stable. To reproduce and understand the issue, you must log in and access the App Buidler page, where the UI issues become apparent.

### Steps to reproduce
1. Log in to ToolJet
2. Enter into an application or create a new application
3. Scroll down forcefully to observe the top bar's behavior during different.

### Video demoing the issue
https://github.com/ToolJet/ToolJet/assets/34749692/2dc57291-211a-464d-92ca-ca3b07e0c443

### Suggested changes as solution

https://github.com/ToolJet/ToolJet/assets/34749692/263b2ec6-a76a-47c7-8e46-bcb7397e0e7a

**Comment by UtkarshDixit-py** [comment]
I want to have a shot at this. Please assign this to me.

**Comment by tejakummarikuntla** [comment]
Hey @UtkarshDixit-py , given an issue already assigned to you, let's wait to welcome other first-time contributors to the project like yourself; thanks for your understanding.

**Comment by V6g1** [comment]
i'm interested to work on this issue

**Comment by fakhruddinkw** [comment]
Can i take this on?

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @V6g1. Assigned this to you.

**Comment by V6g1** [comment]
thanks for considering @tejakummarikuntla .I will get the work done.

**Comment by tejakummarikuntla** [comment]
Hey @V6g1 , were you able to progress with the issue? Feel free to let us know if you need any help.

**Comment by tejakummarikuntla** [comment]
Hey @V6g1 , let us know if you are working on the issue and feel to share if you wish to get this unsigned by chance.

**Comment by V6g1** [comment]
I wish to unsigned the work

**Comment by 4ddx** [comment]
Hey @tejakummarikuntla  I'd be very grateful if you could please let me work on this issue

Thanks!
Best

**Comment by subhajit20** [comment]
@tejakummarikuntla hey, have made a pr for this issue https://github.com/ToolJet/ToolJet/pull/7306
