### ISSUE TITLE
[docs]: Update "RunPy" to "RunJS" in the doc for importing external libraries using RunJS

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#7074]
### Summary

The documentation currently contains references to "RunPy" when it should be "RunJS" in the guide on [how to import external libraries using RunJS](https://docs.tooljet.com/docs/how-to/import-external-libraries-using-runjs/
). This issue aims to correct the text to ensure.

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/how-to/import-external-libraries-using-runjs/

### Steps to reproduce the issue

1. Go to the documentation page: [Link to the documentation](https://docs.tooljet.com/docs/how-to/import-external-libraries-using-runjs/)
2. Scroll down to the section that explains the process of importing external libraries using RunJS.
3. Find the usage of "RunPy" instead of "RunJS" in the text.

<img width="1012" alt="Screenshot 2023-07-20 at 10 29 24 PM" src="https://github.com/ToolJet/ToolJet/assets/34749692/9ed348a2-e138-4129-9c23-00af613d260b">

### Additional Information

To resolve this issue, kindly make the necessary text changes throughout all affected versions of the documentation

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by UtkarshDixit-py** [comment]
I am interested to work on this issue. Please assign.

**Comment by tejakummarikuntla** [comment]
Hey @UtkarshDixit-py , given an issue already assigned to you, let's wait to welcome other first-time contributors to the project like yourself; thanks for your understanding.

**Comment by Paras0750** [comment]
Can you assign me this issue?

**Comment by tejakummarikuntla** [comment]
Thanks for your interest, @Paras0750 . Assigned this to you

**Comment by ishsarin** [comment]
Hi, if this issue is open could I contribute?
