### ISSUE TITLE
[docs]: GIFs present in the documentation appear to be outdated, showing features and functionalities from a previous version of ToolJet

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7078]
### Summary

The GIFs in the[ documentation](https://docs.tooljet.com/docs/data-sources/mssql) are outdated and display an older version of ToolJet. To ensure that the documentation is up-to-date and accurately reflects the latest version of ToolJet, it is essential to update the GIFs with the most recent ones. This way, users can have a clear understanding of the current features, workflows, and user interface of the ToolJet application. 
**Updation is necessary for all the versions of the documentation.**

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/mssql

### Steps to reproduce the issue

1. Open the [documentation](https://docs.tooljet.com/)
2. From the side menu click on the Datasource catalog which opens a sub-menu.
3. Select the Datasource Library and from the sub-menu select MS SQL Server / Azure SQL databases.
4. Observe the GIFs used to explain the docs
<img width="1440" alt="Screenshot 2023-07-21 at 1 50 53 AM" src="https://github.com/ToolJet/ToolJet/assets/85864291/33d78bb4-7658-4f7a-b83b-01703b13b837">

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by ThaungThanHan** [comment]
Hello. I am working on it.

**Comment by tejakummarikuntla** [comment]
Hey @ThaungThanHan , do you want me to assign this issue to you? I see the comment as outdated, kindly confirm.

**Comment by ThaungThanHan** [comment]
> Hey @ThaungThanHan , do you want me to assign this issue to you? I see the comment as outdated, kindly confirm.

Yes, please. I would like to work on this. Sorry about outdated comment, I thought of dropping this but I can take on it now.

**Comment by tejakummarikuntla** [comment]
Thanks for your interest; assigned this to you @ThaungThanHan.

**Comment by ThaungThanHan** [comment]
@tejakummarikuntla Thank you. I have already made a PR.
