### ISSUE TITLE
Table Component: Dynamic Columns activating upon clicking any section in line of toggle switch

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7096]
**Description:**

The toggle switch to turn on and off the dynamic columns allows the user to toggle the dynamic columns functionality in the table component. If the user is clicking in the line of the toggle switch then also the dynamic columns are turned on and off even if the user is not on the toggle switch.

**Steps to Reproduce:**

1. Open ToolJet Application and login
2. Create a new application by clicking on the **Create new app** button.
3. Drag a table component on the canvas of the new application
4. click in the line of the dynamic column **toggle switch** section in the properties of the table component.
5. Click and observe the area which activates the dynamic column.

**Expected Output:**

Clicking on the dynamic columns toggle switch only, should trigger the dynamic columns.

https://github.com/ToolJet/ToolJet/assets/85864291/246c214b-b93f-4e5e-ab91-617e7975caf7

**Comment by aks1809** [comment]
Hi, I went through the code base and found the reason as to why this is happening. It's due to the styles ( display: block )  to the toggle input. I would like to provide a PR to fix this issue as well. Kindly assign this issue to me.

**Comment by tejakummarikuntla** [comment]
Hey @aks1809 , thank you for your interest; assigned this to you.

**Comment by aks1809** [comment]
Hi @tejakummarikuntla, thank you for assigning issue, this PR [fix/#7096](https://github.com/ToolJet/ToolJet/pull/7146) provides fix for the same.
