### ISSUE TITLE
Toggle button and checkbox color is not working

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#7135]
### Environment
All envs

### What is the expected behaviour?
When we set the color for toggle button and checkbox, that color should appear when either of those components are turned on.

### What is the current behaviour?
The color is not appearing

### How to reproduce the issue?

1. Add a checkbox
2. Set its color to red
3. Turn on the checkbox

**Comment by AnuragNishad12** [comment]
Can u show the image of this problem ?
