### ISSUE TITLE
Folders in query manager

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#7140]
### Is your proposal related to a problem?

Query manager does not support organising queries under folders at the moment

### Describe the solution you'd like

Get design from Jaseem

As a developer, I should be able to:

1. Add folders on to the queries section of the query manager
2. Delete folders
3. Rename folder
4. Move existing queries in and out of folders
5. Add new queries directly on to selected folders
6. If a query `myQuery` is moved inside folder `myFolder`, then the query should be accessible as `queries.myFolder.myQuery`

Constraints on folders:

1. Nesting is not allowed, that is, folders are only there in the top level, we cannot add a folder inside another folder
2. Folder naming:
   1.  Unique ( Cannot share name with another folder or query )
   2. Alphanumeric
   3. No special characters or white spaces
   4. Cannot start with a number
   5.  A minimum of 1 character and maximum of 32 characters

PRD: [Here](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-23076)
Design: Here

**Comment by GrowwithNaveen** [comment]
This item is moved to  [Folders in query manager #1567](https://github.com/ToolJet/tj-ee/issues/1567)
