### ISSUE TITLE
[docs]: fix broken links for images

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7158]
### Summary

Three image links are broken in the documentation since their paths are incorrect. 

<img width="1148" alt="Screenshot 2023-07-28 at 11 16 19 AM" src="https://github.com/ToolJet/ToolJet/assets/58169101/737080e6-79ce-45e4-96cd-604057c7503d">
<img width="1148" alt="Screenshot 2023-07-28 at 11 18 08 AM" src="https://github.com/ToolJet/ToolJet/assets/58169101/4f9bf268-dfac-4e53-99e3-ed1202b6ae3f">
<img width="1148" alt="Screenshot 2023-07-28 at 11 19 27 AM" src="https://github.com/ToolJet/ToolJet/assets/58169101/8869d426-e51c-4cc1-86f7-0e26e6edd4fd">

### Issue Type

Documentation bug

### Steps to reproduce the issue

The below table contains 
- broken links(Broken Link column)
- pages on which the broken link exists(Related Page column) 
- and the correct image sources to be used(Replacement Link column)

To fix each link, find the related page of the documentation in the repository, and add the correct image source. 

<google-sheets-html-origin><meta name="sheets-original-selection" data-sheets-range="A1:C4"><meta name="sheets-banding" data-sheets-range="A1:C4" data-sheets-banding-properties="{&quot;1&quot;:{&quot;1&quot;:{&quot;2&quot;:18434,&quot;4&quot;:{&quot;1&quot;:3,&quot;3&quot;:3},&quot;14&quot;:{&quot;1&quot;:3,&quot;3&quot;:3},&quot;17&quot;:1},&quot;2&quot;:{&quot;2&quot;:18434,&quot;4&quot;:{&quot;1&quot;:2,&quot;2&quot;:14411249},&quot;14&quot;:{&quot;1&quot;:2,&quot;2&quot;:14411249},&quot;17&quot;:0},&quot;3&quot;:1,&quot;4&quot;:{&quot;2&quot;:18434,&quot;4&quot;:{&quot;1&quot;:2,&quot;2&quot;:14411249},&quot;14&quot;:{&quot;1&quot;:2,&quot;2&quot;:14411249},&quot;17&quot;:0},&quot;5&quot;:1}}">

Broken Link | Related Page | Replacement Link
-- | -- | --
https://docs.tooljet.com/img/cloud-run/port-and-capacity-tooljet.png | https://docs.tooljet.com/docs/2.5.0/setup/google-cloud-run/ | src="/img/cloud-run/port-and-capacity-postgrest.png"
https://docs.tooljet.com/img/datasource-reference/airtable/airtable_delee.png | https://docs.tooljet.com/docs/1.x.x/data-sources/airtable/ | src="/img/datasource-reference/airtable/airtable_delete.png"
https://docs.tooljet.com/img/datasource-reference/custom-javascript/custom-javascript.png | https://docs.tooljet.com/docs/1.x.x/data-sources/custom-js/ | src="/img/datasource-reference/custom-javascript/run-js.png"

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by webAbhi** [comment]
Hi @karan-rathod-316 I would like to work on this, can you please assign this to me ?

**Comment by karan-rathod-316** [comment]
> Hi @karan-rathod-316 I would like to work on this, can you please assign this to me ?

Hi Abhijeet, thanks for your interest. I have assigned the issue to you.

**Comment by ishsarin** [comment]
Hi, if this issue is open, can I contribute?

**Comment by karan-rathod-316** [comment]
> Hi, if this issue is open, can I contribute?

Hi Ish,

Thank you so much for your interest. This issue has already been picked. Do keep an eye out for other similar issues that we might open in future.
