### ISSUE TITLE
[docs]: Broken documentation links in the Harper DB plugins folder in repository.

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7169]
### Summary

**Description**
When we go into the ToolJet repository on GitHub and then go into the plugins folder and navigate to the HarperDB folder and then click on the link present in the plugins folder in the repository Readme File, it takes us to a page that says **Page no found** Even if the documentation exists.

**Expected Output:**
The link present in the Readme file of the Harper DB plugin folder should take the user to the [documentation](https://docs.tooljet.com/docs/marketplace/plugins/marketplace-plugin-harperdb) of the Harper DB plugin. 

<img width="1433" alt="Screenshot 2023-08-01 at 2 10 45 PM" src="https://github.com/ToolJet/ToolJet/assets/85864291/8e644011-6f53-4d4b-8f9d-a3b0b08965db">
<img width="1440" alt="Screenshot 2023-08-01 at 2 11 24 PM" src="https://github.com/ToolJet/ToolJet/assets/85864291/5c794c37-6677-4fb2-a965-3f6c13c29230">

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/harperdb

### Steps to reproduce the issue

**Steps to Reproduce:**
1. Open the ToolJet repository on GitHub.
2. Find and click on the plugins folder and then navigate to the Harper DB folder and open it
3. Scroll to the end of the page and click on the documentation link in the Readme section.
4. Observe the page which opens up when the link is clicked.

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by webAbhi** [comment]
@ShazanRizvi can you please assign this to me ?

**Comment by tejakummarikuntla** [comment]
Hey @webAbhi. Since there's already an issue assigned to you, let's wait to welcome first-time contributors like yourself; thanks for your understanding.

**Comment by sudip57** [comment]
Can you assign this issue to me ?

**Comment by tejakummarikuntla** [comment]
Hey @sudip57 . Since there's already an issue assigned to you, let's wait to welcome first-time contributors like yourself.

**Comment by Sandeep277** [comment]
Hey, @ShazanRizvi can you assign this issue to me?

**Comment by tejakummarikuntla** [comment]
Hey @vrun1208, Thanks for your interest in contributing to the project. Please review our contributor guidelines and comment on your interest before resolving the issues. Since your contribution is the first time to the project, assigning this issue to you.

**Comment by vrun1208** [comment]
Hi @tejakummarikuntla, apologies for that, next time I'll keep that in mind before opening PR
