### ISSUE TITLE
Improve Code Hinter Performance

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#7171]
**Title:** Improve Code Hinter Performance for Large Applications

**Description:**
We have observed that the Code Hinter in ToolJet tends to slow down when handling large applications. The Code Hinter's primary responsibility is to resolve code references from the input, and this process can become quite heavy, particularly when dealing with multiple references.

To address this performance issue, I propose the following improvements and fixes:

1. **Selective Resolution:** The Code Hinter should now only resolve references when there are actual changes to the current value or updates to the editor state. This means we will avoid unnecessary resolution calls when the input remains unchanged, leading to more efficient performance.

2. **Refined Trigger Mechanism:** Currently, the resolveReferences function is triggered whenever a Code Hinter gains or loses focus. However, this resolution process should only be triggered when there are actual changes to the input, ensuring a more precise and optimal resolution process.

3. **Handling Query Manager Updates:** If the query manager receives an update, the Code Hinter may unmount and remount, triggering the resolver again. We need to address this scenario to maintain the desired performance improvements.

The overall goal of these changes is to optimize the Code Hinter's performance by resolving references more intelligently, resulting in a smoother user experience, especially when dealing with larger applications.

**Comment by Vickeytrades** [comment]
hallo arpit show me your page
