### ISSUE TITLE
Mongo DB Datasource Logo not visible on the Add Datasource Dialog box when in Dark Mode

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7174]
### Environment
All Environments

### Description
When the Add Datasource Dialog box is opened in the light mode the Mongo DB logo is clearly visible but when switching to the dark mode due to the color of the logo it is not visible very easily.

### Steps to Reproduce

1. Open up ToolJet application and switch to the dark mode using the 🌙 icon in the bottom left of the page.
2. Navigate to the Datasource Tab which is present in the left-most icon sidebar.
3. On opening the Datasource tab click on the button **Add New Datasource** button.
4. Add new Datasource Dialog box opens up.
5. Switch the dark and light modes and observe the icon on the Mongo DB datasource button present in this dialog box.

### Expected Output

The logo on the Mongo DB datasource button should be visible in both dark and light mode, can refer to [MongoDB Brand resources](https://www.mongodb.com/brand-resources) for the appropriate image.

### Screenshots
<img width="1134" alt="Screenshot 2023-08-02 at 12 18 25 AM" src="https://github.com/ToolJet/ToolJet/assets/85864291/98aff470-1da9-424e-87fc-6886a13562ae">
<img width="1120" alt="Screenshot 2023-08-02 at 12 18 41 AM" src="https://github.com/ToolJet/ToolJet/assets/85864291/749d9b52-32d6-41d9-b506-09be1afb45f8">

**Comment by moulibrota-das** [comment]
Hi! I am interested in this issue. Can you please assign me for this.

**Comment by tejakummarikuntla** [comment]
Hey @moulibrota-das , thanks for your interest, Assigned this to you.

**Comment by moulibrota-das** [comment]
I have gone through the code and the way the logos are handeled the simpleset way to resolve this will be changing the mongodb logo. 

The current logo in use is MongoDB_Logomark_SlateBlue:
<img width="214" alt="image" src="https://github.com/ToolJet/ToolJet/assets/88196189/b2df2878-6875-43f8-a640-aa48b4aa4cbe">

Proposed change is the MongoDB_Logomark_ForestGreen:
<img width="230" alt="image" src="https://github.com/ToolJet/ToolJet/assets/88196189/96f1b864-7624-4cd9-a93c-780ab6131df7">

**Comment by SWASTI-SUNDAR** [comment]
@ShazanRizvi  please assign this issue to me i want to contribute
