### ISSUE TITLE
Search Bar: Placeholder "Search Item" needs to be updated to "Search apps in this workspace"

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7202]
### Environment
All Environments

### Description
Upon visiting the homepage of the ToolJet application, you will come across a search bar designed to find applications within the specific workspace. Currently, the placeholder text in the search bar reads "Search Item," which requires updating to "Search apps in this workspace" for improved clarity and user understanding.

### Steps to Reproduce:

1. Go to the ToolJet Application and log into the application.
2. If not created any application before, create an app using the "Create new App" button present on the sidebar.
3. Once the app is created go back to the previous page.
4. On the previous page, where now the application created just now can be seen and the search bar is also visible
5. Check for the placeholder text in the search bar

### Expected Output
The current placeholder text on the search bar is "Search Item." To enhance clarity and provide a better user experience, it should be updated to "Search apps in this workspace." This revised text will more accurately guide users on how to utilize the search bar to find applications within the designated workspace.
<img width="1433" alt="Screenshot 2023-08-04 at 12 25 24 PM" src="https://github.com/ToolJet/ToolJet/assets/85864291/4b486c96-f0cb-4bb8-bb1f-45b079ba9806">

**Comment by aamani98** [comment]
I would like to work on this issue.  Please assign this to me.

**Comment by deeepanshu** [comment]
hey @ShazanRizvi can you assign this to me?

**Comment by ishsarin** [comment]
Hi, if this issue is open can I contribute?

**Comment by tejakummarikuntla** [comment]
Hey @MikelGV , I'd request you follow the contributor guidelines; kindly comment about your interest in getting assigned before working on it.

**Comment by thehacklady** [comment]
not yet resolved, will pick up internally.
