### ISSUE TITLE
Google OAuth Redirect Issue with TOOLJET_HOST Configuration Behind Traefik Proxy in Docker Environment

### ISSUE THREAD

**Issue by bayeslearner** [ToolJet/ToolJet#7205]
### Environment

Docker
### What is the expected behavior?

Tooljet is configured to run behind a Traefik proxy within Docker, and it functions properly when I set TOOLJET_HOST to http://localhost:80. By using this configuration, I can successfully access it through https://tooljet.dom.bayeslearner.org, which resolves to a local IP for now.

However, there's an issue with Google Sheets integration. It redirects me to http://localhost:80/oauth2/authorize, which is incorrect since Tooljet operates behind a Traefik proxy.

Additionally, when I change the TOOLJET_HOST setting to https://toolject.dom.bayeslearner.org, I encounter a "bad gateway" error. Attempting to visit https://tooljet.`mydomain` results in failure, and I'm unable to reach the Tooljet client.

What should the value of this setting be to resolve these issues?

**Comment by shah21** [comment]
@bayeslearner, Sorry for the late response. Could you please check the redirect URL that you added on the Google console? The reason it redirected back to the localhost is the wrong url host. Please change the host to reverse proxy if it is incorrect.

**Comment by ajith-k-v** [comment]
Hey @bayeslearner, Check out the solution added by @shah. If you're still having trouble, feel free to reopen the issue.
