### ISSUE TITLE
Events on Dropdowns not working

### ISSUE THREAD

**Issue by nicoruti** [ToolJet/ToolJet#721]
### Version Information
0.7.1

### Environment
Kubernetes

### What is the expected behaviour?
When changing a selection in the dropdown, I would expect the events being triggered.

### What is the current behaviour?
No matter which event I chose (alert, open webpage, run query, etc.), they don't seem to be triggered in any way.

### How to reproduce the issue?

1. Create a new application
2. Add a dropdown (with default values)
3. Add an event (e.g. alert) with type "On select"
4. Save, deploy and launch application

**Comment by Navaneeth-pk** [comment]
@nicoruti  Thanks for reporting the bug. The issue has been resolved and will be included in the next release of ToolJet. The bug is currently resolved on the ToolJet cloud.

**Comment by nicoruti** [comment]
Thanks for the fast fix, @Navaneeth-pk 👍
