### ISSUE TITLE
Unable to select users by clicking on username or email in dropdown

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#7212]
### Environment

    ToolJet Cloud 
### What is the expected behaviour?

When a user clicks on the username or email address of a user in the select div, the user should be selected.

### What is the current behaviour?
When a user clicks on the username or email address of a user in the select div, the user is not selected.

### How to reproduce the issue?

1. Open any existing group
2. Click on the Users tab
3. Select the user from the list

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/20367957/011d6c49-1030-447d-aac7-af3153e7b697

**Comment by DSY4444** [comment]
Hi @ajith-k-v can you please assign this issue to me?
