### ISSUE TITLE
Disable buttons and tabs if user does not have specific access permissions

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#7216]
(Describe your proposed solution here.)

If normal user does not have any specific permissions to perform action and access the tabs, we can disable them directly. 
This will be more user friendly than the current behaviour where system is allowing user to click on the buttons like 'Create app', 'Import app', 'Add datasource' but then on click of it is throwing error toast messages.
We have disabled the tabs and buttons in case of license expiration, something similar can be implemented for this as well.

**Comment by thehacklady** [comment]
will cover separately in different flows, closing this. 

Note - it won't be disable state but a non-editable state.
