### ISSUE TITLE
LDAP: The "Enter" key does not perform the sign in action

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#7217]
### What is the expected behaviour?
When attempting to sign in to the system using LDAP SSO method, pressing the "Enter" key does not trigger the sign in action. To successfully login to the system users are required to manually click the "Sign in" button. 

### What is the current behaviour?
The "Enter" key functionality is currently not supported for this login method.

### How to reproduce the issue?

1. Setup LDAP method in SSO
2. Provide valid credentials and click on enter to perform sign in action
3.

**Comment by thats-sarthak** [comment]
Heyy @dishag18 can you please assign me this issue
