### ISSUE TITLE
[refactor]: Update notification text on copying multiple components

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#7226]
### Overview
The success notification currently says "component copied successfully" while copying a single component. When multiple components are copied, the notification still uses the singular form, causing confusion. To ensure clarity, the notification should accurately display "components copied successfully" for plural instances.

### Steps to Reproduce:
1. Drag and drop multiple components onto the canvas.
2. Select the components on the canvas.
3. Press Ctrl+C (Windows) or CMD+C (macOS) to perform the copy operation.
4. Observe the notification text.

### Expected Behavior:
For single component copies, the notification should remain "component copied successfully." When multiple components are copied, the notification should change to "components copied successfully."

### Screenshot
<img width="895" alt="image" src="https://github.com/ToolJet/ToolJet/assets/34749692/af2189de-e500-4a69-a1d2-373ea191cfc7">

**Comment by ChaitanyaKharya2003** [comment]
I would like to work on this issue, can you assign this to me?

**Comment by tejakummarikuntla** [comment]
Hey @ChaitanyaKharya2003 , thanks for your interest; assigned the issue to you.

**Comment by AAYUSH-droid** [comment]
Hi @tejakummarikuntla i have linked pr #7502 with refactored code to fix this issue
