### ISSUE TITLE
[refactor]: Update text on the "File picker" component

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#7227]
### Overview
The description text on the "File Picker" component reads "Drag and Drop some files here, or click to select files." This text requires revision for clarity and consistency. The required description text should be: "Drag and drop files here or click to select files"

### Steps to Reproduce:
1. Search for the "File Picker" component.
2. Drag and drop the component into the canvas.
3. Notice the description text displayed on top of the component.

### Expected Behavior:
The description text on the file picker component should be: "Drag and drop files here or click to select files"

### Screenshot

<img width="630" alt="Screenshot 2023-08-09 at 1 11 34 PM" src="https://github.com/ToolJet/ToolJet/assets/34749692/d289a590-7429-40ef-be0a-89ac63eb5d46">

**Comment by Paras0750** [comment]
I would like to solve this issue, can you assign it to me?

**Comment by tejakummarikuntla** [comment]
Hey @Paras0750, I appreciate your interest in contributing to the project. Since this is labeled with `good first issue`, let's wait to welcome first-time contributors like yourself, thanks for understanding.

**Comment by AkashChikane** [comment]
I would like to contribute can you assign this issue to me ?

**Comment by tejakummarikuntla** [comment]
Hey @AkashChikane , thanks for your interest, assigned the issue to you.

**Comment by Hiperultimate** [comment]
If this issue is still ongoing can I work on it?

**Comment by AkashChikane** [comment]
@Hiperultimate I am working on the issue

**Comment by divyansshu** [comment]
is this issue solved.. or it is still open for contribution?

**Comment by Brag2gr8** [comment]
hello, I will love to work on this issue

**Comment by vishalpawarR** [comment]
Fixed! Please merge: https://github.com/ToolJet/ToolJet/pull/7369

**Comment by tejakummarikuntla** [comment]
Hey @AkashChikane, Given the duration of the assignment with no recent updates, we need to unassign the task. Your understanding and cooperation in this matter are greatly appreciated.

Assigning this to @divyansshu, progressing the PR #7292 for reviews.

**Comment by divyansshu** [comment]
> Hey @AkashChikane, Given the duration of the assignment with no recent updates, we need to unassign the task. Your understanding and cooperation in this matter are greatly appreciated.
> 
> Assigning this to @divyansshu, progressing the PR #7292 for reviews.

hii @tejakummarikuntla thank you for assigning this issue. I have already submitted PR #7292 for this issue.
