### ISSUE TITLE
Unable to modify data from an existing datasource

### ISSUE THREAD

**Issue by Mekhla-Asopa** [ToolJet/ToolJet#7230]
### What is the expected behaviour?
The existing datasource should be modified with the new data.

### What is the current behaviour?
Unable to edit existing datasource with new data

### How to reproduce the issue?
1. Login with valid credentials.
2. Navigate to the datasource page
3. Create a data source with valid credentials and click on the save button
4. Click on the created data source and update the data in it
5. Click on the save button

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/59684099/89921094-d07c-40d8-ba3b-13dac0639a8f

**Comment by DSY4444** [comment]
Hey @Mekhla-Asopa can you assign this issue to me?

**Comment by akshaysasidrn** [comment]
@DSY4444 have assigned this to you.
