### ISSUE TITLE
Workspace Settings: The icon of the "Datasources" tab shifts to an active color when it is not selected, and changes back to a non-active color when it is selected.

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7248]
### Environment
All Environments

### Description
The "All Users" section within the workspace settings provides a tabbed menu with several options: "Apps," "Users," "Permissions," and "Datasources." When you click on the "Permissions" tab, the "Datasources" tab also becomes active, and its icon changes color accordingly. Upon navigating to the "Datasources" tab, its icon reverts back to its original unselected color.

### Steps to Reproduce
1. Go to the ToolJet application.
2. From the left sidebar of icons click on the settings icon and then navigate to the Groups in the sidebar.
3. Under the heading "All Users", there is a tab menu with several options: "Apps," "Users," "Permissions," and "Datasources."
4. Navigate through the options of the tab menu and observe the change in the color of the icons in front of the options.

### Expected Output
The icon in front of the "Datasources" option present in the tab menu should only change color to active when the "Datasources" tab is selected and it should not change color on the selection of any other tab.

https://github.com/ToolJet/ToolJet/assets/85864291/727ed9d9-d452-4ece-ad4b-f86d2c1fac86

**Comment by VinayakSingh2001** [comment]
I would like to work on this, can you please assign this to me !!

**Comment by subhajit20** [comment]
@ShazanRizvi I am not able to find the exact component ... can you help me out a bit ?

**Comment by vishalbalani** [comment]
I would like to work on this issue, please assign this to me.

**Comment by subhajit20** [comment]
Hey @ShazanRizvi I found the section but there is no Datasources option available, only apps, users, permissions are there.
I think they have removed the datasources option. Not Sure

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. We assign the issue on FCFS.
Assigned the issue to @VinayakSingh2001 .

@subhajit20 , @vishalbalani kindly look into other good first issues and feel free to comment your interest.

**Comment by tejakummarikuntla** [comment]
Hey @VinayakSingh2001 , were you able to progress with the issue? Feel free to let us know if you wish to get the issue unassigned.

**Comment by tejakummarikuntla** [comment]
Hey @VinayakSingh2001 , Given the duration of the assignment with no recent updates, we need to unassign the task. Your understanding and cooperation in this matter are greatly appreciated.
