### ISSUE TITLE
[docs]: Update the Roadmap hyperlink

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#7280]
### Summary

In [ToolJet Docs](https://docs.tooljet.com/docs/), the Roadmap section in the left sidebar is hyperlinked with an outdated URL; it needs an update to the new URL: https://github.com/tooljet/tooljet/milestones

<img width="784" alt="image" src="https://github.com/ToolJet/ToolJet/assets/34749692/635f5683-5a81-4418-9a6a-fbb4589a6116">

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/

### Steps to reproduce the issue

1. Open https://docs.tooljet.com/docs/
2. Scroll to the bottom of the left sidebar
3. Notice the section "Roadmap."

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by StrixV54** [comment]
I will be working on this.

**Comment by tejakummarikuntla** [comment]
Thank you for your interest, @StrixV54, Assigned this to you!

**Comment by Prathamesh2805** [comment]
Hey @StrixV54 are you still working on it?? 
If not @tejakummarikuntla can you please assign it to me, I would love to work on it!

**Comment by tejash023** [comment]
Can I work on this @tejakummarikuntla ?

**Comment by tejakummarikuntla** [comment]
Hey!
The issue is addressed at https://github.com/ToolJet/ToolJet/pull/7283
Kindly look into the pool of other up for grabs at: https://github.com/ToolJet/ToolJet/labels/up-for-grabs
