### ISSUE TITLE
Page Handle Dialog box: The alert background color not adapting to light and dark modes

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7300]
### Environment
All Environments

### Description
The issue pertains to the "Edit Page" handle dialog box, where the alert with the text **"Changing the page handle will break any existing apps that are using this page."** functions properly in the light mode of the application. However, when transitioning to the dark mode, the background color of this alert fails to adjust accordingly. Consequently, the text, which adapts to a white color in response to the dark mode, becomes indiscernible due to the persistent white background. This inconsistency in background coloring results in reduced visibility and readability of the alert's content when the application is in dark mode.

### Steps to reproduce

1. Go to the ToolJet application and click on the **Create New App** button to create an application.
2. The application builder window is opened.
3. From the menu on the left side of the screen click on the **"Pages"** icon.
4. A menu containing all the pages of the application opens.
5. Click on the three dots icon present in front of the page name.
6. The page handle dropdown dialog box opens.
7. Click on the edit icon.
8. A new dialog box opens up with the edit page handle name.
9. now switch between light and dark modes and observe the alert in this dialog box

### Expected Outcome:

The present concern centers around the "Edit Page" handle dialog box, wherein the alert background color remains unaltered when shifting between light and dark modes. Unlike the other alert boxes within the application that seamlessly adjust to these modes, this specific alert box retains a static background color. This discrepancy leads to an issue where the text, optimized for white color in dark mode, clashes with the persistent white background, impeding readability. To ensure consistency and user-friendliness, it's imperative that the alert background color dynamically aligns with the applied mode, akin to the behavior exhibited by the rest of the alert boxes in the application.

https://github.com/ToolJet/ToolJet/assets/85864291/c9fd1b5e-6972-44ec-a346-8cfb2184c67a

**Comment by lazyfuhrer** [comment]
Hey I'd like to work on this @ShazanRizvi

**Comment by RaviTmg** [comment]
Hi @ShazanRizvi I would like to work on this as my first issue

**Comment by SWASTI-SUNDAR** [comment]
hey @ShazanRizvi I want to contribute in this issue

**Comment by tejakummarikuntla** [comment]
Thank you for your interest in contributing to the project, we assign issues on FCFS.
Since @SshibamDebnathh's message was unclear. Assigned the issue to @lazyfuhrer

**Comment by tejakummarikuntla** [comment]
Hey @lazyfuhrer , Given the duration of the assignment with no recent updates, we need to unassign the task. Your understanding and cooperation in this matter are greatly appreciated.

**Comment by shubhjhawar** [comment]
is this issue not assigned to anyone right now?
would love to work on it

**Comment by tejakummarikuntla** [comment]
Thank you for your interest, @shubhjhawar , Assigned the issue to you.

**Comment by tejakummarikuntla** [comment]
Hey @shubhjhawar , thanks for bringing this up; I've checked with the internal teams and learned that it was fixed as a part of the previous releases. I'm very sorry about this. I'd like to ask you to look into other https://github.com/ToolJet/ToolJet/labels/up-for-grabs to comment on your interest.
I look forward to your continuous involvement in the project.
