### ISSUE TITLE
Share Modal: Close icon not adapting to dark mode

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7315]
### Environment
All Environments

### Description:
When you click the "Share" button in the top bar of the app editor, a modal opens up, presenting sharing options and details. To close this dialog box, there's a close icon positioned in the upper right corner. While the icon appears appropriate in the light mode, it fails to adjust accordingly in the dark mode. Consequently, its visibility is compromised, making it challenging to discern within the dark mode setting.

### Steps to Reproduce:

1. Go to the ToolJet application and click on the Create New App button to create an application.
2. The application builder window is opened.
3. Click on the share icon in the topbar of the app builder a new share modal opens.
4. Turn on the dark mode of the application by using the light mode/ dark mode toggle icon.
5. Observe the close icon on the share modal opened when in dark mode.

### Expected output:
The close icon within the modal should be adaptable to the dark mode for enhanced visibility and clarity. Currently, the icon remains unchanged, leading to reduced visibility and difficulty in discerning it against the dark background. To ensure optimal user experience, it's important for the close icon's appearance to adjust seamlessly in accordance with the dark mode settings, facilitating easy recognition and usability in various viewing conditions.

Reproduction video:

https://github.com/ToolJet/ToolJet/assets/85864291/7a3d89ac-f526-47e0-971d-e826a57b5431

Close icon not visible:
<img width="711" alt="Screenshot 2023-08-23 at 3 22 45 AM" src="https://github.com/ToolJet/ToolJet/assets/85864291/e0761f0f-f974-4379-b6d4-37bd82351e8f">

Close Icon is visible:
<img width="720" alt="Screenshot 2023-08-22 at 10 14 19 PM" src="https://github.com/ToolJet/ToolJet/assets/85864291/c2543afb-98c5-477e-af9e-93044f305266">

**Comment by Lovepreet013** [comment]
I would like to take this issue.

**Comment by subhajit20** [comment]
Made a pr regarding this issue https://github.com/ToolJet/ToolJet/pull/7330

**Comment by SWASTI-SUNDAR** [comment]
I want to contribute in this issue can you assign this issue to me

**Comment by tejakummarikuntla** [comment]
Thank you for your interest in contributing to the project, we assign issues on FCFS.
Assigned the issue to @Lovepreet013

**Comment by Lovepreet013** [comment]
sorry, but you can assign this issue to someone else.

**Comment by rahulrangers** [comment]
I want to take up this issue

**Comment by sudip57** [comment]
I would like to contribute to this issue @tejakummarikuntla

**Comment by yetea** [comment]
I'd like to work on this issue

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by tejakummarikuntla** [comment]
We want to express our sincere appreciation for your interest and involvement in this issue. Regrettably, we have decided to address this internally for specific reasons. We apologize for any inconvenience and greatly appreciate your understanding.
