### ISSUE TITLE
Share Modal: Unusual background color of "Get embeddable link for this application" section in dark mode

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7328]
### Environment
All environments

### Description:
Upon clicking the "Share" button in the app editor's top bar, a modal window appears, offering sharing options and details. This modal also provides the choice to obtain an embedded link for the application. While the application is in light mode, the field background appears as intended. However, upon switching to dark mode, the background color of the link field transforms into an unusual shade of grey.

### Steps to Reproduce:

1. Go to the ToolJet application and click on the Create New App button to create an application.
2. The application builder window is opened.
3. Add a component on the canvas by dragging and dropping from the component library.
4. Click on the share icon at the topbar of the app builder a new share modal opens.
5. Turn on the dark mode of the application by using the light mode/ dark mode toggle icon.
6. Observe the color of the background of the **Get embeddable link for this application** section in dark mode.

### Expected output:

The background color of the **Get embeddable link for this application** section should match the background color of other input fields or areas within the application, maintaining visual consistency.

Reproduction video:

https://github.com/ToolJet/ToolJet/assets/85864291/1e542401-8e75-47e2-9e09-7e748e6e5026

Unusual grey background:
<img width="699" alt="Screenshot 2023-08-24 at 2 57 29 PM" src="https://github.com/ToolJet/ToolJet/assets/85864291/abf54413-146b-4ab4-8067-5b3237c2fce0">

**Comment by joypoddar** [comment]
Hi,

I would like to give it a try. Kindly assign it to me.

**Comment by subhajit20** [comment]
@ShazanRizvi  made a pr of this issue https://github.com/ToolJet/ToolJet/pull/7332

**Comment by tejakummarikuntla** [comment]
Hello @subhajit20 ,
I would like to kindly request you to review the [contributor guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md) and ensure that you raise pull requests (PRs) for the issues assigned specifically to you. Since there's already an issue assigned to you, I encourage you to explore up-for-grabs labeled issues, and please comment on your interest in assigning. Thank you for your understanding, and I look forward to your continued involvement in the project.

Assigned the issue to @joypoddar

**Comment by joypoddar** [comment]
@tejakummarikuntla Thank you. I am on it.

**Comment by tejakummarikuntla** [comment]
Hey @joypoddar, were you able to work on the issue? let us know if we can help you with anything or feel free to get this unassinged for others. Thanks for your understanding.

**Comment by joypoddar** [comment]
> Hey @joypoddar, were you able to work on the issue? let us know if we can help you with anything or feel free to get this unassinged for others. Thanks for your understanding.

Hey @tejakummarikuntla, I understand the point you are making. The task I have looks easy. I am sure I will be able to do it. I am facing a problem with setting up the project locally. I have asked for help in the slack channel. Haven't been able to get any solution till now.

It would be really nice if you could tell someone to help me out at the earliest.


Thank you.

**Comment by tejakummarikuntla** [comment]
@adishM98 could be able to help you with the set-up issues @joypoddar

**Comment by joypoddar** [comment]
@tejakummarikuntla I am unassigning myself as I am still struggling to set up the project in local env. Even though I know how to solve the issue, it's unfair to hold an organization at ransom for a problem I am facing. 

I love the community and will get back later once I have been able to install the repo correctly.

**Comment by ValkonX33** [comment]
hey i would i like to work on this

**Comment by ValkonX33** [comment]
@joypoddar  hey can you also guide me how to setup project locally would really appreciate it

**Comment by tejakummarikuntla** [comment]
Thank you @joypoddar, I look forward to your continuous involvement in the project.

@ValkonX33 , thanks for your interest, let's wait to welcome other first-time contributors like yourself to the project, thanks for understanding.

**Comment by joypoddar** [comment]
> Thank you @joypoddar, I look forward to your continuous involvement in the project.
> 
> @ValkonX33 , thanks for your interest, let's wait to welcome other first-time contributors like yourself to the project, thanks for understanding.

@ValkonX33 i wish I could. But unfortunately I haven't yet been able to get the project setup. If you do, I would like to take your assistance.

**Comment by ValkonX33** [comment]
@joypoddar did you try to set it up on gitpod?

**Comment by joypoddar** [comment]
> @joypoddar did you try to set it up on gitpod? 
> 

No

**Comment by ValkonX33** [comment]
> > @joypoddar did you try to set it up on gitpod?
> 
> No

well they haven't provided core details about setting up the project locally and actually running it on local server 
so ig we can't do aything about it then

**Comment by joypoddar** [comment]
> > > @joypoddar did you try to set it up on gitpod?
> > 
> > 
> > No
> 
> well they haven't provided core details about setting up the project locally and actually running it on local server so ig we can't do aything about it then

I did take the help of the slack community but was still getting errors.

**Comment by subhajit20** [comment]
@joypoddar Hey can I work on this?

**Comment by tejakummarikuntla** [comment]
Hey @subhajit20, thanks for your interest, let's wait to welcome other first time contributors like yourself to the project. Looking forward for you contentious participation.
