### ISSUE TITLE
For installed plugins, the card size different

### ISSUE THREAD

**Issue by Mekhla-Asopa** [ToolJet/ToolJet#7344]
### What is the expected behaviour?
The card size of the plugins should be the same.

### What is the current behaviour?
The card sizes of the plugins are different.

### How to reproduce the issue?

1. Login with valid credentials 
2. Navigate to the marketplace icon 
3. Click on the required plugin to install
4. Navigate to the Installed section and check for the installed plugins

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2023-08-29 at 1 29 14 PM" src="https://github.com/ToolJet/ToolJet/assets/59684099/b594a41b-96a6-4570-904c-40b87df46b0e">

**Comment by Sranjan0208** [comment]
Can I  work on this issue?
