### ISSUE TITLE
Error page when an app link is unreachable

### ISSUE THREAD

**Issue by thehacklady** [ToolJet/ToolJet#7392]
User Story:
"As a user, I want to be informed and guided when I cannot access an app due to network errors or server-related issues, so I can take appropriate actions."

Acceptance Criteria:

1. When the app URL is not reachable due to network errors or server-related issues, the system should display an error page with the following content:
   
   - Title:Oops, something went wrong!
   - Helper Text: An error occurred while loading the app. Please try again or contact the admin.

2. The error page should provide two Call-to-Action (CTA) buttons:
   - A CTA to allow the user to reload the page.
   - A CTA to enable the user to return to the home page or dashboard.

By implementing this, the user will have a clear understanding of the issue and the necessary actions to take when facing connectivity problems with the app.

Deisgn - 
<img width="872" alt="Screenshot 2023-09-18 at 1 41 23 PM" src="https://github.com/ToolJet/ToolJet/assets/32910986/3be9dbd2-ec69-4cb2-84c7-07b0549e58c5">

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by tejakummarikuntla** [comment]
Thanks for your interest @Sranjan0208 , would you like to get this assigned to you?

**Comment by Sranjan0208** [comment]
Yes.. Thank You

**Comment by vedant-z** [comment]
@thehacklady @tejakummarikuntla May I also work on this?

**Comment by thehacklady** [comment]
duplicate, closing.
