### ISSUE TITLE
Data Source name consistency to be added

### ISSUE THREAD

**Issue by thehacklady** [ToolJet/ToolJet#7404]
1. Need to update Data sources name to 'Data Sources' for these screens : 
<img width="1380" alt="Screenshot 2023-09-09 at 1 30 38 AM" src="https://github.com/ToolJet/ToolJet/assets/32910986/a950799a-75b9-45b6-8d87-45b3ac5950c4">

<img width="546" alt="Screenshot 2023-09-09 at 1 28 58 AM" src="https://github.com/ToolJet/ToolJet/assets/32910986/cfa95e04-617f-4337-b50d-8ac3f1a7a2d8">

2. Global data sources ---> Data Sources
<img width="1118" alt="Screenshot 2023-09-09 at 1 24 51 AM" src="https://github.com/ToolJet/ToolJet/assets/32910986/754a5626-8cb4-466f-91c8-8624d9a67943">

3. Available data sources ---> Available Data Sources
<img width="1157" alt="Screenshot 2023-09-09 at 1 27 26 AM" src="https://github.com/ToolJet/ToolJet/assets/32910986/59ee034b-3175-4c56-9e32-7d420676a80e">

**Comment by ValkonX33** [comment]
Hey i would like to work on this

**Comment by mrkirthi-24** [comment]
@thehacklady Please can you assign this task to me?
