### ISSUE TITLE
[docs]: Workflow overview

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7406]
### Summary

**NEEDS TO BE CHANGED IN ALL VERSIONS OF DOCUMENTATION**
It appears there may be a spelling error in the overview documentation for workflows in the SMS example, specifically in the usage of the word "identifier." 

<img width="825" alt="Screenshot 2023-09-10 at 2 21 34 PM" src="https://github.com/ToolJet/ToolJet/assets/85864291/c7710148-4469-46ea-b716-7559cd2f19dd">

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/workflows/overview/

### Steps to reproduce the issue

1. Open the URL mentioned in the URL section of this issue.
2. Scroll down to the section with the text  **"Click on the sendSMS node and look at the Results. Under the data property, we can see an error message indentifier. The errorMessage will be null for the messages that are successfully sent to the intended number."**
3. Check for the spelling of identifier

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by mrkirthi-24** [comment]
Hey @ShazanRizvi I would like to work on this issue. Can you please assign it to me?

**Comment by mrkirthi-24** [comment]
Updated docs in all versions #7407

**Comment by tejakummarikuntla** [comment]
Hey @mrkirthi-24 thank you for your contribution, I'd kindly request you to follow our contribution guidelines and be sure to comment on your interest to get the issue assigned before raising the PRs. 

Assigned the issue to you!
