### ISSUE TITLE
[refactor]: Update plugin descriptions on the Marketplace page 

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7417]
### Overview
The plugin labels on the Marketplace page need refactoring. 

### Steps to reproduce
1. Navigate to the Marketplace page.
2. Click on the Marketplace tab under PLUGINS.
3. You'll find a list of plugins with incorrect descriptions and two incorrectly capitalized names (Openai and Github).

![image](https://github.com/ToolJet/ToolJet/assets/58169101/5f547357-deab-46ac-b694-c6ba8ae802e9)

### Expected behaviour 

1. Change the descriptions of the plugins based on the below table:

| Name         | Description                  |  Replacement Description                 |
|:-----------|:----------------------|:--------------------------|
| Plivo        | Datasource plugin for Plivo  | Plugin for Plivo APIs                   |
| Github       | Datasource plugin for GitHub | Plugin for GitHub APIs           |
| Openai       | API plugin from OpenAI       | Plugin for OpenAI APIs            |
| AWS Textract | Datasource plugin from Textract | Plugin for AWS Textract machine-learning service |
| Harper DB    | Datasource plugin for HarperDB | Plugin for HarperDB data source        |

2. Change the name of the `Openai` plugin to `OpenAI` and `Github` plugin to `GitHub`.

**Comment by ValkonX33** [comment]
Hey can i work on this?

**Comment by ValkonX33** [comment]
hey thanks for that, i have a problem i am not able to start the development server would you mind assisting me ?

**Comment by karan-rathod-316** [comment]
@ValkonX33 Sure Sumukh, let me take a look.

**Comment by ValkonX33** [comment]
hey, sorry my bad, can you check it again please, thank you.

**Comment by karan-rathod-316** [comment]
@ValkonX33 Hi Sumukh, Thanks for the swift response. I can see the latest changes. This is in review.
