### ISSUE TITLE
[docs]: Environment variables

### ISSUE THREAD

**Issue by mrkirthi-24** [ToolJet/ToolJet#7430]
### Summary

NEEDS TO BE CHANGED IN ALL VERSIONS OF DOCUMENTATION
It appears that there is a grammatical mistake in the Environment variables documentation for setup. The text is not clear.

![Screenshot 2023-09-13 at 4 40 31 PM](https://github.com/ToolJet/ToolJet/assets/53830546/c329cca5-ae20-451d-9b3f-874b6a606614)

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/setup/env-vars/

### Steps to reproduce the issue

1. Open the URL mentioned in the URL section of this issue.
2. Scroll down to the section with the text "If you intent you use the DB connection url and if the connection does not support ssl. Please use the below format using the variable DATABASE_URL. postgres://username:password@hostname:port/database_name?sslmode=disable".
3. Read the sentence. I think it doesn't makes sense. 

### Additional Information

Actual text should be: "If you intend to use the DB connection URL and the connection does not support SSL, please use the following format using the variable DATABASE_URL: postgres://username:password@hostname:port/database_name?sslmode=disable."

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by RISHIKESHk07** [comment]
Hey there , i would like to contribute to this issue

**Comment by tejakummarikuntla** [comment]
Thanks for sharing @mrkirthi-24 , 
@withshubh could be able to help in reviewing the issue.

**Comment by tejakummarikuntla** [comment]
Liking the PR #7337
