### ISSUE TITLE
[docs]: 

### ISSUE THREAD

**Issue by dkshitij29** [ToolJet/ToolJet#7454]
### Summary

I was installing tool jet locally on macOS with your [guide](https://docs.tooljet.com/docs/contributing-guide/setup/macos).  The postgresQL formula has been updated to postgresql@14. 

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/contributing-guide/setup/macos

### Steps to reproduce the issue

<img width="1365" alt="image" src="https://github.com/ToolJet/ToolJet/assets/111069156/efa944d0-8abe-414e-828f-7e8b4e17d735">

**This document has brew formula as "brew install postgresql", but the when i tpped the brew/core did get this prompt "Warning: Formula postgresql was renamed to postgresql@14."**

<img width="832" alt="image" src="https://github.com/ToolJet/ToolJet/assets/111069156/f3534fff-a7b1-44cc-ae71-3b621d9118f7">

### Additional Information

Requesting to update the website documentation guide to the updated commands.

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [ ] I agree to follow the ToolJet Code of Conduct

**Comment by omkarvilasmote** [comment]
Can you assign me this task i will check and fix it 🙏.

**Comment by dkshitij29** [comment]
Can you guide me on how to assign the issue, and how are you going to work on the main website/ how are you going to update the webpage?

**Comment by ChinmayAlekar** [comment]
Hey @dkshitij29, can you please assign me this issue

**Comment by withshubh** [comment]
@adishM98 Please help me verify it's a valid issue.

**Comment by dkshitij29** [comment]
Hey @withshubh. 
The brew formula for Postgres SQL has been renamed to brew reinstall postgresql@14. I had to refresh my core and install it. It's a new thing from the brew team.
<img width="842" alt="Screenshot 2023-10-07 at 5 04 49 PM" src="https://github.com/ToolJet/ToolJet/assets/111069156/2c2f9743-0a57-486e-ad2a-e5a6bc8939c8">

**Comment by dkshitij29** [comment]
Hey @adishM98 any update on verifying the issue.

**Comment by adishM98** [comment]
Hi @dkshitij29, 

Postgres version 13 or 14 is recommended version to used. But will into the issue mention the docs in using a particular version.
