### ISSUE TITLE
Dark mode issue for edit icon in groups.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#7461]
### Environment

    ToolJet Cloud / Docker / Linux / MacOS ...

### What is the expected behaviour?
Edit icon should be compatible for dark mode in groups.

### What is the current behaviour?
Edit icon is not compatible for dark mode in groups.

### How to reproduce the issue?

1. Login to ToolJet
2. Click on workspace settings.
3. Go to users page.
4. Turn on the dark mode & observe

https://github.com/ToolJet/ToolJet/assets/41302917/8224c38a-80e1-4fe7-88c6-8f09a8611df7

**Comment by subhajit20** [comment]
@Nandinisaha13 Hey! want to help.
Could you assign it to me?

**Comment by Sagar-Pant-2k2** [comment]
Mam i've tried to resolve this issue
please review it
