### ISSUE TITLE
Improving importing app flow

### ISSUE THREAD

**Issue by thehacklady** [ToolJet/ToolJet#7470]
Current flow : User clicks on import app > selects the app > imported, taken to app editor (in case of duplicate name, timestamp will be appended)
New ideal flow : User clicks on import app > selects the app > dialog box appears to rename in case of duplicate name (rather than having timestamp appended)  > imported, taken to app editor.

**Comment by mrkirthi-24** [comment]
@thehacklady I would like to work on this issue.
