### ISSUE TITLE
 SVG Errors in DevTools When Uploading a Table in New Project

### ISSUE THREAD

**Issue by KrzysPi** [ToolJet/ToolJet#7480]
### Version Information
- **ToolJet Version**: v2.17.4

### Environment

    ToolJet Docker

### What is the expected behavior?

   I want to be able to add a table in ToolJet without encountering SVG-related errors in the browser's DevTools console. Specifically, I expect that adding a table should not generate any errors.

### What is the current behavior?

  Upon attempting to upload a table in a new project in ToolJet, I encountered SVG-related errors in the browser's DevTools console:

  1. **Error 1**:
     ```
     Error: <svg> attribute width: Expected length, "auto".
     ```

  2. **Error 2**:
     ```
     Error: <svg> attribute height: Expected length, "auto".
     ```

  When attempting to upload a table in ToolJet, SVG-related errors occur. In one of my applications, these errors appear to be generated in a loop, leading to the application becoming unresponsive. This occurs in more complex applications with multiple tables.

### How to reproduce the issue?

1. Create a new project in ToolJet.
2. Attempt to upload a table.
3. Open the browser's DevTools console, where you will observe the mentioned SVG errors.

### Screenshots or Screencast

![image](https://github.com/ToolJet/ToolJet/assets/84018429/7602d026-3f89-4ee9-bb23-87a63ec27e97)

### Can you identify the location in the driver source code where the problem exists?

 No

### If the bug is confirmed, would you be willing to submit a PR?

Not now

**Comment by Dvinod1** [comment]
Can i work on this issue? but i am using tooljet in wsl.

**Comment by Lovish141** [comment]
If Somebody is not working on this issue,Can you assign me this issue.

**Comment by shubh22** [comment]
This is fixed.
