### ISSUE TITLE
Security email is invalid

### ISSUE THREAD

**Issue by coderbm1** [ToolJet/ToolJet#7504]
Hi

Email address provided here https://github.com/ToolJet/ToolJet/security "security@tooljet.com" is invalid.
Gmail shows message from <mailer-daemon@googlemail.com> and error 550

Kind regards

**Comment by thats-sarthak** [comment]
Can you please assign me this issue

**Comment by coderbm1** [comment]
If I'm not mistaken it's already fixed, is it?

**Comment by thehacklady** [comment]
The issue is fixed.
