### ISSUE TITLE
[refactor]: Update descriptions(tooltips) for checkbox, radio button, toggle switch and textarea components

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7518]
### Summary
Descriptions(tooltips) for components need to be updated.

### How to reproduce the issue?

1. Open the ToolJet App-Builder
2. Hover over the components in the Components library on the right
3. You can see descriptions(tooltips) for each component on hover

### Screenshots 

Table component description(tooltip) example:

<img width="958" alt="table-en" src="https://github.com/ToolJet/ToolJet/assets/58169101/e80aa917-6ef0-4dd0-a0c6-ea895d494aba">

<img width="840" alt="table-widget-config" src="https://github.com/ToolJet/ToolJet/assets/58169101/ace5382a-b17b-413b-8114-a7fdd2d50629">

![image](https://github.com/ToolJet/ToolJet/assets/58169101/4f28eb6f-585d-424d-9c84-4ac4ece23f84)

### Any possible solutions?

Replace the current labels in the `widgetConfig.js` and `en.json` files according to the below table.

| Name             | Current Description                  | New Description       |
|:-----------------|:---------------------------------|:----------------------|
| Checkbox         | A single checkbox                | Single checkbox toggle|
| Radio Button     | Radio buttons                    | Select one from multiple choices|
| Toggle Switch    | Toggle Switch                    | User-controlled on-off switch         |
| Textarea         | Text area form field             | Multi-line text input |

### If the bug is confirmed, would you be willing to submit a PR?
No

### Code of Conduct

- [ ] I agree to follow the [ToolJet Code of Conduct](https://docs.tooljet.com/docs/contributing-guide/code-of-conduct)

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by SAHIL250499** [comment]
Hi @karan-rathod-316 , can I work on this .

**Comment by karan-rathod-316** [comment]
> Hi @karan-rathod-316 , can I work on this .

Hi @SAHIL250499,

Thank you so much for your interest in contributing to ToolJet. Assigning the issue to you.

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by NEMYSESx** [comment]
hey @karan-rathod-316 . I'm new to open source and this issue seems perfect for me can I contribute to it

**Comment by Omsoni06** [comment]
HI @karan-rathod-316 I am taking initiative to solve this issue
