### ISSUE TITLE
[refactor]: Update descriptions(tooltips) for QR scanner, rating, divider and file picker components

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7521]
### Summary
Descriptions(tooltips) for components need to be updated.

### How to reproduce the issue?

1. Open the ToolJet App-Builder
2. Hover over the components in the Components library on the right
3. You can see descriptions(tooltips) for each component on hover

### Screenshots 

Table component description(tooltip) example:

<img width="958" alt="table-en" src="https://github.com/ToolJet/ToolJet/assets/58169101/e80aa917-6ef0-4dd0-a0c6-ea895d494aba">

<img width="840" alt="table-widget-config" src="https://github.com/ToolJet/ToolJet/assets/58169101/ace5382a-b17b-413b-8114-a7fdd2d50629">

![image](https://github.com/ToolJet/ToolJet/assets/58169101/4f28eb6f-585d-424d-9c84-4ac4ece23f84)

### Any possible solutions?

Replace the current labels in the `widgetConfig.js` and `en.json` files according to the below table.

| Name             | Current Description                  | New Description       |
|:-----------------|:---------------------------------|:----------------------|
| QR Scanner       | Scan QR codes and hold its data  | Scan and store QR codes          |
| Rating           | Star rating                      | User star rating            |
| Divider          | Separator between components     | Separate UI elements         |
| File Picker      | File Picker                      | Choose files from device         |

### If the bug is confirmed, would you be willing to submit a PR?
No

### Code of Conduct

- [ ] I agree to follow the [ToolJet Code of Conduct](https://docs.tooljet.com/docs/contributing-guide/code-of-conduct)

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by zainbinfurqan** [comment]
@karan-rathod-316 Can i work on it please.

**Comment by karan-rathod-316** [comment]
Hi @zainbinfurqan, we really appreciate your interest.

As this issue is tagged as a `good-first-issue`, we'd like to give first-time contributors a chance to tackle it. Please feel free to monitor other issues that may pique your interest. Thank you for your time and consideration.

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
Please assign it to me.

**Comment by DarrenDsouza7273** [comment]
Can i work on this issue @karan-rathod-316

**Comment by karan-rathod-316** [comment]
@DarrenDsouza7273 Hi Darren, 

Thank you so much for your interest in contributing to ToolJet. 

Assigning the issue to you. We welcome you to join our ToolJet developer community on [Slack](https://tooljet.com/slack). For any assistance related to issues/contributions, please post in the #contributors channel.

**Comment by Ar-Akhil** [comment]
Is it available for grabs.?
thank you

**Comment by SujalGupta244** [comment]
May you please assign this issue to me ?

**Comment by suiisharma** [comment]
Hello @karan-rathod-316 ,

I am interested in contributing to this issue.
Can you assign it to me ?

**Comment by ShivamJha2436** [comment]
Please assigne this issue to me.

**Comment by ShivamJha2436** [comment]
Please assigne this issue to me.

**Comment by tejakummarikuntla** [comment]
Hey @ShivamJha2436, thank you for your interest. Assigned the issue to you.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

Could you close all the other PRs raised to the issues not assigned to you?

**Comment by ShivamJha2436** [comment]
Ok sure i will close all other PR's. Please Merge this issue.

**Comment by tejakummarikuntla** [comment]
Hey @ShivamJha2436, if you've raised the PR addressing this issue, could you please link it here?

**Comment by tejakummarikuntla** [comment]
@ShivamJha2436 had raised two PRs addressing the issue in parts.
Linking #7988 #7911

**Comment by tejakummarikuntla** [comment]
Unassigning @ShivamJha2436 due to inactivity.

**Comment by ShubhamSharma2003** [comment]
can i also work in this @tejakummarikuntla

**Comment by ilyakokotkin** [comment]
@tejakummarikuntla happy to pick this up :)

**Comment by karan-rathod-316** [comment]
Closed in other PRs.
