### ISSUE TITLE
[refactor]: Update descriptions(tooltips) for timer, list view, tags and pagination components

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7523]
### Summary
Descriptions(tooltips) for components need to be updated.

### How to reproduce the issue?

1. Open the ToolJet App-Builder
2. Hover over the components in the Components library on the right
3. You can see descriptions(tooltips) for each component on hover

### Screenshots 

Table component description(tooltip) example:

<img width="958" alt="table-en" src="https://github.com/ToolJet/ToolJet/assets/58169101/e80aa917-6ef0-4dd0-a0c6-ea895d494aba">

<img width="840" alt="table-widget-config" src="https://github.com/ToolJet/ToolJet/assets/58169101/ace5382a-b17b-413b-8114-a7fdd2d50629">

![image](https://github.com/ToolJet/ToolJet/assets/58169101/4f28eb6f-585d-424d-9c84-4ac4ece23f84)

### Any possible solutions?

Replace the current labels in the `widgetConfig.js` and `en.json` files according to the below table.

| Name             | Current Description                  | New Description       |
|:-----------------|:---------------------------------|:----------------------|
| Timer            | Timer                            | Countdown or stopwatch      |
| List View        | Wrapper for multiple components  | List multiple items   |
| Tags             | Content can be shown as tags     | Display tag labels           |
| Pagination       | Pagination                       | Navigate pages           |

### If the bug is confirmed, would you be willing to submit a PR?
No

### Code of Conduct

- [ ] I agree to follow the [ToolJet Code of Conduct](https://docs.tooljet.com/docs/contributing-guide/code-of-conduct)

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by nayangoyal** [comment]
Hi, @karan-rathod-316 can you assign this issue to me? I am new to open source and I want to solve this issue.

**Comment by karan-rathod-316** [comment]
Hi @nayangoyal, Thank you so much for your interest in contributing to ToolJet. Assigning the issue to you.
To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by weedertree** [comment]
hey, @karan-rathod-316 could you assign me this issue, i'd like to work upon it :)

**Comment by suiisharma** [comment]
Hello @karan-rathod-316 ,

I am interested in contributing to this issue.
Can you assign it to me ?
