### ISSUE TITLE
[refactor]: Update descriptions(tooltips) for circular progressbar, spinner, statistics and range slider components

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7524]
### Summary
Descriptions(tooltips) for components need to be updated.

### How to reproduce the issue?

1. Open the ToolJet App-Builder
2. Hover over the components in the Components library on the right
3. You can see descriptions(tooltips) for each component on hover

### Screenshots 

Table component description(tooltip) example:

<img width="958" alt="table-en" src="https://github.com/ToolJet/ToolJet/assets/58169101/e80aa917-6ef0-4dd0-a0c6-ea895d494aba">

<img width="840" alt="table-widget-config" src="https://github.com/ToolJet/ToolJet/assets/58169101/ace5382a-b17b-413b-8114-a7fdd2d50629">

![image](https://github.com/ToolJet/ToolJet/assets/58169101/4f28eb6f-585d-424d-9c84-4ac4ece23f84)

### Any possible solutions?

Replace the current labels in the `widgetConfig.js` and `en.json` files according to the below table.

| Name             | Current Description                  | New Description       |
|:-----------------|:---------------------------------|:----------------------|
| Circular Progressbar | Show the progress using circular progressbar | Show circular progress  |
| Spinner          | Spinner can be used to display loading status | Indicate loading state         |
| Statistics       | Statistics can be used to display different statistical information | Show key metrics          |
| Range Slider     | Can be used to show slider with a range | Adjust value range          |

### If the bug is confirmed, would you be willing to submit a PR?
No

### Code of Conduct

- [ ] I agree to follow the [ToolJet Code of Conduct](https://docs.tooljet.com/docs/contributing-guide/code-of-conduct)

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by naveen8801** [comment]
Hey @karan-rathod-316, can I pick this up?

**Comment by karan-rathod-316** [comment]
> Hey @karan-rathod-316, can I pick this up?

Hi @naveen8801,

Thank you so much for your interest in contributing to ToolJet. Assigning the issue to you. To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by vibh1103** [comment]
Hi @karan-rathod-316  can i fix this ?

**Comment by tejakummarikuntla** [comment]
Hey @vibh1103 , since there's already an issue assigned to you, let's wait to welcome other first-time contributors like yourself to the project! Thanks for your understanding.

**Comment by chaitanya005** [comment]
Hey @tejakummarikuntla, can I take up this issue?

**Comment by tejakummarikuntla** [comment]
Thanks for your interest @chaitanya005 , assigned the issue to you.
To seek assistance or resolve issues, join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by 0amirk** [comment]
@tejakummarikuntla What's the status of this issue? If no ones actively working on this can I ?

**Comment by Tushar040903** [comment]
pls assign me this issue.

**Comment by tejakummarikuntla** [comment]
Hey @chaitanya005 , were you able to progress with the issue? Kindly let us know if you need any help.
In case if you'd be unable to take it up, kindly let us know to unassign, there are existing PRs we could consider.

**Comment by suiisharma** [comment]
Hello @karan-rathod-316 ,

I am interested in contributing to this issue.
Can you assign it to me ?

**Comment by Bajpai25** [comment]
Hello  @karan-rathod-316 
Could you assign this issue to me.

**Comment by chaitanya005** [comment]
Hello @tejakummarikuntla, I'm not able to take this up right now. Please unassign me

**Comment by tejakummarikuntla** [comment]
Thank you @chaitanya005 , 

Hey @Bajpai25, thanks for your interest. Assigned the issue to you.

**Comment by Sachin24704** [comment]
@tejakummarikuntla , Hi I have raised a PR, please check and merge. Thankyou

**Comment by Bajpai25** [comment]
Hii, @tejakummarikuntla I have created the pull request kindly review it and feel free to contact me if it requires any edits. Thank you.
Here is the PR Link : https://github.com/ToolJet/ToolJet/pull/7593

**Comment by Bajpai25** [comment]
Hii @karan-rathod-316 any updates on the PR . Do let me know .
Thank you.
