### ISSUE TITLE
[refactor]: Update descriptions(tooltips) for timeline, svg image, html viewer and vertical divider components

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7525]
### Summary
Descriptions(tooltips) for components need to be updated.

### How to reproduce the issue?

1. Open the ToolJet App-Builder
2. Hover over the components in the Components library on the right
3. You can see descriptions(tooltips) for each component on hover

### Screenshots 

Table component description(tooltip) example:

<img width="958" alt="table-en" src="https://github.com/ToolJet/ToolJet/assets/58169101/e80aa917-6ef0-4dd0-a0c6-ea895d494aba">

<img width="840" alt="table-widget-config" src="https://github.com/ToolJet/ToolJet/assets/58169101/ace5382a-b17b-413b-8114-a7fdd2d50629">

![image](https://github.com/ToolJet/ToolJet/assets/58169101/4f28eb6f-585d-424d-9c84-4ac4ece23f84)

### Any possible solutions?

Replace the current labels in the `widgetConfig.js` and `en.json` files according to the below table.

| Name             | Current Description                  | New Description       |
|:-----------------|:---------------------------------|:----------------------|
| Timeline         | Visual representation of a sequence of events | Show event timeline      |
| Svg Image        | Svg image                        | Display SVG graphics             |
| HTML Viewer      | HTML Viewer                      | View HTML content                |
| Vertical Divider | Vertical Separator between components | Vertical line separator     |

### If the bug is confirmed, would you be willing to submit a PR?
No

### Code of Conduct

- [ ] I agree to follow the [ToolJet Code of Conduct](https://docs.tooljet.com/docs/contributing-guide/code-of-conduct)

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by zainbinfurqan** [comment]
HI @karan-rathod-316  Can i work on this issue please.

**Comment by Damon248** [comment]
hello @karan-rathod-316! Can I work on this issue?

**Comment by karan-rathod-316** [comment]
Hi @Damon248,

Thank you so much for your interest in contributing to ToolJet. Assigning the issue to you. To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by karan-rathod-316** [comment]
> HI @karan-rathod-316 Can i work on this issue please.

Hi @zainbinfurqan, we really appreciate your interest.

As this issue is tagged as a `good-first-issue`, we'd like to give first-time contributors a chance to tackle it. Please feel free to monitor other issues that may pique your interest. Thank you for your time and consideration.

**Comment by suiisharma** [comment]
Hello @karan-rathod-316 ,

I am interested in contributing to this issue.
Can you assign it to me ?

**Comment by bhaweshchoudhary19** [comment]
Greetings  Karan ! May I contribute to this issue ? It would be great if somehow I'll be able to fix this .

**Comment by tejakummarikuntla** [comment]
Unassigning @Damon248 due to inactivity.
@jobayer12, would you like to get this assigned?

**Comment by jobayer12** [comment]
@tejakummarikuntla Yes, Assign me

**Comment by tejakummarikuntla** [comment]
Hey @jobayer12, thank you for your interest. Assigned the issue to you.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
