### ISSUE TITLE
[refactor]: Update descriptions(tooltips) for custom component, button group, pdf and steps components

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7526]
### Summary
Descriptions(tooltips) for components need to be updated.

### How to reproduce the issue?

1. Open the ToolJet App-Builder
2. Hover over the components in the Components library on the right
3. You can see descriptions(tooltips) for each component on hover

### Screenshots 

Table component description(tooltip) example:

<img width="958" alt="table-en" src="https://github.com/ToolJet/ToolJet/assets/58169101/e80aa917-6ef0-4dd0-a0c6-ea895d494aba">

<img width="840" alt="table-widget-config" src="https://github.com/ToolJet/ToolJet/assets/58169101/ace5382a-b17b-413b-8114-a7fdd2d50629">

![image](https://github.com/ToolJet/ToolJet/assets/58169101/4f28eb6f-585d-424d-9c84-4ac4ece23f84)

### Any possible solutions?

Replace the current labels in the `widgetConfig.js` and `en.json` files according to the below table.

| Name             | Current Description                  | New Description       |
|:-----------------|:---------------------------------|:----------------------|
| Custom Component | Add your custom react component  | Create React components    |
| Button Group     | ButtonGroup                      | Group of buttons         |
| PDF              | Embed PDF file                   | Embed PDF documents            |
| Steps            | Steps                            | Step-by-step navigation aid    |

### If the bug is confirmed, would you be willing to submit a PR?
No

### Code of Conduct

- [ ] I agree to follow the [ToolJet Code of Conduct](https://docs.tooljet.com/docs/contributing-guide/code-of-conduct)

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by vibh1103** [comment]
Hi @karan-rathod-316  
can i work on this task ?

**Comment by AbhishekSinghDev** [comment]
hello @karan-rathod-316 I would like to work on this issue can you please assign me.

**Comment by Damon248** [comment]
Hello there @karan-rathod-316, I would be really happy to work on this issue. Can you please assign me this one?

**Comment by karan-rathod-316** [comment]
> Hello there @karan-rathod-316, I would be really happy to work on this issue. Can you please assign me this one?

Hi @Damon248, This has already been assigned. Please feel free to monitor other issues that may pique your interest. Thank you for your time and consideration.

**Comment by vibh1103** [comment]
Hi @karan-rathod-316 is there any other work i can pick ?

**Comment by suiisharma** [comment]
Hello @karan-rathod-316 ,

I am interested in contributing to this issue.
Can you assign it to me ?
