### ISSUE TITLE
[refactor]: Update descriptions(tooltips) for kanban board, color picker and tree select components

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7527]
### Summary
Descriptions(tooltips) for components need to be updated.

### How to reproduce the issue?

1. Open the ToolJet App-Builder
2. Hover over the components in the Components library on the right
3. You can see descriptions(tooltips) for each component on hover

### Screenshots 

Table component description(tooltip) example:

<img width="958" alt="table-en" src="https://github.com/ToolJet/ToolJet/assets/58169101/e80aa917-6ef0-4dd0-a0c6-ea895d494aba">

<img width="840" alt="table-widget-config" src="https://github.com/ToolJet/ToolJet/assets/58169101/ace5382a-b17b-413b-8114-a7fdd2d50629">

![image](https://github.com/ToolJet/ToolJet/assets/58169101/4f28eb6f-585d-424d-9c84-4ac4ece23f84)

### Any possible solutions?

Replace the current labels in the `widgetConfig.js` and `en.json` files according to the below table.

| Name             | Current Description                  | New Description       |
|:-----------------|:---------------------------------|:----------------------|
| Kanban Board     | Kanban Board                     | Task management board          |
| Color Picker     | Color Picker Palette             | Choose colors from a palette     |
| Tree Select      | Select values from a tree view   | Hierarchical item selector     |

### If the bug is confirmed, would you be willing to submit a PR?
No

### Code of Conduct

- [ ] I agree to follow the [ToolJet Code of Conduct](https://docs.tooljet.com/docs/contributing-guide/code-of-conduct)

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by Chetax** [comment]
@karan-rathod-316   I Would Like To Work On This Issue Can You Please Assigned To Me .

**Comment by suresh8919** [comment]
Hey @karan-rathod-316 I'm interested to work on this Please assign me

**Comment by AbhishekSinghDev** [comment]
Hey @karan-rathod-316  I'm interested to work on this issue can you please assign me.

**Comment by karan-rathod-316** [comment]
> @karan-rathod-316 I Would Like To Work On This Issue Can You Please Assigned To Me .

Hi @Chetax, Thank you so much for your interest in contributing to ToolJet. Assigning the issue to you. 

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by karan-rathod-316** [comment]
> Hey @karan-rathod-316 I'm interested to work on this Please assign me

Hi @suresh8919, thank you so much for your interest. This has already been assigned.

**Comment by Chetax** [comment]
@karan-rathod-316 sir can you please check once my pr ..please sir

**Comment by nikilcodes** [comment]
Hi is this issue taken? I would like to work on it
