### ISSUE TITLE
File Upload in Profile Avatar Accepts Any File

### ISSUE THREAD

**Issue by ATOM43** [ToolJet/ToolJet#7535]
### What is the expected behaviour?
When attempting to upload an image for a profile avatar, the system should check if the selected file is an image and allow only image files to be uploaded.

### What is the current behaviour?
Currently, any type of file can be uploaded as a profile avatar without proper validation, which is not the intended behavior.

### How to reproduce the issue?

1. Open the profile settings.
2. Try uploading any file to avatar.
3. Observe that non-image files are accepted.

### Screenshots or Screencast
![image](https://github.com/ToolJet/ToolJet/assets/94687336/fb2efa29-03ce-46f1-bf66-d98db0200132)

### Any possible solutions?
In the file src/SettingsPage/SettingsPage.jsx, update the input tag (line 194) as follows to enforce the expected behavior:
```javascript
<input
  onChange={(e) => {
    const file = e.target.files[0];
    if (Math.round(file.size / 1024) > 2048) {
      toast.error('File size cannot exceed more than 2MB');
      e.target.value = null;
    } else if (!file.type.startsWith('image/')) {
      toast.error('Please select an image file');
      e.target.value = null;
    } else {
      setSelectedFile(file);
    }
  }}
  accept="image/*"
  type="file"
  className="form-control"
  data-cy="avatar-upload-field"
/>

**Comment by nayangoyal** [comment]
Hi, @ATOM43 can you assign this issue to me? I want to work on this issue.

**Comment by Amruta24818** [comment]
Hey, i did not find this issue in the latest build running locally.

**Comment by ATOM43** [comment]
hey @Amruta24818 ,

In file browser change file type to All files.

**Comment by praneethKJ** [comment]
is it is solved?

**Comment by AllenNH** [comment]
No I believe the bug still exists.
