### ISSUE TITLE
[docs]: changes required in Airtable data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7540]
#### There are a few changes required in the [Airtable data source](https://docs.tooljet.com/docs/data-sources/airtable) reference doc:
1. Replace the following text in description `Airtable API key is required to create an Airtable data source on ToolJet. You can generate API key by visiting [Airtable account page](https://airtable.com/account). ` with the text below:
	  ```
	Airtable Personal Access Token is required to connect to the Airtable data source on ToolJet. You can generate the PAT by visiting [Developer Hub from your Airtable profile](https://support.airtable.com/docs/creating-and-using-api-keys-and-access-tokens#understanding-personal-access-token-basic-actions)
  	```
2. Rename the heading `Supported Queries` to `Supported Operations`
3. Remove the `TIP: This guide assumes that you have already gone through Adding a data source tutorial.`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/airtable

### Additional Information

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by AnushkaPhogat16** [comment]
Hey! I'd like to work on this issue

**Comment by chaitanya005** [comment]
Hey, I would like to take up this issue

**Comment by withshubh** [comment]
Hey @AnushkaPhogat16 - Thanks for showing interest in contributing to ToolJet.
We have assigned the issue to you.

**Comment by withshubh** [comment]
Hey @chaitanya005 - Thanks for showing interest in contributing to ToolJet.
We assign issues on first-come-first-served basis. Since the issue is already assigned I would request you enable the  `watch` on repository, this will help you receive email notifications as soon as we create new issues for hacktoberfest.

**Comment by AnushkaPhogat16** [comment]
Thank you! I'll start working on this asap. 
I am a beginner at this though, could you please let me know how I should start?

**Comment by omkarvilasmote** [comment]
@AnushkaPhogat16  can you asign me this work .

**Comment by tejakummarikuntla** [comment]
Hey @AnushkaPhogat16 , were you able to progress with the issue? Could you look into the previous documentation PRs for reference? Feel free to let us know if you'd like to get this unassigned. We can assign it to others who are willing to contribute just like you. Thanks for your understanding.

**Comment by omkarvilasmote** [comment]
@tejakummarikuntla i will already solved this issue 🙂

**Comment by Bajpai25** [comment]
@tejakummarikuntla 
Could you assign me this issue.

**Comment by withshubh** [comment]
Hey @AnushkaPhogat16 
Please go through this README to learn more about setting up documentation locally: https://github.com/ToolJet/ToolJet/tree/develop/docs#readme

**Comment by tejakummarikuntla** [comment]
Unassigning @AnushkaPhogat16 due to inactivity. 
Assigned the issue to @omkarvilasmote

**Comment by omkarvilasmote** [comment]
@tejakummarikuntla i will alredy push the pull request can you check that

**Comment by omkarvilasmote** [comment]
Sorry for by mistake unsigned clicked sorry @tejakummarikuntla

**Comment by omkarvilasmote** [comment]
@tejakummarikuntla i am working on

**Comment by omkarvilasmote** [comment]
Sir can you assign me any another task?
