### ISSUE TITLE
[docs]: changes in Appwrite data source reference

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7543]
#### changes required
- [ ] Rename doc title from `Appwrite database` to `Appwrite`
- [ ] The description should be `ToolJet can connect to appwrite database to read/write data.`
- [ ] Replace the text `To connect Appwrite datasource to your ToolJet application, go to the data source manager on the left-sidebar and click on the + button. Select Appwrite from the list of available datasources, provide the credentials and click Save. It is recommended to check the connection by clicking on 'Test connection' button to verify if the service account can access Appwrite from the ToolJet server.` with the text below:
     

```
To establish a connection with the Appwrite data source, you can either click on the `+Add new data source` button located on the query panel or navigate to the [Data Sources](https://docs.tooljet.com/docs/data-sources/overview) page from the ToolJet dashboard.
```

---
Note: To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/appwrite

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by nayangoyal** [comment]
Hi, @withshubh can you assign this issue to me? I want to work on this issue.

**Comment by vinayakhegde1** [comment]
Hello @withshubh . I'm new can I work on this

**Comment by morgoth9808** [comment]
Hey @withshubh can I work on this issue

**Comment by withshubh** [comment]
Hey @nayangoyal - Thanks for showing interest in contributing to ToolJet.
We have assigned the issue to you.

**Comment by withshubh** [comment]
Hey @vinayakhegde1 & @morgoth9808 👋 
Thanks for showing interest in contributing to ToolJet.
We assign issues on first-come-first-served basis. Since the issue is already assigned I would request you enable the  `watch` on repository, this will help you receive email notifications as soon as we create new issues for hacktoberfest.

**Comment by vinayakhegde1** [comment]
@withshubh no problem thanks for the help looking forward to contribute

**Comment by omkarvilasmote** [comment]
@nayangoyal  I will submited pull request can you check it and merge please if request are right.

**Comment by sri766** [comment]
Hello @withshubh I want to work on this. Can you assign it to me?

**Comment by ruhankhandakar** [comment]
I want to work on this. @withshubh Can you assign it to me ?

**Comment by suiisharma** [comment]
Hello @withshubh,

I am interested in contributing to this issue. 
Can you assign it to me ?

**Comment by Kajanan02** [comment]
I want to work on this. @withshubh  Can you assign it to me ?

**Comment by tejakummarikuntla** [comment]
Hey @nayangoyal, apologies for assigning you on this. Turns out, there's an existing assignment and the PR is greenlit. We need to unassign you to welcome other first-time contributors. Thanks for your understanding.

@vinayakhegde1, @morgoth9808, @suiisharma, @ruhankhandakar, @sri766 and others, kindly let us know if you are interested in picking this up. We shall assign this to you on FCFS basis.

**Comment by suiisharma** [comment]
@tejakummarikuntla  
 am interested in contributing to this issue.

**Comment by omkarvilasmote** [comment]
I am interested in this issue can you assign it its helpful to got it somthing new. 🫡

**Comment by ruhankhandakar** [comment]
I am interested also 🙌🏻

**Comment by omkarvilasmote** [comment]
That message for maintainer  that task was very easy if you assigned task to someone so. if that person not able to complete then you please assign to some thats help us to achieve something, from this task ,so please can you check that person well providing any solution at. Please assign it someone


And also I am checked some organization repo so there maintainers will be not assigning issue to someone that directly that any person will send first pull request we will be merged it and so ,why you like not do in your repo

**Comment by weedertree** [comment]
could you assign me this isssue

**Comment by Bajpai25** [comment]
@tejakummarikuntla
 I am interested could you assign me this issue.
