### ISSUE TITLE
Email field overlap with backdrop

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#755]
### Version Information
Latest

### What is the expected behaviour?
Email should not overlap

### What is the current behaviour?
Email field is overlapping

### How to reproduce the issue?

1. Click on deploy button on navbar
2. Observe email field overlapping with backdrop

### Screenshots or Screencast
https://imgur.com/a/4gPl4w3

**Comment by johnbabu021** [comment]
can i work on that

**Comment by Navaneeth-pk** [comment]
@johnbabu021 assigned the issue, thanks for contributing to ToolJet!

**Comment by Navaneeth-pk** [comment]
Is there any update on this issue?
@johnbabu021

**Comment by johnbabu021** [comment]
oh there is a problem i can't signup 
error showing invalid email
tried different mails but still not working

**Comment by Navaneeth-pk** [comment]
@johnbabu021 on local or on ToolJet cloud?

**Comment by johnbabu021** [comment]
on local

**Comment by vikasazad** [comment]
Hi @Navaneeth-pk  can i work on this issue..?

**Comment by Navaneeth-pk** [comment]
Sure, assigned to you.
@vikasazad

**Comment by gondar00** [comment]
Closing as issue is fixed
