### ISSUE TITLE
Phone Numbers should be checked and sanitised before onboarding users

### ISSUE THREAD

**Issue by moyezr** [ToolJet/ToolJet#7571]
### Environment
ToolJet Website

### What is the expected behaviour?
The phone number should be checked and verified while onboarding users.
Atleast proper frontend sanitation should be there to ensure that fake phone numbers are not being pushed to database.

### What is the current behaviour?
Currently, when users enter their phone number while onboarding, they can enter literally anything and get away with it.

### How to reproduce the issue?

1.Go to the official website.
2. Use incognito mode.
3. Register for a new account. Provide any number.

### Any possible solutions?
We can use regex or third-party providers to send an otp to users when asking the phone numbers for onboarding.

### Can you identify the location in the driver source code where the problem exists?
Yes, it occurs in PhoneNumberInput component by react-phone-input-2 package.

### If the bug is confirmed, would you be willing to submit a PR?
yes

**Comment by JaswanthJeethu18** [comment]
I would like to work on this , Its a good issue , Kindly someone assign me this issue

**Comment by chaursiyasanjeet** [comment]
I will also like to work on this can you please assign it to me.

**Comment by prashantug21** [comment]
Hi @moyezr, I think basic verification can be done using regular expressions. I would love to work on this issue.

**Comment by moyezr** [comment]
I am not the moderator of the code base. 

So, I can't really assign the issue to you all.

Solve it make a pull request and let the moderators decide if it's for the good.

I just found the issue and proposed it.

Thanks.

**Comment by withshubh** [comment]
Thanks for creating the issue. 
It is being taken care of internally.
