### ISSUE TITLE
UI Improvement : "prefered by thousand companies" section

### ISSUE THREAD

**Issue by VarunCypherV** [ToolJet/ToolJet#7588]
### Is your proposal related to a problem?

  When we look at the preferred by thousand companies headline , its too small and very close to the company logos
[
![image](https://github.com/ToolJet/ToolJet/assets/91377728/01935a97-16ba-40b7-9f01-1e8819e248a0)
](url)

It adds unnecessary tension to the UI

### Describe the solution you'd like

The Proposed Solution is to Add padding space between the list of companies and increase the font size and lighten the font weight / change the colour to grey/whitesmoke

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
Yes I would want to be assigned with this issue please

**Comment by shakthi2003-ice** [comment]
Hey VarunCypherV
I would like to work on this issue. Can u please assign me this issue

**Comment by Bloodlycrul** [comment]
Hello VarunCypherV,
Could you please assign this issue to me?

**Comment by shubh22** [comment]
This repo is not for tooljet.com website. So closing this.
