### ISSUE TITLE
[docs]: changes required in Athena data source reference

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7589]
### Summary

There are a few changes required in the [Athena](https://docs.tooljet.com/docs/data-sources/athena) reference doc:
- Remove the note `NOTE: Query must be saved before running.`
- Update the description for `Connection`:
```
To establish a connection with the Amazon Athena data source, you can either click on the `+Add new data source` button located on the query panel or navigate to the [Data Sources](https://docs.tooljet.com/docs/data-sources/overview) page from the ToolJet dashboard.
```

- Remove the image from the `Querying Amazon Athena` section

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/athena

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by alammoiz** [comment]
Could you please assign to me @withshubh

**Comment by FreemRL** [comment]
Hi I created a PR for this issue (#7592) ^^

**Comment by tejakummarikuntla** [comment]
Hey @alammoiz
Thanks for your interest, since you are already a valuable contributor to us, let's welcome first-time contributors like @FreemRL to the project. Hope you understand.

Assigned the issue to @FreemRL

**Comment by MysteryManav** [comment]
@withshubh can you assign the issue to me ? As a first timer for hacktoberfest, if i can I would like to work on this
