### ISSUE TITLE
UI Improvement : "Building Better Apps Together" section

### ISSUE THREAD

**Issue by VarunCypherV** [ToolJet/ToolJet#7590]
### Is your proposal related to a problem?

The Github Page snippet add on looks like " I want this in the UI no matter even if it means sacrificing the quality of the UI"
![image](https://github.com/ToolJet/ToolJet/assets/91377728/65496ae0-bccf-4bf0-9fb7-13d286705524)

### Describe the solution you'd like

I would take two snippets 1 of the github and one of the slack and put them on the respective sides of the button , reduce the opacity a bit and transform them to rotate some degs and place them as a showcase near the buttons 

### Describe alternatives you've considered

Again make the repository snippet as a light fade background for the right half and then the slack one for left half but color contrast might pose a problem so i restored to what i proposed
(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
Yes i would love to implement it , please assign it to me

**Comment by shubh22** [comment]
This repo is not for tooljet.com website. Hence closing this issue.
