### ISSUE TITLE
[docs]: changes required in Azure blob data source reference

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7591]
### Summary

There are a few changes required in the [Azure blob](https://docs.tooljet.com/docs/data-sources/azureblob) reference doc:
- Replace the term `global datasource` with `data source` or `data sources` in the entire doc
- Make all the **headings** in the doc to [Title Case](https://en.wikipedia.org/wiki/Title_case) (first letter of each word should be capital)

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/azureblob

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by alammoiz** [comment]
Could you please assign to me @withshubh ?

**Comment by mangnez** [comment]
I'm interested in working on this issue @withshubh . If no one has been assigned yet, I'd appreciate the chance to contribute to it.

**Comment by FreemRL** [comment]
Hi I created a PR for this (#7594) ^^

**Comment by tejakummarikuntla** [comment]
We wanted to share that @alammoiz has been a valuable contributor, and @FreemRL already has an issue assigned. In this regard, we'd like to assign the issue to @mangnez. We appreciate your understanding and cooperation. Thanks!

**Comment by mangnez** [comment]
@tejakummarikuntla , will complete this soon. I request you to not assign this to anyone else. Thanks for your patience.

**Comment by mangnez** [comment]
@tejakummarikuntla @withshubh , thanks for assigning this issue to me.
I've made a pr, do check it out.
https://github.com/ToolJet/ToolJet/pull/7615

**Comment by alammoiz** [comment]
> We wanted to share that @alammoiz has been a valuable contributor, and @FreemRL already has an issue assigned. In this regard, we'd like to assign the issue to @mangnez. We appreciate your understanding and cooperation. Thanks!

I don't have any open items yet @tejakummarikuntla . Could you please check again?
