### ISSUE TITLE
[docs]: changes required in Baserow data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7595]
### Summary

There are a few changes required in the [Baserow](https://docs.tooljet.com/docs/data-sources/baserow/) reference doc:
- Remove it from the `Connection` and it before connection section:
```
ToolJet can connect to your Baserow account to read and write data. 
```
- Update the following description for the `Connection`:
```
## Connection

To connect to Baserow, you need to provide the following details:

- **API token**: You can create an API token from your Baserow dashboard. You can follow the steps to create API token from [this link](https://baserow.io/user-docs/personal-api-tokens).
- **Host**: You can either select the Baserow Cloud or Self-hosted option.
  - **Base URL**: If you select the self-hosted option, you need to provide the base URL of your Baserow instance.
```
- Remove the tip `This guide assumes that you have already gone through Adding a data source tutorial.`
- Rename `Supported queries` to `Supported Operations`

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/baserow/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by AniruddhaGawali** [comment]
i can help in that can you assign it to me

**Comment by shelar1423** [comment]
Willing to contribute, kindly assign the above issue to me.

**Comment by tejakummarikuntla** [comment]
Hey @AniruddhaGawali , thanks for your interest, Assigned the issue to you.
We welcome you to join our ToolJet developer community on [Slack](https://tooljet.com/slack). For any assistance related to issues/contributions, please post in the #contributors channel.

**Comment by AniruddhaGawali** [comment]
> Hey @AniruddhaGawali , thanks for your interest, Assigned the issue to you. We welcome you to join our ToolJet developer community on [Slack](https://tooljet.com/slack). For any assistance related to issues/contributions, please post in the #contributors channel.

its show slack link is not active

**Comment by tejakummarikuntla** [comment]
@AniruddhaGawali , Thanks for brining this up, will check this and update you.
