### ISSUE TITLE
[docs]: changes required in BigQuery data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7598]
### Summary

There are a few changes required in the [BigQuery](https://docs.tooljet.com/docs/data-sources/bigquery) reference doc:

- Update the following description for the `Connection`:
```
## Connection

To connect to BigQuery, you need to enable BigQuery API in your Google Cloud Console. You can follow the steps to enable BigQuery API from [this link](https://cloud.google.com/bigquery/docs/bigquery-web-ui). 

Next, you need to create a service account and generate a key for the same. You can follow the steps to create a service account from [this link](https://cloud.google.com/iam/docs/creating-managing-service-accounts).

Now, copy and paste the data from the downloaded JSON file into the **Private key** field in the BigQuery data source form.

**The json file should look like this:**
```
- Remove `Click on the run button to run the query. NOTE: Query should be saved before running.` from the Querying `BigQuery` section.

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/bigquery

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by MSaiKiran9** [comment]
Hi i'm new to this repository & I want to work on this issue can you assign me

**Comment by shelar1423** [comment]
I would like to contribute, kindly assign me

**Comment by tejakummarikuntla** [comment]
Hey @MSaiKiran9, thanks for your interest. Assigned the issue to you.
