### ISSUE TITLE
[docs]: changes required in Cloud Firestore data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7599]
### Summary

There are a few changes required in the [Cloud Firestore](https://docs.tooljet.com/docs/data-sources/firestore) reference doc:
- Add a desctription above `Connection`
```
ToolJet can connect to Cloud Firestore databases to read and write data.
```
- Update the description of the `Connection` to
```
ToolJet connects to your Cloud Firestore using JSON key of your GCP service account. Get your service account key as JSON from GCP console. For generating a new key, check out [Firestore's official documentation](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#iam-service-account-keys-create-console).

Once you have the key, open it in a text editor and copy the contents. Paste the contents in the **Private key** field of the Firestore data source modal.

Click on **Test connection** button to verify if the key is valid. Click on **Save** button to save the data source.
```

Make the above changes in the following:

1. `docs/docs`
2. `docs/versioned_docs/version-2.19.0`
3. `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/firestore

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by shelar1423** [comment]
would like to work on this, kindly assign it to me

**Comment by shakthi2003-ice** [comment]
i have been waiting to get assigned in any issue for the past  days

**Comment by tejakummarikuntla** [comment]
Hey @shelar1423 , thanks for your interest. Assigned the issue to you.
We welcome you to join our ToolJet developer community on [Slack](https://tooljet.com/slack). For any assistance related to issues/contributions, please post in the #contributors channel.

**Comment by shakthi2003-ice** [comment]
I have just started to do open source and i really want to grab this issue
