### ISSUE TITLE
[docs]: changes required in ClickHouse data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7602]
### Summary

There are a few changes required in the [ClickHouse](https://docs.tooljet.com/docs/data-sources/clickhouse) reference doc:
1. Update the description of `Connection` to:
```
To establish a connection with the Clickhouse data source, you can either click on the `+Add new data source` button located on the query panel or navigate to the **[Data Sources](/docs/data-sources/overview)** page through the ToolJet dashboard.
```
2. Rename `datasource` to `data source` or `data sources` in the doc

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/clickhouse

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Kajanan02** [comment]
Can you assign me?

**Comment by Bloodlycrul** [comment]
Could you please assign it to me?

**Comment by shakthi2003-ice** [comment]
Can you please assign me this issue? I really want to make a pr

**Comment by ChinmayAlekar** [comment]
Hey can you please assign me this issue?

**Comment by VivekGuruduttK28** [comment]
Hi @withshubh 
I'm interested in contributing for this issue.
Can it be assigned to me

**Comment by tejakummarikuntla** [comment]
Hey @Kajanan02, thanks for your interest. Assigned the issue to you.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by tejakummarikuntla** [comment]
Hey @Kajanan02 , were you able to progress with the issue? Kindly keep us updated.
Btw, you can feel free to let us know if you'd like to get this unassigned by chance.

**Comment by tejakummarikuntla** [comment]
Unassigned @Kajanan02, due to inactivity.

**Comment by viditagrawal56** [comment]
Hey @tejakummarikuntla can you assign me this issue? I would love to work on it!

**Comment by tejakummarikuntla** [comment]
Hey @tmsagarofficial, thank you for your interest. Assigned the issue to you.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
