### ISSUE TITLE
[docs]: changes required in CosmosDB data source reference

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7607]
### Summary

There are a few changes required in the [CosmosDB](https://docs.tooljet.com/docs/data-sources/cosmosdb/) reference doc:
- Update the description of **Connection** to:
```
To establish a connection with the CosmosDB data source, you can either click on the `+Add new data source` button located on the query panel or navigate to the **[Data Sources](/docs/data-sources/overview)** page through the ToolJet dashboard.
```
- Convert all the headings in `Title Case`

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/cosmosdb

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by vishalkhoje** [comment]
Please assign this issue to me

**Comment by DhritiSoni4** [comment]
Can you please assign this issue to me?

**Comment by tejakummarikuntla** [comment]
Hey @vishalkhoje, thanks for your interest. Assigned the issue to you.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
