### ISSUE TITLE
[docs]: changes required in CouchDB data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7608]
### Summary

There are a few changes required in the [CouchDB](https://docs.tooljet.com/docs/data-sources/couchdb/) reference doc:

1. Remove the gif below the CouchDB description
2. Convert all the headings in `Title Case`
3. Remove the `INFO: NOTE: Query must be saved before running.` under Creating a record section.

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/couchdb

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by nabeel001** [comment]
@withshubh, I would like to work on this issue. Kindly request you to assign this to me

**Comment by tejakummarikuntla** [comment]
Hey @Rizina, thanks for your interest. Assigned the issue to you.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
