### ISSUE TITLE
[docs]: changes required in DynamoDB data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7609]
### Summary

There are a few changes required in the [DynamoDB](https://docs.tooljet.com/docs/data-sources/dynamodb) reference doc:

1. Rename `global data source` to `data source` in the entire doc

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/dynamodb/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by FroostyCodes** [comment]
Hi @withshubh I would like to work on this issue, please do assign it to me 🙏

**Comment by Ramana5564** [comment]
@withshubh I wish to work on this issue.

**Comment by shakthi2003-ice** [comment]
Can you assign me this issue.

**Comment by Bloodlycrul** [comment]
Could you please assign it to me because it's my first time?

**Comment by Ash-mit17** [comment]
Hey can you assign this issue to me

**Comment by VivekGuruduttK28** [comment]
Hi @withshubh 
I'm interested in working on this issue. Can it be assigned to me ?

**Comment by alammoiz** [comment]
Hi @withshubh please assign to me

**Comment by manmohanhunjan** [comment]
@withshubh i would like to work on this issue

**Comment by neha-gunta** [comment]
@withshubh I've made a pull request, kindly look into it

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to you @Ramana5564
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by Ramana5564** [comment]
@tejakummarikuntla I have made a pull request.  Please look into it

**Comment by withshubh** [comment]
Hey @Ramana5564 - There was a mistake from my end. I have updated the URL in the description. Please take a look and make the suggested changes in DynamoDB doc.

**Comment by HeetVekariya** [comment]
@withshubh can i make pull request ?

**Comment by Ramana5564** [comment]
@withshubh I have made a pull request with the new required change. Please look into it.

**Comment by Ramana5564** [comment]
@withshubh new pull request is made with the required change. Please look into it.
