### ISSUE TITLE
[docs]: changes required in ElasticSearch data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7611]
### Summary

There are a few changes required in the [ElasticSearch](https://docs.tooljet.com/docs/data-sources/elasticsearch) reference doc:
1. Update the second paragraph of `Connection` from this:
```
To add a new Elasticsearch database, click on the + button on the data sources panel at the left-bottom corner of the app editor. Select Elasticsearch from the modal that pops up.
```
To this:
```
To establish a connection with the ElasticSearch data source, you can either click on the `+Add new data source` button located on the query panel or navigate to the **[Data Sources](/docs/data-sources/overview)** page through the ToolJet dashboard.
```
2. Rename `datasource` to `data source` or `data sources` in the doc

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/elasticsearch

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by shelar1423** [comment]
Would like to contribute to this.kindly assign

**Comment by AniruddhaGawali** [comment]
i can help in that can you assign it to me

**Comment by mhassanrahi** [comment]
@withshubh , I've fixed it and raised the PR #7618 .

**Comment by alammoiz** [comment]
Can you please assign to me?

**Comment by tejakummarikuntla** [comment]
Hey @mhassanrahi thanks for your interest. Assigned the issue to you.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by shelar1423** [comment]
@tejakummarikuntla but i commented first ,I thought it was a first come first serve basis right ?

**Comment by tejakummarikuntla** [comment]
Hey @shelar1423. Yes, we assign on FCFS, I see you've got an issue already assigned, and I wish you the best in progressing it. We also wanted to welcome first-timers to the project, who had not got any issues assigned, I hope this helps.

**Comment by shelar1423** [comment]
> Hey @shelar1423. Yes, we assign on FCFS, I see you've got an issue already assigned, and I wish you the best in progressing it. We also wanted to welcome first-timers to the project, who had not got any issues assigned, I hope this helps.

Sure understood,so untill my that PR gets merged I can't be assigned another issue ? And till when can I expect the PR to be reviewed
