### ISSUE TITLE
[docs]: changes required in Google Cloud Storage data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7613]
### Summary

There are a few changes required in the [Google Cloud Storage](https://docs.tooljet.com/docs/data-sources/gcs) reference doc:
1. The list of `Supported Operations` are breaking and showing up in one line. Fix it to show it as bullet list items.
2. Rename `datasource` to `data source` or `data sources` in the doc
3. Update the first paragraph of `Connection` section to this:
```
To establish a connection with the Google Cloud Storage data source, you can either click on the `+Add new data source` button located on the query panel or navigate to the **[Data Sources](/docs/data-sources/overview)** page through the ToolJet dashboard.

To connect to GCS, you need to provide the JSON Private Key of a service account that has access to the bucket. You can follow the [google documentation](https://cloud.google.com/docs/authentication/getting-started) to get started.
```

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/gcs/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by AniruddhaGawali** [comment]
i can help in that can you assign it to me

**Comment by UdaySagar-Git** [comment]
hey can you assign it to me ! happy to contribute

**Comment by shakthi2003-ice** [comment]
hey can you assign me this issue?

**Comment by mhassanrahi** [comment]
@withshubh , I've fixed it and raised the PR #7616 .

**Comment by alammoiz** [comment]
Can you please assign to me?

**Comment by tejakummarikuntla** [comment]
Hey @UdaySagar-Git , thanks for your interest. Assigned the issue to you.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
