### ISSUE TITLE
[docs]: changes required in MailGun data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7641]
### Summary

There are a few changes required in the [MailGun](https://docs.tooljet.com/docs/data-sources/mailgun) reference doc:

1. Remove `NOTE: Query should be saved before running.`
2. Update the description for `Connection` to:
```
To establish a connection with the MailGun data source, click on the `+Add new data source` button located on the query panel or navigate to the [Data Sources](https://docs.tooljet.com/docs/data-sources/overview) page from the ToolJet dashboard.
```

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/mailgun

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by nishitxmehta** [comment]
Can you please assign this issue to me?

**Comment by DarrenDsouza7273** [comment]
can i work on this

**Comment by nishitxmehta** [comment]
@withshubh I've the whole documentation I can do it for you, please assign this to me.

**Comment by AtulMinz** [comment]
Can you please assign me this issue?

**Comment by Bitnagar** [comment]
@AtulMinz Unprofessional behaviour. We should wait for it to get assigned.

**Comment by alammoiz** [comment]
Please assign to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @nishitxmehta 
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by nishitxmehta** [comment]
thanks @tejakummarikuntla! I'll start working on the issue.

**Comment by nishitxmehta** [comment]
@tejakummarikuntla, any update on the PR?

**Comment by nishitxmehta** [comment]
@tejakummarikuntla, any issues in the PR?

**Comment by nishitxmehta** [comment]
Hi @withshubh, @tejakummarikuntla, any issues in the PR? Please let me know.
