### ISSUE TITLE
[docs]: changes required in Minio data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7642]
### Summary

There are a few changes required in the [Minio](https://docs.tooljet.com/docs/data-sources/minio) reference doc:

1. Remove `NOTE: Query should be saved before running.`
2. Update the description for `Connection` to:
```
To establish a connection with the Minio data source, click on the `+Add new data source` button located on the query panel or navigate to the [Data Sources](https://docs.tooljet.com/docs/data-sources/overview) page from the ToolJet dashboard.
```

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/minio

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by jatingodnani** [comment]
Interested

**Comment by DarrenDsouza7273** [comment]
can i work on this issue

**Comment by Himangshi** [comment]
assign me please

**Comment by alammoiz** [comment]
Please assign to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @jatingodnani.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
