### ISSUE TITLE
[docs] update the title of HTML and Rich Text Editor component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7643]
### Summary

Update the frontmatter of HTML and Rich editor components.

In the `html.md` file, update the following:
```
---
id: html
title: HTML Viewer
---

# HTML Viewer
```

In the `rich-text-editor.md` file, update the following:
```
---
id: rich-text-editor
title: Text Editor
---
# Text Editor
```

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation bug

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by AdePhil** [comment]
I am interested in this.

**Comment by DarrenDsouza7273** [comment]
Can i work on this issue

**Comment by shelar1423** [comment]
Hey I have a good experience with html , would like to contribute to this

**Comment by AbhineshJha** [comment]
hey ! this is interesting can i work on this ??

**Comment by alammoiz** [comment]
Please assign to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @AdePhil.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
