### ISSUE TITLE
[docs]: changes required in MongoDB data source reference

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7645]
### Summary

There are a few changes required in the [Minio](https://docs.tooljet.com/docs/data-sources/minio) reference doc:

1. Remove `NOTE: Query should be saved before running.`
2. Update the following statement:
```
To add a new MongoDB, click on the + button on data sources panel at the left-bottom corner of the app editor. Select MongoDB from the modal that pops up.
```
to this:
```
To establish a connection with the MongoDB data source, click on the `+Add new data source` button located on the query panel or navigate to the [Data Sources](https://docs.tooljet.com/docs/data-sources/overview) page from the ToolJet dashboard.
```

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/mongodb

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by AtulMinz** [comment]
Can you please assign me this issue?

**Comment by FreemRL** [comment]
I created a PR for this :) (#7646)

**Comment by nikhilgarg26** [comment]
hey @withshubh can i start working on this issue ?

**Comment by alammoiz** [comment]
Please assign to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @AtulMinz.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
