### ISSUE TITLE
[docs]: changes required in MS SQL Server data source reference

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7648]
### Summary

There are a few changes required in the [MS SQL Server](https://docs.tooljet.com/docs/data-sources/mssql) reference doc:

1. Remove `NOTE: Query should be saved before running.`
2. Update the following statement:
```
To add new MS SQL Server / Azure SQL database, click on the '+' button on data sources panel at the left-bottom corner of the app editor. Select SQL Server from the modal that pops up.
```
to this:
```
To establish a connection with the MS SQL Server data source, click on the `+Add new data source` button located on the query panel or navigate to the [Data Sources](https://docs.tooljet.com/docs/data-sources/overview) page from the ToolJet dashboard.
```

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/mssql

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by charandeepsinghb** [comment]
Can you please assign this to me?
Thank you!

**Comment by neha-gunta** [comment]
hey @withshubh can you assign this issue to me, I'm willing to work on it

**Comment by VivekGuruduttK28** [comment]
Hi @withshubh 
I would like to work on this issue. Can it be assigned to me?

**Comment by nikhilgarg26** [comment]
hey @withshubh can i take up this issue

**Comment by alammoiz** [comment]
Please assign to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @charandeepsinghb.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by charandeepsinghb** [comment]
@tejakummarikuntla I have added a PR
