### ISSUE TITLE
[docs]: changes required in n8n data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7650]
### Summary

There are a few changes required in the [n8n](https://docs.tooljet.com/docs/data-sources/n8n) reference doc:

1. Update the following statement in Connection section:
```
Go to the data source manager on the left sidebar and click on + button to add new data source. Select n8n from the list of available data sources in the modal that pops-up.
```
to this:
```
To establish a connection with the n8n data source, click on the `+Add new data source` button located on the query panel or navigate to the [Data Sources](https://docs.tooljet.com/docs/data-sources/overview) page from the ToolJet dashboard.
```

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/mysql

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by charandeepsinghb** [comment]
Hi, I would like to work on this!
Please assign it to me 🙂
Thank you!

**Comment by neha-gunta** [comment]
hey @withshubh can you assign this issue to me, I'm willing to work on it

**Comment by ValkonX33** [comment]
i'm up for it

**Comment by alammoiz** [comment]
Please assign to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @neha-gunta.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
