### ISSUE TITLE
[docs]: changes required in Notion data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7651]
### Summary

There are a few changes required in the [Notion](https://docs.tooljet.com/docs/data-sources/notion) reference doc:

1. Add this as a first paragraph under the `Connection` heading:
```
To establish a connection with the Notion data source, click on the `+Add new data source` button located on the query panel or navigate to the [Data Sources](https://docs.tooljet.com/docs/data-sources/overview) page from the ToolJet dashboard.
```

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/notion

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Sakshi-75** [comment]
Hi @withshubh , can I work on this?

**Comment by abhiraj-ku** [comment]
Hey , @withshubh can i work on this issue?

**Comment by neha-gunta** [comment]
hey @withshubh can you assign this issue to me, I'm willing to work on it

**Comment by VivekGuruduttK28** [comment]
Hi @withshubh 
I would like to work on this issue. Can it be assigned to me?

**Comment by nikhilgarg26** [comment]
hey @withshubh can you please assign me this issue

**Comment by alammoiz** [comment]
Please assign to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @Sakshi-75 .
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by Sakshi-75** [comment]
Hi @withshubh , I've raised a PR for this issue. Please review and share your feedbacks if any. Thanks!
