### ISSUE TITLE
[docs]: changes required in OpenAPI data source reference

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7652]
### Summary

There are a few changes required in the [OpenAPI](https://docs.tooljet.com/docs/data-sources/openapi) reference doc:

1. Rename the `global datasource` to `data source ` or `data sources` in the entire doc

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/openapi

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by vedant-z** [comment]
@withshubh I want to take this one.

**Comment by manmohanhunjan** [comment]
@withshubh would like to work on this issue.

**Comment by neha-gunta** [comment]
hey @withshubh can you assign this issue to me, I'm willing to work on it

**Comment by VivekGuruduttK28** [comment]
Hi @withshubh 
I would love to work on this issue.. Can it be assigned to me

**Comment by nikhilgarg26** [comment]
hey @withshubh can i work on this issue ?

**Comment by alammoiz** [comment]
Please assign to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @manmohanhunjan.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.
