### ISSUE TITLE
[docs]: changes required in MySQL data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7654]
### Summary

There are a few changes required in the [MySQL](https://docs.tooljet.com/docs/data-sources/mysql) reference doc:

1. Rename the global datasource to `data source`
2. Rename `datasource` to `data source` or `data sources`

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/mysql/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by SanchitMahajan236** [comment]
Can you please assign this issue to me ?
I am interested to contribute .

**Comment by manmohanhunjan** [comment]
I would like to work on this issue.

**Comment by Shifat-Ali** [comment]
Hey @withshubh ,
I would like to work on this.

**Comment by Tjs002** [comment]
@withshubh can i work on this issue?

**Comment by MrLEGENDx10** [comment]
Assign me

**Comment by nikhilgarg26** [comment]
hey i am new to open source can i start working on this issue ?

**Comment by alammoiz** [comment]
Please assign to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @SanchitMahajan236.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by SanchitMahajan236** [comment]
I have created a pull request. Please review this PR and merge it.

**Comment by ayan-joshi** [comment]
@withshubh any more issues will be coming from tooljet?

**Comment by withshubh** [comment]
> @withshubh any more issues will be coming from tooljet?

Hey @ayan-joshi , Yes we will be creating new issues for community the entire October, please enable the `watch` in this repository to get instant alerts over email.
