### ISSUE TITLE
[docs]: changes required in Oracle DB data source reference 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7655]
### Summary

There are a few changes required in the [Oracle DB](https://docs.tooljet.com/docs/data-sources/oracledb) reference doc:

1. Remove the ` NOTE: Query should be saved before running.`
2. Add this as first paragraph under Connection heading:
```
To establish a connection with the Oracle DB data source, click on the `+Add new` button located on the query panel or navigate to the [Data Sources](https://docs.tooljet.com/docs/data-sources/overview) page from the ToolJet dashboard.
```

Make the above changes in the following:
- `docs/docs`
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/oracledb

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by SanchitMahajan236** [comment]
I am interested. Can you please assign me this issue ?

**Comment by Gourav2609** [comment]
hello @withshubh can you please assign this issue to me

**Comment by neha-gunta** [comment]
hey @withshubh can you assign this issue to me, I'm willing to work on it

**Comment by HeetVekariya** [comment]
@withshubh I would like to work on this issue.

- My query is that do i needed to be assigned to work on a issue, as It is not written anywhere including contributing.md and readme.me
- While going through the closed issues, most of the PR's are made by the one who is not assigned with that issue & they got merged as well.
- So which practice, i should follow ? do request for issue or go for PR ?

**Comment by nikhilgarg26** [comment]
hey @withshubh i am new to open source can i start with this issue ?

**Comment by alammoiz** [comment]
Please assign it to me.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @Gourav2609.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by Gourav2609** [comment]
thanks @tejakummarikuntla ....

**Comment by Gourav2609** [comment]
Hello @tejakummarikuntla ... please check out the PR #7693  .. looking forward to contribute more
