### ISSUE TITLE
r7ry[refactor]: 

### ISSUE THREAD

**Issue by BMWGS12501000** [ToolJet/ToolJet#7659]
### What area of the codebase is to be refactored?

fgnfgnfgmnhvmb mjhltdsrfaeszgdfcxbvvmhgjrhdxfbvcxvbvb
(Write your answer here.)

### What are the potential advantages of this proposed refactoring?
3etsedh tryw3r3r47h5no8 bjfgj 65y4kjfh
'lsp-odi=t0-w34-ti kgwp[]-=ye57]\\h]fh
rd;\5
]hdfyhdfh 
5e675eyrtwswe4q235nbhjgl,,rty77,ou89.t55
dtyer563
(Describe the advantages here.)3

**Comment by BMWGS12501000** [comment]
fgydrrdrrrydrset

**Comment by HeetVekariya** [comment]
I would like to work on this issue.
Can you please give me more clear description for the issue.
