### ISSUE TITLE
Changing UI in home page

### ISSUE THREAD

**Issue by PRIZZA21** [ToolJet/ToolJet#7681]
At the home page 
![image](https://github.com/ToolJet/ToolJet/assets/96612308/b12e78c7-f19c-414a-bf2a-5b0c8bd2a071)

We can change the UI like sliding carousel 
![image](https://github.com/ToolJet/ToolJet/assets/96612308/6111b270-ce8d-4e1b-bb4d-d0d88b756756)

If the issue is approved , I am willing to give the PR for it

**Comment by Yasir761** [comment]
Is anyone working on this issue, If none please assign it to me?
