### ISSUE TITLE
Link is no longer active

### ISSUE THREAD

**Issue by moheyt** [ToolJet/ToolJet#7690]
I've identified an issue with the Slack invite link not functioning correctly (Link is no longer active). Kindly assign the task to me, and I'll resolve the problem.

![Screenshot (330)](https://github.com/ToolJet/ToolJet/assets/85775976/75bb15c3-d628-45c8-84a2-b1ef538a512e)

**Comment by HeetVekariya** [comment]
I would like on this issue, can you please assign it to me.

**Comment by Sanidhya0077** [comment]
Hey @moheyt I think the slack invite link is expired and needs to be updated.

**Comment by Aarav238** [comment]
Hey I would like to work on it.

**Comment by Navaneeth-pk** [comment]
Resolved.

**Comment by Sanidhya0077** [comment]
Hi @Navaneeth-pk was it due to the link got expired?
