### ISSUE TITLE
TJDB: Ability to edit existing column on dashboard

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#7709]
### Is your proposal related to a problem?
Currently there is no means to edit existing column. We'd need to give users capability to:
-  Rename column name
- Update the constraints
- Add edit column option on column header dropdown

PRD: https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-14476

### Describe the solution you'd like

<img width="1107" alt="image" src="https://github.com/ToolJet/ToolJet/assets/11629675/965ff00b-bc8a-4a55-bc6c-c0e5b8f1e7ac">

 * data type can't be editing post creation 
 * the copywriting for waiting to let ToolJet update links is not required

**Comment by HeetVekariya** [comment]
I would like to work on this issue
