### ISSUE TITLE
Pressing enter/return key should delete the component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7711]
### What is the expected behaviour?

When the confirmation modal for deleting the component pops up, the user should be able to provide input `Yes` by pressing the `Enter/return` key or `Cancel` using the `Esc` key. 

### What is the current behaviour?

Currently, the user will have to use the mouse click to select the option.

### How to reproduce the issue?

1. Drag a component onto the canvas
2. Use `delete` button (windows/linux) or `back` (mac) to delete the component
3. The confirmation modal will popup
4. Try pressing `Enter` or `return` 

### Screenshots or Screencast
![Screenshot 2023-10-09 at 4 57 35 PM](https://github.com/ToolJet/ToolJet/assets/25361949/df52b9a5-aab4-4e0e-b540-a5129b6fd059)

**Comment by NotTheRightGuy** [comment]
I can help with this. Can you assign this issue to me?

**Comment by joanjeremiah** [comment]
I would like to work on this issue, please assign this to me
Thanks

**Comment by ShrutiAngane** [comment]
Hello @withshubh the issue looks like something that I would love to work on. Can you please assign this to me ?

**Comment by NithinSravan** [comment]
Hi @withshubh I would love take up this task if it's still available. Can you please assign it to me?

**Comment by tejakummarikuntla** [comment]
Hey everyone, thanks for your interest. Assigned the issue to @HeetVekariya.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by NotTheRightGuy** [comment]
Thanks, @tejakummarikuntla I will start working on it.
