### ISSUE TITLE
Rename Widget to Component in the confirmation modal of deleting component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7714]
### What is the expected behaviour?

On deleting the component, the confirmation modal should have the following text:
```
Component will be deleted, do you want to continue?
```

### What is the current behaviour?

On deleting the component, a confirmation modal pops up with the following text:
```
Widget will be deleted, do you want to continue?
```

### How to reproduce the issue?

1. Drag a component onto the canvas
2. Use `delete` button (windows/linux) or `back` (mac) to delete the component
3. The confirmation modal will popup
4. Check the text on modal 

### Screenshots or Screencast
![Screenshot 2023-10-09 at 4 57 35 PM](https://github.com/ToolJet/ToolJet/assets/25361949/df52b9a5-aab4-4e0e-b540-a5129b6fd059)

**Comment by HeetVekariya** [comment]
I would like to work on this issue,@withshubh please assign to me

**Comment by NotTheRightGuy** [comment]
Hey, I think I can help with this. Can you assign this to me.

**Comment by HarshitVashisht11** [comment]
i can help with this issue please assign this to me

**Comment by nikunjgupta609** [comment]
@withshubh 
/assign
Please assign me with this good first issue, i am interested in this .

**Comment by Atul72** [comment]
Please assign me the issue. This will of much help.

**Comment by StellarLogic** [comment]
I love to work on this. can you please assign it to me

**Comment by IftequarIffu** [comment]
Would like to work on this. Can you please assign it to me?

**Comment by withshubh** [comment]
Hey @HeetVekariya 👋 
Thanks for showing interest in contributing to ToolJet. Assigned this issue to you.

**Comment by withshubh** [comment]
@NotTheRightGuy @HarshitVashisht11 @nikunjgupta609 @Atul72 @StellarLogic @IftequarIffu 
Thanks, everyone for showing interest in contributing to ToolJet.
We assign issues on a first come first served basis. 
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by HeetVekariya** [comment]
@withshubh Thank you for assigning me the issue, I have created the PR, please review it.

**Comment by HeetVekariya** [comment]
@withshubh I think you missed to assign me the issue, though i have created the PR.

**Comment by HeetVekariya** [comment]
@tejakummarikuntla Sorry for my mistake, I have made another PR.
