### ISSUE TITLE
Change labels to sentence case for Date Picker Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7739]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

⚠️ The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values   | Expected Values  |
| :--------------- | :--------------- |
| Default Value   | Default value    |
| Border Radius    | Border radius    |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object that has the **Date Picker** component name in the name key, and make changes only in that particular object.  
   **For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**

```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```

2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by ValkonX33** [comment]
please assign me this

**Comment by parveshsaini** [comment]
Can you please assign it to me?

**Comment by tejakummarikuntla** [comment]
Hello everyone,
We appreciate your interest in contributing to ToolJet. Let's wait to welcome first time contributors to our project. Please note that we may not assign issues to those who already have an issue assigned. We thank you for your understanding and look forward to your valuable contributions.

**Comment by nishitxmehta** [comment]
Hi @tejakummarikuntla, can you please assign this issue to me! I haven't been assigned any issue.

**Comment by yogesh123gn** [comment]
Hey @tejakummarikuntla, I would like to work on this issue, Can you please assign it to me..?

**Comment by DhairyaMajmudar** [comment]
@tejakummarikuntla @subhajit20 pls. assign this issue to me. It will be mine first contribution to this repo.

**Comment by tejakummarikuntla** [comment]
Hey everyone, thank you for your interest. Assigned the issue to @yogesh123gn.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by tejakummarikuntla** [comment]
Hey @yogesh123gn, were you able to progress with the issue? In case you got stuck with set-up issues, you may take reference to some similar issues that have approved PRs.

**Comment by yogesh123gn** [comment]
Hey @tejakummarikuntla , the issue you have mentioned seems to be fixed in current repository. Can you check for the same please..?

**Comment by tejakummarikuntla** [comment]
Thanks for sharing it @yogesh123gn.
