### ISSUE TITLE
Change labels to sentence case for Container Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7742]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

⚠️ The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values   | Expected Values  |
| :--------------- | :--------------- |
| Loading State    | Loading state    |
| Background Color | Background color |
| Border Radius    | Border radius    |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object that has the **Container** component name in the name key, and make changes only in that particular object.  
   **For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**

```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```

2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by ValkonX33** [comment]
please assign me this

**Comment by steve-aldrin** [comment]
@withshubh i just reproduced the issue, i believe changing the string values of the labels in title case to sentence case (in both en.json and widgetConfig,js)  will fix the issue. If you are willing you can assign me this issue, i will make a pr once the change is done.

**Comment by ValkonX33** [comment]
> please assign me this

@shubh22

**Comment by ValkonX33** [comment]
> Hey @steve-aldrin, Just checking in on the status of the assigned issue. Any chance you could give us a quick update on your progress? If things are a bit stuck, feel free to join our [Slack](https://tooljet.com/slack) for help. Free to let me know if you need to get this unassigned.

if he's not responding, will you please assign this to me @tejakummarikuntla

**Comment by steve-aldrin** [comment]
> Hey @steve-aldrin, Just checking in on the status of the assigned issue. Any chance you could give us a quick update on your progress? If things are a bit stuck, feel free to join our [Slack](https://tooljet.com/slack) for help. Free to let me know if you need to get this unassigned.

Hey thank you for checking up, I am sorry I was caught up in an emergency, I have already joined the slack channel, there are no issues with the dev environment, I'll be making a pr by tommrow night. I hope that's fine thank you.

**Comment by tejakummarikuntla** [comment]
Sure, @steve-aldrin. Will look forward for your PR.
