### ISSUE TITLE
Change labels to sentence case for Number Input Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7746]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

⚠️ The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values   | Expected Values  |
| :--------------- | :--------------- |
| Default Value | Default value |
| Loading State | Loading state |
| Border Radius | Border radius |
| Background Color | Background color |
| Border Color  | Border color   |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object that has the **Number Input** component name in the name key, and make changes only in that particular object.  
   **For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**

```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```

2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by vishalkhoje** [comment]
I am interested to work on this, can you please assign this to me

**Comment by alammoiz** [comment]
can you please assign it to me? I don't have any ticket right now

**Comment by withshubh** [comment]
Hey @vishalkhoje & @alammoiz 
As a valued contributor, I appreciate your interest in picking this up, since this issue holds the https://github.com/ToolJet/ToolJet/labels/good%20first%20issue label, Let's welcome first-time contributors to the project; thank you for your understanding and I look forward for your continuous involvement in the project.

**Comment by nishitxmehta** [comment]
Hi @withshubh , can you please assign this issue to me! I haven't been assigned any issue.

**Comment by vishalkhoje** [comment]
Hi @withshubh 

I would like to kindly mention that I have faced a challenge in finding tasks for Pull Requests (PRs) due to the prevalence of "good first issue" labels on most new tasks. I'm curious about how I can access a wider variety of tasks in such a scenario.

**Comment by Bhushan1019** [comment]
Please assign me this issue I am a first time contributer

**Comment by tejakummarikuntla** [comment]
Hey @Bhushan1019, could you please raise the PR towards `develop` branch
