### ISSUE TITLE
Change labels to sentence case for Range Picker Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7751]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

⚠️ The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values   | Expected Values  |
| :--------------- | :--------------- |
| Border Radius    | Border radius    |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object that has the **Range Picker** component name in the name key, and make changes only in that particular object.  
   **For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**

```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```

2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by VivekGuruduttK28** [comment]
Hi @withshubh 
I would love to work on this issue. Can it be assigned to me?

**Comment by parveshsaini** [comment]
Hey! Please assign it to me

**Comment by withshubh** [comment]
Hey everyone, thank you for your interest. Assigned the issue to @VivekGuruduttK28 
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by VivekGuruduttK28** [comment]
Thank you assigning me this @withshubh. Starting to work on it.

**Comment by VivekGuruduttK28** [comment]
hey @withshubh 
I checked the code and found that the required changes are already made.
![image](https://github.com/ToolJet/ToolJet/assets/127002789/28d72d38-edb9-49a6-bed8-39ba04ed4eaa)
Please check this and let me know.

**Comment by tejakummarikuntla** [comment]
Hey @VivekGuruduttK28. Thanks for bringing this up.
Closing this issue since there are no further changes required on this.

@VivekGuruduttK28 , if you're interested, we can assign you #7756. If yes, please comment on your interest in the issue.

**Comment by VivekGuruduttK28** [comment]
Hi @tejakummarikuntla ,
I would love to work on the issue #7756

**Comment by tejakummarikuntla** [comment]
Great, please comment on your interest in the issue to assign.

**Comment by VivekGuruduttK28** [comment]
Hi @tejakummarikuntla ,
Sorry for the ambiguity. Can this issue be assigned to me?

**Comment by tejakummarikuntla** [comment]
Hi @VivekGuruduttK28 , I've assigned you the issue: https://github.com/ToolJet/ToolJet/issues/7756
I was referring you to comment your interest in the issue https://github.com/ToolJet/ToolJet/issues/7756
