### ISSUE TITLE
Change labels to sentence case for Multiselect Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7753]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

⚠️ The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values   | Expected Values  |
| :--------------- | :--------------- |
|  Default Value    |  Default value |
| Enable select All option | Enable select all option |
| Border Radius    | Border radius    |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object that has the **Multiselect** component name in the name key, and make changes only in that particular object.  
   **For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**

```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```

2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by tfalcongreen** [comment]
Hi there - Can you please assign this issue to me?

**Comment by HarshitVashisht11** [comment]
Can you assign this issue to me , I am already familiar with the code

**Comment by withshubh** [comment]
Hey everyone, thank you for your interest. Assigned the issue to @tfalcongreen 
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by tejakummarikuntla** [comment]
Hey @tfalcongreen. Just checking in on the status of the assigned issue. Any chance you could give us a quick update on your progress? If things are a bit stuck, feel free to join our [Slack](https://tooljet.com/slack) for help. Free to let me know if you need to get this unassigned.

**Comment by Rohxn16** [comment]
I wanna work on this issue. It says up for grabs so Im'ma submit a PR.

**Comment by Rohxn16** [comment]
@tejakummarikuntla I had already submitted a PR. Can u please review that one?

**Comment by Rohxn16** [comment]
![Screenshot from 2023-10-19 00-41-29](https://github.com/ToolJet/ToolJet/assets/142105763/7380448f-af28-4a9b-8330-1b3944649eb7)
Should I change "Select Options" to "Select options" ? it is under the Multiselect component
