### ISSUE TITLE
Change labels to sentence case for File Picker Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7756]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

⚠️ The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values   | Expected Values  |
| :--------------- | :--------------- |
| Instruction Text   | Instruction text      |
| Use Drop zone | Use drop zone |
| Use File Picker | Use file picker |
| Border Radius    | Border radius    |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object that has the **File Picker** component name in the name key, and make changes only in that particular object.  
   **For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**

```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```

2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by verma-divyanshu-git** [comment]
Hey @withshubh 
I'd love to work on this issue.

**Comment by saikiranpatil** [comment]
i would like work on this issue, please assign this to me
i have made these changes
![image](https://github.com/ToolJet/ToolJet/assets/84263946/4f66df64-4110-4251-bb2e-9cf9d564c4ec)

**Comment by withshubh** [comment]
Hey @saikiranpatil @verma-divyanshu-git @parveshsaini 
Issues are already assigned to you all.
I appreciate your interest in picking this up, since this issue holds the https://github.com/ToolJet/ToolJet/labels/good%20first%20issue label, Let's welcome first-time contributors to the project; thank you for your understanding and I look forward for your continuous involvement in the project.

**Comment by jatingodnani** [comment]
@withshubh assign me this issue

**Comment by jatingodnani** [comment]
@withshubh assign me this issue

**Comment by Damon248** [comment]
Hey, @withshubh I would like to work on this issue, can you please assign me this task?

**Comment by tejakummarikuntla** [comment]
Hey @Damon248, just found your PR #7537. It was left out with no update.

**Comment by jatingodnani** [comment]
@tejakummarikuntla can you assign me thia issue?

**Comment by tejakummarikuntla** [comment]
Thank you for your interest, @jatingodnani. As this issue holds the tag `good first issue` let's wait to welcome new contributors to the project, I hope you understand.

**Comment by jatingodnani** [comment]
@tejakummarikuntla add medium level issue

**Comment by tejakummarikuntla** [comment]
Assigned the issue to @VivekGuruduttK28

**Comment by VivekGuruduttK28** [comment]
Hi @tejakummarikuntla,
Can this issue be assigned to me? I'm here from issue #7751

**Comment by Vivek-GuptaXCode** [comment]
greeting maintainers, i would like to know if this issue open to contribute on, if so please assign it to me.thanks in advance

**Comment by VivekGuruduttK28** [comment]
Thank you for assigning me this issue @tejakummarikuntla. Starting to work on it

**Comment by VivekGuruduttK28** [comment]
Hi @tejakummarikuntla,
I have made the required changes in File Picker component. Raising the PR.
