### ISSUE TITLE
Change labels to sentence case for Image Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7773]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

⚠️ The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values   | Expected Values  |
| :--------------- | :--------------- |
| Loading State    | Loading state    |
| Background Color | Background color |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object that has the **Image** component name in the name key, and make changes only in that particular object.  
   **For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**

```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```

2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by Gourav2609** [comment]
@withshubh please assign this to me

**Comment by withshubh** [comment]
Hey everyone, thank you for your interest. Assigned the issue to @RajuGangitla  
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by tejakummarikuntla** [comment]
Hey @RajuGangitla. Just checking in on the status of the assigned issue. Any chance you could give us a quick update on your progress? If things are a bit stuck, feel free to join our [Slack](https://tooljet.com/slack) for help. Free to let me know if you need to get this unassigned.

**Comment by RajuGangitla** [comment]
@tejakummarikuntla I'm facing difficulties in setup the project locally

**Comment by tejakummarikuntla** [comment]
Hey @RajuGangitla, please let us know how we can help you in Slack.

**Comment by anshuman-rai-27** [comment]
@withshubh can you plz assign this issue to me as i have gone through the issue and already solved it , i can raise the PR if you assign me the issue .

**Comment by tejakummarikuntla** [comment]
Hey @RajuGangitla, I'm sorry but we have to unassing the issue.

Thanks for your interest @anshuman-rai-27, Assigned the issue to you.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by hemantmm** [comment]
Hi, @withshubh if @anshuman-rai-27 is not working on this issue, then I can work on this?

**Comment by hemantmm** [comment]
Hi @tejakummarikuntla if @anshuman-rai-27 is not working on this issue, then I can work on this?

**Comment by Just-A-Pixel** [comment]
Hello! Is this issue assigned yet? I am interested in the issue.

**Comment by withshubh** [comment]
Hey @Just-A-Pixel - Assigned this to you.
