### ISSUE TITLE
Change labels to sentence case for Statistics component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7784]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values       | Expected Values       |
| :------------------- | :-------------------- |
| Loading State        | Loading state         |
| Primary Label Colour | Primary label colour  |
| Primary Text Colour        | Primary text colour         |
| Secondary Label Colour           | Secondary label colour            |
| Secondary Text Colour | Secondary text colour |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object which has the related component name in the name key, and make changes only in that particular object.  
**For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**
```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```
2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by ShatilKhan** [comment]
Please assign me these sentence case issues.
I have recently made 3 PRs for Novu docs & currently ranked in Top 10 in Hacksquad
Delivering these issues will be a great opportunity!

**Comment by AtulMinz** [comment]
Can you please assign me this issue?

**Comment by alammoiz** [comment]
can you please assign it to me? I don't have any tickte right now

**Comment by tejakummarikuntla** [comment]
Hello everyone,
We appreciate your interest in contributing to ToolJet. Let's wait to welcome first time contributors to our project. Please note that we may not assign issues to those who already have an issue assigned. We thank you for your understanding and look forward to your valuable contributions.

**Comment by ShatilKhan** [comment]
Hey @tejakummarikuntla , I've made a PR for my previous assigned issue. Can I work on this one for now?

**Comment by SanchitMahajan236** [comment]
Hey!! I would love to contribute to this issue. can you please assign it to me ??

**Comment by lone-wolf45** [comment]
@tejakummarikuntla I am new to open source contributions and I just found this precious repository. This is my first time contributing to ToolJet. 

I would love to work on this. Please assign me this one.

**Comment by VivekGuruduttK28** [comment]
Hi @tejakummarikuntla 
I  would love to work on this issue. Can it be assigned to me?

**Comment by tejakummarikuntla** [comment]
Hey everyone, thank you for your interest. Assigned the issue to @lone-wolf45.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by Praneeth1136** [comment]
hey @tejakummarikuntla, I would love to contribute on this one, if you assign this will be my first
