### ISSUE TITLE
Container only has light theme

### ISSUE THREAD

**Issue by masteradit** [ToolJet/ToolJet#779]
### Version Information
Latest (8c4cb668658b927f431338cff9aa5a89c9a02c97)

### Environment
Self-hosted on Heroku

### What is the expected behaviour?
When dark theme is used, the container should also switch to dark colour.

### What is the current behaviour?
The container remains in light theme even after switching to dark theme.

### How to reproduce the issue?

1. Switch to a dark theme
2. Add container to the canvas

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/39951503/133879070-499f492f-0f6e-449a-9760-712c223c4d80.png)

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by AB-Jeet** [comment]
Can you assign it to me ?

**Comment by Navaneeth-pk** [comment]
@AB-Jeet Sure, thanks for contributing.

**Comment by savannahvaith** [comment]
Hi there, would I be able to pick this up?

**Comment by Navaneeth-pk** [comment]
Sure, assigning to you @savannahvaith

**Comment by ivelin-web** [comment]
What is the status of this issue? Can I try to fix and make PR?
