### ISSUE TITLE
Change labels to sentence case for PDF component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7792]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values       | Expected Values       |
| :------------------- | :-------------------- |
| Show the Download        | Show the download         |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object which has the related component name in the name key, and make changes only in that particular object.  
**For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**
```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```
2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by imsoumik03** [comment]
hey @withshubh can you please assign me this issue?

**Comment by adarshmalviya12** [comment]
I can work on this

**Comment by MrLEGENDx10** [comment]
assign me

**Comment by tejakummarikuntla** [comment]
Hey everyone, thank you for your interest. Assigned the issue to @imsoumik03.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by Damon248** [comment]
Hello @tejakummarikuntla! Can I work on this task or any other similar issue like this?

**Comment by SujalGupta244** [comment]
hey @tejakummarikuntla would you please assign me this issue

**Comment by karan-rathod-316** [comment]
Hi @Damon248, assigning this to you.

Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by karan-rathod-316** [comment]
@Damon248 Can you link the PR to this issue?

**Comment by karan-rathod-316** [comment]
Closing the issue as the related PR is merged.
