### ISSUE TITLE
Change labels to sentence case for Form component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7799]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values       | Expected Values       |
| :------------------- | :-------------------- |
| Button To Submit Form        | Button to submit form         |
| Loading State | Loading state  |
| Background Color | Background color |
| Border Radius        | Border radius         |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object which has the related component name in the name key, and make changes only in that particular object.  
**For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**
```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```
2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by ronisarkarexe** [comment]
@withshubh please assign me, I like to work on this issue.

**Comment by Gourav2609** [comment]
Please assign this issue to me @withshubh

**Comment by ShivankK26** [comment]
has this been solved?

**Comment by withshubh** [comment]
Hey @ShivankK26 
Are you still interested in picking up this issue??
For additional help, you can refer to the reviewers' comments on this PR https://github.com/ToolJet/ToolJet/pull/7843

**Comment by jigarBorde** [comment]
Hii @withshubh 
can you assign this issue to me, if it is still open.

**Comment by Sufiyan-dev** [comment]
@withshubh @tejakummarikuntla waiting for your approval to merge the request

**Comment by karan-rathod-316** [comment]
@Sufiyan-dev Can you please link your PR to this issue?

**Comment by karan-rathod-316** [comment]
Fixed: https://github.com/ToolJet/ToolJet/pull/8465
