### ISSUE TITLE
Badge and Tags are editable even if set as not editable

### ISSUE THREAD

**Issue by masteradit** [ToolJet/ToolJet#780]
### Version Information
Lastest (8c4cb668658b927f431338cff9aa5a89c9a02c97)

### Environment
Self-hosted on Heroku

### What is the expected behaviour?
If "Make editable" is off, then badges and tags should not be editable.

### What is the current behaviour?
ToolJet allows the field to be edited even if "Make editable" is off.

### How to reproduce the issue?

1. Add a table
2. Add a column with badge or tags and do not enable "Make editable"

**Comment by arpitnath** [comment]
picking this up
