### ISSUE TITLE
Fix the `Edit email address` button after signup

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#7802]
### What is the expected behaviour?

The width and height of the `Edit email address` button should be the same as the `Resent verification email` button above it. 

### What is the current behaviour?

Currently, the height and width are not the same as the button above it.

### How to reproduce the issue?

1. Enter the details on the [sign-up page](https://www.tooljet.com/signup). Note: You should sign up for the first time using the email.
2.  Click on `Get started for free` button
3. On the next page, observe the `Edit email address` button.

### Screenshots or Screencast

![ToolJet-Dashboard](https://github.com/ToolJet/ToolJet/assets/25361949/935df27d-d86e-4b5d-8b8c-634772307a43)

**Comment by ronisarkarexe** [comment]
@withshubh can you please assign me this issue? I want to work on this issue.

**Comment by Virtual4087** [comment]
you can assign me this issue

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi i would like to work on this issue plz assign it to me

**Comment by aryankshl** [comment]
hey @withshubh can you please assign this to me?

**Comment by Devvrat1010** [comment]
hello @withshubh can you please assign this task to me ?

**Comment by GeeekySouro003** [comment]
Hello sir i will be very grateful if i get the oppurtunity to work on this.Please assign me on this.

**Comment by aastha44ma** [comment]
Hello Sir, Can you please assign this issue to me ? I will give my best to provide quality work.

**Comment by AryanSaxenaa** [comment]
Hi @withshubh ,Please assign this issue to me

**Comment by akshayw1** [comment]
Hello @withshubh, Please assign me the issue, My way to deal with the task, will be, Initially I will go through contributing guide, and will understand the require stuff, Remaining the task, Need to Just apply the Styled CSS as of above button, Which can be easily done by me. Looking forward to work on these issue.

**Comment by Rahulkottak** [comment]
![Screenshot 2023-10-12 150923](https://github.com/ToolJet/ToolJet/assets/114240026/684d9f9b-a642-4c6d-9587-a850b4d94711)

I'm getting this type of interface.. can u plz confirm the issue once again. @withshubh

**Comment by MrLEGENDx10** [comment]
assign me

**Comment by sohalkumar** [comment]
@withshubh The issue only occurred when we tried to access a protected route (I tried accessing `/dashboard`) without signing in, which redirects to the login/signup page.
I have created a PR that should solve this issue.

**Comment by thisIsSrijan** [comment]
It seems like this bug appears only after a specific screen width (>1200px) and only appears on https://app.tooljet.com/signup , as @BhaveshG-22 mentioned. 
![WhatsApp Image 2023-10-14 at 10 04 25_fe59fd59](https://github.com/ToolJet/ToolJet/assets/113245185/c8ad1d90-60da-48ea-abc0-09c97cd87444)

And I think this is what it should look like: 
![image](https://github.com/ToolJet/ToolJet/assets/113245185/d39ad57f-0ee8-4132-9087-4e0d81fbbfd3)

**Comment by mixamum** [comment]
Id like to work on this issue.

**Comment by MohdAyat** [comment]
@withshubh i went through ur link but the issue wasn't there ,when i tried to create an acc through nav bar then i saw the issue and this bug appears only on big screen laptops like 1440px or more.

**Comment by tejash023** [comment]
@withshubh Can you please assign this to me? I am willing to work on this issue

**Comment by DhairyaMajmudar** [comment]
@withshubh would love to work on this issue pls. assign it to me .

**Comment by pabitra0011** [comment]
@withshubh Please assign me this issue.

**Comment by Vivek-GuptaXCode** [comment]
greeting maintainers,i would like to work on this issue if possible.Thanks in advance

**Comment by mdrizwanfk** [comment]
I would like to work on this, please assign! Thanks!

**Comment by sudip57** [comment]
I would like to work on this issue.

**Comment by Aarav238** [comment]
Hey @withshubh , I would like to work on this issue. I am new to this organization and I think it would be a beginner friendly issue to start with.
Please assign this to me.

**Comment by withshubh** [comment]
Hey @Aarav238 
Are you still interested in picking up the issue?

**Comment by Aarav238** [comment]
Yeah @withshubh !!

**Comment by Aarav238** [comment]
Pleas assign this to me @withshubh

**Comment by withshubh** [comment]
Assigned to @Aarav238

**Comment by Aarav238** [comment]
Thanks!

**Comment by Aarav238** [comment]
Hey @withshubh , i think this issue is already resolved.

**Comment by karan-rathod-316** [comment]
Closing this as it is already resolved.
