### ISSUE TITLE
Dynamic circular border for scroll-to-top

### ISSUE THREAD

**Issue by SrishtiSonam** [ToolJet/ToolJet#7813]
### Is your proposal related to a problem?

(Describe your proposed solution here.)

Now the user can easily move to the "Book a demo" and "Try for free" buttons in just one click after scrolling down to the footer of the page.

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
Yes i would be pleased to submit a PR if a change in given
Could you please consider assigning me to this task as part of Hacktoberfest if it meets your requirements for this project?

**Comment by heysagnik** [comment]
I would love to work for this issue.

**Comment by withshubh** [comment]
Hey @SrishtiSonam 
Thanks for creating this issue.
We have to close this issue since the website is not the part of this repository.
