### ISSUE TITLE
Table Search does not work

### ISSUE THREAD

**Issue by masteradit** [ToolJet/ToolJet#782]
### Version Information
Lastest (8c4cb668658b927f431338cff9aa5a89c9a02c97)

### Environment
Self-hosted on Heroku

### What is the current behaviour?
Table Search does not work with Firestore Datasource and server side search off

**Comment by arpitnath** [comment]
picking this up

**Comment by arpitnath** [comment]
### UPDATE
**What is the current behaviour?**

Table search is not functional
