### ISSUE TITLE
The column pop-over component is being obscured by the query detail panel

### ISSUE THREAD

**Issue by tuutoo** [ToolJet/ToolJet#7824]
### Version Information
v2.19.2
### Environment

Docker

### What is the expected behaviour?

The column pop-over widget should in front of query detail pannel.

### How to reproduce the issue?

1. Add a table widget to the main panel
2. Click the table widget
3. Click the column name on the right

### Screenshots or Screencast

![image](https://github.com/ToolJet/ToolJet/assets/9068314/a6b85979-8fe6-4426-8a8a-c3b0bbd54fe2)

**Comment by Shreyas0410** [comment]
Hey I would like to work on this issue.

**Comment by saikiranpatil** [comment]
can i work on this issue?

**Comment by shubh22** [comment]
This has been fixed. Closing the issue.
