### ISSUE TITLE
Column header positioning is inconsistent while dragging the header to reorder its position in the table

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#7855]
### Version Information
v2.20.1
### Environment
Development

### What is the expected behaviour?
When we try to drag the column header to re-order the headers, it should positioned correctly, that is from the source that needs to be re-ordered.

### What is the current behaviour?
When we try to drag a particular header to re-order its position, the header is not positioned consistently.

### How to reproduce the issue?

1. Drag a table in the canvas
2. Select any column header that needs to be re-ordered and drag it, you can observe, its starting point is inconsistent.

### Screenshots or Screencast
[My app 1697187833826 - ToolJet - 13 October 2023 - Watch Video](https://www.loom.com/share/f276334d5e224ec38834d6fb409289be)

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by iamsid0908** [comment]
@manishkushare  hey, can you please help me to setup this project locally... 
![error](https://github.com/ToolJet/ToolJet/assets/86674873/e361ee45-5a29-4667-96e5-515323f40e65)
