### ISSUE TITLE
Empty folder state and search bar is not appearing for newly added folder

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#7865]
### What is the expected behaviour?
The empty folder notification and search bar should be displayed on the screen to maintain the consistency for the folder structure.

### What is the current behaviour?
Empty state is not displayed if there is no app created by the user.

### How to reproduce the issue?

1. Create a new workpsace
2. Create new folder and verify if empty state is present or not
3. Create new app and navigate to the folder, empty state will appear

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/89f0d98a-537a-4fd4-86ba-7dd63f0bfb5d

### solution
The folder with no apps should ideally display as shown
![image](https://github.com/ToolJet/ToolJet/assets/34749692/9cd55d9a-37a0-44ae-af69-5e771dcafa09)

**Comment by theavitw** [comment]
I should try it out
@dishag18

**Comment by arpitnath** [comment]
cc: @thehacklady

**Comment by tejakummarikuntla** [comment]
Hey @theavitw, would you like to take this up?

**Comment by theavitw** [comment]
Definitely

**Comment by tejakummarikuntla** [comment]
Awesome, thank you for your interest. Assigned the issue to you @theavitw.
Feel free to join our community on [Slack](https://tooljet.com/slack). If you need any help related to issues/contributions, please post in the #contributors channel.

**Comment by theavitw** [comment]
hi @thehacklady ,
Is this project only for mac os ??

**Comment by anoopw3bdev** [comment]
@thehacklady @arpitnath  can you assign this to me, I would like to add a fix

**Comment by Just-A-Pixel** [comment]
Looks like this issue is still open. May I be assigned to it?
