### ISSUE TITLE
User invited with role 'Viewer or Developer' should not be able to update his or other's roles after accepting the invitation.

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#788]
URL: https://app.tooljet.io/users

**Steps to recreate**

1. Login with Admin user.
2. Invite a user with a viewer/ developer role.
3. Accept invitation from the email link.

**Expected:** 
On accepting the invitation user is taken to the user's page. Here the user should not be able to update his or other's roles.

**Actual:**
Able to update self role from Viewer/Developer to Admin. Also able to update primary user's role from Admin to Viewer/Developer. 

In the screenshot below you can see activities for Primary email(Admin): mohinidahiya4@gmail.com and secondary email(To whom the invitation was sent): mdahiya410@gmail.com

<img width="757" alt="Screenshot 2021-09-20 at 11 15 43 AM" src="https://user-images.githubusercontent.com/5313625/133977978-886c540b-0181-4840-a7bc-c9da4aac8602.png">
<img width="1787" alt="Screenshot 2021-09-20 at 11 20 11 AM" src="https://user-images.githubusercontent.com/5313625/133977993-4c84c404-0029-41fe-a6ea-dec754b35de3.png">
<img width="1792" alt="Screenshot 2021-09-20 at 11 21 45 AM" src="https://user-images.githubusercontent.com/5313625/133977995-a9844969-4ab6-4f73-afda-c68fadaa321e.png">
<img width="1792" alt="Screenshot 2021-09-20 at 11 24 13 AM" src="https://user-images.githubusercontent.com/5313625/133977998-e18ac18c-e3ae-4635-b85b-6251c982cd54.png">

**Comment by akhilgkrishnan** [comment]
@mohinid can you confirm this issue once again.

**Comment by akhilgkrishnan** [comment]
@sherfin94 I think she tried with the same user account (admin). So that she could be able to update the role. 
https://www.loom.com/share/1be7c56d1de74ddfa6103e00cdb0c83c

**Comment by akhilgkrishnan** [comment]
https://www.loom.com/share/a19880a0e2bb48fda024a203e4d070c7

Unable to reproduce.

**Comment by mohinid** [comment]
@Navaneeth-pk  please close this issue.
