### ISSUE TITLE
Add hover effect to subcategories on navbar

### ISSUE THREAD

**Issue by singodiyashubham87** [ToolJet/ToolJet#7882]
### Is your proposal related to a problem?

Nope, It's an enhancement

### Describe the solution you'd like

I want to add hover effect to highlight the category which is hovered upon 

### If the feature is approved, would you be willing to submit a PR?
I would love to resolve this issue.

### Screenshot
![image](https://github.com/ToolJet/ToolJet/assets/93720428/e4c1582d-2777-45b9-b5bb-035020ca3823)

**Comment by deanurag** [comment]
I would like to work on this issue.

**Comment by shivam200446** [comment]
I would like to work on this issue please assign me.

**Comment by Surieya** [comment]
i will work on it .. @singodiyashubham87

**Comment by Surieya** [comment]
kindly review my PR @singodiyashubham87

**Comment by Damon248** [comment]
Hello @singodiyashubham87! I would like to work on this issue. Can you please assign me this task?

**Comment by DhairyaMajmudar** [comment]
@withshubh @singodiyashubham87 I would love to contribute to this issue. pls. assign this to me .

**Comment by thehacklady** [comment]
Hey contributors, unfortunately we won't be able to pick this up as this repo is not for issues related to tooljet.com website.
