### ISSUE TITLE
Unable to access user invitation link on Local

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#789]
Getting below error on clicking the invitation link. Please check below SS.

<img width="1791" alt="Screenshot 2021-09-20 at 2 43 26 PM" src="https://user-images.githubusercontent.com/5313625/133979937-8be44541-d708-4c40-88ca-3f39a5e405cd.png">
<img width="1786" alt="Screenshot 2021-09-20 at 2 43 42 PM" src="https://user-images.githubusercontent.com/5313625/133979944-4fa23e3f-93be-4a2b-ab9d-e7e8ab4b88a9.png">
<img width="1789" alt="Screenshot 2021-09-20 at 2 43 58 PM" src="https://user-images.githubusercontent.com/5313625/133979949-aead72d4-b92f-4e94-92cf-1ec7f12058a1.png">

**Comment by akhilgkrishnan** [comment]
@Navaneeth-pk picking up this issue
