### ISSUE TITLE
Update the Twitter Logo to New Logo ( X ).

### ISSUE THREAD

**Issue by niranjan-kurhade** [ToolJet/ToolJet#7907]
Update the Twitter Logo to the latest Logo ( X )

### Describe the solution you'd like

As we know Twitter's name and Logo have been changed. So I would like to change the Logo to X on the docs page of Tooljet. 

![image](https://github.com/ToolJet/ToolJet/assets/97905637/f72129cb-c8d4-4b01-aa52-38297b45462c)

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by niranjan-kurhade** [comment]
Please assign this issue to me.

**Comment by ValkonX33** [comment]
i can work on this

**Comment by omkarvilasmote** [comment]
Can you assign me this work i will give me 100% and add this logo in very low time

**Comment by withshubh** [comment]
Hey @niranjan-kurhade 
Thanks for creating the issue.


Assigned the issue to @niranjan-kurhade since he mentioned he is willing to work on it.
