### ISSUE TITLE
Pin icon on inspector and Error coming white in dark mode and is not readable. 

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#791]
Pin icon on 'Inspector' and 'Error' tabs coming white in dark mode and is not readable(As shown in SS below). Should be black.

<img width="457" alt="Screenshot 2021-09-20 at 11 07 19 AM" src="https://user-images.githubusercontent.com/5313625/133981100-87249201-0b84-45d4-ad60-9eb40b6bd2c0.png">
<img width="483" alt="Screenshot 2021-09-20 at 11 11 07 AM" src="https://user-images.githubusercontent.com/5313625/133981103-0287bdf1-919d-4f70-8040-f5b9d7e3caf7.png">

**Comment by akhilgkrishnan** [comment]
@Navaneeth-pk picking up this issue

**Comment by akhilgkrishnan** [comment]
@mohinid, I found the same issue is happening in the sidebar icon as well. Can you please confirm this?

**Comment by mohinid** [comment]
> @mohinid, I found the same issue is happening in the sidebar icon as well. Can you please confirm this?

Can you please specify where exactly?

**Comment by Navaneeth-pk** [comment]
That's also out of scope for this issue. As I mentioned on the PR (https://github.com/ToolJet/ToolJet/pull/802#issuecomment-923733029), someone is working on it. 

@akhilgkrishnan
