### ISSUE TITLE
Invitation URL in email should be clickable.

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#795]
The invitation URL in the email should be clickable(hyperlink). It’s plain text for now.

<img width="757" alt="Screenshot 2021-09-20 at 11 15 43 AM" src="https://user-images.githubusercontent.com/5313625/133988020-2d8db5f2-bf46-406d-b954-6c4f606b2a2c.png">

**Comment by akhilgkrishnan** [comment]
I can take this

**Comment by Navaneeth-pk** [comment]
Assigned the issue to you. Thanks for contributing to ToolJet :) 
@akhilgkrishnan
