### ISSUE TITLE
Login fails with 502 Bad Gateway of the api-authenticate on fresh Docker install

### ISSUE THREAD

**Issue by smilebasti** [ToolJet/ToolJet#796]
### Version Information
latest
### Environment
Following the Docker Guide

### What is the expected behaviour?
Login to be successful

### What is the current behaviour?
The login page is not working. The domain.com/api/authenticate says 502 Bad Gateway.

### How to reproduce the issue?

1. Ubuntu 20.4.3 with official installation of the latest docker and docker-compose
2. I tried to connect to postgresql container running parallel. Tooljet didn't connect to it during npm run db:create.
3. Used then an external Postgresql and that worked. (I can see the user and a hashed password in the db)
4. Running behind a Nginx Reverse Proxy
5. Host in .env file is only using http://

### Please provide any traces or logs that could help here.
The Docker logs only show the failed connection attempts to the docker container database.

Any help would be appreciated. Not sure where to find any other logs? docker logs container-id doesn't show the Web login attempts

**Comment by Navaneeth-pk** [comment]
@akshaysasidrn can you please take a look at this issue?

**Comment by akshaysasidrn** [comment]
@smilebasti I think the backend server is failing to start. Should be some issue related to db connectivity.
Once you had used an external postgres and seeded the db, what does it show up on server logs? Do try restarting the server container once.

**Comment by smilebasti** [comment]
Thanks for the reply.

I just so that the container restarts every minute.

The logs only show the failed connection/ db:create attempts (as its running since yesterday it repeated the same thing pretty often)

The container also fails after a manual restart after minute

**Comment by akshaysasidrn** [comment]
Try to see if you can connect to the db from the same instance wherein you are running the container? 
This looks to be some configuration issue.

**Comment by smilebasti** [comment]
The issues that are in the logs are the same i saw when i was running the postgresql-contianer on the same machine. After i used an external DB i didn't see any issues and anything new in the logs.
The new DB has all the databases created. I also could see the user with a hashed password. The old db that didn't work is already deleted.

**Comment by smilebasti** [comment]
I just did a complete new installation with the external preexisting external DB and it works flawlessly. 

If you want to continue looking into this problem i can keep the old Tolljet VM running? Else you can close this ticket
