### ISSUE TITLE
Deprecate: Multiselect, badges, multiple badges and radio

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#8024]
### Is your proposal related to a problem?

We need to deprecate Multiselect, badges, multiple badges and radio from Table component as the problems they solve are already solved by either Select or Tags

### Describe the solution you'd like

Make it so, that these column types are only available in existing tables, and add the text `(Deprecated)` next to them in their displayed name.

This should only be done once `Select` and `Tags` are fully implemented.

**Comment by johnsoncherian** [comment]
Fixes in PR #8442
