### ISSUE TITLE
irrelevant link for "Star us on Github" Button

### ISSUE THREAD

**Issue by Srish-ty** [ToolJet/ToolJet#8040]
### What is the expected behaviour?

  The link "Star us on Github" should take users to the repository page.

### What is the current behaviour?

  Instead after clicking the link, It's opening the page of list of stargazers.

### How to reproduce the issue?

1. Open the frontend
2. Scroll down and click on "star us on Github"  button
3. It'll open the link in another tab

### Screenshots or Screencast

![Screenshot 2023-10-27 104629](https://github.com/ToolJet/ToolJet/assets/68679980/a30b9d8a-6008-4d85-a0e4-e03693264a7d)

### Any possible solutions?
Yes, this can be resolved by changing link url in frontend sourcecode

### If the bug is confirmed, would you be willing to submit a PR?
Yes, I'll be working on this. And will submit PR.

**Comment by Pranav2612000** [comment]
Looks like a simple fix. I'll like to work on this issue.

**Comment by Navaneeth-pk** [comment]
Website is not part of this repository.
