### ISSUE TITLE
[docs]: change "Twitter" to "𝕏 (Twitter)" in README.md Community Support Section

### ISSUE THREAD

**Issue by BandhiyaHardik** [ToolJet/ToolJet#8055]
### Summary

I Was reading README.md during that i noticed that Twitter badge is updated to new logo but in community support section it is written as Twitter.

Twitter new logo badge:
![image](https://github.com/ToolJet/ToolJet/assets/110784317/da17b763-d129-4af8-9827-b5ba7f559a0a)

Currently in Community Support section:
![image](https://github.com/ToolJet/ToolJet/assets/110784317/b458a5a7-1eb7-4cd7-855f-1db6ca07abaf)

Suggested change:
![image](https://github.com/ToolJet/ToolJet/assets/110784317/18e9c6d1-7fac-4700-bbb9-d8af9a93ecb6)

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://github.com/ToolJet/ToolJet/blob/develop/README.md

### Steps to reproduce the issue

1. Go to <a href='https://github.com/ToolJet/ToolJet'>ToolJet Repository</a>
2. In README.md look into Community Support Section.
3. Twitter is not updated to 𝕏 (Twitter)

### Additional Information

Twitter has undergone a name change and is now known as "𝕏" To ensure the repository accurately reflects this update, I'm opening this issue.

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by DevanshKyada27** [comment]
Hey can I work on this issue can you please assign me.
