### ISSUE TITLE
Tooljet database: In filter, unable to pass "not null" value for the "is" operation

### ISSUE THREAD

**Issue by Mekhla-Asopa** [ToolJet/ToolJet#8067]
### What is the expected behaviour?
In the filter condition, users can input a "not null" value as part of the "is" operation.

### What is the current behaviour?
Getting an error message, while entering the "not null" value for the "is" operation in the filter condition.

### How to reproduce the issue?
1. Login with the valid credentials 
2. Navigate to the tooljet database page
3. Create a table with more rows and columns 
4. Click on the Filter button 
5. Add a filter condition with the "is" operation and enter the "not null" value 

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2023-10-30 at 2 27 39 PM" src="https://github.com/ToolJet/ToolJet/assets/59684099/353c63d7-f448-4b5e-9be2-3d9d9ec5857c">

**Comment by alpha951** [comment]
Please assign this issue to me

**Comment by Mekhla-Asopa** [comment]
@mansukh-tj  Please check, the screencast.

https://github.com/ToolJet/ToolJet/assets/59684099/7a213c84-2a8c-4fa7-86fe-97f443819657
