### ISSUE TITLE
Transformation/Add-new-Query editor automatically closes and looses all unsaved code when we hover over the queries

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#808]
### Environment
Ubuntu 20.04, MacOS

### What is the expected behaviour?
When we hover over the data queries, nothing should happen to the code being written in transformation editor/new query being configured

### What is the current behaviour?
Transformation editor automatically closes and looses all unsaved code when we hover over the queries
When we add a new query and are configuring it, if we hover over the queries, same issue happens.

### How to reproduce the issue?

1. Add a query
2. Add another one
3. Edit the transformation of the second query
4. Type something in
5. Hover over the queries section

OR simply add a query and hover over the query list before saving it

### Screenshots or Screencast

https://user-images.githubusercontent.com/20333972/134167392-56745a43-440c-4d2d-9326-4786d15ebb85.mp4

**Comment by arpitnath** [comment]
picking this up
