### ISSUE TITLE
Display code result preview for codeboxes outside of inspector

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#809]
### Is your proposal related to a problem?

Presently, we have a code result preview for code input boxes inside the inspector (right panel). However, we don't have them for code boxes such as table drop down options
### Describe the solution you'd like

Add code result previews for

1. All table widgets : dropdowns, radio etc
2. Event handler : show alert -> alert message should have code output
3. Query editor: eg: Url input boxes, input boxes in GUI mode of queries etc
4. Query transformation editor

**Comment by ajinkyaa** [comment]
Working on this, please assign this to me
