### ISSUE TITLE
Font for email confirmation after signup

### ISSUE THREAD

**Issue by jentaruno** [ToolJet/ToolJet#8109]
### Environment

I have ToolJet Docker on Windows. But I came across this issue when signing up through the ToolJet website.

### What is the expected behaviour?

The message should be displayed with IBM Plex Sans (ToolJet's default font).

### What is the current behaviour?

The message is displayed with the default serif font.

### How to reproduce the issue?
Go to ToolJet and sign up for a new account. Fill in all details and finish creating your account.

### Screenshots or Screencast

<img width="299" alt="image" src="https://github.com/ToolJet/ToolJet/assets/99060936/1df4eb2e-10bf-412e-beb8-c3ba3a9f9920">

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by akspan12** [comment]
Found this same when error message is displayed on login page
<img width="287" alt="image" src="https://github.com/ToolJet/ToolJet/assets/23078575/cb3480a6-51ea-46b5-880d-b5bc48c5efdd">
