### ISSUE TITLE
Changing title of tab as per the name of page

### ISSUE THREAD

**Issue by thehacklady** [ToolJet/ToolJet#8114]
The objective of this feature is to enhance the user experience by dynamically updating the browser tab title based on the currently active page within ToolJet. This improvement will provide users with a clear and intuitive representation of the page they are currently viewing.

1. Page Title Management
- The tab title of the browser should dynamically change to match the name of the currently active ToolJet page.
- The tab title should reflect the name of the page in a user-friendly and concise manner.
- The tab title should revert to a default title (e.g., "ToolJet") when the user logs out or navigates to an unsupported URL.

2. Supported Pages
The tab title should dynamically change for the following pages in ToolJet:

- Marketplace
- Dashboard
- Data sources
- Workspace settings
- Settings
- Audit Logs
- Profile

3. Default Tab Title
The default tab title, when no specific page is active, should be set to "Dashboard."

**Comment by ValkonX33** [comment]
we can use useTitle  right?
