### ISSUE TITLE
User is not getting redirected to Dashboard on click of logo from editor mode

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#8142]
### What is the expected behaviour?
If user right clicks on the logo and try to access it in the new tab of the browser it is not getting redirected to the Dashboard.

### What is the current behaviour?
On right click and selecting 'Open in new tab' option, user is getting redirected to the editor mode of the app instead of the Dashboard

### How to reproduce the issue?

1. Create an app
2. Right click on app logo and select open in new tab option
3. Verify the redirection

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/7452699c-ed88-4d16-a54a-4d13c568c5ac

**Comment by rajdip-b** [comment]
Can I work on this bug?
