### ISSUE TITLE
Bug with DATABASE_URL env

### ISSUE THREAD

**Issue by MinhFrostNhat** [ToolJet/ToolJet#8177]
Hi, Currently I using DATABASE_URL: postgres://username:password@hostname:port/database_name?sslmode=disable
But i can not start and I check the logs and I got 
wait-for-it.sh: waiting 300 seconds for username:5432 but it should be wait-for-it.sh: waiting 300 seconds for hostname:5432 ... then start migrate
how can i pass this error please help me!

**Comment by rhuanbarreto** [comment]
@MinhFrostNhat where is this fixed? I see the code in develop branch is still unchanged
