### ISSUE TITLE
Ability to add filter in table component programatically

### ISSUE THREAD

**Issue by shubh22** [ToolJet/ToolJet#8199]
As a user using the application's table component, I want to be able to apply and clear filters to the table data using CSA.

Acceptance Criteria:

1. Given the table component in the application, When I call the setFilters function with an array of objects containing keys i.e "column","condition", "value" then the table should update to display only the rows that meet the specified filter criteria.

2. Given the setFilters function, When I provide an array of filter objects with keys that do not correspond to valid ("column","condition", "value") in the table, then those invalid filters should be ignored, and the table should not be affected by them.
 
3. Given the table with existing filters applied, When I call the setFilters function, then all existing filters should be cleared, and the new filters should be applied.
 
4. Given the table with existing filters applied, When I call the clearFilters function, then all existing filters should be cleared.

**Comment by GrowwithNaveen** [comment]
Filter condition codes: 
```
 { name: 'contains', value: 'contains' },
  { name: 'does not contains', value: 'doesNotContains' },
  { name: 'matches', value: 'matches' },
  { name: 'does not match', value: 'nl' },
  { name: 'equals', value: 'equals' },
  { name: 'does not equal', value: 'ne' },
  { name: 'is empty', value: 'isEmpty' },
  { name: 'is not empty', value: 'isNotEmpty' },
  { name: 'greater than', value: 'gt' },
  { name: 'less than', value: 'lt' },
  { name: 'greater than or equals', value: 'gte' },
  { name: 'less than or equals', value: 'lte' },
```
