### ISSUE TITLE
NumberInputComponent: `{{components.numberinput1.value}}` retains the initial value even after the input has been cleared.

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#8208]
### Environment
All Environments

### What is the expected behaviour?
The value of the input when cleared on the UI then it should also clear the value of `{{components.numberinput1.value}} `according to the UI component.

### What is the current behaviour?
When a value, for example, 34, is entered in the number input, it functions as expected, and `{{components.numberinput1.value}} `reflects the correct value of 34. However, when the input value is cleared, `{{components.numberinput1.value}} `unexpectedly becomes 3.

### How to reproduce the issue?

1. Drag and drop a Number input on the canvas.
2. Enter a value in the input.
3. Watch the value of `{{components.numberinput1.value}} ` in the inspector
4. Clear the value in the input then again observe the value of `{{components.numberinput1.value}} `.

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/85864291/92b6699e-fe90-4ccb-8547-a4776869136a

**Comment by anoopw3bdev** [comment]
Hey @ShazanRizvi can you assign this issue to me, I would like to add the fix

**Comment by shubh22** [comment]
This is fixed.
