### ISSUE TITLE
Align the "Create New application" button with the other elements adjacent to the "Welcome to your new ToolJet workspace" text for better visual consistency.

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#8225]
### Environment
All Environments

### Description:
The positioning of the **"Create New Application"** button on the new workspace page is currently slightly more left-aligned compared to the accompanying text, **"Welcome to your new ToolJet workspace"** To enhance visual symmetry and alignment, adjustments are required to ensure that the button aligns seamlessly with the heading. This will contribute to a more polished and cohesive appearance on the page.

### Steps to Reproduce:

1. Go to the ToolJet application.
2. Create a new workspace from the menu on the bottom left of the page. PFA snapshots
3. Observe the alignment of the button with the heading text.

![Screenshot 2023-11-29 at 10 49 42 PM](https://github.com/ToolJet/ToolJet/assets/85864291/556b08a2-b150-4ffa-9ffd-9d2bd28fa4f1)

### Create workspace:
![Screenshot 2023-11-29 at 10 57 48 PM](https://github.com/ToolJet/ToolJet/assets/85864291/fa545585-cec4-4710-a21d-75fa2045a622)

**Comment by mud1tx** [comment]
@ShazanRizvi I can work on this if it is still open.

**Comment by sbakash** [comment]
@ShazanRizvi can you assign this issue to me if it is still not fixed.

**Comment by withshubh** [comment]
Hey @rajdip-b 
Assigned the issue to you.

**Comment by snehalk19** [comment]
@ShazanRizvi Can you assignee the issue to me, as I can see assignee is blank

**Comment by rajdip-b** [comment]
Hey @snehalk19, feel free to take this up. I won't be able to get to it in a while now :(

**Comment by Ayushhgupta39** [comment]
I'm working on this

**Comment by Ayushhgupta39** [comment]
This seems to be fixed now:

![image](https://github.com/ToolJet/ToolJet/assets/96309609/88369c93-7fcb-4b0c-b3d2-1e43eb8c8d48)

**Comment by Just-A-Pixel** [comment]
Is this issue resolved? If not, may I pick it up?

**Comment by aceppaluni** [comment]
Hi is this still open?

**Comment by karan-rathod-316** [comment]
@ShazanRizvi Please take a look at this issue and related PRs whenever you find the time :-).

**Comment by adityabarodiya** [comment]
can i work on this issue?

**Comment by STSonyThomas** [comment]
May I work on this issue @karan-rathod-316 ?

**Comment by karan-rathod-316** [comment]
Hi @STSonyThomas and @adityabarodiya, the PR related to this issue is already under review. The below community issue is open if you wish to take it up:
https://github.com/ToolJet/ToolJet/issues/9204

**Comment by test0o0** [comment]
May I work on this issue @karan-rathod-316 ?

**Comment by karan-rathod-316** [comment]
Closing this issue as this has been handled in a different PR.
