### ISSUE TITLE
Dropdown component 2.0

### ISSUE THREAD

**Issue by nakulnagargade** [ToolJet/ToolJet#8228]
PRD
[Dropdown -New](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-14576)
[Dropdown (Deprecated)](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-22656)
Design [here](https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?type=design&node-id=8160-139783&mode=design&t=gUdgnTdSTeyvC9J0-4)

**Comment by overlyhonest** [comment]
Design review


### Field
1. Label implementation is incorrect, when resizing text input the spacing between label and input also changes 
2. Interaction for clear field button (hover, pressed etc) are not added 
3. Spacing b/w clear button and dropdown arrow is incorrect 
4. Dropdown arrow icon is incorrect 
5. Search icon is incorrect 
6. Search is broken, can only input 1 character 
7. Resizing is inconsistent with other new inputs, feels like there is an animation added which is not needed, can keep consistant with resizing of other inputs.  
8. Default icon color is incorrect. 

### Option list 
1. Delete button (while hovering over an option) size is incorrect 
2. Spacing between items within an option menu is incorrect 
3. Spacing between label and field (option label and option value) is incorrect 

> In general, it looks like there is a bunch of inconsistencies with design. May need to review again.  


### Other Improvements 
1. Placeholder from `spacing` yo `Spacing`
2. `Mark this as default option` to `Make this default option`

**Comment by overlyhonest** [comment]
Design review


### Field
1. Label implementation is incorrect, when resizing text input the spacing between label and input also changes 
2. Interaction for clear field button (hover, pressed etc) are not added 
3. Spacing b/w clear button and dropdown arrow is incorrect 
4. Dropdown arrow icon is incorrect 
5. Search icon is incorrect 
6. Search is broken, can only input 1 character 
7. Resizing is inconsistent with other new inputs, feels like there is an animation added which is not needed, can keep consistant with resizing of other inputs.  
8. Default icon color is incorrect. 

### Option list 
1. Delete button (while hovering over an option) size is incorrect 
2. Spacing between items within an option menu is incorrect 
3. Spacing between label and field (option label and option value) is incorrect 

> In general, it looks like there is a bunch of inconsistencies with design. May need to review again.  


### Other Improvements 
1. Placeholder from `spacing` yo `Spacing`
2. `Mark this as default option` to `Make this default option`

**Comment by overlyhonest** [comment]
- While resizing, clear button and triangle icon goes to the next line and to the outside of the component div 
- Radius is missing at the bottom corners of the popout menu 
- border is not needed on the popout menu 
- Change the clear button size to medium 
- When I make an invalid search entry and close the popout menu, the next time I open I see no option (when the search is clear)


- Delete button (while hovering over an option) size is incorrect
