### ISSUE TITLE
MultiSelect component 2.0

### ISSUE THREAD

**Issue by nakulnagargade** [ToolJet/ToolJet#8229]
PRD 
[New Component](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-14236)
[Legacy Component](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-22676)
Design [here](https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?type=design&node-id=8160-157855&mode=design&t=gUdgnTdSTeyvC9J0-4)

**Comment by overlyhonest** [comment]
- While resizing, clear button and triangle icon goes to the next line and to the outside of the component div 
- Change the clear button size to medium 
- When I make an invalid search entry and close the popout menu, the next time I open I see no option (when the search is clear)


- Delete button (while hovering over an option) size is incorrect
