### ISSUE TITLE
Add support for setting color of toggle switch widget

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#825]
### Is your proposal related to a problem?

Presently, its not possible to set color (other than text color) for toggle switch widget. There is only one color available.

![image](https://user-images.githubusercontent.com/20333972/134486479-83dd492d-f0eb-4e87-8b04-9c7227f85a71.png)

### Describe the solution you'd like

Add an option with color selector, which allows user to change the toggle color

**Comment by virajbahulkar** [comment]
picking this up
