### ISSUE TITLE
Disable option "Add New Workspace" to the end user

### ISSUE THREAD

**Issue by nitin-anantpranali** [ToolJet/ToolJet#8256]
### Version Information
Version 2.24.4
### How to reproduce the issue?

1. Remove the Auto creation of the workspace
2. Remove Access to "Add New Workspace"
3. Add Setting to allow the user access to "Add new workspace" 

### Screenshots or Screencast
<img width="301" alt="image" src="https://github.com/ToolJet/ToolJet/assets/116695322/483cf0d3-4ae0-4175-b2cb-725f073a8abb">

**Comment by Navaneeth-pk** [comment]
Only super admins can enable/disable this feature: https://docs.tooljet.com/docs/Enterprise/superadmin#restrict-creation-of-personal-workspace-of-users.
