### ISSUE TITLE
Workspace settings: The default 'Users' tab is not appearing as selected, background highlight is missing

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#8263]
### What is the expected behaviour?
When user navigates to the 'Workspace settings' tab, the default tab should appear as selected and highlighted.

### What is the current behaviour?
Users tab is not having any background, so it appears as not selected on click of it.

### How to reproduce the issue?

1. Go to workspace setting tab
2. Click on Users subtab
3.

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/5b3ac0de-5db7-441d-a4d8-0b2dd31dbcd7

**Comment by gsmithun4** [comment]
Moved to EE, not able to reproduce in CE
