### ISSUE TITLE
Enter your phone number works even when left empty

### ISSUE THREAD

**Issue by Ayushhgupta39** [ToolJet/ToolJet#8312]
### Version Information
v2.26.0 and prior

### Environment
All

### What is the expected behaviour?
The Enter your phone number page should be marked as optional or should give an alert when left empty.

### What is the current behaviour?
The page simply moves forward when pressed Continue, even when left empty. This creates an unexpected user experience.

### How to reproduce the issue?

1. Create a new Account using Email or Google/GitHub.
2. Verify your Email and proceed to "Set up Workspace" section.
3. Provide the required details, and then you will reach the "Enter your phone number" page where the issue occurs.

### Screenshots or Screencast
![image](https://github.com/ToolJet/ToolJet/assets/96309609/5b088660-0d99-411b-b6c7-4e12d12ea22e)

### Please provide any traces or logs that could help here.
N/A

### Any possible solutions?
The input field should give an alert on clicking "Continue" if left empty or the page should be simply marked as Optional.

### Can you identify the location in the driver source code where the problem exists?
`/tooljet/frontend/src/OnBoardingForm/OnBoardingForm.jsx`
`/tooljet/frontend/src/OnBoardingForm/OnbboardingFromSH.jsx`

### If the bug is confirmed, would you be willing to submit a PR?
Yes, I would love to work on the issue and contribute 😄

**Comment by shubh22** [comment]
This is the current expected behaviour. We will change it if required in future.

**Comment by Ayushhgupta39** [comment]
Sure
