### ISSUE TITLE
Version: 2.24.3-ee2.10.2  docker  install   count not listen 80 port

### ISSUE THREAD

**Issue by webtang2017** [ToolJet/ToolJet#8317]
### What is the expected behaviour?

docker-compose.yaml  👍：
version: "3"

services:
  tooljet:
    tty: true
    stdin_open: true
    container_name: Tooljet-app
    image: tooljet/tooljet:v2.24.3-ee2.10.2
    restart: always
    env_file: .env
    ports:
      - 11180:80
    depends_on:
      - postgres
      - redis
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod

  postgres:
    container_name: ${PG_HOST}
    image: postgres:13
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
 postgrest:
    container_name: postgrest
    image: postgrest/postgrest:v10.1.1.20221215
    restart: always
    depends_on:
      - postgres
    env_file: .env
    environment:
      - PGRST_SERVER_PORT=11180

  redis:
    container_name: ${REDIS_HOST}
    image: redis:6.2
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data
    env_file:
      - .env
    environment:
      - MASTER=${REDIS_HOST}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  database-backup-service:
    image: postgres:alpine
    container_name: db-backup
    env_file: .env
    volumes:
  container_name: db-backup
    env_file: .env
    volumes:
      - ./backup:/backup
    depends_on:
      - postgres
    command: >
      sh -c 'if [ "$DATABASE_BACKUP" = "true" ]; then
        until PGPASSWORD=$PG_PASS pg_isready -h $PG_HOST -p 5432; do
          echo "Waiting for PostgreSQL to become available..." && sleep 1;
        done;
        PGPASSWORD=$PG_PASS pg_dump --host=$PG_HOST --port=5432 --username=$PG_USER --dbname=$PG_DB -f "/backup
/dump_$(date +'%Y%m%d%H%M%S').sql" &&
        find /backup -type f -mtime +30 -delete &&
        echo "Dump taken successfully." &&
        exit 0;
      else
        echo "Skipping backup." &&
        exit 1;
      fi'      

volumes:
  redis_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/redis_data
  postgres:
    driver: local
    driver_opts:
   driver_opts:
      o: bind
      type: none
      device: ${PWD}/postgres_data
  certs:
  logs:
  fallbackcerts:

bug?or anything wrong?

**Comment by SDBdevelopment** [comment]
Ports below 1024 are classed as privileged -- only root, or someone with the specific privilege, is allowed to open sockets on those ports.

Change to following to get it to work:
```
ports:
- 11180:80  <= change to: - 11180:8080
environment:
PORT: "80"  <= change to: PORT: "8080"
```

**Comment by webtang2017** [comment]
ok,thinks,it is ok

**Comment by adishM98** [comment]
Hi @webtang2017, 

Were you running docker on a server ?

**Comment by adishM98** [comment]
Closing the issue. If you are still facing this issue, please let us know.
