### ISSUE TITLE
Upgrade from v2.23.0 to v2.24.0 (and beyond) breaks my app because of missing globals.currentUser

### ISSUE THREAD

**Issue by codiflow** [ToolJet/ToolJet#8319]
### Version Information
v2.23.0 => OK
v2.24.0 and beyond => NOT OK

### Environment
Tooljet Docker

### What is the expected behaviour?
Updates should not break existing apps and propagate variables as always

### What is the current behaviour?
After installing the update, the global object `globals.currentUser` is missing at all. `globals` only has two instead of four subobjects.

### How to reproduce the issue?

1. Edit app within v2.23.0 and see that object `globals.currentUser` is there.
2. Update to v2.24.0 (or v2.24.5 or beyond, doesn't matter)
3. Edit app within new version and notice error messages (of various kinds) because object `globals.currentUser` is missing.

### Screenshots or Screencast
This is how it should look like:
![image](https://github.com/ToolJet/ToolJet/assets/43847817/1b626d62-cb21-469e-93c2-8dcca5be919a)

In the broken versions `globals.currentUser` and `globals.mode` are missing.

### Additional info

I remember I had this issue back when I used something newer than v2.3.1. So I stayed on this version for quite some time and after upgrading from v2.3.1 to v2.17.5 the problem was gone.

So maybe it has to do with some database migration?

The app we are talking about has around 6MB in size.

If I create a totally new app the object `globals.currentUser` appears like it should. There are no scripts who are manipulating this globals object (don't know if this would be possible though) so they **MUST** be there at all time.

**Comment by shubh22** [comment]
It seems to be working for us. Please upgrade to the latest version and try again.

**Comment by codiflow** [comment]
I now upgraded from `v2.23.0` up to `v2.35.2` and now **I can't even edit my app anymore**. The symptoms are as follows:

My **internal app version** I was editing before starting the upgrade was set to `v1.5.2`. After the upgrade has finished and I start to edit the app again it shows me `v1.0.2` (an old version) in the upper right corner and the following error message appears:

![grafik](https://github.com/ToolJet/ToolJet/assets/43847817/19fe5832-f149-4ae3-baa6-6a7dd09cc22b)

In the browser console this error has been being logged from the very beginning of launching the page:
```
Uncaught TypeError: Cannot read properties of null (reading 'updateDiff')
    at X (main.js?8512c26f047f9fa3a5b7:124:65840)
    at Ua (main.js?8512c26f047f9fa3a5b7:28:40)
    at T (vendor.js?8512c26f047f9fa3a5b7:29126:45074)
    at P (vendor.js?8512c26f047f9fa3a5b7:29126:45362)
    at D (vendor.js?8512c26f047f9fa3a5b7:29126:45301)
```

After changing the app version in the upper right corner to `v1.5.2` the screen gets white (full crash) and the browser console logs:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'canvasMaxWidth')
    at we (main.js?8512c26f047f9fa3a5b7:28:15556)
    at fl (vendor.js?8512c26f047f9fa3a5b7:32892:21571)
    at cu (vendor.js?8512c26f047f9fa3a5b7:32894:3453)
    at b0 (vendor.js?8512c26f047f9fa3a5b7:32894:48959)
    at Xt (vendor.js?8512c26f047f9fa3a5b7:32894:43437)
    at Xi (vendor.js?8512c26f047f9fa3a5b7:32894:43363)
    at Ui (vendor.js?8512c26f047f9fa3a5b7:32894:43212)
    at D1 (vendor.js?8512c26f047f9fa3a5b7:32894:40081)
    at Yl (vendor.js?8512c26f047f9fa3a5b7:32892:3499)
    at B1 (vendor.js?8512c26f047f9fa3a5b7:32894:37118)
```

I mean I can debug my app now but from my perspective it should not happen this often that TJ updates **break internal apps** in a way which makes them unusable like this.

I use a `docker-compose.yml` deployment and the upgrade path I've taken was:
Starting from 2.23.0 I stopped the containers, changed the tag in the `docker-compose.yml`, started the containers, watched the logs for errors (haven't seen any serious ones), reloaded the overview page of ToolJet which shows the current version in the upper right corner and stopped the container. I repeated this for all the following versions:

- 2.24.0
- 2.24.5
- 2.25.0
- 2.26.0
- 2.26.2
- 2.27.0
- 2.27.7
- 2.28.0
- 2.28.4
- 2.29.0
- 2.30.0
- 2.30.4
- 2.32.0
- 2.32.5
- 2.33.0
- 2.33.6
- 2.34.0
- 2.34.2
- 2.35.0
- 2.35.2

I know that it might also have been sufficient to **just update to v2.23.3-ee2.10.2 and then directly to 2.35.2** as mentioned [here](https://docs.tooljet.com/docs/setup/docker#upgrading-to-the-latest-version). I will try that also but from the past I haven't had good experiences with this kind of upgrades.

But generally speaking this always **really** frustrates me because ToolJet updates broke my app for the second time now forcing me to spend hours in testing and stepping from TJ version to TJ version to figure out where the problem was introduced first.

I would **REALLY appreciate** the team to spend some efford on making updates less problematic for admins. Because in production this would mean my clients I create custom apps for would have to pay me all the hours for testing everything after every bigger update. From my perspective this is not a good way how Open Source software could convince enterprise customers at all.

I really can not believe that I'm the only person having this kind of issues. Are there no other **larger business applications** out there built on base of ToolJet? Or am I expecting to much from ToolJet?

**Comment by codiflow** [comment]
Same issue when I upgrade directly from `2.24.0` to `2.35.2`.

**Comment by codiflow** [comment]
As stated in the initial post as long as I use `v2.23.0` everythings fine. As soon as I upgrade to `v2.24.0` my app throws many many `eval_errors` on the browser console as soon as I start the edit mode. Also my **internal app version** in the upper right corner is **different** to the one which was selected when I left the edit mode as I was still on `v2.23.0`.

So the **necessary migrations** while going from `v2.23.0` to `v2.24.0` seem to start breaking my internal app...

**Comment by codiflow** [comment]
@shubh22 I would recommend to reopen this issue if possible 😉

**Comment by ShazanRizvi** [comment]
Hi @codiflow we sincerely apologize for the inconvenience caused and I assure you that our team will look into this on priority.

**Comment by codiflow** [comment]
Thanks. I will provide some more details on the issue here and also try to get a diff of my internal app by exporting it but thats not that easy as the export of all internal app versions already has a total size of ~100MB.

Apart from that this is how the **versioning of my internal app** looks like on `2.23.0` where everything is alright:

![grafik](https://github.com/ToolJet/ToolJet/assets/43847817/fadc7368-fe44-4675-9a92-c180f55f69ac)

And this is how it looks like on `2.24.0` where it is broken:
![grafik](https://github.com/ToolJet/ToolJet/assets/43847817/3c612eae-3806-4816-872f-3baa04ee682a)

As you can see the date for the "current version" is also totally wrong as it just alters an old version.

**Comment by ShazanRizvi** [comment]
@codiflow thanks for sharing the detailed info let me share this with the team.

**Comment by codiflow** [comment]
Unfortunately creating a patch between the two full json exports (each has ~100MB in size) results in a 18 MB patch file...

I don't really get what the heavy migrations from `2.23.0` to `2.24.0` are doing with my internal app but it seems like it's not just "small changes". Unfortunately I cannot share the app itself so maybe you have an idea how I could debug this further?

**Comment by codiflow** [comment]
I investigated this further and deleted the last staging version of my internal app in v2.23.0 so only published versions of my internal app are left in the app export.

I can say that the full app export from `v2.23.0` (again: where everything works in the edit mode as expected without browser console errors) now has about **84.4 MB**.

After the update to `v2.24.0` without even starting the edit mode again the full export hast a total size of about **99.7 MB**. So the migration adds around **15 MB** of content – wherever that comes from and what it is for – I don't know.

So for now this is all I see myself able to do.

**Comment by codiflow** [comment]
OK one last thing – I don't know how this should ever get fixed for me – seems like I'm stuck on v2.23.0 forever with my internal app 😢

I exported the last production version from my internal app (v1.5.1) while being in `v2.23.0`, deleted the original app (the one which has ~80MB in size) and **reimported** the single production version back into `v2.23.0`. Everything also was fine on this new imported app while testing it on `v2.23.0`.

After upgrading to `v2.24.0` and starting the single app (which now only has about 6MB in size) I get different error messages in my browser console which renders the whole editor unusable and also the live version is not working anymore:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'canvasMaxWidth')
```

and

```
TypeError: Cannot read properties of null (reading 'canvasMaxWidth')
```

Seems like one of the messages is the same error I posted yesterday: https://github.com/ToolJet/ToolJet/issues/8319#issuecomment-2057494127

The diff between the two internal app exports now has around **400KB** but it is still way to large to be shared here and there are many confidential parts in it.

Generally speaking I can't say that ToolJet is "production or enterprise ready" when an business app I started developing **one year ago** starting with Tooljet 2.3.1 becomes **unusable** in version 2.24.0 without any clue how this happens.

I think I will have to look into alternatives because this takes way to much time to investigate and from a business perspective things break way to often after TJ updates. That's really sad😢

**Comment by ShazanRizvi** [comment]
Hi @codiflow,

I've informed the team about the issue, and they are currently in the process of debugging it. I'll provide you with an update as soon as possible. We apologize for any inconvenience this may have caused.

**Comment by kavinvenkatachalam** [comment]
Hey @codiflow,

We tried migrating from **v2.23.0-ee2.10.1** to **v2.24.3-ee2.10.2**. Everything seems to be working for us. Attaching the screenshot of the `globals.currentUser` and `globals.mode`. 


Can you please help us with the current Tooljet version you're now (if you already migrated) and can you let us know the issues or share us the error message which breaks the app?





<img width="777" alt="image" src="https://github.com/ToolJet/ToolJet/assets/50441969/739a70c2-9ee9-4d52-8f1e-0470853ba0fa">

**Comment by shubh22** [comment]
Hi @codiflow ,
I understand that you have faced issues while upgrading ToolJet 2 times in the last 1 year. We take this as a serious feedback and recently we have decided to change our release strategy. It will be reflected in a couple of weeks.
We always recommend that you take proper backups and test your release in a development environment before you can upgrade the production instance. I hope this is being followed at your end as well. I can assure you that there are 1000s of enterprises using ToolJet on the most recent versions without any major problems. This sounds like a rare one-off case where something went wrong, which is difficult to debug. If I were to guess the reason then it is most likely that you upgraded to a version above 2.23.0 without upgrading to 2.23.0 itself. 
Do you have the backup from the time you upgraded ToolJet for the first time from your stable version (2.3.1) to something above 2.23.0?
I would suggest you to join our [slack](https://tooljet.com/slack) channel and discuss it in more real time with our support team who can help you find a solution.

**Comment by codiflow** [comment]
Hey @shubh22 ,
> We take this as a serious feedback and recently we have decided to change our release strategy.

Really looking forward to that 🥳

> If I were to guess the reason then it is most likely that you upgraded to a version above 2.23.0 without upgrading to 2.23.0 itself.

Nope, as I mention below this never happened.

> Do you have the backup from the time you upgraded ToolJet for the first time from your stable version (2.3.1) to something above 2.23.0?

No I don't because I **never skipped a version** because of the bad experiences I had from the first time my app got broken by TJ updates. This was why my upgrade approach always looked like the one I mentioned [here](https://github.com/ToolJet/ToolJet/issues/8319#issuecomment-2057494127). So I always went from the latest patch of the current minor version to the next minor version and then went on to the latest patch of this minor and so on.

---

Hey @kavinvenkatachalam ,
> Can you please help us with the current Tooljet version you're now (if you already migrated) and can you let us know the issues or share us the error message which breaks the app?

Currently I'm on `v2.23.0` because this is the latest version where everything works for me. This is also the only version I have a backup from because things in my app have changed in the meantime so downgrading to something below `v2.23.0` is not possible anymore.

Here are my screenshots of `v2.23.0`:
![grafik](https://github.com/ToolJet/ToolJet/assets/43847817/409bf4ed-939c-4709-8cad-6d28990c83b8)

![grafik](https://github.com/ToolJet/ToolJet/assets/43847817/0d38fdb5-51f2-4635-86c4-844a5caaf19a)

I don't know where you get the `v2.23.0-ee2.10.1` from – for me it only show `2.23.0`.
Maybe this is part of the problem? Seems like I'm using the Community Edition in Docker and you are using the Enterprise Edition:

`image: tooljet/tooljet-ce:v2.23.0`

**Comment by codiflow** [comment]
OK I think I found the issue. It must be within the **Community edition** upgrade from `v2.23.0` to `v2.24.0`.

Upgrading from `tooljet/tooljet-ce:v2.23.0` to `tooljet/tooljet-ce:v2.24.0` breaks my app.

Going from `tooljet/tooljet-ce:v2.23.0` to `tooljet/tooljet-ee:v2.23.0-ee2.10.1` and then back to community edition `tooljet/tooljet-ce:v2.24.0` also breaks my app.

BUT when I'm going from `tooljet/tooljet-ce:v2.23.0` to `tooljet/tooljet-ee:v2.23.0-ee2.10.1` and then to `tooljet/tooljet-ee:v2.24.3-ee2.10.2` everything works out 🙏

This is not the kind of "solution" I was looking for because I stay on the community edition for good reasons. But maybe it is possible to switch back to the community edition after the migration from 2.23 to 2.24 went through?

**Comment by kavinvenkatachalam** [comment]
@codiflow I tried updating the CE from 2.23.0 to 2.24.0 and I can see the gloabls.currentUser. Attaching the screenshot. 
The equivalent version for `tooljet/tooljet-ee:v2.24.3-ee2.10.2` in community edition is `tooljet/tooljet-ce:v2.24.3`. Can try upgrading to that above mentioned CE version or `tooljet/tooljet-ce:v2.24.5` and share us the error message or screenshot if you got any issue during the upgrade?

**NOTE:** Please use the original backup copy during the upgrade


<img width="773" alt="image" src="https://github.com/ToolJet/ToolJet/assets/50441969/9b3061bb-64f3-4c3e-a00a-7eef1650b5e2">

**Comment by codiflow** [comment]
There you go:
![grafik](https://github.com/ToolJet/ToolJet/assets/43847817/051347c3-999b-4193-9942-1674fb8defa7)

Upgrading from `tooljet/tooljet-ce:v2.23.0` to `tooljet/tooljet-ce:v2.24.3` results in the same error like mentioned in the previous posts (console logs many `eval errors`).

**Comment by kavinvenkatachalam** [comment]
Thanks for the screenshot. Are you getting the same error on firefox in edit mode?

**Comment by codiflow** [comment]
This are the console log errors while trying to **launch** my app in **Chromium**:
![grafik](https://github.com/ToolJet/ToolJet/assets/43847817/45915311-ba8f-4f52-bae9-95c941c91335)

Opening the **edit mode** in **Firefox** spawns many of those errors in the console:
```
utils.js (93:6) eval_error TypeError: globals.currentUser is undefined
```

**Comment by kavinvenkatachalam** [comment]
Can you check whether the authorize API call on the browser's network tab returning the user data?

<img width="846" alt="image" src="https://github.com/ToolJet/ToolJet/assets/50441969/65b95234-372d-49bc-947d-db7c4ee196ba">

**Comment by codiflow** [comment]
I cleaned up my production app versions and only **two versions are remaining in there now**.

After upgrading from `v2.23.0` to `v2.24.5` I get a white screen now after entering the edit mode and the error messages in the console are different:

Firefox: `TypeError: W.globalSettings is null`
Chromium: `TypeError: Cannot read properties of null (reading 'canvasMaxWidth')`

The browser request responses are returning the data **in this case** (with the cleaned up versions):
![grafik](https://github.com/ToolJet/ToolJet/assets/43847817/d3489c7c-eeb2-425f-9197-18446617ab32)

I will check the browser request response on the error case I mentioned before.

**Comment by kavinvenkatachalam** [comment]
Just checking, have you run the migrations while upgrading to a new version?

**Comment by codiflow** [comment]
> Just checking, have you run the migrations while upgrading to a new version?

What exactly do you mean with "the migrations"? I just went from `v2.23.0` to `v2.24.5` as you mentioned [here](https://github.com/ToolJet/ToolJet/issues/8319#issuecomment-2061141683).

**Comment by codiflow** [comment]
There definitely must be something wrong with the Community edition somehow.

With my app versions cleaned up I went from `v2.23.0` to `v2.24.3-ee2.10.2` and (as already mentioned earlier) **everything works**. When I then "upgrade" back to `v2.24.3` it is broken again.

I also noticed some strange behaviour here:
https://github.com/ToolJet/ToolJet/assets/43847817/39a91f4c-6fa3-4358-bc03-c605e9fe8b1e

It first shows 4 entries in globals and after a short period of "console log errors" it reduces to two errors.

**Comment by ShazanRizvi** [comment]
Hello @codiflow,

Could you please share an export of the app, excluding any confidential information? This would greatly assist us in debugging the issue more effectively.

**Comment by codiflow** [comment]
Hey @ShazanRizvi ,

I'm sorry but as I mentioned earlier that's not possible at all.

But I can try to export some of the old versions of the app which are not this "confidential" and check if the error exists there too. Will check and report back.

**Comment by ShazanRizvi** [comment]
Thank you, @codiflow. Please don't hesitate to let us know if you encounter the error again with the older versions of the app. We are here to help with any issues you may have.😊

**Comment by PriteshKiri** [comment]
Hey @codiflow 

I hope your issue has been resolved. 

If you're still experiencing any difficulties, feel free to reach out to us on our [Slack community](https://www.tooljet.com/slack), and we'll be happy to assist you further. 

Closing the issue for now.
