### ISSUE TITLE
After changing user role, changing it back gives "Forbidden Resource" error

### ISSUE THREAD

**Issue by virajbahulkar** [ToolJet/ToolJet#833]
### Environment
Mac OS

### What is the expected behaviour?
Should be able to change role 

### What is the current behaviour?
Current behaviour is when after changing user role, changing it back gives "Forbidden Resource" error.

### How to reproduce the issue?

1. Click on users tab
2. In the table under role column change currently selected dropdown value
3. Try changing it back, 
4. It gives "Forbidden Resource" error.

### Screenshots or Screencast
https://www.loom.com/share/fb38b498febd460c9edbbc82a2ec1d26

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by akhilgkrishnan** [comment]
@virajbahulkar I think this is the expected behavior because you were logged as a "Viewer". So viewer doesn't have permission to change their role.
