### ISSUE TITLE
Advance options state lost if we hover over queries section

### ISSUE THREAD

**Issue by mohinid** [ToolJet/ToolJet#835]
**Steps to reproduce:**
1. Login to tooljet.
2. Create an app.
3. Add any datasource. I have added postgres.
4. Go to advance tab and click on any one of the toggle. 

**Expected**: Should keep the advance tab open and keep the toggle state saved.

**Actual**: Advance tab is closed. The state of toggle switches are lost.

https://www.loom.com/share/810a50cf7c6847fcb635ae1aed9de6e9

**Comment by arpitnath** [comment]
picking this up
