### ISSUE TITLE
Make The logos aligned properly

### ISSUE THREAD

**Issue by Rakshit-gen** [ToolJet/ToolJet#8350]
![issues1111](https://github.com/ToolJet/ToolJet/assets/64471316/771c2ea7-18b6-401e-b48a-7f7ddaf4ec2f)
### Is your proposal related to a problem?

The logos on the homepage are not aligned properly. Logo in the third column first row don't seem to fit with the grid of other logos .

### Describe the solution you'd like

Maybe fitting them in a grid with proper spacing or maybe proving some right margin to the misaligned logo can do the improvement.

### Describe alternatives you've considered

I think I can improve the grid if the team assigns me the issues

**Comment by Navaneeth-pk** [comment]
Thanks for reporting. Closing the issue as website is on Webflow.
