### ISSUE TITLE
Docker installation isn't working

### ISSUE THREAD

**Issue by lisn0** [ToolJet/ToolJet#8381]
### Environment
    Docker in MacOS 
### What is the expected behaviour?
  `docker-compose up -d` should run the application out of the box

### What is the current behaviour?
  running `docker compose up -d` give the following error `service "database-backup-service" depends on undefined service postgres: invalid compose project`

### How to reproduce the issue?
run the commands in the docks setup [docs](https://docs.tooljet.com/docs/setup/docker) for Docker with external PostgreSQL

1. `curl -LO https://tooljet-deployments.s3.us-west-1.amazonaws.com/docker/docker-compose.yaml`
2. `mkdir redis_data`
3. `curl -LO https://tooljet-deployments.s3.us-west-1.amazonaws.com/docker/.env.external.example`
4. `curl -LO https://tooljet-deployments.s3.us-west-1.amazonaws.com/docker/external.sh && chmod +x external.sh`
5. `mv .env.external.example .env && ./external.sh`
6. `docker-compose up -d`
### Any possible solutions?
remove database-backup-service service dependency on postgres service that doesn't exist

### Can you identify the location in the driver source code where the problem exists?

```  database-backup-service:
    image: postgres:alpine
    container_name: db-backup
    env_file: .env
    volumes:
      - ./backup:/backup
    depends_on:
      - postgres
    command: >
      sh -c 'if [ "$DATABASE_BACKUP" = "true" ]; then
        until PGPASSWORD=$PG_PASS pg_isready -h $PG_HOST -p 5432; do
          echo "Waiting for PostgreSQL to become available..." && sleep 1;
        done;
        PGPASSWORD=$PG_PASS pg_dump --host=$PG_HOST --port=5432 --username=$PG_USER --dbname=$PG_DB -f "/backup/dump_$(date +'%Y%m%d%H%M%S').sql" &&
        find /backup -type f -mtime +30 -delete &&
        echo "Dump taken successfully." &&
        exit 0;
      else
        echo "Skipping backup." &&
        exit 1;
      fi'
```

### If the bug is confirmed, would you be willing to submit a PR?
yes i like to contribute

**Comment by adishM98** [comment]
Hi @lisn0, 

Thank you for pointing out the issue. I will add the fix. Since it's maintained in S3 bucket. I will add the fix right-way.

**Comment by lisn0** [comment]
got it, thanks
