### ISSUE TITLE
[refactor]: Change the dialog box text that appears when you delete a component using the keyboard

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#8385]
### What is the expected behaviour?
All pre-built UI elements should be referred to as "components" in ToolJet.

### What is the current behaviour?
When trying to delete a component using the "delete" button on the keyboard, we get a pop-up that says. `Widget will be deleted, do you want to continue? `

![image](https://github.com/ToolJet/ToolJet/assets/58169101/6bb262c3-8e8b-4dba-b5a3-ce855ff713df)

### How to reproduce the issue?
1. Drop a component on the canvas.
2. Select a component and press the "delete" button on the keyboard.
3. A dialog box will pop-up that refers to the component as "widget".

### Any possible solutions?
Replace the dialog box text - `Widget will be deleted, do you want to continue?`
with - `Are you sure you want to delete this component?`

**Comment by lukas-mar** [comment]
Hi I would like to work on this issue, can I get assigned please?

**Comment by ayushjha119** [comment]
@karan-rathod-316  please can you assign this issue to me?

**Comment by karan-rathod-316** [comment]
> Hi I would like to work on this issue, can I get assigned please?

Hi @lukas-mar, assigning this to you. I appreciate your interest in contributing to ToolJet.

**Comment by karan-rathod-316** [comment]
> @karan-rathod-316 please can you assign this issue to me?

Hi @ayushjha119, This issue has been assigned to another contributor who had requested the assignment first. Please feel free to monitor other issues that may pique your interest. Thank you for your time and consideration.

**Comment by PraveenShinde3** [comment]
I have PR #8394 created for this issue, if no one worked on it you can merge that.

Thanks 🙂

**Comment by karan-rathod-316** [comment]
> I have PR #8394 created for this issue, if no one worked on it you can merge that.
> 
> Thanks 🙂

Hi Praveen, sure I will wait for a couple of days and re-assign this to you(and merge the PR) in case there's no response from the assignee. Ideally, we'd prefer if you comment and get it assigned to yourself before raising the PR🙂. Please feel free to monitor other issues that may pique your interest. Thank you for your time and consideration.

**Comment by karan-rathod-316** [comment]
Merged the below PR for this issue:

https://github.com/ToolJet/ToolJet/pull/8399
