### ISSUE TITLE
TJDB: Add support for `Date with time` as a datatype

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#8408]
### Is your proposal related to a problem?
PRD: https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-13756

ToolJet Database does not support native PGSQLTimestamp data field types. The user has to save timestamp data as a string and while retrieving the data, the user has to format the string to extract time & date data.

### Describe the solution you'd like
Add support for additional datatype `Date with time` which internally uses Postgres TIMESTAMPZ.

- The data will always be stored in UTC format
- The user can opt for what timezone the date needs to be displayed in

**Comment by Sranjan0208** [comment]
I would like to work on this issue
