### ISSUE TITLE
Mongodb better support

### ISSUE THREAD

**Issue by febinsathar** [ToolJet/ToolJet#842]
Mongodb queries are pretty limited (find, aggregates etc are not supported)

Happy to submit a PR

**Comment by Navaneeth-pk** [comment]
Can you please list down the operations that you would like to add?
@febinsathar

**Comment by febinsathar** [comment]
1. find
2. find_one
3. find_one_and_update
4. update_many
5. aggregate
6. count
7. remove
8. distinct
9. remove_one
10. accept a mongo js script and execute (need to check on feasibility)

**Comment by Navaneeth-pk** [comment]
I think we can create separate issues for each operation so that they can be built/shipped as smaller PRs, makes it easier to track. @febinsathar

**Comment by febinsathar** [comment]
sure will do that

**Comment by febinct** [comment]
https://github.com/ToolJet/ToolJet/pull/872/files PR for find_one & find

**Comment by febinsathar** [comment]
https://github.com/ToolJet/ToolJet/pull/872/files PR for find_one & find

**Comment by gsmithun4** [comment]
**List of Mongodb operations**
- List Collections - _Existing_
- Find One
- Find Many
- Total Count
- Count
- Distinct
- Insert One - _Existing_
- Insert Many - _Existing_
- Update One
- Update Many
- Replace One
- Find One and Update
- Find One and Replace
- Find One and Delete
- Aggregate
- Delete One
- Delete Many
- Bulk Operations
