### ISSUE TITLE
[docs]: Link pricing page on the badges

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#8423]
### Summary

There is a badge `Available on: Paid plans` on the documentation of the paid features of ToolJet.
Add a link to these badges to the Pricing page of ToolJet.

#### Pricing Page URL:
- https://www.tooljet.com/pricing

#### Paid feature docs:
- https://docs.tooljet.com/docs/tooljet-copilot
- https://docs.tooljet.com/docs/app-builder/customstyles
- https://docs.tooljet.com/docs/workflows/overview
- https://docs.tooljet.com/docs/user-authentication/sso/openid/setup
- https://docs.tooljet.com/docs/Enterprise/audit_logs
- https://docs.tooljet.com/docs/Enterprise/white-label
- https://docs.tooljet.com/docs/Enterprise/superadmin
- https://docs.tooljet.com/docs/org-management/licensing
- https://docs.tooljet.com/docs/release-management/multi-environment

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by ayushjha119** [comment]
@withshubh  Hey i can start working on this , can you assign this to me

**Comment by ayushjha119** [comment]
@karan-rathod-316 can you assign me i have started doing this

**Comment by karan-rathod-316** [comment]
@ayushjha119 Assigned.

**Comment by ayushjha119** [comment]
@withshubh @karan-rathod-316 please check the latest commit , i think this will fix the issue

**Comment by ayushjha119** [comment]
@karan-rathod-316 can you review this , i think my last commit will solve  the issue

**Comment by ayushjha119** [comment]
@withshubh @karan-rathod-316 Is there any problem in last commit??

**Comment by karan-rathod-316** [comment]
@ayushjha119 Hi Ayush, left a comment on your PR. I can still see some extra changes that are not required. Could you please revert all the additional changes and confirm?

**Comment by ayushjha119** [comment]
@karan-rathod-316 I have already raise a new PR after removing that table misalignment due to VS code extension
can you check this [https://github.com/ayushjha119/ToolJet/commit/4a6d204478d52b673c4947dcd220794c32e4adac](url)
if any more changes required i will do that

**Comment by ayushjha119** [comment]
@karan-rathod-316  https://github.com/ayushjha119/ToolJet/commit/4a6d204478d52b673c4947dcd220794c32e4adac

**Comment by karan-rathod-316** [comment]
@ayushjha119 Thanks! Moving this to review.
