### ISSUE TITLE
Change labels to sentence case for Dropdown Component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#8430]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

⚠️ The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values   | Expected Values  |
| :--------------- | :--------------- |
| Selected Text Color | Selected text color |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object that has the **Dropdown** component name in the name key, and make changes only in that particular object.  
   **For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**

```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```

2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by ayushjha119** [comment]
@withshubh Hey i can start working on this , can you assign this to me

**Comment by karan-rathod-316** [comment]
Hi @ayushjha119, let's wait for other first-time contributors to pick this up. We appreciate your interest in contributing to ToolJet.

**Comment by jangala-laxman** [comment]
Hi @karan-rathod-316, I understood the requirement and this would be my first contribution... Can you please assign this to me..

**Comment by sakshamg1304** [comment]
Hi @withshubh, I can start working on this, can you assign this issue to me ?

**Comment by karan-rathod-316** [comment]
Hi @jangala-laxman, 

Assigning this issue to you. We appreciate your interest in contributing to ToolJet.

**Comment by jangala-laxman** [comment]
Thanks @karan-rathod-316

**Comment by karan-rathod-316** [comment]
Hi @jangala-laxman, For this particular change. We will be happy to test things on our end before merging. Change the required values in widgetConfig file and raise the PR. We'll handle the rest :-)

**Comment by jangala-laxman** [comment]
thanks for the confirmation @karan-rathod-316, will check the changes and do the required...

**Comment by Sufiyan-dev** [comment]
#8462 already fixed it @karan-rathod-316

**Comment by 16achint** [comment]
hi @karan-rathod-316 if nobody working on this issue please assign it to me

**Comment by karan-rathod-316** [comment]
Hi @jangala-laxman. I am going with @Sufiyan-dev's fix since there have been no updates on this in the last two weeks:-).

**Comment by jangala-laxman** [comment]
@karan-rathod-316 , i have already created pull request 2 weeks ago and it was pending for approval

**Comment by karan-rathod-316** [comment]
Hi @jangala-laxman,

Since there were no PRs linked to this issue, we weren't able to figure out if this was done or pending.

I can assign you [#8595](https://github.com/ToolJet/ToolJet/issues/8595) which is very similar in scope if you wish to make your first contribution. Apologies for the mix-up.
