### ISSUE TITLE
Change labels to sentence case for Link component

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#8434]
### Problem

There is an inconsistency in the text casing, some labels under `Properties` and `Styles` tab in the component manager are not in [Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html).

### What is the expected behaviour?

All the labels under the `Properties` and `Styles` tab in the component managers should be in the Sentence case.

### What is the current behaviour?

The below labels are not in Sentence case(changes are only needed in the below labels).

| Current Values       | Expected Values       |
| :------------------- | :-------------------- |
| Link Target        | Link target         |
| Link Text | Link text  |
| Target Type        | Target type         |
| Text Size        | Text size         |
| Text Color        | Text color         |

### How to reproduce the issue?

1. Open ToolJet.
2. Create a new app.
3. Search for the component and drag it onto the Canvas.
4. Click on the component to open the Component Manager in the right sidebar.
5. Examine the labels under both the `Properties` and `Styles` tabs. Some labels are not in sentence case and should be updated accordingly.

### Additional Information

1. Changes are only required in the `widgetConfig.js` file, locate the object which has the related component name in the name key, and make changes only in that particular object.  
**For e.g. for table component, you will make changes in the below object of the widgetConfig.js file:**
```
{
    name: 'Table',
    displayName: 'Table',
    description: 'Display paginated tabular data',
    component: 'Table',
.....
}
```
2. Do not make changes to any other labels, files or components.

### Screenshots or Screencast

**Example** using the table component, items that are not in Sentence case are highlighted in red, these are inconsistent with other labels which are in Sentence case

![image](https://github.com/ToolJet/ToolJet/assets/25361949/a7eca8e0-54b0-4400-a680-12d8d0ff9893)

**Comment by withshubh** [comment]
It's not fixed @VishwajeetRaut - Did you check for link component??


![table-dynamic-column-ToolJet](https://github.com/ToolJet/ToolJet/assets/25361949/a36ff7f9-3e0b-4e84-bb95-69ae47ea8dee)

**Comment by VishwajeetRaut** [comment]
Hey I would like to work on this issue

**Comment by karan-rathod-316** [comment]
Hi @VishwajeetRaut, thank you for interest in contribution to ToolJet. Assigning this to you.

**Comment by 16achint** [comment]
Hi @karan-rathod-316, could you please check out the changes I made

**Comment by karan-rathod-316** [comment]
Hi @16achint Can you link the PR to this issue?

**Comment by 16achint** [comment]
Hi @karan-rathod-316 ,

Please review pull request #8461 at your earliest convenience. 
please try to give me feedback this time i did right or wrong
and Please let me know if anything needs improvement

**Comment by karan-rathod-316** [comment]
Hi @16achint, thank you for your interest in contributing to ToolJet, reviewing your PR.

**Comment by 16achint** [comment]
thank you @karan-rathod-316 and I will keep that in mind : )

**Comment by karan-rathod-316** [comment]
Fixed: [8434](https://github.com/ToolJet/ToolJet/pull/8461)
