### ISSUE TITLE
[docs]: Fix image padding on the Licensing page

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#8454]
### Summary

Images on the [Licensing](https://docs.tooljet.com/docs/org-management/licensing) page have inconsistent padding. 

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/org-management/licensing

### Steps to reproduce the issue

1. Go to the [licensing](https://docs.tooljet.com/docs/org-management/licensing) page
2. Check padding before and after all images. 

### Additional Information

Ensure that there is a same amount of padding/margin before and after all images.

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by NJacksonDev** [comment]
Hi, I would like to work on this. Can you please assign this to me?

**Comment by karan-rathod-316** [comment]
@NJacksonDev Sure. Assigning this to you.

**Comment by karan-rathod-316** [comment]
Hi @NJacksonDev, let us know if there is an update on this issue or in case you have any doubts.

**Comment by karan-rathod-316** [comment]
Closing the issue due to inactivity.
