### ISSUE TITLE
[docs]: Mention about the Env dropdown in the TopBar doc

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#8455]
### Summary

ToolJet now has an `Env` dropdown that allows you to change the environment of the application. Update all the screenshots and add a section for the `Env` dropdown in the TopBar page. 

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/app-builder/topbar/

### Steps to reproduce the issue

1. Open ToolJet docs
2. Go to the [topbar](https://docs.tooljet.com/docs/app-builder/topbar/) page

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Nitz2611** [comment]
assign me please

**Comment by karan-rathod-316** [comment]
Hi @Nitz2611, assigning this to you. We appreciate your interest in contributing to ToolJet.

**Comment by Nitz2611** [comment]
#8470 @karan-rathod-316 I have added pull request. Let me know if it needs any changes.

**Comment by karan-rathod-316** [comment]
Sure @Nitz2611 This is in review.

**Comment by Abhishek-90** [comment]
If this issue is still up for grabs, kindly assign it to me.

**Comment by karan-rathod-316** [comment]
Hi @Abhishek-90, assigning this to you. Happy coding:-).

**Comment by karan-rathod-316** [comment]
Hi @Abhishek-90 

Here's the doc for more context on Environments.

[https://docs.tooljet.com/docs/release-management/multi-environment#environments](https://docs.tooljet.com/docs/release-management/multi-environment#environments)

**Comment by Abhinav-CHD** [comment]
Hi is someone still working on this issue? If not, could you assign this to me?

**Comment by karan-rathod-316** [comment]
Hi @Abhinav-CHD, Let's give some more time to the current assignee to work on the issue :-). Will be happy to re-assign if there is no progress.

**Comment by karan-rathod-316** [comment]
Hi @Abhinav-CHD, since there is no progress on the issue. I can re-assign this issue if you are still looking to pick it up.

**Comment by Abhinav-CHD** [comment]
Hi @karan-rathod-316, you can assign this issue to me, I would be more than happy to work on it

**Comment by karan-rathod-316** [comment]
Hi @Abhinav-CHD, sure. Assigning this to you.

**Comment by Abhinav-CHD** [comment]
Hi @karan-rathod-316, could you please provide information about the resolution and size of gifs and images? Should they all adhere to the previous specifications?

**Comment by 2001asjad** [comment]
Hi @Abhinav-CHD, thanks for working on the issue.
For the images, the ideal size would be within 400 kb, and for gifs,  a size under 1.5 MB is preferred. We suggest you avoid gifs and use images if possible; otherwise, go with the gifs.

**Comment by karan-rathod-316** [comment]
Closed in #9334
