### ISSUE TITLE
[docs]: Update Dashboard page

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#8456]
### Summary

The [Conditions for workspace slug](https://docs.tooljet.com/docs/dashboard#conditions-for-workspace-slug) section needs to be updated.

**Currently, the `Conditions for workspace slug` section has the following text:**

- The workspace slug should be unique.
- The workspace slug should not contain any special characters except -.
- The workspace slug should not contain any spaces.
- The workspace slug should not contain any capital letters.
- The workspace slug should not be empty.

**Replace it with the below text to make it more concise and ensure that it is not formatted as a bullet point:**

The workspace slug must be unique, contain no special characters except hyphens, no spaces, no capital letters, and cannot be empty.

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/dashboard#conditions-for-workspace-slug

### Steps to reproduce the issue

1. Open ToolJet docs.
2. Go to the Dashboard page. 
3. Navigate to the [Conditions for workspace slug](https://docs.tooljet.com/docs/dashboard#conditions-for-workspace-slug) section.

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by raghurambachu** [comment]
please assign this issue to me.

**Comment by ketansahugit** [comment]
Please close this issue as the changes that you suggested are already there on the site.
