### ISSUE TITLE
[Table component] option to select all rows (Fx)

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#8475]
### Is your proposal related to a problem?

Currently, there is no option to select all the rows on the table programmatically after enabling the bulk selection.

### Describe the solution you'd like

Add an option to select all the rows on the table programmatically. Including the Fx.

**Comment by iamabhshk** [comment]
Hii, @withshubh Can I look into this?

**Comment by nakulnagargade** [comment]
This issue is duplicate of https://github.com/ToolJet/ToolJet/issues/8668. Hence closing this issue.
