### ISSUE TITLE
Query errors must show exact reason for error instead of 'Internal Server error' or 'Query could not be completed' or 'Something went wrong' in the debugger

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#8492]
**Enhanced Solution for placement of error messages**
Developer: Kartik Gupta
1. Push both the preview and run query error messages to the debugger.
2. Remove the display of pop-up messages in the editor for both preview and run queries.
3. Ensure there is no UX difference for preview and run query error messages inside the debugger.
4. Show only user-generated messages (e.g., "Query success") in pop-ups, while all system error messages should be pushed to the debugger.

**Solution for detailed error messages**
Developer: Johnson
### Is your proposal related to a problem?

Presently, whenever a query fails, either of the two messages are shown in a toast:

`Internal Server error`
`Query could not be completed`
`Something went wrong` (When RunJS/RunPy fails)

This is not a well specified error message.

### Describe the solution you'd like

Instead of those three static messages, the exact error message should be shown in the toast.

The exact error message should be shown in the debugger entry as well.

**Comment by GrowwithNaveen** [comment]
Push all the error messages to debugger, UI to be finalized.
