### ISSUE TITLE
Update the User label in Groups under Workspace Settings

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#8500]
### What is the expected behaviour?
Under `Workspace Settings`>`Groups`. The `User` tab next to `Apps` should have `Users` as the header.

### What is the current behaviour?
Currently the tab header reads `User`.

### How to reproduce the issue?

1. Go to Workspace Settings
2. Click on Groups

### Screenshots or Screencast
![image](https://github.com/ToolJet/ToolJet/assets/58169101/a92fb38d-d4e4-4cd2-8763-08f6e65ac630)

### Any possible solutions?
Replace the label for the `User` tab with `Users`

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by ayushjha119** [comment]
@karan-rathod-316  can i  take this issue??

**Comment by Avon11** [comment]
@karan-rathod-316 can I solve this?

**Comment by Avon11** [comment]
Hi @karan-rathod-316 I have raised PR to fix this issue. If any change required, please let me know.
https://github.com/ToolJet/ToolJet/pull/8513

**Comment by karan-rathod-316** [comment]
Hi @Avon11 , assigning this to you. We appreciate your interest in contributing to ToolJet.

**Comment by karan-rathod-316** [comment]
Closing the issue with this PR:
https://github.com/ToolJet/ToolJet/pull/8513
