### ISSUE TITLE
[refactor]: Add Border Radius property to the Chart component's configuration options

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#8502]
### What is the expected behaviour?
- Users should be able to set the `Border radius` property for the Chart component. 
- The default `Border radius` should be 4.

### What is the current behaviour?
Currently, the Chart component's configuration options don't have the`Border radius` property. 

### How to reproduce the issue?
1. Drag and drop a Chart component
2. Select it, and check the properties under the Styles tab - you won't find the `Border radius` property which is available for other components like Table.

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by ayushjha119** [comment]
@karan-rathod-316 can i try to solve this issue ??

**Comment by Nitz2611** [comment]
assign me

**Comment by Avon11** [comment]
@karan-rathod-316 I'll be happy to pick up.

**Comment by Nitz2611** [comment]
#8511

**Comment by karan-rathod-316** [comment]
Hi @Avon11, assigning this to you and checking the PR.

**Comment by karan-rathod-316** [comment]
Hi @ayushjha119, Since this is labelled as a `good-first-issue`, I have assigned this to a first-time contributor :-). Thank you so much for your interest in contributing to ToolJet.

**Comment by karan-rathod-316** [comment]
Hi @Avon11, I have assigned this to @Nitz2611. But we do have other open issues that are suitable for first-time-contributors. Feel free to look and let me know if something interests you.

**Comment by ayushjha119** [comment]
Okk no issue @karan-rathod-316 but i have already raised a PR

**Comment by Avi2492** [comment]
I am new so can i start working on this

**Comment by MHRSRoni** [comment]
Is the issue solved? I want to contribute.

**Comment by HermanBide** [comment]
Is the issue solved? I want to contribute.

**Comment by karan-rathod-316** [comment]
Hi @HermanBide, assigning this issue to you. Thank you for your interest in contributing to ToolJet:-)

**Comment by karan-rathod-316** [comment]
Hi @HermanBide, closing this issue since this is done. Feel free to look at other issues that might interest you:-),
