### ISSUE TITLE
Ability to rename excel files downloaded from Table component

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#8505]
### Describe the solution you'd like
Currently, when we download an Excel sheet from the Table component by clicking the download button, the downloaded file automatically gets the name 'all-data'. We should have a feature that allows you to give a custom name to these Excel files when you download them.

### If the feature is approved, would you be willing to submit a PR?
No

**Comment by johnsoncherian** [comment]
Fixed under issue: https://github.com/ToolJet/ToolJet/issues/8725

**Comment by GrowwithNaveen** [comment]
Fixing this with: https://github.com/ToolJet/ToolJet/issues/8725
