### ISSUE TITLE
Minor alignment issue

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#863]
The blue bottom border of the query editor should align with the border of the header.

![image](https://user-images.githubusercontent.com/7828962/135209280-f55502dd-ee78-49d5-81c5-a33ef1a84e30.png)

Steps to reproduce: 
a) Click on the + icon to add a new data query
b) Try switching between the general and advanced tabs of the query editor

**Comment by satyamgupta1495** [comment]
Hey Navaneeth, Could you please assign me this issue?

**Comment by Navaneeth-pk** [comment]
Assigned, thanks for your interest in contributing to ToolJet.
@satyamgupta1495

**Comment by Navaneeth-pk** [comment]
Unassigning the issue as there is no update for the last 10 days.
@satyamgupta1495

**Comment by rutulganatra** [comment]
I want to work on this issue. Can you please assign it to me?
