### ISSUE TITLE
Update the confirmation message when revoking access to a data source for a group

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#8658]
### What is the expected behaviour?
When you revoke access to a particular data source for a group, the confirmation message should be 

`Are you sure you want to revoke the group's access to this data source - <data source name>?`

`<data source name>` should be replaced with the actual data source name.

### What is the current behaviour?
Currently, when we revoke access to a data source for a group, we get the below message, which is misleading. 
`Are you sure you want to delete this data source - <data source name>?`

### How to reproduce the issue?
1. Go to Workspace Settings > Groups
2. Select a group and go to the `Datasources` tab
3. Add a data source and then remove it
4. When you remove the data source, you will get a confirmation message - `Are you sure you want to delete this data source - <data source name>?`

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2024-01-30 at 11 58 09 AM" src="https://github.com/ToolJet/ToolJet/assets/58169101/5b411464-c4f8-492c-a84d-0e4724bbd12e">

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by FurquanAnwer** [comment]
@karan-rathod-316 please assign this issue to me !

**Comment by karan-rathod-316** [comment]
Hi @FurquanAnwer, assigning this issue to you. Thank you so much for your interest in contributing to ToolJet.

**Comment by gsmithun4** [comment]
EE issue
