### ISSUE TITLE
AI Copilot to help builders build tools

### ISSUE THREAD

**Issue by Matx00** [ToolJet/ToolJet#8660]
### Is your proposal related to a problem?

Even if TooJet is simple to use, still the learning and development phases could be greatly improved with the use of an AI Copilot

### Describe the solution you'd like

 I was wondering if you could integrate an AI Copilot to assist who are building an internal tool to build from a prompt. in natural language. Two examples to explain better what I mean are https://v0.dev/ and https://www.airplane.dev/autopilot. Probably this could be done by asking an LLM to generate a React components and directly integrate it in the project when asked.
I am not an expert of this codebase, so I can't be more specific than this

### Describe alternatives you've considered
None

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by Navaneeth-pk** [comment]
We are working on something similar internally as an extension of our Copilot feature.

**Comment by Matx00** [comment]
> We are working on something similar internally as an extension of our Copilot feature.

Sorry, what do you mean?

**Comment by Navaneeth-pk** [comment]
https://docs.tooljet.com/docs/tooljet-copilot/
