### ISSUE TITLE
AI Product Copilot for tool final users

### ISSUE THREAD

**Issue by Matx00** [ToolJet/ToolJet#8662]
### Is your proposal related to a problem?

Even if there are greater builders out there able to design functional and simple tools, still many users prefer to directly ask to do something instead of learning to use the tool.

### Describe the solution you'd like

 I was wondering if you could integrate an AI Product Copilot to assist users of the tools built with ToolJet. Essentially, this should be a conversation (text, voice) chatbot able to help the user perform the tasks present in the platform and eventually execute them as an AI agent. This https://opencopilot.so/ is a great example of an open source tool that could be integrated into ToolJet in order to achieve this goal.
I am not an expert of this codebase, so I can't be more specific than this

### Describe alternatives you've considered
None

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by Navaneeth-pk** [comment]
Sorry, this won't align with our roadmap.

**Comment by Matx00** [comment]
> Sorry, this won't align with our roadmap.

:(
