### ISSUE TITLE
Adding capability in query builder to search by variable name

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#8677]
### Is your proposal related to a problem?

Yes, currently we do not have an option for selecting variable names inside the query builder. 

This feature request is from one of our [users](https://tooljet.slack.com/archives/C05S9PXGS66/p1701179395708539).

### Describe the solution you'd like
Allow searching for variable names inside the query builder.

### If the feature is approved, would you be willing to submit a PR?
No

**Comment by GrowwithNaveen** [comment]
The usability of the feature is low, as within queries we cannot search for particular variables. Deprioritizing now. Will check again with the query builder revamp.

**Comment by shubh22** [comment]
Duplicate
