### ISSUE TITLE
The dashboard needs a refresh to get the add folder icon(`+`) back once the search icon is clicked

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#8679]
### What is the expected behaviour?
When you click on the search button and then click somewhere else without typing, the cross button should show to close the search bar. 

<img width="457" alt="Screenshot 2024-01-31 at 8 32 25 PM" src="https://github.com/ToolJet/ToolJet/assets/58169101/a150791b-315e-424b-8745-79bd477e0706">

<img width="457" alt="Screenshot 2024-01-31 at 8 32 51 PM" src="https://github.com/ToolJet/ToolJet/assets/58169101/62dcab7a-bd6f-4f75-821c-d4734d2fa7a2">

### What is the current behaviour?
Once the search icon is clicked and we click somewhere else without typing anything in the search bar, the cross button does not show up.  Because of this, the dashboard needs a refresh to get the add folder icon(`+`) back. 

<img width="457" alt="Screenshot 2024-01-31 at 8 33 32 PM" src="https://github.com/ToolJet/ToolJet/assets/58169101/50695082-08d3-4407-9eda-e3375ffab72b">

### How to reproduce the issue?

1. Go to the dashboard
2. Click on the search icon
3. Click somewhere else without entering any text in the search bar

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by developwithabhinav** [comment]
Hi, I got it, I want to work on this one.
Thanks

**Comment by 7pixel-cl** [comment]
Hey, how are you guys? If possible, let me take this one.

**Comment by iAdtya** [comment]
Hii Karan plz reassign the issue to me i have coded the solution but the only problem i am having trouble setting up project locally can i get some guidance on how to solve this error so that i can raise a pr 
![Screenshot 2024-02-05 200947](https://github.com/ToolJet/ToolJet/assets/93979441/c6ec4e4c-65e0-482b-b442-00f8add1ae44)

**Comment by Rohankumarmenu** [comment]
Hello Karan, can you  assign this task to me.

**Comment by karan-rathod-316** [comment]
Hi @7pixel-cl, has there been any progress on this issue??

**Comment by karan-rathod-316** [comment]
Hi @Rohankumarmenu, I am re-assigning this to you since we haven't received any response from @7pixel-cl.

**Comment by HermanBide** [comment]
has this bug been fixed?

**Comment by karan-rathod-316** [comment]
Hi @HermanBide, this has been assigned to @Rohankumarmenu last week. I can re-assign it to you in case there is no progress by the end of this week. Let me know if you would be interested in picking it up.

**Comment by Rohankumarmenu** [comment]
Hello @karan-rathod-316 ,while I am running it on my local system using docker .I had gone through and followed the given docker documentation steps for set up. I am getting error "Database Connection error ".Can you help me with this?

**Comment by Rohankumarmenu** [comment]
Hello @karan-rathod-316 ,while I am running it on my local system using docker, i am getting error "Database Connection error ".I had gone through and followed the given docker documentation steps for set up. Can you help me with this?

**Comment by iAdtya** [comment]
@karan-rathod-316 even i got the same error i posted it above, i even tried it cloud postgres database!! but the error persists

**Comment by karan-rathod-316** [comment]
Hi @adishM98, Can you please check the issue that @Rohankumarmenu is facing?

**Comment by Just-A-Pixel** [comment]
Is this still being worked on? I'd like to pick this up if no one is working on it.

**Comment by karan-rathod-316** [comment]
Hi @Just-A-Pixel, @Rohankumarmenu is working on it, and we will give him some more time to resolve the issue :-).

**Comment by 609harsh** [comment]
Is someone still working on this?

**Comment by karan-rathod-316** [comment]
Hi @609harsh, assigning this to you. Happy coding :-)

**Comment by Rohit-Singh-Rawat** [comment]
Hi @karan-rathod-316, issue resolved. Please review and share feedback. Thanks!

**Comment by 609harsh** [comment]
Hi @karan-rathod-316  i have resolved the issue. I have created a pull request #9020 , but it seems there is some problem with PR. Since its my first contribution please look into it and guide me for the same

**Comment by karan-rathod-316** [comment]
@609harsh No worries. We are reviewing your PR.

**Comment by Rohit-Singh-Rawat** [comment]
No problem, and I am sorry, will positively ask for assigning next time. Pls consider if original assignee not able to complete it.
Thanks.
