### ISSUE TITLE
Consistent spacing for datasource dynamic forms

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#868]
![image](https://user-images.githubusercontent.com/7828962/135288651-1eb51fcc-73a6-4930-8bc9-bf54bf78c395.png)

The top margin of the toggle switch is not consistent with rest of the fields.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by Navaneeth-pk** [comment]
Assigned.
@himanshu007-creator

**Comment by himanshu007-creator** [comment]
@Navaneeth-pk  Hi, I am unable to set up the project on my machine. I have read the documentation but none of the methods works for me ( docker/ubuntu). So please assign this issue to someone else.
In case changes can be made to the front-end alone, without setting up the project, do let me know.

**Comment by Navaneeth-pk** [comment]
Can you please explain the issue that you are facing while setting up? We can help. 
@himanshu007-creator

**Comment by Navaneeth-pk** [comment]
Can you please explain the issue that you are facing while setting up? We can help. 
@himanshu007-creator

**Comment by Navaneeth-pk** [comment]
Can you please explain the issue that you are facing while setting up? We can help. 
@himanshu007-creator

**Comment by akshitarora921** [comment]
Hi, can I work on this?

**Comment by Navaneeth-pk** [comment]
Since @himanshu007-creator is not able to set up the project, assigning to @akshitarora921
