### ISSUE TITLE
Bug in pagination component

### ISSUE THREAD

**Issue by tuutoo** [ToolJet/ToolJet#8684]
### Version Information
v2.16.1
### What is the expected behaviour?

Expect it to have a max page number e.g. 10, after 10 pages you click the next page button and the pages update.
It should look like this one. Page displayed should have a fixed number, e.g. no more than 10
1... 5, **6**, 7 ... 25

<img width="556" alt="image" src="https://github.com/ToolJet/ToolJet/assets/9068314/e3c5031e-16b0-40ea-9835-d59de7bd6d4f">
<img width="617" alt="image" src="https://github.com/ToolJet/ToolJet/assets/9068314/8be9752b-adb6-4b1b-aad1-be235d65f944">

### What is the current behaviour?

If the total pages assigned hundreds, it will even longer.
![image](https://github.com/ToolJet/ToolJet/assets/9068314/cd4c34d4-e956-405a-8218-7a5127d1c6a9)

### How to reproduce the issue?

1. Assign a big value to the total pages.
![image](https://github.com/ToolJet/ToolJet/assets/9068314/e1a518ac-c9a0-4640-a0ae-853658bfdf3f)

**Comment by GrowwithNaveen** [comment]
Similar bug reported in past: https://github.com/ToolJet/ToolJet/issues/6017
Will be taking this in Appbuilder 1.6

**Comment by GrowwithNaveen** [comment]
### Solution:
1. By default, the component will display 5 pages only, regardless of the "Number of pages" value set in properties. Even if the user changes this value to a higher number, like 25, only the first 5 pages will be initially visible.
2. Users can navigate to additional pages beyond the initial 5 by using the direction icons provided in the interface.
3. The overall size of the component will remain fixed, regardless of the number of pages defined in the properties. This ensures consistency in the user experience.
4. Attaching the screen shot for reference,
![image](https://github.com/ToolJet/ToolJet/assets/81761482/24f934a3-bdb9-499b-9796-dfe97528cd2e)
