### ISSUE TITLE
Bug : Components are not rendering in the mobile view for launched apps

### ISSUE THREAD

**Issue by manishkushare** [ToolJet/ToolJet#8704]
### Version Information
v2.27.7
### Environment
Development

### What is the expected behaviour?
All the components should be visible on the mobile view as well

### What is the current behaviour?
Components are not visible on the mobile view for launched apps.

### How to reproduce the issue?

1. Create a new app
2. Drop any component on the canvas
3. Allow dragged component to be visible in the mobile view as well from its widget inspector
4. Now, release the app, go to the dashboard, and launch that particular app.
5. On the launched app, open the inspector and change the layout to mobile. You can see the component will be rendered. But, now refresh the page, and the component is no longer visible.

### Screenshots or Screencast
[error-in-mobile-view.webm](https://github.com/ToolJet/ToolJet/assets/37823141/cac41903-f396-402b-b3f8-689d1c21b2bb)

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by shizzgar** [comment]
Still not working...
