### ISSUE TITLE
Introducing cell density property in table

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#8706]
### Is your proposal related to a problem?
Currently, the cell density in table is simple and needs more enhancement.

### Describe the solution you'd like
Introducing the following:
1. Regular - Regular (existing one)
2. Condensed - Condensed (existing one)
3. Content wrap - New. 
       1. Auto - Default (To handle backward compatibility)
       2. Custom - Variable height input by user.

Design file [here](https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?type=design&node-id=10970-97858&mode=design&t=xhhnVAHTGZ0qtdtr-4)
### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by johnsoncherian** [comment]
Closed in PR #9415
