### ISSUE TITLE
Creating workflow bug

### ISSUE THREAD

**Issue by Milange12** [ToolJet/ToolJet#8733]
### Version Information

Version 2.28.2-ee2.13.0

### Environment

ToolJet  Docker compose 

### What is the expected behaviour?

  Creating a workflow without errors. Working with databases inside workflow.

### What is the current behaviour?

  After creating workflow i got this error:
Tooljet-app  | error: error: invalid input syntax for type uuid: "true"
Tooljet-app  |     at /app/server/node_modules/pg/lib/client.js:526:17
Tooljet-app  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
Tooljet-app  |   length: 99,
Tooljet-app  |   severity: 'ERROR',
Tooljet-app  |   code: '22P02',
Tooljet-app  |   detail: undefined,
Tooljet-app  |   hint: undefined,
Tooljet-app  |   position: undefined,
Tooljet-app  |   internalPosition: undefined,
Tooljet-app  |   internalQuery: undefined,
Tooljet-app  |   where: undefined,
Tooljet-app  |   schema: undefined,
Tooljet-app  |   table: undefined,
Tooljet-app  |   column: undefined,
Tooljet-app  |   dataType: undefined,
Tooljet-app  |   constraint: undefined,
Tooljet-app  |   file: 'uuid.c',
Tooljet-app  |   line: '134',
Tooljet-app  |   routine: 'string_to_uuid'
Tooljet-app  | }

I think this is not that important for tooljet proper usage, couse i can create workflows, create run.js or if statements, run sql statements in my postgress data source.

But then i try to change query UI is become broken, example below:

### How to reproduce the issue?

1. creating workflow.
2. After click on postgresql1:

### Screenshots or Screencast

  
1. ![image](https://github.com/ToolJet/ToolJet/assets/91943369/c62773dc-b61e-4d05-9f6a-07268e8150ad)
2. ![image](https://github.com/ToolJet/ToolJet/assets/91943369/7bfeb6fe-6402-4df5-b026-1e485fec7bf0)

P.S. Thanks for ur awesome work!
Best Regards

**Comment by ganesh8056** [comment]
The problem has been resolved in version **v2.28.4-ee2.14.0**
