### ISSUE TITLE
Upgrade react from v16 to v18

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#878]
https://reactjs.org/blog/2020/10/20/react-v17.html

![image](https://user-images.githubusercontent.com/12490590/135429822-2e25dc93-9b7a-44c9-9998-b8aa7c9f2d17.png)

Pretty straightforward upgrade.

Majorly because react 17 removes event pooling and other perf enhancements, less memory consumption etc.
https://reactjs.org/blog/2020/08/10/react-v17-rc.html#no-event-pooling

Update 2nd Sept 2022: 
following guide from https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

**Comment by febinct** [comment]
https://github.com/airbnb/react-dates/blob/master/package.json
is not updated to 17 yet

**Comment by am-a-man** [comment]
hey,
I would like to work on this, could you assign it to me?

**Comment by BabbarRaghav** [comment]
can you please assign me this?

**Comment by sidbelbase** [comment]
tasks need to be assigned to work or I can start on working on this?

**Comment by WadekarPrashant** [comment]
Hey, can I work on this issue? Please assign it to me.
@TheLearneer @sidbelbase @am-a-man

**Comment by owengaspard** [comment]
@withshubh If someone is needed to work on this, I would be happy to.
