### ISSUE TITLE
Table column type: Text

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#8789]
PRD: https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-17676

Design: https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?type=design&node-id=9480-189961&mode=design&t=yk19JifpIFwXgeDM-4

**Comment by johnsoncherian** [comment]
Fixed in #8442
