### ISSUE TITLE
Table column type: Image

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#8790]
PRD: https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-15096
Design: https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?type=design&node-id=9564-280062&mode=design&t=yk19JifpIFwXgeDM-4

**Comment by johnsoncherian** [comment]
Fixed in PR #8442
