### ISSUE TITLE
Make users table headers more legible in dark mode

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#884]
### Is your proposal related to a problem?

Presently the column titles in users listing table is not very legible in dark mode:
![image](https://user-images.githubusercontent.com/20333972/135805627-64fd3bb9-893b-4db3-a803-ac29dcf9d918.png)

### Describe the solution you'd like

Make it more legible, perhaps like this:
![image](https://user-images.githubusercontent.com/20333972/135805731-cbd79096-d98c-4ba1-9979-d3df30aa1303.png)

**Comment by Ajinkya2000** [comment]
Let me work on this.

**Comment by mslourens** [comment]
@sherfin94 can you please assign this issue to me?
