### ISSUE TITLE
Inconsistent checkbox behavior in list view parent when adding child checkboxes

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#8840]
We're encountering an issue with checkboxes in list view parent components when adding child checkbox components. The UI behaves unexpectedly (see attached video grab for reference).

https://github.com/ToolJet/ToolJet/assets/81761482/e8c172a2-4422-42a5-9098-31fdedb77430

**Comment by munanadi** [comment]
If you notice, the image component also doesn't show up in the tree viewer on the sidebar.

<img width="844" alt="Screenshot 2024-02-20 at 5 25 33 PM" src="https://github.com/ToolJet/ToolJet/assets/22261173/2b8b894b-7022-4db0-9a2e-e3fead409013">


1. Should this be the case? If not, then we need to show the image components on the side tree view as well.
2. Also, The PR linked to this issue #8855 doesn't fix the dynamic update of the sidebar as components are removed. 

I can help out here I guess. Let me take a look?
