### ISSUE TITLE
Make instruction to adjust widget search term legible in darkmode

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#885]
### Is your proposal related to a problem?

Instruction to adjust widget search term is not legible in darkmode
![image](https://user-images.githubusercontent.com/20333972/135806761-7b396fdb-0de2-4ca1-b10b-4859db845179.png)

### Describe the solution you'd like

Make it more legible, perhaps like this:
![image](https://user-images.githubusercontent.com/20333972/135806940-74df348b-f79d-4b08-aeaa-5ba1c283077c.png)

**Comment by iAmPriyam** [comment]
I'd like to fix this issue.
