### ISSUE TITLE
Make widget close button more legible in dark mode

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#886]
### What is the expected behaviour?

Widget close button should be more legible in darkmode, perhaps like this:
![image](https://user-images.githubusercontent.com/20333972/135807339-886f155e-f793-41e4-81a2-18edb6f45474.png)

### What is the current behaviour?

![image](https://user-images.githubusercontent.com/20333972/135807269-0c657217-f536-43df-a9b7-a1f28ba9d66b.png)
### How to reproduce the issue?

1. Add a button widget
2. Click on its handle to display the inspector on the right panel
3. Look at the close button on the inspector

**Comment by devon221** [comment]
Can you share the file locations ?😃

**Comment by sherfin94** [comment]
@devon221 Everything you need to set it up and start contributing is available on the `Contributing guide` section in our [documentation](https://docs.tooljet.io/docs/intro/)!

**Comment by ritikbheda** [comment]
Hi @sherfin94 I would like to work on this issue.

**Comment by akshitarora921** [comment]
Can I work on this?

**Comment by sherfin94** [comment]
@akshitarora921 Sure, thank you. Assigned you.
