### ISSUE TITLE
Dashboard side panel scrolls up and down

### ISSUE THREAD

**Issue by Mekhla-Asopa** [ToolJet/ToolJet#8877]
### What is the expected behaviour?
The dashboard side panel should be fixed.

### What is the current behaviour?
Dashboard side panel scrolls up and down.

### How to reproduce the issue?

1. Login with valid credentials
2. Create more than 10 apps to get the pagination footer
3. Mouse hover on the dashboard right panel and move vertically 
4. Navigate to the database page
5. Create a table with more than 50 records
6. Repeat step 4

### Screenshots or Screencast
<img width="1440" alt="Dashboard_panel" src="https://github.com/ToolJet/ToolJet/assets/59684099/0a66439d-e695-46ae-a177-831d4ad8abb3">

<img width="1440" alt="dashboard_panel_app" src="https://github.com/ToolJet/ToolJet/assets/59684099/d0105b36-7172-4daf-95e7-ece2f18deaf4">

**Comment by maniksharma424** [comment]
Hi Mekhla 
Can i pick this issue ?
