### ISSUE TITLE
CSP issue (upgrade-insecure-requests)

### ISSUE THREAD

**Issue by ShankyJS** [ToolJet/ToolJet#890]
### Version Information

I used [tooljet-ce:latest](https://hub.docker.com/layers/tooljet/tooljet-ce/latest/images/sha256-13957585ae9ef9f35012abfa8b576c0441f3ceb493eeb201f9061f3c4a97293d?context=explore)

### Environment

Kubernetes deployment.

### What is the expected behaviour?

After deploying the tooljet-ce image to our GKE cluster I created all the configurations to use port 80 (so not HTTPS enabled) and noticed that all the requests from the client are being redirected to HTTPS so the Client is failing on my end. 

### What is the current behaviour?

Tooljet Client CSP should be able to serve the static files over HTTP and HTTPS should not be a requirement in order to make the client work.

### How to reproduce the issue?

1. Deploy tooljet-ce in a GKE cluster.
2. Create Service and Ingress to Expose the service in port 80.
3. Navigate to the endpoint that you exposed on port 80, you will get a blank page.

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/17713708/135877578-be872406-ce99-493c-803a-f0b76d91b404.png)

### Please provide any traces or logs that could help here.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests

### Any possible solutions?

Disable upgrade-insecure-requests on Helmet in order to prevent rewriting the URLs from HTTP to HTTPS.

### Can you identify the location in the driver source code where the problem exists?

Not sure.

### If the bug is confirmed, would you be willing to submit a PR?

Not at this moment.

**Comment by Navaneeth-pk** [comment]
Thanks for reporting this issue. Fixed the issue and pushed it as a hotfix ( https://github.com/ToolJet/ToolJet/commit/ee1e59dee5150359ebd51ebdc30dd15a57bf211c).

**Comment by ShankyJS** [comment]
Confirmed that now it's working in my end and Tooljet now supports working without needing to use HTTPs!

Great work, thank you.
