### ISSUE TITLE
AWS S3 DATASOURCE

### ISSUE THREAD

**Issue by renegarci** [ToolJet/ToolJet#8947]
### Version Information
2.30.4

### Environment

    ToolJet over Aws ECS

### What is the expected behaviour?

  Create an AWS S3 DATASOURCE and using it in my application to read all buckets

### What is the current behaviour?

  Selecting any option from the selector (read buckets by example) and clicking in Run button, it is throwing the error:
  
  status:"failed"
message:"Internal server error"
description:"Region is missing"
data:{} 0 keys

But the region was provided when creating the datasource, and the test button over there was working well.

### How to reproduce the issue?

1. Create an AWS S3 DATASOURCE
2. Test the datasource from the creation form.
3. Use the datasource in some application, and just to proceed click Run button

### Screenshots or Screencast
![Screenshot 2024-02-28 at 14 55 15](https://github.com/ToolJet/ToolJet/assets/65568700/18dbcef0-552d-400d-82af-4a5e5f986654)

### Please provide any traces or logs that could help here.
status:"failed"
message:"Internal server error"
description:"Region is missing"
data:{} 0 keys

### Any possible solutions?
i dont know

### Can you identify the location in the driver source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by akshaysasidrn** [comment]
@renegarci We were not able to replicate this. Could you help to try this out
1. Goto the data sources dashboard and re-enter the connection options
2. Open your browser's network tab to monitor the subsequent requests that are bound to happen in the next steps
3. Click on test connection, Take a screenshot of the corresponding request body and response to share here. 
3. Click on save. Take a screenshot of the corresponding request body and response to share here. 
4. Try rerunning the query

Note: Please mask sensitive creds in the screenshot you'd paste here.

**Comment by renegarci** [comment]
@akshaysasidrn im doing the same test in my current tooljet-ce:CE-LTS-2.50.24 version installed in aws ecs, and the issue is the same, my bucket and keys are in us-east-1, im testing in chrome and firefox in private tabs no cache, but always the same.  Could you tell me how you can got a valid test? 

I mean over which aws region are your bucket and keys and your browser pls, because i dont get a single good test using this plugin, also using the s3 template app, is throwing other distintc error :(
