### ISSUE TITLE
Page not found on this "https://docs.tooljet.com/docs/setup/docker-local"

### ISSUE THREAD

**Issue by edendattox** [ToolJet/ToolJet#8961]
### What is the expected behaviour?
It should show the the docker command to run in the local machine.

### What is the current behaviour?
Its currently showing the Page not found

### How to reproduce the issue?
1. Go to this Url [https://docs.tooljet.com/docs/contributing-guide/setup/docker/](url).
2. In info section click on 'here' link.
3. it will take you to this [https://docs.tooljet.com/docs/setup/docker-local](url) which is showing page not found.

### Screenshots or Screencast
<img width="1440" alt="Screenshot 2024-03-01 at 6 33 52 PM" src="https://github.com/ToolJet/ToolJet/assets/74775804/0830069d-292e-428b-8050-c2f1a5e86868">

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by karan-rathod-316** [comment]
This is fixed in this PR: 
[https://github.com/ToolJet/ToolJet/pull/8966](https://github.com/ToolJet/ToolJet/pull/8966)
