### ISSUE TITLE
Auto-filling workspace URL slug based on workspace name  

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#8978]
When a user enters the name of their workspace- it would be helpful to pre-fill the workspace name in the slug input. 
Eg. Workspace name- `My workspace` 
Workspace slug- `my-workspace` 

The user should still be allowed to edit the slug after, this is only set as default pre-fill for ease of UX

![image](https://github.com/ToolJet/ToolJet/assets/127945292/79df2468-dcf9-4d72-a5b2-b13bf9c9809a)

**Comment by 609harsh** [comment]
can you please assign this issue to me?

**Comment by nechalmaggon** [comment]
Hi @609harsh Thank you for expressing your interest in contributing! Unfortunately, this issue will be handled internally. Do have a look out on issues with the label `up-for-grabs` -those are the ones open to the community!

**Comment by 609harsh** [comment]
Sure and Thanks for the info
