### ISSUE TITLE
Docker image does not start correctly when using network mode "host"

### ISSUE THREAD

**Issue by stefan-girlich** [ToolJet/ToolJet#9007]
### Environment
MacOS, Docker v20.10.23, build 7155243

### What is the expected behaviour?
When I add `--network host` as a launch parameter, ToolJet should start successfully and allow accessing services on `localhost`.

### What is the current behaviour?
Opening `http://localhost:80` in the browser results in `ERR_CONNECTION_REFUSED`

### How to reproduce the issue?

Run Docker command from [docs](https://github.com/ToolJet/ToolJet/?tab=readme-ov-file#try-using-docker), add `--network host` parameter:
docker run -d \
  --name tooljet \
  --restart unless-stopped \
  -p 80:80 \
  --network host \
  --platform linux/amd64 \
  -v tooljet_data:/var/lib/postgresql/13/main \
  tooljet/try:latest

### Please provide any traces or logs that could help here.
[docker_log.txt](https://github.com/ToolJet/ToolJet/files/14508283/docker_log.txt)

### Any possible solutions?
The logs show indefinite spawning and killing of `postgrest` processes. This also occurs when (successfully) running the container without `--network host`, so i am not sure if this is related to the original issue.

### Can you identify the location in the driver source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
Happy to help if I can

**Comment by adishM98** [comment]
Hi @stefan-girlich, 

Early docker desktop did not support `--net host` on mac. They recently pushed an update. Could you try to upgrade docker desktop to version 4.29.0. 

Reference from issue - https://github.com/docker/roadmap/issues/238#issuecomment-2044688144

**Comment by adishM98** [comment]
Closing the issue. Please let us know if you are still facing issues.
