### ISSUE TITLE
Selecting the copied component by default when copy pasting components

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9016]
**Current behavior:**  When copying and pasting components, the parent component remains selected by default, not the copied child component. Attaching a screen grab for reference

**Expected behavior:** After pasting, the copied child component should be automatically selected.
Reasoning: Selecting the copied child component directly after pasting improves accessibility and simplifies further editing.

https://github.com/ToolJet/ToolJet/assets/81761482/c11dce8d-6261-4950-8d6b-e8f21a90c6f1

**Comment by Rohit-Singh-Rawat** [comment]
Hello @GrowwithNaveen, I'm interested in addressing this issue.

**Comment by GrowwithNaveen** [comment]
Check in Grid PR once.
