### ISSUE TITLE
Initial check on frontend for min length password should be done

### ISSUE THREAD

**Issue by 609harsh** [ToolJet/ToolJet#9037]
### Environment
Tooljet web

### What is the expected behaviour?
Once a user clicks on login if password is less than 5 characters error message should be displayed or login button should only be active if password length is >=5 characters. (similar to signup page)

### What is the current behaviour?
api call is made even when password is less than 5 characters

### If the bug is confirmed, would you be willing to submit a PR?
yes

**Comment by 609harsh** [comment]
hey @nechalmaggon can i work on this issue?

**Comment by nechalmaggon** [comment]
@609harsh Hi, just wanted to confirm if you are talking about the character limit in the login page or the sign-up while creating a password?

**Comment by 609harsh** [comment]
@nechalmaggon  Character limit on Login page.
In the first image login button is active even for less than minimum character limit in password field. which is different from signup page.
<img src="https://github.com/ToolJet/ToolJet/assets/97297407/13d28782-cb7b-4178-8a61-4c79d3f9d2d5" width="300" height="400">
<img src="https://github.com/ToolJet/ToolJet/assets/97297407/64e331e9-3864-4379-861f-c0af58a3ac43" width="300" height="400">
