### ISSUE TITLE
TJDB: As a user I should be able to create foreign keys on table creation

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#9038]
### Is your proposal related to a problem?
The user is not able to form relations b/w tables

### Describe the solution you'd like
PRD: [link](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-13736)
ADR: [link](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-17976)
Design: [link](https://www.figma.com/file/tYa0dxFKAObnxC8Jx0ACzn/TJ-DB?type=design&node-id=4781-139186&mode=design&t=U40yysr22DNNwRX7-0)

On table creation, a user should be able to create a foreign key constraint on a column being created

- User can click on `Add relation` to open FK creation drawer
- The subsequent drawer that opens can be used to select source, target and [actions](https://www.postgresql.org/docs/current/ddl-constraints.html)
- On creating the selection, it should be represented on the FK relation section
- Clicking on create should show success/error toast
- Foreign key relations should be shown on the link icons on hover as per design

### Constraints to note:
- **Referential integrity**: foreign key must reference an existing primary key value in another table or be nullable
- **Matching data types**: foreign key and the referenced primary key must have matching or compatible data types
- **Deletion and Update rules:** Set rules to avoid or allow orphaned rows in target table

<img width="873" alt="image" src="https://github.com/ToolJet/ToolJet/assets/11629675/42541904-ebe2-4927-a0e8-77fbfcaa462f">

<img width="978" alt="image" src="https://github.com/ToolJet/ToolJet/assets/11629675/2f84fcc1-0e39-495d-a37c-393d59760852">

<img width="978" alt="image" src="https://github.com/ToolJet/ToolJet/assets/11629675/00b4b0c9-c03c-4941-8388-fd00c2000e4e">

<img width="980" alt="image" src="https://github.com/ToolJet/ToolJet/assets/11629675/5b5f1ceb-a865-4b40-8dea-ac1c45b45334">

**Comment by mansukh-tj** [comment]
If user clicks on link icon next to a column, prefilled FK screen opens up with the following details pre filled

1. Type as Single Foreign Key
2. Table and Column name of the column whose link icon was clicked

**Comment by mansukh-tj** [comment]
Action for updating and deleting target FK value are as follows
<img width="356" alt="image" src="https://github.com/ToolJet/ToolJet/assets/144771579/d572b04a-4d27-4de6-9969-1a823692eb87">

Refer Feature 18 & 19 in the PRD

**Comment by mansukh-tj** [comment]
Limit Self refrential foreign keys - not permitted in TJ DB
