### ISSUE TITLE
TJDB: As a user, I should be given option to link for foreign key data on cell/row edit

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#9073]
design: [link](https://www.figma.com/file/tYa0dxFKAObnxC8Jx0ACzn/TJ-DB?type=design&node-id=5896-200207&mode=design&t=HqCvhSkhX1rOMjvK-0), [link](https://www.figma.com/file/tYa0dxFKAObnxC8Jx0ACzn/TJ-DB?type=design&node-id=5410-189879&mode=design&t=HqCvhSkhX1rOMjvK-0)

### Describe the solution you'd like
- Selecting Foreign Key value from a dropdown (having referenced column values of target table) in cell navigation, edit row, create a row, default value in edit column and create column
- If the value does not exist in target table, throw an error and fail the edit row/create row query
- The dropdown with referenced data should be searchable and do infinite scroll with pagination.

**Comment by Sadaf-A** [comment]
Hey @akshaysasidrn !
I would love to work on this issue.
could you please assign it to me?

**Comment by akshaysasidrn** [comment]
> Hey @akshaysasidrn ! I would love to work on this issue. could you please assign it to me?

We had picked it up internally as a part of our milestone. Please check for other open issues.
