### ISSUE TITLE
Header of the Workspace Constant page is not consistent with other pages

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#9089]
### What is the expected behaviour?
The `Workspace constants` header should be consistent with the `Applications`, `Data sources`, and `ToolJet Database` headers.

### What is the current behavior?
The `Workspace constants` header is not consistent with other headers in the dashboard.

### How to reproduce the issue?

1. Log in to ToolJet
2. Press all the icons in the left sidebar and observe the headers of `Applications`, `Data sources`, and `ToolJet Database`
3. Navigate to `Workspace constants` 

### Screenshots or Screencast
Correct:
![image](https://github.com/ToolJet/ToolJet/assets/58169101/2170159d-18e2-4d6b-8da2-56d1ee49e1b0)

Incorrect:
![image](https://github.com/ToolJet/ToolJet/assets/58169101/b1fc7171-d3b6-4dd4-955b-534719422365)

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by Bhavin789** [comment]
Hi @karan-rathod-316 , I might need to understand this well but if its ok, can I give it a shot? Thanks

**Comment by karan-rathod-316** [comment]
Hi @Bhavin789, assigning this to you. Happy coding:-)

**Comment by Bhavin789** [comment]
Thanks

**Comment by alewilliam789** [comment]
Found the fix for the header and the PR is in. Let me know if you need anything else.

**Comment by Bhavin789** [comment]
Hi @alewilliam789, I had already started working on this issue but got stuck in setup as I am new to this. [Ref for slack issue](https://tooljet.slack.com/archives/C05SSQF138F/p1710693306842719)

Would have loved to contribute to gain confidence in open-source but I think I need time to ramp up :)
@karan-rathod-316 , is there a guideline where an assigned issue can be resolved by someone else if not solved faster? If there are, will adhere to it from the next time and try to resolve things faster.  Thanks!

**Comment by ma-yur** [comment]
HI @karan-rathod-316 i would like to work on this, Can u assign this to me?

**Comment by karan-rathod-316** [comment]
Hi @Bhavin789, this issue is still with you.  We allow time to our original assignees to work on the issues before exploring other options. You can continue working on it. Do confirm if you are not going ahead with it.

**Comment by 2001asjad** [comment]
Hey @Bhavin789, do let us know if you're still working on the issue.

**Comment by Bhavin789** [comment]
Hi @2001asjad, apologies but I won't be able to take this up right now. I am still not able to run Tooljet locally, seeking help on the slack. 
@karan-rathod-316, please feel to re-assign. I'll now pick up an issue only when I have things running locally. 
Apologies for the delay again.

**Comment by 2001asjad** [comment]
Hi @alewilliam789, let us know if you're willing to work on this issue.

**Comment by alewilliam789** [comment]
Yeah guys the commit I had solved the problem already. I tested it in Devtools just to make sure. It was just a CSS rule that wasn't supposed to be applied to that header that needed to be deleted.

**Comment by STSonyThomas** [comment]
Hey if this issue still requires resolution may I be assigned the issue? @2001asjad

**Comment by 2001asjad** [comment]
Hey @STSonyThomas , thanks for your interest in contributing to ToolJet, but currently, a PR for this issue is under review.
