### ISSUE TITLE
Add a video explanation of deploying ToolJet on Heroku using 1-click deploy

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#909]
The documentation for Heroku one-click deployment: https://docs.tooljet.io/docs/deployment/heroku

We need to create a video that can be uploaded to our YouTube account. The video should explain how to deploy ToolJet on Heroku with a single click.

**Comment by luharuka** [comment]
HAY @Navaneeth-pk CAN YOU ASSIGN IT TO ME ALSO  DESCRIBE IT MORE WHAT EXACTLY TO DO

**Comment by MohsinNajmuddin** [comment]
@Navaneeth-pk I can do it. Assign it to me
