### ISSUE TITLE
Update a label related to the PDF component

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#9090]
### Description
`Show the download` label on the PDF component should be changed to `Show download button`. 

### How to reproduce the issue?
1. Create an application
2. Drag and drop a PDF component on the canvas
3. Navigate to its properties panel on the right
4. You will find a `Show the download` label

### Screenshots
![image](https://github.com/ToolJet/ToolJet/assets/58169101/65322bd0-be0d-4b74-afae-d0b6ed4fc401)

### Any possible solutions?
Replace the `Show the download` label with `Show download button`

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by devesh-2002** [comment]
May I take up this issue?

**Comment by karan-rathod-316** [comment]
Hi @devesh-2002, assigning this to you. Happy coding:-)

**Comment by burnsie000** [comment]
first timer to open source, is this issue available to take up?

**Comment by karan-rathod-316** [comment]
Hi @burnsie000, @devesh-2002 has already raised a PR for this. Feel free to explore other community issues that might pique your interest :-).
