### ISSUE TITLE
TJ DB: On clicking expand icon to edit the row, only right panel should open up and row should NOT get selected

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#9097]
Currently, the flow of editing a row is 

1. Expand row
2. Edit row values in right panel
3. Save Changes
4. Deselect the edited row in the dashboard 

![Image](https://github.com/ToolJet/ToolJet/assets/144771579/2b66c039-119b-45f7-9b2c-754775a87a99)

Here, step 4 is redundant.
On clicking expand icon to edit the row, only right panel should open up and row should NOT get selected

**Comment by blank0537** [comment]
@mansukh-tj I have raised PR for this. Please assign the issue.

**Comment by mansukh-tj** [comment]
Assigned
