### ISSUE TITLE
Sidebar of the data sources page is not consistent with other pages 

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#9109]
### What is the expected behavior?
The border color of the `Data sources` sidebar should be consistent with the `Applications` and `ToolJet Database` sidebars.

### What is the current behavior?
The `Applications` and `ToolJet database` sidebars display a border color on the right side, which is currently absent from the `Data sources` sidebar

### How to reproduce the issue?
1. Log in to ToolJet
2. Once you are on the dashboard, click on the `Applications` and `ToolJet database` icons and check their sidebars
3. Navigate to the `Data sources` sidebar

### Screenshots or Screencast
**Incorrect:**
![image](https://github.com/ToolJet/ToolJet/assets/58169101/73cba9bb-edb7-43a4-af3a-a135fde393b5)

**Correct:**
![image](https://github.com/ToolJet/ToolJet/assets/58169101/134d2335-71de-4cdd-bade-4161bdf81901)

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by prackode** [comment]
Hey Karan, may I take up this issue?

**Comment by Shikha1234** [comment]
Hi Karan,

Thank you for your observation about the sidebar borders in ToolJet.

Upon reviewing the issue, it seems that the absence of a border in the Data sources sidebar may not be a bug but rather a result of its longer content length, which triggers the scrollbar. However, if you could provide more details or screenshots illustrating the specific aspect you believe needs attention, it would be helpful for further investigation.

Please find attached clip and Looking forward to hearing more from you. 

Thanks 
Shikha



https://github.com/ToolJet/ToolJet/assets/11242283/537462f6-9217-4604-a42e-ff2e54a6f3ec

**Comment by prackode** [comment]
Possible fixes:
- Including a down arrow inplace of the existing scrollbar to display pagination
- Changing the visibility of scrollbar to transparent

**Comment by karan-rathod-316** [comment]
Hi @prackode, let me confirm this with the team and get back to you.

@Shikha1234 Thank you so much for your detailed input :-).

**Comment by prackode** [comment]
Any updates?
