### ISSUE TITLE
Workflow: The result section does not allow vertical scrolling

### ISSUE THREAD

**Issue by Mekhla-Asopa** [ToolJet/ToolJet#9125]
### What is the expected behaviour?
The vertical scrolling should be done in the result section

### What is the current behaviour?
Vertical scrolling is not present in the result section

### How to reproduce the issue?

1. Login with the valid credentials 
2. Navigate to the workflow page
3. Create a workflow with "restapi" or others
4. Run the workflow 
5. Verify the result

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/59684099/f0f5428a-2ff5-409a-8a3f-37516798562c

**Comment by sjcode99** [comment]
Hi @Mekhla-Asopa, assign this issue to me. wanted to work on it.
