### ISSUE TITLE
Supabase Integration

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#9138]
**Marketplace Inputs**
1. Project URL
2. Service Role Secret
![image](https://github.com/ToolJet/ToolJet/assets/144771579/dfba418a-9b91-40b4-97d5-fe69cc66b068)

**Query Builder Inputs**

1. Data source
2. Table
3. Operations - Count Rows, Create Row, Update Row, Delete Row, Get Rows

![image](https://github.com/ToolJet/ToolJet/assets/144771579/2eb51032-b1bc-40cc-bc6c-fb87a79ac4ee)

Filter list:

- Equals
- Not Equals
- Less Than
- Less Than Equal to
- Greater than
- Great than equal to
- is
- is not
- in

API documentation: https://supabase.com/docs/reference/javascript/introduction

**Comment by blank0537** [comment]
@mansukh-tj @2001asjad Im willing to work on this. Please assign it to me

**Comment by 2001asjad** [comment]
Sure, @blank0537, I have assigned the issue to you. Thanks for contributing to ToolJet.
