### ISSUE TITLE
Configuration options to add new events has alignment issues

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#9155]
### What is the expected behaviour?
- Add a component to the canvas, select the component, and navigate to its properties panel on the right. 
- When you click on `New event handler`, and the new events' configuration options open up, the drop-down fields and text boxes should have consistent height and width. 

### What is the current behavior?
1. Text boxes and drop-downs fields are not aligned properly 
2. Text boxes should have the same height and width as the drop-down fields
![image](https://github.com/ToolJet/ToolJet/assets/58169101/9a242806-ed85-4f42-8616-94bdb8d4021b)

### How to reproduce the issue?
1. Add a component to the canvas, select the component, and navigate to its properties panel on the right. 
2. Click on `New event handler`, and its configuration options will open up.
3. Choose different `Actions` and observe all the properties below the `Action` dropdown - you will see that there are alignment issues with text boxes and drop-down fields

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by ma-yur** [comment]
I would like to work on this issue, Can u assign this to me?

**Comment by karan-rathod-316** [comment]
Hi @ma-yur, assigning this to you. Thank you for your interest in contributing to ToolJet.

**Comment by harshp0205** [comment]
Hey, I would like to solve this issue, can you assign it to me?

**Comment by karan-rathod-316** [comment]
Hi @harshp0205, will assign this to you if there is no update from the original assignee. 

@ma-yur Can you confirm whether you are still working on it?

**Comment by ma-yur** [comment]
Hi @karan-rathod-316 sorry for the delay, currently facing few issues while setting up the project on my local.
I will try to setup in my local and pick up other issues later. 
Please assign the issue to @harshp0205

**Comment by 2001asjad** [comment]
Sure @ma-yur, no worries. @harshp0205 I am assigning this issue to you. Thanks for contributing to ToolJet.

**Comment by harshp0205** [comment]
Thanks, on it.

**Comment by akshat8605** [comment]
Hi, I am interested to work on this issue. Can this be assigned to me?

**Comment by 2001asjad** [comment]
Hi @akshat8605, I will assign this issue to you if there are no updates from the previous assignee.

**Comment by nick2432** [comment]
can i work on this?

**Comment by 2001asjad** [comment]
Hey @harshp0205 , any updates on this?

**Comment by harshp0205** [comment]
I tried, but i am not able to deliver the final output, you can assign it to someone else who is willing to contribute.

**Comment by nick2432** [comment]
@2001asjad I can work on this.

**Comment by 2001asjad** [comment]
No problem @harshp0205. @akshat8605 I am assigning this issue to you, do confirm if you’re going forward with it. Happy coding!

**Comment by 2001asjad** [comment]
Since there has been no confirmation from Akshat, @nick2432, I am assigning this issue to you, do confirm if you're going forward with it.

**Comment by 2001asjad** [comment]
@nick2432, are there any updates on this issue?

**Comment by nick2432** [comment]
@2001asjad , I'll start tomorrow. I was busy with my exams.

**Comment by 2001asjad** [comment]
Hello @nick2432 , are there any updates on this issue?

**Comment by nick2432** [comment]
> @nick2432 , please confirm if you're working on this issue.

i am working please give me 2 more days

**Comment by karan-rathod-316** [comment]
Hi @nick2432, any updates?

**Comment by nick2432** [comment]
> Hi @nick2432, any updates?

I am getting 'Unable to connect to the database' when I run the command 'cd ./server && npm run start:dev'.

**Comment by karan-rathod-316** [comment]
Hi @nick2432, can you join us on [slack](https://join.slack.com/t/tooljet/shared_invite/zt-2ij7t3rzo-qV7WTUTyDVQkwVxTlpxQqw) and post the query in the #contributors channel.

**Comment by 2001asjad** [comment]
Unassigned due to lack of progress.

**Comment by SohamPatel0810** [comment]
Hi,
 Can you please  assign this task to me.

**Comment by anshika-93** [comment]
I think this bug no longer exist in the UI as the text fields and dropdown list are aligned in the latest code
![image](https://github.com/ToolJet/ToolJet/assets/22219468/1b5de8f5-2055-4c33-8954-aa96e465f31a)

**Comment by karan-rathod-316** [comment]
Hi @anshika-93, let me check with the team on this.

**Comment by karan-rathod-316** [comment]
Closing the issue as this has been handled internally.
