### ISSUE TITLE
Change a label related to workspace constants

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#9156]
### What is the expected behaviour?
The label for the `Go to workspace constants` button should read `Go to Workspace constants`

### What is the current behaviour?
Currently it is `Go to workspace constants` 

### How to reproduce the issue?
1. Go to `Settings` > `Workspace settings` > `Workspace variables` - You will find a `Go to workspace constants` button at the top (change it to `Go to Workspace constants`)

### Screenshots or Screencast
![image](https://github.com/ToolJet/ToolJet/assets/58169101/815f11ff-968a-4f6e-b2fa-f4ac77a6d3e5)

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by joelali5** [comment]
Hi @karan-rathod-316 , I'm a first time contributor on this project, and I'd like to help out with this issue. Let me know please. Thank you.

**Comment by arp55** [comment]
Hi @karan-rathod-316 . Have opened a PR for the same. Please check.

**Comment by karan-rathod-316** [comment]
Hi @joelali5, Assigning this to you. Happy Coding:-)

**Comment by karan-rathod-316** [comment]
@arp55 It would be great if you can get the issues assigned before raising a PR. Since @joelali5 was the first one to ask, I am assigning this to him. If the current assignee isn't able to complete it, I will consider your PR.

**Comment by arp55** [comment]
Sure, no problem

**Comment by joelali5** [comment]
Thanks @karan-rathod-316 I will open a PR for this shortly.

**Comment by joelali5** [comment]
@karan-rathod-316 After setting my development environment, I am unable to signup, below is the screenshot. Please let me know if you have an idea of what I need to do. Thank you

<img width="566" alt="Screenshot 2024-03-22 at 14 06 56" src="https://github.com/ToolJet/ToolJet/assets/42684254/0130ba6b-ac16-4c8c-8e16-f427865f4ef5">

**Comment by joelali5** [comment]
Hi @karan-rathod-316 I figured it out. I have raised a pull request, here: https://github.com/ToolJet/ToolJet/pull/9171

**Comment by PriteshKiri** [comment]
Closing the issue as the PR for this issue has been merged.
