### ISSUE TITLE
Community template: Base64 encoder & decoder

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9163]
### Description:
This template provides a simple user interface to encode and decode data using Base64, a binary-to-text encoding scheme. It allows users to input text or binary data and convert it to its Base64 representation or vice versa.

### Template feature list:
Read the template feature list [here](https://docs.google.com/document/d/15jpT_YwQQKV4GmfzucKHwR3446rfKCZhpkSDlZlBqGo/edit?usp=sharing)

### Template guidelines: 
Read the guidelines [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

### Template deadline:
Last day of picking up the templates is **19 April 2024** and submitting the templates is **28 April 2024**

**Comment by Abraham599** [comment]
Hi @GrowwithNaveen, I would like to work on this issue. Can you assign this issue to me ?

**Comment by Abraham599** [comment]
and do I need to build this template as a whole new web app ? and am I free to use own tech stack (React js for frontend, TailwindCSS as styling framework and express for the backend) ?

**Comment by mthirumalai2905** [comment]
hey @GrowwithNaveen  i can build this template please assign this issue to me  i  will get this to u asap

**Comment by mthirumalai2905** [comment]
sir i just created a simple product this way just have to change the colors accordingly to u r template guidelines i used vanilla javascript am ready to do it by react and tailwindcss or any other framework 
[os.webm](https://github.com/ToolJet/ToolJet/assets/98790479/7c596144-4589-4883-835b-896c1bd1d6da)

**Comment by GrowwithNaveen** [comment]
Hi devs, Thank you for your interest in this item. It serves as a sample created for internal testing purposes.
The official templates for the "[Community Templates](https://github.com/orgs/ToolJet/projects/16/views/2)" board will be launched tomorrow. Please keep an eye out for it on the board.
