### ISSUE TITLE
Page heading should be in one line

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#9180]
Page header for the following should be in a single line and not split into two (ref screenshot)- 
1. Profile settings 
2. Audit logs
3. Workspace constants 

<img width="276" alt="Screenshot 2024-03-25 at 11 56 22 AM" src="https://github.com/ToolJet/ToolJet/assets/127945292/748f691c-d407-469b-a3be-6ad459dca33d">
<img width="242" alt="Screenshot 2024-03-25 at 11 56 30 AM" src="https://github.com/ToolJet/ToolJet/assets/127945292/cff35209-9672-4f41-bb85-4259fba40a36">
<img width="278" alt="Screenshot 2024-03-25 at 11 56 45 AM" src="https://github.com/ToolJet/ToolJet/assets/127945292/09a5c25c-bade-43f3-bf01-31bf95c2691a">

**Comment by Latish705** [comment]
@nechalmaggon can tell a which page you are facing this

**Comment by nechalmaggon** [comment]
@Latish705 It is for the following pages- 
1. Profile settings 
2. Audit logs 
3. Workspace constants

**Comment by ajith-k-v** [comment]
Ref: #9284
