### ISSUE TITLE
logo alignment issue

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#919]
On the application editor, the ToolJet logo should align with the sidebar icons.

![image](https://user-images.githubusercontent.com/7828962/136315100-a23ad311-2084-4d0c-ac5f-a27bc02397ff.png)

**Comment by Navaneeth-pk** [comment]
Assigned, thanks for contributing to ToolJet.
@sumitkumarju

**Comment by Navaneeth-pk** [comment]
@sumitkumarju is there an update on this issue?

**Comment by sumitkumarju** [comment]
Docker one

**Comment by Navaneeth-pk** [comment]
If using docker, you don't need to run `npm start`. Please follow the instructions in the setup guide: https://docs.tooljet.io/docs/contributing-guide/setup/docker
@sumitkumarju

**Comment by Navaneeth-pk** [comment]
Can you please join our slack community so that you will get help from someone to set this up? https://join.slack.com/t/tooljet/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg

**Comment by sumitkumarju** [comment]
Yes
