### ISSUE TITLE
Community template: Base64 encoder & decoder

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9190]
### Description:
This template provides a simple user interface to encode and decode data using Base64, a binary-to-text encoding scheme. It allows users to input text or binary data and convert it to its Base64 representation or vice versa.

### Template feature list:
Please check [here ](https://docs.google.com/document/d/15jpT_YwQQKV4GmfzucKHwR3446rfKCZhpkSDlZlBqGo/edit?usp=sharing)

### Template guidelines:
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

### Template deadline:
1. Upon assignment of a template development task, you must complete the development process within 10 working days and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
2. Failure to complete the development within 10 working days or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by AtulMinz** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by adityarawat007** [comment]
Hello @GrowwithNaveen  can you please assign this Issue to me

**Comment by sahilsekr42** [comment]
@GrowwithNaveen  is this issue open for everyone also i would like to understand how these templates are being rendered from the json files which key value pairs to consider and and how are unique ids being generated

**Comment by karan-rathod-316** [comment]
Hello @AtulMinz,

I've allocated this task to you. Take a moment to review the accompanying guidelines thoroughly. Should any questions arise or further clarification be needed, feel free to reach out in the #contributors channel on [slack](https://tooljet.slack.com/). Please note, the completion timeline for this task is set for 10 days.

**Comment by karan-rathod-316** [comment]
For data storage and processing, please use [ToolJet Database](https://docs.tooljet.com/docs/tooljet-database) in your apps.

**Comment by karan-rathod-316** [comment]
Hi @AtulMinz,

Is there any update on this PR?

**Comment by AtulMinz** [comment]
Hi @karan-rathod-316 ,
I'm working on it.

**Comment by karan-rathod-316** [comment]
Sure, please let us know if you will need a deadline extension for this.

**Comment by karan-rathod-316** [comment]
Hi @AtulMinz,

Is there any update on this?

**Comment by AtulMinz** [comment]
@karan-rathod-316 I'm sorry for the delay.
I am working on the script part.

**Comment by karan-rathod-316** [comment]
Hi @AtulMinz,

Any update on this?

**Comment by karan-rathod-316** [comment]
Un-assigning this due to lack of activity. @AtulMinz

**Comment by MK884** [comment]
hello @karan-rathod-316 can you please assign this task to me

**Comment by yanishbansal** [comment]
Hi , I would like to work on this issue , Can you please assign it to me?

**Comment by karan-rathod-316** [comment]
Hi @MK884, 

Assigning this issue to you. Happy coding:-)

@yanishbansal I have assigned this to @MK884, but feel free to take a look at other issues with `up for grabs` label.

**Comment by PriteshKiri** [comment]
Closing the issue as the [PR](https://github.com/ToolJet/ToolJet/pull/9653) for this issue has been merged.
