### ISSUE TITLE
Community template: Lorem ipsum generator

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9202]
### Description:
The "Lorem Ipsum Generator" template will provide users with the ability to generate dummy text content for various purposes, such as placeholders, testing, or prototyping. The template will offer a range of options to generate different types of content, including paragraphs, sentences, titles, words, full names, email addresses, company URLs, and company names.

### Template feature list:

Please check [here](https://docs.google.com/document/d/1q6EodAESj8MeAYkwWwBEylNg4YxZgIfrmRc6KH3gYME/edit?usp=sharing)

### Template guidelines:

Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

### Template deadline:
1. Upon assignment of a template development task, you must complete the development process within 10 working days and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
2. Failure to complete the development within 10 working days or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

### Note: This template is up for grab from 02/April/2024, Tuesday.

**Comment by mthirumalai2905** [comment]
@GrowwithNaveen  Assign this to me

**Comment by kaseraSwastik** [comment]
@GrowwithNaveen Sir, Can I know, where should the UI codes goes (which folder)?

**Comment by Ranit-Bandyopadhyay** [comment]
@GrowwithNaveen i am interested to do this, kindly assign it to me

**Comment by abdel-rahmanSalem** [comment]
Hi @GrowwithNaveen, This is my first time contributing, and I would be happy if you could assign it to me. Thank you!

**Comment by sahilsekr42** [comment]
@GrowwithNaveen is this issue open for everyone also i would like to understand how these templates are being rendered from the json files which key value pairs to consider and and how are unique ids being generated

**Comment by karan-rathod-316** [comment]
Hello @abdel-rahmanSalem ,

I've allocated this task to you. Take a moment to review the accompanying guidelines thoroughly. Should any questions arise or further clarification be needed, feel free to reach out in the #contributors channel on [slack](https://tooljet.slack.com/). Please note, the completion timeline for this task is set for 10 days.

**Comment by Ranit-Bandyopadhyay** [comment]
@karan-rathod-316 i have already made the backend and the frontend part. Kindly assign it to me as I have already completed. Just yet to be reviewed

**Comment by karan-rathod-316** [comment]
Hi @Ranit-Bandyopadhyay, we'd prefer if you get the issue assigned before you begin working on it :-) 

Since we have already assigned this to @abdel-rahmanSalem, we will wait for him to confirm in case he is starting with the template. I will be happy to re-assign it to you otherwise. Also, we have another template which is beginner friendly - [9203](https://github.com/ToolJet/ToolJet/issues/9203). Would be happy to assign it to you.

**Comment by Ranit-Bandyopadhyay** [comment]
@karan-rathod-316 kindly confirm it as I have worked on it for 3 days and kindly provide the slack community access for contribution

**Comment by mthirumalai2905** [comment]
I already did the work for some other encryption and decryption base64 templates just have to change the color schemes accordingly but am still not assigned with any tasks please have a look into it

**Comment by karan-rathod-316** [comment]
Hi @mthirumalai2905, would you be interested in picking up this templates? :-)

https://github.com/ToolJet/ToolJet/issues/9203

**Comment by abdel-rahmanSalem** [comment]
hi @karan-rathod-316, 

Thank you for assigning the task to me. I acknowledge the assignment and will start working on it promptly. I'll make sure to review the guidelines thoroughly and adhere to the completion timeline of 10 days.

Also, could you please add me to the Slack community of ToolJet?

**Comment by Ranit-Bandyopadhyay** [comment]
@karan-rathod-316 can you list which issues are open and are beginner friendly and sequentially assign them. It would be good.

**Comment by karan-rathod-316** [comment]
Hi @Ranit-Bandyopadhyay, can you please comment on #9203? Can assign it once you post a comment.

**Comment by Ranit-Bandyopadhyay** [comment]
@karan-rathod-316 done

**Comment by mthirumalai2905** [comment]
@karan-rathod-316  #9163 can you assign?

**Comment by karan-rathod-316** [comment]
@abdel-rahmanSalem For data storage and processing, please use [ToolJet Database](https://docs.tooljet.com/docs/tooljet-database) in your apps.

**Comment by GrowwithNaveen** [comment]
Closed with PR https://github.com/ToolJet/ToolJet/pull/9313

**Comment by PriteshKiri** [comment]
Hey @abdel-rahmanSalem ! :tada: we wanted to take a moment to acknowledge your amazing contribution to the ToolJet community templates.

As a token of our appreciation, we'd like you to accept this badge: [Template Trialblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg) You can add it to your GitHub profile or dev portfolios via readme file.

<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>

You can add the following code to your readme file.

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


We really value your efforts, and please don't hesitate to keep contributing!  Feel free to check out the [community template board](https://github.com/orgs/ToolJet/projects/16/views/2) for more opportunities.
