### ISSUE TITLE
Community template: Digital marketing campaign manager

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9203]
### Description:
This tool empowers users to build and append UTM tags (Urchin Tracking Module) to URLs. These tags act like short codes added to URLs, enabling to track the source and campaign details of your website traffic. They offer valuable insights for website owners and marketers.

### Template feature list:
Please check [here](https://docs.google.com/document/d/1xpClC4O5r2NzSuIZuuf31xfm9hg1aNRiPJfHMpWEGtg/edit?usp=sharing)

### Template guidelines:
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

### Template deadline:
1. Upon assignment of a template development task, you must complete the development process within 10 working days and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
2. Failure to complete the development within 10 working days or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

### Note: This template is up for grab from 02/April/2024, Tuesday.

**Comment by Abhinav-CHD** [comment]
Hi, could you assign this issue to me?

**Comment by Ranit-Bandyopadhyay** [comment]
@karan-rathod-316 kindly assign it to me

**Comment by karan-rathod-316** [comment]
Hello @Ranit-Bandyopadhyay ,

I've allocated this task to you. Take a moment to review the accompanying guidelines thoroughly. Should any questions arise or further clarification be needed, feel free to reach out in the #contributors channel on [slack](https://join.slack.com/t/tooljet/shared_invite/zt-2g72swtd0-o83AS90zbt5xpcVYo5ivGw/). Please note, the completion timeline for this task is set for 10 days.

Please acknowledge the assignment before you begin. This lets us know it's in progress :-).

**Comment by karan-rathod-316** [comment]
Hi @Abhinav-CHD, we will be having sharing more community templates soon to our contributors. This particular issue was already offered to @Ranit-Bandyopadhyay on a different thread. We'd be happy to assign you other templates in future:-).

**Comment by Ranit-Bandyopadhyay** [comment]
@karan-rathod-316 I acknoledge the assignment.

**Comment by karan-rathod-316** [comment]
@Ranit-Bandyopadhyay For data storage and processing, please use [ToolJet Database](https://docs.tooljet.com/docs/tooljet-database) in your app.

**Comment by atharvnaik1** [comment]
Hi, could you assign this issue to me?

**Comment by karan-rathod-316** [comment]
Hi @atharvnaik1,

This template is already done, you can pick up [#9204](https://github.com/ToolJet/ToolJet/issues/9204) if you are interested in contributed. Please comment on the issue so that I can assign it to you.

**Comment by PriteshKiri** [comment]
Hey @Ranit-Bandyopadhyay ! :tada: we wanted to take a moment to acknowledge your amazing contribution to the ToolJet community templates.

As a token of our appreciation, we'd like you to accept this badge: [Template Trialblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg) You can add it to your GitHub profile or dev portfolios via readme file.

<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>

You can add the following code to your readme file.

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


We really value your efforts, and please don't hesitate to keep contributing!  Feel free to check out the [community template board](https://github.com/orgs/ToolJet/projects/16/views/2) for more opportunities.
