### ISSUE TITLE
Community template: Finance underwriting

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9205]
### Description:
This template streamlines the underwriting process, enabling thorough evaluation and approval of loan applications based on company criteria.

### Template feature list:
Please check [here](https://docs.google.com/document/d/1NQcivXXNDM7U6dfHa0wdsGqqchqAS5nXMWGOb9orL1s/edit?usp=sharing)

### Template guidelines:
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

### Template deadline:
1. Upon assignment of a template development task, you must complete the development process within 10 working days and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
2. Failure to complete the development within 10 working days or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

### Note: This template is up for grab from 02/April/2024, Tuesday.

**Comment by Manik-Jasrai** [comment]
Hi! Can I grab this issue.
I am a beginner at open source so can you guide me for this issue.

**Comment by karan-rathod-316** [comment]
Hello @Manik-Jasrai,

I've allocated this task to you. Take a moment to review the accompanying guidelines thoroughly. Should any questions arise or further clarification be needed, feel free to reach out in the #contributors channel on [slack](https://tooljet.slack.com/). Please note, the completion timeline for this task is set for 10 days.

**Comment by karan-rathod-316** [comment]
Hi @Manik-Jasrai, This particular template is more suitable for experienced developers. Do keep an eye out for other templates that we might open up to community developers in future.

**Comment by Sadaf-A** [comment]
@karan-rathod-316 Hey! I would like to pick this up

**Comment by karan-rathod-316** [comment]
Hello @Sadaf-A ,

I've allocated this task to you. Take a moment to review the accompanying guidelines thoroughly. Should any questions arise or further clarification be needed, feel free to reach out in the #contributors channel on [slack](https://tooljet.slack.com/). Please note, the completion timeline for this task is set for 10 days.

Please acknowledge the assignment before you begin. This lets us know it's in progress :-).

**Comment by Sadaf-A** [comment]
> Hello @Sadaf-A ,
> 
> I've allocated this task to you. Take a moment to review the accompanying guidelines thoroughly. Should any questions arise or further clarification be needed, feel free to reach out in the #contributors channel on [slack](https://tooljet.slack.com/). Please note, the completion timeline for this task is set for 10 days.
> 
> Please acknowledge the assignment before you begin. This lets us know it's in progress :-).

Hey, the slack invitation link in the README file is no longer active could you please share a new one

**Comment by Sadaf-A** [comment]
> Hello @Sadaf-A ,
> 
> I've allocated this task to you. Take a moment to review the accompanying guidelines thoroughly. Should any questions arise or further clarification be needed, feel free to reach out in the #contributors channel on [slack](https://tooljet.slack.com/). Please note, the completion timeline for this task is set for 10 days.
> 
> Please acknowledge the assignment before you begin. This lets us know it's in progress :-).

I acknowledge the assignment and I have started working on this template

**Comment by 2001asjad** [comment]
Hi @Sadaf-A, thanks for contributing to ToolJet. I'll confirm with the team and get back to you.

**Comment by karan-rathod-316** [comment]
@GrowwithNaveen Can you please update this?

**Comment by GrowwithNaveen** [comment]
@Sadaf-A Description is updated, thanks for notifying it. Let's us know for any more clarifications.

**Comment by Sadaf-A** [comment]
> @Sadaf-A Description is updated, thanks for notifying it. Let's us know for any more clarifications.

Hey, Thanks for addressing the issue. Could I get a slack invite link as the current invite link in the README and the website is outdated

**Comment by karan-rathod-316** [comment]
Hi @Sadaf-A, here's the invite link:

https://join.slack.com/t/tooljet/shared_invite/zt-2g72swtd0-o83AS90zbt5xpcVYo5ivGw

**Comment by GrowwithNaveen** [comment]
Closed with PR: https://github.com/ToolJet/ToolJet/pull/9362

**Comment by PriteshKiri** [comment]
Hey @Sadaf-A ! :tada: we wanted to take a moment to acknowledge your amazing contribution to the ToolJet community templates.

As a token of our appreciation, we'd like you to accept this badge: [Template Trialblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg) You can add it to your GitHub profile or dev portfolios via readme file.

<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>

You can add the following code to your readme file.

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


We really value your efforts, and please don't hesitate to keep contributing!  Feel free to check out the [community template board](https://github.com/orgs/ToolJet/projects/16/views/2) for more opportunities.

**Comment by Sadaf-A** [comment]
> Hey @Sadaf-A ! :tada: we wanted to take a moment to acknowledge your amazing contribution to the ToolJet community templates.
> 
> As a token of our appreciation, we'd like you to accept this badge: [Template Trialblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg) You can add it to your GitHub profile or dev portfolios via readme file.
> 
> <div align="left">
>   
> [![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)
> 
> </div>
> 
> You can add the following code to your readme file.
> 
> ```
> <div align="left">
>   
> [![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)
> 
> </div>
> ```
> 
> 
> We really value your efforts, and please don't hesitate to keep contributing!  Feel free to check out the [community template board](https://github.com/orgs/ToolJet/projects/16/views/2) for more opportunities.

Hey @PriteshKiri ,
Thanks a lot for the badge I really appreciate it
