### ISSUE TITLE
Tooljet database show nothing after make application public

### ISSUE THREAD

**Issue by hunter-xue** [ToolJet/ToolJet#9239]
### Environment

    Docker

### What is the expected behaviour?
  show data in tooljet database correctly. 

### What is the current behaviour?
  show nothing, alter I make my application public. also after I embeded the public application in a iframe. 

### How to reproduce the issue?

1. Create a new table in tooljet database. 
2. Select the created table in previous step。 
3. Release the application and make it public. 
4. Copy the URL of application to new browser window which did NOT login to tooljet and open the applicaiton. 

### Screenshots or Screencast

  
![image](https://github.com/ToolJet/ToolJet/assets/4905312/bebccdf0-7d14-4856-8109-a0e5ea2dc1b1)

**Comment by shubh22** [comment]
This is fixed.
