### ISSUE TITLE
manage organization users link is not visible in dark mode.

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#924]
![image](https://user-images.githubusercontent.com/7828962/136339020-c655b461-705f-473e-b6b8-2b2fd3079edd.png)

"manage organization users" link is not visible in dark mode. 

Steps to reproduce: 
a) create an application
b) Click on share button at the top right corner of the editor

**Comment by radiantly** [comment]
Hi, could I take a go at this issue?
