### ISSUE TITLE
Radio button components 2.0

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9242]
PRD: https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-15316
Figma design: https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?type=design&node-id=543%3A158995&mode=design&t=PO6hC9cGLOnFrK7X-1

**Comment by AsimKumarChakraborty** [comment]
Adding a tooltip which supports multiple values for each circle, like a star widget, will be very helpful.
