### ISSUE TITLE
Missing pin/unpin button in ```Global settings``` - App builder 

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9262]
### Current behavior:
The "Global settings" section within the app builder window lacks a dedicated pin/unpin button. However, it still functions based on the pin/unpin state set elsewhere.

### Expected behavior:
A pin/unpin button should be added to the "Global settings" section for user convenience in managing its visibility within the app builder window.

**Attaching a screengrab for reference,**

https://github.com/ToolJet/ToolJet/assets/81761482/2ef65755-3d04-4985-bdb5-c4b870152277

**Comment by Sadaf-A** [comment]
Greetings @GrowwithNaveen  , I would like to work on this issue!
