### ISSUE TITLE
Text component - Long text rendering issue

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9265]
The Text component encounters two issues when handling lengthy text content:
1. Initial Text Clipping: The beginning portion of very long text is hidden. This can be resolved by removing the justify-content property.
2. Incomplete Scrolling: When text overflows its designated area with vertical alignment set to "center," scrolling fails to reveal the entire text content.

Attaching a screenshot for reference,
![image](https://github.com/ToolJet/ToolJet/assets/81761482/198bae26-28c7-45cd-a16b-8c4e8ec67355)

**Comment by johnsoncherian** [comment]
Fixed in PR #9272 
And released in #9289
