### ISSUE TITLE
Update the label under Action Buttons in the Properties Panel

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#9273]
### What is the expected behaviour?
If there are no Actions configured for a component, the label should read `No action buttons` 

### What is the current behaviour?
The label reads `There are no action buttons` 

### How to reproduce the issue?
1. Drag and drop a component on the canvas
2. Select it and navigate to its properties panel
3. Observe the label under `Action Buttons`

### Screenshots or Screencast
<img width="301" alt="image (1)" src="https://github.com/ToolJet/ToolJet/assets/58169101/25388dc3-18c5-4821-b380-9858d4b62506">

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by Sadaf-A** [comment]
Hey @karan-rathod-316 , 
I have opened a PR for this hope it resolves the issue!

**Comment by karan-rathod-316** [comment]
Hi @Sadaf-A, adding you as the assignee and moving your PR to review. We'd appreciate it if you ask for assignment before working on issues going forward :-). Thank you for your interest in contributing to ToolJet.

**Comment by Sadaf-A** [comment]
> Hi @Sadaf-A, adding you as the assignee and moving your PR to review. We'd appreciate it if you ask for assignment before working on issues going forward :-). Thank you for your interest in contributing to ToolJet.

Thanks for letting me know, I will keep that in mind for sure

**Comment by karan-rathod-316** [comment]
@Sadaf-A 
I would also like to draw your attention to a template creation issue that is currently open to our community. Do leave a comment on the issue if you would be interested in picking it up: https://github.com/ToolJet/ToolJet/issues/9205
