### ISSUE TITLE
Tooljet Database: Provide support for advance queries

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#9282]
### Summary:
Extend the current database query capabilities in ToolJet to support more advanced SQL functionalities, including but not limited to `GROUP BY,` aggregation functions like `SUM()`, `COUNT()`,` AVG()`, and other analytical operations. This enhancement is aimed at enabling users to perform more sophisticated data analysis and reporting directly within ToolJet applications.

### Detailed Description:

- Grouping Data: Using GROUP BY to aggregate data based on specific columns.
- Aggregate Functions: Applying functions like SUM(), COUNT(), AVG(), MAX(), and MIN() to perform calculations on grouped data.
- Filtering Aggregated Data: Utilizing HAVING to filter data after aggregation.
- Complex Joins: Enhancing support for various types of joins to facilitate complex data relationships

**Comment by adi790uu** [comment]
Hey @ShazanRizvi can I solve this

**Comment by Sadaf-A** [comment]
Hey @ShazanRizvi @karan-rathod-316 , I would like to work on this issue if you could please assign it to me
