### ISSUE TITLE
App crashes when {{moment(undefined)}} is passed into certain code input fields

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#929]
### Environment

Linux

### What is the expected behaviour?

When I type in `{{moment(undefined)}}` as default value of text area or text input, the app should not crash.
### What is the current behaviour?

It crashes
### How to reproduce the issue?

1. Drag in a text area
2. Type in `{{moment(undefined)}}` to its default value
3. Click somewhere outside

### Screenshots or Screencast

https://user-images.githubusercontent.com/20333972/136354094-3d0c1340-b3aa-4f39-a5f7-d53ffbe8b25e.mp4

**Comment by withshubh** [comment]
The issue has been fixed.
