### ISSUE TITLE
Dark mode loading state 

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#9296]
The loader animation color should be #3A4251 throughout the product. Find attached below a screen recording of an example of the current loader animation. 

Loading state color in the following screens are to be updated- 
1. App dashboard 
2. TJ Database 
3. Data sources 
4. Settings  (all sub-tabs)
5. Workspace settings (all sub-tabs)
6. Audit logs 

https://github.com/ToolJet/ToolJet/assets/127945292/5405f7f4-572b-4a9f-83f7-476e30ce1afd

**Comment by Sadaf-A** [comment]
Hey @nechalmaggon , I would like to work on this!

**Comment by karan-rathod-316** [comment]
Hi @Sadaf-A, assigning the issue to you. Happy coding :-).

**Comment by karan-rathod-316** [comment]
@Sadaf-A I just want to highlight that this is a critical issue with a deadline of 3 days. Do let me know if you need an extension :-).

**Comment by Sadaf-A** [comment]
> @Sadaf-A I just want to highlight that this is a critical issue with a deadline of 3 days. Do let me know if you need an extension :-).

Sure thing, I'll try my best to complete within the given timeframe

**Comment by Sadaf-A** [comment]
> @Sadaf-A I just want to highlight that this is a critical issue with a deadline of 3 days. Do let me know if you need an extension :-).

Hey, I will need today's time to complete this issue I hope that is alright

**Comment by karan-rathod-316** [comment]
Hi @Sadaf-A,

Just wanted to know if there's an update on this PR. This is a priority issue and needs to be closed soon.

**Comment by Sadaf-A** [comment]
> Hi @Sadaf-A,
> 
> Just wanted to know if there's an update on this PR. This is a priority issue and needs to be closed soon. 

Hey, while I'm trying to solve this issue actively I'm not able to solve it yet. The codebase is new and it may take longer than I expected.

**Comment by Sadaf-A** [comment]
Hey @karan-rathod-316, I believe this should solve the issue please have a look. I have tested it out on my local setup would it be a good idea to attach a demo video?

Thank You

**Comment by karan-rathod-316** [comment]
Hi @Sadaf-A, 

No, video is not needed. Thank you so much for your contribution, will move this to Review.
