### ISSUE TITLE
Update a label in the query panel when using OpenAI as the Data Source

### ISSUE THREAD

**Issue by 2001asjad** [ToolJet/ToolJet#9367]
### What is the expected behaviour?
The label for the message input should read `Message`

### What is the current behaviour?
The label currently reads `Message as input,`

### How to reproduce the issue?

1. Go to the data source dashboard > configure the OpenAI data source 
1. Create a new app > Add OpenAI as the data source from your app's query panel
2. Under the `Operation` panel, choose `Chat` from the dropdown
3. Observe the `Message as input,` label

### Screenshots or Screencast
![image](https://github.com/ToolJet/ToolJet/assets/60435499/55917abd-c21b-49fc-8132-db051f2adec1)

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by devansh-m12** [comment]
can i work on this issue ?

**Comment by 2001asjad** [comment]
Sure, @devansh-m12, I am assigning this issue to you. Thanks for your interest in contributing to ToolJet!

**Comment by Vikas-singh-0** [comment]
Is it still open ?? I could make my first contribution 🙂

**Comment by 2001asjad** [comment]
Hey @Vikas-singh-0 , currently this issue has been assigned, if there is no progress from the previous assignee, I will assign this to you. :)

**Comment by STSonyThomas** [comment]
Can I work on this issue?

**Comment by devanshu052000** [comment]
Hey, I wanted to work on this issue. Is it still open?

**Comment by karan-rathod-316** [comment]
Hi @devanshu052000, since there is no response from the original assignee, I would be happy to assign this to you. Let me know if you are still interested in picking this up. cc: @2001asjad

**Comment by devanshu052000** [comment]
Yes I am interested to work on this

**Comment by karan-rathod-316** [comment]
Great, assigning this to you :-). Just a heads-up that this is a deadline-driven tasks and needs to be completed within 5 days.

**Comment by devanshu052000** [comment]
Will keep that in mind, thanks for informing!

**Comment by karan-rathod-316** [comment]
Hi @devanshu052000, since your doubts were solved on slack. Were you able to proceed with the Issue?

**Comment by devanshu052000** [comment]
Hi Karan, Will try out the solution provided on slack today in the evening and will let you know regarding the same

**Comment by Vishalll07** [comment]
Hey just wanna ask, is the issue still open to work,? if yes is the issue on fronted like the message as input should be written like only message ? Or is it something else I took wrong? I mainly want to understand the issue , even if I am not allowed to work will be great if you make me understand

**Comment by 2001asjad** [comment]
Hi @Vishalll07, yes, you got it right; when we use `OpenAI` as the data source for the app that we're creating, in the query panel, after choosing `Chat` as the option from the dropdown. Currently, the label for the message reads `Message as input,` and we would want it to read as `Message`. Please confirm whether you want to work on this issue, and I'll assign this to you. :)

**Comment by Vishalll07** [comment]
hey @2001asjad   actually am new to opensource contributions, for  which I want to get the  issue as clarified as possible 
![github first pr](https://github.com/ToolJet/ToolJet/assets/78494000/8d7d1a2d-5179-4398-af1f-31f3e064464e)
so moving up to the steps to generate the issue am not able see the operations panel , Is the feature disabled for now ?
and if you don't mind can you please find me the #9367 issue folder

**Comment by AbhishekSaroch** [comment]
Hey @2001asjad can i work on this issue ? 
I will resolve this issue .

**Comment by Vikas-singh-0** [comment]
Seems like its still not resolved 😞😞

**Comment by 2001asjad** [comment]
Hi @AbhishekSaroch, I am assigning this issue to you. Thanks for your interest in contributing to ToolJet :)

**Comment by AbhishekSaroch** [comment]
Thankyou @2001asjad

**Comment by AbhishekSaroch** [comment]
Hi @2001asjad i am getting some issues while setting up tooljet's code base in my local 
So working on that

**Comment by 2001asjad** [comment]
Since there has been no update from the previous assignee, @ruthvik129, I am assigning this issue to you. Thanks for your interest in contributing to ToolJet :)

**Comment by ruthvik129** [comment]
@2001asjad raised a PR , kindly review and let me know if any fixed have to be done

**Comment by 2001asjad** [comment]
Thanks, @ruthvik129; we will review your PR and get back to you.
