### ISSUE TITLE
Missing items under "Company" in mobile Nav

### ISSUE THREAD

**Issue by david-everett** [ToolJet/ToolJet#9384]
### What is the expected behaviour?
All items load properly when you click on company in mobile nav, including Careers & Events

### What is the current behaviour?
Careers is partially visible on iPhone 15, events is completely invisible with no option to scroll, 

### How to reproduce the issue?
1. Click on mobile nav
2. Click on Company

### Screenshots or Screencast
![Mobile Nav](https://github.com/ToolJet/ToolJet/assets/98620729/0ace452b-6959-42ce-8ab6-4fd82f114e06)

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by atharvnaik1** [comment]
@david-everett  need to change css @media-only  for mobile view  with low padding and margin to bottom component shall i ?

**Comment by atharvnaik1** [comment]
May I work on this issue ?

**Comment by AnkityadavIITR** [comment]
@david-everett if this issue isn't assign to anyone, i would be happy to work on it

**Comment by EbrahimAfridi** [comment]
I think this issue is resolved.

**Comment by shubh22** [comment]
This repo doesn't track bugs in tooljet.com website.
