### ISSUE TITLE
The right-align icon under Styles is smaller in size compared to left-align and centre-align

### ISSUE THREAD

**Issue by prajval-tooljet** [ToolJet/ToolJet#9385]
### Environment
ToolJet Cloud / Docker / Linux / MacOS

### What is the expected behaviour?
The right align icon under styles across all components is smaller than the left and centre align icon 

### What is the current behaviour?
There is no hinderance with the functionality. it is an UI issue.

### How to reproduce the issue?

1. Choose any component
2. Navigate to Styles
3. Click on right align

### Screenshots or Screencast
![image-style-icon](https://github.com/ToolJet/ToolJet/assets/163403152/574c1d44-a8b1-4371-b0a9-930ab68b6120)

**Comment by Sadaf-A** [comment]
Hey @prajval-tooljet , I would like to work on this!

**Comment by atharvnaik1** [comment]
Hey @prajval-tooljet  , I think its due to faulty right margin .. I can fix it right away !!
