### ISSUE TITLE
Input field and cancel button should be disabled when an app import is in progress

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#9388]
### What is the expected behaviour?
Input field and cancel button should be disabled when an app import is in progress.

### What is the current behaviour?
Currently, when the app is being imported, the related input field and cancel buttons are not disabled.

### How to reproduce the issue?
1. Click on the ellipsis on the `Create new button` and select `Import`
2. Select a ToolJet app to import > Enter the app name
3. Click on `Import` - you will observe that the input field and cancel button are not disabled. 

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/58169101/ea007f02-b98f-43d3-bd3d-a12b189ba492

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by Godlearningtocode** [comment]
Hey karan, anyway i can try and contribute to this issue?

**Comment by karan-rathod-316** [comment]
Hi @Godlearningtocode, Assigning this to you. Happy coding :-)

**Comment by orinamio** [comment]
Hi all, please let me know if help is needed to resolve this issue within the deadline.

**Comment by Godlearningtocode** [comment]
Hi karan, i would like to apologize as i was not able to fix the bug yet. 
Due to some unforeseen circumstances i will not be able to work for the next few days and i am not sure if i would be able to complete the given task within the deadline.

**Comment by karan-rathod-316** [comment]
Hi @orinamio, 

Let me know if you can pick this up. Would be happy to re-assign it to you:-).

**Comment by orinamio** [comment]
@karan-rathod-316 happy to help. Yes, assign it to me :)

**Comment by karan-rathod-316** [comment]
@orinamio Done. Please not that this is a deadline-driven task and needs to be completed within 5 days.

**Comment by orinamio** [comment]
@karan-rathod-316 opened a PR [here](https://github.com/ToolJet/ToolJet/pull/9446) :)

**Comment by karan-rathod-316** [comment]
@orinamio Thank you for the quick turn-around. I will move this to review.
