### ISSUE TITLE
Docs:  update `ToolJet` to `ToolJet Solutions, Inc`

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#945]
<img width="1016" alt="Screenshot 2021-10-08 at 12 08 29 PM" src="https://user-images.githubusercontent.com/67645175/136510725-cee4a63f-0d7b-4019-b69f-69ffd35d3d92.png">

Change`ToolJet` to `ToolJet Solutions, Inc` (Footer)

**LInk**:  https://docs.tooljet.io/docs/intro/

**Comment by aparna2899** [comment]
Hey I want to contribute please assign me this.

**Comment by arpitnath** [comment]
Sure, assigning the issue to you. @aparna2899
