### ISSUE TITLE
Fix heading in dark mode for adding or editing a datasource

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#946]
### How to reproduce the issue?

1. Create a new App
2. From the Lefthand Sidebar click on `Add or edit datasource`

### Screenshots or 
<img width="354" alt="Screenshot 2021-10-08 at 12 21 03 PM" src="https://user-images.githubusercontent.com/67645175/136511812-4d4127ad-237f-412c-baba-59421b87d306.png">
Screencast

<img width="354" alt="Screenshot 2021-10-08 at 12 21 08 PM" src="https://user-images.githubusercontent.com/67645175/136511852-108fa2bc-2032-46a6-aeb1-6ef6b1d2abd7.png">

**Comment by aparna2899** [comment]
Please assign me this.

**Comment by thevibhu** [comment]
Can I take up this issue?

**Comment by arpitnath** [comment]
@aparna2899 are you still working on it?
