### ISSUE TITLE
Workspace Slug can automatically populate to workspace name

### ISSUE THREAD

**Issue by kriks7iitk** [ToolJet/ToolJet#9488]
### Is your proposal related to a problem?
User have to enter slug name when creating a workspace, it can inherit workspace name

(Write your answer here.)
Populate it to workspace name
### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

**Comment by shubh22** [comment]
Duplicate Issue #8978
