### ISSUE TITLE
'Show password' option on login screen

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#951]
### Is your proposal related to a problem?

Presently, the user cannot see the password they are typing in, at the login screen.

### Describe the solution you'd like

Add a checkbox and label saying 'show password' below the password input field.
Display the password as text when this checkbox is checked.

**Comment by akshitarora921** [comment]
@sherfin94 @Ishika414 Can I work on this?

**Comment by saisumanthkumar** [comment]
@sherfin94 can I work on this,I can resolve with in a day If you allow

**Comment by Navaneeth-pk** [comment]
@Ishika414 is there any update on this issue?

**Comment by AP2008** [comment]
@Navaneeth-pk Hi. I have started working on it. Can you please assign it to me ?

**Comment by saisumanthkumar** [comment]
@Navaneeth-pk  please check
<div style="display:inline">
<img src="https://user-images.githubusercontent.com/74057515/138036013-f83915ac-cfee-4e14-8308-6247fa867701.PNG" height="300px" />
<img src="https://user-images.githubusercontent.com/74057515/138036021-a42947f0-f613-42cf-985d-d24903cca284.PNG" height="300px" />
</div>
