### ISSUE TITLE
Click filter not working on edges in query manager

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9538]
**Description:** Clicking the filter button in the query manager has no effect on certain areas around the edge of the UI.

**Current behavior:** Clicking the filter button does not apply the filter to data points located near the edges of the query manager UI.

**Expected behavior:** Clicking the filter button should apply the filter to all data points within the query manager view, regardless of location.

**Steps to reproduce:**
1. Open the query manager.
2. Add few queries.
3. Apply a filter by clicking the filter button.
4. Observe that data points near the edges of the UI might not be filtered as expected.

**Comment by yanishbansal** [comment]
Hi Naveen, its a bit unclear about the problem and the desired expected behaviour , can you please attach the screenshot for this bug ?

**Comment by karan-rathod-316** [comment]
@GrowwithNaveen

**Comment by GrowwithNaveen** [comment]
@yanishbansal sure attaching a video grab for reference. The cursor only changes to a pointer (clickable) over the text part of the element, not the edges or corners. Ideally, the entire element should be clickable, not just the text.


https://github.com/ToolJet/ToolJet/assets/81761482/3fb58bca-4c8b-437c-8d58-cfc344d49200

**Comment by 2001asjad** [comment]
Hey @yanishbansal, would you be going forward with this issue?

**Comment by 609harsh** [comment]
hi @2001asjad  please assign this to me i am interested

**Comment by 2001asjad** [comment]
Sure @609harsh , assigning this issue to you. Happy coding :)

**Comment by PriteshKiri** [comment]
Hey @609harsh ,

Any updates on this issue?

**Comment by MK884** [comment]
I am interested in solving this issue

**Comment by PriteshKiri** [comment]
Sure! @MK884 

Assigned it to you. Happy coding :)

**Comment by PriteshKiri** [comment]
Thanks for submitting the PR @MK884 . Moving it to review.

**Comment by PriteshKiri** [comment]
Closed with PR https://github.com/ToolJet/ToolJet/pull/10039
