### ISSUE TITLE
Layout shift occurs in the component's style section on hover

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9560]
**Description:**
1. In the container component's styles section, [there is a noticeable layout shift when hovering over the background color](https://github.com/ToolJet/ToolJet/assets/81761482/ccb0617b-e42f-4172-9eaa-fcf8743ef537). This is also seen in List view component. This issue can be addressed by updating the copy with the word `Background` to prevent the layout shift instead of `Background color`.
2. In Tabs component, [there is a glitch in UI when we hover](https://github.com/ToolJet/ToolJet/assets/81761482/56c1cae5-d7cc-4ecc-b2e9-b058d7739fd4). Need to be exhaustively tested and fixed with other components.

**Comment by nandinisaha013** [comment]
This is fixed.
