### ISSUE TITLE
Table crashing on searching special characters

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9563]
**Description:**
This issue reports a crash that occurs when searching the table using the search bar with special characters.

**Current behavior:**
Searching the table for entries containing special characters like "*", "+", "(", ")" causes the table to crash.

**Expected behavior:**
The table search should function normally regardless of any special characters present in the search query or table data.

**Steps to reproduce:**
1. Open the table component with dummy data or your data.
2. Access the search bar for the table.
3. Enter a search query containing any special characters: "*", "+", "(", ")".
4. Initiate the search.
5. The table should crash upon performing the search.

[Attaching a video grab for reference](https://www.loom.com/share/ae82a908aab6452b9d6ee8d04284caf1?sid=2907c196-2607-4745-af8e-2fc6a2c3b8fb)

**Comment by Sadaf-A** [comment]
Hey @GrowwithNaveen !
I would like to work on this issue

**Comment by akshayjoshi892** [comment]
@GrowwithNaveen 
I guess this bug is not present at the moment.
[Screencast from 07-07-24 11:12:04 AM IST.webm](https://github.com/ToolJet/ToolJet/assets/67548071/237fdc8f-d6e1-4b8f-ae85-4e42ac497f75)
