### ISSUE TITLE
TJDB: Adding both FILTER and SORT conditions in the query throws error

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#9609]
### Version Information
Version 2.38.0-ee2.15.28-cloud2.3.11

### Environment
ToolJet Cloud 

### What is the expected behaviour?

The query should run smoothly with both conditions

### What is the current behaviour?

If either of SORT or FILTER conditions are used, query works fine.
As soon as both of them are added it throws in error.

### Screenshots or Screencast

**Case 1**
![image](https://github.com/ToolJet/ToolJet/assets/144771579/28f1d3c8-e64c-4243-98f7-2b9bc489dd51)
![image](https://github.com/ToolJet/ToolJet/assets/144771579/73066c8a-8bf5-4e5e-a29b-fa425dd4385c)

**Case 2**
![image](https://github.com/ToolJet/ToolJet/assets/144771579/7f198aa6-5559-469c-9532-9e5e6bdf56fb)
![image](https://github.com/ToolJet/ToolJet/assets/144771579/b2e2128d-88f5-44c7-8e93-31987b819719)

**Comment by Sadaf-A** [comment]
Hey @mansukh-tj !
I would like to work on this issue

**Comment by mansukh-tj** [comment]
@Sadaf-A Assigned!

**Comment by akshaysasidrn** [comment]
@Sadaf-A Kindly let us know if you have already started working on it. This is in priority and we are planning to have it fixed sooner. If you haven't started with it, we'll pick this up internally.

**Comment by Sadaf-A** [comment]
> @Sadaf-A Kindly let us know if you have already started working on it. This is in priority and we are planning to have it fixed sooner. If you haven't started with it, we'll pick this up internally.

Hey, I have started working on this and made some progress I will notify you if I'm not able to solve it on time
Thank You

**Comment by mansukh-tj** [comment]
@Sadaf-A Please let us know by today EOD. If not completed by today, we will be internally assigning it.

**Comment by Sadaf-A** [comment]
> @Sadaf-A Please let us know by today EOD. If not completed by today, we will be internally assigning it.

Hey, I haven't been able to solve it yet

**Comment by akshaysasidrn** [comment]
@Sadaf-A Hope you understand the urgency. This is breaking and we need to resolve it promptly. Therefore taking this up internally.

**Comment by Sadaf-A** [comment]
> @Sadaf-A Hope you understand the urgency. This is breaking and we need to resolve it promptly. Therefore taking this up internally.

Yes, I understand it took me a lot of time because I wasn't able to set up tooljet db locally initially
