### ISSUE TITLE
[refactor]: Add missing Spanish translations

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#9611]
### What is the expected behaviour?
When the language is changed to Spanish, all the labels should be in Spanish. 

### What is the current behaviour?
Currently, only partial labels have Spanish text.
![Screenshot 2024-04-30 at 11 51 39 AM](https://github.com/ToolJet/ToolJet/assets/58169101/1350b7ae-959a-47e7-a9a3-5e921c21770b)

### How to reproduce the issue?
1. Change the language to Spanish by updating the env (`LANGUAGE=es`)
2. Login to ToolJet
3. You can see that only some labels have Spanish text while others don't

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by AkshayKathiriya** [comment]
@karan-rathod-316  I'd like to work on this, can you assign me here.

**Comment by 2001asjad** [comment]
Hey @AkshayKathiriya, I am assigning this issue to you. Thanks for contributing to ToolJet.

**Comment by 2001asjad** [comment]
@AkshayKathiriya , are there any updates on this?

**Comment by AkshayKathiriya** [comment]
Hii @2001asjad, there is some labels remaining in app builder so working on it, after that will raise PR (Max tomorrow EOD).
Thanks.

**Comment by 2001asjad** [comment]
Hello @AkshayKathiriya, are there any updates from your side?

**Comment by AkshayKathiriya** [comment]
Hi @2001asjad, here is [PR](https://github.com/ToolJet/ToolJet/pull/9770).

**Comment by karan-rathod-316** [comment]
Moving this to review. Thanks @AkshayKathiriya!

**Comment by ShyanRoyChoudhury** [comment]
I would love to work on this issue.

**Comment by PriteshKiri** [comment]
Assigning it to you @ShyanRoyChoudhury. Happy coding :)

**Comment by ShyanRoyChoudhury** [comment]
Hi @karan-rathod-316. I am comparing the labels for `language=es` with different languages. I am not sure I quiet understand which labels you are referring to. Could you please share screenshots?

**Comment by PriteshKiri** [comment]
@ShyanRoyChoudhury whatever translations are there in the English language there should be a Spanish translation for it as well.

**Comment by PriteshKiri** [comment]
Thanks for the contribution @ShyanRoyChoudhury. Moving the issue to the review.

**Comment by PriteshKiri** [comment]
Unassigning the issue due to lack of progress.

**Comment by JorgeSanchez-Encora** [comment]
Hey, I would like to work on this issue!

**Comment by PriteshKiri** [comment]
@JorgeSanchez-Encora  assigned. Happy coding! 😊  

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by PriteshKiri** [comment]
Thanks for your contribution @JorgeSanchez-Encora.

`Quick PR`
