### ISSUE TITLE
Implement `Download all` functionality for server-side paginated data in table component

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9624]
**Description:**
This feature will allow users to download all available data from the server, regardless of the current page displayed in the table component. Currently, server-side pagination limits the records returned to the user's view. This functionality will bypass this limitation and provide a complete dataset for download.

**Design to be finalized.**

**Comment by GrowwithNaveen** [comment]
Solution brainstorming:
Add a new event for "Get table data" and with this solve this problem.

**Comment by Kartik18g** [comment]
[ee PR](https://github.com/ToolJet/tj-ee/pull/2767)

**Comment by Kartik18g** [comment]
**Description**
We've added a new event called download Data, which can be attached to the table.
This event will only trigger when user clicks the download button when server side pagination is enabled. In case table is server side paginated and no event is associated, the app will fallback to the old download flow.

**Comment by prajval-tooljet** [comment]
The download event is available for client side pagination tables too but is not functional, we need to make sure this won't be confusing for developers as it is only implemented for server side pagination
