### ISSUE TITLE
Improve UI style for data source headers

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#9627]
<img width="676" alt="Screenshot 2024-05-07 at 3 29 37 PM" src="https://github.com/ToolJet/ToolJet/assets/20367957/2c9252a0-3c51-4836-9ef7-ff95aaa73620">

**Comment by gsmithun4** [comment]
Style
https://www.figma.com/file/idCYgis6JK6jRI97i8IXa2/Data-source?type=design&node-id=5369-3205&mode=design&t=ukto82LUk0VYiDK7-0

**Comment by Abhishek-90** [comment]
@gsmithun4 , I am not able to access the figma design to view it. I have raised access request can you please look into it? I would like to take this issue.
