### ISSUE TITLE
`Divider` & `Vertical divider` component 2.0

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9644]
1. The icon for Divider & Vertical divider is exactly the same, whereas the divider icon should be horizontal.
2. `Divider` should be renamed to `Horizontal Divider`

![image](https://github.com/user-attachments/assets/63c5f2b6-b559-4f06-9567-acefb7a65329)

**Comment by SohamPatel0810** [comment]
Hi,
I can take up this task.

Thank you

**Comment by PriteshKiri** [comment]
Hey @SohamPatel0810, please let me know if you are still interested in working on this issue.

**Comment by SohamPatel0810** [comment]
Hi,
Yes I would like to take up the issue.

**Comment by SohamPatel0810** [comment]
Please assign it to me.

**Comment by SohamPatel0810** [comment]
Yes, I'm still interested.

**Comment by PriteshKiri** [comment]
Assigned @SohamPatel0810. Happy coding :)

**Comment by PriteshKiri** [comment]
Hey @SohamPatel0810, any updates on the issue?

**Comment by SohamPatel0810** [comment]
Hey ,
I have final exams going on so will be done by Tuesday.

**Comment by Himanshuch8055** [comment]
If @SohamPatel0810 is unable to do so, I would like to work on this issue.

**Comment by Tanush-J** [comment]
@Himanshuch8055 If you are not working on this, let me know, I can work on this.

**Comment by Himanshuch8055** [comment]
Go ahead, @Tanush-J. We appreciate your contribution. But remember, once this task is approved by any official contributor, then you can continue.

**Comment by PriteshKiri** [comment]
@SohamPatel0810 are you still working on the issue?

@Himanshuch8055 @Tanush-J as this issue is already assigned we will wait for @SohamPatel0810 to respond. Meanwhile you can check out other issues under `community contribution` lable.

Feel free to drop your queries in the contributor's channel of our [Slack community](https://tooljet.com/slack)

**Comment by SohamPatel0810** [comment]
I am unable to setup the database . If its urgency you can assign it to
someone else at the current moment.

**Comment by PriteshKiri** [comment]
@Himanshuch8055 are you still interested in working on this issue?

**Comment by Himanshuch8055** [comment]
Sure, I'll give it a try. @PriteshKiri

**Comment by PriteshKiri** [comment]
@Himanshuch8055  assigned. Happy coding! 😊  

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by PriteshKiri** [comment]
Hey @Himanshuch8055 

Any updates on the issue?

**Comment by PriteshKiri** [comment]
@Himanshuch8055 are you still working on this issue? Please let me know if you facing any issues.

**Comment by PriteshKiri** [comment]
Hey @Himanshuch8055 

Were you able to figure out the fix for this issue?

**Comment by PriteshKiri** [comment]
@Himanshuch8055 are you still working on this issue?

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress

**Comment by himanshudube97** [comment]
@PriteshKiri If this issue is not yet fixed , please assign it to me.

**Comment by PriteshKiri** [comment]
@himanshudube97 assigned. Happy coding! 😊  

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by himanshudube97** [comment]
@PriteshKiri I had one doubt. So the issue listed above is a `divider` component. But we also have a `dividerhorizontal` component, so do you want me to do changes to the divider component, or should i use `dividerhorizontal` component. 
I mean i can keep the Divider component as it is and do changes to `dividerhorizontal`.

**Comment by PriteshKiri** [comment]
Hey @himanshudube97 

As mentioned in the description, 

1. You have to change the icon name from "divider" to "Horizontal divider"
2. For the same component you have to change the verticle icon to horizontal, share the screenshot here

Looping in @GrowwithNaveen 

<img width="288" alt="image" src="https://github.com/user-attachments/assets/43f64710-2405-4f67-888d-d53c23dbab57">

**Comment by GrowwithNaveen** [comment]
Hi @himanshudube97

As mentioned by Pritesh this is the exact requirement for this issue. Feel free to check with us for any clarifications.  

CC: @DevangAgarwal93

**Comment by himanshudube97** [comment]
@PriteshKiri @GrowwithNaveen  Hi , i have added the pr to this issue
[https://github.com/ToolJet/ToolJet/pull/10832](url)

Thank you.

**Comment by PriteshKiri** [comment]
Thanks for your contribution @himanshudube97 🙌

**Comment by kushalsourav** [comment]
@PriteshKiri
Hi, I'd like to work on this issue if it's open and unassigned. Could you please assign it to me? 
Thank you!

**Comment by PriteshKiri** [comment]
Hey @kushalsourav ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!
