### ISSUE TITLE
Unintended UI behavior in `Horizontal divider` component

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9645]
**Issues:**
1. Unadjustable white space below the divider.
2. Fixed height of the divider, preventing size customization.

**Current behavior:**
- The Horizontal Divider component displays with an unchangeable amount of white space below it.
- There is no option to modify the divider's height, resulting in a fixed size.

**Expected behavior:**
- The white space below the divider should be adjustable or eliminated entirely.
- Users should be able to customize the divider's height.

**Steps to reproduce:**
1. Implement the Horizontal Divider component in your application.
2. Observe the white space below the divider.
3. Attempt to adjust the divider's height. You will find that the height remains fixed.

Attaching a video grab for reference,

https://github.com/ToolJet/ToolJet/assets/81761482/7a9f5313-5dac-4db1-890c-49bfb6492140

**Comment by overlyhonest** [comment]
Design review 
- Horizontal divider is fixed, but will need to look into vertical devider as well. The issues are
- - Vertical divider has uneven spacing on each side 
- - Vertical divider can exist in zero columns 


@GrowwithNaveen

**Comment by overlyhonest** [comment]
`Vertical divider can exist in zero columns`

This is only happening in this PR, we need to fix this.
