### ISSUE TITLE
Table search - Empty String search handling with `searchText`

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9659]
**Problem Description**
Currently, clicking the "x" button within the Table component's search function resets the `searchText` to an empty string. However, this empty string is not passed through the `searchText`. 

**Solution**
Update `searchText` with Empty String: Modify the click event handler for the "x" button to explicitly update the `searchText` property with an empty string.

**Comment by johnsoncherian** [comment]
Already released under https://github.com/ToolJet/tj-ee/pull/1363
