### ISSUE TITLE
Add Search Bar and Alphabetical Sorting for Workspace Constants

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#9664]
The workspace constants page currently lacks a search bar, hindering efficient navigation. Moreover, the current arrangement prioritizes displaying the most recent addition at the top, which could be improved by sorting the constants alphabetically by name.

**Comment by nechalmaggon** [comment]
Hi @sahilshityalkar so sorry for the late reply. Firstly, thank you for expressing interest in contributing to ToolJet, we're always delighted to have more contributors! However, this issue will be resolved internally. Please look out for issues with the label `up-for-grabs` - those are the ones open to the community. Feel free to respond with any questions you may have! 

cc- @PriteshKiri

**Comment by sahilshityalkar** [comment]
No worries, thanks for the update!
