### ISSUE TITLE
TJDB: As a user, I should be able to import applications and tables with its foreign keys created

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#9695]
### Is your proposal related to a problem?
The current import/export API does not support the creation of tables with foreign keys.

### Describe the solution you'd like
Upon importing tables, it should have the same schema as that of import. 

### If the feature is approved, would you be willing to submit a PR?
No

**Comment by shaurya-sharma064** [comment]
https://github.com/ToolJet/ToolJet/pull/9661
