### ISSUE TITLE
TJDB: Fix icon for '+ Add relation' button as per design

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#9699]
### Version Information
v2.42.0

### Environment
all

### What is the expected behaviour?
Should conform as per design [file](https://www.figma.com/design/tYa0dxFKAObnxC8Jx0ACzn/TJ-DB?node-id=4668-85261&t=znfEpzcyicMdYljt-0)

### What is the current behaviour?
![image](https://github.com/ToolJet/ToolJet/assets/11629675/06e44064-1b77-4031-9a7d-8a0d5f1fdc29)

**Comment by parthy007** [comment]
Is it already fixed?
![Screenshot 2024-05-16 at 12 47 26 PM](https://github.com/ToolJet/ToolJet/assets/108089718/13a36d66-1da7-441c-818c-a110307a629a)

**Comment by mansukh-tj** [comment]
No, See design
<img width="611" alt="image" src="https://github.com/ToolJet/ToolJet/assets/144771579/590507e9-f8ef-4388-8f2b-5877d319cbd5">


vs

current behavior

<img width="626" alt="Screenshot 2024-05-16 at 2 28 53 PM" src="https://github.com/ToolJet/ToolJet/assets/144771579/c33f244d-97b8-4177-be66-2d711a4d8c2a">

**Comment by parthy007** [comment]
> No, See design <img alt="image" width="611" src="https://private-user-images.githubusercontent.com/144771579/331130672-590507e9-f8ef-4388-8f2b-5877d319cbd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTQ3ODMsIm5iZiI6MTcxNTg1NDQ4MywicGF0aCI6Ii8xNDQ3NzE1NzkvMzMxMTMwNjcyLTU5MDUwN2U5LWY4ZWYtNDM4OC04ZjJiLTU4NzdkMzE5Y2JkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxMDE0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmU3NGFmY2EzNWVkOTNhNDI2ZTE2MGNkZDNlMDdiYzBmMWYyZDJjNzEzNWQ3ZTRhNDg0OGMyZjdmNmY4YzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D0X2eNGNue0G6yuwzfeBeSLQ87ueZL-IM-Qn_F9p8gI">
> 
> vs
> 
> current behavior
> 
> <img alt="Screenshot 2024-05-16 at 2 28 53 PM" width="626" src="https://private-user-images.githubusercontent.com/144771579/331130839-c33f244d-97b8-4177-be66-2d711a4d8c2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTQ3ODMsIm5iZiI6MTcxNTg1NDQ4MywicGF0aCI6Ii8xNDQ3NzE1NzkvMzMxMTMwODM5LWMzM2YyNDRkLTk3YjgtNDE3Ny1iZTY2LTJkNzExYTRkOGMyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxMDE0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzQxZjBhNDQ2ZWQ3OWFjMzRkOGE1ZmYxZTA3YWVjZjI4MDkwMDM4NGJkYmU2NThkNzI0OTk1MGYyNjhjZjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SRGfe9AEMmHx_yqZsU2wnMempLQfu5uv3OR5QiYj8LY">

I think all this is a part of this issue [#9698](https://github.com/ToolJet/ToolJet/issues/9698)

**Comment by mansukh-tj** [comment]
<img width="472" alt="image" src="https://github.com/ToolJet/ToolJet/assets/144771579/a103674c-eaaf-4c18-a173-cbcb2a9fe56c">

Current disabled state has to be changed to this
