### ISSUE TITLE
TJDB: As a user, I should be able to directly type over NULL values

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#9709]
### Is your proposal related to a problem?
Currently, the user can't type on NULL values. 

In table cell edit: 
User have to either switch set null toggle to false or press backspace.
![image](https://github.com/ToolJet/ToolJet/assets/11629675/522666bf-7756-48d2-8c9a-3d4ebf8ae6c4)

In edit row:
User has to click on null toggle to be able to type in values to overwrite
![image](https://github.com/ToolJet/ToolJet/assets/11629675/d4d832d0-f088-4b3a-a1b4-9b72c2649a8e)

### Describe the solution you'd like
User should be able to typeover predefined values in edit cell and edit column

**Comment by shaurya-sharma064** [comment]
https://github.com/ToolJet/ToolJet/pull/9739
