### ISSUE TITLE
TJDB: Create new button not aligned

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#9712]
### Version Information
v2.42.0

### Environment
all

### What is the expected behaviour?
`Create new table` button should be aligned similar to rest of the resources like, apps & workflows

### What is the current behaviour?
The button is not aligned like the apps & workflows create button
![image](https://github.com/ToolJet/ToolJet/assets/11629675/d5d29060-8d05-4502-aa44-0ced3bee37c7)

**Comment by santosh-kuchetti** [comment]
![image](https://github.com/ToolJet/ToolJet/assets/106766496/86702965-1b2c-4ffa-89da-a241f39e1df2)
![image](https://github.com/ToolJet/ToolJet/assets/106766496/c4934a6b-a9b6-4f97-8c27-8139d37ff6a4)

@akshaysasidrn, both buttons allignments are same.
Can you explain more about what expect the alignment is wrong, it would be helpful if mentioned in detail
