### ISSUE TITLE
TJDB: Editing the column name after foreign key is made breaks create/edit table

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#9718]
### Version Information
v2.42.0

### Environment
all

### What is the expected behaviour?
Editing the column name should update the foreign key relation accordingly

### What is the current behaviour?
Foreign key relation made will not be updated with the new column name and thus create/edit table fails

### Screenshots or Screencast
![editing-col-name](https://github.com/ToolJet/ToolJet/assets/11629675/20244629-f7f4-4617-9dc6-4251e1e4b0ea)

**Comment by shaurya-sharma064** [comment]
https://github.com/ToolJet/ToolJet/pull/9742
