### ISSUE TITLE
User email should not be clickable

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#972]
![image](https://user-images.githubusercontent.com/7828962/136765935-8c90e104-91a6-4309-950a-c6b0224f2d82.png)

Page: https://stagingbe.tooljet.io/users

The email of the users should not be a link.

**Comment by shreyakumari10** [comment]
Can I give it a try?

**Comment by Navaneeth-pk** [comment]
Thanks for contributing to ToolJet. Assigned the issue. @DarkSoul26 

Thanks for your interest in contributing but have to assign the issue to the person who commented first. @shreyakumari10

**Comment by DarkSoul26** [comment]
@Navaneeth-pk can you tell how to start the frontend. As **npm start** isn't working properly.

**Comment by Navaneeth-pk** [comment]
@DarkSoul26 is there any update on this issue?
