### ISSUE TITLE
`Unable to save changes` error when duplicating a page

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9720]
**Description:**
When attempting to duplicate a page, the system encounters an "unable to save changes" error. This prevents the successful duplication of the page.

**Current behavior:**
Duplicating a page results in an "unable to save changes" error, and the changes are not saved.

**Expected behavior:**
Duplicating a page should successfully create a copy of the page without encountering any errors.

**Steps to reproduce:**
1. Navigate to the page you wish to duplicate.
2. Select the option to duplicate the page.
3. Observe the "unable to save changes" error message.

**Notes:**
This issue needs to be resolved to ensure that users can duplicate pages without errors. Ensure to check both the frontend and backend processes involved in the page duplication.

**Comment by stepinfwd** [comment]
closed in perfomance PR
