### ISSUE TITLE
TJDB: The respective error field border should highlight with the error toast message

### ISSUE THREAD

**Issue by Mekhla-Asopa** [ToolJet/ToolJet#9753]
### Is your proposal related to a problem?
If there are more than six columns in a row, when adding a new row or editing a row, Unable to identify the error field.

### Describe the solution you'd like
The respective error field border should highlight with red colour

**Comment by mansukh-tj** [comment]
![image](https://github.com/ToolJet/ToolJet/assets/144771579/69ed4e12-c0c6-4a84-851e-67540b60faf6)

This feature will be used to highlight empty inputs on row creation (while pressing Enter without filling all fields) with error message "Cannot be empty" after #9749 is completed and on creation if backend throws error for a column value, highlight with error message "Data type mismatch"
