### ISSUE TITLE
TJDB: Add keyboard support for create a row and adding next simultaneously using `Shift+Enter`

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#9769]
This issue is in continuation of #9749

### Is your proposal related to a problem?
Currently, when user creates a row he has to do the following steps
1. click "Add data"
2. click "Add row"
3. Add data in "create a row" drawer
4. Click "Create Row" or after the issue mentioned above is completed, press "Enter" key after last input 
5. Row is saved, Drawer closes

Then after that if he wants to add another row he has repeated all of these steps again. Step 1 & 2 are redundant steps
 
### Describe the solution you'd like
Add keyboard support for Create and Add next with "Shift + Enter" that we keep the drawer open to add next row. Need to add its indicator in the "Create Row" drawer as below. Changes to be made in footer 
1. Text to indicate shortcut id functional
2. "Enter" icon inside "Create" button
<img width="1386" alt="image" src="https://github.com/ToolJet/ToolJet/assets/144771579/498b0510-cf96-4cb1-9cd3-32fcbe07fd9b">

**Comment by sahilshityalkar** [comment]
I'd like to work on this issue .
