### ISSUE TITLE
[docs]: Add Salesforce plugin docs describing how it configure it and what queries we support

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#9771]
### Summary

Detailed Salesforce docs have to be created to explain all operations we support. Currently we support
1. SOQL query
2. CRUD Action
- Create
- Retrieve
- Delete
- Update

### Issue Type

Documentation feature/update

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by amanregu** [comment]
Added under https://github.com/ToolJet/ToolJet/pull/9819
