### ISSUE TITLE
Table component breaks with `nested object` in data

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9775]
**Description:**
The table component is currently breaking when provided with a nested object in the data. Ideally, the table should handle incorrect data structures gracefully without causing a break.

**Steps to reproduce:**
1. Add a new table component to a page.
2. Create a sample dataset with nested objects.
3. Bind the prepared dataset with nested objects to the table component via Query manager.
4. Notice that the table component breaks, when it encounters the nested object in the dataset.

**Expected Behavior:**
The table component should not break. Instead, it should handle the nested objects, possibly by either flattening the data or ignoring nested structures while displaying a warning or error message.

**Solution:**
Please investigate and implement a solution to ensure the table component can manage nested objects without breaking.

Slack thread: https://tooljet.slack.com/archives/C02QT13RF51/p1716176291347559

**Comment by johnsoncherian** [comment]
Released to EE LTS in https://github.com/ToolJet/tj-ee/releases/tag/EE-LTS-2.50.4.2
