### ISSUE TITLE
Same colour badge for active and archived user

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#979]
### Environment
all

### What is the current behaviour?
Currently both active and archived user has same colour badges on users page.  

### How to reproduce the issue?
visit `/users` page

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/11629675/136809193-3924d934-8328-47c0-95de-629053191092.png)

### Any possible solutions?
Make use of red badge from [tabler](https://preview.tabler.io/docs/badges.html) for archived user

### Can you identify the location in the driver source code where the problem exists?
https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/ManageOrgUsers/ManageOrgUsers.jsx

**Comment by TheLearneer** [comment]
Hi there, I would like this fix this. :v:
