### ISSUE TITLE
[Components] Some components can't be moved by dragging on the body of the component

### ISSUE THREAD

**Issue by bleachyin** [ToolJet/ToolJet#9803]
1. The container can't be moved by mouse dragging
2. Calendar has some issue at times while trying to move by pressing on the body.
3. Kanban

**Comment by GrowwithNaveen** [comment]
Hi @bleachyin,

We've reproduced the issue. Currently, a container can be moved by clicking and dragging the configuration handle, but not by clicking inside the container.

Could you please try moving it using the configuration handle? Attached is a reference video.

Thank you.

https://github.com/ToolJet/ToolJet/assets/81761482/439d74b4-fc4a-409f-bd60-cf337f6dabd3
