### ISSUE TITLE
Show error message in toast when clone app fail

### ISSUE THREAD

**Issue by roofeel** [ToolJet/ToolJet#9809]
### Version Information
v2.43.0

### Environment
MacOS

### What is the expected behaviour?
show error message in toast

### What is the current behaviour?
error detail message not shown

### How to reproduce the issue?

1. change if condition to true, force throw error in https://github.com/ToolJet/ToolJet/blob/develop/server/src/services/tooljet_db_import_export_service.ts#L17
2. clone app

### Screenshots or Screencast
<img width="886" alt="image" src="https://github.com/ToolJet/ToolJet/assets/1115454/601071fc-911a-4516-82ac-208fbe479a70">

### Please provide any traces or logs that could help here.
<img width="1094" alt="image" src="https://github.com/ToolJet/ToolJet/assets/1115454/a1a7a522-64af-4526-9765-f21350139ae3">

### Any possible solutions?
fix typo in code e -> error

### Can you identify the location in the driver source code where the problem exists?
https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/_components/AppModal.jsx#L93

### If the bug is confirmed, would you be willing to submit a PR?
YES

**Comment by karan-rathod-316** [comment]
Hi @roofeel, thank you for creating the PR for this issue. Moving this to review!

**Comment by priteshTJ** [comment]
Hey @roofeel ! :tada: 

We wanted to take a moment to acknowledge your amazing contribution to the ToolJet community issues..

As a token of our appreciation, we'd like you to accept this badge: [Quick Fixer](https://logo-badges.tooljet.com/quick-fixer-badge.svg) You can add it to your GitHub profile or dev portfolios via readme file.


<div align="left">

[![ToolJet Quick Fixer](https://logo-badges.tooljet.com/quick-fixer-badge.svg)](https://github.com/ToolJet/ToolJet/issues)

</div>

You can add the following code to your readme file

```
<div align="left">

[![ToolJet Quick Fixer](https://logo-badges.tooljet.com/quick-fixer-badge.svg)](https://github.com/ToolJet/ToolJet/issues)

</div>
```

We really value your efforts, and please don't hesitate to keep contributing!  Feel free to check out the `up-for-grab` [issues](https://github.com/ToolJet/ToolJet/issues) for more opportunities.
