### ISSUE TITLE
User groups management select search dropdown not showing selected value

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#984]
### Version Information
develop

### Environment
all

### What is the expected behaviour?
click on multi-select drop-down does not populate the selection

### What is the current behaviour?
select options should be shown as in react-select-search
https://react-select-search.com/?path=/story/multiple-select--search

### How to reproduce the issue?
1.login as admin
2.goto /groups and edit a group
3. try selecting apps or users from dropdown

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/11629675/136825390-3dcdfb5a-f6b0-4b4a-abbe-2da4da043bb2.png)

**Comment by Navaneeth-pk** [comment]
Assigned to you. Thanks for contributing to ToolJet.
@Bhavin789

**Comment by Bhavin789** [comment]
Hi @Navaneeth-pk, this is finally resolved 🎉 . Just closed native postgresql running on `5432` port. Docker spun it up for me with a breeze!

I will start looking into it. Thanks!

**Comment by shivangT** [comment]
Fixed
