### ISSUE TITLE
Loading state fixes

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#9841]
Fixing loading states for - 
- App dashboard
- Data sources dashboard
- Workspace login

**Comment by 609harsh** [comment]
Please assign this issue to me

**Comment by nechalmaggon** [comment]
Hi @609harsh thanks for showing your interest, however this issue will be resolved internally. Do look out for issues tagged with `up-for-grabs` as those are the ones open for the community!

**Comment by 609harsh** [comment]
ohh okay i am already familiar with code base of Tooljet so was looking forward for some more good contributions.

**Comment by 2001asjad** [comment]
Hey @609harsh, thanks a lot for showing interest in contributing to ToolJet. You can look at this open issue: #9538. Let us know if you're interested in taking this one. I'll be happy to assign this to you :)

**Comment by 609harsh** [comment]
yes i am interested

**Comment by 2001asjad** [comment]
Awesome! Please comment on the issue, and I'll assign it to you.
