### ISSUE TITLE
Make use of trash icon for users and group permission deletions

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#985]
### Is your proposal related to a problem?
User or group permission related deletions are currently a link and has no progress indication involved

### Describe the solution you'd like
Update these to trash icon and add loading state when deletions are performed

/users page
![image](https://user-images.githubusercontent.com/11629675/136826751-6108f3ef-4ee1-445f-aa44-30a2305111dd.png)

/groups page
![image](https://user-images.githubusercontent.com/11629675/136826814-a03d1e46-10dc-44fe-8c49-ecd983fcaaf5.png)

/groups/:id page
![image](https://user-images.githubusercontent.com/11629675/136827076-16493c4e-3af9-496e-8764-df7eeb826b9a.png)
![image](https://user-images.githubusercontent.com/11629675/136827156-07109a83-7cde-41a5-80e4-ac27732efc32.png)

**Comment by withshubh** [comment]
Hey @saimaheshtaduri 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by WadekarPrashant** [comment]
Hey, can I work on this issue? Please assign it to me.

**Comment by withshubh** [comment]
Hey @WadekarPrashant 
This issue is already assigned to someone. Please look for issues that are unassigned.

**Comment by withshubh** [comment]
Hey @saimaheshtaduri - Any updates on it?

**Comment by saimaheshtaduri** [comment]
@withshubh I'll raise a pr in a day or two. 
Thanks :)
