### ISSUE TITLE
Introducing two types of workspace constants

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#9855]
1. Server side- secrets- masked & encrypted values- restricted usage
2. Client-side- repeatable values- no encryption

**Comment by gsmithun4** [comment]
Added this to scope
Constants with any other string attached with it
![](https://files.slack.com/files-pri/T01U3V1QJTE-F07DDKZUB6V/screenshot_2024-07-18_at_6.33.45___pm.png)
