### ISSUE TITLE
Feature: Request confirmation before leaving editor

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#987]
![image](https://user-images.githubusercontent.com/7828962/136904728-ae104b40-5198-4ff0-8463-64866709c39b.png)

When a user click on the back button from the app builder, a confirmation dialog needs to be displayed with the text: "The unsaved changes will be lost if you leave the editor".

**Comment by dluk** [comment]
Do we have some way to detect if there are unsaved changes or should we just show confirmation dialog even if there are no actual changes made to the app?
