### ISSUE TITLE
Rest API : Option to manually toggle off Retrying once the request fails

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#9876]
### Problem
Currently, the one a REST query fails, the query is re hits the endpoint again 3 times by default. The might not be ideal behaviour for some API requests.

### Solution
In both static and global REST API data sources, we need a toggle button to switch this behaviour. By default if will always be toggle on with the copy:

"Retry on network errors"

Global DS
<img width="623" alt="image" src="https://github.com/ToolJet/ToolJet/assets/144771579/18a195ed-f086-4a7e-a383-4a725a1b13a0">

Global DS - Query Builder
<img width="707" alt="image" src="https://github.com/ToolJet/ToolJet/assets/144771579/afb156bb-d1bd-41f3-9a89-a0f81c42ea39">

_Note: If in config toggle is on and in particular query of this ds is toggle is off, then Query builder option will be given precedence over that of ds config_

Static DS - Query Builder
<img width="714" alt="image" src="https://github.com/ToolJet/ToolJet/assets/144771579/befd887b-5e33-4c1d-a4f0-b01f0cfdfc2b">

**Comment by sahilshityalkar** [comment]
Can you assign this issue to me? I'd like to work on it.
