### ISSUE TITLE
Icon to close inspector is not visible in dark mode

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#988]
![image](https://user-images.githubusercontent.com/7828962/136910708-8f626aac-3314-4c6f-b99d-ec71434e5584.png)

The icon inside the button to close the inspector is not visible in dark mode.

**Comment by Navaneeth-pk** [comment]
Thanks for contributing @Snehpatel007, assigned the issue.

**Comment by ThisIsFaar** [comment]
> @Snehpatel007 are you still working on it?

@arpitnath If there is no reply, I am here to solve 💪

**Comment by arpitnath** [comment]
@ThisIsFaar thank you for contributing, assigning it to you

**Comment by ThisIsFaar** [comment]
@arpitnath is it fine?
![image](https://user-images.githubusercontent.com/67395591/138222836-6b482a3c-7979-4f3f-bf52-18329ead2e64.png)

**Comment by arpitnath** [comment]
> @arpitnath is it fine? ![image](https://user-images.githubusercontent.com/67395591/138222836-6b482a3c-7979-4f3f-bf52-18329ead2e64.png)

can you raise a PR?
