### ISSUE TITLE
DigitalOcean one-click-deploy is broken

### ISSUE THREAD

**Issue by rapcal** [ToolJet/ToolJet#9885]
### Version Information
N/A

### Environment
Trying to deploy to DigitalOcean with one-click-install

### What is the expected behaviour?
According to [the docs](https://docs.tooljet.com/docs/setup/digitalocean/), "A new tab will open up, sign-in to your DigitalOCean account. Once signed-in, the Create App page will open up and Resources will be already selected. Click on Next button."

### What is the current behaviour?
An error message appears saying

> Error while creating app from Git template
> Could not create app from Git template.
> Unexpected token '<', "<!DOCTYPE "... is not valid JSON.

It seems DigitalOcean is expecting application/json and getting text/html

### How to reproduce the issue?

1. Access https://cloud.digitalocean.com/apps/new?repo=https%3A%2F%2Fgithub.com%2FToolJet%2FToolJet%2Ftree%2Fmain OR
2. Click the deploy button on [this page](https://docs.tooljet.com/docs/setup/digitalocean/)

### Screenshots or Screencast
![image](https://github.com/ToolJet/ToolJet/assets/620436/6377c84d-1625-48b1-a7c5-1975c1422439)

### Please provide any traces or logs that could help here.
N/A

### Any possible solutions?
Couldn't find any

### Can you identify the location in the driver source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
If you point me in the right direction, sure!

**Comment by rapcal** [comment]
Thanks a lot. Sorry to bother the team with something that isn't on your end.

**Comment by adishM98** [comment]
No worries at all! Thank you for pointing out the issue.

**Comment by adishM98** [comment]
Hi @rapcal , 

The issue with Digital Ocean has been resolved. You can now proceed with the Digital Ocean one-click deployment.
