### ISSUE TITLE
Replace column name "``Mobile_number``" with "``Phone``" in demo data of table component

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9899]
**Problem Description:**
In the current implementation of the Table component's demo data, the column name for mobile numbers is labeled as "Mobile_number." 

**Solution:**
For better readability and consistency, this column name should be updated to "Phone" This change will improve the clarity and user experience of the Table component.

**Comment by aman8218** [comment]
@GrowwithNaveen can you give me the more details about the table and can you assign me this issue??
