### ISSUE TITLE
Community template: Digital asset management 

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9923]
**Description:**
This template provides a solution for a user-friendly digital asset management system that seamlessly integrates with ToolJet, allowing users to create, organise, and manage digital assets effortlessly.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1rHsNiVMPstknbZ-Riiln_Sf6_QfncpCQl_nFQIah3BI/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within 10 working days and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within 10 working days or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by karan-rathod-316** [comment]
Hi @Sranjan0208, assigning this to you. The deadline for this issue is 7 days. Please go through the documentation before you proceed.  

Thank you so much for your interest in contributing to ToolJet.

**Comment by PriteshKiri** [comment]
Hey @Sranjan0208 ,
Any updates on this?

**Comment by Sranjan0208** [comment]
I am done with the most of the work just this part "On hovering a field in asset table - the asset data gets reflected on the right side card. Refer below screenshot-" is left

**Comment by PriteshKiri** [comment]
Hey @Sranjan0208 are you done with the template?

**Comment by PriteshKiri** [comment]
Hey @Sranjan0208, any updates??

**Comment by Jyotipal29** [comment]
hey @PriteshKiri  i would like to work on this issue . could you please assign it to me

**Comment by PriteshKiri** [comment]
Hey @Jyotipal29, assigned the issue to you.

Please feel free to drop your queries in the contributor's channel of our [Slack community](https://tooljet.com/slack)

**Comment by Nishant-FactWise** [comment]
hey @PriteshKiri i would like to work on this issue . could you please assign it to me

**Comment by shivang2000** [comment]
hey @PriteshKiri i would like to work on this issue . could you please assign it to me

**Comment by shivang2000** [comment]
Hey @PriteshKiri  I have already raise a issue that i am not able to run the application locally on my system do you have an update on it for me ?

**Comment by PriteshKiri** [comment]
Hey @shivang2000, I hope your local is up and running now.

**Comment by PriteshKiri** [comment]
@shivang2000 are you still working on the issue?

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress.

**Comment by anasKhafaga** [comment]
Hello @PriteshKiri, Can I work on this issue?

**Comment by PriteshKiri** [comment]
Thanks for your contribution @anasKhafaga.

**Comment by GrowwithNaveen** [comment]
Hey @anasKhafaga  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!
