### ISSUE TITLE
Community template: Transportation logistics tracker

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9924]
**Description:**
This template enables to track pickup times, group sizes, estimated travel times, and promptly communicate any changes to drivers.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1c3vZQIdDHdh6DXwYmqpDtaX0PX0VdoVqI7eOY9l18oo/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within 10 working days and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within 10 working days or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by kinskiwu** [comment]
Hi I'd like to work on this ticket. Ty!

**Comment by PriteshKiri** [comment]
@kinskiwu assigned to you. Happy coding :) If there is any clarification needed feel free to check with us in our dedicated [Slack thread](https://tooljet.slack.com/archives/C05SSQF138F/p1717070821941189).

**Comment by PriteshKiri** [comment]
Thanks for your contribution @kinskiwu. Moving the issue to review.

**Comment by GrowwithNaveen** [comment]
Hey @kinskiwu  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!

**Comment by kinskiwu** [comment]
@GrowwithNaveen Thank you so much! It's great working with the team!

**Comment by kinskiwu** [comment]
@PriteshKiri Of course! I posted the experience on Linkedin a while back. Let me share the link on Slack so other contributors can see it😊

**Comment by PriteshKiri** [comment]
Sure @kinskiwu!! You can share it in the #community-showwcase channel 🙌
