### ISSUE TITLE
Community template: Course management for online courses

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9925]
**Description:**
This template allows you to manage online courses effortlessly. Add and update course details, list all courses, and filter by category for easy navigation.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1tmV_Q2BRkZUMUkcXpXW4_m1HjU0m_aCxyOGSYJ4AKMo/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within 10 working days and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within 10 working days or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by nikhil822** [comment]
Hi @GrowwithNaveen. I would like to work on this task. Could you please assign this task to me?

**Comment by PriteshKiri** [comment]
Hey @nikhil822 

Assigned to you. Please go ahead, if there is any clarification needed feel free to check with us in our dedicated [Slack thread](https://tooljet.slack.com/archives/C05SSQF138F/p1717070821941189).

**Comment by MK884** [comment]
i am interested to work on this template. could you assign it to me?

**Comment by sebzz2k2** [comment]
Hey @GrowwithNaveen can i work on this.

**Comment by PriteshKiri** [comment]
@sebzz2k2 assigned to you. Please go ahead, if there is any clarification needed feel free to check with us in our dedicated [Slack thread](https://tooljet.slack.com/archives/C05SSQF138F/p1717070821941189).

**Comment by PriteshKiri** [comment]
Hey @sebzz2k2, any updates on the template?

**Comment by PriteshKiri** [comment]
Hey @sebzz2k2  any updates on the template? Please let me know if you are facing any issues.

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress.

**Comment by AnkityadavIITR** [comment]
Hii @PriteshKiri , if this issue is still unassigned i'm interested to working on this

**Comment by PriteshKiri** [comment]
@AnkityadavIITR assigned. 🙌

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by AnkityadavIITR** [comment]
Hii @PriteshKiri ! , I've successfully created the PR for this issue, please review it let me know if anything else needs to be done. Thanks :)

**Comment by PriteshKiri** [comment]
Thanks for your contribution @AnkityadavIITR. Moving it to testing.

**Comment by GrowwithNaveen** [comment]
Hi @AnkityadavIITR, Thank you for your excellent work on the template. We've already confirmed that it meets our requirements. We’ll be deploying it shortly and will provide an update once it’s live.

**Comment by AnkityadavIITR** [comment]
Thank you, @GrowwithNaveen, for keeping me updated on the process. I look forward to seeing my contribution go live soon :)

**Comment by AnkityadavIITR** [comment]
Hi @GrowwithNaveen ,
I hope you're well! I wanted to follow up on the PR I submitted. I noticed it’s been a few weeks since the last update, and I was wondering if there’s any further feedback or timeline on when it might be merged. I’d be happy to assist with any additional steps if needed. Thank you for your time, and I look forward to hearing from you!

**Comment by GrowwithNaveen** [comment]
Hi @AnkityadavIITR, thanks for following up. We're currently working on some refactoring optimizations in our codebase, which has caused a delay in merging and deploying the community templates. We're in the final stages of these optimizations, and the templates should be deployed by the last week of October. If there are any changes to this timeline, either earlier or later, we'll make sure to update you in advance.

**Comment by AnkityadavIITR** [comment]
Thanks @GrowwithNaveen for the response and update

**Comment by GrowwithNaveen** [comment]
Hey @AnkityadavIITR  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!

**Comment by AnkityadavIITR** [comment]
Thanks @GrowwithNaveen for this amazing badge !!

**Comment by PriteshKiri** [comment]
Hey @AnkityadavIITR!!

Looking forward to your post on our #community showcase channel. :)

You can post a video or image with a few words about your template and building experience.
