### ISSUE TITLE
Community template: Student Management for online courses

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9926]
**Description:**
This template simplifies student management for online courses. List all students, add and update student details, and filter by course and occupation name. 

**Template feature list:**
Please check [here](https://docs.google.com/document/d/112hE6x5YR3VINO8eZTr0HQs3zHzGazuFwT1YXyPfUTw/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within **7 working days** and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within **7 working days** or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by alexlazellari** [comment]
Hii, I would like to work on this template. Can you please assign it to me?

**Comment by GrowwithNaveen** [comment]
@alexlazellari assigned to you. Please go ahead, if there is any clarification needed feel free to check with us in our dedicated [Slack thread](https://tooljet.slack.com/archives/C05SSQF138F/p1717070821941189).

**Comment by PriteshKiri** [comment]
Hey @alexlazellari, any updates on the template?

**Comment by alexlazellari** [comment]
Hi @PriteshKiri, I have already done my pull request here: https://github.com/ToolJet/ToolJet/pull/10083

**Comment by PriteshKiri** [comment]
Thanks for your contribution @alexlazellari. Moving the issue to review.

**Comment by GrowwithNaveen** [comment]
Hi @alexlazellari submitted [PR](https://github.com/ToolJet/ToolJet/pull/10083) doesn't have the template UI and functionalities. Can you please check the [Template feature list ](https://docs.google.com/document/d/112hE6x5YR3VINO8eZTr0HQs3zHzGazuFwT1YXyPfUTw/edit?usp=sharing) and create this template?

**Comment by PriteshKiri** [comment]
Hey @alexlazellari,

Any updates on the issue?

**Comment by mnshrm** [comment]
Hi @PriteshKiri,
Can I work on this issue?

Regards,
Aman Sharma

**Comment by PriteshKiri** [comment]
@alexlazellari unassigning due to lack of progress.

**Comment by PriteshKiri** [comment]
@mnshrm assigned!!

Please note that the deadline for this task is 7 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.

**Comment by mnshrm** [comment]
Hi @PriteshKiri,
Can you please share the slack link again

Thanks

**Comment by PriteshKiri** [comment]
Sure! Please join via [this](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) link

**Comment by PriteshKiri** [comment]
Hey @mnshrm,

Any updates on the issue?

**Comment by mnshrm** [comment]
Hi @PriteshKiri, 
I have completed majority of the template, but a facing a small issue, I have posted it in slack, awaiting reply for the same

**Comment by mnshrm** [comment]
Hi @PriteshKiri,
I have raised PR for the issue #11072, I was unable to add reviewers in it for some reason, please let me know if any discrepancy is found

**Comment by PriteshKiri** [comment]
Hey @mnshrm ,

Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by yuvi-mittal** [comment]
heyy @PriteshKiri , I am a first time contributor , is there any issue i can work on ?

**Comment by PriteshKiri** [comment]
Hey @yuvi-mittal ,

This issue has already been assigned. 

You can check out other open issues under the `community contribution` label. Thanks!

**Comment by GrowwithNaveen** [comment]
Hey @mnshrm  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!
