### ISSUE TITLE
Community template: Student attendance tracker

### ISSUE THREAD

**Issue by GrowwithNaveen** [ToolJet/ToolJet#9927]
**Description:**
This template streamlines student attendance tracking. Maintain attendance records, view course-wise attendance for specific dates, and mark students as present.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1FOiVFH8b9oix3yUh0aVCqI5awsXaeXOQG5ulZbVi0Z4/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within 10 working days and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within 10 working days or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

**Comment by MK884** [comment]
Hii, I would like to work on this template. Can you please assign it to me?

**Comment by karan-rathod-316** [comment]
Sure @MK884, assigning it to you. Happy coding:-)

**Comment by PriteshKiri** [comment]
Thanks for the PR @MK884 . Moved the issue to Testing.

**Comment by GrowwithNaveen** [comment]
Hi @MK884 , Thank you for your excellent work on the template. We've already confirmed that it meets our requirements. We’ll be deploying it shortly and will provide an update once it’s live.

**Comment by MK884** [comment]
Thank you, @GrowwithNaveen , for keeping me updated on the process. I look forward to seeing my contribution go live soon :)

**Comment by GrowwithNaveen** [comment]
Hi @MK884,

We tested the template again and noticed that the TJDB schema is missing. Could you please export the app again with TJDB table schema and update the JSON [in the PR](https://github.com/ToolJet/ToolJet/pull/10023)? Also, it would be helpful if you could share the demo data you used for testing the template.

Thanks in advance!

**Comment by GrowwithNaveen** [comment]
Hey @MK884  ! :tada:
We wanted to take a moment to recognize your fantastic contributions to the ToolJet community templates.

As a token of our appreciation, we’d like to award you the Template Trailblazer badge! You can showcase it on your GitHub profile or dev portfolio via your README file.
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
To add the badge, simply paste the following code into your README file:

```
<div align="left">
  
[![ToolJet Template Trailblazer](https://logo-badges.tooljet.com/Template-Template-Badge.svg)](https://github.com/orgs/ToolJet/projects/16/views/2)

</div>
```


Let the dev community know what you've built!!! :fire:

Feel free to share a screenshot or video of your template, along with details about your template and your experience with the ToolJet platform, in the [#community-showcase](https://tooljet.slack.com/archives/C07TGKLMRDK) channel or on your socials.

Thanks for your contribution!!

**Comment by MK884** [comment]
Thanks @GrowwithNaveen
