### ISSUE TITLE
TJDB: Overlap between the text and the "Null" text, and the custom button remains highlight

### ISSUE THREAD

**Issue by Mekhla-Asopa** [ToolJet/ToolJet#9931]
### What is the expected behaviour?
- The text shouldn’t overlap with the "Null" text
- The Null button should be highlighted.

### What is the current behaviour?
- The text overlaps with the "Null" text
- The Null button isn’t highlighted.

### How to reproduce the issue?

1. Login with valid credentials
2. Create a table add rows
3. Click on the edit row
4. Enter Null value in the field

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/59684099/8132fc36-2985-4f70-9a40-7c826ac1c181

**Comment by Aryanshu919** [comment]
Could you assign this to me? I would like to work on this issue.
