### ISSUE TITLE
Update helper text for password field on reset password page

### ISSUE THREAD

**Issue by ajith-k-v** [ToolJet/ToolJet#9939]
### Steps to reproduce

1. Navigate to the login page.
2. Click on the "Forgot Password" link.
3. Follow the instructions to send a reset password link to your email.
4. Use the link received in the email to access the reset password page.
5. Observe the helper text in the password field on the reset password page.

The text should be `Password should be at least 5 characters`

<img width="465" alt="Screenshot 2024-05-31 at 1 56 58 PM" src="https://github.com/ToolJet/ToolJet/assets/20367957/bf63f899-39e8-4eaf-bc56-71b625dce9b7">

**Comment by jaymehta002** [comment]
I have created a Pull Request #9940 
Review it..

**Comment by karan-rathod-316** [comment]
Hi @jaymehta002, assigning the issue to you and picking up the PR. In future, please get the issue assigned first before going ahead with the PR:-).

**Comment by jaymehta002** [comment]
okay, Thanks

**Comment by frafra** [comment]
@jaymehta002 Stop spamming people by mentioning them randomly, please.
