### ISSUE TITLE
App dashboard - scroll UI 

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#9953]
**Where?**
- Left nav bar 
- Page 

**What to fix?** 
- Dark mode 
- Scroll to be visible and shown only on hover of the container and not constantly (for Chrome and Safari browsers)

<img width="1440" alt="Screenshot 2024-06-03 at 3 04 57 PM" src="https://github.com/ToolJet/ToolJet/assets/127945292/dd076fb6-2416-4ed6-b542-e4b92d31b5d9">

**Comment by Thiru-kumaran-R** [comment]
Can I solve this issue?

**Comment by nechalmaggon** [comment]
Hi @Thiru-kumaran-R thanks for showing interest! Unfortunately, this issue will be solved internally. You can look for issues labelled `up-for-grabs` - those are the ones open for the community!

**Comment by PriteshKiri** [comment]
Sure @Thiru-kumaran-R . Happy coding :)

**Comment by PriteshKiri** [comment]
@Thiru-kumaran-R any updates on this?

**Comment by Thiru-kumaran-R** [comment]
@PriteshKiri  Thank you for assigning this task to me. I am currently in the midst of my semester exams, which will span the next month. I am sorry, but I am unable to work on this project at the moment. I hope you understand.

**Comment by harshit078** [comment]
Hi @PriteshKiri, Can I work on this issue and take it up ?

**Comment by PriteshKiri** [comment]
Assigned @harshit078. Happy coding :)

**Comment by harshit078** [comment]
https://github.com/ToolJet/ToolJet/assets/73997189/7d721bf2-44d6-454b-8599-9a93c0a818f9

Hi, just to clarify I'm not able to repro this issue. Is there something I'm missing ?

**Comment by PriteshKiri** [comment]
Unassigning @harshit078

**Comment by FurquanAnwer** [comment]
@PriteshKiri  Can you assign this issue to me ?

**Comment by PriteshKiri** [comment]
@FurquanAnwer we are refactoring the issue. I will assign you once that is done.

**Comment by PriteshKiri** [comment]
@FurquanAnwer the issue description has been updated. Could you let me know if you are still interested in working on this issue?

**Comment by FurquanAnwer** [comment]
@PriteshKiri yeah sure ! will work on it.

**Comment by PriteshKiri** [comment]
Assigned @FurquanAnwer. Happy coding :)

**Comment by PriteshKiri** [comment]
Hey @FurquanAnwer, any updates on the issue?

**Comment by FurquanAnwer** [comment]
Still working on it, just give a couple of days more. Will raise PR.

**Comment by PriteshKiri** [comment]
Hey @FurquanAnwer, any update on the issue? Please let me know if you have any queries.

**Comment by FurquanAnwer** [comment]
@PriteshKiri I am having issue in setting up tooljet locally in ubuntu. The following command is throwing some error. ---
npm install
npm install --prefix server
npm install --prefix frontend
**npm run build:plugins** ------> This one is throwing error.

This one is where I am stuck. Earlier I was trying to use Windows to locally setup tooljet but didn't work so I switched to ubuntu.

**Comment by PriteshKiri** [comment]
@FurquanAnwer 

Apologies for the delay in reply. Can you please share more details on the errors you are facing with the Windows setup?? 

Feel free to drop your setup issues in our [Slack community](https://tooljet.com/slack). We have a `contributors` channel there.

**Comment by PriteshKiri** [comment]
Hey @FurquanAnwer, 

Could you let me know if you were able to fix the issue?

**Comment by CuriousCoder00** [comment]
If it's yet to be resolved, you can assign it to me. I would love working on it. @PriteshKiri

**Comment by FurquanAnwer** [comment]
I couldn't fix the issue. @Pritesh Kiri you can assign it to someone else.

**Comment by CuriousCoder00** [comment]
Then, May i take it ?? 
You can assign it to me @PriteshKiri

**Comment by PriteshKiri** [comment]
Hey @CuriousCoder00 , We greatly appreciate your interest. However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

We hope you understand our decision and thank you for your understanding.

**Comment by CuriousCoder00** [comment]
@PriteshKiri I understand, But there have been no issues with the label `community contribution`

**Comment by JacksonDynamics** [comment]
@PriteshKiri  I am a new contributor.  This would be my very first open source contribution.  I would like the opportunity to solve this if I can.

**Comment by PriteshKiri** [comment]
@JacksonDynamics  assigned. Happy coding! 😊 

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by PriteshKiri** [comment]
Hey @JacksonDynamics, any updates on the issue?

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress.

**Comment by nikhilbhatia08** [comment]
@PriteshKiri I would like to work on this issue, can you please assign me.

**Comment by nikhilbhatia08** [comment]
https://github.com/user-attachments/assets/4d0fe6b6-0b5f-47bc-b0d3-8f71a56367d3

@PriteshKiri I have added the scrollbar on the left navbar. Please can I raise a PR on this issue.

**Comment by PriteshKiri** [comment]
@nikhilbhatia08 assigning the issue to you. 

You can raise the PR for the same. Please make sure that you test it on both Safari and Chrome before submitting the PR.

**Comment by nikhilbhatia08** [comment]
@PriteshKiri Done for both of the browsers, but in safari the scrollbar shifts the layout. I will try to complete and submit a PR by EOD.

**Comment by nikhilbhatia08** [comment]
PR submitted [#10766](https://github.com/ToolJet/ToolJet/pull/10766). Please have a look sir.

**Comment by PriteshKiri** [comment]
Thanks for your contribution @nikhilbhatia08. Moving the issue to review.

`Quick PR`

Can you please update the PR name to "fix: App dashboard left nav bar scroll issue"

**Comment by nikhilbhatia08** [comment]
@PriteshKiri sir any update on the PR submitted.

**Comment by PriteshKiri** [comment]
Hey @nikhilbhatia08,

The PR is currently under review. It might take some time for the review and merge process.

**Comment by PriteshKiri** [comment]
Unassiging due to lack of progress

This issue is open for contribution now 🙌
