### ISSUE TITLE
Filepicker data passed to POST RestAPI not converted to multipart/form-data

### ISSUE THREAD

**Issue by nicolaphee** [ToolJet/ToolJet#9967]
### Version Information
2.38.0 

### Environment
ToolJet Cloud

### What is the expected behaviour?
Passing a file loaded to a filepicker component to a POST RestAPI query allows one to interrogate such API. 
![image](https://github.com/ToolJet/ToolJet/assets/50681875/73117041-375b-4672-a60a-80ea52808493)

According to the [online documentation](https://docs.tooljet.com/docs/data-sources/restapi/#request-types):
> If a file object from a [FilePicker widget](https://docs.tooljet.com/docs/widgets/file-picker) is set as a value, the body is automatically converted to be sent as a multipart/form-data request.

### What is the current behaviour?
When trying to run a query constructed as above, a Response code 422 (Unprocessable Entity) is return by the server. 

Apparently, Tooljet is currently sending the data in json form without converting it to `multipart/form-data` as stated in the documenattion.  
In fact, attributes of the previewed ToolJet file picker include _name, type, content, parsedData, filePath_ (see screenshot), whereas the API in exam, built using FastAPI's UploadFile class, processes an object having different attributes: file, size, filename, etc. (see [UploadFile class](https://fastapi.tiangolo.com/reference/uploadfile/) docs for a complete list details). 
In addition, the `content-type` header of the Tooljet request is automatically set to `application/json`, even if one enters a different content-type value. 

### How to reproduce the issue?
1. create a filepicker component called `filepicker1` in a Tooljet app 
2. create a RestAPI query sendind a POST request to a server taking a `file` body parameter; for instance, this is a sample API request 
```
curl -X 'POST' \
'https://sample-api-address.com/upload-file' \
-H 'api-key: AAAbbbCCC' \
-H 'Content-Type: multipart/form-data' \
-F 'file=@sample_file.txt;type=text/plain'
```
3. in the RestAPI query, enter a body parameter with `key=file` and `value={{components.filepicker1.file[0]}}`
4. run the RestAPI query

### Screenshots or Screencast
Sample 422 response
![Sample 422 response](https://github.com/ToolJet/ToolJet/assets/50681875/bffc3882-7215-4698-b275-5092c7104e50)

### Any possible solutions?
In [this](https://tooljet.slack.com/archives/C01TY0ZGH6X/p1717083716090509) slack conversation, it was proposed to use a RunJS query to preprocess the data from the filepicker before passing it to the API:
```
const file = {{components.filepicker1.file[0]}};
const formData = new FormData();
formData.append('file', new File([file.content], file.name, { type: file.type }));

fetch('https://sample-api-address.com/upload-file', {
  method: 'POST',
  headers: {
    'api-key': 'AAAbbbCCC',
  },
  body: formData,
})
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.error('Error:', error));
```
However, with such workaround sensitive data such as API key to 3rd party service is exposed.

**Comment by ShazanRizvi** [comment]
Fixed in #9808
