### ISSUE TITLE
(SH-2016) Use double quotes to expand expressions

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#997]
## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ToolJet/ToolJet/issue/SH-2016/occurrences/](https://deepsource.io/gh/ToolJet/ToolJet/issue/SH-2016/occurrences/)

**Comment by Navaneeth-pk** [comment]
Thanks for contributing, assigned the issue.
@raviprasanthgit

**Comment by raviprasanthgit** [comment]
@sparkingdark  this is compeleted and PR is raised already .
